### ISSUE TITLE
The "Help" buttons are wrongly displayed for the "Test Builds" and "QA Status" section even if no text description is provided clicking the "Help" buttons

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1003]
**[Affected versions]:**
- Firefox Release 65.0.2 and above
- Chrome 72.0.3626.109

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an experiment created on the "https://experimenter.stage.mozaws.net/" website.
- You are logged in your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites and click the "Edit" button from "Risk" section.
3. Observe the blue "Help" buttons for the "Test Builds" and "QA Status" section.

**[Expected result]:**
- No "Help" buttons are displayed.

**[Actual result]:**
- The "Help" buttons are displayed.

**[Notes]:**
- Attached is a screen shot of the issue:
![help](https://user-images.githubusercontent.com/40061643/53748326-d082ad00-3ead-11e9-8da8-9c0bb76a8070.PNG)

**Comment by Softvision-RemusDranca** [comment]
I have retested this issue with the new stage deployment (v2.25.0) and it seems that it is also reproducible for the "Technical Risks Description" field. The "Help" button is displayed even if no text description is available.
Attached is a screen shot of the "Technical Risks Description" field:
![capture](https://user-images.githubusercontent.com/40061643/53822965-72bb9700-3f79-11e9-9230-03c2b8312309.PNG)

**Comment by shell1** [comment]
:) this is another good catch - but we know a lot of this is inconsistent and we need to clean up help button, in box content, link to mana throughout the product.  we will cover this in the UX review.  

I'm closing this for now - and putting the note in the UX review form referencing this closed issue so we can check fix based on all the changes coming between now and Whistler.
