### ISSUE TITLE
Main experimenter page causing Slow DB Query

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#10032]
Sentry Issue: [EXPERIMENTER-PROD-M4](https://mozilla.sentry.io/issues/4848779503/?referrer=jira_integration)

|----|----|
|**Offending Spans**|db - SELECT "experiments_nimbusexperiment"."id"...|

Issue source main page of [https://experimenter.services.mozilla.com/nimbus/](https://experimenter.services.mozilla.com/nimbus/) .

Issue: we are loading too many experiments and requesting too much data from the server

Side-effect: slow loading experiments list

Proposed Solutions:

* Add pagination to each tab (Live, Review, Preview, Completed…)
* Fetch each tab independently
* Limit the amount of data we are fetching by creating a new endpoint or editing the endpoint in it is not used anywhere else. 
  * Add pagination to each tab (Live, Review, Preview, Completed…)
  * Fetch each tab independently
  * Limit the amount of data we are fetching by creating a new endpoint or editing the endpoint in it is not used anywhere else. Here are some examples:
    * I am only seeing the name of the feature in the UI grid, yet the server is returning:
`"featureConfigs":[{"id":81,"slug":"featureCallout","name":"featureCallout","description":"A Firefox Messaging System message for the Feature Callout message channel","application":"DESKTOP","ownerEmail":null,"__typename":"NimbusFeatureConfigType"}],`
    * I am not seeing any targeting info in the UI grid but targeting is returned:

`"targetingConfig":[{"label":"Early day user (less than 28 days)","value":"early_day_user_v2","description":"Users with profiles that are less than 28 days old","applicationValues":["DESKTOP"],"stickyRequired":true,"isFirstRunRequired":false,"__typename":"NimbusExperimentTargetingConfigTyp`

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-4189)

**Comment by jaredlockhart** [comment]
Yes those analyses are all correct, but I think the offending field here is `qa_comments` which is included in the `getAllExperiments` query and yet is not used by the table.  We can probably remove that field and that should clear up this particular regression.

**Comment by jaredlockhart** [comment]
And in theory as part of that fix we could do a more exhaustive check on every field that's included in the `getAllExperiments` query and remove all the fields that aren't being used.  Theoretically typescript should help us here by just commenting out all the fields on [the auto generated type](https://github.com/mozilla/experimenter/blob/main/experimenter/experimenter/nimbus-ui/src/types/getAllExperiments.ts#L43-L77) and then running and rerunning the typechecker until it passes with the minimum set of fields necessary for that page to work.  There may be some fields used that typescript won't catch so you'll probably also have to manually verify on your local that it's intact, but paring out as many of those fields as we can should be an easy way to speed up the initial load.

**Comment by data-sync-user** [comment]
➤ Elise Richards commented:

PR to remove qa_comment from the query: https://github.com/mozilla/experimenter/pull/10039 ( https://github.com/mozilla/experimenter/pull/10039|smart-link )

**Comment by data-sync-user** [comment]
➤ Elise Richards commented:

I’m down for doing those typescript improvements. I’ll split that into a separate ticket 👍

**Comment by data-sync-user** [comment]
➤ Elise Richards commented:

https://mozilla-hub.atlassian.net/browse/EXP-4202 ( https://mozilla-hub.atlassian.net/browse/EXP-4202|smart-link )
