### ISSUE TITLE
"Risks" details is hard to read - group the question/response better

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#1004]
* Unless your eyes/focus is on the first or last item, it's not sure which Yes/No goes with which question, 
* Normally green is the "universal" color for "yes" and red for "no". (Also, we could consider using emojis/unicode characters that look like checkboxes/crosses) 

<img width="967" alt="screen shot 2019-03-04 at 2 51 01 pm" src="https://user-images.githubusercontent.com/26739/53758928-21ce7480-3e8d-11e9-925e-ff38b406426c.png">

**Comment by shell1** [comment]
Let's stick with the "Yes"=red convention.  In this case it's a risk assessment and a "Yes" answer for this process has always been the risky answer.  All questions are phrased so Yes=risky=red.

I totally agree on the "which answer goes with which question".  This will get worse when we expand the list.  Putting this bug to match the question/answer more clearly into the v3 milestone (same line? spaces between question/answer pairs?).
