### ISSUE TITLE
make schemas_lint has incorrect instructions when lint fails

### ISSUE THREAD

**Issue by brennie** [mozilla/experimenter#10080]
When you run `make schemas_lint` and the schemas have changed, you get the following error:

```
nimbus-schemas typescript package is out of sync please run make schemas_build
make: *** [Makefile:297: schemas_lint] Error 1
```

However, `make schemas_build` does not regenerate the typescript. That is done by `make schemas_dist_npm` (or `make schemas_dist`).

We should move the `schemas_dist` task into `schemas_build` to fix this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4239)

**Comment by mikewilli** [comment]
We should also verify that the README and CI are correct after any changes.
