### ISSUE TITLE
Hide branch options for rollouts

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#10092]
Rollouts only have a single branch, so they will appear as two options

* Rollout (All Branches)
* Rollout (control branch)

These two are synonymous, so let’s remove one of those.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4244)

**Comment by jaredlockhart** [comment]
Whoops tagged the wrong issue, fixed in https://github.com/mozilla/experimenter/pull/10117
