### ISSUE TITLE
The ask-experimenter Slack channel is not opened when the "#ask-experimenter on Slack" button is clicked

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1011]
**[Affected versions]:**
- Firefox Release 65.0.2 and above
- Chrome 72.0.3626.121

**[Affected Platforms]:** 	 	
- All Windows
- All Mac 	 	
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Click the "#ask-experimenter on Slack" button and observe the behavior.

**[Expected result]:**
- Slack app not installed: The Slack website is opened on the #ask-experimenter Slack channel.
- Slack app installed: The Slack app is opened on the #ask-experimenter Slack channel.

**[Actual result]:**
- Slack app not installed: You are redirected to the "The address wasn’t understood" page.
- Slack app installed: The Slack app is opened but not on the #ask-experimenter Slack channel.

**[Notes]:**
- This issue is reproducible even if Slack is opened in the browser.
- This issue is also reproducible if you previously joined the #ask-experimenter Slack channel.
- On Chrome if the "#ask-experimenter on Slack " button is clicked and the Slack app is not installed, nothing happens.
- I could not verify the behavior when the Slack app is installed on Linux, because I wasn't able to install the app.
- Attached are screen recordings of the issue:
  - Slack app not installed:
![askexperimenter](https://user-images.githubusercontent.com/40061643/53820838-4271f980-3f75-11e9-820f-5317682b1a16.gif)

  - Slack app installed:
![appaskexperimenter](https://user-images.githubusercontent.com/40061643/53820862-4e5dbb80-3f75-11e9-91bc-8518612340cd.gif)

**Comment by mostlygeek** [comment]
It appears the slack link requres a `team_id`, ours is: `T027LFU12`.

**Comment by shell1** [comment]
If this is anything other than dead simple to fix - I'm 100% fine with that "#ask-experimenter in slack" not linking to open directly.  It's entirely a nicety.  People knowing the channel is the requirement - and the wording alone covers that perfectly.  Folks can get themselves to slack and find that channel.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's partially fixed on the https://experimenter.stage.mozaws.net/ website after the (v2.25.1) deployment:
- The issue is no longer reproducible if the Slack app is installed. The #ask-experimenter Slack channel is automatically opened after clicking the "#ask-experimenter on Slack" button.
- The issue is still reproducible if the Slack app is NOT installed. You are redirected to the "The address wasn’t understood" page after clicking the "#ask-experimenter on Slack" button.
Considering this I will reopen this issue.

**Comment by mostlygeek** [comment]
Let's just unlink it as @shell1 recommended.

**Comment by shell1** [comment]
I'm closing this ticket as is - 100% fine with this behavior.   it if works with the app installed great.  If not, and folks can figure out how to manually type it very easily from context.
