### ISSUE TITLE
Rename "User Journey + Messaging" team project

### ISSUE THREAD

**Issue by aminomancer** [mozilla/experimenter#10177]
Can we change one of the "Team Projects" for experimenter? There's a [Team Projects field](https://github.com/mozilla/experimenter/blob/2779e9dfd5382801666672433721d9f054ba3d58/experimenter/experimenter/nimbus-ui/src/components/FormOverview/index.tsx#L254), and the "User Journey + Messaging" project name for that field is outdated. Can we change it to `Onboarding, Messaging, and Communications`

Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4302)

**Comment by shell1** [comment]
I renamed it while I was in there changing the project name for the Search team.

**Comment by shell1** [comment]
done

**Comment by yashikakhurana** [comment]
oh @shell just renaming it won't work

**Comment by shell** [comment]
I see you encountered my nickname sibling 🙂 I wonder how many of us out there

**Comment by shell1** [comment]
oooh - it won't?  I can see it showing differently in the drop down.  does it need to change elsewhere?

I will need to do for "search and suggest" as well (changed from original "search" only)

**Comment by yashikakhurana** [comment]
if that's the big name change, for sure you can see that updated, but filtering won't work on top of that
