### ISSUE TITLE
When cloning a delivery that targets a specific branch, the clone targets all branches

### ISSUE THREAD

**Issue by danielkberry** [mozilla/experimenter#10187]
When cloning a delivery that targets a specific branch, the clone targets all branches of the targeted delivery. For example, a delivery with a targeting expression of `(enrollmentsMap['test-555-copy'] == 'control')` when cloned, the clone will have a targeting expression of `('test-555-copy' in enrollments)`. 

Expected Behavior: the clone has the same targeting as the original. 

Actual Behavior: the clone's targeting is modified to be any branch of the original. 

https://github.com/mozilla/experimenter/assets/2738595/9b692d1b-7569-4d7a-971b-61adeef6f2c1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4312)

**Comment by jaredlockhart** [comment]
Oh my god, I *ALWAYS* forget to update the clone method 😖
