### ISSUE TITLE
Clicking "Save and Continue" on the Branches page after already saving throws an error

### ISSUE THREAD

**Issue by danielkberry** [mozilla/experimenter#10185]
When clicking "Save and Continue" on the Branches page after previously pressing "Save", a `You are trying to swap branch names. Please choose another name for the branches.` error is thrown. 

Expected Behavior: 
The page is saved and progresses to the Metrics page. 

Actual Behavior: 
An error is generated and the user remains on the Branches page. 

<img width="1509" alt="Screenshot 2024-01-31 at 2 10 12 PM" src="https://github.com/mozilla/experimenter/assets/2738595/3de69a1b-7a84-4032-af44-2afa2e22b01e">

https://github.com/mozilla/experimenter/assets/2738595/c13084c2-ceb5-4fe0-8a8b-bfa3375004d9

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4310)

**Comment by jaredlockhart** [comment]
We're in the process of rewriting these forms into HTMX anyways so it's not worth fixing in the React UI.  We'll just close this.
