### ISSUE TITLE
The Overview section UI shifts when attempting to subscribe/unsubscribe from archived experiments

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#10230]
**[Prerequisites]:**

* Have an archived Nimbus experiment's page opened.

**[Steps to reproduce]:**

1. Scroll down to the Overview section of the Summary page.
1. Click the "Subscribe"/"Unsubscribe" button and observe the UI.

**[Expected result]:**

* The "Subscribers can't be updated while an experiment is archived" warning is displayed.

**[Actual result]:**

* The UI is shifted when the warning notification is displayed.

**[Notes]:**

* The issue is reproducible regardless of the screen size/browser window size.
* Attached a screen recording of the issue:

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-4344)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/56952">subscribe_UI.gif</a>

**Comment by eliserichards** [comment]
We can mitigate this by removing the button when experiments are archived. I'll double-check that there isn't a reason to keep the button (I know subscribing to notifications has been used as a way to filter by "my" experiments in the past, so maybe it would act like a kind of bookmark and we want to keep this for Archived experiments?)

**Comment by data-sync-user** [comment]
➤ Elise Richards commented:

PR: https://github.com/mozilla/experimenter/pull/10241 ( https://github.com/mozilla/experimenter/pull/10241|smart-link )

**Comment by data-sync-user** [comment]
➤ Patriciu Pop commented:

I’ve verified that the issue is no longer reproducible, the Subscribe/Unsubscribe buttons are no longer available on archived experiments. Thank you Elise!
