### ISSUE TITLE
manifest-tool fetch job should report failures first in PRs

### ISSUE THREAD

**Issue by yashikakhurana** [mozilla/experimenter#10264]
Recently we saw that when the bot was not able to fetch FML from the VPN, the job ran successfully, but instead, it should have failed. https://github.com/mozilla/experimenter/pull/10263

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4364)

**Comment by brennie** [comment]
Actually this is behaving as intended. If there are any failures, they get reported in the PR description. I guess they should probably move to the top of the list so theyre more visible
