### ISSUE TITLE
Comments can wrongly be saved if only empty spaces are inserted in the input field

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1028]
**[Affected versions]:**
- Firefox Release 65.0.2 and above
- Chrome 72.0.3626.121

**[Affected Platforms]:** 	 	
- All Windows
- All Mac 	 	
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.
- Have an experiment created on the Experimenter stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the created experiment from prerequisites.
3. Click the "+ Add Comment" button from the "Overview" section.
2. Insert an empty space in the input field.
5. Click the "Save Comment" button and observe the behavior.

**[Expected result]:**
- The "Please fill out this field" message is displayed.

**[Actual result]:**
- The comment is saved but not validated.

**[Notes]:**
- This issue is reproducible for all the sections where  the "Add comment" option is available.
- Attached is a screen recording of the issue:
![addcomment](https://user-images.githubusercontent.com/40061643/54021416-ca841900-4198-11e9-8433-d3f69b5bc468.gif)

**Comment by shell1** [comment]
it's not saving in Stage, so no longer reproducable.  I'm almost OK if this happens once in a while too.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible on Experimenter stage "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
Tested on Windows 10 x64, Mac 10.14 and Arch Linux 4.16.6 x64.
