### ISSUE TITLE
The branch size can wrongly be saved with whole numbers larger or smaller than 100

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1030]
**[Affected versions]:**
- Firefox Release 65.0.2 and above
- Chrome 72.0.3626.121

**[Affected Platforms]:** 	 	
- All Windows
- All Mac 	 	
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.
- Have an experiment created on the Experimenter stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the created experiment from prerequisites.
3. Click the "Edit" button from "Branches" section.
4. Enter a whole number larger or smaller than 100 in the "Branch Size" input field.
5. Click the "Save Draft" button and observe the behavior.

**[Expected result]:**
- The "! The size of all branches must add up to 100 " error message is displayed.

**[Actual result]:**
- The draft is saved.

**[Notes]:**
- This issue is also reproducible if multiple Branches are created and saved with different branch sizes.  The entered numbers sum can result in values smaller or larger than 100.
- Attached is a screen recording of the issue:
![branchsize](https://user-images.githubusercontent.com/40061643/54032051-35454c80-41b9-11e9-8171-377d5538bc6b.gif)

**Comment by peterbe** [comment]
The explanation is that `ExperimentVariantsPrefFormSet.clean`  doesn't do the same `total_percentage` validation that `ExperimentVariantsFormSet.clean` does.

**Comment by jaredkerim** [comment]
@peterbe Oh you're too fast! I didn't see you picked this up, I already submitted a pr.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible on the "https://experimenter.stage.mozaws.net/" website after the (v2.25.1) deployment.
Tested on Windows 10x64, MacOS 10.14 and Arch Linux 4.16.6 x64.
