### ISSUE TITLE
An experiment can wrongly be saved without completing the "Population Filtering", "Objectives" and "Analysis Plan" sections

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1035]
**[Affected versions]:**
- Firefox Release 65.0.2 and above
- Chrome 72.0.3626.121

**[Affected Platforms]:** 	 	
- All Windows
- All Mac 	 	
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.
- Have a draft created with the "Overview" section completed and saved.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the created experiment from prerequisites.
3. Click the "Edit" button from "Objectives" section.
4. Insert a name in the "Data Science Owner" input field.
5. Click the "Save Draft" button and observe the behavior.

**[Expected result]:**
- An error message that informs the user that the "Objectives" and "Analysis Plan" sections must be completed is displayed.

**[Actual result]:**
- The experiment is saved. 

**[Notes]:**
- This issue is not reproducible if the the default text from the input field is deleted. If the experiment is saved with an empty input field, the "Please fill up this field" tool-tip is displayed. 
- After the experiment is saved without editing the "Objectives" and "Analysis Plan" sections, they appear incomplete on the main page of the experiment witch blocks the experiment to go in the "Ready to Ship" state. 
- However, when the experiment is saved without editing the "Population Filtering" section, the "Population" sections is displayed as completed on the main page of the experiment. 
- Attached is a screen recording of the issue:
![SaveNot](https://user-images.githubusercontent.com/40061643/54133005-f401a680-441d-11e9-8383-6662c7b4c7e8.gif)

**Comment by jaredkerim** [comment]
This is now the desired behaviour.
