### ISSUE TITLE
 Checklist Question 5: Is this a long running experiment, that will span across 3 or more Firefox versions

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1036]
"Yes" radial button selection for this question - should make ________(TBD) required. Required means they need to check it before they can click "ready for shipping".

Help for this question should take them to the risks section. https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-Risk

The help next to the actual checklist item should go to the main Dependent section. Linking to the section instead of the specific action, avoids future name changes breaking the header link. https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-DependentSign-offs

**Comment by shell1** [comment]
For now this doesn't add any dynamic checklist item.  It is critical that it links to the help.  we will make a filter based off "yes" answers - so QA can do a simple filter on all experiments that are flagged "will span across firefox versions".

**Comment by jaredkerim** [comment]
@shell1 If we add the minimum and maximum firefox versions we'll automatically know this, do we also need to make this a risk checkbox?  If we make it a separate risk checkbox there's the possibility that it could become out of sync with what the min/max firefox version fields show?

**Comment by shell1** [comment]
great point - better to auto create - one less quesiton
