### ISSUE TITLE
Replace FontAwesome w/ static SVGs?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#1039]
Ref: #965

> It still hurts my soul to have 18.3MB worth of static files into the git repo. Espectially those tonnes of svgs that we know we don't use.

---

Currently, it looks like FontAwesome loads 12.7 KB of CSS and 66.1 KB of .woff2 files:

- [/static/lib/fontawesome/css/all.css](https://experimenter.services.mozilla.com/static/lib/fontawesome/css/all.csshttps://experimenter.services.mozilla.com/static/lib/fontawesome/css/all.css) &ndash; 12.7 KB
- [/static/lib/fontawesome/webfonts/fa-solid-900.woff2](https://experimenter.services.mozilla.com/static/lib/fontawesome/webfonts/fa-solid-900.woff2) &ndash; 66.1 KB

**Comment by jaredlockhart** [comment]
It's not hurting anybody (except peter), so I'll just close this until it blows up in our face.
