### ISSUE TITLE
Please add new application support to experimenter for Accounts

### ISSUE THREAD

**Issue by clouserw** [mozilla/experimenter#10393]
Please let me know if you need any more detail here.  This is a line item on the checklist.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4408)

**Comment by yashikakhurana** [comment]
sure can you add a link for probe scraper PR here, once its get merged I would be able to start working on this

**Comment by clouserw** [comment]
The directions said file a ticket, so, I did @ https://bugzilla.mozilla.org/show_bug.cgi?id=1884795
