### ISSUE TITLE
The Inclusion/Exclusion experiment fields display the selected filters after a short delay

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#10403]
**[Prerequisites]:**

* Have Nimbus experiment created with an Audience filter that requires and excludes experiments.

**[Steps to reproduce]:**

1. Open the experiment's Audience page or refresh it, if it's already opened.
1. Observe the "Exclude users enrolled in these experiments/rollouts" and "Require users to be enrolled in these experiments/rollouts (past or present)" fields.

**[Expected result]:**

* The selected required/excluded experiments are displayed in the field.

**[Actual result]:**

* The fields are empty and the data is displayed after a ~6s delay

**[Notes]:**

* The fields are also empty and new experiments cannot be selected until the delay passes and the dropdown is loaded.
* Attached a screen recording of the issue:

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-4414)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/59977">filters_displayed_after_delay.gif</a>

**Comment by brennie** [comment]
We should probably put a spinner or loading indicator for that field before its loaded. I don't know that we can work around this performance wise because its a gql query for all experiments on a given application, and graphene spends a lot of time generating that.

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

All this UI will be replaced soon anyways so it’s not worth investing much more time in if it meets the basic needs, closing this as wontfix.
