### ISSUE TITLE
Update Cirrus checklist Glean instructions

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#10413]
Cirrus setup checklist includes a section for filing PRs against Glean probe scraper, however this should be done by filing a DO ticket with the necessary information rather than filing a PR directly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4415)

**Comment by data-sync-user** [comment]
➤ Yashika Khurana commented:

Updated checklist with the following info- 

  * File a DO (Data org) ticket with the necessary information
    * File a bug following the Glean docs - https://mozilla.github.io/glean/book/user/adding-glean-to-your-project/enable-data-ingestion.html#add-your-product-to-probe-scraper ( https://mozilla.github.io/glean/book/user/adding-glean-to-your-project/enable-data-ingestion.html#add-your-product-to-probe-scraper|smart-link ) 
    * Pick the application id as described above
    * Call out that this is for a Nimbus / Cirrus Sidecar
    * Have the Glean app depend on "glean-core" and "nimbus-cirrus" (to be noted in the dependencies section when filing a bug).
    * Don't add any metrics or ping files, as this is not required for the sidecar (the right dependencies are already included)
