### ISSUE TITLE
Sorting by channel ascending or descending does not sort experiments correctly

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#1042]
**[Affected versions]:**
- Firefox Release 65.0.2 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac 	 	
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Click the "Sort Experiments" drop down and select the "Firefox Channel Ascending" option.
3. Scroll down the page and observe the experiment channels.
4. Repeat Step 3 for all pages.

**[Expected result]:**
- Experiments are ordered in the following way Firefox - Release Firefox - Beta Firefox - Nightly Firefox.
**OR**
- Experiments are ordered in the following way Nightly Firefox - Beta Firefox - Release Firefox - Firefox.

**[Actual result]:**
- Experiments are ordered in the following way Firefox - Beta Firefox - Nighty Firefox - Release Firefox.

**[Notes]:**
- The issue is reproducible with the "Firefox Channel Descending" option as well, but in this case the order is Release - Nightly - Beta - Firefox.
- Attached is a screen recording of the issue: [Link](https://drive.google.com/open?id=1VdTtNV-Vo2SnvHVXs630Gmz3xtV8gJcm)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible on Experimenter stage "https://stage.experimenter.nonprod.dataops.mozgcp.net" website after the v2.28.0 stage deployment.
Tested on Windows 10x64, Mac 10.14 and Arch Linux 4.16.6 x64.
