### ISSUE TITLE
The branches input fields are not validated after the fields are unfocused if no value is inserted

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1044]
**[Affected versions]:**
- Firefox Release 65.0.2 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac 	 	
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.
- Have an experiment created on the Experimenter stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the created experiment from prerequisites.
3. Click the "Edit" button from "Branches" section.
4. Delete the value from one of the input fields from "Control Branch".
5. Click outside the input field's boundary and observe the behavior.
6. Hover over the input field and observe the behavior.

**[Expected result]:**
- Step 5: The input field's boundary turns red.
- Step 6: The "Please fill out this field" tool-tip is displayed.

**[Actual result]:**
- Step 5: The input field's boundary color remains unchanged. 
- Step 6: No tool-tip is displayed.

**[Notes]:**
- This issue is reproducible for all branches input fields.
- This issue is also reproducible when a field has no value and the experiment is saved. After the value from a different branch input field value is deleted and the same field is unfocused, the boundaries of that field remain green and also on hover, no tool-tip is displayed.
- Attached is a screen recording of the issue:
![noValidation](https://user-images.githubusercontent.com/40061643/54370796-eef06180-4680-11e9-9ccf-8460dc7a6ec7.gif)

**Comment by jaredkerim** [comment]
Good catch but we're just gonna close this as a wontfix per @shell1
