### ISSUE TITLE
The "Pref value" filed is not validated if other fields have invalid values when the experiment is saved

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1045]
**[Affected versions]:**
- Firefox Release 65.0.2 and above
- Chrome 72.0.3626.121

**[Affected Platforms]:** 	 	
- All Windows
- All Mac 	 	
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.
- Have an Pref-Flip Study experiment created on the Experimenter stage website.
- Have a branch created with the "Pref Type" set to "boolean".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the created experiment from prerequisites.
3. Click the "Edit" button from "Branches" section.
4. Insert an invalid value in the "Pref value" input field (eg.: 43543).
5. Delete the value from the "Branch Size" input field.
6. Click the "Save Draft" button and observe the behavior.

**[Expected result]:**
- Error messages are displayed for both input fields.

**[Actual result]:**
- Only the error message for the input field where the value was deleted (Step 5) is displayed.

**[Notes]:**
- This issue is not reproducible if all other input fields are completed with valid data. When the "Save Draft" button is clicked the error message is displayed.
- This issue is not reproducible if a invalid JSON value is inserted in the "Pref value" input field.
- Attached is a screen recording of the issue:
![noError](https://user-images.githubusercontent.com/40061643/54376706-4e07a380-468c-11e9-97f4-3ff8a32bf38d.gif)

**Comment by jaredkerim** [comment]
It does the validation in two stages, which is kind of annoying but this is a wontfix since eventually it gets it right ;)
