### ISSUE TITLE
Only two fields are marked as mandatory when an empty "Population" page is saved

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#1046]
**[Affected versions]:**
- Firefox Release 65.0.2 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac 	 	
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Click the "Create Experiment" button.
3. Fill out all the mandatory fields with valid values.
4. Click the "Save Draft and Continue" button.
5. Click the "Save Draft" button and observe the behavior.
6. Select a channel and a version.
7. Click the "Save Draft" button again and observe the behavior.

**[Expected result]:**
- Step 5: All mandatory fields are marked.

**[Actual result]:**
- Step 5: Only the "Firefox Channel" and "Firefox Version" fields are marked as mandatory.
- Step 7: Five more fields are marked as mandatory.

**[Notes]:**
- Attached is a screen recording of the issue: [Link](https://drive.google.com/open?id=1CWlwgT_kw8pUMs3YrGZXKnY_z6x-x7lG)

**Comment by jaredkerim** [comment]
This is being handled by #902
