### ISSUE TITLE
Simplify docker image building

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#10546]
Right now we selectively build our docker images. This is a problem as there seem to have been some changes made to how the script reports and the builds are no longer working correctly. Lets just build each week.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4467)

**Comment by brennie** [comment]
What do you mean when you say "build each week"? We build our docker images on demand based on Makefile targets and requirements.
