### ISSUE TITLE
Display comparison-to-branch when viewing results compared to a non-control branch

### ISSUE THREAD

**Issue by danielkberry** [mozilla/experimenter#10583]
In the confidence interval portion of the results UI, all CIs are marked with a location at zero labeled "control" (green ovals in the below example). However, point represents the comparison-to-branch, not necessarily the control branch. Can we update so that this uses the value of the Reference Branch? In this example, that would be "treatment-a". 

<img width="1486" alt="Screenshot 2024-04-16 at 11 41 37 AM" src="https://github.com/mozilla/experimenter/assets/2738595/d6610fdb-9412-45c3-90c9-38b2b6ddb8c7">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4476)

**Comment by mikewilli** [comment]
Making sure I understand the request -- the data and visualization are correct, but we want **control** to read, in this example, **treatment-a**? Or are both the data and the labeling wrong?

**Comment by danielkberry** [comment]
Data & viz are correct, I just think it would be more clear if the label on the CI was updated. Something like this:
 
<img width="1486" alt="Screenshot 2024-04-16 at 11 41 37 AM" src="https://github.com/mozilla/experimenter/assets/2738595/d05c8f2f-4d3b-4902-b9f5-7768e00d0453">
