### ISSUE TITLE
Update our docker-compose files to use depends_on 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#10592]
`links` have been [EOL](https://docs.docker.com/network/links/) for a while now, we should switch to using `depends_on` instead. I found this out by using an open source docker replacement named `podman`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4478)

**Comment by jaredlockhart** [comment]
Docs here https://docs.docker.com/compose/compose-file/05-services/#depends_on
