### ISSUE TITLE
Pagination is broken on search-limited pages

### ISSUE THREAD

**Issue by lizzard** [mozilla/experimenter#1063]
When I limit the experiments by version, for example in https://experimenter.services.mozilla.com/?ordering=-latest_change&type=&status=&firefox_channel=&firefox_version=66.0&project=&owner=  giving 13 results, pagination breaks (clicking on page 2 or next brings me to page 2 of the full list of 77 experiments).

**Comment by jaredkerim** [comment]
@lizzard Your timing is impeccable, we just deployed the [fix](https://github.com/mozilla/experimenter/issues/596) for this yesterday!  Double check that again on prod and see if you can reproduce it.

**Comment by lizzard** [comment]
Verified!

**Comment by jaredkerim** [comment]
Fixed by https://github.com/mozilla/experimenter/issues/596
