### ISSUE TITLE
Make a Whatsdeployed link

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#1065]
[Now that `/__version__` should be exposed. ](https://github.com/mozilla-services/cloudops-deployment/pull/3020)

**Comment by peterbe** [comment]
This includes making a link from this projects README. E.g. https://github.com/mozilla/delivery-console/#delivery-console

**Comment by mythmon** [comment]
This link is configured for Experimenter, but it doesn't seem like the change from mozilla-services/cloudops-deployment#3020 has gone through yet: https://whatsdeployed.io/s/utG/mozilla/experimenter

**Comment by peterbe** [comment]
I don't know what the exact intentions were but on Slack you pointed out https://whatsdeployed.io/s/uFe/mozilla/experimenter which is now fully working.
