### ISSUE TITLE
"Locales" and "Geographic regions" shouldn't be in client matching textarea

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#1067]
Those two blocks should be done with drop-downs now. 
<img width="941" alt="Screen Shot 2019-03-18 at 3 39 57 PM" src="https://user-images.githubusercontent.com/26739/54559591-c2955780-4996-11e9-942c-00c51068c45d.png">

**Comment by jaredkerim** [comment]
Yes you're right, that is confusing! We should definitely remove that.
