### ISSUE TITLE
BugzillaURLField should use settings.BUGZILLA_HOST

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#1069]
See the code: https://github.com/mozilla/experimenter/blob/46d9fdbafc0cd0adc70fa2ebd724b598178918fe/app/experimenter/experiments/forms.py#L40-L52
it hardcodes the string `"https://bugzilla.mozilla.org/"`. 

In my `.env` I use `BUGZILLA_HOST=bugzilla-dev.allizom.org` because I want to make absolutely sure that my local testing doesn't accidentally update any real bugs. 

<img width="940" alt="Screen Shot 2019-03-18 at 3 39 18 PM" src="https://user-images.githubusercontent.com/26739/54560418-b6aa9500-4998-11e9-94fc-0ba9bb2d2489.png">

Also, this "hardcodedness" would prevent use of `https://bugzil.la`. [For example](https://gist.github.com/kyoshino/6408622)

**Comment by jaredkerim** [comment]
@peterbe The Bugzilla URLs that are entered by the user are never written to or modified, currently, they're just stored and linked to on the detail page.  If that behaviour changes, we will definitely have to revisit this.  I'll leave it open in the backlog so we can refer to it.

**Comment by jaredkerim** [comment]
This is fixed now.
