### ISSUE TITLE
Check for missing migrations in `make check`

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1079]
When we run `make check` we should also check that no migrations should have been created that were missed.

**Comment by jaredkerim** [comment]
Looks like we can do `python manage.py makemigrations --check` and it will raise non-zero exit if it creates a migration.

**Comment by mythmon** [comment]
Prior art in the form of a Normandy PR to do the same thing: https://github.com/mozilla/normandy/pull/1591
