### ISSUE TITLE
New comment is multiplied for each click action on the "Save Comment" button

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1095]
**[Notes]:**
- Normally we consider multiple clicks issues to be minor ones due to edginess. However, considering the fact that you can have a short break between clicks until the page is refreshed and comment posted, makes this issue more easy to be encountered by users with slow connection. I think that this issue was already encountered on this [experiment](https://experimenter.services.mozilla.com/experiments/firefox-quantum-bar-experiment-1-xul-vs-html/#comment104 ), in production.   

**[Affected versions]:**
- Firefox Release 66.0 and above
- Chrome 73.0.3683.75

**[Affected Platforms]:** 	 	
- All Windows
- All Mac 	 	
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.
- Have an experiment created on the "https://experimenter.stage.mozaws.net/" website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the created experiment from prerequisites.
3. Click the "Add Comment" button from "Overview" section.
4. Insert a string in the "Add Comment" input field.
5. Click the "Save Comment" button two times or more and observe the behavior.

**[Expected result]:**
- One comment is saved and displayed.

**[Actual result]:**
- The same comment is saved and multiplied for each click action.

**[Additional Notes]:**
- This issue is reproducible for all the sections where the "Add comment" option is available.
- Attached is a screen recording of the issue:
![CommentsMultiply](https://user-images.githubusercontent.com/40061643/54764207-ff17bc00-4bff-11e9-9afa-a01e413c4141.gif)

**Comment by jaredkerim** [comment]
The fastest click in the west!  Good find but this is edge casey enough that we're just gonna close it.
