### ISSUE TITLE
Conflict between experimenter population % for VP signoff and % argument to pass to Normandy

### ISSUE THREAD

**Issue by jtg567** [mozilla/experimenter#1096]
As a tool for manual normandy recipe launchers, experimenter serves as a placeholder for values that are agreed upon to feed forward into the recipe launch process. The population % on experimenter currently maps 1:1 with what is used on normandy.

As a tool for Fx stakeholders, experimenter serves as a historical paper trail to document the decisions made in an experiment's launch. Recently we have realized that passing >1% of release as the population parameter doesn't necessarily net that proportion of eligible enrollments for an experiment after applying additional filtering criteria. That is, less than 1% may actually be targeted for a study effectively negating the risk that VP sign-off was intended to assuage. As such, the population % on experimenter can be an over-estimate of the final % of the audience affected

**Ideally, experimenter would represent not only the gross % that is used to perform sampling via normandy, but also an estimate of the final net % after filtering to give stakeholders a realistic size of the audience being affected ultimately. Presumably this would be another required field in the model, possibly with another required field to reference an external doc for substantiating power/sample size decisions.**

**Comment by jaredlockhart** [comment]
I think this can be solved by https://github.com/mozilla/experimenter/issues/2359 so closing this as a duplicate.
