### ISSUE TITLE
[Intermittent]  The user prefs set by an experiment are not removed after disabling the experiment’s recipe

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#10989]
**[Affected versions]:**

* Firefox build version: Firefox Beta 129.0b1, Build ID: 20240708194140

**[Affected Platforms]:**

* Windows 10 x64;
* macOS 14.3/14.5

* Linux Mint 21.2

**[Prerequisites]:**

* Have access to the Nimbus console.

* Have a launched desktop experiment created with a user pref not registered in the “about:config” page using the prefFlips feature configuration.

* Set up the latest Firefox Beta to point to the Stage server and set the “messaging-system.log” pref to “all” value.

**[Steps to reproduce]:**

1. Enroll in the newly created experiment.

1. Have a colleague with access to Nimbus click the “End experiment” button from the Experimenter page.

1. Approve the changes on the Experimenter page.

1. Approve the changes in the Remote Settings Writer and wait for the experiment to be completed.

1. Restart the browser.

1. Go to the “about:config” page and search for the pref that was set by the experiment.

**[Expected result]:**

* The pref set by the experiment cannot be found after the experiment was disabled since it wasn’t previously registered in the “about:config”.

**[Actual result]:**

* The pref set by the experiment is displayed in the “about:config” page having the same value.

**[Notes]:**

* This issue is reproducible only with experiments having preferences that are not registered in the “about:config” page already.

* This issue is also reproducible if the Stage collection is changed to another collection (e.g.: Prod collection).

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-4689)

**Comment by brennie** [comment]
This is a bug in Firefox.
