### ISSUE TITLE
Hard to get back to experiment overview

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#1099]
If you clicked on any of the "Edit" links from the experiment overview you edit up on an edit page. E.g. "Population". From there, the only way back is to scroll all the way to the bottom and click "Cancel Editing".

**Comment by peterbe** [comment]
I think a good solution would be to make the name clickable. Basically the stuff after the "Edit " prefix. 
<img width="707" alt="Screen Shot 2019-03-21 at 2 42 38 PM" src="https://user-images.githubusercontent.com/26739/54776981-a50afc80-4be7-11e9-8f57-34b1c26e4749.png">

**Comment by jaredkerim** [comment]
Cool this is handy!
