### ISSUE TITLE
Add a Linux only targeting 

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#11072]
we need to run this same experiment on Linux only - and there's no targeting for Linux only.

https://experimenter.services.mozilla.com/nimbus/fpp-floating-point-protection-rollout/summary

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4713)

**Comment by jaredlockhart** [comment]
Looks like we just need to check `os.isLinux`
