### ISSUE TITLE
Old PrefFlip experiments that were in Preview are now stuck and can't be sent to Draft or Live

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#11080]
**[Steps to reproduce]:**

1. Navigate to [https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/?status=Preview&feature_configs=763](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/?status=Preview&feature_configs=763).
1. Click one of the Experiments and click the “Go Back to Draft” or “Request Launch” buttons.
1. Observe the page.

**[Expected result]:**

* The Experiment is successfully moved to either Review or Draft states.

**[Actual result]:**

* The “This experiment cannot be published to preview.” error is displayed.

**[Notes]:**

* Attached a screen recording of the issue.

!firefox_lwJmgbkQ0i.mp4|width=2560,height=1400,alt="firefox_lwJmgbkQ0i.mp4"!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-4719)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/66945">firefox_lwJmgbkQ0i.mp4</a>

**Comment by data-sync-user** [comment]
➤ Beth Rennie commented:

We can no longer push prefFlips experiments/rollouts into preview so it is impossible to get into this state.

We can manually move all these recipes from preview into draft in the database, and they will eventually get removed from the RS preview collection.

**Comment by brennie** [comment]
Closed because this wont be fixed by a code change. the original bug is still tracked in JIRA
