### ISSUE TITLE
All existing experiments are wrongly updated with the "Locales" and "Countries" sections with the "All" default option

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1111]
**[Notes]:**
- This issue can be confusing for users since the Locales and Geographic regions are already displayed for existing experiments in the Population Filtering section. 
- Also it could impact experiments that are already in the "Ready for Sign-Off" or "Draft" states, who were already completed.

**[Affected versions]:**
- Firefox Release 66.0.1 and above
- Chrome 73.0.3683.75

**[Affected Platforms]:** 	 	
- All Windows
- All Mac 	 	
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open an existing experiment card.
3. Observe the description from the "Population" section.

**[Expected result]:**
- The "Locales" and "Countries" sections are not displayed.

**[Actual result]:**
- The "Locales" and "Countries" sections with the "All" default option are displayed.

**[Additional Notes]:**
- This issue is reproducible for all existing experiments, regardless of the state they are in.
- I could not verify this issue on an experiment in the "Complete" state because there isn't one available on Experimenter stage.
- Attached is a screen recording of the issue:
![LocalesNot](https://user-images.githubusercontent.com/40061643/54922344-99357800-4f10-11e9-9cd7-95641e9d8425.gif)

**Comment by jaredkerim** [comment]
Yes without manually correcting the historical data there is no way to automatically set these to the correct values.  I may go in and manually fix some of them, but it's very time consuming and tedious.
