### ISSUE TITLE
The description from the “Test Instruction” section is wrongly displayed for the “QA Status of your code” in the Experiment Bugzilla Ticket

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/experimenter#1112]
**[Affected versions]:**
- Firefox 66 and up
- Chrome Version 73.0

**[Affected Platforms]:**
- All Mac
- All Windows
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.
- Have a “Ready to Ship” experiment created on the "https://experimenter.stage.mozaws.net/" website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to experiment from the prerequisites. 
2. Scroll down to the “Testing & QA” section and observe the “QA Status” section’s description.
3. Click the “Experiment Bugzilla Ticket” button. 
4. Observe the “QA Status” sections description.

**[Expected result]:**
Step 2 & Step4:  The same description is displayed for both. 

**[Actual result]:**
Step 2. The description for the “QA Status” section is correctly displayed. 
Step 4. The description from the “Test Instructions” is displayed in the “QA Status of your code” section.

**[Notes]:**
- Attached a screen recording with the issue: [Link](https://drive.google.com/open?id=1pbGa7Vp_vUqr_AGvvGp-ymj4odaSg1IC)

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on the [Experimenter stage](https://stage.experimenter.nonprod.dataops.mozgcp.net/) website after the v2.28.1 stage deployment.
Tested on Windows 10x64, Mac 10.14 and Arch Linux 4.16.6 x64.

**Comment by Softvision-RemusDranca** [comment]
This issue is reproducible after the v2.30.0 stage deployment on [Experimenter stage](https://stage.experimenter.nonprod.dataops.mozgcp.net/) website.
Considering this, I will reopen this issue and remove the verified-fixed label.
