### ISSUE TITLE
Write RFC/Proposal on updating CI Workflow

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#11128]
We have discussed a plan to update our CI workflow to better account for external changes, lets write something up and discuss it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4736)

**Comment by jaredlockhart** [comment]
<img width="446" alt="image" src="https://github.com/user-attachments/assets/8abd1d35-5ace-44e6-b68a-0cfeef01bbe4">
