### ISSUE TITLE
Add-on studies are wrongly named “Opt-Out study” in the Experiment Bugzilla Ticket

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/experimenter#1113]
**[Affected versions]:**
- Firefox 66 and up
- Chrome Version 73.0

**[Affected Platforms]:**
- All Mac
- All Windows
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.
- Have a “Ready to Ship” Add-on experiment created on the "https://experimenter.stage.mozaws.net/" website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to experiment from the prerequisites. 
2. Observe the experiment’s type.
3. Click the “Experiment Bugzilla Ticket” button. 
4. Observe the “Experiments Type” section’s description in the Bugzilla Ticket.

**[Expected result]:**
Step 2 & Step 4. The “Add-On Study” type is displayed on both websites.

**[Actual result]:**
Step 2. The “Add-On Study” type is displayed.
Step 4. The “Opt-Out Study” type is displayed.

**[Notes]:**
- Attached a screenshot with the issue:

![Study Add-on](https://user-images.githubusercontent.com/37875464/54923708-79ec1a00-4f13-11e9-9438-8a92a107c2ff.png)

**Comment by tiftran** [comment]
Will be fixed in https://github.com/mozilla/experimenter/issues/803
