### ISSUE TITLE
The Experiment Bugzilla Ticket isn't updated with the "Locales" and "Countries" sections

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1114]
[Notes]:
- Not sure if this behavior is intended since the "Locales" and "Countries" sections are now optional, but I am logging this issue because before the "Population Filtering" section was divided, these two sections were displayed in the Experiment Bugzilla Ticket.   

**[Affected versions]:**
- Firefox Release 66.0.1 and above
- Chrome 73.0.3683.75

**[Affected Platforms]:**
- All Mac
- All Windows
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.
- Have a “Ready to Ship” experiment created on the "https://experimenter.stage.mozaws.net/" website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to experiment from the prerequisites. 
2. Click the “Experiment Bugzilla Ticket” button. 
4. Observe the “Are there specific criteria for participants?” description section in the Bugzilla Ticket.

**[Expected result]:**
- The "Locales" and "Countries" sections are displayed.

**[Actual result]:**
- The "Locales" and "Countries" sections are not displayed.

**[Additional Notes]:**
- Attached a screen shot of the issue:
![Screenshot_2019-03-25 1526490 -  Shield  Add-On Study Experiment no 3](https://user-images.githubusercontent.com/40061643/54930020-31d2f480-4f1f-11e9-9b18-f5767704c361.png)

**Comment by shell1** [comment]
planned as part of #803 improvements coming very soon.
