### ISSUE TITLE
Mobile integration tests run when they shouldn't on circleci

### ISSUE THREAD

**Issue by b4handjr** [mozilla/experimenter#11157]
I noticed that for a couple PRs the mobile integration tests ran even though there was no change within the `experimenter/` directory. We should fix that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4745)

**Comment by jrbenny35** [comment]
We need to add `- check_file_paths` to the [android job](https://github.com/mozilla/experimenter/blob/main/.circleci/config.yml#L336-L369) and [the fenix/fennec recipe job](https://github.com/mozilla/experimenter/blob/main/.circleci/config.yml#L409-L425)
