### ISSUE TITLE
Unable to save 'all' locales/countries in admin

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1121]
When editing an experiment in the admin, we should be able to save the experiment form with no countries/locales selected, which indicates that the experiment targets all locales/countries.  Right now if you try to save, it gives an error that those fields are required, when they should not be.

**Comment by glasserc** [comment]
Should we try to distinguish between affirmatively choosing "all" vs. not having interacted with the input at all?

**Comment by jaredkerim** [comment]
@glasserc If you open the experiment admin page, make no changes, and hit save, that should succeed, ie whatever state the locales/countries is in should be preserved.

**Comment by jaredkerim** [comment]
Closing as duplicate of https://github.com/mozilla/experimenter/issues/1084
