### ISSUE TITLE
Change 'str' validation for pref type

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1123]
We need to change the pref_value field to a CharField rather than a JSON field, probably a Max length of 1024 is reasonable @mythmon? 

Then we need to change the way the value is validated. For int and bool we can JSON parse into a python type and compare, and for string type we will do no validation and capture what is entered verbatim. This will allow us to store JSON blobs correctly for experiments that rely on them. 

- Change `pref_value` to charfield max_length=1024
- Change the validation [here](https://github.com/mozilla/experimenter/blob/master/app/experimenter/experiments/forms.py#L517-L533) to only check for int and bool, in the case of string, we will do no validation and just capture what is written verbatim
- Update tests

**Comment by mythmon** [comment]
> We need to change the pref_value field to a CharField rather than a JSON field, probably a Max length of 1024 is reasonable @mythmon?

There is [a recipe](https://delivery-console.prod.mozaws.net/recipe/659/) that had a preference value that was over 1700 characters (it was a Pocket preference using a JSON blob). Maybe we should go with something like 10KB instead? i.e. `max_length=10240`.
