### ISSUE TITLE
Capture user facing name and description for all experiments

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1124]
We need to add two fields to capture a name and description that will be shown to end users enrolled in an experiment. This is critical for add-on experiments now and will become important for pref experiments in the future. We can probably put them on the 'firefox and branches' form page. 

- Add `public_name` charfield to `Experiment`
- Add `public_description` charfield to `Experiment`
- Expose them in the `ExperimentVariantsBaseForm`
- Update form tests
- Put them in the `section_overview.html` template

**Comment by tiftran** [comment]
@jaredkerim was wondering would public name and public description be needed to be exposed in the experiments API? 
If so, correct me if I'm wrong, then serializers.py and the readme would need to be edited too??

**Comment by jaredkerim** [comment]
@tiftran Oh I think I missed this question! In theory we could have added it to the API in this PR but it's also okay to do that in a separate PR when it comes up.

**Comment by tiftran** [comment]
@jaredkerim it's all good, i think I asked this question again via slack or vidyo and you told me it was k
