### ISSUE TITLE
What is the correct format for entering JSON values into string preferences?

### ISSUE THREAD

**Issue by SuYoungHong** [mozilla/experimenter#1125]
Experimenter has inconsistent behavior when entering a string value for the preference the first time, and when you go back and edit that page. 

For a pref-flip experiment, if I create an experiment, I can specify branch values for the preference like this: 

`{"some": "value"}`

However, when I go back to edit the "Branches" section (say, to modify the % for each branch), Experimenter will not let me proceed, and give me a "pref value must be a string" error.

**Comment by SuYoungHong** [comment]
update: now, Experimenter is giving the same error (`!Unexpected value type (should be string) ` when entering the pref values into the experiment for the first time (previously, it only gave this error when editing the page after it was entered the first time).

**Comment by SuYoungHong** [comment]
Editing this issue for: 

We (activity stream / pocket) have a preference (string type) which should take a JSON. 

We want the value to be entered into the client's preference in this format[1]: 

```
{"api_key_pref":"extensions.pocket.oAuthConsumerKey","enabled":true,"show_spocs":true,"layout_endpoint":"https://getpocket.cdn.mozilla.net/v3/newtab/layout?version=1&consumer_key=$apiKey&layout_variant=basic"}
```

However, when we enter that value into Experimenter, it gives us this error: 

```
!Unexpected value type (should be string) 
```

What is the correct value to enter into Experimenter to ensure that the original value[1] gets entered correctly into the client's prefs? 

We previously tried:

```
"{\"api_key_pref\":\"extensions.pocket.oAuthConsumerKey\",\"enabled\":true,\"show_spocs\":true,\"layout_endpoint\":\"https://getpocket.cdn.mozilla.net/v3/newtab/layout?version=1&consumer_key=$apiKey&layout_variant=basic\"}"
```

but this results in the client not getting the correct preference. 

Please advise. 

**note:** previously, in [this experiment](https://experimenter.services.mozilla.com/experiments/activity-stream-pkt-newtab-beta66complexandperformance2/), experimenter accepted the unquoted JSON[1] and experiment subjects seem to have gotten the correct preference value.

**Comment by jaredkerim** [comment]
@SuYoungHong You can now enter JSON into the pref value fields in any formatting without concern for escaping etc.

**Comment by SuYoungHong** [comment]
awesome! thanks :)
