### ISSUE TITLE
Expose `groups` property for NimbusExperiments in api/v7/experiments

### ISSUE THREAD

**Issue by sarahhjchung** [mozilla/experimenter#11265]
Skylight is looking to filter and badge experiments based on the `groups` property so we are hoping that the `api/v7/experiments` api could eventually expose the `groups` property. This property would be an array type containing strings.

cc: @dmose

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4773)

**Comment by jaredlockhart** [comment]
@sarahhjchung Hi, what is `groups` here?  I'm not aware of any property of a Nimbus experiment called `groups`?

**Comment by sarahhjchung** [comment]
Hi, sorry I found out that 'groups' is already exposed in the `features` value inside branches if they exist so I'll be closing this issue now!
