### ISSUE TITLE
The "Pref Type" and "Pref Branch" sections are wrongly displayed on an Add-on experiment's page if it was previously saved as a Pref-Flip Study

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1128]
**[Affected versions]:**
- Firefox Release 66.0.2 and above
- Chrome 73.0.3683.75

**[Affected Platforms]:** 	 	
- All Windows
- All Mac 	 	
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.
- Have an Pref- Flip experiment created on the Experimenter stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites.
3. Click the "Edit" button from "Overview" section.
4. Click the "Type" drop-down menu and select the "Pref-Flip Study" option.
5. Click the "Save Draft" Button and observe the "Branches" section from the main page of the experiment.

**[Expected result]:**
- The "Pref Type" and "Pref Branch" sections are not displayed.

**[Actual result]:**
- The "Pref Type" and "Pref Branch" sections are displayed.

**[Notes]:**
- Attached is a screen shoot of the issue:
![Type Pref](https://user-images.githubusercontent.com/40061643/55176593-128bcf80-518a-11e9-9a86-84b397ce4ad5.PNG)

**Comment by shell1** [comment]
closing as highly edge case - doesn't break usability
