### ISSUE TITLE
Most Recently Updated not sorting by latest date

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1155]
The 'Most Recently Updated' sort on the list page should use the most recent date from an experiments changelog set, but looking at prod right now that doesn't seem to be the case.

**Comment by uhlissuh** [comment]
Just to throw in my two cents here, when I went to production to try to observe the disorder mentioned, I couldn't see it. Everything seemed ordered in accordance to the "History" section dates...

**Comment by jaredkerim** [comment]
@uhlissuh Okay I may have been mistaken when I saw it, I'll close this and we can reopen or refile it if we observe the behaviour again.
