### ISSUE TITLE
[Enhancement] Add information in the “History” section about what Experiment section was edited 

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/experimenter#1156]
**[Notes]:**
- Having additional information about what section was edited would make it much easier to track changes. At the moment you are informed that there were changes made to the experiment but it does not mention where exactly. This makes it very difficult to find the changes, having to reread the whole experiment. However, if the section that was edited would have been mentioned in the “History” section, you could focus only on that area and easily find what was changed. 

**[Affected versions]:**
- Firefox 66.0.2 and up
- Chrome Version 73.0

**[Affected Platforms]:**
- All Mac
- All Windows
- All Linux

**[Steps to reproduce]:**
1. Open the browser and navigate to the https://experimenter.services.mozilla.com/ website.
2. Click on one of the “Ready to ship” experiments ([Example](https://experimenter.services.mozilla.com/experiments/feature-revenue-impact-study-for-enhanced-tracking-protection/)).
3. Observe the experiment History section.

**[Expected result]:**
- A message detailing what specific section was edited is displayed.

**[Actual result]:**
- The following message is displayed ”<user name> Edited Experiment”

**[Additional Notes]:**
- Attached a screenshot with the issue:

![Screenshot_2019-04-05 Mozilla Experimenter](https://user-images.githubusercontent.com/37875464/55623156-d1f40d80-57aa-11e9-9b3f-bc52cf96ad3c.png)

**Comment by jaredkerim** [comment]
Yep this is planned in https://github.com/mozilla/experimenter/issues/464 as part of the upcoming [Lifecycles Project](https://github.com/mozilla/experimenter/projects/7).  Closing as a duplicate.
