### ISSUE TITLE
Add experiment preview image

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#117]
Add an image which captures the design change of the experiment to use as a preview and visual cue for the purpose of the experiment.

**Comment by jaredkerim** [comment]
Blocked on #255

**Comment by shell1** [comment]
we are closing out a bunch of these original "we could possible do x" UX enhancements.  Mid-year after 2 quarters of development - we will look at the UX and see all up what changes will be truly helpful to the users.  Don't want a bunch of ideas in the backlog that might get worked on individually - and conflict with more recent changes.
