### ISSUE TITLE
NimbusReviewSerializer is busted, letting experiments be published without full validation

### ISSUE THREAD

**Issue by brennie** [mozilla/experimenter#11767]
#11283 added the `segments` field to the experiments model:

```python
    segments = ArrayField(
        models.CharField(max_length=255),
        default=list,
        verbose_name="Segments",
    )
```

but did not add this field to the `NimbusReviewSerializer`. Thus, when saving the front-end, we end up with the following response in the graphQL payload:

```json
      "readyForReview": {
        "ready": false,
        "message": {
          "segments": [
            "This list may not be empty."
          ]
        },
        "warnings": {},
        "__typename": "NimbusReviewType"
      },
```

However, our [useReviewCheck hook](https://github.com/mozilla/experimenter/blob/41804a1566451fba8b21cdd99823881ddd35c6c2/experimenter/experimenter/nimbus-ui/src/hooks/useReviewCheck.tsx#L13-L42) does not map this field to a specific page because this field is not editable in the current UI, only the new UI. PageSummary then passes the invalidPages prop from useReviewCheck down to ChangeApprovalOperations which uses [that prop](https://github.com/mozilla/experimenter/blob/main/experimenter/experimenter/nimbus-ui/src/components/ChangeApprovalOperations/index.tsx#L69-L71) to determine whether or not we should be able to launch experiments.

This was not caught by our API unit tests because in our factories for generating test data, we always [set segments to a list](https://github.com/mozilla/experimenter/blob/41804a1566451fba8b21cdd99823881ddd35c6c2/experimenter/experimenter/experiments/tests/factories.py#L462-L464), which prevents the error from triggering. Changing this attribute to be an empty list results in 585 test failures and 12 errors.

The fix for this is as follows:

- Add segments to the NimbusReviewSerializer with allow_empty=True
- Change the factory to default to an empty list of segments
- Change the frontend to prevent publishing if readyForReview.ready !== true

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4973)

**Comment by jaredlockhart** [comment]
Thank you for the detailed write up @brennie 🙏 

Couple thoughts:

* I was wrong about `allow_empty`, we just need to replicate the pattern we used for [outcomes](https://github.com/mozilla/experimenter/blob/main/experimenter/experimenter/experiments/api/v5/serializers.py#L643-L645)

* After thinking about it more I think we should vary fields that are optional between being empty and having values, so something like

```py
    primary_outcomes = factory.LazyAttribute(
        lambda o: [oc.slug for oc in Outcomes.all()[:random.randint(0, 2)]]
    ) 
```
