### ISSUE TITLE
Update Experimenter pref flip intake to support multiple preferences

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1176]
After the Normandy client lands in Firefox 69 or 70 (Release in Sept 3 or October 22) - Experimenter will need to be updated the intake multiple preferences per branch (if desired).

UX pending implementation details (what is the client going to need - what format).

**Comment by jaredkerim** [comment]
Closing as a duplicate of https://github.com/mozilla/experimenter/issues/1421
