### ISSUE TITLE
[Enhancement] QA Sign-OFF process improvement

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1177]
**[Notes]:**
- We are addressing this enhancement because we were put in the impasse of whether to check or not the "QA Sign-Off", when the QA’s recommendation was "RED - DON’T SHIP". We didn't want to mislead the owner of the experiment in going forward with the experiment if the "QA Sign-Off" was checked and saved.

**[Affected versions]:**
- Firefox Release 66.0.3 and above
- Chrome 73.0

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on the "https://experimenter.stage.mozaws.net/" website
- Have a complete experiment in the "Ready for Sign-Off" state with all mandatory Sign-offs checked and saved except the "QA Sign-Off".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites and check the "QA Sign-Off" check-box.
3. Select one of the QA sign-off type options displayed (Green/Yellow/Red).
4. Click the "Save Sign-offs" button.
5. Click the "Ready to Ship" button.

**[Expected result]:**
- Step 2: The "GREEN - SHIP IT", "YELLOW - SHIP IT CONDITIONALLY", "RED - DON’T SHIP" options are displayed.
- Step 5: A dialog box is displayed if the "YELLOW - SHIP IT CONDITIONALLY" or the "RED - DON’T SHIP" option was previously selected, asking the user to confirm if he wants to proceed even if the QA’s recommendation is Red or Yellow.

**[Actual result]:**
- Step 2: There is no option displayed to select the QA’s recommendation type.
- Step 5: The experiment goes in the "Ready to Ship" state regardless of the QA’s recommendation.

**[Additional Notes]:**
- The suggested flow is just as an orientation. We could have a general QA sign-off checkbox, the 3 options with indentation and when one is checked, the general checkbox is checked too.
Or we could have a dialog box that opens when the sign-off checkbox is clicked that allows QA to select the type. After selected it would look like QA sign-off - SHIP IT / QA Sign-off - SHIP IT CONDITIONALLY / QA Sign-off - DON’T SHIP IT. Maybe with a color too.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-74)

**Comment by shell1** [comment]
#1171 we are limiting who can sign-off on the QA to only QA folks - to remove accidental signing.  So the QA Sign-off box should not be checked unless status is green or yellow.  then it becomes product choice (who does the final "ready to ship") if they will ship with the QA yellow issues.  Putting this on backlog as enhancement to give "green' or "yellow" sign-off option there as well - to be 100% visible.
