### ISSUE TITLE
The lists for "Locales" and "Countries" input fields are not available on the new stage server

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1202]
**[Affected versions]:**
- Firefox Release 66.0.3 and above
- Chrome 74.0. and up

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an experiment created on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- You are logged in your LDAP account on Experimenter stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://stage.experimenter.nonprod.dataops.mozgcp.net/".
2. Open the created experiment from prerequisites.
3. Click the "Edit" button from "Population" section.
4. Click on the "Locales" input field and observe the behavior.
5. Click on the "Countries" input field and observe the behavior.

**[Expected result]:**
- Step 4: The list with all available locales is displayed.
- Step 5: The list with all available countries is displayed.

**[Actual result]:**
- Step 4: The list with locales is not displayed and only the "All locales" option is available.
- Step 5: The list with countries is not displayed and only the "All countries" option is available.

**[Notes]:**
- Attached is a screen recording of the issue:
![DropDownList](https://user-images.githubusercontent.com/40061643/56654277-5f36cd80-6698-11e9-8cb1-8e138d0e4e40.gif)

**Comment by jaredkerim** [comment]
Yes this is because we neglected to load the locales/countries into the new stage deployment.  I'm trying to get ops to load the old stage database in so all the old testing experiments are recovered and that will also solve this.  I'll leave this open until we can confirm the locales/countries are back.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible on Experimenter stage "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website after the old database was uploaded.
Tested on Windows 10x64, Mac 10.14 and Arch Linux 4.16.6 x64.
