### ISSUE TITLE
The "Study" word from experiment Type help section was entirely removed instead of replaced with "Experiment" word

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/experimenter#1204]
**[Affected versions]:**
- Firefox Release 66.0.3 and above
- Chrome 74.0. and up

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://stage.experimenter.nonprod.dataops.mozgcp.net" page.
2. Click the "Create Experiment" button from top right side of the page.
3. After redirected, click on "Help" blue text button from under the experiment "Type" section.
4. Observe how are the experiment types named in help message.

**[Expected result]:**
- Experiment types are named "Pref-Flip Experiment" and "Add-on Experiment".

**[Actual result]:**
- The word "Experiment" was removed after both type names, making the descriptions sound a bit strange especially for Add-on type. ("An Add-on sends a Firefox Add-on...").

**[Notes]:**
- The initial naming was "Pref-Flip Study" and "Add-on Study", but it seems that after the global naming replacement was performed, the word "Study" was dropped completely and not replaced in this section.
- Here is a screenshot of the issue:
![Experimenter issue 1](https://user-images.githubusercontent.com/17258026/56672544-4e4d8280-66bf-11e9-9e8c-a7904309d3b6.png)

**Comment by jaredkerim** [comment]
Ah yep small text change, good catch.

**Comment by shell1** [comment]
+1 minor but in future will need - so putting to fix sooner than later.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible on Experimenter stage "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website after the v2.28.1 stage deployment. The word "experiment" was added for both type names in the experiment Type help section.
Tested on Windows 10x64, Mac 10.14 and Arch Linux 4.16.6 x64.
