### ISSUE TITLE
The "study" word is used instead of "experiment" in the email sent to Release Drivers- UPDATE TO DELIVERY

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1208]
**[Notes]:**
- Also, there are 2 exclamation points displayed at the end of the email's content.

**[Affected versions]:**
- Firefox Release 66.0.3 and above
- Chrome 74.0. and up

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an experiment in the "Ready for Sign-Off state created on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- You are logged in your LDAP account on stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://stage.experimenter.nonprod.dataops.mozgcp.net/".
2. Open the experiment from prerequisites.
3. Click the "Send intent-to-ship email" button from the "Required Sign-Off Checklist".
4. Click the "Send" button from the pop-up displayed.
5. Open the sent email that you are also added at CC, from your Inbox (@mozilla.com) and observe it's content.

**[Expected result]:**
- Only the "experiment" word is used for experiments. 

**[Actual result]:**
- The "study" word is used instead of the "experiment" word.

**[Additional Notes]:**
- Attached is a screen shot of the issue:
![Capture](https://user-images.githubusercontent.com/40061643/56734581-eef97c00-676b-11e9-80e2-85928d9994d1.PNG)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-75)

**Comment by jaredkerim** [comment]
Good catch!

**Comment by shell1** [comment]
putting this into the coming staged roll-outs milestone.  As we go into that we need to clean up specific language wherever possible - including all emails generated.  If possible - want to word that intent to ship email so it can be used for experiments, staged-rollouts, and mobile.  so the {type} of request will be in the subject... to say pref-flip experiment, add-on experiment, staged roll-out, etc... but maybe the body could be common.

**Comment by jaredlockhart** [comment]
`Study` should say `Delivery` now

**Comment by shell1** [comment]
We will change this to DELIVERY instead study throughout the body
