### ISSUE TITLE
The padding around the "Send intent-to-ship email" button is not the same

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1209]
**[Affected versions]:**
- Firefox Release 66.0.3 and above
- Chrome 74.0. and up

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an experiment in the "Ready for Sign-Off state created on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- You are logged in your LDAP account on stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://stage.experimenter.nonprod.dataops.mozgcp.net/".
2. Open the experiment from prerequisites.
3. Observe the "Send intent-to-ship email" button from the "Required Sign-Off Checklist" section.

**[Expected result]:**
- The padding around the "Send intent-to-ship email" button is the same. 

**[Actual result]:**
- There is almost no padding on the bottom side of the "Send intent-to-ship email" button.

**[Notes]:**
- Attached is a screen shot of the issue:
![Capture](https://user-images.githubusercontent.com/40061643/56739717-0fc7ce80-6778-11e9-9c55-cdd3e1310fba.PNG)

**Comment by jaredkerim** [comment]
Ah yep that's a little wonky, we should fix that.  I'm also not a huge fan of the button being in the middle of the checklist items (even though I suggested it).  Maybe we can move it to somewhere that looks a little less jarring than where it is now?

**Comment by uhlissuh** [comment]
So glad to see this issue come up, as that button has been bugging me for days now.. 😄

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible on Experimenter stage "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website after the v2.28.1 stage deployment.
Tested on Windows 10x64, Mac 10.14 and Arch Linux 4.16.6 x64.
