### ISSUE TITLE
Fix "Platforms" support to allow multi-select (same as Locales and Countries) and add a few more specific options

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1210]
**[Notes]:**
- I filled this issue because in the past we had experiments that were requested to be tested only on two different platforms (eg: Mac and Windows) or other combinations of only two platforms.

**[Affected versions]:**
- Firefox Release 66.0.3 and above
- Chrome 74.0. and up

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an experiment in the "Ready for Sign-Off state created on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- You are logged in your LDAP account on stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://stage.experimenter.nonprod.dataops.mozgcp.net/".
2. Open the experiment from prerequisites.
3. Click the "Edit" button from the "Population" section.
4. Click the "Platform" input field and select the "All Windows" option.
5. Click again on the "Platform" input field and select the "All Mac" option.
6. Observe the "Platform" input field.
 
**[Expected result]:**
- Both options are displayed in the "Platform" input field. 

**[Actual result]:**
- Only the "All Mac" option is displayed in the "Platform" input field.

**[Additional Notes]:**
- This issue is reproducible regardless of which combined selection of two is chosen, out of the three available platforms ("All Windows", "All Mac", "All Linux"). 
- Attached is a screen recording of the issue:
![One on a time](https://user-images.githubusercontent.com/40061643/56742963-61735780-677e-11e9-8ef9-1c736d8d6256.gif)

**Comment by jaredkerim** [comment]
Yes, I think this is working as intended for now.  I think for the case you're describing you'd have to just describe it in the additional filters section, and I'm not sure how the Normandy system implements that.  @shell1 any thoughts?

**Comment by shell1** [comment]
good catch.  I will check with folks at our tuesday sync and take make this work the way we want (whether that is as in now or something else) when we tackle the rest of the filter UX improvements.

**Comment by shell1** [comment]
REMINDER: file ticket in normandy repo as well for the specific windows version
