### ISSUE TITLE
The string example for the "Pref Value" field from the "Help" description is wrongly displayed between quotes

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1211]
**[Affected versions]:**
- Firefox Release 66.0.3 and above
- Chrome 74.0. and up

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an experiment created on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- You are logged in your LDAP account on stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://stage.experimenter.nonprod.dataops.mozgcp.net/".
2. Open the experiment from prerequisites.
3. Click the "Edit" button from the "Branches" section.
4. Click the "Help" button from the "Pref Value" section.
5. Observe the example displayed for strings.

 
**[Expected result]:**
- The example is not displayed between quotes.

**[Actual result]:**
- The example is displayed between quotes.

**[Notes]:** 
- Attached is a screen shot of the issue:
![Capture](https://user-images.githubusercontent.com/40061643/56751382-9a1b2d00-678e-11e9-83b6-c7d81e264a2e.PNG)

**Comment by jaredkerim** [comment]
Yes this is definitely incorrect now, we should fix that sooner than later.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible on Experimenter stage "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website after the v2.28.1 stage deployment.
Tested on Windows 10x64, Mac 10.14 and Arch Linux 4.16.6 x64.
