### ISSUE TITLE
Truncate descriptions on list page

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1212]
Right now users can enter fairly long descriptions in the 'short description' field which can cause the list page entries to be very large.  Maybe we should truncate them on the list page so that each list item has a maximum height so you can see more on a single screen?

Add a "..." to end of any that are truncated to indicate that it continues.

**Comment by shell1** [comment]
+1.  Roughly 6-9 lines looks visually good in the list.  It's more the vertical space the listing occupies than the character density that messes up the listing page look.  

do you need a character limit or is line limit possible?  the lower line counts look the best - but 9 isn't offensive - so maybe let it go that high to get the info in one screen and then crop?
