### ISSUE TITLE
Bugzilla tickets have new required fields

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1216]
Bugzilla recently added some new required fields, so we have to update our background tasks to include them:

 "A value must be set for the 'Is Regression' field."

**Comment by shell1** [comment]
@jaredkerim does the "is defect" set the "type" field.  If we can set the "type" to "task" and priority to P3 that would be ideal.

Setting both of these will get us off the nag list for these bugs.
Task is for engineering work to enable/disable something - which at the point of launch is what is happening.  P3 means it is in our backlog - which is accurate.  They are in backlog waiting for next steps that will resolve them (complete or archive)

**Comment by emceeaich** [comment]
Use `bug_type` = `task` to set that field, which is required.

Is the `is_regression` error coming up on bugzilla-dev.allizom.org?

**Comment by glasserc** [comment]
Spoke about this on Slack. `type` is OK. "Is Regression" was on Bugzilla Dev and was due to a configuration change that the BMO team is still developing. We don't have to worry about that just yet.

**Comment by shell1** [comment]
@glasserc should I file a new ticket to get type:task and priority set by default with ticket creation?
type:task will be required soon - so want that added that and priority now.

@emceeaich that is exactly the issue.   is_regression being required caused issues to not create through existing experimenter automation.

**Comment by glasserc** [comment]
@shell1 No -- the PR that closed this issue added type and priority to the ticket creation.
