### ISSUE TITLE
[Enhancement] We should update "Population" percent error message and its "Help" section description to reflect decimal values

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/experimenter#1231]
**[Notes]:**
- Targeting 1% of Firefox Release population needs VP sign-off. Because of this, I'm suggesting this enhancement to better inform people that decimal values can be also added, especially when targeting Firefox Release population.
- Also, if I remember well, we had experiments where study owner targeted 1% of Release population and we had to change the value to eliminate extra approval needed afterwards. 

**[Affected versions]:**
- Firefox Release 66.0.3 and above
- Chrome 74.0. and up

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on stage website.
- You already have at least 1 experiment in "Draft" state with Population set to 1%.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://stage.experimenter.nonprod.dataops.mozgcp.net" page.
2. Click on a draft experiment from the list.
3. Scroll down to "Population" section and click the top right "Edit" button.
4. Reduce the population percent to "0" and attempt to "Save as Draft" the experiment.
5. Observe the error message displayed.
6. Click the "Help" blue text button for the population percentage and observe the details.

**[Expected result]:**
- Step 5: The error message also explains that the population can be a "0.x" value but not 0.
- Step 6: The "Help" section details that values can also have decimal (eg: 0.5%) and that if Firefox Release population is targeted, the study owner might need approval even for the lowest % value of users. Also, an approximate example of what is the value for Release/Beta/Nightly that does not need approval is displayed in the Help section.

**[Actual result]:**
- Step 5: The error message states only that " The population size must be between 0 and 100 percent.".
- Step 6: There is no mention of decimal values or population size examples for each channel.

**[Notes]:**
- Here is a screenshot of the current behavior:
![image](https://user-images.githubusercontent.com/17258026/57081491-7f503780-6cfd-11e9-8b5b-963567e287a0.png)

**Comment by jaredlockhart** [comment]
This hasn't blocked anybody so far so closing.
