### ISSUE TITLE
No bugzilla ticket created (production experimenter) with an experiment May 1

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1232]
This experimenter was created May 1 and no experimenter bugzilla ticket was created with it https://experimenter.services.mozilla.com/experiments/activity-stream-pktnewtabh12019-release66-confirmation-test/

I checked and just created a bug with a title and description only and it worked - so what is blocking it from creating on the production instance? https://bugzilla.mozilla.org/show_bug.cgi?id=1548378

**Comment by jaredkerim** [comment]
Looks like the celery process went AWOL and stopped processing the queue.  There are no error logs in sentry or GCP to explain why.  We'll have to pay attention to it to see if it gets into that state again.

**Comment by jaredkerim** [comment]
I think the worker hung, I'm going to close this and if we see it again we can reopen.
