### ISSUE TITLE
Use django-configurations to provide updatable configurations

### ISSUE THREAD

**Issue by mythmon** [mozilla/experimenter#1240]
When settings are added or changed, it is often the case that developers need to update their local `.env` file. If they don't there are problems, sometimes obvious but sometimes subtle. Usually these settings need values, but dummy data works just fine.

In Normandy we store most settings in settings *classes* powered by django-configurations. This provides several settings presets that we can use in different environments. The most notable of these are the two presets `Testing` and `Development`. The `Testing` preset is used for all automated tests, and `Development` is used by default for local devs. The settings preset used is configured by environment variables, and individual preferences can be overwritten with environment variables as well.

I think that adopting a model like this for Experimenter will make keeping up with the project easier as settings change.

**Comment by shell1** [comment]
saw an issue rarely early on - but haven't seen enough since to warrant investing in this change.
