### ISSUE TITLE
The Sign-offs order from the "Optional Sign-Off Checklist" changes after each page refresh

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1244]
**[Affected versions]:**
- Firefox Release 66.0.4 and above
- Chrome 74.0. and up

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an "Ready for Sign-Off" experiment created on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- You are logged with your LDAP account on Experimenter stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://stage.experimenter.nonprod.dataops.mozgcp.net/".
2. Open the experiment from prerequisites.
3. Refresh the page and observe the Sign-offs order from the "Optional Sign-Off Checklist" section.

**[Expected result]:**
- The Sign-offs order is the same.

**[Actual result]:**
- The Sign-offs order changes after each page refresh.

**[Notes]:**
- Attached is a screen recording of the issue:
![Reorder](https://user-images.githubusercontent.com/40061643/57223296-3dc9d000-700e-11e9-8946-da807651338f.gif)

**Comment by jaredkerim** [comment]
@tiftran I think if you just wrap the sets in `sorted(set(....))` that should be an easy fix.

**Comment by tiftran** [comment]
@jaredkerim will do, was along the lines of what I was thinking of as well

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible on Experimenter stage "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website after the v2.28.1 stage deployment.
Tested on Windows 10x64, Mac 10.14 and Arch Linux 4.16.6 x64.
