### ISSUE TITLE
The text from the “Test Instruction” section is wrongly displayed as the “QA Status of your code” in the Experiment Bugzilla Ticket for an unarchived experiment

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/experimenter#1254]
**[Affected versions]:**
- Firefox 66 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.
- Have an experiment in the “Ready to Ship” state that was archived before milestone [2.28.0](https://github.com/mozilla/experimenter/milestone/46?closed=1)

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to the experiment from prerequisites.
2. Click the “Unarchive this experiment” button.
3. Click the “Return to Sign-Off” button.
4. Edit the “QA Status” section and save the draft.
5. Click the “Ready to Ship” button.
6. Refresh the page and navigate to the Experiment Bugzilla Ticket.
7. Observe the “QA Status” sections description.

**[Expected result]:**
- The description for the “QA Status” section is correctly displayed

**[Actual result]:**
- The description from the “Test Instructions” is displayed in the “QA Status of your code” section.

**[Notes]:**
- This issue is not reproducible with experiments that were not archived.
- There are ~20 archived experiments on the [production](https://experimenter.services.mozilla.com/?ordering=-latest_change&type=&status=&firefox_channel=&firefox_version=&project=&owner=&archived=on) website which could encounter this issue.
- [Here](https://drive.google.com/open?id=1MxNQLDh-DI_yLQUHM1D9u0D7iv9F0LZI) you can find a screen recording of the issue.

**Comment by shell1** [comment]
Valid issue - but with how quickly things are changing we will close without fixing.  If an experiment goes from archived to any of the active states - I will watch for this.  Thank you.
