### ISSUE TITLE
[Enhancement] An experiment should not be able to be moved through states and to save Sign-offs while it is archived

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1255]
**[Affected versions]:**
- Firefox Release 66.0.4 and above
- Chrome 74.0. and up

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Draft archived experiment created on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- You are logged in your LDAP account on stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://stage.experimenter.nonprod.dataops.mozgcp.net/".
2. Open the archived experiment from prerequisites.
3. Click the "Ready for Sign-off" button.

**[Expected result]:**
- The "Ready for Sign-off" button is not actionable. 

**[Actual result]:**
- The experiment goes in the Ready for Sign-Off state.

**[Notes]:**
- All other options to go forward with the experiment creation are available when the experiment is archived. As well as the options to  save/unsave Sign-Offs, Send intent-to-ship email.
- Attached is a screen recording of the issue:
![Archived](https://user-images.githubusercontent.com/40061643/57314327-1c461280-70fa-11e9-9273-064c9f2815d5.gif)

**Comment by jaredlockhart** [comment]
Hasn't broken anything for anybody so far so closing.
