### ISSUE TITLE
Way to identify and find experiments with a survey

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1265]
blocked on #507 

We had 3 issues with surveys.  1) we didn't get the info needed.  #507 addresses that 2) surveys often require delicate ending coordination - so I need a way to make sure we triple check experiments with surveys 3) the survey team should have a simple way to see what experiments need surveys.

* can you think of a place to add a filter to identify studies with a survey?  I can't see how the filtering for "in QA" looks anymore in stage (#941) in staging - but would like it to make sense with that filtering model.  It's a similar use case - ability to slice out experiments that need a certain type of attention (in this case "survey" related).  
* is there a way to add a visual notification under the experiment timeline if there is a survey needed bubble checked?   We see that summary screen when we filter for what changes need to be made.  So a visual indicator would be very helpful - i'm fine with the words "includes survey" under the date range.  maybe in bubble format?  I'm totally open to ideas (if it's even feasible)
![image](https://user-images.githubusercontent.com/8192232/57548791-b387b180-7316-11e9-8b5b-5b7292214eb4.png)

uper helpful for us and the survey team to be able to pull that info out.  Surveys are work for them and they can totally screw up our timing when we end a study.  we've been bit so many times on that.

**Comment by uhlissuh** [comment]
This issue can now just be an issue addressing your second question – the "add a visual notification under the experiment timeline if there is a survey needed"
