### ISSUE TITLE
Ensure all failed bugzilla calls notify the user

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1282]
I'm still able to create situations locally where a bugzilla call fails but I do not receive a notification, and no stack trace is sent to sentry.  We should figure out how to replicate those cases and ensure that any failed bugzilla call always results in a user notification and a sentry record.

I'll figure out how to recreate it and add instructions here.

**Comment by tiftran** [comment]
Test Cases tried:

Pref:

- Minimum required values for draft experiment x3
- Min required values + feature bugzilla url x3
- Min required values + feature bugzilla url + pop. fields field x3

Addon:

- Minimum required values for draft experiment x3
- Min required values + feature bugzilla url x3
- Min required values + feature bugzilla url + pop. fields field x3

Took longest production description and made it twice as long to see if bugzilla API had a description char limit

can't seem to reproduce locally 😬

**Comment by jaredkerim** [comment]
We should change all our tasks to always show a notification if they fail:

https://github.com/mozilla/experimenter/blob/master/app/experimenter/experiments/tests/test_tasks.py#L294

This should test the exact opposite.
