### ISSUE TITLE
Add an “Enrollment Paused” label next to the “Live” label. 

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1293]
Add an “Enrollment Paused” label next to the “Live” label.  
![image](https://user-images.githubusercontent.com/8192232/58056338-a25c5300-7b15-11e9-93d2-c890d8c7a975.png)

NEW REQUEST: Have a label on experiments have "Enrollment Paused"  - that is based off the Normandy API Pause information.

OLD REQUEST (we aren't doing this based on ability to get info from Normandy API):
This should be controlled by a Normandy folks manual click.  There is not a programmatic way for Normandy to indicate if an experiment is paused.  So would like a manual click, so we know when these transitions have been done without looking at code.

Maybe under “Archive Experiment” - but it’s not available unless you report to Benson (or are benson or shell).

**Comment by mythmon** [comment]
> There is not a programmatic way for Normandy to indicate if an experiment is paused.

This information is technically accessible in the Normandy API, in a clear format. It is a bit tricky to extract right now though. A manual control sounds like the right choice right now.

**Comment by shell1** [comment]
blocked om #158.  Going to implement after Tiff puts in the scaffolding.

**Comment by shell1** [comment]
@tiftran and me slacked on how easy it would be to get the date.  Since it's not dead simple to pull - I'm fine without it.  

Indicator is P1 - the date is P5.  So Tif can skip "pause date" investigation.  Bang for buck is 90% the indicator label.    That fixes the risk of human error of missing a pause request entirely (either me not asking for a Pause - or it not getting done on Normandy side).  The indicator would give me the ability to simply check and fix any issues.
