### ISSUE TITLE
add-on active experiment name field marked optional but doesn't accept blank values

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#1297]
Maybe a dupe of #902, but the add-on "active experiment name" field on the population wizard screen is marked optional but doesn't accept blank values, maybe because of a uniqueness constraint:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/173889/58208173-11ae8000-7c99-11e9-9eb7-387eab602327.png">

**Comment by shell1** [comment]
Make that field Delayed Optional

**Comment by jaredkerim** [comment]
Oh funny, just learned a little bit of django history and trivia:

https://stackoverflow.com/questions/17257031/django-unique-null-and-blank-charfield-giving-already-exists-error-on-admin-p/21934494

https://code.djangoproject.com/ticket/4136

https://github.com/django/django/commit/267dc4adddd2882182f71a7f285a06b1d4b15af0

This was fixed 3 years ago, by setting `empty_value=None` on the autogenerated ModelForm field, but if you override the field manually, like we do, it reverts to `empty_value=""` which is the old behaviour, see here:

https://github.com/django/django/blob/master/django/forms/fields.py#L209

so when you manually override a CharField in a ModelForm with a model CharField that has `(blank=True, null=True, unique=True)` you have to remember to set `empty_value=None` on the form CharField.  Funny.
