### ISSUE TITLE
Subsume firefox-test-tube

### ISSUE THREAD

**Issue by robhudson** [mozilla/experimenter#1298]
With the removal of the test-tube front-end, the only things the firefox-test-tube repo is doing is:

* A nightly import job, run via airflow, to aggregate population counts per experiment and branch
* An API endpoint that telemetry-streaming `POST`s to that collects experiment enrollment and unenrollment counts in 5 minute windows

I'd like to propose that a separate github repo and infrastructure for only these 2 things is overkill and these could be incorporated into experimenter, which ends up linking to the grafana instance that is reading this data.

**Comment by robhudson** [comment]
It was mentioned by @sunahsuh that it may be possible to update the telemetry-streaming job to write directly to the database and bypass the POST API endpoint mentioned above.

**Comment by jaredkerim** [comment]
@robhudson I don't think this should go here, Experimenter won't replace the data storage logic that Test Tube does, I think if something takes over for the TT db it'll be something completely independent managed by data engineering, so I think this should be replaced by a data engineering bug.  

We filed one here: https://bugzilla.mozilla.org/show_bug.cgi?id=1527679 but it was rejected as wontfix until the new druid backend launches.  If you want something to happen before that maybe reopen this ticket and add more context?
