### ISSUE TITLE
A new tab cannot be opened using keyboard shortcuts on Mac and Linux if a dropdown menu is already open

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/experimenter#1322]
[Affected Versions]:
- Firefox Release 67.0.1
- Firefox Beta 68.0.1
- Firefox Nightly 69.0a1

[Affected Platforms]
- All Mac
- All Linux

[Perquisites]
- Logged in with your LDAP account. 

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to the https://stage.experimenter.nonprod.dataops.mozgcp.net/ website.
3. Click on the "Most Recently Updated" dropdown menu.
4. Press the "Cmd+T" ("Ctrl+T" on Linux) keyboard combination on the keyboard and observe the behavior.

[Expected results]:
- A new tab is opened and focused.

[Actual results]:
- Nothing happens.

[Notes]:
- The issues is reproducible using all the dropdown menus from the "Sort Experiments" and "Filter Experiments" sections.
- Attached a screen recording of the issue: [here](https://drive.google.com/open?id=1eDZ05T21Jg4Pv0lwR9uQFoTqN5nmI--z).

**Comment by Softvision-PatriciuPop** [comment]
It appears that this is a Firefox issue that I have been able to reproduce on other websites that have dropdowns that use the "select" element. For testing I have used this [site](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select) . I will log a new bugzilla issue and post another comment.

**Comment by Softvision-PatriciuPop** [comment]
Here is the issue logged in bugzilla: [link](https://bugzilla.mozilla.org/show_bug.cgi?id=1557678)

**Comment by shell1** [comment]
closing as this isn't a blocker for our usability.  we'll inherit if Fx fixes, but not concerned.
