### ISSUE TITLE
[Windows] Intermittent - The Slack Application for Desktop is not launched when middle clicking the "#ask-experimenter on Slack" hyperlink

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/experimenter#1323]
[Affected versions]:
- Firefox Release 67 and above

[Affected Platforms]:
- All Windows

[Prerequisites]:
- You are logged in your LDAP account on stage website.
- The "Remember my choice for slack links" checkbox from the Launch Application window was previously checked.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "https://stage.experimenter.nonprod.dataops.mozgcp.net/".
2. Press middle click on the "#ask-experimenter on Slack" hyperlink under the Mozilla Experimenter logo.
3. Observe what happens next.

[Expected result]:
- A new page opens with the following string inside the Address Bar: "slack://channel?team=T027LFU12&id=CF94YGE03".
- The Slack application opens and is displayed on desktop.

[Actual result]:
- Only the "slack://channel?team=T027LFU12&id=CF94YGE03" string opens in a new tab. The application is not launched on desktop.

[Additional Notes]:
- This is also reproducible when opening the link in a new tab, using the Context Menu.
- Attached is a screen recording of the issue:

![slack app](https://user-images.githubusercontent.com/26000308/59045501-dca15080-8888-11e9-85f4-dd048327c096.gif)

**Comment by shell1** [comment]
middle clicking is not a supported primary use case.
