### ISSUE TITLE
The "Page not found" is displayed when clicking the "here" link from the "Data Science Bugzilla URL / Help" section

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1326]
**[Affected versions]:**
- Firefox Release 67.0.1 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on Experimenter stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Click the "Create Experiment" button.
3. Click the "Help" button from the "Data Science Bugzilla URL" section.
4. Click the "here" link from the description displayed and observe the behavior.

**[Expected result]:**
- The Mozilla mana page from where to file a ticket with Data Science is displayed.

**[Actual result]:**
- The "Page not found" is displayed.

**[Notes]:**
- Attached is a screen recording of the issue:
![page not found](https://user-images.githubusercontent.com/40061643/59093904-a6fa7700-891d-11e9-85c5-e1ebb3ac1afe.gif)

**Comment by shell1** [comment]
Can we make that "here" link to https://mana.mozilla.org/wiki/display/PM/Mozilla+Data+Science#MozillaDataScience-dsflagshipprograms2019

They updated their bugzilla template and that link broke - so let's link to the right section of their mana page instead (less fragile).

**Comment by Softvision-PatriciuPop** [comment]
I have verified this issue and it is no longer reproducible on the Experimenter Stage "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website after the v2.30.0 stage deployment.
Tested on Windows 10 x64, Mac 10.14 and Ubuntu 16.04.
