### ISSUE TITLE
The History logs order changes after each page refresh

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1327]
**[Affected versions]:**
- Firefox Release 67.0.1 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an experiment created on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- You are logged with your LDAP account on Experimenter stage website.
- Have history logs for the experiment.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://stage.experimenter.nonprod.dataops.mozgcp.net/".
2. Open the experiment from prerequisites.
3. Refresh the page and observe the History section.

**[Expected result]:**
- The History logs order is the same.

**[Actual result]:**
- The History logs order changes after each page refresh.

**[Notes]:**
- The dates order is not changed in the History section when the page is refreshed.
- Attached is a screen recording of the issue:
![historyLogs](https://user-images.githubusercontent.com/40061643/59099863-1035b680-892d-11e9-8473-e3b619aa7c67.gif)

**Comment by shell1** [comment]
Totally agree this is odd - but our level of granularity is daily and the order by person isn't specific.   it's just a sort by day - so it really isn't timing based.  we're putting this as a P5 - since it could be testing confusing seeing this change.  shouldn't impact real world use.

**Comment by jaredlockhart** [comment]
Hasn't blown up anybody's world so closing.
