### ISSUE TITLE
Nothing happens when the "Help" button from the "Platform" section is clicked

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1330]
**[Affected versions]:**
- Firefox Release 67.0.1 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on Experimenter stage website(https://experimenter.stage.mozaws.net/).
- Have an experiment created on Experimenter stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/" .
2. Open the experiment from prerequisites.
3. Click the "Edit" button from the "Population" section.
4. Click the "Help" button from the "Platforms" section and observe the behavior.

**[Expected result]:**
- The "Platforms" section expands and a description is displayed or a new tab opens on the mana page.
OR
- The "Help" button is not displayed if no description will be provided for this section.

**[Actual result]:**
-  Nothing happens.

**[Notes]:**
- Attached is a screen recording of the issue:
![PlatformHelp](https://user-images.githubusercontent.com/40061643/59192306-b4686900-8b8a-11e9-8c16-319dfe92126a.gif)

**Comment by jaredlockhart** [comment]
Fixed now!
