### ISSUE TITLE
The actionable area of the "Owned Experiments" and "Subscribed Experiments" links wrongly exceeds the left side of the strings 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1331]
**[Affected versions]:**
- Firefox Release 67.0.1 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on Experimenter stage website(https://experimenter.stage.mozaws.net/).
- Have an experiment created on Experimenter stage website.
- You are subscribed to at least one experiment.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/" .
2. Click outside the left side borders of the "Owned Experiments" or "Subscribed Experiments" links.

**[Expected result]:**
- Nothing happens.

**[Actual result]:**
- The "Owned Experiments" or "Subscribed Experiments" pages are opened.

**[Notes]:**
- Attached is a screen recording of the issue:
![HeaderSection](https://user-images.githubusercontent.com/40061643/59194155-c1885680-8b90-11e9-883a-ca4801b851cb.gif)

**Comment by shell1** [comment]
Agree this is odd, but it's not blocking usability - so we're OK with the current behavior.
