### ISSUE TITLE
The "Locales" and "Countries" dropdown menus are briefly displayed when opening the "Population" edit card 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1333]
**[Affected versions]:**
- Firefox Release 67.0.1 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on Experimenter stage website(https://experimenter.stage.mozaws.net/).
- Have an experiment created on Experimenter stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/" .
2. Open the experiment from prerequisites.
3. Click the "Edit" button from the "Population" section.
4. Observe the edit "Population" card's UI.

**[Expected result]:**
- The UI is rendered correctly.

**[Actual result]:**
- The dropdown menus for the "Locales" and "Countries" sections are briefly displayed.

**[Notes]:**
- This issue is also reproducible if the Edit card is opened and the page is refreshed.
- Attached is a screen recording of the issue:
![Dropdowns](https://user-images.githubusercontent.com/40061643/59197135-2e9fea00-8b99-11e9-8c97-c8d97200159b.gif)

**Comment by shell1** [comment]
Agreed it's weird, but unless we see this causing a usability issue down the road - this is acceptable behavior.
