### ISSUE TITLE
The "Help" button for the "Lightning Advisory (Optional)" Sign-off is wrongly linked to the mana page/"Dependent Sign-offs" 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1342]
**[Action Needed]:**
Please link the "Lightning Advising" help here: https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-LightningAdvising

**[Notes]:** 
- I logged this issue because the "Lightning Advisory (Optional)" Sign-off doesn't have any dependencies with the Risk questions and also, it's description on the mana page is displayed in the "Optional Sign-off" section.

**[Affected versions]:**
- Firefox Release 67.0.1 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on Experimenter stage website, "https://experimenter.stage.mozaws.net/".
- Have an experiment in the "Ready for Sign-Off state, created on Experimenter stage website. 

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites.
3. Click the "Help" button for the "Lightning Advisory (Optional)" Sign-Off.
4. Observe the behavior.

**[Expected result]:**
- The mana page is opened on the "Lightning Advising" section.

**[Actual result]:**
- The mana page is opened on the "Dependent Sign-offs" section.

**[Additional Notes]:**
- Attached is a screen recording of the issue:
![LigAdv](https://user-images.githubusercontent.com/40061643/59273966-003a1180-8c62-11e9-856c-17cfa1600706.gif)

**Comment by shell1** [comment]
Please link the "Lightning Advising" help here: https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-LightningAdvising

**Comment by motin** [comment]
@shell1 Should the Lightning Advisory also be moved down to the Optional Sign-Off Checklist, or is it in the mandatory part for increased visibility or other reason?

**Comment by shell1** [comment]
@motin we want it up there for increased visibility.  The top part of the checklist is the order the items should be approached (get your Datascience review first, then lightning advising, then allocate engineering, request QA, etc).   Those are the parts common to most all experiments (and really any delivery).

Lightning talk is a very likely one that anyone new to an experiment (or any complex experiment) would want to mitigate risk.  once you've been through a few times - you can skip unless you have a reason (mitigate risk of not knowing something is a good reason)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible after the v2.31.0 stage deployment on [Experimenter stage](https://stage.experimenter.nonprod.dataops.mozgcp.net/) website. Now the "Help" button is linked to the Lightning Advising section on the mana page.
Tested on Windows 10 x64, Mac 10.14 and Arch Linux 4.16.6 x64.
