### ISSUE TITLE
Generated filter objects should not include a locale filters for "All locales"

### ISSUE THREAD

**Issue by mythmon** [mozilla/experimenter#1345]
When an experiment lists all locales, the generated filter objects when clicking "Send to Normandy" include

```
{
  "type": "locale",
  "locales": []
}
```

This would be rendered by Normandy to JEXL as `(normandy.locale in [])`, which would always evaluate to false.

The correct way to specify all locales in Normandy filter objects is to not filter on locales. The filter objects generated should not include any filter with `"type": "locale"`.

**Comment by jaredkerim** [comment]
Oh this was fully a bug, I did do the check to exclude these filters I just did it wrong.  Good catch @mythmon
