### ISSUE TITLE
The subscribed experiments which are archived are not displayed after clicking the "Subscribed Experiments" link

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/experimenter#1354]
*[Affected versions]:*
- Firefox Release 67.0.1 and above
- Chrome 75 and above.

*[Affected Platforms]:* 	 	
- All Windows
- All Mac
- All Linux

*[Prerequisites]:*
- You are logged in your LDAP account on Experimenter stage website, "https://experimenter.stage.mozaws.net/".
- You are subscribed to an archived experiment.

*[Steps to reproduce]:*
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Click the "Subscribed Experiments" link from the header of the page.
3. Observe the behavior.

*[Expected result]:*
- All subscribed experiments are displayed even if are archived.

*[Actual result]:*
- The subscribed experiments which are archived are not displayed.

*[Notes]:*
- This can be confusing because the number of the subscribed experiments displayed under the "Owner Experiments" doesn't match with the number of the filtered subscribed experiments.
- As a workaround, you need to have both "Show archived experiments" and "Show subscribed experiments" filters checked.
- Attached is a screen recording of the issue:
![SubscibedArchived](https://user-images.githubusercontent.com/19226534/59337624-a55bf500-8d09-11e9-87db-1c63c41a0cf6.gif)

**Comment by jaredkerim** [comment]
https://media2.giphy.com/media/SpBBCn5F09DJC/giphy.gif
