### ISSUE TITLE
The intent to ship email can wrongly be send without completing all the fields with data needed for Release Management

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1355]
**[Affected versions]:**
- Firefox Release 67.0.1 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on Experimenter stage website, "https://experimenter.stage.mozaws.net/".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Click the "Create Experiment" button.
3. Complete all the mandatory fields ("Name", "Short Description" and "Data Science Bugzilla URL") from the "Overview" edit card.
4. Click the "Save Draft" button.
5. Click the "Ready for Sign-Off" button.
6. Observe the "Send intent-to-ship email" button from the "Required Sign-Off Checklist" section.

**[Expected result]:**
- The button is grayed out or not displayed until all the information needed for Release Management is completed.

**[Actual result]:**
- The button is actionable and the email can be sent.

**[Notes]:**
- Attached is a screen recording of the issue:
![Realman](https://user-images.githubusercontent.com/40061643/59338831-c9203a80-8d0b-11e9-9439-915ee7676f58.gif)

- Also here is a screen shot with an email sent with the information completed in step 3:
![shortEmail](https://user-images.githubusercontent.com/40061643/59338848-cfaeb200-8d0b-11e9-9e1d-3d17451522ed.PNG)

**Comment by shell1** [comment]
@jkerim @jaredkerim Just checking if these emails actually send from experimenter stage?  Hoping no :) - but wanted to check.

If the issue is just someone could click on the button in production - before they had filled out enough info - I'm OK with that scenario.   The button is a convenience - but has the same limitations situation if a person doesn't know what info to send with intent to ship.  It's a bit better in that the template shows.

**Comment by shell1** [comment]
Let's wait and see if this is an issue.  It seems common sense - and we'd need to build a lot of guardrails around it to enforce validations.  If it is an issue, we may need to remove this capability and put people back to doing manually.  Unfortunately the easiest is saying "don't click until the very end"... but then release mgmt doesn't get enough time.    After they have requested QA - the necessary fields should have been filled in.
