### ISSUE TITLE
Asked for "missing info" while using admin console

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1356]
using the admin console to move an add-on experiment to "live" - I was asked for missing required information.  the "value" information isn't required for add-on experiments though - i didn't think.

![image](https://user-images.githubusercontent.com/8192232/59373109-d2a2a600-8cfd-11e9-8ebb-f8a120c4b5cb.png)

**Comment by jaredkerim** [comment]
Oh yes interesting we should fix that.

**Comment by shell1** [comment]
doesn't hurt anything - shell just needs to do when editing.
