### ISSUE TITLE
The Sign-Offs order changes when an experiment enters in the "Ready to Ship" state from the "Ready for Sign-Off" state

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1359]
**[Affected versions]:**
- Firefox Release 67.0.1 and above
- Chrome 75 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on Experimenter stage website.
- Have an experiment in the "Ready for Sign-Off" state created.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites and observe the Sign-Offs order from the lists.
3. Click the "Ready for Sign-Off" button.
4. Observe the Sign-Offs order displayed in this state.

**[Expected result]:**
- The Sign-Offs have the same order in both states.

**[Actual result]:**
- The Sign-Offs order changes when the experiment goes in the "Ready to Ship" state.

**[Notes]:**
- Attached is a screen shot of the order of the Sign-Offs for experiments in both states:
![Ready for Sign-Off](https://user-images.githubusercontent.com/40061643/59430927-3c00e280-8dec-11e9-95b6-b919ef313c60.PNG)

**Comment by shell1** [comment]
Agree it is different, but I'm OK with this behavior.
