### ISSUE TITLE
Add 3 new people to QA sign-off group

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1360]
Please add these 3 new accounts to the QA sign-off group:

Simona Rosu -  srosu@mozilla.com
Gelu Haiduc  -  ghaiduc@mozilla.com
Lorand Janos - ljanos@mozilla.com

I also took the liberty to add them in the https://docs.google.com/spreadsheets/d/1W6nqGxFU3rDxkRGpRM1vq3O2vbnv_baHx4iv7l-Em6c/edit#gid=0 spreadsheet.

**Comment by shell1** [comment]
@Softvision-RemusDranca everyone has been added except ljanos, srosu, and bsurd. I slacked them all asking them:

"Hi. I was asked to give you all rights to check off the QA sign-off box in Experimenter (in case you need this ability in the future). Everyone in QA who might QA experiments has this permission. To do that I need you each to open Experimenter once, so we get your LDAP name into the system. Please go to https://experimenter.services.mozilla.com/ and sign-in (SSO should work). You just need to open the link and sign-in. After that Experimenter knows about you and I can add you to the "QA Sign-off" group."

**Comment by shell1** [comment]
done
