### ISSUE TITLE
The old "Jira" link needs be updated to the new one

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1377]
**[Affected versions]:**
- Firefox Release 67.0.2 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on Experimenter stage website.
- Have an experiment in the "Ready for Sign-Off" state created.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites.
3. Click the "Jira" link from the "QA Jira Request Sent" Sign-Off.
4. Observe the URL displayed in the Address bar.

**[Expected result]:**
- The new  "https://jira.mozilla.com/" URL is displayed.

**[Actual result]:**
- The old "https://moz-pi-test.atlassian.net/" URL is displayed.

**[Notes]:**
- Attached is a screen recording of the issue:
![JiraLink](https://user-images.githubusercontent.com/40061643/59680477-1738b080-91da-11e9-8af1-d7eeba12f8fb.gif)

**Comment by shell1** [comment]
this is how it should be in stage (or any pre-release channels) - but release (https://experimenter.services.mozilla.com/) needs to point to the production Jira instance https://jira.mozilla.com/

**Comment by jaredkerim** [comment]
@robotblake I think we just need to update an env var?

**Comment by shell1** [comment]
@robotblake I just corrected the release Jira link should go to here:  https://jira.mozilla.com//secure/CreateIssueDetails!init.jspa?pid=10245&issuetype=10202 

Sorry - we got the wrong link from QA.

**Comment by shell1** [comment]
I updated the link again at 1 PM EST on Wednesday.  the PI request mana has links to all their PI information.  since we have future uses in mind - beyond experimenter... https://mana.mozilla.org/wiki/display/PI/PI+Request is the future proof URL.

**Comment by shell1** [comment]
Hi @robotblake when I click on the link it is taking me to authenticate instead of here:  https://mana.mozilla.org/wiki/display/PI/PI+Request

I'm sorry - my adding the link we needed in comments probably confused things.

**Comment by shell1** [comment]
Closing again - i just didn't realize this is just waiting for the next update to Prod to release for the env variables to take effect in Prod version.
