### ISSUE TITLE
Allow users to edit the normandy slug

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1384]
In addition to https://github.com/mozilla/experimenter/issues/1380 some users have requested that we allow full user edit capabilities for the Normandy slug so that experiment owners can ensure critical information is present, such as particular strings required for telemetry filtering.

**Comment by shell1** [comment]
Today use the experiment name for the slug name.  That works in most cases.  For ones where it doesn't (there was an error) - you can ask Shell (or jared / mythmon) to update manually in experimenter.  

We can revisit if this continues to be an issue.  Su wa the requester
