### ISSUE TITLE
Release: 2.30.x

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1388]
- [x] Create 2.31.0 Milestone (due date two weeks from now)
- [x] Move all open tickets in 2.30.0 to 2.31.0
- [x] Close 2.30.0 Milestone
- [x] Approve and merge all open dependabot PRs
- [x] Pull master
- [x] Ensure `make check` passes
- [x] `git tag v2.30.0;git push --tags`
- [x] `@here deploying v2.30.0 to stage https://github.com/mozilla/experimenter/milestone/53?closed=1` in #experimenter 
- [x] Add celery beat process to stage deployment
- [x] Verify that stage loads with v2.30.x
- [x] Receive *GREEN* ship report from QA
- [x] `@robotblake please push v2.30.x to production` in #experimenter 
- [x] Verify that prod loads with v2.30.x
- [x] Create release issue for July 8 2019

**Comment by jaredkerim** [comment]
@tiftran Now that this is complete I think you can mark this as closed 🙆 Was using this release tracking issue helpful? Maybe we should add some steps for validating that the deploys were successful?

**Comment by tiftran** [comment]
@jaredkerim yes, i think it was helpful. Sounds like a good idea to add steps for validating 👍

**Comment by jaredkerim** [comment]
- [ ] Add celery beat process to stage deployment
- [ ] Verify that stage loads
- [ ] Verify that prod loads

**Comment by jaredkerim** [comment]
Just gonna take on the QA report for this release:

We finalized testing the new stage deployment v2.30.0 and it’s dot releases (v2.30.1 and v2.30.2) on Experimenter website. Here are the results:

New issues: 

    #1433 - Clone experiments are not displayed on the top of the first page list after they are created - major

    #1432 - The "Recipe ID" can wrongly be sent to Normandy with the "0" value - normal

    #1112 - The description from the “Test Instruction” section is wrongly displayed for the “QA Status of your code” in the Experiment Bugzilla Ticket - normal - regression




QA’s recommendation:  GREEN - SHIP IT

Reasoning: 

- All blocker and almost all major issues were fixed in the v2.30.1 and v2.30.2 dot releases. Also, most of the remaining issues found that have a lower impact were closed as wontfix.

- Although the remaining new issue (#1433) that we consider to be major is not yet fixed, we don’t consider it as a blocker since it will only be encountered by a small number of users. However, we recommend fixing it in the next release, as this issue affects the card position of a cloned experiment, being randomly displayed after creation, rather than on the top of the list from the first page.  

Testing Summary:

- Windows 10 x64 - Test Run

- Mac 10.14 - Test Run

Tested Platforms:

- Windows 10 x64

- Mac OS 10.14

Tested Firefox versions:

- Firefox Release 67.0.1

- Firefox Release 67.0.4

**Comment by tiftran** [comment]
https://github.com/mozilla/experimenter/issues/1442 was found

**Comment by tiftran** [comment]
creating milestone v2.30.3 for #1442

**Comment by tiftran** [comment]
Closing v2.30.3 has been released to prod and stage
