### ISSUE TITLE
The "Server Error (500)" is displayed when accessing the Experimenter(stage) website

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1391]
**[Notes]:**
- I'm not sure what where the exact steps that cause this, but I was testing the new "Clone experiment" functionality. 
- I was performing negative testing on the cloned experiment's name in the prompt displayed after clicking the "Clone experiment" button:
  - Entering a long name and clicking the "Clone" button;
  - Entering the same name and clicking the "Clone" button;
  - Entering empty spaces and clicking the "Clone" button;
  - Entering special characters and clicking the "Clone" button;
  - Clicked the "Back" button after entering an invalid name.

**[Affected versions]:**
- Firefox Release 67.0.4 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile created.
- You are logged in your LDAP account on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites. 
2. Navigate to "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
3. Observe the behavior.

**[Expected result]:**
- The Experimenter(stage) website is opened.

**[Actual result]:**
- The "Server Error (500)" is displayed.

**[Additional Notes]:**
- Attached is a screen recording of the issue an the [link](https://sentry.prod.mozaws.net/operations/experimenter-stage/issues/5985994/) to the error received on Sentry: 
![stage500](https://user-images.githubusercontent.com/40061643/60079863-6bdaaf00-9737-11e9-8044-1686c838e360.gif)

**Comment by uhlissuh** [comment]
I understand what's going on!

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible on Experimenter stage "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website after the v2.30.1 stage deployment.
Tested on Windows 10 x64, Mac 10.14 and Arch Linux 4.16.6 x64.
