### ISSUE TITLE
Add a Text field for "Abstract", that is editable after the experiment ends

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1399]
Add an OPTIONAL text field for "Abstract". This needs to editable after the experiment (or future normandy use - like Staged Rollouts) ends.

In box help should read:  "Brief summary of any analysis or learnings from this work.  The goal is to quickly communicate what was learned." 

The help should link here: https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-Summary

**Comment by uhlissuh** [comment]
We've decided this field is not needed at this time.
