### ISSUE TITLE
The experiments URL's are not updated if their name is changed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1402]
**[Affected versions]:**
- Firefox Release 67.0.4 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- Have an "Draft" experiment created on Experimenter stage.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites.
3. Click the "Edit" button from the "Overview" section.
4. Insert a new name in the "Name" section.
5. Click the "Save Draft" button and observe the tab's URL.

**[Expected result]:**
- The URL reflects the new name of the experiment.

**[Actual result]:**
- The URL reflects the old name of the experiment.

**[Notes]:**
- Attached is a screen recording of the issue:
![URL](https://user-images.githubusercontent.com/40061643/60264046-f1eb2700-98ea-11e9-8f91-4bb7eb3da8ee.gif)

**Comment by uhlissuh** [comment]
Hey that's actually by design. We don't want the URL to change and break a bunch of people's links to the experiment!
