### ISSUE TITLE
The "Branches" section is wrongly displayed as complete if a clone experiment is changed from Add-On to Pref-Flip type

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1403]
**[Affected versions]:**
- Firefox Release 67.0.4 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- Have an Add-On clone experiment, cloned from an complete experiment, created on Experimenter stage.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites.
3. Click the "Edit" button from the "Overview" section.
4. Change the type of the experiment into a "Pref-Flip" from the "Type" section.
5. Click the "Save Draft" button and observe the "Branches" section.

**[Expected result]:**
- The "Branches" section is incomplete since the sections from "Firefox Pref" and "Pref Value" are not completed.

**[Actual result]:**
- The "Branches" section is complete even though the sections from "Firefox Pref" and "Pref Value" are not completed.

**[Notes]:**
- As a result, the experiment can be pushed in the "Ready to Ship" state without completing the mandatory fields from the "Firefox Pref" and "Pref Value" sections.
- Also, the sections from "Firefox Pref" and "Pref Value" are not displayed in the "Branches" section.
- Attached is a screen recording of the issue:
![AddOnClone](https://user-images.githubusercontent.com/40061643/60271463-15b66900-98fb-11e9-954d-ff1429f55a70.gif)

**Comment by shell1** [comment]
while this is an issue - if they are cloning we should not expect them to change type.  It might happen - but so edge that we aren't building for that case.  we can manually catch and correct those.
