### ISSUE TITLE
The "Experiment Bugzilla Ticket" is not created for experiments with names over ~230 characters

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1404]
The "Experiment Bugzilla Ticket" is not created for experiments with names over ~230 characters

**[Notes]:**
- This is the [error](https://sentry.prod.mozaws.net/operations/experimenter-stage/issues/5741831/) received on Sentry for an experiment with a name that has 255 characters: "The text you entered in the Summary field is too long (280 characters, above the maximum length allowed of 255 characters)."

**[Affected versions]:**
- Firefox Release 67.0.4 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- Have an "Draft" experiment created on Experimenter stage.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites.
3. Click the "Edit" button from the "Overview" section.
4. Insert a new name that has over 230 characters in the "Name" section.
5. Click the "Save Draft" button.
6. Click the "Ready for Sign-Off" button.
7. Refresh the page and observe the top section of the page.

**[Expected result]:**
- The "Experiment Bugzilla Ticket" is created for the experiment and a message that the ticket was created is displayed.

**[Actual result]:**
- The "Experiment Bugzilla Ticket" isn't created for the experiment and a message that the ticket wasn't created is displayed.

**[Additional Notes]:**
- Attached is a screen recording of the issue:
![LongName](https://user-images.githubusercontent.com/40061643/60281196-28399e00-990d-11e9-88b9-cb9f45fb64db.gif)

**Comment by tiftran** [comment]
Things to consider if we decide to reduce the max num of chars for experiment name...
 • Upon creation: summary = [Experiment]: <Type> <Name>
 • Ready to Ship: summary = [Experiment]: <Type> <Name> FX <min version> to <max version>
