### ISSUE TITLE
No error message is displayed when saving a second branch with the same name for an already created experiment

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1411]
**[Affected versions]:**
- Firefox Release 67.0.4 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- Have an experiment created on Experimenter stage with only one branch.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites.
3. Click the "Edit" button from "Branches" section and change the "100" value from the "Branch size" section to "50".
4. Click the "Add Branch" button.
5. Complete the fields from the created branch with valid data and with the same name as for the first branch.
6. Click the "Save Draft" button and observe the behavior.

**[Expected result]:**
- An error message that informs the user that the Name of the branches must be unique for the experiment, is displayed.

**[Actual result]:**
- No error message is displayed and the the experiment is not saved even if all input fields color turn green.

**[Notes]:**
- Attached is a screen recording of the issue:
![Branch](https://user-images.githubusercontent.com/40061643/60347662-8e362c00-99c6-11e9-87f6-4c1fdb733f1b.gif)

**Comment by jaredkerim** [comment]
I'm not able to recreate this on current master, so I'm going to close for now and we can reopen/refile if it comes up again:

<img width="1440" alt="Screenshot 2019-09-03 13 41 23" src="https://user-images.githubusercontent.com/119884/64195895-9724fd00-ce50-11e9-9a57-57616371b723.png">
