### ISSUE TITLE
Pref studies need the Branching section updated to support multiple prefs

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1421]
Remove the existing top 3 fields that are currently under "Firefox Preference" heading - (they will be going under branches).  We want them to behave the same in the branching section as these fields did.

Inside the Branch details: 
- Add "Branch" to the existing "Name" field title - so it is now clearly a field for "Branch Name".
- Add a "Pref Name" field before the existing "Pref Value" field.  It should be the same type and same validation properties of the original "Pref Name" field. 
- Add "Pref Branch" here - same drop down options and validation as the original pref branch.
- New: "Add Pref" button INSIDE each branch section.  Clicking should pop up 3 new boxes for "Pref Name", "Pref Value", "Pref Branch".

Sending info to Normandy about multiple prefs:
- Need new schema generation - Now we’ll need to send over:  branchname - pref name - pref value - pref branch:default/user.  Existing schema https://searchfox.org/mozilla-central/source/toolkit/components/normandy/actions/schemas/index.js#230  
- Add a new serializer for new recipe format.  

![image](https://user-images.githubusercontent.com/8192232/60528674-ccbf3580-9ca9-11e9-982f-8c17ad5a109f.png)

**Comment by jaredkerim** [comment]
Note in the UI we should ask 'Does this experiment target a single pref or multiple prefs'

For single prefs we can just use the old single pref ui, for multiple prefs we can show the new UI but we have to caveat it if Min Version < 68, grey out the 'multiple prefs' option and explain 'multiple prefs aren't available for firefox versions below 68'

**Comment by jaredkerim** [comment]
Blocked on https://github.com/mozilla/experimenter/issues/1586 before we make any UI changes to the design page.
