### ISSUE TITLE
Add-on studies need the Branching section updated to support multiple branches

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1422]
The existing two fields under "Firefox Add-ons" will go away (ActiveExperimentName and Signed Release URL).  The title will stay there since it holds the experiment branch detail area together conceptually - otherwise would just be a bunch of branch details in the summary page.

Inside the Branch details: 
- Add "Branch" to the existing "Name" field title - so it is now clearly a field for "Branch Name".
- Add a "Signed Release URL" field after the existing "Description" field.  It should have the same validation properties of the original "Signed Release URL" field. 
- We need a way to indicate if a branch that will be control based on having no add-on.  I'm thinking a checkbox for "No add-on needed - Control"?  
-- that would send a null value for the "signed Release URL field".  
-- Clicking "no add-on needed" needs to "meet" the signed release URL required-delayed field need.  I'm OK if we put an obviously junk URL in there... this is used by a human, not directly by a computer.

Sending info to Normandy with add-ons branching support:
- Need new schema generation - Now we’ll need to send over:  branchname - signed release URL.  If it's "no add-on needed" just send a null over.  Existing schema https://searchfox.org/mozilla-central/source/toolkit/components/normandy/actions/schemas/index.js#230  
- Add a new serializer for new recipe format.  

![image](https://user-images.githubusercontent.com/8192232/60528712-e9f40400-9ca9-11e9-9ffd-32c96de7fbd0.png)

**Comment by jaredkerim** [comment]
Blocked on https://github.com/mozilla/experimenter/issues/1586 before we make any UI changes to the design page.

**Comment by jaredkerim** [comment]
Note in the UI we should ask 'Does this experiment ship a single addon or branched addons'

For single addons we can just use the old single addon ui, for branched addons we can show the new UI but we have to caveat it if Min Version < 68, grey out the 'branched addons' option and explain 'branched addons aren't available for firefox versions below 68'
