### ISSUE TITLE
The "Recipe ID" can wrongly be sent to Normandy with the "0" value

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1432]
**[Notes]:**
- After clicking the "Send to Normandy" button with the "0" value in the "Recipe ID" input field, the experiment goes in the "Accepted by Normandy" state, but without displaying the "Normandy Recipe ID:", "Delivery Console Recipe" and "Normandy API Recipe" subsections in the "Normandy Info" section.

**[Affected versions]:**
- Firefox Release 67.0.4 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- Have an experiment in the "Ready to Ship" state, created on Experimenter stage.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites.
3. Click the "Send to Normandy" button.
4. Insert the value "0" in the "Recipe ID" input field from the modal displayed.
5. Click the "Send to Normandy" button and observe the behavior.

**[Expected result]:**
- The value isn't accepted and an error message is displayed.

**[Actual result]:**
- The value is accepted and the experiment goes in the "Accepted by Normandy" state.

**[Additional Notes]:**
- Attached is a screen recording of the issue:
![RecipeID](https://user-images.githubusercontent.com/40061643/60720626-06a36c80-9f34-11e9-886e-0b8787ed03a6.gif)

**Comment by shell1** [comment]
This is a valid limit that we should check - but i'm OK with it - since only 3 people set those values.
