### ISSUE TITLE
Clone experiments are not displayed on the top of the first page list after they are created

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1433]
**[Affected versions]:**
- Firefox Release 67.0.4 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- Have an experiment created on Experimenter stage.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites.
3. Click the "Clone this Experiment" button.
4. Click the "Clone" button from the prompt displayed.
5. Click the home page button and observe the new clone's card position.

**[Expected result]:**
- The clone's card is the first one displayed on the top list from the first page.

**[Actual result]:**
- The clone's card is randomly displayed on other pages.

**[Notes]:**
- Here is a [link](https://drive.google.com/open?id=1q9IHZC912GmbpWurCaOUt3wFV0oG5CSm) for the screen recording of the issue:

**Comment by shell1** [comment]
confirmed this is weird, not sure how big the impact of it is - but we'll look at.
