### ISSUE TITLE
Add improve, regress fields

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#145]
Add two fields to summarize which things were improved, and which were regressed so we can see at a glance how each experiment affected core metrics.

Examples:

improved: clicks searches

regressed: blocks latency

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-78)

**Comment by shell1** [comment]
Moving past Lifecycle.  there are 3 related bugs in this area that need more time with the potential consumers (product, data science, normandy) to be clear on the use cases - so we implement it as best as possible
