### ISSUE TITLE
The Firefox “ Max Version” can wrongly be saved if it is lower than the “Firefox Min Version”

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1455]
**[Notes]:**
- @uhlissuh  If the experiment goes in the "Ready to Ship" state having this Firefox versions set, it will update the "Normandy Recipe Slug" with the set versions. Also, I'm not sure what impact it could have on the Normandy recipe creation so I will mark it's severity as "Major".

**[Affected versions]:**
- Firefox Release 68.0 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on Experimenter stage website.
- Have an experiment in the "Draft" or "Ready for Sign-Off" state created on Experimenter stage.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites and click the "Edit" button from the "Population" section.
3. Click the “Firefox Min Version” dropdown menu and select a Firefox version (ex: 60).
4. Click on the “No Max Version” dropdown menu and select a lower Firefox version then the one selected for the  “Firefox Min Version” (ex: 57).
5. Complete all the other mandatory fields from the “Population” page with valid data.
6. Click the "Save Draft" button and observe the behavior.

**[Expected result]:**
- An error message is displayed informing the user that the "Firefox Max Version" must be equal or higher then the "Firefox Min Version".

**[Actual result]:**
- The experiment is saved and the changes are reflected on the experiment's card.

**[Additional Notes]:**
- Attached is a screen recording of the issue:
![MinMaxVersion](https://user-images.githubusercontent.com/40061643/61136002-73d27700-a4cb-11e9-8880-6390a9fee008.gif)

**Comment by shell1** [comment]
need to add a check that the max needs to equal or higher than the minimum.

Catch could be just "red" - max versions needs higher or equal to minimum version.
