### ISSUE TITLE
Add some way to indicate whether an experiment was 'graduated'

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#146]
Usually when we do an experiment, it's to test some new set of code/features.  At the end of the experiment, we may then launch that code/feature to everybody, delete it and never launch it to anybody, or make some change and launch it as a new experiment.  We need to add some way to indicate this in the status of an experiment so when we're looking at the list view it's obvious to see which experiments made their way out to everybody or not.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-79)

**Comment by shell1** [comment]
I'd like a list of check boxes with most common final states (but need to input on what those should be).  Ideally we could use these to slice things up later and look at the text fields (results, conclusions, lessons learned) for more information.
__ enabled feature based on results
__ held off on feature based on results
__ invalid study
__ launched another experiment based on results
