### ISSUE TITLE
Nothing happens when the "Help" buttons from the "Firefox Channel" and "Firefox Versions" section are clicked

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1460]
**[Affected versions]:**
- Firefox Release 68.0 and above
- Chrome 75 and above.

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on Experimenter stage [website](https://experimenter.stage.mozaws.net/).
- Have an experiment created on Experimenter stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/" .
2. Open the experiment from prerequisites.
3. Click the "Edit" button from the "Population" section.
4. Click the "Help" button from the "Firefox Channel" or "Firefox Versions" section and observe the behavior.

**[Expected result]:**
- The section expands and a description is displayed or a new tab opens on the mana page.
OR
- The "Help" buttons are not displayed if no description will be provided for this sections.

**[Actual result]:**
-  Nothing happens.

**[Notes]:**
- Attached is a screen recording of the issue:
![HelpButtons](https://user-images.githubusercontent.com/40061643/61213481-d4e98d00-a70d-11e9-861a-dfcbea8f9840.gif)

**Comment by shell1** [comment]
i'd be happy to remove those now that the UX is clear.  Either works - fixing or removing.
