### ISSUE TITLE
Validate JSON provided in pref flips

### ISSUE THREAD

**Issue by iwsmith** [mozilla/experimenter#1479]
We should add a feature to warn if smart quotes (`”` U+201C & `”` u+201D)  are present in JSON values for pref branches, as these are not valid to define string literals and will result in errors. Furthermore, they are not visually distinct from quotation marks (U+0022 `"`) and hard to catch.

For example, my JSON was:
```
"stories_endpoint":”https://getpocket.cdn.mozilla.net/v3/firefox/global-recs?version=3&consumer_key=$apiKey&locale_lang=en-US&feed_variant=default_spocs_on&model_id=b-0085-15k-age-05-syn-limp-explore-locales-rr”
```
when it should have been:
```
"stories_endpoint":"https://getpocket.cdn.mozilla.net/v3/firefox/global-recs?version=3&consumer_key=$apiKey&locale_lang=en-US&feed_variant=default_spocs_on&model_id=b-0085-15k-age-05-syn-score-explore-locales-rr"
```

See https://bugzilla.mozilla.org/show_bug.cgi?id=1566800 as an example cause by smart quotes.

**Comment by iwsmith** [comment]
Actually thinking about this, we should really just validate whatever JSON we are given:`JSON.parse(pref-string)` and catch the exception to display as error text if it doesn't work.

**Comment by mythmon** [comment]
How would you propose handling string prefs that don't contain JSON?

**Comment by iwsmith** [comment]
Ah good point. One option would be to make add a JSON pref type distinct from string prefs. This change could just be on the experimenter web page, so that the downstream stuff still processes it as a string pref. The experimenter page could then apply JSON parsing to validate the input, and we could also increase the size of the text box you enter the JSON into to make it easier to use. 

A cheaper option is still parse whatever is in there as JSON, and just have a warning to the effect of "If this is a JSON string pref, it isn't valid". This might confuse users, but it is super cheap to do.

I think the first option (adding a new pref-type to the web front end) is the better one; it should be less confusing to users and could be done completely in JS on the experimenter page.
