### ISSUE TITLE
Update Data Science bug with experiment statuses

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1482]
We write to the experimenter bug at certain points - can we send information to the data science bug as well.  

Emily brought this idea up - need to thing through avoiding making an overly chatty systems - but also some things would be nice. 

Example scenario - they have a DS bug.  that bug launches v1 of an experiment.  the experiment fails for whatever reason and they need v2.  There isn't a great correlation between DS bug and experimenter ticket to be able to track down v2 (unless you know it happened).

also no search for bug numbers (any associated with the experimenter) in experimenter search - would be a huge help if that is simple.

**Comment by jaredkerim** [comment]
@shell1 If the goal is to correlate multiple experiments with a single DS bug, you can just put the same DS bug in the v2 experiment when you create it or automatically if it's cloned.  We could also write to the DS bug, but if it's just about correlating that might not even be necessary.

Also making the bug numbers searchable is so small I could do it in less time than it takes to write this comment and to prove it I will.

**Comment by jaredkerim** [comment]
- ready to ship
- went live
- completed

added as comments to the data science bug
