### ISSUE TITLE
Send an email to a mailing list when experiments have "ready-to-ship" clicked

### ISSUE THREAD

**Issue by mythmon** [mozilla/experimenter#1491]
Subscribing to experiments is pretty cool, but it is mostly useful if you only care about a few experiments. That fits most users. On the other hand, I care about almost all the experiments (that get to a certain point).

I'd like to automatically subscribe to any experiment once it gets to "ready to ship". (or at least get emails as if I were subscribed). Bonus points if I can manually unsubscribe to studies that I don't actually want to hear about that particular experiment.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-80)

**Comment by shell1** [comment]
these notices for the operations style people are relevant for DS and QA at different points as well.  Figuring out how noisy we want things to be makes sense.  DS at draft and QA at begin sign offs and exp ops at ready to ship

**Comment by jaredlockhart** [comment]
Let's make a django group of users to be notified specifically when an experiment moves to ready to ship.
