### ISSUE TITLE
Add comments resolution state

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#1499]
We should add a way to mark a comment as acknowledged or resolved because right now people will request changes to experiment designs in the comments, but there's no way to know whether those changes were actually made.

Perhaps we can add a little UI like a thumbs up or checkbox and when it's clicked we capture who clicked it and when and amend that to the comment so it looks something like

Jared Kerim *tuesday may 1st*
Hey can you update the max version to 68?
                    👍 rdalal *wednesday may 2nd*

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-81)

**Comment by shell1** [comment]
this is in the suite of it is difficult to work with comments.  being able to marked as addressed would work.  but need a way to make it clear that it is addressed into the main form (and not hanging out in comment).

agree with the premise - how to make it so it's not "agree" versus not.  there will likely be "thumbs up" for agree versus done.
