### ISSUE TITLE
Show edit history for a section inline with comments

### ISSUE THREAD

**Issue by mythmon** [mozilla/experimenter#1500]
It would be nice to see edit history in-line with comments, to better understand the changes made to the recipe and the current state of the experiment.

I mocked up what this might look like, based on [this experiment](https://experimenter.services.mozilla.com/experiments/webrender-amd-performance-68/).

![image](https://user-images.githubusercontent.com/305049/61827491-862ca900-ae19-11e9-8312-af70681913a8.png)

**Comment by shell1** [comment]
we are going to hold this ticket and revisit after alissa lands her more advanced change history fixes... then revisit

**Comment by shell1** [comment]
New customers are our priority for 2020 and this is not a simple immprovement or blocker.  closing for now and revisit concept in 2021
