### ISSUE TITLE
Feature URL validation rejects bug aliases

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#1513]
Bugzilla URLs with bug aliases are rejected:

<img width="673" alt="image" src="https://user-images.githubusercontent.com/173889/62135087-74725800-b296-11e9-83d4-40a0f8c4be3a.png">

**Comment by jaredkerim** [comment]
@shell1 suggests that we should be explicit about the bugzilla number being referenced rather than using its alias here.
