### ISSUE TITLE
Add an Invalid bool to Experiment

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#152]
We need a way to denote that an experiment was invalid for whatever reason, and I think this should live outside of the state transitions so we'll just make it a bool.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-82)

**Comment by shell1** [comment]
moving this beyond lifecycle as well.  need more thought on who would be using this (data scientists, product, normandy) and their user cases for needing it - to make the implementation as useful as possible.
