### ISSUE TITLE
Delivery Console and Normandy API links no longer work

### ISSUE THREAD

**Issue by mythmon** [mozilla/experimenter#1542]
The Delivery Console and Normandy API links don't actually link to their respective sites now. They don't have an `href` attribute, and so only reload the page.

![image](https://user-images.githubusercontent.com/305049/62737249-34247f80-b9e4-11e9-9cf5-7d15e86c15da.png)

**Comment by uhlissuh** [comment]
Woops! Thanks @tiftran for fixing this..
