### ISSUE TITLE
Show pref rollout status (current, historical, future)

### ISSUE THREAD

**Issue by rkothari19** [mozilla/experimenter#1588]
During RDL rollout via Normandy in 61, it was hard to deduce what the rollout rate was at any given point in time. For Normandy rollouts, relman team will be interested in knowing details like:

1. Which pref rollouts have occurred in the past?
2. Which pref rollout is currently in progress? Rollout cadence, channel, firefox version
3. Pref rollouts that are configured and planned for future.
4. For each rollout, there should be a status like ongoing, finished, planned, testing, etc.

**Comment by jaredlockhart** [comment]
I think everything on this list is now covered, so I'm gonna close this.  @rkothari19 If you still have any feature requests for rollouts in experimenter, feel free to either reopen this or file a new ticket!
