### ISSUE TITLE
Move Normandy/Recipe fields into related model

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#1600]
We need to create a new NormandyRecipe model in a new app called Normandy, with the following fields:

- slug (from normandy_slug)
- recipe_id (from normandy_id)
- enabled
- enrolling (from is_paused)

We'll need to update the forms to manage that foreign keyed object and write a data migration to move existing experiments to the new structure.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-86)

**Comment by jaredkerim** [comment]
Blocked on https://github.com/mozilla/experimenter/issues/1597
