### ISSUE TITLE
Change line length to 90 characters

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1618]
In the course of exploring mypy I had to change the max line length from 80 to 90 characters and I think it's just a generally better length so I think we should adopt it for the project in general.

**Comment by Patil2099** [comment]
@jaredkerim Can I work on this? Where do I have to make changes?
Thanks

**Comment by jaredkerim** [comment]
@Patil2099 yes absolutely!  Start by forking the repo, then create a branch in your fork, and make the following changes:

https://github.com/mozilla/experimenter/pull/1610/files#diff-f1de0b81812b935bca33c5d72cf10fe1R3

https://github.com/mozilla/experimenter/pull/1610/files#diff-b67911656ef5d18c4ae36cb6741b7965R44

https://github.com/mozilla/experimenter/pull/1610/files#diff-b67911656ef5d18c4ae36cb6741b7965R47

Then to make sure they worked run:

    make code_format

This will automatically apply the changes and reformat the code.  Then run

    make check

to make sure that everything passes all the static checks.  If everything passes, then create a commit formatted like `Changed line length to 90 characters fixes #1618` and submit a pull request and tag me for review.  Thanks for helping 😄

**Comment by sviho** [comment]
Hi @jaredkerim! Can I work on this?

**Comment by jaredkerim** [comment]
@sviho Absolutely!  Follow the instructions in the README to get the docker environment setup and your tests passing using `make check` then follow the instructions above, feel free to ping me here if you get too stuck :)

**Comment by jaredkerim** [comment]
@sviho Thanks for contributing :D 

Feel free to pick up anything marked as Good First Bug:

https://github.com/mozilla/experimenter/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Bug%22
