### ISSUE TITLE
Add the ability to clone experiments

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#163]
We need the ability to clone existing experiments to relaunch rejected experiments.

**Comment by shell1** [comment]
It should copy over the study field information - but no comments or checklist approvals.

Another use case is people launching a slight variant - so copying over information.  Requesters keep asking to just "tweak" the existing study in ways that are often not a minor impact for data science.  These should be a new study.  We want to make it easy to get right.

**Comment by uhlissuh** [comment]
fields in question:
bugzilla_id,
data_science_bugzilla_url,
feature_bugzilla_url
