### ISSUE TITLE
Celery integration tests?

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#1634]
https://github.com/mozilla/experimenter/issues/1631 happened because we mock out all of the celery/redis boundaries in our unit tests, I wonder if there's some way for us to meaningfully integrate test that so that we could've caught this sooner?

**Comment by jaredkerim** [comment]
Actually it occurs to me that using `mypy` to type check the task arguments would've also caught this.  Another point in favour of https://github.com/mozilla/experimenter/pull/1610

**Comment by jaredkerim** [comment]
This does appear in the following test case:

https://testrail.stage.mozaws.net/index.php?/cases/view/391791&group_by=cases:section_id&group_order=asc&group_id=50929

So it might be sufficient to just convert that test exactly as its written into an integration test to cover the that specific case of updating bugzilla, but if there are other celery tasks that are not directly reflected in the UI then perhaps we should cover those.

**Comment by jaredlockhart** [comment]
I was on something when I thought this was a good idea.
