### ISSUE TITLE
Update html ids for more effective integration testing

### ISSUE THREAD

**Issue by uhlissuh** [mozilla/experimenter#1635]
in the integration tests we do things like `"#formset > div:nth-child(5) > div:nth-child(3) > div:nth-child(1) > h4:nth-child(1)` to get an element... but we could also just make these elements have logical ids so that we aren't relying so much on the structure of the DOM staying the same into the future when we want to grab these elements.

**Comment by Adrian-Tamas** [comment]
@uhlissuh Hi. I have some limited experience with jinja2 templating and flask and I would like to help on this if you can give me direction into the area I can start in.

**Comment by uhlissuh** [comment]
@Adrian-Tamas, hey! have you got this project running locally yet? This bug is really going to be about looking at the integration tests and seeing the places where we can add an id to an HTML element so that the CSS selector can be made much more simple. If you specifically check out the file experiment_design.py within the integration folder, you will see lots of really complicated selectors relying on locating children of divs, etc. Go find those elements in the templates that we are trying to grab, and add an id to them, then go back into the integration test and update the selector to grab the element by id instead! Does that make sense?

**Comment by jaredkerim** [comment]
I think this is essentially done now but this ticket didn't get closed so I'm closing it.
