### ISSUE TITLE
Change form section descriptions to describe role

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#1639]
We should change the section descriptions for each form field to declare which role (data science, experiment owner (pm, epm, em)) is responsible for which page.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-91)

**Comment by shell1** [comment]
Overview blue box description saying: "Requester (PM, Engineering, or EPM) provides the basic information to plan a project."

Current population section will become Timeline & Population with blue box description saying: "Data Science works with the requesting team to define the population and project timeline." 

Objectives and analysis blue box description saying: "Data Science works with the requesting team to define the outcomes and how they'll be measured."

Risk and Testing blue box description saying: "Requester (PM, Engineering, or EPM) answers questions to identify risks, define the test plan, and work with QA to capture the test results".

New Design Section blue box description saying:  "Requester works with Data Science to define the project and each branch".
