### ISSUE TITLE
Filter criteria missing from recipe: US geo wasn't automatically added to recipe

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1656]
US geo wasn't added to recipe automatically...

https://experimenter.services.mozilla.com/experiments/activity-stream-pkt-new-tab-release69-layout-holdback-1573312/

Rehan investigating  why.

**Comment by shell1** [comment]
because it was cloned - dupe

**Comment by jaredlockhart** [comment]
Duplicate of #2345
