### ISSUE TITLE
Multiple 'Created Experiment' changelogs in history

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1670]
In this experiment we see many 'Created Experiment' entries in the history, that doesn't seem right:

https://experimenter.services.mozilla.com/experiments/activity-stream-pkt-new-tab-release69-layout-holdback-1573312/

**Comment by tiftran** [comment]
@jaredkerim can't seem to reproduce this locally, is it possible to have access to the admin side in production, read only would sufficient would like to see what was recorded in the change log?

**Comment by jaredkerim** [comment]
Oh heck @tiftran how were you not already superuser on Experimenter admin, just added you and @uhlissuh both.
