### ISSUE TITLE
Branch pref value should not be required in admin

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#1682]
That field should definitely be optional in the admin because it's not relevant at all to addon experiments.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-94)

**Comment by jaredkerim** [comment]
And the following fields:

- firefox_channel
- firefox_min_version

**Comment by tiftran** [comment]
no longer able to reproduce, closing
