### ISSUE TITLE
Preview intent-to-ship email

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#1703]
It's not clear to a user what content will end up in the intent-to-ship email. It would be nice to be able to preview the intent-to-ship email before one hits "send," just so I can make sure the idiot garbage I've typed into Experimenter is actually the content I want to publish.

**Comment by jaredkerim** [comment]
@tdsmith Don't be so hard on yourlife, you have the best idiot garbage <3

**Comment by shell1** [comment]
We'll revisit in 2021 depending on the state of things (how much using).  Good idea - but not likely 2020 radar.
