### ISSUE TITLE
Add Normandy Multi Pref Recipe

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1717]
We can implement the Recipe Serializer for Multi-Pref recipes without needing the UI for it because we can now use it for even the single recipe case.  So let's implement the new schema as a separate set of serializers, and then we'll follow a simple rule to determine which serializer to use:

Min Version >= 68: use MultiPrefRecipeSerializer
Else: use SinglePrefRecipeSerializer

Multi pref recipe schema: https://normandy.cdn.mozilla.net/api/v3/action/9/

**Comment by mythmon** [comment]
The original issue listed that the multi-pref recipe should be used for versions 69 and above. After discussing this with @glasserc, I adjusted the original message to be version 68 and above, to reflect when the feature is actually available.

**Comment by jaredkerim** [comment]
This is important to land ASAP so we should get this working for 2.41.0 I think.
