### ISSUE TITLE
Clear variant slugs when cloning

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1733]
When we clone an experiment we need to remove the variant slugs so that they can be regenerated by the new names of the branches in the cloned experiment.

**Comment by uhlissuh** [comment]
oops i didn't mean to close this!

**Comment by jaredkerim** [comment]
From slack chatting with @uhlissuh we gotta remember to populate the variant slugs when we move to ready to ship in case the user never goes back to set them.

**Comment by jaredkerim** [comment]
D'oh! We can't have empty slugs, so instead we'll just update the variant slug on every variant save (rather than only once at creation time)
