### ISSUE TITLE
Rename Experimenter to Intaker

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/experimenter#1743]
Experimenter is doing intake for rollouts and non experiment things.  It's time to rename the project.  @shell1 and I decided "intaker" is a good name.  Plan to make it happen: 

* [ ] Change naming in UI
* [ ] 3xx experimenter.services.mozilla.com to 
* [ ] Set up intaker.services.mozilla.com as the new DNS name
* [ ] Figure out how to notify people of this change -- quick presentation @  product/cross functional meetings? 
* [ ] ???

**Comment by jaredkerim** [comment]
# BLOCKED - WE'RE NOT CALLING IT INTAKER

**Comment by jaredkerim** [comment]
![200](https://user-images.githubusercontent.com/119884/66863240-965bac80-ef60-11e9-970b-c26b7150a7b7.gif)

**Comment by mostlygeek** [comment]
![200](https://media.giphy.com/media/RfNI9AOHI8ioen31Rr/giphy.gif)

**Comment by jaredlockhart** [comment]
Experimenter's new name is..... Experimenter!  Unless we have a strong impetus to rename it I think we should just keep it the same.
