### ISSUE TITLE
Rollout Design section

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1745]
Design section:
At the top of the Design section (above the "Design" field) - add a new "Playbook" field.  The help should point here https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90737068#StagedRollouts/GradualRollouts-Playbooks
drop down options are: 

- Low Risk Schedule
- High Risk Schedule
- Marketing Launch Schedule
- Custom

In what is the branch section now - we just need the follow fields (so no complex logic)

- Description

### Addon 
- URL with the Signed Release Add-on 

### Pref
- Pref Name
- Pref Type
- Pref Value
- ~~Pref Branch~~ (edit: Roll outs are always default branch. -mythmon)

**Comment by shell1** [comment]
@mythmon I'm tempted to leave in branch so we catch when they are on user branch.  Even if the drop down ONLY says default as the selectable option (with User grayed out)... so that they raise concerns if they need User.

**Comment by mythmon** [comment]
That fits well with the guardrails idea of the project. It helps guide users towards the right choice, and throws up a warning when there are problems. Sounds good to me.
