### ISSUE TITLE
Changing wording on risk questions so they work for other types

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1746]
The few questions that didn't need any changes are in italic below.  For the others I mostly changed "experiment" to "project".  I changed the wording on a few questions (ex: change 1% to "over a million).  I added a few new questions in bold.

Is this project sensitive and/or internal only? 

Are there any partners or external services involved in this project?

_Does this have a high risk to the brand?_ 

Does this require delivery outside the scheduled Normandy change window?  --- this is a big change from previous questions "Does this experiment require uplifting code or a rushed experiment schedule?".  Please change the help to direct users https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-NormandyChangeWindow

Does this project affect more than 1 million Release users? 

Does this project have possible negative impact on revenue? 

_Do you need data that doesn’t exist in telemetry already?_ 

_Are you using Category 3 or 4 data?_

Does this project impact teams outside of your own? 

Is UX a significant part of this project? 

Is this a revision of a previous experiment?

Is this project Complex / Technically Risky? 

NEW Questions:
**Does this need security review, consulting, or security testing?**  help should like to https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-Risk and a YES answer should make the Security Review mandatory

**Does this content involve encryption or VPN technology?**  help should like to https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-Risk and a YES answer should make the Legal Review mandatory

**Comment by jaredlockhart** [comment]
This is all done now, everything is called 'delivery'.
