### ISSUE TITLE
Cleaning up "Experiment" word for items that work across experiments and other types

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1762]
Overview section
Change Experiment Owner to "Primary Owner" - this can be done for all types (experiments and all new ones - the "Experiment" isn't needed.

Timeline and population section
Remove "Experiment" from "Experiment Timeline" header - so just "Timeline"
Remove "Experiment" from "Experiment Population" header - now just "Population"

**Comment by uhlissuh** [comment]
I think this was already taken care of in another PR that changed all the instances of the word "experiment" to delivery."

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/issues/1997
