### ISSUE TITLE
Modify integration tests to alert on failed form validation

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#1768]
If one of our integration tests attempts to fill out a form, and the form fails validation, then we should send some kind of alert in the test output that that's what happened.  Right now it'll just say it timed out waiting for the next page to load, but this makes it harder to figure out why the test failed.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-101)

**Comment by jrbenny35** [comment]
We discussed one way to do this which is worth investigating. 

@jaredkerim -> "if the url stays the same, and some error class becomes present?"

I think this could work, we could also do a quick scan of the page looking for the error messages that appear when a form is filled incorrectly and raise an error. That error will trigger that test to fail and the screenshot will be be attached to the html report.
