### ISSUE TITLE
Error on list page when type not in query parameters

### ISSUE THREAD

**Issue by uhlissuh** [mozilla/experimenter#1777]
https://sentry.prod.mozaws.net/operations/experimenter-prod/issues/6511014/

```
KeyError: ''
(21 additional frame(s) were not displayed)
...
  File "experimenter/experiments/filtersets.py", line 256, in get_type_display_value
    for type in self.data.getlist("type")
  File "experimenter/experiments/filtersets.py", line 256, in <listcomp>
    for type in self.data.getlist("type")

KeyError: ''
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-102)

**Comment by mythmon** [comment]
This happened when I open a link I have bookmarked that includes a parameter `type=`, like this:

```
https://experimenter.services.mozilla.com/?type=
```

I think that URL that I bookmarked was generated by a previous version of Experimenter.
