### ISSUE TITLE
Use form data instead of state to serialize form and submit to server

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1790]
Track the state of each input in its local DesignInput component

**Comment by uhlissuh** [comment]
Started this. getting value state into designinput isn't too complicated, but had trouble with FormData which was proposed as the mechanism for getting all of these values to the fetch. form data doesn't group the variants into something  we would want... like `variants: [{name1, ratio1, description1, value1}]` everything is flat. 

<img width="360" alt="Screen Shot 2019-10-23 at 4 51 42 PM" src="https://user-images.githubusercontent.com/1551682/67442377-6c843480-f5b5-11e9-9365-f03bbf0a9cac.png">

 would love some ideas for how to address this problem.

**Comment by uhlissuh** [comment]
i pushed a branch up if anyone is curious https://github.com/uhlissuh/experimenter/tree/designinput-controls-state

i only made modications for pref experiments... so if you are looking at this branch look at a pref exp.

**Comment by jaredkerim** [comment]
@uhlissuh check this out

https://www.npmjs.com/package/form-serialize#indexed-arrays
