### ISSUE TITLE
[Dev] The sections from the "Design" card are not displayed for new experiments

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1833]
**[Affected versions]:**
- Firefox Release 70 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac

**[Prerequisites]:**
- You are logged in your LDAP account on Experimenter Dev [website](https://dev.experimenter.nonprod.dataops.mozgcp.net/).

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://dev.experimenter.nonprod.dataops.mozgcp.net/"
2. Click the "Create Experiment" button.
3. Complete the mandatory fields from the "Overview" section and save the experiment.
4. Click the "Edit" button from the "Branches" section.
5. Observe the card's content.

**[Expected result]:**
- All UI/sections are displayed and rendered correctly.

**[Actual result]:**
- The sections from this card are not displayed.

**[Notes]:**
- Attached is a screen shot of the issue:
![DesignCard](https://user-images.githubusercontent.com/40061643/67769844-d2f9ce80-fa5d-11e9-8eb7-79f7a5c312cd.PNG)

**Comment by shell1** [comment]
verifying - but believe this has since been closed.
