### ISSUE TITLE
[Dev] The design card cannot be saved after editing an existing Pref-Flip experiment

### ISSUE THREAD

**Issue by Martin-Robert** [mozilla/experimenter#1834]
**[Affected versions]:**
- Firefox Release 70.0

**[Affected Platforms]:**
- All Windows
- All Mac

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://dev.experimenter.nonprod.dataops.mozgcp.net/" website.
- Have an already created Pref-Flip experiment on the Experimenter dev website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://dev.experimenter.nonprod.dataops.mozgcp.net/".
2. Open the created experiment from prerequisites.
3. Click the "Edit" button from "Branches" section.
4. Make sure that all the fields are completed with valid data.
5. Press "Save Draft" button and observe the behavior.

**[Expected result]:**
- The branch is being saved.

**[Actual result]:**
- Nothing happens and there is no error message on FE.

**[Notes]:**
- This issue can be reproduced with any "Pref Type" options from "Firefox Pref" section.
- This issue can also be reproduced if you add as many Branches as you want, just make sure that the added value of the "Branch Size" is equal to 100.
- The PUT call made after pressing "Save Draft" is failing with 500, you can see the cURL beneath:

curl "https://dev.experimenter.nonprod.dataops.mozgcp.net/api/v1/experiments/celery-test/design-pref/" -X PUT -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0" -H "Accept: */*" -H "Accept-Language: en-US,en;q=0.5" --compressed -H "Referer: https://dev.experimenter.nonprod.dataops.mozgcp.net/experiments/celery-test/edit-design/" -H "Content-Type: application/json" -H "Origin: https://dev.experimenter.nonprod.dataops.mozgcp.net" -H "Connection: keep-alive" -H "Cookie: _ga=GA1.2.823804811.1572348437; _gid=GA1.2.1251952834.1572348437; session=p1oYDjWnPXFpCcss4Bm5rg..|1572437141|jO7rD4L0DdflWwsCx1OTEVm_CEo.; csrftoken=yWaRkG1VP7yb58GVKtaT4Ema31C6AWqIS4a4PyKkClQSob7S2F5LwFW3EPDFtLmu; _gat_gtag_UA_123143157_1=1" -H "TE: Trailers" --data "{""pref_key"":""vsdaasdv"",""pref_type"":""integer"",""pref_branch"":""default"",""variants"":[{""ratio"":""100"",""name"":""Control"",""description"":""Control"",""value"":""3"",""is_control"":""true""}]}"

**Comment by uhlissuh** [comment]
I checked this, and I believe this bug got fixed as part of another ticket/fix. I am not observing this behavior as of right now.
