### ISSUE TITLE
It looks like some experiments are reporting "enrollment complete" after launching

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1843]
https://experimenter.services.mozilla.com/experiments/webrender-intel-performance-70/ and
https://experimenter.services.mozilla.com/experiments/activity-stream-pktnewtab-releasesyndicatedboost-confirmation/ looked to still be enrolling on Oct 30th - despite showing enrollment complete pill.

**Comment by mythmon** [comment]
I manually marked these experiments as not paused via the Experimenter admin. I think we still don't know why they got paused in the first place.
