### ISSUE TITLE
The sections from the "Design" form are removed after clicking the "Add Branch" button while having an error on the page

### ISSUE THREAD

**Issue by Martin-Robert** [mozilla/experimenter#1857]
*[Affected versions]*
- Firefox Release 70.0

*[Affected Platforms]*
- All Windows
- All MacOS

*[Prerequisites]*
- You are logged with your LDAP account on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- Have an experiment created on Experimenter stage.

*[Steps to reproduce]*
1. Open the browser with the profile from prerequisites and navigate to 
"https://stage.experimenter.nonprod.dataops.mozgcp.net/".
2. Open the experiment from prerequisites.
3. Click the "Edit" button from "Design" section.
4. Fill in "Branch Size" text field with invalid data ex: 101.
5. Click the "Save Draft" button.
6. Click "Add Branch" button and observe the behavior.

*[Expected result]*
- A new branch is added.

*[Actual result]*
- The sections from the page are removed.

*[Notes]*
- This issue can also be reproduced if you fill with invalid data any field that is validated when pressing "Save Draft".
- The sections are re-displayed.
- Attachments:

![2019-10-31_17h15_30](https://user-images.githubusercontent.com/55738964/67961146-f8c0d800-fc03-11e9-9f75-52ab09a21607.gif)
 if the page is refreshed.

**Comment by jaredkerim** [comment]
Thank you @Martin-Robert this is exactly what I was looking for!
