### ISSUE TITLE
The branch name can wrongly be saved with special characters

### ISSUE THREAD

**Issue by Martin-Robert** [mozilla/experimenter#1861]
*[Affected versions]:*
- Firefox Release 70.0

*[Affected Platforms]:*
- All Windows
- All MacOS

*[Prerequisites]:*
- You are logged with your LDAP account on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- Have an experiment created on Experimenter stage.

*[Steps to reproduce]:*
1. Open the browser with the profile from prerequisites and navigate to 
"https://stage.experimenter.nonprod.dataops.mozgcp.net/".
2. Open the experiment from prerequisites.
3. Click the "Edit" button from "Design" section.
4. Fill in "Name" section with special characters.
5. Click the "Save Draft" button.
6. Observe the behavior.

*[Expected result]:*
- There is an error message displayed underneath "Name" text field.

*[Actual result]:*
- The draft is successfully saved

*[Notes]:*
- Attachments:

![2019-10-31_17h51_25](https://user-images.githubusercontent.com/55738964/67963742-c31dee00-fc07-11e9-82c1-413f0941e6c5.gif)

**Comment by tiftran** [comment]
closing, issue will be addressed with changes for #1879 as well
