### ISSUE TITLE
Branch size must be between 1-100

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1863]
You can currently save two branches with sizes 0 and 100 and it'll validate, branch size should be between 1-100.

**Comment by uhlissuh** [comment]
between 1 and 99 methinks?

**Comment by mythmon** [comment]
It's valid to have a single branch that is 100%, in the case of rollouts or some specific types of experiments.

**Comment by uhlissuh** [comment]
@mythmon ... oh interesting...

**Comment by uhlissuh** [comment]
@mythmon  so 100 should be an allowed value.
