### ISSUE TITLE
Removing a branch deletes all values from remaining branch

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1882]
Steps to reproduce

1) Create three branches
2) Fill them all in with invalid data
3) Submit to server, get errors
4) Delete the middle branch
5) The last branch has all its fields emptied out

![branch-fields](https://user-images.githubusercontent.com/119884/68056337-3d627700-fcc9-11e9-9a4c-07d6d4f5037a.gif)

**Comment by shell1** [comment]
@tiftran do you think Felix is hitting something related to this bug?  He asked about this in ask-experimenter "Possible Experimenter bug? Trying to edit https://experimenter.services.mozilla.com/experiments/fingerprinting-implementation-retention-study-v1/edit-design/, deleting branches and renaming some from the 5 branches to this screenshot - and the changes are not saving."

![image](https://user-images.githubusercontent.com/8192232/68257377-e7067880-ffe7-11e9-936b-da8fe5d756f5.png)

**Comment by rehandalal** [comment]
@shell1 as I understand this has not been rolled out to prod yet. It is only on stage so if Felix is having the issue on prod it would be unrelated.

**Comment by tiftran** [comment]
@shell1  separate bug has been created for this issue https://github.com/mozilla/experimenter/issues/1894
