### ISSUE TITLE
Addon Experiment Summary Page shows pref info?

### ISSUE THREAD

**Issue by tiftran** [mozilla/experimenter#1893]
Is this a bug?
![image](https://user-images.githubusercontent.com/25379936/68259642-49af4280-ffef-11e9-82e9-9f8a05c1d0ff.png)

Edit: originally filed cause I noticed it was on production https://experimenter.services.mozilla.com/experiments/fingerprinting-implementation-retention-study-v1/ haven't really looked at it but might be a corner case where pref-flip -> clone -> addon?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-113)

**Comment by uhlissuh** [comment]
I've noticed this for a long time... I suspected it had to do with the fact that when we create dummy experiments we randomly fill in all the info for all types of experiments so these fields show on the detail page. But in reality, a user would never be filling out the fields for all the different experiments, so it's not in practice much of a problem. This is what I always assumed about this. :)
