### ISSUE TITLE
Remove non ldap emails from database

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#1906]
Because of a configuration error, we introduced many emails to the database for non mozilla ldap users.  These accounts are not necessary and add unnecessary noise to any user selection drop down, so we should write a data migration to remove them.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-114)
┆Issue Number: EXP-114

**Comment by jaredkerim** [comment]
Note:

There's more than just the @mozilla domain we need to keep (softvision, pocket), but let's make sure
