### ISSUE TITLE
Remove type from Design serializers

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1919]
We left the 'type' field in the design serializers from an earlier design of the API but we should get rid of those.

https://github.com/mozilla/experimenter/blob/master/app/experimenter/experiments/serializers.py#L606

**Comment by jaredkerim** [comment]
https://github.com/mozilla/experimenter/blob/master/app/experimenter/experiments/serializers.py#L527-L529

**Comment by uhlissuh** [comment]
this is a duplicate of another issue that's already fixed.
