### ISSUE TITLE
Include data scientist as owner for `Owned Experiments`

### ISSUE THREAD

**Issue by teonbrooks** [mozilla/experimenter#1937]
Would it be possible to have the Owned Experimenter populated when a data scientist is assigned. I believe that it is currently targeting just the listed Experimenter Owner, but often this is a partnership of both the experiment owner and the data scientist.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/EXP-116)

**Comment by shell1** [comment]
made it so Data scientists get all the same email updates as the owner.  If they are the same role (exception not the rule) - DS can add themselves as experiment owner.

**Comment by teonbrooks** [comment]
@shell1, do you know if there is a way to have it update the link in the upper right corner with the counts, that's been the easiest navigation point for me to find experiments I'm involved with

**Comment by shell1** [comment]
just slacked as I don't understand how the use case is different than filtering for the DS owner https://experimenter.services.mozilla.com/?ordering=-latest_change&search=&status=&firefox_channel=&firefox_version=&owner=&analysis_owner=150&experiment_date_field=&date_range_after=&date_range_before=
