### ISSUE TITLE
Search checkboxes are confusing

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#1985]
Some of the search checkboxes ("show archived experiments") expand the possible result set while other options with identical language ("show subscribed experiments") limit the possible result set.

It would be helpful to use different language for these cases -- e.g. "include" vs "limit to", or "also show" vs "only show".

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-119)

**Comment by jaredkerim** [comment]
Good point @tdsmith we should improve the language on that!
