### ISSUE TITLE
Use browser field required check for DesignInput

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1993]
We might be able to tell DesignInput to use the browsers form field required check to prevent people from saving the design page without required fields.  This will just make the UI a little more consistent with the other pages.  I think all fields visible on the design page should be required for now.

**Comment by uhlissuh** [comment]
I took a stab at this for a bit... nothing super easy jumped out (easy as defined by just throwing a required in there somewhere)... it might be a little more elaborate to get this implemented with React Bootstrap. I think this link is getting at what we are trying to do... https://react-bootstrap.github.io/components/forms/#forms-validation-native 

I'm willing to pursue it more, but the ticket didn't make it sound like it direly wanted.... so before I spend too much more time doing this, figured I'd check in to see how much this is really wanted versus time spent tinkering.

**Comment by jaredkerim** [comment]
Actually I think we would have to implement custom logic ourselves to block the API call from sending if the fields are blank, then it's more work than it's worth.  Thanks for investigating @uhlissuh !
