### ISSUE TITLE
Concerns about assertCountEqual in serializer tests, and elsewhere.

### ISSUE THREAD

**Issue by uhlissuh** [mozilla/experimenter#2030]
there's been a few times recently I've noticed tests using assertCountEqual not behaving the way I would expect. 

Here's an example:

```
def test_serializer_outputs_expected_schema(self):
        experiment = ExperimentFactory.create_with_variants(
            type=ExperimentConstants.TYPE_ADDON
        )
        experiment.is_branched_addon = True
        experiment.save()

        serializer = ExperimentDesignBranchedAddonSerializer(experiment)

        self.assertCountEqual(
            serializer.data,
            {
                "type": experiment.type,
                "is_branched_addon": True,
                "variants": [
                    ExperimentVariantSerializer(variant).data
                    for variant in experiment.variants.all()
                ],
            },
        )

```

this test was passing even though I had removed `type` from the base serializer already. If type isn't in the serializer, serializer.data should not have `"type": experiment.type` in it, and this test should fail, but instead it passes.

**Comment by uhlissuh** [comment]
if you make this test use assertEqual instead of assertCountEqual, and remove the type (as it shouldn't be there because I'm removing type) this test then fails with this: 
```
 self.assertEqual(
AssertionError: {'is_[31 chars]s': [OrderedDict([('addon_release_url', 'https[1024 chars])])]} != {'is_[31 chars]s': [{'description': 'Party prepare decision k[1132 chars]i'}]}

```

**Comment by tiftran** [comment]
Did some digging and I think we're misusing CountEqual 😬 . I don't think CountEqual is intended for dictionaries, as it's equivalent to` assertEqual(Counter(list(first)), Counter(list(second)))` stated [here](https://docs.python.org/3.2/library/unittest.html#unittest.TestCase.assertCountEqual). Using countEqual on dicts would mean that we're only checking the keys match. Not sure why you're getting the behaviour of removing entries and it being fine though....

The original intention of using CountEqual is to avoid ordering test failure which for your example would be for the order of variants.

Maybe this would mean we need to test each field separately? or maybe pop variants out and test that the rest is equal?

**Comment by uhlissuh** [comment]
Oh so you mean that the error above might just be an ordering problem? It's hard to tell from the bit of readout.
