### ISSUE TITLE
multi pref form, add pref on last variant, everything goes away!

### ISSUE THREAD

**Issue by uhlissuh** [mozilla/experimenter#2035]
![bug3](https://user-images.githubusercontent.com/1551682/70301978-bb2a0e80-17b0-11ea-9e66-79ba137e06a4.gif)

to reproduce:

go to multi pref design page. 

click add pref button on LAST variant. must be the last one. 

everything goes away.

if you add prefs on the first variant first, then go to add a pref on the last one, all is fine... must be in exact order as written above.

**Comment by jaredkerim** [comment]
Rehan suggests using default props
