### ISSUE TITLE
Integer type prefs being exported as strings

### ISSUE THREAD

**Issue by mythmon** [mozilla/experimenter#2080]
On at least the delivery linked below, the values of the integer pref are being reported as strings in the API. Delivery Console picks this up, and nothing logs any errors. It's a thing that we almost tripped over while deploying recipes today.

https://experimenter.services.mozilla.com/api/v1/experiments/separate-search-default-in-private-browsing/recipe/

**Comment by tiftran** [comment]
I think https://github.com/mozilla/experimenter/pull/2141 should have solve this, closing issue
