### ISSUE TITLE
Fixes for deployment

### ISSUE THREAD

**Issue by jbuck** [mozilla/experimenter#21]
Just a running list I need to put somewhere

- [x] Need endpoints for `__version__`, `__heartbeat__`, and `__lbheartbeat__`
- [x] Need to add user within container
- [x] Switch to mozlog output
- [x] Need to have option to disable `DEBUG`
- [x] Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.
  - [ ] Add option for `USE_X_FORWARDED_HOST`
- [ ] Maybe add `SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')`
- [ ] Add S3 bucket to resources
- [ ] Add lambda job to resources to sync S3 bucket
- [ ] Add VPN

**Comment by jaredkerim** [comment]
[x] Add uwsgi

**Comment by jaredkerim** [comment]
Those last 3 items I don't think will get done since we're not adding VPN or S3 support.
