### ISSUE TITLE
Switch to flat design

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2172]
I'm no designer, and I'm getting a little tired of the grey/white bubble look, we could try poking around at a more flat design, something the screenshot below.  That was a couple lines of html/css change (taking out the background colour from body and remove a few borders).  If it's a couple lines and makes things a little more modern, there's no harm in doing it.  It probably requires a little playing around with to make the spacing a little nicer.

![Screenshot_2020-01-14 Seamless incremental portal](https://user-images.githubusercontent.com/119884/72379293-22f14480-36e1-11ea-8672-69b9a974114c.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-125)

**Comment by jaredlockhart** [comment]
Actually I realize I basically just want it to look exactly like this github page.

**Comment by uhlissuh** [comment]
white background!
