### ISSUE TITLE
Changing DS from bugzilla to Jira

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#2190]
Change the "Data Science Bugzilla URL" to "Data Science Jira Ticket" - it will be a URL of this form... though if you match it only needs to match to "https://jira.mozilla.com/browse/" - NOT The "DS-".  ex: https://jira.mozilla.com/browse/DS-352

When this is changed - it should change over from writing to the data science bugzilla URL when a draft is created and states are changed - and now write to that Jira URL.  Jira expertise in house: Majken Longlade and Juli Sofijski (mgr). 

Please change the experimenter help to say the following:
"Provide a link to the DS Jira ticket that was filed with the Data Science team that tracks this delivery. If you have not already filed a ticket with Data Science, you can do that **_here_**.

Example: https://jira.mozilla.com/browse/DS-352"

The **_here_** should link to https://mana.mozilla.org/wiki/display/PM/Data+Science+Jira+documentation

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-127)

**Comment by tiftran** [comment]
### NOTE: currently experiment dev, stage, prod all points to the JIRA prod instance.
When this is worked in, will need to keep in mind that we would need to have JIRA dev/stage instance so that we don't fill JIRA prod with junk updated

**Comment by shell1** [comment]
won't be doing for legacy - but what syncing is wanted for Nimbus here?  talk with Emily/jmok on that.
