### ISSUE TITLE
Date Math issues for various phases

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/experimenter#2202]
<img width="786" alt="Screen Shot 2020-01-24 at 11 39 45 AM" src="https://user-images.githubusercontent.com/953153/73090691-73656080-3e9e-11ea-803a-ab5e38236a36.png">

I was looking at some past experiments and noticed the durations for Total Duration and Observation were both off by quite a bit (this one was https://experimenter.services.mozilla.com/experiments/activity-stream-contextual-onboarding-experiment-for-dynamic-triplets-on-newtab-in-firefox-72/)

**Comment by jaredlockhart** [comment]
Oh yep good catch 👍

**Comment by jaredlockhart** [comment]
Use the same method we use for the start/end dates here:

https://github.com/mozilla/experimenter/blob/master/app/experimenter/experiments/models.py#L440-L455

and make sure to update it on the detail page the list page

**Comment by jaredlockhart** [comment]
Also testing those methods might be a good use cases for more parameterized tests!
