### ISSUE TITLE
End to End Test: Generic Experiment

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2222]

**Comment by jrbenny35** [comment]
Gave this a try and got this error: 
``` Experimenter failed to create a Bugzilla Ticket for your experiment. Please contact an Experimenter Administrator on #ask-experimenter on Slack. ```

Looks like we will have to create a server to catch bugzilla calls. That would also help us confirm that the service is working.

**Comment by jrbenny35** [comment]
Also, not sure how to solve: ```The Data Science Ticket was UNABLE to updated with experiment_info ```

**Comment by jrbenny35** [comment]
@jaredlockhart do we know what we want to actually test with this? Maybe a POST message or something?

**Comment by jaredlockhart** [comment]
So one thing we could do is make a tiny python server that just mocks out the bugzilla APIs we care about....... But I don't think it's that important.  We're scaling back a bunch of our bugzilla integrations so I'm not sure it's worth the effort.

It's basically trying to do two things

1) create a new bugzilla ticket for the experiment
2) update the data science buzilla ticket that's provided

#1 it will try to do and fail with the error you provided, but as long as you can get through the rest of the flow I don't think it matters.

#2 is gone now, if you update to the latest master now it asks for a Jira ticket URL and then there are no API calls after that.  

So yeah I'd say just ignore it if you can.

**Comment by jrbenny35** [comment]
So we want to get to the point that says "Send to Normandy"?

**Comment by jrbenny35** [comment]
JSON blob can be found at ```<experimenter_url>/api/v1/<slug>/recipe/```
