### ISSUE TITLE
Move writeable APIs into a separate root API path

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2250]
To help keep teh distinction between read only and writeable APIs clear, we should move all the writeable ones (used for design page now and soon timeline/pop page) into a separate root API path like `/api/v2/` or something.

**Comment by mostlygeek** [comment]
It sounds like from the issue description that we want to make it clearer for people which APIs are readable/writable based on the URI.   

Seems like we're looking to expand experimenter's API and this is a design question.  I thought we were talking about a graphql API.   I like that direction more than more REST api design.

**Comment by jaredlockhart** [comment]
And in teh course of doing this maybe we can update the swagger docs to split the api endpoints into groups that are more clearly labeled as 'public' (v1) and 'private' (v2) so that it's clear to external parties which apis they can call.
