### ISSUE TITLE
Intent to ship email won't sent with HTTPS Everywhere add-on

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#2253]
Arthur hit this when trying to ship "send intent to ship email".

I don't believe this is a major thing -but wanted engineering's thoughts?  I'm thinking edge case and we can just let someone know if they hit it.  

![image](https://user-images.githubusercontent.com/8192232/74045840-55a9f800-4982-11ea-85ce-dd941072de77.png)

**Comment by shell1** [comment]
Arthur also said: "probably indicates a non-https request is being sent. To be clear, I only have N=1 here so it could be something stochastic and unrelated."

**Comment by jaredlockhart** [comment]
Interesting, this isn't very actionable without more information, I'm going to close this for now and if it keeps happening we can reopen it.  The best thing to do is screenshot the network tab of the browser if this happens again.
