### ISSUE TITLE
History broken for rollouts

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2255]
Just noticed this if you edit the rollout design page:

<img width="208" alt="Screenshot 2020-02-07 12 03 42" src="https://user-images.githubusercontent.com/119884/74049347-ee03a500-49a1-11ea-8770-3ec695c70a5a.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-134)

**Comment by tiftran** [comment]
@jaredlockhart was only able to reproduce when rollout is set to Live via admin while required fields are incomplete, which I believe would not be a valid workflow in a production setting?
Was wondering if that was how you got to see the change logs broken or if there was another way that i'm missing while I was trying to reproduce it?
