### ISSUE TITLE
Experimenter API does not reflect correct type for pref value

### ISSUE THREAD

**Issue by tiftran** [mozilla/experimenter#2260]
![Screen Shot 2020-02-07 at 4 50 08 PM](https://user-images.githubusercontent.com/25379936/74075920-fb348a00-49c9-11ea-89c6-f383b64039bd.png)

was fixed for recipes... but this was forgotten...

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-136)

**Comment by datavizard** [comment]
Is anybody working on this issue? I can work on this issue but would need some context here.
