### ISSUE TITLE
Add OS version input

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2265]
We need to capture the OS Version if someone chooses to filter by OS, so we should add an optional text field that appears if someone selects anything other than `All Platforms`

**Comment by shell1** [comment]
we don't want a text field there.   we want specifically to offer "all windows, windows 7, windows 8, Windows 8.1, windows 10+" 

multi-select please- as they may want win 8.1, and win 10 (but not win 7 or win 8).
