### ISSUE TITLE
Filter intake for Addons

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2268]
We need to add a new filter:

Include Addon

Should work like branches so you can add/remove an arbitrary number of them and each one includes

- addon id

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-139)

**Comment by uhlissuh** [comment]
I would like this ticket to refer in whole to the addon filtering i am going to add. Right now, we have a ticket for "include addon" and "exlude addon", but i don't think the work breaks down that way.

**Comment by uhlissuh** [comment]
Un-assigning myself.
