### ISSUE TITLE
Filter on Exclude Addon

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2269]
We need to add a new filter:

Exclude Addon

Should work like branches so you can add/remove an arbitrary number of them and each one includes

- addon id

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-140)

**Comment by uhlissuh** [comment]
i don't think this issue is needed.. one ticket for addon filtering will likely be enough.

**Comment by uhlissuh** [comment]
I began this work, but don't think I can finish it completely in my time left here. I am un-assigning myself.
