### ISSUE TITLE
[Enhancement] The "Export to Normandy" modal should not be dismissed if the recipe ID is an invalid value

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#2289]
**[Affected versions]:**
- Firefox Nightly 75.0a1, Build ID 20200217214434

**[Affected Platforms]:**
- Windows 10 x64

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- Have a delivery in Ready for Ship state.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to 
"https://stage.experimenter.nonprod.dataops.mozgcp.net/".
2. Open the experiment from prerequisites.
3. Click the "Send to Normandy" button and then the "Export to Normandy" button.
4. Switch back to the previous tab and write `test` in the "Primary Recipe ID" field.
5. Click the "Save Recipe ID" button and observe the behavior.

**[Expected result]:**
- The modal remains displayed and an error message is displayed for the field.

**[Actual result]:**
- The page is refreshed and the modal show's the "Export to Normandy" button. Only after clicking it a 2nd time will it show the error message in the field.

**[Notes]:**
- I got bit by this when I tried to put the recipe ID as `delivery-console.stage.mozaws.net/recipe/677/`, instead of just a number.
- Attached a screen recording of the issue:

![don't dismiss modal if the recipe ID is an invalid input](https://user-images.githubusercontent.com/18304511/74753399-c1406f00-5278-11ea-9317-51aa26db89bb.gif)

**Comment by SoftVision-CosminMuntean** [comment]
The Send to Normandy flow was changed since this bug was logged and the behavior described in this issue is no longer encountered. Considering this, I will mark this issue as Verified Fixed.
