### ISSUE TITLE
Intermittent integration test failure: #id_pref_name

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2302]
Just saw this on circle:

```
response = {'status': 404, 'value': '{"value":{"error":"no such element","message":"Unable to locate element: #id_pref_name","sta...\\nregisterSelf@chrome://marionette/content/listener.js:501:5\\n@chrome://marionette/content/listener.js:1854:1\\n"}}'}
```

https://app.circleci.com/jobs/github/mozilla/experimenter/8042

**Comment by jrbenny35** [comment]
Looks like there is a wait locator but no wait function
https://github.com/mozilla/experimenter/blob/5d14940445a6e2cea5b35fa3ec5ce64ae12c75f3/tests/integration/pages/experiment_design.py#L24

I have a fix but I am going to run it a few times to make sure it passes
