### ISSUE TITLE
Change DS bugzilla field to DS Jira field

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#2303]
Even though we can't link to Jira - change the field to request Jira ticket.

Change the "Data Science Bugzilla URL" to "Data Science Jira Ticket" - it will be a URL of this form... though if you match it only needs to match to "https://jira.mozilla.com/browse/" - NOT The "DS-". ex: https://jira.mozilla.com/browse/DO-352

This field won't automatically do anything.

Please change the experimenter help to say the following:
"Provide a link to the DS Jira ticket that was filed with the Data Science team that tracks this delivery. If you have not already filed a ticket with Data Science, you can do that here.

Example: https://jira.mozilla.com/browse/DO-352"

*****The "you can do that here" should link to the Datascience help for more guidance on creating the Jira issue. https://mana.mozilla.org/wiki/display/PM/Data+Science+Jira+documentation

**Comment by jaredlockhart** [comment]
- We have to rip out all the bugzilla validation on the field
- Rip out all the celery tasks that pertain to this field
