### ISSUE TITLE
Typo if Data Science ticket fails on experiment sign off

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/experimenter#2307]
The text at the page says "The Data Science Ticket was UNABLE to updated with experiment_info ". I think it should say ```The Data Science Ticket was UNABLE to be updated with experiment_info ```

**Comment by tiftran** [comment]
ripping this out as a part of https://github.com/mozilla/experimenter/issues/2303

**Comment by shell1** [comment]
closign as this code is going away
