### ISSUE TITLE
Remove unnecessary [] from 'Other Recipe IDs'

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2314]
Looks like we're prepopulating the other recipe ids field with some unnecessary square brackets that need to be cleared out before you can save, those shouldn't be there: 

<img width="789" alt="image (1)" src="https://user-images.githubusercontent.com/119884/75292680-acbd2300-57f2-11ea-8326-59ffc1210c5c.png">

**Comment by uhlissuh** [comment]
I can't reproduce this.. @tiftran can you... or can you provide more info @jaredlockhart ? Definitely can reproduce #2289 in all of my attempts though.

**Comment by jaredlockhart** [comment]
Looks like we can't reproduce this so  I'm gonna close it and we can reopen/refile it if it comes up again.

**Comment by jaredlockhart** [comment]
@rehandalal just saw this in production again, reopening.  Maybe it's somewhere in the JS form state management?

**Comment by jaredlockhart** [comment]
Death to the export modal.
