### ISSUE TITLE
Add docs to run integration-tests

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/experimenter#2317]
There are currently no docs on how to run the integration-test suite. We should fix that by adding docs on how they can be run locally.

**Comment by jrbenny35** [comment]
Here is what I have so far:
```
# Experimenter Integration Tests

### Prerequisites
- Docker
- Docker-Compose
- make
- [geckodriver]
- Python 3
- [tox]

### Setup using docker and make

To run the tests via docker-compose use the following make commands.

- Start and run the tests
```
make integration_test_run
```
You can view the tests running via VNC and port 5900. The password to connect to the container is `secret`.
To trigger the tests within the container:
```
docker-compose -p experimenter_integration -f docker-compose.yml -f docker-compose.integration-test.yml exec firefox sh -c "tox -c tests/integration"
```
With the VNC window open, you should see Firefox open and Selenium executing commands.

### Setup using local Firefox

Install [geckodriver] in your path. You should be able to do `geckodriver --version` from your terminal if your path is correct. Firefox must also be available from
your path. To verify this use the following command: `firefox --version`. If there is no output check your configuration.

Now navigate to the directory that you have cloned experimenter into and follow these steps:

1. Within the experimenter root directory:
```
mkdir python_env
python3 -m venv python_env
source python_env/bin/activate
```
If successful your shell should have an `(python_env)` prefix.
2. Install Tox
```
pip install tox
```
3. Start the tests
```
tox -c tests/integration/tox.ini
```
Firefox should open and the tests should execute.

### Extras

- To run a single test with tox you must pass the arguments through tox using `--` and then use the _keyword_ argument within pytest.
Ex: `tox -c tests/integration -- -k name_of_test`
- To deactivate the virtual env: `source deactivate`
- Setup and start containers but do not run tests: `make integration_up_detached`
- Setup and start containers but do not run tests and show all container messages: `make integration_up`
- Kill all containers: `make kill`


[geckodriver]: https://github.com/mozilla/geckodriver/releases
[tox]: https://tox.readthedocs.io/en/latest/
```

**Comment by uhlissuh** [comment]
Hey I edited your comment because it had an errant "```" that was messing up the formatting... hope you don't mind. 

I tried your steps for local setup and they seem like they will work.... unfortunately though, I got all the way to seeing the first test listed and attempt to run... then it all just stalled indefinitely. Assuming this is a geckodriver issue? I'm gonna take another stab at it tomorrow to see if I can't get everything, and in particular geckodriver, set up correctly. I definitely think running locally is going to be the simplest and best way to run the the integration tests... This is what I'm seeing at the moment:

![inttest](https://user-images.githubusercontent.com/1551682/75837136-d4733480-5d78-11ea-8eba-8c4f40ad7b06.gif)

**Comment by jrbenny35** [comment]
@uhlissuh can you try and just let it run until it fails? If it doesn't fail after 5 min let me know here please. Thanks.

**Comment by uhlissuh** [comment]
If I wait, they'll all error out with this connection error:

![Uploading Screen Shot 2020-03-16 at 10.23.58 AM.png…]()

**Comment by jrbenny35** [comment]
> If I wait, they'll all error out with this connection error:
> 
> Uploading Screen Shot 2020-03-16 at 10.23.58 AM.png…

I don't think this image uploaded correctly, can you try again please?

**Comment by uhlissuh** [comment]
sorry @jrbenny35, I fixed it.

**Comment by jrbenny35** [comment]
Did you make any changes to the URL within the tox file? Is experimenter accessible at ```http://nginx``` in your browser?

**Comment by jaredlockhart** [comment]
Closing this until it comes up again.
