### ISSUE TITLE
Expose Normandy slugs and/or recipe IDs in /experiments/ endpoint

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#2318]
For pensieve, we need to map an Experimenter entry to the Normandy recipes it describes so that we can write queries. Can Normandy recipe IDs and slugs for each delivery be added to the /experiments/ API endpoint? cc @scholtzan

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/pull/2319
