### ISSUE TITLE
Sticky issue question

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#2326]
Looking back at issues we hit last year - several involved missing sticky criteria.

Trying to think of a simple way to catch the issue where people target users to be in the experiment based on something they later change.

"Is this experiment targeting users based on a preference - who's value is then changed by the experiment?"

I'm thinking this should add a label or something for Normandy folks to clearly see - like surveys - that there may be dragons here.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-148)

**Comment by shell1** [comment]
this should go in the targeting criteria area - and add a STICKY label to the experiment if they say "Yes".

**Comment by jaredlockhart** [comment]
Checkbox on the timeline page

**Comment by shell1** [comment]
Nimbus should make sure they won't hit this with the manual process - as it bites us all the time today when enrollment criteria differ from the target change. 

AKA - enroll only users who have never changed this pref - then for one branch change that pref.

**Comment by shell1** [comment]
Nimbus should make sure they won't hit this with the manual process - as it bites us all the time today when enrollment criteria differ from the target change. 

AKA - enroll only users who have never changed this pref - then for one branch change that pref.
