### ISSUE TITLE
Store estimated population size in number of profiles

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2359]
We currently capture the definition of a delivery's target population by requesting a percentage of the total population, ie 25% of Firefox Beta.  However this same percentage can have wildly different outcomes in terms of the total number of profiles enrolled depending on the additional filters that are defined for the delivery.  This can make it hard to know whether the real enrollment numbers reflect the expected target population size while monitoring a live delivery.

Perhaps a simple solution to this is to additionally capture an estimate of the number of enrolled profiles as a reference point.  I don't think we need to add any fancy live integration with telemetry for this to update  it live while it's running, just put it somewhere on the detail page.

It's worth noting that there are significant differences between the 'active client ids per 24 hours' and  'cumulative enrolled clients' so we should take that into account and be clear about which we mean, my guess would be the latter.

**Comment by tdsmith** [comment]
sgtm! Definitely "total enrolled."

**Comment by shell1** [comment]
this should show up in the details page. Experiments only (not rollouts or generic).  Let's start with field being optional - may change to required later - but see how it works out first.
