### ISSUE TITLE
Edits not captured in changelog

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2377]
I just noticed [this experiment](https://experimenter.services.mozilla.com/experiments/webrender-continued-v2-nightly-only/) on prod had information entered under branches, objectives, analysis, and qa testing, but only a single changelog entry in the history for the overview page.  I would expect there to be changelog entries for everything entered, so let's check to make sure that the changelogs are behaving correctly.

**Comment by tiftran** [comment]
Experiment above was cloned, so instead of a "created experiment" a "cloned from <parent>" would be more helpful
