### ISSUE TITLE
Wait on react rendered ID for react page integration tests

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2439]
For the integration tests to pass, they have to wait until the  page is ready.  For our react rendered pages (timeline/pop and design), the tests need to wait on an ID that gets rendered by  react rather than django. 

Right now the timeline test waits on this element:

https://github.com/mozilla/experimenter/blob/master/app/tests/integration/pages/experiment_timeline_and_population.py#L32-L33

which is rendered by django:

https://github.com/mozilla/experimenter/blob/master/app/experimenter/templates/experiments/edit_timeline_population.html#L34

and so it will be available to the integration test before react  has finished rendering the page.  So we need to emit the ID as part of the react render flow rather than in the django template.

**Comment by jrbenny35** [comment]
The thing with ```wait_for_page_to_load``` is that it is flexible. It doesn't need to be the same for every page. So I can just wait for text to appear from one of the form options even
