### ISSUE TITLE
Disable integration tests in circle for master merges

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2444]
We probably don't need to run the integration tests after a PR lands on master before it's deployed, we should see if we can disable that in the circle config.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-153)

**Comment by jrbenny35** [comment]
I am going to vote against this. Right now we are just running the same tests, but soon (e2e, more tests) we will have more tests. I don't think it would be fun waiting 15min or more for a green on circleci for every PR. We should just run e2e tests on PR's and then run the whole suite for each master merge. Or something like that.
