### ISSUE TITLE
Increase session duration to 24hrs

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#247]
The current session duration for the 0auth sessions is set to something small like 30m.  We should increase this to 24h so people don't lose work in the middle of editing stuff.

**Comment by jbuck** [comment]
How does that jive with https://wiki.mozilla.org/Security/Guidelines/OpenID_Connect#Session_handling ? I wonder if that check can be done automatically or something

**Comment by jaredkerim** [comment]
@shell1 Watch this

**Comment by jbuck** [comment]
Right now the cookie lasts for 1 hour. Looking at the openidc config, I think I need to increase `session_cookie_lifetime` from `3600` to something larger

**Comment by jaredkerim** [comment]
@jbuck Is this something you can do immediately? Or do we have to wait until we move to GCP to change it?

**Comment by jbuck** [comment]
Yes, I can test this change now (not sure if it's the right setting, just guessing it is)

**Comment by jbuck** [comment]
This was done about two weeks ago, but I forgot to update the bug!

https://github.com/mozilla-services/cloudops-deployment/commit/20d5f652581824ab44c8abc1d68e58d5c6fb25d0#diff-c5f19811fb4cacf93c53fcbb950bdcf9
