### ISSUE TITLE
Signoffs for Message Type

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2496]
### Default required reviews for message experiments:
* Data Science
* QA Requested
* Intent to ship
* QA Signoff
* Relman signoff
* UX

**Comment by shell1** [comment]
Is it hard to change the order?  In my ideal world - it would be....
    Data Science Review
    Intent to ship
    QA Requested
    Copy/UX Review
    QA Signoff

and legal/VP will be added if the check off the risk of "partner" involved.

**Comment by jaredlockhart** [comment]
@shell1 yep the vp gets added if they check risk to the brand:

<img width="878" alt="Screenshot 2020-04-27 17 29 20" src="https://user-images.githubusercontent.com/119884/80422704-a90a5300-88ac-11ea-8e2f-d12de9f4cce4.png">
<img width="308" alt="Screenshot 2020-04-27 17 29 29" src="https://user-images.githubusercontent.com/119884/80422711-aa3b8000-88ac-11ea-8e88-019e50aece93.png">

**Comment by jaredlockhart** [comment]
And here's the order you asked for:

<img width="235" alt="Screenshot 2020-04-27 17 30 51" src="https://user-images.githubusercontent.com/119884/80422828-dc4ce200-88ac-11ea-8b15-ec32a274bee4.png">
