### ISSUE TITLE
Reduce circle job credit usage

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2532]
Okay let's figure out a few strategies to bring down our circle usage.

The biggest standout I can think of is disabling integration tests after master merges, they should only be run on PRs.

**Comment by jrbenny35** [comment]
Did you already get yelled at?? :laughing:

**Comment by jaredlockhart** [comment]
![giphy](https://user-images.githubusercontent.com/119884/78716132-6a582d00-78ec-11ea-9f7a-13b92db1c1a2.gif)
