### ISSUE TITLE
Risk section filled in - but then edit shows empty

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#2544]
I have a quicktime mov that I couldn't figure how to attach - but it's really easy - this experiment https://experimenter.services.mozilla.com/experiments/delegated-credentials-nightly-breakage-study-v2/edit-risks/  when we looked at summary had the risk section filled in.  But when we go to edit - they are all blank.  
![image](https://user-images.githubusercontent.com/8192232/79169870-76d3fe00-7da2-11ea-9ca6-011891898abb.png)
![image](https://user-images.githubusercontent.com/8192232/79169883-84898380-7da2-11ea-8a9b-9ddf428e4475.png)

**Comment by uhlissuh** [comment]
this is also a problem on the results section which uses the same piece of template.
