### ISSUE TITLE
Add S3 storage for storing media files

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#255]
We want users to be able to upload images for projects and experiments, so we need to setup S3 media storage.

**Comment by shell1** [comment]
we are closing out a bunch of these original "we could possible do x" UX enhancements.  Mid-year after 2 quarters of development - we will look at the UX and see all up what changes will be truly helpful to the users.  Don't want a bunch of ideas in the backlog that might get worked on individually - and conflict with more recent changes.
