### ISSUE TITLE
Read normandy recipe IDs for shipped deliveries

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2562]
Rather than the current workflow of manually entering Recipe IDs in the modal, let's update the background worker to look in the Normandy  API  for Experimenter slugs that don't have recipe IDs in our  database and save them and update  the  state to accepted, so then the workflow would  be

1) Click `Send to Normandy` in Experimenter
2) Fill out and save in Delivery Console
3) - Experimenter automatically detects that a `Ready to Ship` delivery that does not have a Normandy ID now appears in the Normandy V3 Recipe API and saves that recipe ID to the database.  
    -  If it finds a second  recipe with the same slug, it adds that recipe ID to the 'other recipe ids' field.  
    - Experimenter updates the status to `Accepted by Normandy`

**Comment by rehandalal** [comment]
> If it finds a second recipe with the same slug, it adds that recipe ID to the 'other recipe ids' field.

I think there is an edge case we'll need to account for here. If two (or more) recipes exist with the same slug then I think the oldest one should become the "primary" recipe ID and the rest should become "other" recipe IDs.

I suspect we may need to add the ability to filter by experimenter slug to the Normandy API to make this a little easier.

**Comment by jaredlockhart** [comment]
Oooo that's a good idea

Also I was imagining that there wasn't really a useful heuristic to determine which one is the primary.  Even now the idea of 'primary' only means which one is used to check the 'liveness' of the delivery but it's already a broken concept.  What does it mean if one ends and the other is open?  We just skipped over figuring that out, so I'm not sure that it makes a difference here?
