### ISSUE TITLE
No DS is displayed in summary view

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#2567]
https://experimenter.services.mozilla.com/experiments/https-upgrade-study/

am i losing my mind that the DS should show in the summary?

**Comment by jaredlockhart** [comment]
Looks like nobody picked one:

<img width="839" alt="Screenshot 2020-04-20 16 28 42" src="https://user-images.githubusercontent.com/119884/79796721-08ec8100-8324-11ea-893d-87f36bae0ab9.png">

This field is still optional, should we change it?

**Comment by shell1** [comment]
this really is always optional - the DS jira is a top link and I can find DS from there.   I'm OK with this behavior.
