### ISSUE TITLE
DC doesn't support platform filter objects

### ISSUE THREAD

**Issue by tiftran** [mozilla/experimenter#2568]
Will need to revert to platforms back to comments.

<img width="993" alt="Screen Shot 2020-04-20 at 10 31 41 PM" src="https://user-images.githubusercontent.com/25379936/79829109-1cfda600-8357-11ea-9406-c38beccf84b3.png">

**Comment by jaredlockhart** [comment]
Just add it as a line to the 'comment' field and dont' send it as a filter object.  If we can keep the serializer code intact and just not use it that'd be great, if the checks complain about unused code we can just delete it and revert the commit later when we wanna put it back.
