### ISSUE TITLE
Add message experiment data science conversion fields

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2599]
From @tdsmith: 

![unnamed](https://user-images.githubusercontent.com/119884/80546389-80a15800-8983-11ea-8e05-cc6790159204.png)

* [ ] Add those four fields to the bottom of the objectives/analysis page
* [ ] Add them to the analysis plan section of the detail page
* [ ] Only show up for message experiments
* [ ] Add them to the API
* [ ] Add them to the changelog

**Comment by tdsmith** [comment]
Context, and suggestion for docs:

> The conversion event describes the outcome that you are attempting to drive with the experiment. For example, if the experiment attempts to drive users to import their bookmarks from a different browser, the bookmark import feature should send a Firefox event telemetry event when the bookmarks are imported. This event must be sent from clients in both the control and all treatment branches of the experiment. This allows us to measure the success of the experiment at driving the targeted interaction. An empty box will match any value for that event parameter.
