### ISSUE TITLE
Recipe API endpoint returns 500 errors for messaging experiments (staging)

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#2604]
While trying to test pulling from the API on staging, I started hitting  500 errors while trying to fetch messaging experiments (e.g. https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v1/experiments/message-experiment-123/recipe/). 

I'm not running into this issue for other recipes like add-ons

**Comment by jaredlockhart** [comment]
Ah this should be returning a 404 for that endpoint for experiments that aren't ready to ship yet

**Comment by k88hudson** [comment]
Ah, thanks!
