### ISSUE TITLE
Integration Test: Comments

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2622]
A user recently reported that our comments fields stopped working, so I'd like to add an integration test that checks that comments are working on the detail page.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-169)

**Comment by jrbenny35** [comment]
@jaredlockhart thoughts on this for allowing the selenium selectors to be less ugly?

```<a id="{{ section_name }}-comment{{ comment.id }}" href="#comment{{ comment.id }}">```

vs

https://github.com/mozilla/experimenter/blob/5d9a1f810580110faefe24f464859c71b98e6773/app/experimenter/templates/experiments/section_base.html#L52

**Comment by jaredlockhart** [comment]
> @jaredlockhart thoughts on this for allowing the selenium selectors to be less ugly?
> 
> `<a id="{{ section_name }}-comment{{ comment.id }}" href="#comment{{ comment.id }}">`
> 
> vs
> 
> https://github.com/mozilla/experimenter/blob/5d9a1f810580110faefe24f464859c71b98e6773/app/experimenter/templates/experiments/section_base.html#L52

I think this should be fine but you'd have to do the same thing to both the id and the href, give it a shot.
