### ISSUE TITLE
Symbols are escaped in markdown code snippets

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#2637]
Not a big deal but I noticed as I was using code blocks in markdown, I noticed some pretty aggressive escaping going on: 

Expected: `"branch_1"`
Actual: ![image](https://user-images.githubusercontent.com/1455535/81289428-68d96c00-9034-11ea-99ef-8149e8e9a3be.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-172)

**Comment by jaredlockhart** [comment]
What field did that happen on?

**Comment by jaredlockhart** [comment]
Oh I see.  I think that's just the markdown preprocessor we're using, I'm not sure there's anything we can do about it.

**Comment by k88hudson** [comment]
It's in the `Description` section of overview
