### ISSUE TITLE
Pref value should allow more than 255 chars for json strings

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2639]
JSON blobs can be very large, the pref value field on the design page should allow more than 255 characters.

**Comment by ScottDowne** [comment]
I'm hitting this too.

I've noticed two things.

1. It only seems to happen with multi pref setups. If I do a single pref, I don't get this limit.
2. Seems to happen on string prefs too.

Is there a workaround?

**Comment by kanhema** [comment]
Not ideal, has anyone gotten to this yet?
