### ISSUE TITLE
Sentry failure for multipref

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2640]
https://sentry.prod.mozaws.net/operations/experimenter-prod/issues/8356500/?query=is%3Aunresolved

**Comment by tiftran** [comment]
Did some poking... looked at the experimenter changelog, request body from Sentry and what's currently being outputted by `/design/multi-pref` 
It seems like it was an attempt to swap the ordering of prefs that cause this.

**Comment by jaredlockhart** [comment]
Oh good analysis @tiftran you're right.  What did we say last time we hit this?  That we just won't handle this case?

**Comment by jaredlockhart** [comment]
I feel like we should at least catch the error and show something nice.

**Comment by tiftran** [comment]
I think the last time was pre react design page and I think we did return some generic error thing for that too.
