### ISSUE TITLE
Use http/2 in nginx

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2655]
Looking about `about:networking` looks like everything is http/2 now except our local dev server.  I think it's just as simple as adding `http2` to the server directive in nginx, so we should enable that to more closely replicate production behaviour locally.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-176)

**Comment by bhushan-borole** [comment]
Hello @jaredlockhart.
Is this issue still open for solving?
