### ISSUE TITLE
Add random experimentation quotes

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#266]
Let's add little quotes to encourage people to think experimentally!

Example:

"Experimentation is an act of humility, an acknowledgment that there is simply no way of knowing without trying something different."

https://www.nytimes.com/2017/12/01/business/why-trying-new-things-is-so-hard.html

**Comment by shell1** [comment]
we are closing out a bunch of these original "we could possible do x" UX enhancements.  Mid-year after 2 quarters of development - we will look at the UX and see all up what changes will be truly helpful to the users.  Don't want a bunch of ideas in the backlog that might get worked on individually - and conflict with more recent changes.
