### ISSUE TITLE
End to End Tests: Add Related Projects to Overview Page

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2662]
Missing the 'Related Projects' field in the Overview page in the integration tests.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-177)

**Comment by jrbenny35** [comment]
@jaredlockhart thoughts on this for allowing the selenium selectors to be less ugly?

```<a id="{{ section_name }}-comment{{ comment.id }}" href="#comment{{ comment.id }}">```

**Comment by jaredlockhart** [comment]
> @jaredlockhart thoughts on this for allowing the selenium selectors to be less ugly?
> 
> `<a id="{{ section_name }}-comment{{ comment.id }}" href="#comment{{ comment.id }}">`
> 
> vs
> 
> https://github.com/mozilla/experimenter/blob/5d9a1f810580110faefe24f464859c71b98e6773/app/experimenter/templates/experiments/section_base.html#L52

Did you post this in the wrong ticket? https://github.com/mozilla/experimenter/issues/2622 ?

**Comment by jrbenny35** [comment]
LOL yup, let me move it
