### ISSUE TITLE
when manually adding projects - kept hitting error for not having "live" stage with enroll change blocking save

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#2670]
<img width="1316" alt="Screen Shot 2020-05-16 at 10 57 12 AM" src="https://user-images.githubusercontent.com/8192232/82127170-72668080-9766-11ea-94a1-36481600fdd8.png">

not sure if this is an issue - but reporting

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-178)

**Comment by jaredlockhart** [comment]
* Enrollment complete should have old/new status as `Live`
* Data migrate those new changelogs to set those statuses, leave the user alone

**Comment by shell1** [comment]
only hit when i need to manually edit an experiment later - can live with working around provided it doesn't break anything else.
