### ISSUE TITLE
Add a dummy data management command

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#268]
Let's make [a management command](https://docs.djangoproject.com/en/2.1/howto/custom-management-commands/) to populate the db with dummy data for easy testing.

You can use the test factories to make this very simple, for instance

    from experimenter.experiments.tests.factories import ExperimentFactory
    ExperimentFactory.create_with_status(Experiment.STATUS_DRAFT)

will create a fully formed experiment with all the necessary related data.  So I think for this management command, it should take two optional parameters

    python manage.py create-dummy-experiments <number of experiments> <optional status>

Number of experiments: default to 10

Optional status: If status is specified, create all experiments with that status. If no status is specified, just choose at random for each experiment by doing something like
   
    import random
    random_status = random.choice(Experiment.STATUS_CHOICES)[0]
    ExperimentFactory.create_with_status(random_status)

And then add tests and add an alias to the Makefile (look at the load-locales-countries to see an example).  Let me know if you have any questions!

**Comment by peterbe** [comment]
I can work on this. I have exactly 1 experiment in my local db. If you can run `./app/manage.py dumpdata experiments projects` and send me that JSON dump I can turn that into a management script. 

Actually, I'm not convinced about checking in any such `.json` file into git so it's probably best to have as a file we email each other combined with a custom import script that can take this file as a parameter.

**Comment by jaredkerim** [comment]
@tiftran Oh! I just realized you'll also need to do

    ExperimentFactory.create_with_status(..., type=random.choice(Experiment.TYPE_CHOICES)[0])

so that we get a mix of pref and addon experiments.

**Comment by robhudson** [comment]
This fails for me with the output...

```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "base_locale_code_key"
DETAIL:  Key (code)=(b) already exists
```

This is the first time I'm walking through the README steps to create data locally.
