### ISSUE TITLE
Error page not very responsive

### ISSUE THREAD

**Issue by Siddharth1698** [mozilla/experimenter#2683]
![Screenshot from 2020-05-26 04-13-41](https://user-images.githubusercontent.com/31384057/82846647-84cf7f80-9f07-11ea-84c9-ac216390aba6.png)
The following happens when i resize firefox. The url moves out of box and doesn't look responsive.

**Comment by jaredlockhart** [comment]
@Siddharth1698 Ah that page is on Auth0, we don't control that page.  It's been a bit wonky for a while, I think you need to contact infosec about that?
