### ISSUE TITLE
Initial Rapid Experiment Intake Form

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2686]
After we add the API here: https://github.com/mozilla/experimenter/issues/2674

We can expose a simple form for the mockup:

<img width="918" alt="Screenshot 2020-06-01 16 42 03" src="https://user-images.githubusercontent.com/119884/83452549-ea9b9a00-a426-11ea-954d-2067e4761c6d.png">

The feature/audience/trigger fields are undefined until we get the JSON data to populate their options, so we can put dummy placeholders there for now, but for submission let's start with:

* name
* hypothesis
* version (optional)

So let's add the UI, the state tracking, and submission logic.

**Comment by jaredlockhart** [comment]
Update: don't show the owner on the creation form, it's redundant with the header:

<img width="1215" alt="Screenshot 2020-06-01 18 59 44" src="https://user-images.githubusercontent.com/119884/83462922-72d76a80-a43a-11ea-8e1a-9b7a90077027.png">

**Comment by rehandalal** [comment]
mockup: https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/WIP-Platform-Exp?node-id=214583%3A0
