### ISSUE TITLE
Pull real names from OpenIDC

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#271]
In addition to the users email, we should also use their real names.  Let's pull and store that header as well.

**Comment by shell1** [comment]
we are closing out a bunch of these original "we could possible do x" UX enhancements.  Mid-year after 2 quarters of development - we will look at the UX and see all-up what changes will be truly helpful to the users.  Don't want a bunch of ideas in the backlog that might get worked on individually - and conflict with more recent changes.  We'll work out a high impact, many UX changes plan based on feedback from the evolved state of Experimenter.
