### ISSUE TITLE
Create Bugzilla ticket for Rapid Experiment

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2718]
When a rapid experiment is created, we should also create a bugzilla ticket.  This will require the templated copy from PM.

**Comment by pdehaan** [comment]
When does this happen? After the experiment is approved in Remote Settings?

**Comment by AnaMedinac** [comment]
Here is the templated copy: https://docs.google.com/document/d/1YLgQU-pYsOmZiGXFWCr0CtxxoRMfYXqpkcSxqZs0PwQ/edit?usp=sharing. 

Let me know if you think we should add to it.
