### ISSUE TITLE
Intermittent failure in test_models.py test

### ISSUE THREAD

**Issue by emtwo** [mozilla/experimenter#273]
======================================================================
FAIL: test_experiment_variants_returns_correct_string (experimenter.experiments.tests.test_models.TestExperimentModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/experimenter/experiments/tests/test_models.py", line 146, in test_experiment_variants_returns_correct_string
    '1 Variant : 1 Control',
AssertionError: '1 Control : 1 Variant' != '1 Variant : 1 Control'
- 1 Control : 1 Variant
+ 1 Variant : 1 Control

**Comment by jaredkerim** [comment]
Fixed
