### ISSUE TITLE
Add "(optional)" after Lightning Advising in the required sign-off list.

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#2771]
having "Lightning Advising" early in the sign-off list is helpful for guiding/reminding people - but causes issues as it now looks required for experiments.  it had said "Lightning Advising (optional)" in brackets before.  

Removed "(optional)" because thought we wanted rollouts to have it required - but we aren't really doing that for all rollouts.  @mythmon are you OK with going back to saying optional?  I get asked every week about it.

**Comment by mythmon** [comment]
Yes, I'm ok with this.

**Comment by shell1** [comment]
Second thought, I'm going to pause on this request - just until we figure out what is happening with capacity planning.  In case lightning advisings do become required.

**Comment by shell1** [comment]
confirming we will remove the (optional).  we aren't using lightning advisings for capacity management - so it's all upside to adding that word back to the tag.
