### ISSUE TITLE
Clean up some stale branches in repo?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#2775]
Not really important, but just casually noticed that we seemingly have about 430+ branches in GitHub and about 20 pages of stale branches: https://github.com/mozilla/experimenter/branches/stale?page=20

I think I have contributor access high enough to trim stale branches and can definitely sit here for 10 minutes clicking the delete icon next to stale branches that have been merged, but wanted to confirm that you wanted me to do that before I went all silly with your repo.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-181)

**Comment by jaredlockhart** [comment]
Let me take a look at this when I get a chance

**Comment by pdehaan** [comment]
Sure, but if its a bunch of trivial button clicking, feel free to assign to me so it doesnt distract you from more important matters. Alternatively, we can ignore it for now since it doesn't hurt anything and revisit after our deadline.
