### ISSUE TITLE
Autogenerate user_id to simulate experiment branch for QA

### ISSUE THREAD

**Issue by punamdahiya** [mozilla/experimenter#2793]
Scope of this issue is to auto generate user_id that can be used to set normandy.user_id in about:config to test respective experiment branch.

something like

qa.user_id {
control: "a12378asd",
branch_1: "b3423wqw",
}

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1099)
┆Issue Number: EXP-1099

**Comment by jaredlockhart** [comment]
We need to confirm whether this is a requirement for Experimenter.

**Comment by punamdahiya** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1652596 to support generating user_ids using testing function inside m-c. Eventually it will be great to automate this support directly in experimenter. Thanks!

**Comment by jaredlockhart** [comment]
@punamdahiya Awesome thank you!  In the spirit of not letting unactionable tickets build in the backlog, I will close this, and when we want to revisit it we can file a new ticket.
