### ISSUE TITLE
Admin CSS is broken

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2797]
That's a big heckin logo:

![Screenshot_2020-06-09 Mozilla Experimenter](https://user-images.githubusercontent.com/119884/84193392-615d1680-aa69-11ea-8e58-f743fd3633f0.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-183)

**Comment by kanurag94** [comment]
![Screenshot from 2020-08-19 23-42-05](https://user-images.githubusercontent.com/5468342/90673630-a5dd0d80-e275-11ea-8db2-290b587f7227.png)
LGTM
