### ISSUE TITLE
Allow for empty string pref values in branch preferences

### ISSUE THREAD

**Issue by mikedeboer** [mozilla/experimenter#2824]
Ref: this was brought up whilst working with QA on this ticket: https://experimenter.services.mozilla.com/experiments/amazon-tile-study/

<img width="791" alt="Screenshot_15_06_2020__17_42" src="https://user-images.githubusercontent.com/141571/84678019-cb753000-af2f-11ea-944f-1a6d3e11bee8.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-185)

**Comment by mythmon** [comment]
Note: Normandy does not currently allow empty preference values either, but I plan to add them in mozilla/normandy#2236
