### ISSUE TITLE
Use typescript-eslint parser for rapid .eslintrcjs

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#2834]
Since we are using typescript-eslint rules, it would be a good idea to use the `@typescript-eslint/parser` for the `parser` setting in `.eslintrc`.

See https://github.com/typescript-eslint/typescript-eslint#what-about-babel-and-babel-eslint

> The key trade-off can be summarized as babel-eslint supports additional syntax which TypeScript itself does not, but typescript-eslint supports creating rules based on type information, which is not available to babel because there is no type-checker.

> Because they are separate projects powered by different underlying tooling, they are currently not intended to be used together.

**Comment by jaredlockhart** [comment]
Change here: https://github.com/mozilla/experimenter/blob/main/app/experimenter/static/rapid/.eslintrc.js#L7
