### ISSUE TITLE
Inconsistent eslint rules for js/ts in rapid folder

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#2835]
Not sure if this is intentional , but for example, `no-unused-vars` is an error in jsx v.s. a warning in `tsx`:

```
/Users/k88hudson/github/experimenter/app/experimenter/static/rapid/components/App.jsx
  3:7  error  'foo' is assigned a value but never used  no-unused-vars

/Users/k88hudson/github/experimenter/app/experimenter/static/rapid/components/App.tsx
  3:7  warning  'foo' is assigned a value but never used  @typescript-eslint/no-unused-vars
```

Is there a reason we couldn't apply the same rules across all files?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-186)

**Comment by jaredlockhart** [comment]
@k88hudson Where are we using jsx?

**Comment by k88hudson** [comment]
@k88hudson check if this is still valid
