### ISSUE TITLE
Feature/Audience for Rapid Intake UI

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2843]
Once https://github.com/mozilla/experimenter/issues/2842 is done we can hook those fields up to the new Rapid UI.  The fields are already built they just need to be hooked up.

**Comment by k88hudson** [comment]
Link to comps: https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/WIP-Platform-Exp?node-id=214583%3A0

**Comment by jaredlockhart** [comment]
Note: remove triggers field from UI
