### ISSUE TITLE
HTTP 500 when clicking on "n Owned Deliveries" after adding rapid experiment

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#2845]
Not entirely sure why I'm seeing a 500. If I change the owner ID in the URL, I can see results for 28-30, but as soon as i use my owner ID of 31, I get an error.

https://stage.experimenter.nonprod.dataops.mozgcp.net/?owner=31&archived=on

Not sure what's happening. But https://stage.experimenter.nonprod.dataops.mozgcp.net/__version__ is giving me the following:

```json
{
  "commit": "64a2125bd45fba7bb673dedced0966ec1e898284",
  "source": "https://github.com/mozilla/experimenter.git",
  "build": "https://circleci.com/gh/mozilla/experimenter/12343"
}
```

But the rapid experiment form wasn't added until the next commit; https://github.com/mozilla/experimenter/commit/107ba800871fa548421b29032762a3aa8161b0e8.

The odd thing is that the stage server was seemingly on the 107ba800871fa548421b29032762a3aa8161b0e8 commit earlier, but either something was reverted or something else is going on.

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/issues/2846
