### ISSUE TITLE
404 after submitting a new rapid experiment

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#2849]
After submitting a shiny, brand new rapid experiment, I'm taken to a sparse page that says 404:

https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/rapid/rapido-experimento/

If I click on "3 Owned Deliveries" in the heading area, and click on my new rapid experiment, I'm taken to the following page:

https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/rapido-experimento/
(looks like the only difference is the /rapid/ path in the 404ing path)

**Comment by jaredlockhart** [comment]
Easy cowboy, that page isn't built yet: https://github.com/mozilla/experimenter/issues/2687 ;)
