### ISSUE TITLE
 Add bugzilla ticket link to rapid detail page

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2876]

**Comment by pdehaan** [comment]
Ref #2937

I'm a bit confused around the timing of the Bugzilla ticket creation.
- Should the bugzilla ticket be created before the experiment is submitted for approval?
- Should the bugzilla ticket be created after the experiment is approved?
- Do we want bugzilla tickets for rejected experiments?
- Do we want bugzilla tickets for abandoned experiments that are created but never submitted for approval?

**Comment by jaredlockhart** [comment]
All great questions.  Right now, launching an experiment depends on a bugzilla ticket existing (to refer to its bugzilla ID and update its status) and since the workflow is

Create Draft -> Request Approval

The only time we have to create the bugzilla ticket is at experiment creation time.  If we want to change this we'd have to rethink whether we want bugzilla tickets at all, which has broader considerations in terms of experiment visibility and integration into bugzilla tracked workflows.

@AnaMedinac do you have any thoughts?

**Comment by pdehaan** [comment]
My vote (not that this is a democracy) is that we create the Bugzilla ticket after the user clicks the "Submit for Approval" button [I can't imagine we care about the experiment if the user never clicks Submit]. Once the request has been submitted, I imagine a Bugzilla ticket makes sense for transparency.
If the experiment is rejected, we auto-close the Bugzilla ticket.
If the experiment is approved, we could potentially update the Bugzilla ticket with the approver and start date, etc.
But I think you mentioned that the current Experimenter workflow already has GitHub integration, so you've probably already wired up the plumbing on things that need to be submitted to Bugzilla.

**Comment by jaredlockhart** [comment]
The detail page already has the link, so closing this in favour of: https://github.com/mozilla/experimenter/issues/3016

And @pdehaan has moved his discussion to: https://github.com/mozilla/experimenter/issues/3015
