### ISSUE TITLE
Editing rapid experiment should say 'Edit <name>' in the title instead of Create.....

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2901]
<img width="733" alt="Screenshot 2020-06-26 18 01 33" src="https://user-images.githubusercontent.com/119884/85904567-15cf9a00-b7d7-11ea-9639-364c9d8bfecb.png">

**Comment by pdehaan** [comment]
Are experiments editable, or are you only talking about the workflow after you hit "Save" and it is still in a draft state and then you click the "Back" button to modify the experiment before it has been submitted for approval?

**Comment by jaredlockhart** [comment]
> Are experiments editable, or are you only talking about the workflow after you hit "Save" and it is still in a draft state and then you click the "Back" button to modify the experiment before it has been submitted for approval?

Yes that.
