### ISSUE TITLE
Ensure data is available for test-tube frontend

### ISSUE THREAD

**Issue by robhudson** [mozilla/experimenter#293]
Here is a list of the data we are hoping to have eventually for test-tube:

* [ ] experiment start date / end date
* [ ] experiment descriptions
* [ ] experiment authors
* [ ] metric descriptions (pulling from the probe dictionary?)

Will these be provided in APIs?

**Comment by tdsmith** [comment]
@sunahsuh mentioned that Experimenter would help link the Normandy names and telemetry IDs of add-on studies for Test Tube; mozreport would consume those as well. Is that right / is use case captured by this ticket?

**Comment by jaredkerim** [comment]
This will be supplanted by the new Normandy event telemetry that will be collected and visualized in Grafana.

**Comment by jaredkerim** [comment]
@tdsmith Ensuring consistency between Experimenter and Normandy for study names is something we want but is not captured by this ticket.
