### ISSUE TITLE
Move shared js dependencies into shared packages.json

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2940]
<img width="901" alt="Screenshot 2020-06-29 18 00 10" src="https://user-images.githubusercontent.com/119884/86060275-668eff00-ba32-11ea-99ba-db784441effc.png">

With this current setup, we have two sets of packages.json for the core and rapid UIs, but some packages appear in both.  Dependabot will have to update them each separately which causes duplicate dependabot PRs.  I think if we move the common dependencies into the central packages.json we can avoid these duplicate PRs which would save time and money.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-191)

**Comment by pdehaan** [comment]
It might also be nice to do the same for the ESLint configs and other shared stuff. ESLint is pretty good at using overrides or other methods of using specific rules for specific folders/globs.
