### ISSUE TITLE
Inconsistent select field UI in rapid experiment form

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#2941]
The first two select fields (Features and Audience) use a custom `<select>` field, whereas the last two select fields (Trigger and Firefox Version) use the native `<select>` UI. Inconsistent, but probably not a deal breaker (since this is an internal only tool).

> Should we also convert the `<select />` fields below on L138 and L154?
>
> _Originally posted by @pdehaan in https://github.com/mozilla/experimenter/pull/2888_

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/86060671-1441e400-ba1a-11ea-9bfb-b5fdd48a7fdc.png)

**Comment by jaredlockhart** [comment]
Some of them are single choice and some are multi choice and I think only the multiple choice need to use the new one?

**Comment by jaredlockhart** [comment]
Trigger is going away altogether, so I think only Features needs to use XSelect, and Audience and Firefox Version can use a regular select (single choice)

**Comment by pdehaan** [comment]
We're losing Trigger for MVP? Or is that post MVP? Do we need to update the Figma spec?
/cc @AnaMedinac

**Comment by jaredlockhart** [comment]
Yeah trigger is gone for MVP.  Yeah we can use this component for all selects, @tiftran informs me that you can use it for single and multi select cases so it makes more sense to maintain a single select component with consistent labeling/error handling/etc.

**Comment by jaredlockhart** [comment]
Also I don't like `XSelect` as the name, especially if we're using it for single and multi case.

**Comment by AnaMedinac** [comment]
Btw, I've updated the Figma to reflect the removal of trigger for the MVP.

**Comment by pdehaan** [comment]
This is probably invalid now that we've lost the Trigger dropdown, and it looks like a recent PR converted that last "Firefox Version" dropdown to use the XSelect for consistency greatness.

**Comment by tiftran** [comment]
Closing as #2993 has addressed this
