### ISSUE TITLE
Save button on rapid experiment form is potentially confusing

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#2943]
Krupa was mentioning this as well, but the "Save" label on the initial rapid intake form is confusing since you aren't really _saving_, per se. Nothing really happens until you click that button and then request approval.

Wondering aloud if changing "Save" to "Next" makes it more apparent that you're on stage 1 of a process and merely hitting "Save" doesn't submit the request.

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/86061812-4b18f980-ba1c-11ea-8aad-91282ed87aed.png)

**Comment by jaredlockhart** [comment]
@AnaMedinac

**Comment by AnaMedinac** [comment]
I agree that this might be confusing. 
Could we potentially add a `Next` button on the right hand side, while keeping the `Save` on the left - the user may want to save it as a draft. Would it be possible once the experiment owner has filled out all the required fields the `Next` button changes colours from Grey to Blue?

Something like this potentially?

<img width="676" alt="image" src="https://user-images.githubusercontent.com/22782298/86144715-05177080-bac4-11ea-98c5-d90ef084b8ea.png">

**Comment by jaredlockhart** [comment]
@AnaMedinac what's the distinction between the `Save` and `Next` buttons? What do they each do when you click them?

**Comment by AnaMedinac** [comment]
I think for right now, based on conversations, we are closing this and keeping as is. In the next iterations the UX might be different and we most likely won't have the same buttons.
