### ISSUE TITLE
Name/slug must be unique for rapid experiments

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2959]
We need to slugify the name and check that the slug is unique when validating the name of a rapid experiment.

**Comment by pdehaan** [comment]
Is this rapid experiment specific though, or is this a core Experimenter issue as well?
I guess it comes down to:
1. Do rapid experiment slugs have to be unique?
1. Do NON-rapid experiment slugs have to be unique?
1. Can rapid and non-rapid experiment slugs sandboxed, or do they have to be unique across the entire system?

**Comment by tiftran** [comment]
@pdehaan 
Rapid and non rapid experiments should have unique slugs, non exclusively between the two types.
Currently non rapid experiments already have this constraint in place, so we need to add this check for rapid.

**Comment by mythmon** [comment]
> Rapid and non rapid experiments should have unique slugs, non exclusively between the two types.

This is true for the mechanical systems. I'd request that we make them globally unique anyways. That would make it nicer for the people who have to deal with experiments. This also means that we can't run into the situation where we confuse telemetry from one experiment with another experiment.

**Comment by tiftran** [comment]
yup, yup I think we're saying the same thing and https://github.com/mozilla/experimenter/pull/2960 achieves this?
