### ISSUE TITLE
Set Firefox Version in rapid recipe

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2965]
We have a `Firefox Version` field in the rapid UI, but it's not connected to the backend yet.  It's not clear to me how that field relates to our existing concepts of 'firefox min version' and 'firefox max version' that we use to create the recipe.  Also how will the choice of firefox version be reflected in the recipe?  How does it get into the filter expression?

Marking this as `blocked` pending feedback from @k88hudson and @AnaMedinac and @tdsmith

**Comment by pdehaan** [comment]
Which API are you referring to? Will this be something in Experimenter, something via nimbus-shared module, or is there a Firefox/Bugzilla API for version numbers?

**Comment by pdehaan** [comment]
Per https://github.com/mozilla/nimbus-shared/pull/59, do we still need the Firefox Version dropdown field in the UI, or are we hardcoding everything for Release channel only?

**Comment by k88hudson** [comment]
For MVP i think we could get away with having this be not in the UI and targeting the current version only – however, in the future I would imagine the default for this being the current release version, with the ability to edit it. What do you think @AnaMedinac @tdsmith, does that fit with most existing use cases?

**Comment by tdsmith** [comment]
I think it makes the most sense to allow users to specify a minimum version; I think we will often want to synchronize message launches with feature availability. Deploying a message to the release channel is not sufficient to restrict it to users that have the ability to use a feature.

Experiment owners usually don't want a maximum version constraint; AIUI that's imposed to limit release QA work.

**Comment by pdehaan** [comment]
> allow users to specify a minimum version

@tdsmith What is a "minimum version"? Are you thinking major releases (78.0, 79.0, etc) or more like minor/patch versions (78.0.2, 79.1)

**Comment by tdsmith** [comment]
We've expressed constraints on build_id before 🙃 but I think major version should be sufficient for most use cases

**Comment by jaredlockhart** [comment]
@tdsmith MVP1 is specifically interested only in the minimum requirement to launch A/A experiments, so I don't think targeting considerations that are specific to messages are applicable yet.  What are your thoughts on version constraints within the context of A/A?

**Comment by tdsmith** [comment]
I meant to respond to Kate's question about existing use cases for version targeting.

If you're asking if an element of the wireframe is a real requirement, I defer to Ana; if a version filter exists at all for A/A tests it would be virtuous for it to behave the same way that everything else will require; I think the only technical reason to include a version filter for A/A tests would be to exercise our version targeting, which does seem valuable.

**Comment by jaredlockhart** [comment]
@tdsmith Okay then that leads back to my original questions, what are the semantics? Is it the minimum version? Exact version? How is that represented in the recipe/audience/filter expression?

**Comment by tdsmith** [comment]
I nominate "minimum version" and have no useful opinions about how that's expressed to clients.

**Comment by jaredlockhart** [comment]
@k88hudson I think it falls to you then?

**Comment by k88hudson** [comment]
Sounds good, let's go with this field reflecting the minimum version - defaulting to whatever is the current Firefox release version - with the ability to change it.

For example, if the current Firefox release is `80`, we would set this field in the UI to be `80` by default, which would translate into `version >= 80` in targeting

**Comment by k88hudson** [comment]
I know it's extra work to calculate the current release, but I think weshould implement it at some point (i have some code written for that in bugzy we could refactor or maybe there is an API somewhere?)

**Comment by jaredlockhart** [comment]
Blocked on https://github.com/mozilla/nimbus-shared/issues/73

**Comment by jaredlockhart** [comment]
Blocked on https://github.com/mozilla/nimbus-shared/milestone/3

**Comment by jaredlockhart** [comment]
When we serialize the recipe we just need to use the filter expression here:

https://github.com/mozilla/nimbus-shared/blob/main/data/ExperimentDesignPresets.ts#L25

and python string substitute in the firefox version.
