### ISSUE TITLE
Audience field suggests entering text

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2966]
<img width="288" alt="Screenshot 2020-07-02 17 21 09" src="https://user-images.githubusercontent.com/119884/86414082-f7fbac80-bc90-11ea-91d2-67ca347aa294.png">

`Description` suggests entering text in a text field, where this is a select drop down, so I would expect the verb to be `Select`.  What do you think @AnaMedinac ?

**Comment by AnaMedinac** [comment]
Great point, it will be a drop down, so `Select...` makes sense. I checked and I saw that currently on stage it says `Select...` so I'll close this bug.

**Comment by jaredlockhart** [comment]
I see this on stage:

<img width="1175" alt="Screenshot 2020-07-13 13 32 58" src="https://user-images.githubusercontent.com/119884/87334897-66e8c900-c50d-11ea-96ac-b76dad8e0715.png">

Which says 'Description of audience'

But this isn't critical for A/A so I don't think it's worth reopening or changing
