### ISSUE TITLE
Rapid detail page state for requested review

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2995]
After the review is requested, we need a state on the detail page to show that the review has already been requested, and that the experiment can no longer be edited.

**Comment by jaredlockhart** [comment]
Probably want to do a couple things:

- Update 'Draft' to 'Pending Review' or something
- Grey out the blue 'Request Review' button, maybe change its text?
- Disable the 'Back' button that takes you back to the edit page (I would think the disabled state should be grey, so maybe it shouldn't be grey when it's not disabled like it is now?)

**Comment by AnaMedinac** [comment]
Here is a screen shot of the `Requested Review` state:

<img width="644" alt="image" src="https://user-images.githubusercontent.com/22782298/87332918-5aaf3c80-c50a-11ea-92ce-215d294f31a7.png">



I've updated the Figma to reflect the states, here: https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/WIP-Platform-Exp?node-id=214583%3A0

Also as reference here is the user flow with the states: https://miro.com/app/board/o9J_kpOgUTE=/
