### ISSUE TITLE
Subtitle says 'A/A CFR' but I think A/A is not using CFR anymore

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2999]
On the subheader of the edit page it says

`Create and automatically launch an A/A CFR experiment. A/A experiments measure the accuracy of the tool.`

but I think that the A/A experiment type doesn't involve CFR at all so I don't think this wording is correct?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-195)

**Comment by jaredlockhart** [comment]
@AnaMedinac thoughts?

**Comment by AnaMedinac** [comment]
That was unintentional - feel free to drop the CFR. I've updated the Figma too.

**Comment by jaredlockhart** [comment]
Just remove all references to CFR in the UI and code.
