### ISSUE TITLE
Remove telemetry fields from Experiment model

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3008]
I think the telemetry field definitions will be statically defined in the nimbus shared repo:

https://github.com/mozilla/nimbus-shared/blob/main/data/features/picture_in_picture.toml#L10-L12

so there's no need to store them on the experiment model.

**Comment by bhushan-borole** [comment]
Hello @jaredlockhart.
To resolve this issue these parameter should be removed right?
https://github.com/mozilla/experimenter/blob/7a5623042535f36896e24bb5e917df10a9715d6a/app/experimenter/experiments/models.py#L239
