### ISSUE TITLE
Rapid detail page state for Live experiment

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3009]
When the experiment goes live, we need to reflect that on the detail page. Some ideas:

- Status pill goes to Live
- `Request Review` button is gone?
- Links to dashboards?

**Comment by AnaMedinac** [comment]
Here is a screen shot of the `Live` state:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/22782298/87334699-12dde480-c50d-11ea-9aab-6f02694552ec.png">


I've updated the Figma to reflect the states, here: https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/WIP-Platform-Exp?node-id=214583%3A0

Also as reference here is the user flow with the states: https://miro.com/app/board/o9J_kpOgUTE=/
