### ISSUE TITLE
Public API for Rapid Experiments

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3010]
Let's add the public API for Rapid Experiments using the Rapid Serializer here:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/api/v1/serializers.py#L252

Update:

Let's make this a new API version, so we'd have

`/api/v4/experiments/`
`/api/v4/experiments/<slug>/`

using the rapid recipe serializer for experiments of type Rapid in the following states:

Accepted
Live
Complete

and use the `get_prefetched` method on the model manager so we dont' make a ton of db calls, example:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/api/v1/views.py#L19

**Comment by tdsmith** [comment]
It would be convenient for Pensieve if we had an endpoint like `/api/v1/experiments/` that would expose the entire collection of experiments at once, though we can hit the existing experiments/ endpoint and then pull individual experiments in Nimbus format on-demand if we have to.
