### ISSUE TITLE
Should `Request Approval` be `Request Review` in rapid detail page?

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3011]
I just noticed that the button to submit for review says `Request Approval` but we use the word `Review` in a lot of other places, so I just wonder if we want to use the word `Review` or `Approval`?  Whichever we pick we should make sure the rest of the UI is consistent with it (just inside of the rapid stuff, I don't think it's necessary to make the rapid workflow and the old workflow consistent), like when we update the status badge to the next state, `In Review` vs `Pending Approval` or something?

**Comment by bhushan-borole** [comment]
I understand consistency is the main point here.
In my opinion review button should be named `Request Review` and not `Request Approval`.
I can work on resolving this issue.

**Comment by AnaMedinac** [comment]
We will dive deeper into this and the different states we want to have with UX and Content for M2. Closing it for now.
