### ISSUE TITLE
Compute bucket size at launch time

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3014]
When we have real data for audience and features we'll be able to compute the number of buckets an experiment needs.  Awaiting details from @tdsmith .

**Comment by jaredlockhart** [comment]
Blocked on data and feedback and design from @tdsmith

**Comment by tdsmith** [comment]
We can afford not to block on this for the A/A MVP; hard-coding 1% will give us the populations we need for that. This'll be more important when we gear up to run real experiments.

I think hashing out a spec for this in the MVP timeframe is reasonable, and I'll work on breaking this down, but the implementation can come later.

**Comment by jaredlockhart** [comment]
Blocked on https://github.com/mozilla/nimbus-shared/issues/69

**Comment by jaredlockhart** [comment]
Blocked on https://github.com/mozilla/nimbus-shared/milestone/3

**Comment by jaredlockhart** [comment]
No fancy computing, it's just a constant:

https://github.com/mozilla/nimbus-shared/blob/main/data/ExperimentDesignPresets.ts#L37

**Comment by jaredlockhart** [comment]
What we need to do is create the actual bucket range object in the task here:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/kinto/tasks.py#L23-L25

by calling this method:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/models.py#L1330

and then updating the serializer to actually serialize the bucketrange object instead of returning a hard coded dict

and then THAT has to use the number of buckets from teh design template

**Comment by jaredlockhart** [comment]
Oh and the namespace is the normandy slug
