### ISSUE TITLE
Clarify what Bugzilla tickets are for (in Details UI) and when they should be created for Nimbus Experiments?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#3015]
My vote (not that this is a democracy) is that we create the Bugzilla ticket after the user clicks the "Submit for Approval" button [I can't imagine we care about the experiment if the user never clicks Submit]. Once the request has been submitted, I imagine a Bugzilla ticket makes sense for transparency.
If the experiment is rejected, we auto-close the Bugzilla ticket.
If the experiment is approved, we could potentially update the Bugzilla ticket with the approver and start date, etc.
But I think you mentioned that the current Experimenter workflow already has GitHub integration, so you've probably already wired up the plumbing on things that need to be submitted to Bugzilla.

_Originally posted by @pdehaan in https://github.com/mozilla/experimenter/issues/2876#issuecomment-652057461_

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-196)

**Comment by jaredlockhart** [comment]
Blocked on further discussion with @k88hudson @AnaMedinac

**Comment by jaredlockhart** [comment]
Colinked https://github.com/mozilla/experimenter/issues/3012

**Comment by k88hudson** [comment]
In [user testing](https://docs.google.com/document/d/1IKR3hp91WhsFXplROeIHCrNuKNkeeaaLcyvJ67xArvg/edit#) it also wasn't clear what experiment owners are supposed to do with the Bugzilla ticket or what it's for, so we should clarify that as well
