### ISSUE TITLE
Add slug only API in V1

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3044]
The data tools team needs an API that only returns the list of slugs and is filterable on status, let's add that to the V1 API.

**Comment by tiftran** [comment]
Don't exactly have all the context, might be a dumb question but
is this https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v1/experiments/?status=Draft sufficient?

**Comment by jaredlockhart** [comment]
Yeah basically in theory that should be sufficient, but because of the number of db calls it makes, it's still quite slow, and the new nimbus monitoring dashboard needs to get a list of slugs, and using the call you mentioned above takes ~2.5s.  So we could either try to setup a caching strategy for it, but that gets kinda messy (simple in theory, ugly in practice) or we could just make an endpoint that only gets the list of slugs, which should be snappier.  This is basically a bandaid solution because it's easier to do than building a proper caching strategy.

**Comment by jaredlockhart** [comment]
Actually before we do this, let's do this:

https://github.com/mozilla/experimenter/issues/3010

and see what the performance of that endpoint is like before we do this, since ultimately what we need are the slugs for the rapid experiments.

**Comment by jaredlockhart** [comment]
Now that PIBAL is moving into experimenter we wont' need this.
