### ISSUE TITLE
404 on CSS source map

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#3055]
Randomly spotted in devtools console while trying to submit a new Rapido experiment.

```
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://stage.experimenter.nonprod.dataops.mozgcp.net/static/assets/css/index.css
Source Map URL: /static/assets/index.css.map
```

https://stage.experimenter.nonprod.dataops.mozgcp.net/static/assets/css/index.css defines the source map at the bottom:

```css
/*# sourceMappingURL=/static/assets/index.css.map */
```

This 404s https://stage.experimenter.nonprod.dataops.mozgcp.net/static/assets/css/index.css.map, which explains the source map parsing error.

I think the core problem is that the CSS has an invalid path to the source map:

- /static/assets/css/index.css
- /static/assets/index.css.map (I do believe this needs to be in the css/ directory along with the CSS file, not in the parent dir)

Note that going to https://stage.experimenter.nonprod.dataops.mozgcp.net/static/assets/css/index.css.map directly prompts you to download the index.css.map file, so we know the path is correct.

**Comment by bhushan-borole** [comment]
Hey @pdehaan 
I would like to take on this issue.
I am facing an issue, in the repo, I can't find `index.css.map` anywhere

**Comment by pdehaan** [comment]
@bhushan-borole Yeah, I imagine that the CSS sourcemap is a generated artifact from Webpack/Parcel or something. Let me poke around and see if I can figure out the CSS pipeline and report back (unless somebody else knows off the top of their head and beats me to it).

**Comment by pdehaan** [comment]
I _think_ maybe the source mapping is happening via Parcel here: https://github.com/mozilla/experimenter/blob/0f4f6bfa8143e2095bc0b6d7d80e812b88d6f201/app/experimenter/static/core/package.json#L76-L77

**Comment by bhushan-borole** [comment]
So I will have to add the `css/` after the `/static/assets/` ?

**Comment by pdehaan** [comment]
@bhushan-borole I dont think so. I think appending `css/`would break the js/* bundling.

I've been trying to research Parcel CLI and how to configure CSS source maps and haven't found an answer yet, although we could potentially disable source maps via https://parceljs.org/cli.html#disable-source-maps (although not sure if that is too severe).

**Comment by bhushan-borole** [comment]
I will try disabling source maps, and shoot a PR, let's see if it works out.
Is it fine? @pdehaan
