### ISSUE TITLE
400 Bad Request console error when trying to Request Approval for a Rapid experiment

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#3056]
### STR

1. https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/rapid/beep-de-boop/ (or create a new experiment)
2. Click the [Request Approval] button.
3. Open your devtools console.

### Actual results

```
[XHR] POST https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v3/experiments/beep-de-boop/request_review/    [HTTP/2 400 Bad Request 88ms]
```

<img width="1684" alt="Mozilla_Experimenter_and_New_Issue_·_mozilla_experimenter" src="https://user-images.githubusercontent.com/557895/87717526-60548e80-c765-11ea-99c2-ab47f52eb068.png">

**Comment by jaredlockhart** [comment]
This might actually be the correct behaviour, can you do it again and look at the response payload of the 400 request?

**Comment by pdehaan** [comment]
Oh interesting:

> ```
> status: [ "You can not change an experiment's status from Review to Review" ]
> ```

<img width="1680" alt="Mozilla_Experimenter" src="https://user-images.githubusercontent.com/557895/87731099-7c185e80-c77e-11ea-9373-1605656aa951.png">

So I think I was confused because the label said "Draft" so I spammed the button a couple times. And now I'm in a Review state, but i can still press the "Request Approval" button and get that error. I'll have to poke at this tomorrow and see if I can break this apart into separate bugs since there might be a couple different conflicting issues here. 🐟

**Comment by jaredlockhart** [comment]
Closing as duplicate of https://github.com/mozilla/experimenter/issues/3004
