### ISSUE TITLE
Use nimbus_shared to validate rapid experiment schema

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3058]
Now that the experiment schema is landed in the shared repo and the validator is there, let's use it to validate the schema in our tests.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-199)

**Comment by jaredlockhart** [comment]
Note: we're missing proposedDuration, but that'll just be fixed when we validate against the proper schema.

**Comment by mythmon** [comment]
@jaredlockhart can you add some details about what is blocking this?
