### ISSUE TITLE
cloning for multi-pref studies doesn't take the prefs with it

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#3059]
cloning for multipref studies doesn't take the multiple prefs. 

this is super error prone to do manually - and having done it 4 times in recent history - it's a time suck.

I'd like to this be a P1 - as I just have forgotten to file - but I've hit it at least 6 times this year.  Every time I'm holding my breath hoping I get it right and triple checking.  Saw a customer have issues with getting the right pref values across 3 experiments - which would have been a lot less likely with a pref clone.

**Comment by jaredlockhart** [comment]
Oh no!!! Why didn't we catch this after the first time! They should absolutely be cloned, we'll get to this first thing next week!
