### ISSUE TITLE
Experiment screenshots per variant

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#306]
Rather than a single screenshot for the whole study, we should have a screenshot for each variant.  Of course they should be optional.

**Comment by shell1** [comment]
we are closing out a bunch of these original "we could possible do x" UX enhancements.  Mid-year after 2 quarters of development - we will look at the UX and see all up what changes will be truly helpful to the users.  Don't want a bunch of ideas in the backlog that might get worked on individually - and conflict with more recent changes.
