### ISSUE TITLE
Add link to Analysis Report after enrollment period ends

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3066]
After the enrollment period is complete, a link to an analysis report will become available.  We need to add it to the detail page.  We should probably put a placeholder that says 'your analysis report will become available on such and such date' and then replace that with the real link when it's ready.  It'll be a predictable url that includes the slug.  Blocking on @tdsmith to provide the root URL.

**Comment by tdsmith** [comment]
https://metrics.mozilla.com/protected/experiments/{{ slug }}.html

**Comment by jaredlockhart** [comment]
*Note change dashes to underscores for the slug

**Comment by jaredlockhart** [comment]
Just lift this:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/static/rapid/components/experiments/ExperimentDetails.tsx#L180-L187

into here:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/static/rapid/components/experiments/ExperimentDetails.tsx#L86-L101
