### ISSUE TITLE
Convert Rapid intake form's read-only Hypothesis field into a multiline textarea?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#3093]
https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/rapid/testing-rapido-intake-1

I have a sample hypothesis [with line breaks and such] from an existing live experiment. I didn't paste the content here since I wasn't sure if there was confidential information.

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/88237745-bda08200-cc34-11ea-8f65-49d51070e9c1.png)

When you're in the read-only view (i guess anything other than initial form input state), the Hypothesis is a single line input which is very difficult to scan if you have a medium or larger sized hypothesis.

**Comment by jaredlockhart** [comment]
Blocked pending UI discussion this week with @AnaMedinac

**Comment by k88hudson** [comment]
I think it would be fine to just show this as a text paragraph, if not a textarea.
