### ISSUE TITLE
Set APPEND_SLASH to False

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3125]
We keep running into situations where clients hit endpoints without trailing slashes and get redirected through the auth boundary, so we should just set this to False in settings.py

https://docs.djangoproject.com/en/3.0/ref/settings/#append-slash

`settings.py`:
```py
APPEND_SLASH = False
```

**Comment by jaredlockhart** [comment]
@bhushan-borole This would be an easy one to pick up!

**Comment by bhushan-borole** [comment]
> @bhushan-borole This would be an easy one to pick up!

Sure I would love to fix this issue!

**Comment by jaredlockhart** [comment]
This causes significant breakage in at least the integration tests and possibly elsewhere, and I don't think the demand for it right now is high enough to warrant that level of investment.  Let's close this for now and if it becomes a more significant problem we can reopen or refile it.
