### ISSUE TITLE
Requesting approval triggers the wrong request in Remote Settings?

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#3139]
When attempting to test publishing experiments to staging, I noticed that a different experiment (not the one I requested review on) got pushed to Remote Settings – or maybe there's just a significant delay?

**Comment by k88hudson** [comment]
- Check happens every 5 minutes
- Waits for approval to happen before incrementing in the queue

**Comment by jaredlockhart** [comment]
Blocked on further discussion.

**Comment by jaredlockhart** [comment]
Closing pending refiling
