### ISSUE TITLE
Rollout in experimenter - the tooling wrote it as an experiment

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#3140]
What we suspect happened is this started out as a type experiment and was edited and then was changed to type rollout - 

and the experiment flag got set and kept.  All the branches that were originally entered were also moving over into the recipe.  multi-pref branches.

ex where it happened:
https://experimenter.services.mozilla.com/experiments/activity-stream-pocket-new-tab-spoc-personalization-v2-rollout/

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-204)

**Comment by jaredlockhart** [comment]
<img width="784" alt="Screenshot 2020-07-28 17 06 51" src="https://user-images.githubusercontent.com/119884/88721858-c42b6f80-d0f4-11ea-96d6-160f781a785b.png">

Yep that's exactly what happened.  K I'll take a look at it when I get some cycles.
