### ISSUE TITLE
update the help for add-on rollout and experiment

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#3141]
update the help of Signed Add-On URL

Enter the URL where your release signed add-on can be found.  This MUST BE the release signed add-on (not the test signed add-on) that you want deployed. See here for more info.

"See here for more info" already links to the right place - https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments

**Comment by rehandalal** [comment]
Maybe:

```
Enter the URL to your release signed add-on. This should be a link to a 
taskcluster artifact that was signed as part of a "release build" not a 
"dep build".
```
