### ISSUE TITLE
Enabled field should be set to false after experiment is complete

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#3148]
After an experiment has been completed, it should be set to `enabled = false` in the public API

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-207)
┆Issue Number: EXP-207

**Comment by k88hudson** [comment]
Added to test cases here https://docs.google.com/document/d/1ZRGbpifv3qS_igW6Gx06mwehXwScyN6JMxFzcuGG3wA/edit#heading=h.ewf760w0v8d6

**Comment by pdehaan** [comment]
What about if the experiment is rejected? Should we set `enabled=false` there too?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

@peter - that is captured by `status`
