### ISSUE TITLE
Non live experiments show "Unknown - Unknown (Unknown days)" on experiment list page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#3150]
https://stage.experimenter.nonprod.dataops.mozgcp.net/?owner=31&archived=on

We display "Unknown - Unknown (Unknown days)" on the experiment list page for "Draft" and "Ready for Sign-Off" experiments; but it seems like the dates get populated/calculated once the experiment is "Accepted by Normandy" or "Live".

Not sure if we should hide the "Unknown - Unknown (Unknown days)" text since its kind of confusing and unhelpful.

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/88822443-b6b7c900-d178-11ea-9897-1e8abdb72576.png)

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/88822395-a6075300-d178-11ea-89a3-c90d1a6c26b3.png)

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/88822667-00081880-d179-11ea-8516-3a2c5f1dfeb5.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-209)
┆Issue Number: EXP-209

**Comment by jaredlockhart** [comment]
Yeah this is how we've always had it, I'm open to suggestions about what we'd like to put there.

**Comment by pdehaan** [comment]
I'd vote to just hide that block of known unknowns.
But yeah, prior art+nonblocking. P5 it into the abyss.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This will be obsolete with the new directory view, so, effectively this is a wontfix.
