### ISSUE TITLE
Update nimbus-shared npm module to 0.0.9

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#3156]
Looks like the npm version is pinned to 0.0.7 and the Python version is pinned to 0.0.9. I can't imagine that's going to break anything, but definitely a potential risk for chaos. 🐒 

https://github.com/mozilla/experimenter/blob/f5098daba0d557bf0161b477e8602935473c7b85/app/experimenter/static/rapid/package.json#L7

https://github.com/mozilla/experimenter/blob/a74f4024a55704169a71d7697a3f7931b4337dde/app/requirements/default.txt#L169

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-212)

**Comment by jaredlockhart** [comment]
AHA!!! See I knew this would happen.  We need to add a static check that asserts those two are the same.

**Comment by pdehaan** [comment]
I was hoping Dependabot would keep these always in sync, but I'm guessing it was a manual bump for the Python module for a bug fix and we didnt bump npm at the same time.

**Comment by jaredlockhart** [comment]
Done and done:

https://github.com/mozilla/experimenter/blob/main/app/pyproject.toml#L52
