### ISSUE TITLE
[rapid] Add note that hypothesis isn't public info

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#3165]
Currently the UI doesn't indicate which fields are public or private.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-220)
┆Issue Number: EXP-220

**Comment by k88hudson** [comment]
Perhaps we can add something in the description along the lines of `This will only be seen by users with LDAP access` or something? Added a comment in figma https://www.figma.com/file/lAP4IeohBNMPawhsUaB4nq?node-id=27:1735#36357545
