### ISSUE TITLE
Move audiences, features, and preset data into Experimenter

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#3172]
Based on our conversations around making it easier to iterate on audiences, features, etc. as we build out Nimbus experiments, let's move the data from nimbus-shared into Experimenter.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-223)

**Comment by jaredlockhart** [comment]
I think I'm gonna close this in favour of just building the relevant models.
