### ISSUE TITLE
Create role for users who are allowed to create nimbus experiments

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#3174]
We should create a role for users who are allowed to create nimbus experiments which only gets set after a user has gone through training.

This role should allow the user to see all routes and make edits.

Users who do not have this role should only be able to see the directory view **(without a create new button)**, the summary view (/:slug), and results view.

See also #3199

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-224)
┆Issue Number: EXP-224

**Comment by jaredlockhart** [comment]
This is doable using django roles.
