### ISSUE TITLE
Rename “Objective” to "Hypothesis"

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#3175]
**Rename** "Objective" to "Hypothesis"

**new help text:**  Please fill in the hypothesis following the formula in the box.  There may be multiple hypothesis in one experiment.  
For roll-outs - please fill in follow the same formula - but substitute the second sentence with "we believe a rollout is needed to mitigate `describe the technical or perception risk`".

**new in box guidance (should not disappear when they start typing):**
If we `"do this/build this/create this" change in the experiment` for `these users`, then we will see `this outcome`.

We believe this because we have observed `this` via `data source, UR, survey`.

Optional - We believe this outcome will `describe impact` on `core metric`.

**note** - i wasn't sure how to indicate the text should be different, without messing up the ticket because my angle brackets were interpreted as mark-up.  I like how this looks in github - but please use whatever will look good in experimenter.  It may be sharp angle brackets around the info - if the inbox text doesn't like the mark-up.

**update** help text on "Internal Description"
**new help text**
Describe the details / purpose of your delivery in for internal consumers.  This assists supporting teams to understand what you are doing and helps avoid delays.  It is also a useful reference to understand the experiments that have been run.

Please add any bugs and/or issues related to this delivery work. Link to any PRDs, Invision, or related documents. Please include a description of for each link. 

**Hide** "Related Work URLs" 
With the mandatory addition of "Public Description" - "internal description" can now capture everything - including what we used to put in "related work URLs".  Removing this duplicate / possibly confusing field.

**Comment by mythmon** [comment]
@shell1 FYI, this turned out pretty hard to read because a bunch of words got removed. GitHub doesn't like when you have `<` angle brackets `>` surrounding a single word, since it's HTML sanitizer is a bit aggressive. So something like

```
<multiple words>
```

comes out ok, but

```
<oneword>
```

Gets deleted.

You can fix it by editing the message and putting a backslash before the first bracket

```
\<like> \<this>
```

Alternatively, {curly braces} will work just fine.
