### ISSUE TITLE
Move all targeting expression generation logic to Nimbus serializer

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#3203]
Right now we have some logic for how filter expressions are generated in preset strings https://github.com/mozilla/nimbus-shared/blob/main/data/ExperimentDesignPresets.ts#L25, and some of it in Experimenter ([here](https://github.com/mozilla/experimenter/blob/a74f4024a55704169a71d7697a3f7931b4337dde/app/experimenter/experiments/api/v4/serializers.py#L108) and [here](https://github.com/mozilla/experimenter/blob/a74f4024a55704169a71d7697a3f7931b4337dde/app/experimenter/experiments/api/v4/serializers.py#L113)).

After taking a look with fresh eyes, I think it makes more sense to move this code to one place (i.e. in the serializer), given that the string templates we've defined are tightly coupled to the serializer and we're likely to change it as we iterate on what we support with Nimbus.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-226)
┆Issue Number: EXP-226

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

We won't be making any changes to v4 so I'm going to close this.
