### ISSUE TITLE
Change targeting/filter_expression in v4 to use a constant

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#3204]
Remove the filter_expression property from the serializer

For the targeting field, create a create a string template constant for each application. 

For Firefox Desktop, it should be:

'browserSettings.update.channel in {firefox_channels} && env.version|versionCompare('{minFirefoxVersion}') >= 0 && {targetingConfig}

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-227)
┆Issue Number: EXP-227

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

So keep the rapid prototype intact we won't be modifying it in any way, I'm going to close this and file a new ticket for any V5 related work.
