### ISSUE TITLE
Remove `userId` from supported randomization units in external API

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#3205]
In https://github.com/mozilla/nimbus-shared/commit/336d51620c1ac6d44417f7c4a3dff83d34f6e706 we added `userId` as an optional for randomization units, but as of the /v5` api / Firefox 81, I don't think we should support this as an option (`normandy_id` is probably more descriptive). 

Let's remove it and make sure the Bugzilla ticket to implement `bucketConfig`-based bucketing is able to understand `normandy_id`. https://bugzilla.mozilla.org/show_bug.cgi?id=1656500.

To clarify, the only two options for now should be:
- `normandy_id`
- `client_id`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-228)
┆Issue Number: EXP-228

**Comment by piatra** [comment]
This is dependent on https://github.com/mozilla/nimbus-shared/pull/111

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

We won't be making any changes to v4 so I'm closing this.
