### ISSUE TITLE
Add platform to experiment definition

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#3210]
In order to support mobile experiments and other platforms, we will need to define `platform` in the following areas:

Platforms should include `fenix` and `firefox-desktop`

- in the API (to route them to the correct clients)
- in the UI (users should be able to select which platform their experiment will be run on)
- in our schema

See [updated figma](https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/WIP-Platform-Exp?node-id=214583%3A0) : 
![image](https://user-images.githubusercontent.com/1455535/89911498-82ec9280-dbbf-11ea-9e97-562361d1436b.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-230)

**Comment by jaredlockhart** [comment]
Let's close this and we can refile something new when we start getting the new UI stood up.
