### ISSUE TITLE
Move rapid JS bundle from base template to rapid base template

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3216]
Move this:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/templates/base.html#L164

to here:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/templates/experiments/rapid.html#L7-L8

**Comment by jaredlockhart** [comment]
@bhushan-borole This would be another good quick bug!

**Comment by bhushan-borole** [comment]
Sure I will work on it.
Can you assign it to me please? @jaredlockhart
