### ISSUE TITLE
Use new remote settings collection

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#3217]
When we land changes to the finalize the v5 API, we should switch to a new remote settings bucket 

See Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1656503

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-73)
┆Issue Number: EXP-73

**Comment by piatra** [comment]
Collection name is `nimbus-desktop-experiments`

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

This doesn't need to be its own ticket, it can just be folded into https://jira.mozilla.com/browse/EXP-439
