### ISSUE TITLE
Validate JEXL targeting property in Firefox in CI

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3243]
Let's see if we can setup a way for a Firefox client (maybe of some specified version(s)?) to execute the `targeting` JEXL expressions that Experimenter generates for rapid Nimbus experiments in circle as part of our CI run.

Instructions from @k88hudson:

Ok, this works with a couple of important caveats:

* randomizationUnit has to be `userId`, not `normandy_id`. This would be easy enough to express if this were in code but it might simplest here just to write out `userId` in the template string since we only support a single randomization unit option right now anyway.
* this will fail if either `audienceTargeting` or `audienceFilterExpression` are undefined.

I tested with the following steps.

1. Open Firefox Nightly (version 80)
1. Add the following to the Browser Toolbox console:

{{Cu.import("resource://gre/modules/components-utils/FilterExpressions.jsm");
Cu.import("resource://gre/modules/components-utils/ClientEnvironment.jsm");
Cu.import("resource://messaging-system/lib/RemoteSettingsExperimentLoader.jsm");

// Filter expression
var minFirefoxVersion = "78";
var audienceFilterExpression = undefined;

// Targeting
var randomizationUnit = "userId";
var bucketNamespace = "foo-1232ad3";
var bucketStart = 0;
var bucketCount = 50;
var bucketTotal = 100;
var audienceTargeting = "localeLanguageCode == 'en'";

var recipe = {
  // These are your preset expressions, converted to JS
  filter_expression: `env.version|versionCompare('${minFirefoxVersion}') >= 0 && ${audienceFilterExpression}`,
  targeting: `[${randomizationUnit}, "${bucketNamespace}"]|bucketSample(${bucketStart}, ${bucketCount}, ${bucketTotal}) && ${audienceTargeting}`
};

// 1. Test filter_expression by simulating RS filtering https://searchfox.org/mozilla-central/source/services/settings/remote-settings.js#63
await FilterExpressions.eval(recipe.filter_expression, {env: ClientEnvironmentBase});

// 2. Test targeting by calling RemoteSettingsExperimentLoader
await RemoteSettingsExperimentLoader.checkTargeting(recipe);}}

1. Try different user Ids to see if you get a different result from the `targeting`. These are the ones I tried:

{{app.normandy.user_id=dd438e6c-03cf-d144-8e71-ab94b3d6c570 => true
app.normandy.user_id=asdasdas => false}}

1. Try changing the `minFirefoxVersion` to something in the future (e.g. 88) to see if it resolves to `false`.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-71)
┆Issue Number: EXP-71

**Comment by piatra** [comment]
We had this setup for [activity-stream](https://github.com/mozilla/activity-stream/) running mochitests in Taskcluster CI.
Have a look at the [taskcluster config file](https://github.com/mozilla/activity-stream/blob/master/.taskcluster.yml) it was running a custom docker image with the firefox source code inside it and executing [a shell script](https://github.com/mozilla/activity-stream/blob/master/mochitest.sh).

**Comment by jrbenny35** [comment]
Some questions:

* Should the filter expression ever evaluate to true? If so, under what condition would make it do that?
* Is there a concrete way to get ```targeting``` to return true? You provided 2 examples but for testing it would be nice to know what exactly was needed.

**Comment by jaredlockhart** [comment]
@jrbenny35 great point, I don't think we need to worry about that for the first pass, the thing I care the most about is if any of the keys like `localeLanguageCode` is mispelled and returns `undefined` does the whole string come back as undefined.

**Comment by jaredlockhart** [comment]
Here's an example of an up to date filter expression:

```js
channel in ["Nightly", "Beta", "Release"] && version|versionCompare('80.!') >= .! && localeLanguageCode == 'en'
```

**Comment by jaredlockhart** [comment]
Here's an example @k88hudson wrote to test the targeting directly against the filterexpression module in firefox:

https://phabricator.services.mozilla.com/D93588#change-F9oCEGntQron

**Comment by jaredlockhart** [comment]
Here's a way to test it that might be more useful, note: changing the bucketing to always match ie 100/100 buckets enroll

```js
Cu.import("resource://gre/modules/components-utils/ClientEnvironment.jsm");
Cu.import("resource://messaging-system/lib/RemoteSettingsExperimentLoader.jsm");

// Targeting
var randomizationUnit = "userId";
var bucketNamespace = "foo-1232ad3";
var bucketStart = 0;
var bucketCount = 100;
var bucketTotal = 100;
var audienceTargeting = "localeLanguageCode == 'en'";

var recipe = {
// These are your preset expressions, converted to JS
targeting: `[${randomizationUnit}, "${bucketNamespace}"]|bucketSample(${bucketStart}, ${bucketCount}, ${bucketTotal}) && channel in ["Nightly", "Beta", "Release"] && version|versionCompare('80.!') >= .! && localeLanguageCode == 'en'`
};
```

**Comment by k88hudson** [comment]
Some examples:

### Testing the actual environment of the browser
This is how you would test that a targeting expression is valid according to the *actual conditions in the browser*:

```js
// Setup
Cu.import("resource://messaging-system/lib/RemoteSettingsExperimentLoader.jsm");
const EXPRESSION = "version|versionCompare('80.!') >= 0 && localeLanguageCode == 'en'`;

const actual = await RemoteSettingsExperimentLoader.checkTargeting({targeting: EXPRESSION});
// You would expect this to evaluate to true ONLY if the *actual* version of the browser was
// greater than 80 and the locale started with en.
assert.equal(actual, true);
```

### Testing an expression with a *simulated* environment
This is how you would check if a targeting expression works, but simulate the environment of the browser.

```js
const { TargetingContext } = ChromeUtils.import(
  "resource://messaging-system/targeting/Targeting.jsm"
);
let targeting = new TargetingContext();

const ENVIRONMENT = {version: "80.1", localeLanguageCode: "en-US"};
const EXPRESSION = "version|versionCompare('80.!') >= 0 && localeLanguageCode == 'en'`;

const actual = await targeting.eval(EXPRESSION, ENVIRONMENT);
assert.equal(actual, true);

**Comment by jrbenny35** [comment]
I am getting this error. ```Token !  (unaryOp) unexpected in expression: [userID, "foo-1232ad3"]|bucketSample(0, 100, 100) && channel in ["Nightly", "Beta", "Release"] && version|versionCompare('80.!') >= .!```

Maybe my formatting is wrong?

**Comment by jrbenny35** [comment]
Does this have to be run on nightly?

**Comment by piatra** [comment]
Yes formatting was incorrect. See Kate‘s example where version compare is used to compare against a number not `.!`.

**Comment by jrbenny35** [comment]
Having this error
```
Uncaught (in promise) TypeError: can't convert a to primitive type: its [Symbol.toPrimitive] property is not a function
    eval resource://gre/modules/components-utils/mozjexl.js:1
    BinaryExpression resource://gre/modules/components-utils/mozjexl.js:1
    promise callback*95/b.BinaryExpression resource://gre/modules/components-utils/mozjexl.js:1
    eval resource://gre/modules/components-utils/mozjexl.js:1
    promise callback*94/e.prototype.eval resource://gre/modules/components-utils/mozjexl.js:1
    BinaryExpression resource://gre/modules/components-utils/mozjexl.js:1
    eval resource://gre/modules/components-utils/mozjexl.js:1
    promise callback*94/e.prototype.eval resource://gre/modules/components-utils/mozjexl.js:1
    _eval resource://gre/modules/components-utils/mozjexl.js:1
    promise callback*93/d.prototype._eval resource://gre/modules/components-utils/mozjexl.js:1
    eval resource://gre/modules/components-utils/mozjexl.js:1
    eval resource://gre/modules/components-utils/FilterExpressions.jsm:56
    eval resource://messaging-system/targeting/Targeting.jsm:192
    <anonymous> debugger eval code:17
    <anonymous> debugger eval code:18
    getEvalResult resource://devtools/server/actors/webconsole/eval-with-debugger.js:243
    evalWithDebugger resource://devtools/server/actors/webconsole/eval-with-debugger.js:167
    evaluateJS resource://devtools/server/actors/webconsole.js:1118
    evaluateJSAsync resource://devtools/server/actors/webconsole.js:1012
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103
```

**Comment by piatra** [comment]
@jrbenny35 can you please share what input you were trying to evaluate?

**Comment by jrbenny35** [comment]
> @jrbenny35 can you please share what input you were trying to evaluate?

I was using Kates suggestion of testing with a simulated environment

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Marking as High priority as this is blocking [~bforehand@mozilla.com]'s efforts.

**Comment by jrbenny35** [comment]
With the help of @piatra I have 2 tests, simply changing the version and making sure the expression returns the expected true or false based on if the version matches. Is this a sutible start? It seems the locale part of the simulated environment/expression doesn't have any effect on making the evaluation true or false.

**Comment by jaredlockhart** [comment]
@jrbenny35 Yes that sounds fantastic!

**Comment by pdehaan** [comment]
@jrbenny35 What test script were you using?
I still see the [`[Symbol.toPrimitave]` error](https://github.com/mozilla/experimenter/issues/3243#issuecomment-738958612) using Kate's "simulated env" test [above](https://github.com/mozilla/experimenter/issues/3243#issuecomment-724203164) in Firefox Nightly.

**Comment by jrbenny35** [comment]
@pdehaan 
```
const { TargetingContext } = ChromeUtils.import(
        "resource://messaging-system/targeting/Targeting.jsm"
    );
    const ENVIRONMENT = {version: 80.1, localeLanguageCode: "en-US"};
    let targeting = new TargetingContext(ENVIRONMENT);
    const EXPRESSION = `version|versionCompare(80.!') >= 0 && localeLanguageCode == 'en'`;
    console.log(EXPRESSION);
    const actual = await targeting.evalWithDefault(EXPRESSION, ENVIRONMENT);
```
