### ISSUE TITLE
Nimbus: transparency into experiments running - public description in rapid intake form

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#3264]
@AnaMedinac providing visibility for what we were experimenting on was one of the "trust and privacy" requirements that experiments were given.  It's around the Mozilla value of transparency to the user.

I don't know the way that was determined to implement this with Nimbus.  There's different theories on exposing through about:studies to users (current normandy) or gathering exposing on a website of all experiments possibly running.

The flaw with about:studies is there are experiments happening in other places (example mobile) that are not exposed in this area.  It all methods have slightly different ways of exposing - it's less easy for users to find that info.  Moving to a common website format that several experiment frameworks can feed with their information might be the best path forward.

However it is determined to expose this information - we need to capture public description to make that available somewhere.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-65)
┆Issue Number: EXP-65

**Comment by k88hudson** [comment]
Just a note that right now we have a hard-coded public description about A/A tests being diagnostic
