### ISSUE TITLE
Add validators for different feature types

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#3289]
We have schemas available for about:welcome, CFR, and moments. Let's add a validation step for the JSON value field.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-63)
┆Issue Number: EXP-63

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Duplicate of https://jira.mozilla.com/browse/EXP-510
