### ISSUE TITLE
Support feature configs in variants

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#3290]
This need further discussion, but we need to express a relationship between a `Variant` and a `Feature` (that is, to be able to include feature configs in variants)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-62)
┆Issue Number: EXP-62

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Duplicate of EXP-266
