### ISSUE TITLE
Visualization User Research

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3320]
Conducting exploratory user research on determining what information should be presented and how it should be presented with key stakeholders.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/EXP-49)

**Comment by emtwo** [comment]
Can't tell you filed this... But I believe we can call this done.
Here is the link to the figma mockups https://www.figma.com/file/q6Xh9g6LrOj2OQ59LbAFXm/Experiment-Dashboard-Mockup?node-id=0%3A1
