### ISSUE TITLE
Experiment data scientists should be included when creating an experiment

### ISSUE THREAD

**Issue by emtwo** [mozilla/experimenter#3363]
It should be possible to assign a data science owner to an experiment at creation/edit time and this would be displayed in the visualization page.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-240)
┆Issue Number: EXP-240

**Comment by data-sync-user** [comment]
➤ Marina Samuel commented:

This includes adding it as an input when creating the experiment, saving it to the database, and making sure it's available to the visualizations page.
