### ISSUE TITLE
Add text input for summary/conclusions/next steps

### ISSUE THREAD

**Issue by emtwo** [mozilla/experimenter#3365]
This would be at the top of the viz page as shown in the mockups\

We should be able to support a link to a full analysis / "results" summary in mana

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-242)
┆Issue Number: EXP-242

**Comment by shell1** [comment]
@emtwo there is a project for creating a knowledge repository that likely will relate to the work.  Kimmy is the lead - but is keeping engaged with Ana M as it progresses.  Will loop you in to cross pollinate for shared needs (like summary, conclusion, etc.).  

Here's the work in progress PRD https://docs.google.com/document/d/1vMp7TfqzMqilX0TSow4JIQjEzc4hqlE92xa_sm6BL08/edit#
