### ISSUE TITLE
Update contributing.md to include FXA protocols

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3398]
The FXA team has a lot of well thought out practices around commits, we should incorporate those into our contributing.md docs: https://github.com/mozilla/fxa/blob/main/CONTRIBUTING.md#git-commit-guidelines

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-256)
┆Issue Number: EXP-256

**Comment by jodyheavener** [comment]
Oh sweet, yeah I love the Conventional/Angular commit style 🙏

**Comment by lmorchard** [comment]
A thing we might want to do here that we've never quite done on FxA: Come up with an agreed-upon list of scopes - i.e. the "foo" in "chore(foo):"

We kind of keep meaning to do that on FxA and never quite have. So, work in similar areas all end up using slightly different scopes. Then, when we generate the changelogs from commit messages, the scope groupings are all a little off.
