### ISSUE TITLE
Add application and channel to experiment model

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3402]
Applications should include reference-browser, `fenix,` and `firefox-desktop`

Please change firefox_channel to be application_channels

Channels should be specific to each application – note that for mobile applications, each channel has an app id which needs to be used in the targeting config.

Also, channels should be many-to-many (so store as an array)

Please also update the serializers.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-260)
┆Issue Number: EXP-260

**Comment by data-sync-user** [comment]
➤ Travis Long commented:

On mobile, "platform" should probably be more aptly named as "application" if what we really want to target are specific apps with this.  Platform to me would be "iOS", or "Android", and could be a valid target for an experiment definition if we wanted to target all of our applications on a specific platform.

Right now on the nimbus-sdk side of things, we are collecting the application-id for matching/filtering purposes, which is unique per application and per application channel.  So for instance, Fenix has a unique application-id for nightly, beta, and release, that could be used to target specific apps/channels.  The same holds true for all of our mobile apps that I have worked with so far (which is most of them thanks to helping integrate Glean into them)

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

> we are collecting the application-id for matching/filtering purposes, which is unique per application and per application channel.

I'd be happy with `application` from a API perspective, that does make more sense and avoids confusion with platform meaning Windows/Mac on desktop.

**Comment by jaredlockhart** [comment]
@travis79 Please add the list of valid `channel` options for each of `reference-browser` and `fenix` to this ticket.  Thnx!

**Comment by travis79** [comment]
For Fenix:

| Channel | Associated App-id |
| :------ | :---------------- |
| Nightly | `org.mozilla.fenix` |
| Beta    | `org.mozilla.firefox.beta` |
| Release | `org.mozilla.firefox` |

Reference Browser only has a single channel (release) and its associated app-id is `org.mozilla.reference.browser`
