### ISSUE TITLE
Add FeatureConfig Model

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3408]
Let's create a FeatureConfig model.

Feature Configs need to have:**

* **slug**: unique identifier for the feature**
* **applicationId**: identifier for application

* **name**: human-readable name for the feature

* **description**: human-readable description for the feature

* **owner**: text field - email address of the owner of the feature**

* **schema** (optional):  If the feature configuration should include custom parameters, this should be a JSON Schema ([draft-07](http://json-schema.org/draft/2019-09/json-schema-validation.html)) describing those parameters. If the feature is a simple flag, this should be null.

Experiments should optionally define a relationship with a single feature id.

The value in Branch should be associated with a JSON schema for that feature.

See Technical documentation: [https://docs.google.com/document/d/1AqRetDJRMIEWGTBdNkwH9zQ2WP-v2mIklY4shJN7QWk/edit](https://docs.google.com/document/d/1AqRetDJRMIEWGTBdNkwH9zQ2WP-v2mIklY4shJN7QWk/edit#heading=h.5ekpmdxm3mm2)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-266)
┆Issue Number: EXP-266

**Comment by jaredlockhart** [comment]
Test
