### ISSUE TITLE
Support iOS versions

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3409]
We should support mobile versions in the versions drop-down. Some investigation is needed to determine what the values should be for each application

Note: Fenix shares the same version list with Desktop.  iOS will require its own version list.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-267)
┆Issue Number: EXP-267

**Comment by data-sync-user** [comment]
➤ Travis Long commented:

Here is an example of the application version strings in Fenix from October, most are in the format of A.B.C with a few A.B.C-rc1 in there.  We also see some "Unknown" and oddball versions.  
https://sql.telemetry.mozilla.org/queries/75975 ( https://sql.telemetry.mozilla.org/queries/75975 )

Firefox for iOS uses a slightly different versioning of A.B with even fewer oddballs in there:
https://sql.telemetry.mozilla.org/queries/75976 ( https://sql.telemetry.mozilla.org/queries/75976 )

Other apps vary somewhat but mostly follow semver that I have seen.

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Blocked until we are ready to address iOS

**Comment by jaredlockhart** [comment]
Versions from gh releases: https://api.github.com/repos/mozilla-mobile/firefox-ios/releases

Application info from glean: https://probeinfo.telemetry.mozilla.org/v2/glean/app-listings
