### ISSUE TITLE
Console front-end setup

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3413]
The [Experimenter ADR 0002](https://github.com/mozilla/experimenter/blob/main/app/experimenter/docs/adrs/0002-nimbus-front-end-directory-tree-and-stack.md) outlines a proposed directory tree change regarding the front-end and a new front-end stack. This epic contains issues regarding the initial setup before diving into the core of the changes.

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/EXP-271)

**Comment by LZoog** [comment]
@k88hudson I don't believe epics or user stories in FxA JIRA are synced to GH issues, we should probably follow suit here since this is a placeholder for issues and not an issue.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Engineering breakdown is complete. Issues are filed and estimated.
