### ISSUE TITLE
Disable sentry for local dev

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3414]
For most local dev no SENTRY_DSN will be set so we should just not initialize sentry if it's not set.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-272)

**Comment by jodyheavener** [comment]
Is this to avoid a console error? Counter point: this kind of error helped FxA realize that we had neglected to set an env var for a project. 🤷

**Comment by jaredlockhart** [comment]
No it's not for a console error, it's a couple things.

1) I originally set it up becuase I used sentry to debug my local dev environment becuase debugging celery tasks can be a complete nightmare, but I haven't used it in a long time

2) When you run vscode inside the containers there's this little edge case where it'll drop environment variables that don't have a value set so django complains in that specific context

So i thought we could just check if it's set before we try to initialize it?
