### ISSUE TITLE
Allow consuming server settings values on client, serve app at `/nimbus`

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3429]
Certain server settings should be exposed from Django to the client, including at least a Sentry DSN. In FxA, we expose server config data [through a meta tag](https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/public/index.html#L13). We need to do this similarly, but set up through a Django template (see https://mozilla.slack.com/archives/CANCHH6R1/p1600797437034700), and the application should be served at `/nimbus`.

Closing this issue should set us up to grab the Sentry DSN URL in EXP-282 and will serve the app to `/nimbus`. It wouldn't hurt to update the README with a quick blurb about this.

(Context history: see this Slack thread|https://mozilla.slack.com/archives/C011MC5EB0V/p1599764101070400] and a [meeting note doc](https://docs.google.com/document/d/1bM5ZDXsl2bcWRWW9W8tk47Ik9eTQJqKObHBDj5w1sao/edit) around this)

Notes from Jared:
1) add a template to host the frontend that basically looks like https://github.com/mozilla/experimenter/blob/main/app/experimenter/legacy-ui/templates/experiments/rapid.html
2) a view to host it + tests
3) a url path to it
4) the logic around using the yarn dev server on dev and static assets management on prod
The view should look like: https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/views.py#L234-L235, and here's the test: https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/tests/test_views.py#L807-L814
Example URLs: https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/urls.py#L22-L28, but in that case we were mirroring the route definitions in both django and react:
https://github.com/mozilla/experimenter/blob/main/app/experimenter/legacy-ui/rapid/components/App.tsx#L17-L33

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-283)
┆Issue Number: EXP-283

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Note: I've modified this to include serving from `/nimbus` but left it at a 3. If it seems more like a 5 when someone starts on it, bump it up. 👍

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

[~lzugai@mozilla.com] [~jkerim@mozilla.com] I think we need to take a slightly different approach with `nimbus-ui`. While in development create-react-app apps do not expose build files (unlike rapid and core which appear to watch/build/copy them to the /assets directory IIUC); they're instead hidden away and served at the React dev server address, and only visible when you generate a build. To get around this in FxA we proxy the React server while in development, and only serve the static build files in production. Is it possible to proxy a local address in our Django setup?

**Comment by lmorchard** [comment]
> To get around this in FxA we proxy the React server while in development, and only serve the static build files in production. Is it possible to proxy a local address in our Django setup?

I don't think we need to proxy here. We had [a thread in Slack](https://mozilla.slack.com/archives/CANCHH6R1/p1600797437034700) where we talked about linking directly to the webpack-dev-server in local dev and to static files in stage and prod. [Something like this with a conditional in a Django template](https://cscheng.info/2016/08/03/integrating-webpack-dev-server-with-django.html). Is this a different concern where that solution doesn't work?

**Comment by jodyheavener** [comment]
Oh you mean that Slack thread linked at the top that I didn't look at before posting 😅 I think that should do it, my bad!
