### ISSUE TITLE
Add :slug: routes, dummy pages, and navigate user after experiment creation

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3464]
EXP-299 handles creating an experiment on form submission. This task adds slug routes and navigates the user to the "edit" view. Remove any console log or alert message from that PR (see comment at the end of that ticket).

On successful new experiment creation, a `/nimbus/:slug:/` route, `/nimbus/:slug:/edit` route, `/nimbus/:slug:/edit/overview` route, `/nimbus/:slug:/edit/branches`, and `/nimbus/:slug:/request-review` routes should be accessible.

--

1) Rename `AppLayoutExperimentEdit` to `AppLayoutWithSidebar` - when the original name was suggested, it wasn't clear the non-edit state (beyond parity) also has a sidebar and nav.

2) Add a dummy `PageEditOverview/index.tsx` component to display on `nimbus/:slug:/edit/overview`, wrapped in `AppLayoutWithSidebar` - doesn't actually have to display any content, just a page component that’ll be ready for buildout. Add to Storybook.

3) Add a dummy `PageEditBranches/index.tsx` component to display on `nimbus/:slug:/edit/branches`, wrapped in `AppLayoutWithSidebar` - doesn't actually have to display any content, just a page component that’ll be ready for buildout.  Add to Storybook.

4) Add a dummy `PageRequestReview/index.tsx` component to display on `nimbus/:slug:/request-review`, wrapped in `AppLayoutWithSidebar` - doesn't actually have to display any content, just a page component that’ll be ready for buildout.  Add to Storybook.

5) `/nimbus/:slug:/` and `/nimbus/:slug:/edit` should redirect to `/nimbus/:slug:/edit/overview`. The `nimbus/:slug:/` page will later redirect based on experiment status (EXP-496 and EXP-497) but for now just redirect to the edit overview page.

6) When a user successfully creates an experiment (see EXP-299), navigate them to `nimbus/:slug:/edit/overview`

7) Modify the nav component in the sidebar in `AppLayoutWithSidebar` to link to these pages - make sure the "active page" state is blue to match Figma, (other states will be done later) and ensure the nav is a `<nav>` component with a `<ul>` and `<li>`'s (see https://react-bootstrap.github.io/components/navs/)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-295)
┆Issue Number: EXP-295

**Comment by LZoog** [comment]
This was closed in: https://github.com/mozilla/experimenter/pull/3797
