### ISSUE TITLE
Add isHighVolume flag to API 

### ISSUE THREAD

**Issue by scholtzan** [mozilla/experimenter#3478]
Normandy has a `isHighVolume` flag for high volume experiments. It would be useful if this flag could be exposed through the API so that Jetstream can ignore processing these experiments.

https://github.com/mozilla/jetstream/issues/61

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-306)

**Comment by tiftran** [comment]
Change made https://github.com/mozilla/experimenter/pull/3487 @scholtzan I believe it's on experimenter prod right now. Please kindly reopen this issue if there's something wrong :)
