### ISSUE TITLE
Expose DS Jira ticket in the Experiment page - Legacy

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#3499]
We require a DS Jira ticket for legacy experiment creation.  We need to expose a clickable link to them on the page for that experiment.  Ideally at the end of the overview section.  
![image](https://user-images.githubusercontent.com/8192232/93403980-d9dc2c00-f83d-11ea-848a-f89351813990.png)

Immediate need is to address **stakeholder experiment lifecycle tracking** - insight into running experiments and exposing the work tracking for one experiment in Jira and experimenter logically https://jira.mozilla.com/browse/DS-1098

Use cases:
- If a product owner needs to know more about where experiments are in analysis for running or complete experiments - they could easily find with the DS Jira ticket.   Selena wants that ability as well - to find out where an experiment is in the progress to getting results.
- Shell frequently needs to go into the admin tool to find the DS Jira ticket associated with an experiment - since that is hidden once an experiment completes.  Use case - when we are using the same DS ticket for a set of experiments.
- We want to expose how the Jira and Experimenter views  are related.  In general we will be using DS Jira more (or a report generated from Jira - still TBD) to see experiments that are in design, the queue, or blocked from getting to be experiments.  This is to meet a need from Selena to know what is in the queue for the next 0-6 weeks.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-320)

**Comment by tiftran** [comment]
@shell1 doesn't the "Data Science Issue Ticket" button in the light blue bar acheive this? or am I missing some context and you're referring to something else?

**Comment by shell1** [comment]
@tiftran I have no idea how I missed every seeing that change.  Totally embarrassed.  That absolutely meets the needs.
