### ISSUE TITLE
Revert nvm in Dockerfile PR when upstream issue gets fixed

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#3502]
We can probably revert this whole #3489 PR when it gets fixed, maybe we'll give it a couple weeks.

_Originally posted by @jaredlockhart in https://github.com/mozilla/experimenter/pull/3489#discussion_r489795663_

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-321)
┆Issue Number: EXP-321

**Comment by jaredlockhart** [comment]
Thanks for filing @pdehaan !

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Discussion of a solution is at https://discuss.circleci.com/t/docker-build-fails-with-nonsensical-eperm-operation-not-permitted-copyfile/37364/13

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is no longer blocked.
