### ISSUE TITLE
Modify dependabot workflow to run CI on each pr before merge to dependencies

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3503]
So maybe we can find a middle ground between the large number of CI runs we had when we CI'ed every dependabot PR onto main, and the single CI run with the current workflow.   Looking at the last couple weeks, there's been multiple cases where individual dependency changes break some part of the build/tests and then chasing them down is very time consuming.  

So here's the workflow I propose

1) Dependabot is configured to create PRs against `dependencies` branch and automatically merge them if they're successful
2) Circle is configured to do a full build/integration run against each individual dependabot PR as they are created against the `dependencies` branch
3) There are no branch protections against `dependencies` branch, such as `PRs must be up to date` like we have on `main`, which means each individual PR can be merged without needing to rebase after another one merges
4) Dependabot PRs that break build/tests will get stuck as a PR and can be inspected individually and either closed or modified to pass individually
5) When all dependabot PRs (minus ones that get stuck and closed) are merged into `dependencies` a single PR can be manually created against `main`
6) The rest of the current flow remains the same

This will result in more CI runs than the current flow but less than the original flow, and should hopefully be smoother than the workflow we have now.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-322)
┆Issue Number: EXP-322

**Comment by jodyheavener** [comment]
> Circle is configured to do a full build/integration run against each individual dependabot PR as they are created against the dependencies branch

Maybe I'm misunderstanding - If Circle is running on each individual dependabot PR, doesn't this defeat the purpose of a dependencies branch? Why not PR against main in this case?
