### ISSUE TITLE
Remove unused setting:

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3521]
This isn't used anymore and can be removed:

https://github.com/mozilla/experimenter/blob/64479f626035be129d762ba7b31301e6d85c271f/app/experimenter/settings.py#L229-L231

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-336)
┆Issue Number: EXP-336

**Comment by richardgreg** [comment]
Hi @jaredlockhart. For this issue is it simply deleting those three lines?

**Comment by jaredlockhart** [comment]
@richardgreg yes exactly!

**Comment by satrio-hw** [comment]
are you working on this issue @richardgreg ? I could make a PR if it's still open to working on

**Comment by richardgreg** [comment]
@satrio-hw I have already submitted a PR and it has been merged.
