### ISSUE TITLE
Deprecate Rapid Prototype

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3528]
When Nimbus M1 is complete when can rip out the entire Rapid prototype.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-345)
┆Issue Number: EXP-345

**Comment by jaredlockhart** [comment]
Let's do this after we hit parity with all the new stuff so we don't disrupt the existing rapid prototype.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Moved this from M2 to Maintenance fix version.

When doing this, we can also rip out the `visualization` package that lives in `legacy-ui`.

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Closing as a duplicate of https://jira.mozilla.com/browse/EXP-687
