### ISSUE TITLE
I am getting this errror

### ISSUE THREAD

**Issue by Ritwik880** [mozilla/experimenter#3535]
Sorry, you do not have permission to access https://experimenter.services.mozilla.com

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-348)
┆Issue Number: EXP-348

**Comment by jaredlockhart** [comment]
@Ritwik880 Experimenter is an internal only service for Mozilla employees, is there something specific you are looking for that might be available on a publicly available service?
