### ISSUE TITLE
Add nimbus-ui dev server to docker-compose file

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3551]
We want to be able to spin up the nimbus-ui CRA dev server with everything else via `make up`. At the time of writing there's a WIP PR/branch here with more details: [https://github.com/mozilla/experimenter/pull/3547](https://github.com/mozilla/experimenter/pull/3547)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-354)
┆Issue Number: EXP-354

**Comment by jodyheavener** [comment]
I'll be adding this as part of #3429. If the existing open PR gets merged beforehand that's fine, but it'll otherwise be covered in an upcoming PR from me.
