### ISSUE TITLE
Initialize Visualization (Svelte), feed data into components

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3555]
We should have the visualization data from EXP-286. We need to initialize the Svelte component and feed it data per experiment where Svelte charts will be needed.

See how visualization was recently implemented for `rapid`: https://github.com/mozilla/experimenter/pull/3419/files (https://github.com/mozilla/experimenter/pull/3419/files#diff-c40f7fdaa13a0db9e38422101ec9986eR5-R9 and https://github.com/mozilla/experimenter/pull/3419/files#diff-fec63f36922df8ca330bb1346212b631R63 - can this be improved?)
At the time of writing (10/7), the visualization work has been done in React and not Svelte. We should be able to copy-and-paste the `visualization` package out of `static/visualization` and into `nimbus-ui/visualization` since it's very basic. We'll be able to remove the `legacy-ui/visualization` and `legacy-ui/rapid` packages shortly after.

Also see the ADR for more info: https://github.com/mozilla/experimenter/blob/main/app/experimenter/docs/adrs/0003-analysis-visualization-architecture-approach.md

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-357)
┆Issue Number: EXP-357

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Cancelling: per Marina, this isn't something we'll get to before early 2021.

**Comment by LZoog** [comment]
Closing, this was "cancelled" in Jira but didn't close in GH
