### ISSUE TITLE
Improve build speed with poetry export

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3577]
`poetry install` is noticeably slower than `pip install`, on my local machine for Experimenter it comes out to:

`poetry install`: 3m
`pip install`: 50s

So I as just reading through https://github.com/python-poetry/poetry/issues/338 and someone suggested doing

`poetry export -f requirements.txt --dev | pip install -r /dev/stdin`

See: https://github.com/python-poetry/poetry/issues/338#issuecomment-546813466

So let's do that until their new parallel installer:

https://github.com/python-poetry/poetry/pull/2595

is released.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-361)
┆Issue Number: EXP-361

**Comment by CircleOnCircles** [comment]
did you try the experimental parallel? https://github.com/python-poetry/poetry/pull/2595
