### ISSUE TITLE
Add channel icons to UI

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#359]
We should add little Nightly, Beta, and Release icons to anywhere we use the channel labels, so that it's easier to visually distinguish them.

**Comment by shell1** [comment]
we are closing out a bunch of these original "we could possible do x" UX enhancements.  Mid-year after 2 quarters of development - we will look at the UX and see all up what changes will be truly helpful to the users.  Don't want a bunch of ideas in the backlog that might get worked on individually - and conflict with more recent changes.
