### ISSUE TITLE
Update/merge Desktop/JS binding docs for tech review

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3619]
Existing docs updated, deprecated, linked and/or merged and ready for outside technical review of Desktop JS Bindings:

* UniFFI theory of operations doc
  * link to Travis’ vendoring doc
  * link/borrow pieces of Android api doc for observer bits
* ADR for UniFFI/Nimbus Firefox Desktop JS Bindings

The review and landings themselves will be tracked in other tickets, so some of the earlier comments here will be filed/tracked elsewhere..

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SDK-19)
┆Issue Number: SDK-19

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Leaving unassigned as this will be work done by an external team. Lina will keep track of this throughout the sprint.

**Comment by data-sync-user** [comment]
➤ Lina Cambridge commented:

The review packet so far:

  * An ADR for front-end bindings ( https://docs.google.com/document/d/1XVBvjt52EKgaaAflMDqUGXQy2AK3sufgEFIu1ZjWbqw ), via WebIDL, XPIDL, js-ctypes, or Wasm.
  * An ADR for C++ platform bindings ( https://docs.google.com/document/d/1kaVliEaNzhLthudBmWSJnmbyC70P0AQqNGE_4K0HYmI ).
  * A prototype for front-end ( https://github.com/mozilla/uniffi-rs/pull/255 ) bindings.

**Comment by data-sync-user** [comment]
➤ Nicholas Nethercote commented:

I've looked over the three parts of the review packet. Overall it looks good. The C++ proposal is straightforward. The JS proposal is still gnarly but that is unavoidable. I put some additional comments are in the Google Docs and the PR.

**Comment by data-sync-user** [comment]
➤ Lina Cambridge commented:

Thanks, @nnethercote! To close this issue out, I think we'll want to:

  * Update the ADR to reflect that we're going with Option C for now. We can always revisit later.
  * Bring #255 up to date with Nick's feedback, and get it reviewed and landed.
  * Convert the Google Doc ADRs to Markdown, and move them into this repo.

After that's done:

  * https://github.com/mozilla/application-services/issues/3571. Copy that ticket into a new Bugzilla bug and make a Phabricator patch to build the Rust Nimbus SDK and the generated bindings in Desktop. These can be Nightly-only to start with.
  * Figure out the testing story. Start with a Nimbus xpcshell test, and maybe build a more elaborate testing strategy for generated bindings later (mozilla/uniffi-rs#272).

**Comment by rfk** [comment]
This is still open in our Jira, so re-opening here.

**Comment by data-sync-user** [comment]
➤ Daniel Mosedale commented:

Here is the updated Theory of Operations doc, which I've sent out for review:

https://docs.google.com/document/d/1JnSruKgfKDcfIuiMirEIhum4NOWYlo58sCXPoxtC21g/edit#heading=h.gug06n5739a

**Comment by data-sync-user** [comment]
➤ Daniel Mosedale commented:

Updated version of the ADR doc is at

https://docs.google.com/document/d/1wIb2ZOXn2RI75-GvicuuYbsYS-nqBAqMJxmVaePE3Wg/edit?usp=sharing ( https://docs.google.com/document/d/1wIb2ZOXn2RI75-GvicuuYbsYS-nqBAqMJxmVaePE3Wg/edit?usp=sharing )

The main changes here are just that I've incorporate a bunch of useful comments on the original doc from suggestions into the doc itself.

**Comment by data-sync-user** [comment]
➤ Daniel Mosedale commented:

Because the changes to the ADR doc weren't substantive, I don't think getting further review on it at this is likely to be very useful.
