### ISSUE TITLE
Use separate build and deploy Docker images

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3634]
To speed up and improve the consistency of our deploys, we should separate our Docker image into two stages, one for build and one for deploy.  The current image is 1gb, and 821mb of that is `node_modules` so if we just nuke that in the deploy image we should be able to bring it way down.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-435)
┆Issue Number: EXP-435

**Comment by jaredlockhart** [comment]
Example from GLAM: https://github.com/mozilla/glam/blob/main/Dockerfile
