### ISSUE TITLE
Add Changelogs to NimbusExperiment

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3639]
We need to attach Changelogs to NimbusExperiment to track changes, dates, users, etc.

We'll need to add a second foreign key on Changelog to NimbusExperiment, and make sure all the utility functions accept NimbusExperiment correctly.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-438)
┆Issue Number: EXP-438

**Comment by jaredlockhart** [comment]
Eh looking at it more let's just make a new ChangeLog model for NimbusExperiments so we don't tightly couple ourselves to the legacy implementation.
