### ISSUE TITLE
Mutation to update a branch

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3644]
A branch should be able to be updated, the control boolean should not be able to be changed.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-442)
┆Issue Number: EXP-442

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

This is no longer needed as 3643 can update or add branches.

**Comment by LZoog** [comment]
Closing, this was already implemented
