### ISSUE TITLE
Add version.json to deploy container

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3673]
Oops forgot to add `version.json` to the deploy container

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-450)
┆Issue Number: EXP-450

**Comment by jaredlockhart** [comment]
Fixed on the ops side: https://github.com/mozilla-services/cloudops-infra-deploylib/blob/master/deploylib/docker.py#L247
