### ISSUE TITLE
`PageNew` modifications - back links, add "Application" field, finish styles

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3696]
Figma: https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/Nimbus-Console-UI?node-id=216066%3A11123

On `PageExperimentNew`: 
1) Add the “X” button and cancel buttons, both of which should be links taking the user from `/nimbus/new/` back to `/nimbus/ (the directory view)
2) Add the “Application” drop-down field which roughly maps to [https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/models/nimbus.py#L48](https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/models/nimbus.py#L48). This is not currently in the Experimenter platform (`rapid` or `core`) in the front-end but was implemented in the BE in https://github.com/mozilla/experimenter/commit/cdf90494a7861d72ef400121e7281e2b8b2d4479.
3) Make any other text or styling adjustments to closely resemble the Figma comp

Note: much of this was already completed in another ticket so it's been reduced from a 5 to a 3.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-462)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/14367/screenshot-1.png">screenshot-1.png</a> | <a href="https://jira.mozilla.com/secure/attachment/14420/Screen+Shot+2020-10-29+at+5.55.59+PM.png">Screen Shot 2020-10-29 at 5.55.59 PM.png</a>
┆Issue Number: EXP-462

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

We need to make sure that field specific errors are reflected on the form.  For instance here, `application` has an invalid value, but the application field is green/valid:

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

We also need to make sure the drop-down is populated with label values that should come from the `useConfig` hook. Attached a screenshot of what this looks like in the `rapid` project.  !screenshot-1.png|thumbnail!

**Comment by jodyheavener** [comment]
> We need to make sure that field specific errors are reflected on the form.  For instance here, application has an invalid value, but the application field is green/valid

Just drive-by commenting here... since the `application` dropdown values are now loaded via the GQL config an incorrect value _shouldn't_ be possible. That being said, once [EXP-530](https://jira.mozilla.com/browse/EXP-530) is in the errors should show up on each field correctly. However, any selection in the dropdown will initially show the green checkmark.
