### ISSUE TITLE
Frontend builds invalidating docker cache

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3707]
Something is changing in the frontend builds that is invalidating the docker cache which causes it to rebuild frontend assets everytime the containers start, which is affecting local dev and CI.  The simplest approach I've learned to manage this is disable all gitignores, re run all the docker commands, and git will expose what paths have changed.  It's probably a cache path getting dumped back to the host filesystem we just have to add a callout for in the compose files.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-472)
┆Issue Number: EXP-472

**Comment by jaredlockhart** [comment]
Ah found it, it's parcel randomly generating a websocket port:

-  var ws = new WebSocket(protocol + '://' + hostname + ':' + "39389" + '/');
+  var ws = new WebSocket(protocol + '://' + hostname + ':' + "33291" + '/');
