### ISSUE TITLE
`PageEditBranches` copy and "meatball" dropdown

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3742]
1) Make sure the copy matches Figma
2) Replace “X” delete functionality with a "meatball" drop-down for
2a) deleting (existing functionality) and
2b) duplicating (new functionality)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-482)
┆Issue Number: EXP-482

**Comment by pdehaan** [comment]
Ah, I came here to file this issue, but for my own future reference, here's a shot of the current UI vs the Figma spec:

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/100792508-95d5dd80-33cf-11eb-986f-2949435dbd9e.png)

<img width="1047" alt="Nimbus_Console_UI_–_Figma" src="https://user-images.githubusercontent.com/557895/100792608-bb62e700-33cf-11eb-8842-8c90ab9aa192.png">

**Comment by lmorchard** [comment]
Looks like this issue is "Cancelled" in jira but still open here - I seem to remember we punted implementing this in a meeting many weeks ago
