### ISSUE TITLE
Extend Apollo cache "experiment edits" to handle multiple experiments

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3755]
EXP-297 sets us up to manage the "edited" state of an experiment.

However, if a user makes edits on Experiment A without saving and then navigates to a different experiment, Experiment B, we don't want edits from Experiment A to show in Experiment B. Ideally if the user saves edits in Experiment B and navigates back to Experiment A, we could keep those unsaved edits around.

At the time of writing, EXP-297 is still WIP but if that’s called something like `experimentEdits`, then this can be changed from...

```
experimentEdits: {
  // modified/updated fields and values are set here onchange
}
```

... to an array of objects with the slug for identifying that page:
```
localExperiment: [{
  slug: "my-special-slug",
  editedFields: {
    // modified/updated fields and values are set here onchange
  }
}]
```

Different names can certainly be used, but keep in mind we'll be extending this objects in this array further in EXP-491.

1) The cache should be reconfigured to the shape shown above. The previous object (`experimentEdits`?) will be moved inside the new object. It should be initialized as an empty array.
 2) Whenever a user hits any `nimbus/:slug:/edit/*` page (`PageEditOverview`, `PageEditBranches`, `PageEditMetrics`, or `PageEditAudience`), if an object in the `localExperiment` array containing that slug does not already exist, write one to the cache with the slug from params; we probably need a hook or helper function since we'll be using this repeatedly across "edit" pages.
 3) The hook created in EXP-297 will need to be updated so that when modifying or reading from the cache, the correct object is modified. Find the correct object to update by slug.
4) Create a similar client resolver/hook as made in EXP-297 to allow updates to `slug` (which will be used on a slug name update in EXP-463).
5) Doc updates? :grinning:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-494)
┆Issue Number: EXP-494

**Comment by LZoog** [comment]
Closing this, we went with a different approach.
