### ISSUE TITLE
Add pref name auto completion

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#376]
We should helpfully auto complete pref names, we can populate it from here:

https://searchfox.org/mozilla-central/source/browser/app/profile/firefox.js

It should only be a helpful suggestion, there will still be prefs that aren't found in there so we should still only loosely validate.

**Comment by leplatrem** [comment]
There is this list as well: https://searchfox.org/mozilla-central/source/modules/libpref/init/all.js

**Comment by jaredlockhart** [comment]
Never really became useful/necessary.
