### ISSUE TITLE
Bump python to 3.9

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3761]
We should bump up the python version in pyproject.toml to 3.9:

[https://github.com/mozilla/experimenter/blob/main/app/pyproject.toml#L8](https://github.com/mozilla/experimenter/blob/main/app/pyproject.toml#L8)

and in the docker container here:

[https://github.com/mozilla/experimenter/blob/main/app/Dockerfile#L2](https://github.com/mozilla/experimenter/blob/main/app/Dockerfile#L2)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-500)
┆Issue Number: EXP-500

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/pull/3763
