### ISSUE TITLE
Add minimum test coverage requirement in Nimbus + meet coverage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3808]
We have been pretty diligent on our tests but CI doesn't prevent merging if we're not at a certain threshold.

The `rapid` project has line coverage and nothing more:
```
  coverageThreshold: {
    global: {
      lines: 100,
    },
  },
```

Is this what we want for Nimbus?

Also, do we want to collect coverage on our mocks and testing utilities (which at the moment holds a Storybook helper, hence the uncovered lines in test)?

![image](https://user-images.githubusercontent.com/13018240/97016427-54215f80-1512-11eb-96fa-207551c4bf4a.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-516)
┆Issue Number: EXP-516

**Comment by LZoog** [comment]
General consensus is to cover only the lines to 100% (not branches etc.) and to go ahead and ignore `test-utils.tsx` and `mocks.tsx`.

This will require testing the line in `useExitWarning` since there's one uncovered line.
