### ISSUE TITLE
Experiment `application` GQL inconsistency

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3826]
Creating a new Experiment requires the `application` value in the mutation to be lowercase (e.g. `fenix`), but the returned enum (`NimbusExperimentApplication`) for this property in a query is always uppercase (e.g. `FENIX`). So unless one is transformed along the way they can’t be compared.

Not a huge deal, but it would be nice to make these consistent.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-519)
┆Issue Number: EXP-519

**Comment by jodyheavener** [comment]
This appears to be fixed now.
