### ISSUE TITLE
Can we add the new experiment types to avocado?

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#3828]
http://storage.googleapis.com/avocado-dev/index.html

avocado pulls info from experimenter on time spent in stages.  This is used when reporting to leadership on experiment progress.

right now the only types are add-on and pref-flips.  I'd like to know the timing on message router, rollouts, and rapid experiments.

ideally it would allow me to select multiple types

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-520)
┆Issue Number: EXP-520

**Comment by tiftran** [comment]
changes made in https://github.com/mozilla/avocado/pull/62
