### ISSUE TITLE
GraphQL response "message" no longer returns object

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3850]
It was noted that the Nimbus frontend no longer correctly displays validation errors. Further investigation revealed that the GraphQL (API v5) response object's "message" property no longer returns an object of errors, where the key is the field and the value is an array of error strings.

Expected: `{ [fieldKey: string]: string[ ] }[]`

Actual: string

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-530)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/14501/Capture.PNG">Capture.PNG</a> | <a href="https://jira.mozilla.com/secure/attachment/14364/Screen+Shot+2020-10-29+at+6.51.46+PM.png">Screen Shot 2020-10-29 at 6.51.46 PM.png</a>
┆Issue Number: EXP-530

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

[~jkerim@mozilla.com] or [~bbangert@mozilla.com] can I give this to either of you for next sprint?

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Hmm. The message is returning a schema like `{ [fieldKey: string]: string}` for an error like a name without alphanumeric characters. This seems triggered by bad values for the application field. Will need to work out why these two fields are different in error reporting

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Oh, I think I see the problem: There are two different kinds of errors happening here.

When the field has invalid characters and it's caught by Django serializer validation, that's a 200 OK JSON response with per-field errors under `data.createExperiment.message`

When the field fails GQL-level type validation - as in the case of an invalid enum value submitted for application - that's a 400 Bad Request with an entirely different `errors` response schema detailing problems in the GQL query itself.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Tempted to wave the WONTFIX flag on this one.

Turns out that the Nimbus front-end does display _per-field_ validations from the back-end, provided that the overall GQL mutation is otherwise valid.

But, if the GQL mutation fails validation due to a type mismatch, the Graphene back-end calls the whole request bad. There's no easily parsed per-field information to bubble up to the user.

That said, the user shouldn't be able to cause that kind of error via the UI - because we should be populating things like select fields with the proper enum choices and performing basic client-side validation.

So, IMO, a validation failure at the GQL level should be considered a bug in the UI and not a user-actionable problem.

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

[~lorchard@mozilla.com] That sounds reasonable to me, the reason we hit this in the first place was becuase we changed the server schema without updating the client but now we have a solid `make check` check for that so in theory we shoudln't be able to land the repo in that state again, so I'm fine with wontfixing this and if we wind up in a similar situation again it's about making sure the server/client contract is well enforced and not a ui error handling change.

**Comment by lmorchard** [comment]
Going to close this - I think we worked things out here
