### ISSUE TITLE
nimbus-ui PageNew storybook story displays an error

### ISSUE THREAD

**Issue by lmorchard** [mozilla/experimenter#3893]
Looks like [the recent update to send overview mutation when form submitted](https://github.com/mozilla/experimenter/pull/3843) may have broken the PageNew story:

* Before: https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/265a366028dce040318162dd5fa0459c45e41e69/nimbus-ui/index.html?path=/story/pages-new--basic

* After: https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/5797b0f1eaeb53adb68951e40cf0f2715cc0fe8f/nimbus-ui/index.html?path=/story/pages-new--basic

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-549)
┆Issue Number: EXP-549

**Comment by LZoog** [comment]
Oh hey, I was about to put a quick fix up for this and now it has an associated issue! I'll assign to myself

**Comment by lmorchard** [comment]
I don't think this is actually fixed yet

**Comment by lmorchard** [comment]
Wait nevermind me, follow up over here https://github.com/mozilla/experimenter/issues/3896
