### ISSUE TITLE
Display only valid "feature config" options in UI based on application

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3918]
The valid pairings of feature configurations based on experiment application will be provided in the server configuration passed down to the client.

On the Branches page in the UI, filter through the options from the config to only display valid "channel" options in the drop-down displayed to the user after they click the "+ feature configuration" button.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-560)
┆Issue Number: EXP-560

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Re-opening as this was reverted in https://github.com/mozilla/experimenter/pull/4255

**Comment by pdehaan** [comment]
@jodyheavener Do we want to keep this issue open? I see we reopened it ~2hrs ago but I think the recent commit auto-closed it in GitHub.

**Comment by jodyheavener** [comment]
Darn commit titles!

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Completed in EXP-952
