### ISSUE TITLE
`make test` step in README is no longer a task in the Makefile

### ISSUE THREAD

**Issue by lmorchard** [mozilla/experimenter#3937]
Was trying a reinstall from scratch. The README advises:
```
Run tests

make test
```
But, this happens:
```
➜  experimenter git:(main) ✗ make test
make: *** No rule to make target 'test'.  Stop.
```
Looks like it was removed here: https://github.com/mozilla/experimenter/commit/9336d4faf89f6e723c4ab4cd32bbdf92f176c9a8

Should update the docs to reflect what the new step should be. (i.e. `make check`? or is that too heavy?)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-565)
┆Issue Number: EXP-565

**Comment by jodyheavener** [comment]
Fixed in #4534
