### ISSUE TITLE
Add QA collection and status and celery tasks

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3947]
To facilitate QAing Nimbus experiments, let's add a special remote settings collection called `nimbus-qa` that requires no dual sign off, an experiment status called `QA`, and a celery task that checks for experiments in QA status and pushes them to the collection, and experiments in the collection that aren't in QA status and removes them.

Note: One thing I realized is in theory you can 'Launch to Preview' and 'Go back to draft' back and forth instantly and endlessly so we'll have to make sure we account for that in the RS sync mechanism so we don't accidentally get the backend stuck in some weird state

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-567)
┆Issue Number: EXP-567

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Do we want to add a PREVIEW_PENDING state or `isPreviewRequested` boolean to finesse the visible state reported in the UI?

I'm scratching my head at EXP-887. First obvious thing is to add a `NimbusConstants.Status.PREVIEW` status. The front-end can set that via the update mutation. Then, the Celery task can scan for experiments in PREVIEW status but not yet present in the QA kinto collection and execute the push.

However, this affords no pending state in the interim between requesting preview push and the celery task run. So, there would be a time span when the experimenter clicks the button, sees the UI report it live in Preview, yet nothing has updated in Kinto.

Maybe this isn't as important as the REVIEW > ACCEPTED transition  because that has a manual approval step in the middle that could be a relatively long time in resolution. The pending preview state would ideally only last as long as the delay between database update and the next celery beat (every 10 minutes?). 

Still, this might be at least a paper-cut of an issue.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Similarly, do we want a DRAFT_PENDING state to reflect the 'Go back to draft' from Preview transition? That would lock editing until "ownership" has truly been handed back to Experimenter from Kinto

**Comment by jaredlockhart** [comment]
@lmorchard Yeah exactly those are both astute observations.  I *think* it's probably safe to not do that and see if it becomes a critical workflow blocker and then tack it on later, but I don't think it's a blocker to actually implementing the mechanism.  You can't even build the publishing workflow without those states because of the manual review step, but here it's just a UI optimization so I'd hazard we wait to see if we need it.

**Comment by jaredlockhart** [comment]
@lmorchard oh the other thing is we can trigger the task immediately when the ui trigger happens in addition to the schedule to remove that delay.
