### ISSUE TITLE
Inconsistency in GQL input types for experiment ID

### ISSUE THREAD

**Issue by lmorchard** [mozilla/experimenter#3954]
Not sure if this is a big deal, but: While working on hooking up further GQL mutations in the front-end, I noticed an inconsistency in specifying experiment ID.

* For `UpdateExperimentInput` type, it's a `graphene.ID` type named `id`.
* But, for `UpdateExperimentStatusInput`, it's a `graphene.Int` type named `nimbus_experiment_id`

Looks like most other inputs follow the latter pattern. But maybe they should be using `graphene.ID`?

This also translates to string / number and naming inconsistencies in the generated Typescript types.

https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/api/v5/inputs.py#L26-L27
```python
class UpdateExperimentInput(ExperimentInput):
    id = graphene.ID(required=True)
```

https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/api/v5/inputs.py#L94-L97

```python
class UpdateExperimentStatusInput(graphene.InputObjectType):
    client_mutation_id = graphene.String()
    nimbus_experiment_id = graphene.Int(required=True)
    status = NimbusExperimentStatus(required=True)
```

https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/types/globalTypes.ts#L82-L95
```typescript
export interface UpdateExperimentInput {
  clientMutationId?: string | null;
  name?: string | null;
  application?: NimbusExperimentApplication | null;
  publicDescription?: string | null;
  hypothesis?: string | null;
  id: string;
}

export interface UpdateExperimentStatusInput {
  clientMutationId?: string | null;
  nimbusExperimentId: number;
  status: NimbusExperimentStatus;
}
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-570)
┆Issue Number: EXP-570

**Comment by lmorchard** [comment]
Oh, and this is also a type inconsistency with a fetched experiment - need to do a `parseInt(experiment.id)` to use the fetched experiment's ID.

https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/types/getExperiment.ts#L59-L61
```
export interface getExperiment_experimentBySlug {
  __typename: "NimbusExperimentType";
  id: string;
```

**Comment by bbangert** [comment]
Agreed, the experiment ID should always be a `graphene.Int`, unless we modify the ID to be a GraphQL object identifier.
Per https://graphql.org/learn/global-object-identification/

A GraphQL ID is intended to be globally unique, which means we can't just use the Nimbus experiment ID, since that isn't unique from any other db id. It would need to be prefixed with the table name or something to ensure its globally unique to use this correctly.

**Comment by lmorchard** [comment]
So, then it sounds like the work here would be to:
1. In the API, switch use of `id = graphene.ID` in experiment queries & mutations over to `nimbus_experiment_id = graphene.Int`
1. Then, follow up with changes to the front-end as necessary.

**Comment by lmorchard** [comment]
Also noticed this issue around `featureConfig` ID:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/types/getConfig.ts#L24-L26
```typescript
export interface getConfig_nimbusConfig_featureConfig {
  __typename: "NimbusFeatureConfigType";
  id: string;
```

https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/api/v5/inputs.py#L53
```python
class UpdateExperimentBranchesInput(graphene.InputObjectType):
    client_mutation_id = graphene.String()
    nimbus_experiment_id = graphene.Int(required=True)
    feature_config_id = graphene.Int()
```

**Comment by lmorchard** [comment]
Thinking about this some more, I'm not sure that we want to switch away from `graphene.ID`? That would be pretty extensive change from what it looks like the framework does auto-magically. Seems like most of these types just auto-map database ID as GQL ID

https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/api/v5/types.py

**Comment by jaredlockhart** [comment]
Oh I was just poking around at this while working on the graphql, we can definitely use graphene.Int everywhere for ids and then get rid of a ton of parseInts everywhere in the frontend.
