### ISSUE TITLE
Add hypothesis default to create form

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3963]
We need to add the hypothesis default guidance text to the create form.  This text is defined as a constant in the backend, so we should add it to the config query so the frontend can render it, and validate on the backend that the user modified it from the default.  I noticed that validation errors from the server weren't triggering the form to be marked as invalid, so we should do that as well so if the server fails validation the form is marked as invalid.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-577)
┆Issue Number: EXP-577

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/pull/3964
