### ISSUE TITLE
Can't update Nimbus Experiment from admin when selected feature config has empty schema

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3965]
... I think I got that description right?

If you try to update an Experiment at **/admin/experiments/nimbusexperiment/:id/change/** and its selected feature config has a schema with an empty value the page borks.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-578)
┆Issue Number: EXP-578

**Comment by jaredlockhart** [comment]
Oh no it's not the serializers, it's the admin form here:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/admin/nimbus.py#L28-L30

Just gotta

`        if feature_value and feature_config and feature_config.schema:`

**Comment by jaredlockhart** [comment]
Oh what you're describing @lmorchard is something different.  The mutations run through the V5 serializers and yes your approach is correct although i'd demorgan that into 

```py
if not (self.instance and feature_config and feaure_config.schema) 
```

but yes.  That should probably be a separate ticket with a test.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I think I fixed this as part of another issue here:

https://github.com/mozilla/experimenter/pull/4390/commits/9ffe421d0adca2182ea6da5cc074e9b52c903468#diff-ef293ebe07a98d7f8810e1114712d868a25ae39f66ade8308dbe4fcf3d4c003fR28-R35

But also, we're got a PR to remove admin validation altogether, here:

https://github.com/mozilla/experimenter/pull/4408
