### ISSUE TITLE
(visualization) Copy overview table from `rapid` into TableOverview component

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3976]
EXP-461 creates a placeholder for the `TableOverview` component which is displayed on the Results page. Copy over this table from the `rapid` project into this component and add it and its various states into Storybook. Note that the experiment data structure differs slightly between the projects.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-585)
┆Issue Number: EXP-585

**Comment by LordReigns** [comment]
Is it possible for me to work on this?

**Comment by emtwo** [comment]
> Is it possible for me to work on this?

Hi @LordReigns! Thanks for your interest in the project! This particular ticket has an upcoming target deadline, but we may have other interesting tasks for you to work on if you'd like! If so, we can get back to you soon with a short list :) Cheers!
