### ISSUE TITLE
Publishing to RS not working in stage/prod?

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#4006]
As of this morning Andrei and I tried publishing a couple of experiments to staging (https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/do-not-delete-about-welcome-reference-test) and prod (https://experimenter.services.mozilla.com/experiments/nimbus/homepage-remediation-exposure-nightly-test). They seem to be stuck in `Review` status and never make it to`Accepted`.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-600)
┆Issue Number: EXP-600

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Not sure this is fully implemented yet?

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Dropped from our fix version. [~khudson@mozilla.com] will be dropping a comment and closing this as no longer reproducible.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Per [~khudson@mozilla.com] in Slack, this is not an issue. Cancelling.

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

This was fixed by EXP-605
