### ISSUE TITLE
Are we going to backfill shield studies or experiments from the last two years?

### ISSUE THREAD

**Issue by rkothari19** [mozilla/experimenter#401]
I see shield studies, experiments from a selective set of teams in the experimenter dashboard right now. Are we going to backfill data from last two years here?

**Comment by jaredkerim** [comment]
I wasn't planning on going as far back as two years, I did many of the experiments in the last six months.  Right now not all past Shield studies fit into Experimenter (lack of addon studies, multipref) so we can't backfill them.  But when those features are added we can look back at other past studies and start backfilling more aggressively.  

If there are any recent studies that are pref flip with exactly two branches that are missing, add links to the bugzilla tickets here and I will add them!

**Comment by jaredkerim** [comment]
@shell1 Any thoughts on this?

**Comment by shell1** [comment]
hmm...now that I think about this - I'll add the studies that are live now.  It will be a little mocked up - since the sign-offs are in bugs and not Experimenter - but likely better to pull random information on what is running together in one place.  right now we have details in a spreadsheet of what is still running :).    I will close out once done.

We will not go backwards in history of experiments, unless there is a request to add a specific study.  At that point - it would be the team doing the work - and Normandy / Experimenter team would just change the flag to "completed".  The only justification is once the data can be attached and searched easily from Experimenter - creating an experimenter study to hang data off.  Since that ability is a bit out still -there is no reason to do this for historical studies.

**Comment by shell1** [comment]
Emailed Jared to verify I haven't forgotten anything when I create Experimenter projects for the "on-going" studies that started through the old process.  This will make Experimenter the source to run all the Normandy worklists and for Release Management to see everything live. 

Just verifying that only things I'll need to fix are: 

1. closing out the Experimenter created Experimenter bugzilla tickets - and calling out that there is a different REAL - existing SHIELD bug for these experiments.
2. asking Jared to move these to Live once they are created and running.  That way they will get into our tracking flow.

note for Shell - these are the ones I'll be creating:
WebRender: https://trello.com/c/KwiHLnWg
Cert Error Pages: https://trello.com/c/At9TbZ5L
Cookie Restrictions: https://trello.com/c/yNm6xgCj
Pocket Spocs Optimization: https://trello.com/c/8AcnPKm1
Pocket Spocs Holdback: https://trello.com/c/zSthhiB9
PUSH performance: https://trello.com/c/Lzpavk9s - UNCLEAR if this is still running.  will need to check.  based on card it should be off - but it's still in the SHIELD slide.

**Comment by shell1** [comment]
The links to experimenter studies below are all the ones that can be marked "Live".  Their SHIELD ticket - should now be their Experimenter bugzilla tickets.  These are in the first line of the Description of each experiment. 

1. https://experimenter.services.mozilla.com/experiments/webrender/ WebRender: https://trello.com/c/KwiHLnWg 
2.     https://experimenter.services.mozilla.com/experiments/cert-error-pages/ Cert Error Pages: https://trello.com/c/At9TbZ5L
3.     https://experimenter.services.mozilla.com/experiments/cookie-restrictions-on/ Cookie Restrictions: https://trello.com/c/yNm6xgCj
4.     https://experimenter.services.mozilla.com/experiments/pocket-spocs-optimization-test/ Pocket Spocs Optimization: https://trello.com/c/8AcnPKm1
5.     https://experimenter.services.mozilla.com/experiments/pocket-spocs-holdback/ Pocket Spocs Holdback: https://trello.com/c/zSthhiB9
6.     https://experimenter.services.mozilla.com/experiments/push-performance-study/ PUSH performance: https://trello.com/c/Lzpavk9s

**Comment by shell1** [comment]
awesome.  All live studies are now in experimenter.  

https://experimenter.services.mozilla.com/?ordering=-latest_change&type=&status=Live&firefox_channel=&firefox_version=&project=&owner=
