### ISSUE TITLE
Summary table has "Hypothesis" th in double-bold

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4015]
... but _ONLY_ the Hypothesis `<th>`, none of the others.

https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/sdfsdfsdf/request-review

https://github.com/mozilla/experimenter/blob/e88024a8ad395a222cb3aa2a98440ccdbb1c54c8/app/experimenter/nimbus-ui/src/components/TableSummary/index.tsx#L28-L30

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99454181-e979fe80-28da-11eb-8466-a54f89dcb822.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-608)
┆Issue Number: EXP-608

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Hopefully just a class name gone awry

**Comment by pdehaan** [comment]
> Hopefully just a class name gone awry

I think we can just remove the extra `<b>` wrapper tag. I can PR this shortly (unless somebody else is actively working on those files and it'll cause a conflict).
But it's a low priority paper cut.
