### ISSUE TITLE
Hypothesis text strips newlines in the Summary view

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4017]
https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/lorem-ipsum-hypothesis-test/edit/overview looks like this:

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99455155-4de98d80-28dc-11eb-8277-6dc5654462a7.png)

But by the time I get to the https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/lorem-ipsum-hypothesis-test/request-review page, the newlines are gone and its One Great Paragraph:

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99455263-796c7800-28dc-11eb-87ca-60590d19dd73.png)

Pretty sure the Hypothesis is internal only, so this isn't user facing, but the lack of formatting makes it difficult to review.

I also almost expected it to auto-link the hyperlink in the overview, but that's probably outside the scope of this newline discussion so I can file that shortly.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-609)
┆Issue Number: EXP-609

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Similar to EXP-610, this could be done on the back or front end
