### ISSUE TITLE
Auto link URLs in Hypothesis text in summary

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4018]
If you have a detailed hypothesis with various links to UI specs or tech docs or whimsical GIFs, the text appears as plain text (with linebreaks removed, see #4017), meaning you need to scan the text, manually copy links (like a chump) and then open a new tab, paste the text link to see the content.

There should be several npm modules which auto-link text ([**linkify-urls**](https://www.npmjs.com/package/linkify-urls) or [**linkify-it**](https://www.npmjs.com/package/linkify-it) or probably dozens of others), and I'm sure PyPI has some too, depending on where the logic would need to be injected (but probably best to do it at render time vs preprocessing).

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99455925-64dcaf80-28dd-11eb-9dc1-f5374fdbed53.png)
Ref: https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/lorem-ipsum-hypothesis-test/request-review

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-610)
┆Issue Number: EXP-610

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Decide if we want to do this, and then whether it's better done on the backend or just in frontend client
