### ISSUE TITLE
Experiment owner not getting set when creating new experiment

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4019]
I just created https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/peter-test-1000/request-review earlier today, but it tells me that the **Experiment Owner** is not set, which means that when I go to https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/ I can't see any of the experiments I've previously created.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-611)
┆Issue Number: EXP-611

**Comment by pdehaan** [comment]
![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99460213-504fe580-28e4-11eb-9950-4ffed1a4cf6e.png)

Actually, it looks like that mock experiment is "waiting for review". Should it have been able to be submitted without:

1. An experiment owner?
1. Any primary or secondary probe sets?
1. A target audience/channel/version?

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Maybe not implemented yet? I thought I saw server-side code that set the owner from current auth'd user.

**Comment by pdehaan** [comment]
Not sure if this is the best way to confirm this, but I did a bit of stubling around with graphiql and almost all (except 4?) experiments had an `owner: null`

https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v5/graphql#query=%7B%0A%20%20experiments%20%7B%0A%20%20%20%20name%0A%20%20%20%20owner%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20slug%0A%20%20%20%20status%0A%20%20%20%20publicDescription%0A%20%20%20%20startDate%0A%20%20%20%20endDate%0A%20%20%7D%0A%7D%0A

Curious if the ones that ARE setting the `owner` are creating the experiments directly in the django admin, or if there is some other hiccup somewhere.

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

This does seem like a real bug – since it isn't included in the recipe synced to remote settings I don't think this is technically release-blocking.

[~jkerim@mozilla.com] can you confirm

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Confirmed, owner is not set

**Comment by pdehaan** [comment]
On the Review & Launch page it shows as an error saying "Owner not set", so I guess as long as there is no validation happening on that page that enforces an experiment is valid before sending it to review then it wouldn't be a release blocker (just a deep papercut).

But I think per https://github.com/mozilla/experimenter/issues/4100, I was able to get an invalid experiment into an "in review" state, so I'm guessing we don't have any experiment validation yet on the review page.

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

[~jkerim@mozilla.com]  – I meant, can you confirm that it's not going to break anything related to publishing (will it mess up changelogs or something?) Is it just a bug that essentially shows up in the UI?
