### ISSUE TITLE
Add explicit review sign off states

### ISSUE THREAD

**Issue by rkothari19** [mozilla/experimenter#402]
Instead of just indicating that QA has signed off, can we add the date when the sign off was done? This is good metadata for relman team when reviewing study readiness.

**Comment by jaredkerim** [comment]
@rkothari19 I am going to add explicit sign off buttons for each kind of sign off, and that will show in the history as 

<date>
someperson@mozilla.com QA Sign Off

**Comment by jaredkerim** [comment]
Here is the current list of PHD review sign offs:

Science Review
Firefox Peer Review
Legal Review
UX Review
QA Review
Security Review
Relman Review
ITS
