### ISSUE TITLE
Potentially confusing nimbus primary button colors

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4020]
Step 1: https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/new

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99460684-26e38980-28e5-11eb-84fb-4df8f42b2651.png)
**Figure 1:** Primary action ("Create experiment") is blue, secondary action ("Cancel") is light gray.

---

Step 2: https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/button-color-check/edit/overview

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99460787-58f4eb80-28e5-11eb-8bd3-dd6d0bf9fd04.png)
**Figure 2:** Here, I'd argue that "Next" is the primary action (and saving is implied if changes were made) but the primary button is a darker gray, and the secondary action ("Save") is blue.

---

Step 3: https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/button-color-check/edit/branches

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99460875-880b5d00-28e5-11eb-8b0a-5bd5d5317737.png)
**Figure 3:** Mostly consistent w/ Step 2, although the "Save" button looks to be a lighter blue than used previously. (EDIT: Oh, it's because the button is seemingly `disabled` until I add descriptions).

---

Step X: https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/button-color-check/request-review

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99462490-a58df600-28e8-11eb-9ca2-f12ebaf75c6a.png)
**Figure 4:** Disabled "Launch" button (because checkboxes unchecked).

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99462506-ac1c6d80-28e8-11eb-90d0-012fd3edf1d6.png)
**Figure 5:** Enabled "Launch" button.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-612)
┆Issue Number: EXP-612

**Comment by lmorchard** [comment]
> Figure 2: Here, I'd argue that "Next" is the primary action (and saving is implied if changes were made) 

Saving is actually *not* implemented when "Next" is clicked. There should be a warning on an attempt to leave without saving, but I think that's broken right now - [we have an issue open to fix it](https://github.com/mozilla/experimenter/issues/3885) but .

> Figure 3: Mostly consistent w/ Step 2, although the "Save" button looks to be a lighter blue than used previously

Yeah, save is disabled here until the data is valid enough to submit. (e.g. Ratio must be a number before we can submit the changes)

> Figure 5: Enabled "Launch" button.

Probably makes sense to switch Launch to a primary button style

**Comment by pdehaan** [comment]
> > Figure 3: Mostly consistent w/ Step 2, although the "Save" button looks to be a lighter blue than used previously
> 
> Yeah, save is disabled here until the data is valid enough to submit. (e.g. Ratio must be a number before we can submit the changes)

That's interesting.
The form apparently isn't in a valid state whether I toggle the "Users should be split evenly between all branches" checkbox or not. The only way to apparently get the form into a valid saveable state is to add at least one branch, then fill in the description field for each branch created.

**Comment by pdehaan** [comment]
> Saving is actually _not_ implemented when "Next" is clicked. There should be a warning on an attempt to leave without saving, but I think that's broken right now - [we have an issue open to fix it](https://github.com/mozilla/experimenter/issues/3885) but .

I imagine this will cause a lot of frustration if users are expected to hit Save then Next on each page. (Considering I'm just now realizing I've probably edited lots of dummy experiments and not hit "Save" then "Next" and lost untold "qwerty" changes due to me [ignorantly] expecting a "Next" flow to save any changes before proceeding.)

I believe the original Experimenter ["Create Delivery" flow](https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/new/) had "Save Draft" and "Save Draft and Continue" buttons:

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99561653-0c102400-297c-11eb-942f-afa7eec60f41.png)
**Figure 6:** "Save Draft" vs "Save Draft and Continue" buttons to save-and-stay vs save-and-next.

---

And the Experimenter ["Create Rapid Experiment" flow](https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/rapid/new/) had a single "Save" button:

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99561932-5d201800-297c-11eb-8111-370199aec3e5.png)
**Figure 7:** Single "Save" button.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Depending on what we decide for the button color UX, implementation is probably just swapping some class names around
