### ISSUE TITLE
Nimbus Public name field doesnt validate on blur (create pattern for server-side validation clearing onblur)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4021]
https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/aaab/edit/overview

If I set the experiment name to "aaa", i get a validation error saying "Nimbus Experiment with this name already exists". If I change the experiment name to "aaab" and tab or focus out of that field, the error message persists, despite the name now being valid. It appears validation only happens again if I click "Save" or "Next" buttons.

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99468385-4f737f80-28f5-11eb-8639-fa07a1f1c257.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-614)
┆Issue Number: EXP-614

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I think the problem here is that server-side errors are not getting hidden when the field becomes dirty. Probably a quick tweak

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Bumping this up to a 5, in my WIP branch I've been giving the same treatment to our other inputs + DRYing up some stuff in regards to our forms for consistency + updating docs as well.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Ended up actually bumping this up to an 8. There was a lot of refactoring involved and it certainly took a while to wrap my head around what was going on. The fix for this will cover the Audience, Metrics, and Audience pages and the error will clear `onChange`.
