### ISSUE TITLE
Clicking "Next" in nimbus wizard doesn't save changes

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4022]
1. Go to https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/new and create a new experiment.
1. On the `/${slug}/edit/overview/` page, change the Public name and possibly fill in the hypothesis with a short novella.
1. Click the "Next" button.

Note that the changes you just made on the overview page were not saved when clicking "Next". In the case of an experiment name, this is mildly annoying. In the case of me filling in a lengthy hypothesis only to have my changes lost, it'd be pretty frustrating data loss.

Making a user click Save _then_ Next each time feels counterintuitive.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-613)
┆Issue Number: EXP-613

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

If we want next to work this way, it seems like a relatively simple change - next should do what save does and navigate to next step.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Hmm, I know I asked if we wanted "Next" to "Save and Next" and remember being told no. 😅 I think the intended behavior is that "Next" should be disabled if there's any unsaved changes.

**Comment by jodyheavener** [comment]
I'm not having much luck with #3885 (see my thread) and so having this will probably help prevent accidental data loss (alternatively, disabling Next until you have Saved, but it sounds like there was some pushback there)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~amedinac@mozilla.com] [~khudson@mozilla.com] Could either of you chime in here on the questions above?

**Comment by k88hudson** [comment]
I'd be highly in favour of `Save and Continue` v.s. disabling since:
- it doesn't matter if people save even if there were no changes and it makes them feel good sometimes to just click save
- it's hard to figure out why something is disabled

**Comment by k88hudson** [comment]
I just witnessed Alex hitting save like... 3 times to be sure :P

**Comment by jodyheavener** [comment]
The consensus is that "Next" will be re-labelled as "Save and Continue" (it must now save and advance to the next page) and "Save" will remain as well (no change).

**Comment by pdehaan** [comment]
Sounds like the previous/current Experimenter UI/flows (which is good);

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/102251863-37722a00-3eba-11eb-8cfc-d826d00038e7.png)
