### ISSUE TITLE
Add Public description field to the new experiment form for Nimbus experiments?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4023]
1. Go to https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/new and create a dummy experiment. It should prompt you for the following magic:
  - Public name
  - Hypothesis
  - Application (Desktop|Fenix)
1. Click the "Create experiment" button.
1. Note that the subsequent `/experiments/nimbus/${publicName}/edit/overview/` page is nearly identical with the following changes:
  - Application is no longer editable (despite still being a Draft -- if you got that wrong, burn it down and start again)
  - New textarea is added for "Public description".

Not sure if adding Public description to the New experiment form would make more sense (since I don't believe it is toggled depending on whether you specified the application as "Desktop" or "Fenix". But it feels like it turned a 1 page intake form into a 1.2 page intake form since the overview page has one extra field.

---

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99469159-f278c900-28f6-11eb-9d62-3ef2b4184c38.png)
**Figure 1:** Create new Experiment

---

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99469205-0f150100-28f7-11eb-8213-04191b97d243.png)
**Figure 2:** Experiment overview page, now ft. Public description field.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-616)
┆Issue Number: EXP-616

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Seems like a UX call - public description wasn't a field included in the Figma mockups. Seems not super-hard to do, but will require both front and back end changes

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

This is by design. Confirming with [~amedinac@mozilla.com] - should we cancel this?

**Comment by data-sync-user** [comment]
➤ Ana Medinac commented:

Hey! This is by design. The Create Experiment should just require the bare minimum to be able to create the draft experiment. Meanwhile, the Overview page has more information that the user can fill in later in the process. Eventually, the Overview page will grow and might have a few more boxes.

I'll close this ticket. 

CC: [~pdehaan@mozilla.com], [~lzugai@mozilla.com] , [~lorchard@mozilla.com]

**Comment by pdehaan** [comment]
<img width="222" alt="Nimbus_Console_UI_–_Figma" src="https://user-images.githubusercontent.com/557895/99850406-2986ee80-2b32-11eb-9688-97921e281ba7.png">

Closing. There was a note in the Figma specs about this as well. My bad.
