### ISSUE TITLE
Make Nimbus Public description field required?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4024]
https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/aadsfs/edit/overview

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99469330-51d6d900-28f7-11eb-85f7-a75a8758f7e4.png)

On step 2 of the Nimbus new experiment flow, it gently prompts for a public description which will be public to users on the **about:studies** page.
This field looks optional (validation doesn't seem to care that i left it blank and hit Save or Next). 

Not sure if this should be required for all studies, since having a bunch of potential experiments with no actual descriptions appear in my about:studies page. As an end user, I might be creeped out that I've been enrolled into X studies but not told what they do, what data they collect, etc.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-615)
┆Issue Number: EXP-615

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Might be a part of final review validation at the end? Maybe needs to be implemented on the form itself?

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

If I'm understanding the issue correctly this is now addressed - you can skip this field while you set up the experiment, but before the Review page is made accessible you must complete the public description. Note that currently you can hit the review page directly, but that'll see by protected in exp-497

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Moved this down to a 1 since the work was completed outside of this issue.
