### ISSUE TITLE
New Experiment UI doesnt match UX spec

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4038]
https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus

```json
{ "commit": "07b2625bb1cc908637d529af8fab5a7a97438ff8",
  "source": "https://github.com/mozilla/experimenter.git",
  "build": "https://circleci.com/gh/mozilla/experimenter/18309" }
```

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99595961-5c9e7600-29aa-11eb-8425-64fe61e4568a.png)

The [Figma specs](https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/Nimbus-Console-UI?node-id=216037%3A1694) show that we should have a "Nimbus Experiments" heading w/ a blue "Create new" button and then a list of experiments grouped by status. (For some reason none of my recent experiments are assigned to me, so after I create them they disappear into the abyss unless I can remember their slug and my experiment page is mostly blank, as shown above).

![Nimbus_Console_UI_–_Figma](https://user-images.githubusercontent.com/557895/99596103-940d2280-29aa-11eb-9bdb-1fdd7d3191be.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-620)
┆Issue Number: EXP-620

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I don't think we're done implementing thing here yet

**Comment by LZoog** [comment]
Closing this since now the Home page shows the Directory View
