### ISSUE TITLE
New Nimbus admin sidebar (i) icons look more informational than warnings

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4039]
https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/button-color-check/edit/overview

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99596694-9d4abf00-29ab-11eb-9315-c0a2becadaf3.png)

I spent a few seconds hovering over the new `(i)` icon expecting some informational tooltip.

~~What's doubly interesting is that if I go to the "Overview", "Branches", or "Audience" pages (all of which allegedly are missing details), I cant see any errors or warnings or indications of what I need to fix in order to remedy the missing details.~~

Filed as #4040; _"Validation on new Nimbus Experiment form doesn't highlight missing details"_

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-621)
┆Issue Number: EXP-621

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

More of a UX call than engineering I think. Maybe needs consideration whether the ℹ️ should be more of a warning or error icon?

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Paging [~amedinac@mozilla.com] for this. We do have the dark red icon but it wouldn't be as pretty in the sidebar. What do you think?

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Superseded by EXP-987
