### ISSUE TITLE
Add a "Conclusions / Action" field that's editable after a study ends

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#404]
We need to add a conclusions field that appears after a study launches and is still editable after a study closes

**Comment by shell1** [comment]
What type of optional information do we want after the study ends?  Looking to provide the in-box guidance so we get what we are hoping here.   AKA:  What question are we hoping to be able to answer based on information in this box?  adding @javaun 

Examples of questions I think we want answers to:

1. Do we want the ability to find results related to the study after the fact?  This will be built in towards the end of the year - but for now ask for "**link(s) to any data science results from this study**"?
2. Which studies impacted the product quickly "**Will what was learned in this study result in in product changes in the next 3 months**"
3. To know if the study was successful in answering the original questions.  So "**Did you learn what you intended from this study?  If not, do you know what was missing?**"
4. Do we want to know how impactful this study was - to help prioritize studies in the future?   So we'd ask "**did this study inform any decisions that should increase any of the core KPI metrics?  If yes, which ones and how?**

**Comment by pdehaan** [comment]
Should this be a big `<textarea>` or just a link to a Google doc, or some other editable group document?

**Comment by teonbrooks** [comment]
I think that there should be both a section for a URL and a text area for executive summary

**Comment by shell1** [comment]
starting fresh issues - so there is no confusion on implementation of this area.

#1268 #1269 #1270
