### ISSUE TITLE
Validation on new Nimbus Experiment form doesn't highlight missing details

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4040]
> What's doubly interesting is that if I go to the "Overview", "Branches", or "Audience" pages (all of which allegedly are missing details), I cant see any errors or warnings or indications of what I need to fix in order to remedy the missing details.
> &mdash; via #4039 

https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/button-color-check/edit/overview

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99597499-ee0ee780-29ac-11eb-913b-ae165dca71b6.png)

If I click the "Save" button, all the fields are marked as valid, so I'm not sure what the missing details are.

Turns out, the "Public description" is semi-required (but not caught by validation). If I set the public description field and hit save, and reload the page, the `(i)` disappears and the sidebar is updated.

Which is possibly a different issue. Adding a missing Public description and clicking the Save button doesn't remove the `(i)` in the sidebar or update the "Missing details in: ..." string without doing a page refresh.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-622)
┆Issue Number: EXP-622

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I think this is basically to-be-implemented in https://jira.mozilla.com/browse/EXP-465

**Comment by lmorchard** [comment]
https://github.com/mozilla/experimenter/issues/3699
