### ISSUE TITLE
Add "duplicate experiment" functionality

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4048]
It was relatively common in the development/testing phase of launching an experiment to have to copy another experiment (e.g. after finishing an A/A test, creating an A/B test with identical targeting etc.)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-629)
┆Issue Number: EXP-629

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Should this issue be a part of the EXP-628 epic?

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Should this be split into two issues for frontend and backend?

**Comment by lmorchard** [comment]
> Should this be split into two issues for frontend and backend?

Yeah, this should probably be more like an entire standalone epic and broken down. Seems misplaced within the Launch to Preview / QA epic.

**Comment by data-sync-user** [comment]
➤ Ana Medinac commented:

Might not need this for the QA launch flow. It would be a nice to have, but not necessary. After speaking with Jared, this might be a separate epic. [~khudson@mozilla.com] does this make sense to you?

If so, might bump out of the Launch Preview epic.

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Yep, makes sense to bump this out :+1:
