### ISSUE TITLE
Confusing Nimbus experiment client-vs-server validation

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4051]
https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/new

1. Set the "Public name" to "aaa".
1. Click "Create experiment" button.
	- Nothing really happens, but the "Application" dropdown is highlighted. Clicking the "Create experiment" button again causes the "This field may not be blank" validation error to appear and the "Application" field to have the red validation highlight.
1. Set the Application target to "Desktop" or "Fenix" (doesn't matter).
	- Note that the Hypothesis field never changed, but there should now be three green checkmarks for the "Public name" text field, "Hypothesis" text area, and the "Application" drop down menu; leading me to think my fields are all valid and I'm good to go(tm).
1. Click the "Create experiment" button again.
1. The "Public name" and "Hypothesis" fields are now invalid.
	- In the case of "Public name", the experiment named "aaa" already exists. You can change it to "AAA" and you get a cool error saying "Name maps to a pre-existing slug" which is :+1:
	- In the case of "Hypothesis", I guess it doesn't like the default value so you have to type a few random characters to make it look non-default.

Not sure what the solution is. I think it'd be nicer (as a user) to get the validation earlier if my public name/slug is unavailable without having early validation saying it's valid and then server validation saying "oops, try again".

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-632)
┆Issue Number: EXP-632

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

This could be complex. I think the basic issue is that we don't talk to the server until submission - there's information that on-the-fly client-side validation doesn't have (e.g. existing experiment slugs). So, to really resolve this, we'd probably need client-side validation to bounce off a server API for every field at least on blur

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Yeah or we just gut out the client side validation altogether and every click to save hits teh server so you only see the server validation.
