### ISSUE TITLE
Unable to create valid Nimbus experiment

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4053]
https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/peter/edit/audience

Looks like I can fake enough data/branches to get a valid experiment, with the exception of "Missing details in: Audience".

I guess the problem is that there isn't a UI for Audience yet, so it can't be valid, and therefore I can no longer get to a Review & Launch state or see the summary.

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99707878-e9503f00-2a51-11eb-89d3-b9376fcd3144.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-634)
┆Issue Number: EXP-634

**Comment by lmorchard** [comment]
Yeah, we're not feature-complete yet - just starting on the audience form stuff today hopefully https://github.com/mozilla/experimenter/issues/3749

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I think this will be resolved by other things yet to be implemented, but going to toss it into an epic as maybe something easily closed at that point.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

This should be close-able once EXP-506 is finished.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~pdehaan@mozilla.com] Canceling this bug as not yet implemented - as no code is expected required to land a 'fix', this won't be actionable on anyone to review.
