### ISSUE TITLE
Can not create branch without feature

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4056]
I just noticed if you try to add a branch, by default it has no feature config, so you fill in name and description, and it says

Feature Config required when a branch has feature enabled.

so I think it's defaulting to feature_enabled=True which doesn't match the UI

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-636)
┆Issue Number: EXP-636

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Cancelling as this is a dupe of EXP-627.

**Comment by LZoog** [comment]
Huh, per my previous comment I cancelled this on 11/19 but it didn't close the issue, closing now.
