### ISSUE TITLE
Pref changes are no longer recorded in History if the same user edited them twice in a row

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/experimenter#4083]
**[Notes]**
- The issue is reproducible if any of the pref "Branch", "Name", "Type" or "Value" is changed twice in a row by the same user.
- This behavior is encountered quite often because the user which creates an Experimenter page, usually edits the pref branches at least two times until the Experimenter page is moved to "Ready for Sign off" state. 
- Since these changes are not recorded, a person (in particular) who checks the Experimenter page can miss that the pref branches have been changed. QA has almost missed these types of changes a few times.

**[Affected versions]:**
- Firefox 83.0 Release
- Chrome 87.0.4280.66 

**[Affected Platforms]:**
- All Windows;
- All macOS;
- All Linux;

**[Prerequisites]:**
- You are logged in your LDAP account.
- Have an experiment created on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- The Branches section is already completed during the Experiment creation.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://stage.experimenter.nonprod.dataops.mozgcp.net/".
2. Open the experiment from prerequisites and click the "Edit" button from "Branches" section.
3. Edit the pref Name, Type or Value and click the "Save Draft" button.
4. Repeat step 2 and step 3.
5. Observe the "History" section.

**[Expected result]:**
- The pref changes are recorded in the History section for both changes.

**[Actual result]:**
- No new pref changes are recorded in the History section.

**[Additional Notes]:**
- The issue is NOT reproducible if multiple users edit the pref "Branch", "Name", "Type" or "Value" in turn.
- The issue is NOT reproducible if there is One Pref for all branches.
- The Pref changes are recorded in the History section only if the branch "Size", "Name", or "Description" is edited.
- Here is a link with the screen recording of the issue: [Link](https://drive.google.com/file/d/1KdJBPxwPlMXlbvXEt3YgUhQqEW9DCfrH/view?usp=sharing)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-645)
┆Issue Number: EXP-645

**Comment by SoftVision-CosminMuntean** [comment]
The "History" section is very useful for the QA team, to verify if there are any updates on the experiment. During the test case creation and experiment testing, the QA verifies the "History" section quite often to see if there are new updates.
There were a few cases when the Normandy stage recipe and the test cases were created based on the initial information from the Experimenter page and we missed that the prefs were changed/edited because the changes were not recorded in the "History" section. 

Considering this, we would like to have this issue fixed as soon as possible.

**Comment by jaredlockhart** [comment]
@SoftVision-CosminMuntean Thanks for catching this we'll look at it this week 👍

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on Firefox Release 84.0.2 and Chrome 87.0 on Windows 10 x64 and macOS 10.15.6. 
- The pref changes are recorded in History if the same user edits them multiple times in a row.
