### ISSUE TITLE
Prefill branch names when adding new Nimbus Experiments?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4092]
This wasnt clear from the [Figma spec](https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/Nimbus-Console-UI?node-id=216037%3A6948), but after creating dozens of dummy experiments, it's getting a bit tedious.

Since experiments have 2 branches created by default, should we just prefill the control branch's name to "control" and the second branch's name to "treatment" to avoid making users enter those each time? They're still user editable, but prefilling those with values that will work for the majority of use cases might make it slightly faster to get started.
If the user adds a third (or whatever number) additional branch, probably safe to leave the branch names empty and make them do the work of filling in a name since we don't want to get silly with "treatment 2", "treatment 3", etc.

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/100793189-9fac1080-33d0-11eb-9e2f-5c160d72a894.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-649)
┆Issue Number: EXP-649

**Comment by pdehaan** [comment]
What's interesting here, is that if we click "+ Add branch" button, it will prefill the branch name with "New treatment 2" but we don't prefill a default Description so the page won't be valid. Since we already create placeholder branch names for new branches, I think it makes sense to add placeholders for the default branches as well (possibly even making up values for description).

**Comment by lmorchard** [comment]
>What's interesting here, is that if we click "+ Add branch" button, it will prefill the branch name with "New treatment 2"

Hmm, IIRC, the name is pre-filled on the client side because at one point the code needed *something* there to generate a unique slug. 

But, we removed the client-side slug handling, so actually these names could be left blank now and don't *need* to be generated. And I don't think we actually *want* these placeholder names to be part of a valid submission. (i.e. The user *should* come up with something to enter here)
