### ISSUE TITLE
Django Admin "Firefox min version:" doesn't fit with Fenix nightly version names

### ISSUE THREAD

**Issue by travis79** [mozilla/experimenter#4097]
Fenix Nightly doesn't use the same version naming as the beta and release channels do, making the "Firefox min version" field in the Django Admin tool a little confusing.  Here is an example of what Fenix nightly version names look like: https://sql.telemetry.mozilla.org/queries/76605

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-652)
┆Issue Number: EXP-652

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Assuming that our initial mobile experiments do not require any targeting (right [~tlong@mozilla.com]?) and it's possible to leave this field blank in the UI, I wouldn't consider this technically blocking,  but it is weird that the options only provide Desktop-specific values in the UI. It's also weird that it's called firefoxminversion in the model and the values are hard-coded, but yeah, also not blocking.

**Comment by data-sync-user** [comment]
➤ Travis Long commented:

Correct, we don't require this for targeting our first experiments.

**Comment by jaredlockhart** [comment]
Blocked pending further discussion with @travis79 and the rust sdk team to figure out how we wanna target against these timestamp based nightly versions

**Comment by travis79** [comment]
@jaredlockhart After discussing with the SDK team, we aren't going to target based on version on Nightly for now, and I will be investigating how to handle this probably when we get back from the holiday break.  @k88hudson suggestion pulling the versions from telemetry/BigQuery, but that doesn't really solve the issue of targeting something that hasn't been released yet (can't guess the exact version name).  I'll ping you as I dig into the investigation and I'm happy for this issue to be backlogged until we can unblock it.
