### ISSUE TITLE
Add nimbus-ui sourcemaps to Sentry

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4099]
The nimbus-ui React app should supply sourcemaps to Sentry so exceptions can point to the correct lines of code where they occurred. Setup instructions [here](https://docs.sentry.io/platforms/javascript/sourcemaps/) (heads up, you'll need someone to get you a Sentry API token, and you'll need to set up env vars for stage and prod).

Also because it's a create-react-app you won't have direct access to the Webpack config, but you can inject new config in our [Rescripts config](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/.rescriptsrc.js).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-654)
┆Issue Number: EXP-654

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Btw, marked this as High priority because it's darn near impossible ( https://sentry.prod.mozaws.net/operations/experimenter-stage/issues/10082384/?query=is%3Aunresolved ) to see what's going on in Sentry right now with the minified JS.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Added flag as this is blocked by exp-730

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Let's see if I can figure this out

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

{quote}heads up, you'll need someone to get you a Sentry API token, and you'll need to set up env vars for stage and prod{quote}

Dug around today and it looks like we'll need some ops support for this part? Or, at least, access to configure Jenkins and create internal integrations on Sentry? (Neither of which I have)

The plugin itself looks easy enough to configure, but it needs an auth token and per-environment vars at build time:

  1. Need an auth token for SentryWebpackPlugin for use in uploading a source map. This sounds like an internal integration auth token ( https://docs.sentry.io/product/integrations/integration-platform/#internal-integrations ). Unless I'm missing it, I don't think I have access to see or use the UI to create this
  2. Need a SENTRY_AUTH_TOKEN env var at build (i.e. in Jenkins?) to supply the internal integration auth token to webpack
  3. Need SENTRY_ORG and SENTRY_PROJECT env vars to be accessible during build - i.e. SENTRY_ORG="operations", and then SENTRY_PROJECT="nimbus-ui-prod" and SENTRY_PROJECT="nimbus-ui-stage" respectively

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

See, I am suspicious of if we even need this separate Webpack setup. Our two frontend Sentry projects have the "Enable JavaScript source fetching" option enabled, both prod and stage point to the sourcemap file, and the sourcemap file is readily available (prod ( https://experimenter.services.mozilla.com/static/nimbus/static/js/main.js.map )). So why wouldn't it be able to find the sourcemaps on its own? I also asked in FxA ( https://mozilla.slack.com/archives/CLV3KMZ8B/p1607532351136300 ) a while back, and they used to use the Webpack plugin but have since removed ( https://github.com/mozilla/fxa/commit/58d0f9f8d8cb89991bf3cac25cfe96967a68fd67 ) it and just rely on that Sentry setting it seems.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

That source map on prod is not readily available to Sentry, I don't think. Accessing https://experimenter.services.mozilla.com/static/nimbus/static/js/main.js.map redirects to an Auth0 login page

**Comment by lmorchard** [comment]
Making some progress: https://github.com/mozilla/experimenter/compare/4099-sentry-sourcemaps

I've got the build process uploading sourcemaps to a commit-based release on my personal Sentry account with an internal integration auth token. Also need to thread through the commit hash as release version when reporting errors to Sentry to associate them with the uploaded sourcemaps.

Still working on trying to get the right sourcemaps uploaded, though. Seems like we have a source map for post-Typescript JS code, so the Sentry errors are still rather unhelpful.

Sentry also is a bit confused by our proxied-through-Django setup and thinks the source code lives at http://localhost:3000 rather than https://localhost. I think the local Sentry reporting library is trying to fetch source that way.

Still digging

**Comment by lmorchard** [comment]
> Sentry also is a bit confused by our proxied-through-Django setup and thinks the source code lives at http://localhost:3000 rather than https://localhost. I think the local Sentry reporting library is trying to fetch source that way.

Oh, I see... the source *does* live at http://localhost:3000 - we *didn't* proxy it for local dev. Sentry is hitting a CORS restriction trying to fetch that source for itself from https://localhost

**Comment by lmorchard** [comment]
A new challenger solution has appeared: https://bugzilla.mozilla.org/show_bug.cgi?id=1715126

Going to [try whitelisting the static assets](https://github.com/mozilla/experimenter/pull/5374#issuecomment-856112809) as exempt from Auth0 login, which may make uploading sourcemaps unnecessary.

**Comment by lmorchard** [comment]
Sourcemap should be accessible now without auth. Let's see if Sentry notices the difference.

```
✗ curl -I https://experimenter.services.mozilla.com/static/nimbus/static/js/main.js.map
HTTP/2 200 
server: openresty/1.15.8.2
date: Mon, 07 Jun 2021 21:22:50 GMT
content-type: application/octet-stream
content-length: 7032493
cache-control: max-age=60, public
access-control-allow-origin: *
last-modified: Mon, 07 Jun 2021 21:17:38 GMT
etag: "60be8cf2-6b4ead"
vary: Origin
strict-transport-security: max-age=31536000
via: 1.1 google
alt-svc: clear
```
