### ISSUE TITLE
You can force a NImbus experiment Review state by hacking URL

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4100]
https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/sdfadfasdf/request-review

You can see from the sidebar that I'm missing required info for "Audience", as well as a page of errors for experiment owner not being set, missing probes, duration, etc... But I was still able to check a couple checkboxes and set my experiment into the Review state, which seems wrong.

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/100905447-efe0ac80-347c-11eb-966c-3949a9eef484.png)

I know hacking URLs probably isn't a valid use case, but there might be a second issue here it shouldnt have let me request review of an experiment that is missing so much required data still.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-655)
┆Issue Number: EXP-655

**Comment by jodyheavener** [comment]
I think #3757 or #3758 should address this.

**Comment by LZoog** [comment]
@pdehaan closing this, it should no longer be an issue, please reopen if not 🙂
