### ISSUE TITLE
NimbusProbeSet event_category property is nullable

### ISSUE THREAD

**Issue by scholtzan** [mozilla/experimenter#4104]
I just noticed this while [integrating the new `probesets` API into Jetstream](https://github.com/mozilla/jetstream/pull/342). Based on the schema in https://github.com/mozilla/experimenter/blob/7e0635a58f9cb81606985a05a6ec3a03d827f50b/app/experimenter/docs/openapi-schema.json#L3595 `event_category` cannot be nullable. However, based on the [feature definition in nimbus-shared](https://github.com/mozilla/nimbus-shared/blob/3c41e072407af80d457931deed47cd840e358af4/types/features.ts), scalar probes are not expected to have the `event_category` property.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-657)
┆Issue Number: EXP-657

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Probe sets are dead.  Long live probesets.
