### ISSUE TITLE
General Application Error on Nimbus Results page

### ISSUE THREAD

**Issue by emtwo** [mozilla/experimenter#4111]
This is likely due to the missing `retained` metric. Made the assumption it would be available from Jetstream but alas. It is not. Will need to fix

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-661)
┆Issue Number: EXP-661

**Comment by emtwo** [comment]
https://sentry.prod.mozaws.net/operations/experimenter-prod/issues/10187409/

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Moving into "In Progress" per Marina's mention during our Experimenter meeting today.
