### ISSUE TITLE
Use internal redash URL for dashboards

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#412]
Right now we're using the 'public url' for dashboards except they seem to be broken, so let's switch to using the private internal URL.

**Comment by emtwo** [comment]
This internal url is now available as a field on a dashboard object called `slug_url`

https://github.com/mozilla/stmoab/blob/master/stmoab/SummaryDashboard.py#L32

**Comment by jaredkerim** [comment]
Bump stmoab to 0.0.8
