### ISSUE TITLE
Add applications API endpoint to V6

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4147]
Let's add an endpoint to V6 that lists all applications.  In the future we can add additional metadata to each application to assist jetstream in identifying the relevant telemetry for a given application.

/api/v6/applications/

slug: str
channels: str[]

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-674)
┆Issue Number: EXP-674

**Comment by data-sync-user** [comment]
➤ Tim Smith commented:

I think this is mooted and we don't need it anymore; it's been replaced by the appId/appName pair in the Experiment DTO described in ADR 0004.
