### ISSUE TITLE
Add channel to experiments V6 API

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4148]
We need to expose the channel field in the V6 experiments API so jetstream can identify the relevant telemetry for a given experiment.  Blocked on https://github.com/mozilla/nimbus-shared/issues/146

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-673)
┆Issue Number: EXP-673

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Ok, v1.2.0 should be published now
