### ISSUE TITLE
If an experiment has saved branches, it shouldn't show empty default branches

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4150]
Right now if you create an experiment, giv eit only a control branch, save, and reload the page, you'll se a second empty branch.  If an experiment has saved branches loading the branches form should only show the saved branches.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-675)
┆Issue Number: EXP-675

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

I'm going to close this as a dupe of EXP-821 / #4403
