### ISSUE TITLE
Disallow non-numbers from being typed in number fields

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4151]
We want to extract this as well as we can to use across all inputs that show numbers for better client-side validation. We'll likely have to disable characters from being entered with a keydown listener.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-677)
┆Issue Number: EXP-677

**Comment by pdehaan** [comment]
Interesting! https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Using_number_inputs

> ### Using number inputs
> When you create a number input with the proper `type` value, `number`, you get automatic validation that the entered text is a number, and usually a set of up and down buttons to step the value up and down.
>
> _**Important:** Bear in mind that, logically, you should not be able to enter characters inside a number input other than numbers. There seems to be some disagreement about this among browsers; see [bug 1398528](https://bugzilla.mozilla.org/show_bug.cgi?id=1398528)._

Firefox Beta seems to let me spam a bunch of letters in MDN samples, but Chrome Release limits it to numeric values only, so this seems to be an upstream browser issue.

**Comment by LZoog** [comment]
Funny, I'm the one that made this task and didn't realize it, but this was solved in #4499
