### ISSUE TITLE
Labels on Review & Launch don't match intake form

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4155]
https://stage.experimenter.nonprod.dataops.mozgcp.net/__version__

```js
{ "commit": "7906f4618b0f5f0526c44fe9f7ba1d0f68c8bb08",
  "source": "https://github.com/mozilla/experimenter.git",
  "build": "https://circleci.com/gh/mozilla/experimenter/19125" }
```

Minor nit, but makes it a bit trickier to fix any potential issues if the field labels don't match.

## [/edit/audience](https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/pdehaan-2020-12-07-005/edit/audience)

![pdehaan_2020-12-07_005_–_Audience___Experimenter](https://user-images.githubusercontent.com/557895/101418165-113d0080-38a2-11eb-8700-f3ec4e5aa35d.png)

---

## [/request-review](https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/pdehaan-2020-12-07-005/request-review)

![pdehaan_2020-12-07_005_–_Review___Launch___Experimenter](https://user-images.githubusercontent.com/557895/101418145-084c2f00-38a2-11eb-9ba0-b4e85698311f.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-680)
┆Issue Number: EXP-680

**Comment by LZoog** [comment]
This is a UX question, @AnaMedinac @k88hudson should we adjust the wording on the table to what Peter has suggested?

**Comment by AnaMedinac** [comment]
Ah yes! They should definitely match. Let's update:
* `Population %` to `Percent of clients` and
*  `Custom audience` to `Advanced Targeting`. 
Let's leave `Minimum version` as is. I'll update the Figma specs btw.
