### ISSUE TITLE
Population % of zero reports as "Not set" in Review but valid in Audience

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4156]
[/request-review](https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/pdehaan-2020-12-07-005/request-review)

![pdehaan_2020-12-07_005_–_Review___Launch___Experimenter](https://user-images.githubusercontent.com/557895/101418960-d340dc00-38a3-11eb-800b-40867bd54042.png)

---

[/edit/audience](https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/pdehaan-2020-12-07-005/edit/audience)

![pdehaan_2020-12-07_005_–_Audience___Experimenter](https://user-images.githubusercontent.com/557895/101419065-14d18700-38a4-11eb-843a-cea9f36ac7b4.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-681)
┆Issue Number: EXP-681

**Comment by LZoog** [comment]
The population percent should be above 0 but less than or equal to 100 and we should enforce this in the FE and BE.

**Comment by LZoog** [comment]
The solve for this issue should add client-side validation.

Enforcing validation in the BE will be handled in #4185.

**Comment by lmorchard** [comment]
I think this issue is made obsolete by our decision to no longer gate submission on client-side validation - this should be all server-side now in the review-time validation

https://github.com/mozilla/experimenter/issues/4299
