### ISSUE TITLE
Audience page "Percent of clients" shows error on decimals but doesn't show an error message

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4157]
![pdehaan_2020-12-07_005_–_Audience___Experimenter](https://user-images.githubusercontent.com/557895/101419438-ddafa580-38a4-11eb-8d48-4c0fa3fdc839.png)

Not sure if decimals should be valid or not (we could argue either way), but currently we show an error icon in the intake form, but no error message so it isn't super actionable (although the number controls convert things back to integers and fix the validation error). 

Ref #4151

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-682)
┆Issue Number: EXP-682

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Looks like this is native browser validation flagging this as invalid - it's a type="number" but without a step attribute, which I guess asserts that the number should be a whole integer?

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

https://github.com/mozilla/experimenter/pull/4174
