### ISSUE TITLE
Consolidate error colors

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4161]
I was on [/edit/overview](https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/pdehaan-2020-12-07-006/edit/overview?show-errors) and noticed that I had 3 different colors for various error states. Not sure if there was discussion around that in today's validation/errors meeting, so feel free to close this or dupe it to something else as you see fit.

If we're voting, I think I prefer #DC3545, as far as colors go &mdash; it feels a bit less harsh than the "Public description" #840000 color.

![pdehaan_2020-12-07_006_–_Overview___Experimenter](https://user-images.githubusercontent.com/557895/101431645-27f05100-38bc-11eb-9f2c-0da5833ddfe0.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-686)
┆Issue Number: EXP-686

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

In combining the review-readiness state with the rest of the in-field errors (EXP-981) we are partially addressing this
