### ISSUE TITLE
Rejected experimenter experiment not returned to an editable DRAFT state

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4167]
https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/pdehaan-2020-12-07-005/edit/overview was submitted and rejected (See [Slack](https://mozilla.slack.com/archives/CANCHH6R1/p1607390795397500) discussion for more context).

My experiment was rejected, but per [GraphiQL](https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v5/graphql#query=%7B%0A%20%20experimentBySlug(slug%3A%22pdehaan-2020-12-07-005%22)%20%7B%0A%09%09id%0A%20%20%20%20owner%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20name%0A%20%20%20%20slug%0A%20%20%20%20publicDescription%0A%20%20%20%20status%0A%20%20%7D%0A%7D%0A) the state is currently set to "ACCEPTED" and not "DRAFT" so the experiment is non-editable.

Ref: [Figma spec](https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/Nimbus-Console-UI?node-id=216037%3A1694).

![Nimbus_Console_UI_–_Figma](https://user-images.githubusercontent.com/557895/101515282-0a120300-3933-11eb-9581-ae41625c7252.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-694)
┆Issue Number: EXP-694

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Addressed by recent review workflow changes.
