### ISSUE TITLE
"Accepted" status should display in progress bar as "Review"

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4186]
In the Summary component, when an experiment's status is "accepted," it isn't displayed in the progress bar. It should reflect "review".

!image-2020-12-08-16-14-18-235.png|thumbnail!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-707)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/14554/image-2020-12-08-16-14-18-235.png">image-2020-12-08-16-14-18-235.png</a>
┆Issue Number: EXP-707

**Comment by pdehaan** [comment]
Possibly also worth calling out, but the [Figma spec](https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/Nimbus-Console-UI?node-id=216037%3A1694) does show a special "Accepted" state in that brief time where:

> After an experiment is approved, before it launches. "Results" are grey-out with help text explaining why...

Also interesting is that it's the only phase of the flow with the "Accepted" state.
Not sure if this is related to this ticket, or if we need a separate ticket for _this_ stage of the overloaded "Accepted" term, or if we need to update the UI specs with the new workflow so it's in sync with whatever we do here.

![Banners_and_Alerts_and_Nimbus_Console_UI_–_Figma](https://user-images.githubusercontent.com/557895/101819059-99f1b180-3ad9-11eb-8d48-4f7f7322e774.png)
