### ISSUE TITLE
Inconsistent error message display on Nimbus branches

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4195]
https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/pdehaan-2020-12-08-004a/edit/branches?show-errors

This had me stumped for a while... Seems like a combination of focus events causes some previous validation messages to disappear. Not sure if it's dueling client vs server validations or something else sneaky.

### STR

1. Change your branch Ratio to "0.3".
    > You should get a validation error saying "Ratio must be a number". Ignore that.
1. Clear the branch Description.
    > You should get a validation error saying "This field may not be blank."
    > Note that the Ratio validation message disappeared, and the "Save" button is currently disabled.
1. Enter a valid branch Description.
    > The validation tells me that the Description field is now valid, but we seemingly lost the validation on the Ratio field and there is no way for me to Save the form since I'm in a pseudo-invalid state.
    > At this point I had to re-navigate to the page again (losing all my changes) and realized I sloppily left the ratio as a decimal vs an integer.

---

![pdehaan_2020-12-08_004a_–_Branches___Experimenter](https://user-images.githubusercontent.com/557895/101557253-7d3a6a00-3971-11eb-9571-c8f804543903.png)

![pdehaan_2020-12-08_004a_–_Branches___Experimenter](https://user-images.githubusercontent.com/557895/101557300-9511ee00-3971-11eb-9ef8-5bba05664bf9.png)

![pdehaan_2020-12-08_004a_–_Branches___Experimenter](https://user-images.githubusercontent.com/557895/101557340-aeb33580-3971-11eb-82cb-5cbc595db160.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-716)
┆Issue Number: EXP-716

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I think I might be in the process of fixing this as part of EXP-679
