### ISSUE TITLE
Ability to edit other peoples experiments?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4205]
Related to, but possibly not fixed by, #4142

I was trolling through the GraphiQL page for Draft experiments and by extracting the slug I can seemingly find other people's experiments and edit them (while they're still in the draft state, I wasn't seemingly able to edit an existing experiment in the "Approved" state, even if appending the /edit/ URL (the "Save" and "Next" buttons still appear, but seem to do not save any changes when clicked).

```graphql
{
  experiments(limit: 10, status: Draft) {
    # ...
  }
}
```

https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/testo/edit/overview

I think you could argue either way if anybody can edit anybody's experiments, but this felt like it was worth calling out so we know the risks and implications.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-726)
┆Issue Number: EXP-726

**Comment by jaredlockhart** [comment]
Yep this is expected, even in the legacy workflow there's no concept of editing restrictions, and we haven't designed any for nimbus either.

**Comment by pdehaan** [comment]
Closing as designed.

**Comment by pdehaan** [comment]
From Slack:

> **Peter deHaan**  3 minutes ago
> Do we keep a changelog of edits and by whom somewhere? Or I guess if it isn’t user visible, it might not matter and i might not know if somebody else ever tweaked my experiment and fixed a typo or changed a URL.
>
> **Jared Lockhart**  2 minutes ago
We're logging changes they're just *not exposed in the ui yet
