### ISSUE TITLE
Check for set difference in kinto.tasks.nimbus_check_kinto_push_queue

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4209]
It looks like remote settings got into a state where it had rejected an experiment but the rejection record was gone before the task was able to check it, so we should add a conditional check here:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/kinto/client.py#L56

Sentry record:

https://sentry.prod.mozaws.net/operations/experimenter-stage/issues/10223981/?query=is%3Aunresolved

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-731)
┆Issue Number: EXP-731

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

This is fixed now by https://github.com/mozilla/experimenter/issues/5028
