### ISSUE TITLE
Default enrollment period of 7 days cannot be blank

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4218]
https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/pdehaan-2020-12-100010/edit/audience?show-errors

After creating an experiment, if you click on the "Audience" link under "Review & Launch" it will redirect you to the /edit/audience page with the `show-errors` query string flag.

![pdehaan_2020-12-10_001_0____–_Audience___Experimenter](https://user-images.githubusercontent.com/557895/101812395-24351800-3ad0-11eb-84a1-54f387eead25.png)

Note that currently the `proposedDuration` and `proposedEnrollment` are `null` (per the [GraphiQL dashboard](https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v5/graphql#query=%7B%0A%20%20%23%20experiments(limit%3A%205%2C%20status%3A%20Accepted)%20%7B%0A%20%20experimentBySlug(slug%3A%20%22pdehaan-2020-12-100010%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20owner%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20status%0A%20%20%20%20name%0A%20%20%20%20slug%0A%20%20%20%20publicDescription%0A%20%20%20%20isPaused%0A%20%20%20%20proposedDuration%0A%20%20%20%20proposedEnrollment%0A%20%20%20%20populationPercent%0A%20%20%20%20totalEnrolledClients%0A%20%20%20%20firefoxMinVersion%0A%20%20%20%20application%0A%20%20%20%20channels%0A%20%20%20%20hypothesis%0A%20%20%20%20targetingConfigSlug%0A%20%20%20%20startDate%0A%20%20%20%20endDate%0A%20%20%7D%0A%7D%0A)), so it looks like a confusing placeholder text is setting the "7" and "28" values on the front end while the underlying data is failing validation until the form gets into a valid state and can be saved with the placeholder values.
But currently, to the end user, it looks like somehow an enrollment period of 7 days is somehow a valid choice.

Also note that this only seems to be an issue if you click the specific "Audience" link under "Review & Launch". If you click the main "Audience" link above, or the informational `(i)` icon, you won't get that `?show-errors` query string or the error icons.

---

<img width="786" alt="pdehaan_2020-12-10_001_0____–_Audience___Experimenter" src="https://user-images.githubusercontent.com/557895/101814371-e71e5500-3ad2-11eb-824a-80ffa44f6131.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-736)
┆Issue Number: EXP-736

**Comment by pdehaan** [comment]
Ref: #4196

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

This is no longer reproducible
