### ISSUE TITLE
Clicking "error" icon in main nav doesnt show error icons on pages

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4221]
Loosely related to #4218

Clicking the "Audience" link under "Review & Launch" shows `(!)` validation error icons, but clicking the `(i)` icon in the side navigation does not.
Not sure if it's an easy fix (we'd need to split the one current `<a>` wrapper into two separate anchor links, one of which appends the [`?show-errors` query string arg](https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/pdehaan-2020-12-100010/edit/audience?show-errors).

<img width="1108" alt="pdehaan_2020-12-10_001_0____–_Audience___Experimenter" src="https://user-images.githubusercontent.com/557895/101815253-226d5380-3ad4-11eb-81ac-29132054299d.png">

versus

<img width="1103" alt="pdehaan_2020-12-10_001_0____–_Audience___Experimenter" src="https://user-images.githubusercontent.com/557895/101815398-521c5b80-3ad4-11eb-9034-3c652a7ab00a.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-738)
┆Issue Number: EXP-738

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

These are intentionally not clickable elements, but it is acknowledged that this is unclear and we are working on addressing this partly in EXP-981 and possibly changing the color of these buttons. Related EXP-621
