### ISSUE TITLE
Channel is in an unintuitive order

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4224]
Typically we think of channels in the following order:  Unbranded, Nightly, Beta, Release

We should probably reorder the values in this drop down:

<img width="766" alt="Screen Shot 2020-12-10 at 2 56 56 PM" src="https://user-images.githubusercontent.com/119884/101822929-14312e80-3af8-11eb-836c-de5b95f80af2.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-739)
┆Issue Number: EXP-739

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

This is now fixed.
