### ISSUE TITLE
`application` field for Fenix Nightly just shows "fenix" instead of "org.mozilla.fenix"

### ISSUE THREAD

**Issue by travis79** [mozilla/experimenter#4235]
Since the SDK matches the `application` field against the `application_id` that is passed in during init, it is expecting the same bundle identifier that is used by the Play Store.  This is the only way that channels are currently encoded in mobile that we can target them.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-745)
┆Issue Number: EXP-745

**Comment by jaredlockhart** [comment]
Ah okay this is conflating `application` and `channel`.  What you're looking for here is `channel`:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/constants/nimbus.py#L105-L107

which is exposed in the DTO as `channel`:

https://github.com/mozilla/nimbus-shared/blob/main/types/experiments.ts#L25

Example in the fenix experiment targeting `Fenix Nightly` on stage:

https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v6/experiments/fenix-nimbus-validation-2/

<img width="342" alt="Screen Shot 2020-12-11 at 2 21 25 PM" src="https://user-images.githubusercontent.com/119884/101945431-31c7cc00-3bbc-11eb-8104-10adef488331.png">

**Comment by k88hudson** [comment]
@jaredlockhart Let's go with application in the DTO being org.mozilla.fenix – it makes more sense given the way applications are set up from a targeting perspective (although not in the UI)

**Comment by data-sync-user** [comment]
➤ Tim Smith commented:

Closing in favor of EXP-825.
