### ISSUE TITLE
Validate total enrolled clients > 0 to launch, provide guidance to contact data science

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4256]
Total Enrolled Clients should be greater than 0, but this number should come from a data scientist, so we should provide some helpful guidance to experiment owners that they need to get this number from data science.  This number isn't used to launch the experiment, but is just used for reference when looking at monitoring telemetry to know if the total enrolled population matches the experiment design expectation. @AnaMedinac can you provide maybe a sentence that we can put under the field to provide helpful guidance?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-747)
┆Issue Number: EXP-747

**Comment by k88hudson** [comment]
+1 to having some text for guidance, I also think we could just ask DS to just fill out the fields directly in experimenter assuming the have the link the DS ticket
