### ISSUE TITLE
Targeting config had to be selected twice

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#4259]
When trying to select a targeting config, we had to select it twice to get it to stick. (when choosing First Run)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-749)
┆Issue Number: EXP-749

**Comment by jaredlockhart** [comment]
Oh yep, I just saw it! Looks like there's a JS delay for some reason:

![2021-05-18 17-33-27 2021-05-18 17_34_23](https://user-images.githubusercontent.com/119884/118726482-5ffea700-b7ff-11eb-977d-9077fa5b28c5.gif)

**Comment by pdehaan** [comment]
Weird. I'm unable to reproduce this on macOS 10.15.7/Catalina (rMBP w/ 32GB RAM though) with a random draft experiment (https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/ppop-tiny-test/edit/audience) on latest Firefox Nightly or Chrome. My initial thought was that the page was still somehow finishing rendering the DOM while you were trying to modify the dropdown value, but I can't see any delay using a mouse or keyboard to change that field.

Is it always slow for you two, or just the first time you try modifying the value on that page (and reselecting the field is much faster)?
