### ISSUE TITLE
Disabled feature has null value, kinto publishing expects it to be JSON-serializable

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#4260]
We ran into this when publishing an experiment with an enabled=false branch I think https://sentry.prod.mozaws.net/operations/experimenter-stage/issues/10261719/

Is it possible it's expecting JSON for the feature value?

Changing the value on django admin to `{}`fixed the problem

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-750)
┆Issue Number: EXP-750

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Blocking on https://github.com/mozilla/nimbus-shared/pull/166

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/pull/5104
