### ISSUE TITLE
Missing Audience Channel doesn't have a missing detail icon

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4262]
The [Audience](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-2020-12-14-001/edit/audience?show-errors) page's Channel doesn't seem to have an `(i)` icon if you don't have a selected channel.

1. Create a new experiment via https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/new
1. Set an experiment name, hypothesis, and application type.
1. Click the "Audience" link under "Review & Launch".
1. Note that the "Channel" field is required and may not be blank, but there is no `(i)` icon next to that field.

![pdehaan__2020-12-14__001_–_Audience___Experimenter](https://user-images.githubusercontent.com/557895/102132290-47c9cc80-3e08-11eb-996a-54d3956da7bd.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-751)
┆Issue Number: EXP-751

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Will be covered by EXP-981
