### ISSUE TITLE
Confusing "control branch is required" error message on new experiments

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4265]
1. Create a new experiment with a valid name, hypothesis, and application type.
1. Click the ["Branches" link under the "Review & Launch" section](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-2020-12-14-003/edit/branches?show-errors).
1. Note the red `(i)` icon next to the control branch with the following text:
    > A control branch is required

I have a default control and treatment branch. I think the error is trying to tell me that I am missing a branch name and description for the control branch (but the error message doesn't really imply that). Also curious is that there isnt a matching red `(i)` icon next to the default treatment branch, despite it also missing a branch name and description.

---

![pdehaan_2020-12-14_002_–_Branches___Experimenter](https://user-images.githubusercontent.com/557895/102139863-4b168580-3e13-11eb-9054-1e4f7c913011.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-754)
┆Issue Number: EXP-754

**Comment by lmorchard** [comment]
> I have a default control and treatment branch. 

I think the issue here is that you *don't* actually get these branches created along with the experiment in the database. The server provides this page with a blank control & treatment branch, but they don't really exist yet until this page is saved.

**Comment by jaredlockhart** [comment]
I just got it as:

<img width="1221" alt="Screen Shot 2020-12-16 at 3 19 46 PM" src="https://user-images.githubusercontent.com/119884/102402069-40462700-3fb2-11eb-9169-99a7fefa6ba5.png">

It's not clear what this is referring to?

**Comment by lmorchard** [comment]
This is new behavior, aiming to fix as part of #4289

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

This will be addressed in EXP-978
