### ISSUE TITLE
Next Button should also save when clicked

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4266]
A few users had clicked Next in the UI expecting that it would Save their data, and were surprised that there was data loss. 

As a user, I want to be able to save my data and avoid data loss if I click Next in the UI.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-753)
┆Issue Number: EXP-753

**Comment by lmorchard** [comment]
Duplicate of https://github.com/mozilla/experimenter/issues/4022 ?

**Comment by jodyheavener** [comment]
Yeah, it's cancelled in Jira but not updating here (Wil is trying to fix that)
