### ISSUE TITLE
Change "Create Experiment" on the Create page to "Next"

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4268]
Based on user feedback, the "Create Experiment" button on the "Create New Experiment" page is scary. Users don't know if this will launch the experiment or if it will initiate the recipe flow. 

Proposal is to change "Create Experiment" to  "Next" - "Next" is also more common across the entire UI.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-755)
┆Issue Number: EXP-755

**Comment by pdehaan** [comment]
Possibly related: https://github.com/mozilla/experimenter/issues/4022#issuecomment-745421359

> The consensus is that "Next" will be re-labelled as "Save and Continue" (it must now save and advance to the next page) and "Save" will remain as well (no change).
