### ISSUE TITLE
Expose nimbus isolation group/bucket to admin

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4270]
I wanted to avoid exposing these to the admin to discourage manually intervening in their operation and relying on the automation, but for early testing it looks like we have to go in and futz with them so let's just expose them for the time being in case we need to tweak them.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-758)
┆Issue Number: EXP-758

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

[~jkerim@mozilla.com] I'll leave this for you to sort since you mentioned you might close this anyways.

**Comment by jaredlockhart** [comment]
Actually this didn't end up being needed, so closing.
