### ISSUE TITLE
Ability to set negative % of clients on Nimbus Audience page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4276]
https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-2020-12-15-002b/edit/audience

1. On the Audience page, set the "Percent of clients" to a negative value.
1. Click the Save button.
2. You should get an error message, but the value should be oddly set, meaning you will see the negative value in the [GraphiQL dashboard](https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v5/graphql#query=%7B%0A%20%20experimentBySlug(slug%3A%22pdehaan-2020-12-15-002b%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20owner%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20status%0A%20%20%20%20name%0A%20%20%20%20slug%0A%0A%20%20%20%20proposedDuration%0A%20%20%20%20proposedEnrollment%0A%20%20%20%20populationPercent%0A%20%20%20%20totalEnrolledClients%0A%20%20%20%20firefoxMinVersion%0A%20%20%20%20monitoringDashboardUrl%0A%20%20%20%20startDate%0A%20%20%20%20endDate%0A%20%20%20%20%0A%20%20%7D%0A%7D%0A).
3. 

![pdehaan_2020-12-15_002b_–_Audience___Experimenter](https://user-images.githubusercontent.com/557895/102269239-36002c00-3ed1-11eb-8d6e-09a0533669c2.png)

https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-2020-12-15-002b/request-review

<img width="900" alt="pdehaan_2020-12-15_002b_–_Review___Launch___Experimenter" src="https://user-images.githubusercontent.com/557895/102270234-a0659c00-3ed2-11eb-8e33-f95d74663e0c.png">

So the client side validation thinks it isn't valid (falls below minimum threshold), but the form is still saved, and it clears the informational `(i)` icon beside "Audience" page, and allows me to get into the "Review & Launch" state and submit for approval.

Silly edge case, sure, but might mean something is fishy with our validations.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-762)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15206/Screen+Shot+2021-01-18+at+10.48.00+AM.png">Screen Shot 2021-01-18 at 10.48.00 AM.png</a>
┆Issue Number: EXP-762

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

I don't think this is reproducible anymore. I am unable to save a negative value without an error, and am unable to proceed to the Review page until it's a positive value. Please re-open if you can repro. !Screen Shot 2021-01-18 at 10.48.00 AM.png!

**Comment by LZoog** [comment]
This was cancelled in Jira but the issue wasn't closed in GH.

We'll enforce client-side validation for Audience fields to disallow negative fields in #4615.
