### ISSUE TITLE
Initial Directory View

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4295]
This bug adds an initial directory view that should display Live, Completed, In Review, and Drafts Experiments.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-772)
┆Issue Number: EXP-772

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

no github sync, recreating

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

trying again

**Comment by LZoog** [comment]
This issue was completed with this PR: #4215
