### ISSUE TITLE
Results page doesn't load in Safari browsers

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#4303]
I dunno how much we want to invest in webcompat for internal tools, but e.g. https://experimenter.services.mozilla.com/nimbus/message-homepage-remediation-v2-search-value-props-exper-release-83/results gives a blank page on Firefox iOS, mobile Safari, and desktop Safari.

The desktop Javascript console says:

[Error] SyntaxError: Invalid regular expression: invalid group specifier name (anonymous function) (main.js:2)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-779)
┆Issue Number: EXP-779

**Comment by jodyheavener** [comment]
I haven't verified but I suspect this is due to the usage of a [lookbehind](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/RichText/index.tsx#L9), which turns out to not be [supported](https://caniuse.com/js-regexp-lookbehind) in Safari on mac and iOS.
