### ISSUE TITLE
Order branches in results page with control first

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4308]
The results page is filling up with tons of awesome content and graphs which is awesome :D 

But I just noticed that control is mixed in with the treatment branches, but we should be able to pull it up to the top since the experiment tracks which branch is control.

<img width="280" alt="Screen Shot 2020-12-18 at 12 38 34 PM" src="https://user-images.githubusercontent.com/119884/102643904-f97d3c00-412d-11eb-8e2b-1c0ee97b1256.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-784)
┆Issue Number: EXP-784

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Do we have a link to an experiment where this is happening to reproduce, ideally the one from which this screenshot was taken?

As far as I can tell, the control / reference branch should be appearing first, insofar as the Summary component explicitly sticks it first in the display list: https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/Summary/TableBranches/index.tsx#L25-L28

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Can't seem to repro locally, looked through live & completed experiments on stage & prod and can't find an example of this bug. Maybe it's been fixed since December?

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Looked some more and I think maybe this is already fixed? We can re-open if we have a place where it's reproducible
