### ISSUE TITLE
Improve useCommonForm tests (and/or move some tests out to other files)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4312]
See https://github.com/mozilla/experimenter/pull/4277#discussion_r544277587

We need to mock what's returned by `useCommonForm` to better test that `<FormErrors />`, `formControlAttrs`, and `formSelectAttrs` are all called with the expected field names.

See https://github.com/mozilla/experimenter/commit/8cd3e947413cacbac44edfbb647ff744d5702518 which doesn't work, but that's the general idea. We'll then no longer need the test span in `<Form Errors />`.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-780)
┆Issue Number: EXP-780

**Comment by LZoog** [comment]
Changed the title here - per some discussion in #4420, let's also consider moving the `is used on expected fields` tests from `useCommonForm` into their corresponding form test files.
