### ISSUE TITLE
Missing mutation submission assertions in tests

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4357]
We have tests that submit a form like so:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/PageEditOverview/index.test.tsx#L126-L137

but it ends at asserting that the submit button was clicked but not that the mutations fired off successfully.  So we can break the mutations and this test will still pass, I would expect that if the mutations are broken this test should fail.

Example of a broken mutation:

If the key in this object:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/PageEditOverview/index.tsx#L21

does not match the name in the query:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/gql/experiments.ts#L24

the mutation execute successfully but the check here

https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/PageEditOverview/index.tsx#L44

will fail causing the following lines not to be hit.

I don't know a good way to type check across the query name and the result object, but things were broken in local dev but tests/typechecking were passing.

It's possible even if we mocked out the response with the wrong key the test would still pass but the mutation would still fail in local dev, so it would be nice if we can find a way to test that more rigorously.  It might just need to be an integration test if we can't figure out how to do it in jest.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-797)
┆Issue Number: EXP-797

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

I think our new integration tests cover this now so I will close.
