### ISSUE TITLE
Reorder sections on /nimbus/ page?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4373]
Re: https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/

The current order is:

1. Live Experiments
2. Completed
3. In Review
4. Drafts

I'd argue that "In Review" should probably be second in the list.

Not sure about the ordering of Completed vs Drafts. Since this list isn't personalized to the logged in user, seeing everybody's Drafts together probably makes it the least important item. So I'd imagine a reasonable order is "Live", "In Review", "Completed", then "Drafts".

Although if this page was specific to the logged in user, I'd imagine it might almost be reversed where I'd mostly likely care about my current Draft experiments, then In Review, then Live, then Completed.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-806)
┆Issue Number: EXP-806

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Closing in favor of https://jira.mozilla.com/browse/EXP-1004
