### ISSUE TITLE
Live experiments have no end date?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4374]
Probably a gross misunderstanding by me, but I thought this was interesting...

Currently we only have 1 live experiment on Staging:
![Experiments___Experimenter](https://user-images.githubusercontent.com/557895/103932048-20e47a80-50d6-11eb-8a85-ec02c33a19cc.png)

https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/test-cfr-experiment

You can see from the screenshot that we're enrolling from Nov 13-23, and have an end date of Nov 23.
Yet, when I click on that live experiment to go to the details page, I don't see an end date on the timeline, therefore the timeline looks like a big gray `<hr/>` versus a progress bar of sorts.

Now I'm confused why it simultaneously has and doesn't have an `endDate`, so I revert to looking through [the GraphiQL dashboard](https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v5/graphql#query=%7B%0A%20%20experimentBySlug(slug%3A%22test-cfr-experiment%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20owner%20%7B%0A%20%20%20%20%20%20username%0A%20%20%20%20%7D%0A%20%20%20%20status%0A%20%20%20%20name%0A%20%20%20%20slug%0A%20%20%20%20proposedDuration%0A%20%20%20%20proposedEnrollment%0A%20%20%20%20startDate%0A%20%20%20%20endDate%0A%20%20%20%20%0A%20%20%7D%0A%7D%0A):

```graphql
{
  experimentBySlug(slug:"test-cfr-experiment") {
    id
    owner {
      username
    }
    status
    name
    slug
    proposedDuration
    proposedEnrollment
    startDate
    endDate
    
  }
}
```

Which spits out this (with `endDate: null`):

```json
{
  "data": {
    "experimentBySlug": {
      "id": 29,
      "owner": {
        "username": "aoprea@mozilla.com"
      },
      "status": "LIVE",
      "name": "test-cfr-experiment",
      "slug": "test-cfr-experiment",
      "proposedDuration": 10,
      "proposedEnrollment": 10,
      "startDate": "2020-11-13T18:49:10.379319+00:00",
      "endDate": null
    }
  }
}
```

Or maybe the question is why is the homepage showing an `endDate` if the `endDate` via GraphQL is `null`?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-807)
┆Issue Number: EXP-807

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/pull/4672
