### ISSUE TITLE
Audience page valid save, next button is disabled

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4377]
I just noticed you can save the audience page, have all the fields be marked as valid and the save succeeds, but the next button is disabled:

<img width="1200" alt="Screen Shot 2021-01-08 at 10 43 39 AM" src="https://user-images.githubusercontent.com/119884/104034146-8308b280-519e-11eb-9550-d6e3a99e73cb.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-811)
┆Issue Number: EXP-811

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

1) The missing field here is expected number of clients, which has been added to the required list

2) The 'save and continue' button is now never disabled

I think this has been addressed.
