### ISSUE TITLE
Results Page Doesn't Load

### ISSUE THREAD

**Issue by emtwo** [mozilla/experimenter#4379]
E.g. `Attribution Targeting Release AA Test` is in the "completed" tab. When I click `results` on the right for it, it redirects to the design page.

I think this is a regression starting in https://github.com/mozilla/experimenter/commit/c756d99b35cc0ddf2cb3d390a08329c4eeb0867e as it seems to work fine locally when I tested in an earlier commit.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-812)
┆Issue Number: EXP-812

**Comment by LZoog** [comment]
I think this is occurring because it's not actually waiting for the analysis results before redirecting, the user should be redirected if the results aren't available, but you can see the sidebar go from "could not load data" to loading it and enabling of "results" link.
