### ISSUE TITLE
Separate analysis logic into new AppLayout

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4398]
With some recent PRs/work around the Results/Design page, `AppLayoutWithExperiment` has become a little bloated with logic around handling the analysis/visualization data when it's only needed on the Results/Design page.

Creating an`AppLayoutWithAnalysis` (or better named) to handle that logic and use on those pages would be cleaner.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-816)
┆Issue Number: EXP-816

**Comment by LZoog** [comment]
Closing this, was done in #4414
