### ISSUE TITLE
Add Nimbus global navigation?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4427]
As a user, if I navigate directly to an experiment, there isn't any global navigation or anything to take you back to the /nimbus/ homepage (apart from tweaking URI)

For example, https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/fenix-bookmark-icon

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-833)
┆Issue Number: EXP-833

**Comment by LZoog** [comment]
This can probably be marked as a dupe of #3972, and relates to #4444

**Comment by LZoog** [comment]
#3972 has been thrown into the next train starting today, closing this as a dupe.
