### ISSUE TITLE
Remember last active tab on Nimbus homepage

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4428]
When you click to an experiment from the homepage directory and then navigate back you are taken to the first available tab, which is currently “Active”. This is confusing and annoying.

Update the homepage directory to “remember” the last tab you were on when you left. I think we have two options for this:

* When the tab changes, update the location hash, and check for the hash on page load.
* This would also allow you to link directly to a tab.
* If you want to get really fancy, use Reach Router or fire a push state so that it updates the path instead of the hash.

* Local storage; when the tab changes store it, and check for it on page load.

I imagine the first option would be best. Either option should allow you to change to the non-first tab in the homepage directly, click to an experiment page, and then click back and be back on the tab you left from.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-834)
┆Issue Number: EXP-834

**Comment by jodyheavener** [comment]
I think we have two options for this:

- Make tab change update location hash, and check for the hash on page load. I prefer this method.
  - This would also allow you to link directly to a tab
- Local storage; when the tab changes store it, and check for it on page load
