### ISSUE TITLE
Primary and Secondary probset types should be consolidated

### ISSUE THREAD

**Issue by emtwo** [mozilla/experimenter#4433]
The types are kind of long, e.g. `(getExperiment_experimentBySlug_secondaryProbeSets | null)[] | null;`

It would be best to have them defined in one place and used everywhere.

This is a follow-up from https://github.com/mozilla/experimenter/pull/4414#discussion_r557791995

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-838)
┆Issue Number: EXP-838

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

ProbeSets are extinct, but scientists have cloned and resurrected them in ProbeSet Park, though I hear they escaped their paddocks and are roaming the island freely.  Someone call Samuel Jackson to take care of it please.
