### ISSUE TITLE
We don't need to expose the single pref option any more in experimenter

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#4437]
This is a paper cut UI issue - of removing the option for single pref flips - since we are fully migrated over to only using the multipref code on the back end (even if it is a one pref change).

Not critical - if it introduces any weirdness (like with cloning impact).  But if it's easy to remove - it would remove a hiccup someone gets stuck on every few weeks.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-844)
┆Issue Number: EXP-844

**Comment by tiftran** [comment]
hey @shell1, was wondering if I could get more detail in why/how people get stuck, maybe it might be easier to fix than gutting stuff out? Currently as is, if a user selects the single pref option, it should still output a multipref recipe, (unless there's a bug that I'm not aware of... correct me if there is 🙂 )

if we do go forward with removing the single pref option, it would also make sense to remove the single branch addon option as well?
