### ISSUE TITLE
Summary view should link to results view

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#4444]
Experiment summary views currently do not link to the results view; e.g. https://experimenter.services.mozilla.com/nimbus/onoff-aboutwelcome-experiment does not link to https://experimenter.services.mozilla.com/nimbus/onoff-aboutwelcome-experiment/results.

I think linking the results view from the summary view would facilitate discoverability.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-847)
┆Issue Number: EXP-847

**Comment by LZoog** [comment]
Related / could be done at the same time: #3972

**Comment by LZoog** [comment]
#3972 has been thrown into the next train starting today, closing this as a dupe.
