### ISSUE TITLE
User feedback - Defining branches in ratios is confusing

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#4449]
In a Jan 19 Experiment review meeting, Punam brought up that DS defined branch sizes in percentages (e.g. 40% control, 20%, treatment-1, etc.) and wasn't sure if converting to ratios would introduce errors. No blocker, just more of a UX hiccup/feeling of lack of confidence

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-851)
┆Issue Number: EXP-851

**Comment by lmorchard** [comment]
Would it be better if we had some kind of UX that used percentages and enforced a 100%-total requirement between all the ratio fields? 

If so, maybe something like... the control branch ratio is not editable, but it's the remaining % of users not taken up by other branches?
