### ISSUE TITLE
[nimbus] alternating row colors on summary tables makes it tricky to scan

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4454]
Per my comment in the [`EXP-648`](https://jira.mozilla.com/browse/EXP-648) _"I want to be able to see branches and full audience information on the Summary/Design Page"_ Epic:

> Only immediate issue I noticed was that the Figma specs didn't specify alternating colored row backgrounds for the various tables, but the current tables have alternating white/grey colored backgrounds.
>
> <img width="819" alt="_EXP-648__I_want_to_be_able_to_see_branches_and_full_audience_information_on_the_Summary_Design_Page_-_Jira" src="https://user-images.githubusercontent.com/557895/105214256-9d2e8300-5b04-11eb-80f8-d6e19a47383b.png">

Re: https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/browser-settings-attr-targeting-test

Personally, I feel that when every single line in the page/tables alternate, it really loses the effect of highlighting important information. The table rows already have borders to make it easier to scan the row heading/label vs the content (since each table has horizontal based `label:value` layouts). I think the only place where the colored header makes sense is in the "Branches" table, where we have a table header for the branch name (see "control" and "treatment" below):

<img width="790" alt="browser_settings_attr_targeting_test___Experimenter" src="https://user-images.githubusercontent.com/557895/105214690-2f368b80-5b05-11eb-9007-01ebfb2c485a.png">

But, because not only the header row has a background, but EVERY row, it makes it much harder to visually distinguish the important row headers.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-854)
┆Issue Number: EXP-854

**Comment by pdehaan** [comment]
Possibly a better explanation...

If I remove the `.table-striped` from the table, and move the branch label row into a more semantically correct `<thead>`; something like this:

```html
<thead class="thead-light">
  <tr>
    <th colspan="2" data-testid="branch-name">control</th>
  </tr>
</thead>
```

... then it makes it a bit easier to read (maybe, maybe not, what do I know).

<img width="747" alt="browser_settings_attr_targeting_test___Experimenter" src="https://user-images.githubusercontent.com/557895/105215409-17abd280-5b06-11eb-8fcc-716f598dd1b6.png">

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~amedinac@mozilla.com] do you want alternating row colors?

**Comment by AnaMedinac** [comment]
@pdehaan thanks for raising this - Let's go with your proposed solution. @LZoog Is it an easy update?

**Comment by LZoog** [comment]
@AnaMedinac Should be! :)
