### ISSUE TITLE
snakeToCamelCase in CommonForm hook causing submit errors not to be displayed in Storybook

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4455]
I _think_ this is just affected in Storybook, but this PR: https://github.com/mozilla/experimenter/pull/4363/commits

Looks like this in Storybook: https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/763dba338f9bd679780a700bca1eb2ea151f2674/nimbus-ui/index.html?path=/story/components-formaudience--server-submit-errors

Before this commit, the errors were displayed: https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/2c6ea4a0c67bb5e48852d301fd8fec0d5bb2f74a/nimbus-ui/index.html?path=/story/components-formaudience--server-submit-errors

This is also the case in our other forms.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-855)
┆Issue Number: EXP-855

**Comment by lmorchard** [comment]
Yeah, I think camelCase submit error keys stories would need to be fixed in this case - the submit errors are snake_case from the server.
