### ISSUE TITLE
Flaky console error in DirectoryTable test

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4459]
Low priority unless this starts creeping up in CI, but I noticed yesterday at least twice when running `nimbus-ui` tests that this console error would pop up.

Seems like `slug: `some-experiment-${Math.round(Math.random() * 100)}` sometimes ends up producing the same number. Didn't poke at the code but it's probably more ideal to use something like a uuid here, or maybe just increasing the number is good enough.

```
    console.error ../../node_modules/react-dom/cjs/react-dom.development.js:88
      Warning: Encountered two children with the same key, `some-experiment-21`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
          in tbody (at DirectoryTable/index.tsx:120)
          in table (at DirectoryTable/index.tsx:94)
          in div (at DirectoryTable/index.tsx:93)
          in DirectoryTable (at DirectoryTable/index.tsx:190)
          in DirectoryCompleteTable (at PageHome/index.tsx:47)
          in div (at PageHome/index.tsx:46)
          in div (created by TabPane)
          in Transition (created by Fade)
          in Fade (created by TabPane)
          in TabPane (created by Tabs)
          in div (created by ForwardRef)
          in ForwardRef (created by Tabs)
          in TabContainer (created by Tabs)
          in Tabs (at PageHome/index.tsx:38)
          in Body (at PageHome/index.tsx:77)
          in div (at AppLayout/index.tsx:16)
          in main (created by Container)
          in Container (at AppLayout/index.tsx:15)
          in AppLayout (at PageHome/index.tsx:61)
          in PageHome (at PageHome/index.test.tsx:48)
          in ApolloProvider (at mocks.tsx:214)
          in MockedCache (at PageHome/index.test.tsx:47)
          in Subject (at PageHome/index.test.tsx:55)
```

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-858)
┆Issue Number: EXP-858

**Comment by pdehaan** [comment]
> ```js
> slug: `some-experiment-${Math.round(Math.random() * 100)}`
> ```

Do we need to use `Math.round()` here? I think currently we'd have a 1-in-100 chance of getting a key collision, but if we just use a key like `some-experiment-0.210343536354455`, that %% probably drops considerably (although collisions are still not impossible). Or, yeah, UUIDs would do the trick.
