### ISSUE TITLE
Nested form submit errors not clearing onchange

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4485]
Noticed while working on EXP-771 / #4299 that this was happening. On `Branches` (and potentially around Additional Links when that work is merged), submit errors don't clear on change.

I have a solution WIP, but it's not as trivial as I was hoping due to the indexing/multiple treatment branches, so I think it should be done in a separate issue.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-876)
┆Issue Number: EXP-876

**Comment by LZoog** [comment]
Had a comment on "potentially" affecting Additional Links but it definitely does, per https://github.com/mozilla/experimenter/pull/4480#pullrequestreview-578825888 / https://github.com/mozilla/experimenter/pull/4480#pullrequestreview-579365330. Bumping this up from a 2 to a 3, I think the solution for Branches might look slightly different than Additional Links

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

I'd like to finish this now, but I'm bumping this out of the sprint as well as out of Palm due to much higher priority tasks taking precedence. Leaving myself some notes...

I still have a WIP branch, but I'm running into a rendering issue in Branches/Branch after resetting submit errors where the submit error is clearing, but because `errors` are passed into each `FormBranch`, `FormBranch` is rerendering and `formControlAttrs` in `useCommonNestedForm`/`useCommonForm` is getting hit a bunch of times and it resets the `defaultValue` which means any time it clears, the default value is displayed in the input. I've tried a couple things without luck so far (mostly trying to `useEffect` or `useLayoutEffect` in one of the hooks) but haven't gotten it working + my resetting error approach could use a little cleanup.

Also, I'm not seeing submit errors getting displayed under Additional Links. We don't appear to be using the same URL-check server-side as we are on risk mitigation link and when I take out the client-side validation I can't seem to coerce submit errors to show, but it's making me scratch my head since I left a comment in https://github.com/mozilla/experimenter/pull/4480#pullrequestreview-578825888 which appeared to show them. Unless I'm mistaken might need to stick some server-side validation there (might need a separate issue filed), but the solution here should fix any onChange clearing.
