### ISSUE TITLE
Move common form validation objects to their own home

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4520]
We have a handful of form field validation objects squatting in the [constants file](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/lib/constants.ts). Time to give them their own home, perhaps a `forms.ts` that could include other common form things. Maybe this lives adjacent to the useCommonForm hook files, or maybe in the lib/ directory? Not sure.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-896)
┆Issue Number: EXP-896

**Comment by lmorchard** [comment]
I know I kind of advocated early on for a general `hooks/` folder separate from `lib/`. But, as we've done more shared form stuff, it might even make sense to wrangle all of that into one module - hooks, constants, and all. Maybe `lib/forms.ts`? Don't want to bikeshed on it too intensely.
