### ISSUE TITLE
favicons are unfabulously large

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4522]
Per https://pdehaan.github.io/repo-lint-www/repo/mozilla/experimenter/

- [app/experimenter/legacy-ui/imgs/favicon.ico](https://github.com/mozilla/experimenter/blob/main/app/experimenter/legacy-ui/imgs/favicon.ico) — 100644; 361.4KB
- [app/experimenter/nimbus-ui/public/favicon.ico](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/public/favicon.ico) — 100644; 361.4KB

361 KB for a favicon seems pretty... unnecessary for a 256x256 1 color logo. Presumably it was just an converted+unoptimized legacy-ui asset that got copied over into new Nimbus flow, and bandwidth is cheap, but should be an easy fix.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-902)
┆Issue Number: EXP-902

**Comment by jaredlockhart** [comment]
I CAN'T GET ANYTHING PAST YOU

**Comment by pdehaan** [comment]
#wontfix
