### ISSUE TITLE
react-select is defined in root app/package.json file

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4524]
Per https://pdehaan.github.io/repo-lint-www/repo/mozilla/experimenter/

> ### package.json
>
> - [app/experimenter/legacy-ui/core/package.json](https://github.com/mozilla/experimenter/blob/main/app/experimenter/legacy-ui/core/package.json) — 100644; 3.06KB
> - [app/experimenter/nimbus-ui/package.json](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/package.json) — 100644; 3.59KB
> - [app/package.json](https://github.com/mozilla/experimenter/blob/main/app/package.json) — 100644; 502B

Looks like we have 3 package.json files in the repo (so far so good). But it gets a bit weird that we have **react-select** nested at app/package.json (which is the only dependency/devDependency defined in that file):

https://github.com/mozilla/experimenter/blob/cf8ba055022f36bf63fddb32fbd8d86ee51eda1d/app/package.json#L9-L11

Not sure if we can just delete it. Seems like we already have it defined in both other package.json files 
https://github.com/mozilla/experimenter/blob/cf8ba055022f36bf63fddb32fbd8d86ee51eda1d/app/experimenter/legacy-ui/core/package.json#L44
https://github.com/mozilla/experimenter/blob/cf8ba055022f36bf63fddb32fbd8d86ee51eda1d/app/experimenter/nimbus-ui/package.json#L51-L52

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-900)
┆Issue Number: EXP-900

**Comment by jaredlockhart** [comment]
I had to put it in there otherwise weirdness happened:

https://github.com/mozilla/experimenter/pull/4166/files#r539600282

But if someone can figure out a way to do this more properlyer, I'm all for it 👍

**Comment by pdehaan** [comment]
Closing as "as-designed".
