### ISSUE TITLE
Serializer return `null` for Mobile experiments if targeting is empty

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4542]
This is a blocker on the Nimbus Rust SDK being able to target users for the nightly launch

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-913)
┆Issue Number: EXP-913

**Comment by lmorchard** [comment]
Found a hitch with setting this to null - it fails to validate against the shared schema type:

https://github.com/mozilla/nimbus-shared/blob/main/types/experiments.ts#L72

I think I can remove it from the object and leave it undefined, which passes validation.

But, does that work as expected for the SDK?
