### ISSUE TITLE
Value field is required for features

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#4543]
Not all features have values, it should be possible to select a feature and make it enable/disabled without setting a value.

Some scenarios for the **feature** property inside branches:

**When the aboutwelcome feature is selected and enabled, with no value**
【 highlighted #d4d4d4 】{【 end highlighted 】
【 highlighted #9cdcfe 】"featureId"【 end highlighted 】【 highlighted #d4d4d4 】: 【 end highlighted 】【 highlighted #ce9178 】"aboutwelcome"【 end highlighted 】【 highlighted #d4d4d4 】,【 end highlighted 】
【 highlighted #9cdcfe 】"enabled"【 end highlighted 】【 highlighted #d4d4d4 】: 【 end highlighted 】【 highlighted #569cd6 】true【 end highlighted 】【 highlighted #d4d4d4 】,【 end highlighted 】
【 highlighted #9cdcfe 】"value"【 end highlighted 】【 highlighted #d4d4d4 】: 【 end highlighted 】【 highlighted #569cd6 】null【 end highlighted 】
【 highlighted #d4d4d4 】}【 end highlighted 】
**When the aboutwelcome feature is selected and disabled, with no value**
【 highlighted #d4d4d4 】{【 end highlighted 】
【 highlighted #9cdcfe 】"featureId"【 end highlighted 】【 highlighted #d4d4d4 】: 【 end highlighted 】【 highlighted #ce9178 】"aboutwelcome"【 end highlighted 】【 highlighted #d4d4d4 】,【 end highlighted 】
【 highlighted #9cdcfe 】"enabled"【 end highlighted 】【 highlighted #d4d4d4 】: 【 end highlighted 】【 highlighted #569cd6 】true【 end highlighted 】【 highlighted #d4d4d4 】,【 end highlighted 】
【 highlighted #9cdcfe 】"value"【 end highlighted 】【 highlighted #d4d4d4 】: 【 end highlighted 】【 highlighted #569cd6 】null【 end highlighted 】
【 highlighted #d4d4d4 】}【 end highlighted 】

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-914)
┆Issue Number: EXP-914

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Is there a particular feature where the value is unexpectedly required where it shouldn't be?

I think we hide the value field if the schema for the feature value is null - but if the selected feature has a non-null schema, we show the field & require it.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

From a Slack convo ( https://mozilla.slack.com/archives/CANCHH6R1/p1614724756230600 ), it seems that we do have optional feature values but what we don't have are any features generated in dev by the factories to produce a null-schema feature that would exercise the optional feature value validation. Going to resolve this issue by tweaking the data factories so that this happens and it's possible to easily try out an optional feature value.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

bq. but what we don't have are any features generated in dev by the factories to produce a null-schema feature

Looking further, it seems the opposite is true, so I'm confused now. But will try to ensure we have both feature configs with schemas and some with null schema and ensure that feature value is optional for the null-schema case.
