### ISSUE TITLE
Removed FF min version values breaking experiments

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4546]
[~pdehaan@mozilla.com] discovered that his [experiment](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/test-cfr-experiment) wasn't loading, and it looked like it was because his firefoxMinVersion was set to 80, which was [recently removed](https://github.com/mozilla/experimenter/pull/4486).

`> Expected a value of type \"NimbusExperimentFirefoxMinVersion\" but received: 80.!`

We soon realized that many experiments in [stage](https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v5/graphql#query=%7B%0A%20%20experiments(limit%3A100)%20%7B%0A%20%20%20%20id%0A%20%20%20%20owner%20%7B%0A%20%20%20%20%20%20email%0A%20%20%20%20%7D%0A%20%20%20%20status%0A%20%20%20%20name%0A%20%20%20%20slug%0A%20%20%20%20publicDescription%0A%20%20%20%20firefoxMinVersion%0A%0A%20%20%7D%0A%7D%0A) and [production](https://experimenter.services.mozilla.com/api/v5/graphql#query=%7B%0A%20%20experiments(limit%3A100)%20%7B%0A%20%20%20%20id%0A%20%20%20%20owner%20%7B%0A%20%20%20%20%20%20email%0A%20%20%20%20%7D%0A%20%20%20%20status%0A%20%20%20%20name%0A%20%20%20%20slug%0A%20%20%20%20publicDescription%0A%20%20%20%20firefoxMinVersion%0A%0A%20%20%7D%0A%7D%0A) cannot load because they use versions that were deprecated.

Since bumping up the minimum version of or "no version"ing the broken experiments would invalidate them we should probably reinstate those older versions. Additionally, we should probably update the query to return the value from the DB and not use an enum, so when a version is removed it doesn't tank the experiment.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-915)
┆Issue Number: EXP-915

**Comment by pdehaan** [comment]
Ref: https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/test-cfr-experiment

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/106956787-f6dda280-66eb-11eb-9ba9-1417945ffacb.png)

[GraphiQL for `experimentBySlug(slug:"test-cfr-experiment") {...}`](https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v5/graphql#query=%7B%0A%20%20experimentBySlug(slug%3A%22test-cfr-experiment%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20owner%20%7B%0A%20%20%20%20%20%20email%0A%20%20%20%20%7D%0A%20%20%20%20status%0A%20%20%20%20name%0A%20%20%20%20slug%0A%20%20%20%20publicDescription%0A%20%20%20%20firefoxMinVersion%0A%0A%20%20%7D%0A%7D%0A) returns:

```json
{
  "errors": [
    {
      "message": "Expected a value of type \"NimbusExperimentFirefoxMinVersion\" but received: 80.!",
      "path": [
        "experimentBySlug",
        "firefoxMinVersion"
      ]
    }
  ],
  "data": {
    "experimentBySlug": {
      "id": 29,
      "owner": {
        "email": "aoprea@mozilla.com"
      },
      "status": "LIVE",
      "name": "test-cfr-experiment",
      "slug": "test-cfr-experiment",
      "publicDescription": "Testing cfr rapid experiments",
      "firefoxMinVersion": null
    }
  }
}
```

**Comment by pdehaan** [comment]
[Internal Slack thread](https://mozilla.slack.com/archives/CANCHH6R1/p1612470789184200)

Sounds like older versions should never be removed since it can break things unexpectedly. But I'm not sure what that looks like, since we don't want to keep "Firefox 80" permanently pinned to the top of a `<select>` field when we're currently on Firefox 103.0.2. Not sure if there is a way to hide older versions (prior to the current Release/ESR channel version) but still have them available for older experiments that targeted them.

**Comment by jodyheavener** [comment]
My thinking is we could have an enum of "current" versions provided through the config to populate the <select>, but use the value directly from the DB for the query. So the enum can be constantly changing while the stored value can do its own thing.

**Comment by jaredlockhart** [comment]
Oh yeah @jodyheavener that's not a bad idea, having two enums.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Can't find the PR from a quick search but I remember this being addressed and the link in the original issue comment now works.
