### ISSUE TITLE
It’s hard to tell the difference between prod and staging

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4550]
Not sure if we should maybe add a clear header for Nimbus Experimenter which says "STAGE" or "PRODUCTION" or include slightly different colored backgrounds so somebody doesn't try adding dummy experiments to production or whatnot.

Ref: https://mozilla.slack.com/archives/C011MC5EB0V/p1612545581014000 and https://mozilla.slack.com/archives/C011MC5EB0V/p1612546090015200

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-918)
┆Issue Number: EXP-918

**Comment by k88hudson** [comment]
We ran into a situation with this where we accidentally requested a review on a test experiment in production, so I think it would be worth discussing this (or other ways to mitigate that) sooner than later

**Comment by k88hudson** [comment]
Could we do.... bootstrap dark theme :P
