### ISSUE TITLE
Grafana doesn't work for fenix experiments, should we link?

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4576]
There's a live Fenix experiment in nimbus right now, and we display the grafana link, but it won't have any data since it's collected in different data stores.  Until we have proper monitoring for fenix experiments, should we disable the grafana link and maybe indicate that fenix experiments doens't have first class monitoring support?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-930)
┆Issue Number: EXP-930

**Comment by data-sync-user** [comment]
➤ Tim Smith commented:

Grafana works for Fenix experiments now, when Fenix has an SDK version that sends enrollment events.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

[~tismith@mozilla.com] just confirming - is this issue outdated now?

**Comment by data-sync-user** [comment]
➤ Tim Smith commented:

I believe it's outdated, yeah. I wasn't sure about the situation wrt release but the next version of the SDK in release will definitely have these events now. Closed wontfix~
