### ISSUE TITLE
Remove project urls/views/templates

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#458]
There's no strong planned use case for projects so let's just remove the urls, pages, tests, etc for now.

**Comment by ramitsawhney27** [comment]
Is this issue something I can work on? This would be my first time contributing and I'd love to get involved.

**Comment by jaredkerim** [comment]
@ramitsawhney27 Hi yes this is something you can work on, thank you!  Let me add more context:  I want to keep the Project model around because we are currently using it to allow for filtering experiments based on projects, but all of the user facing elements are out of date and not being used.  So in specific, the following should be removed:

- The root url https://github.com/mozilla/experimenter/blob/master/app/experimenter/urls.py#L13
- The project form https://github.com/mozilla/experimenter/blob/master/app/experimenter/projects/forms.py#L31
- The project urls file https://github.com/mozilla/experimenter/blob/master/app/experimenter/projects/urls.py
- The project views file https://github.com/mozilla/experimenter/blob/master/app/experimenter/projects/views.py
- The tests here https://github.com/mozilla/experimenter/blob/master/app/experimenter/projects/tests/test_forms.py
- And here https://github.com/mozilla/experimenter/blob/master/app/experimenter/projects/tests/test_views.py


Please run `make check` before committing, this will automatically run all tests, linting, and code auto formatting.  Thanks!

**Comment by jaredkerim** [comment]
I'm not sure what the future of projects is.  @shell1 What do you think?  Should we expand Projects or kill them?

**Comment by shell1** [comment]
kill for now.  definitely can see the the ability to filter like items together - but this is something we can do "en masse" down the road.  And having clear groupings might be easier in hind sight as well.  This all seems to be shaking out now.  there are different "areas" and also different "KPIs" impacted and just many ways folks are slicing and dicing project work.  Let's wait to see how that lands and can take an improvement if a need & direction is clearer in future.

**Comment by jaredkerim** [comment]
We need to actually remove this code to free up the ability to meaningfully use the word 'project' in the future.
