### ISSUE TITLE
Generate bucketing at review time rather than accepted time

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4580]
To allow users to review an experiments DTO as early as possible, we should generate the bucket allocations for an experiment when it moves into `REVIEW` rather than `ACCEPTED`.  Detailed instructions:

https://github.com/mozilla/experimenter/pull/4573#pullrequestreview-585919933

Additionally, we should make the DTO URL a property on NimbusExperiment and expose it through the GQL API so that it doesn't need to be conditionally generated on the frontend.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-933)
┆Issue Number: EXP-933

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Should this be PREVIEW as well as per https://jira.mozilla.com/browse/EXP-628 ? A missing bucketing config will not allow the test experiment to enroll
