### ISSUE TITLE
Results sidebar loads on Design page when Results are available

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4585]
https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/multi-stage-onboarding-set-default-v42-experiment/

Click the fancy new "Go to Design" navigation near the top. This should take you to https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/multi-stage-onboarding-set-default-v42-experiment/design

<img width="820" alt="Multi-Stage_Onboarding__Set_Default_v4_2_Experiment___Experimenter" src="https://user-images.githubusercontent.com/557895/107425681-24ec2980-6ad4-11eb-866f-fac9f4d1d8ab.png">

Note, clicking any of the side navigation under "Results" seems to be a noop and append an invalid anchor to the URL (ie: "#tagged_search_count"). My guts are telling me that it's because my page slug is still ./design and those sidebar links should be going to ./results#slugy-slug. A theory which might be confirmed by the fact I can click on that "Results" heading to go to the ./results page, and then clicking on the other subnav seems to work.

<img width="814" alt="Multi-Stage_Onboarding__Set_Default_v4_2_Experiment_–_Design___Experimenter" src="https://user-images.githubusercontent.com/557895/107425970-844a3980-6ad4-11eb-8a7b-32b9f32a55f1.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-936)
┆Issue Number: EXP-936

**Comment by pdehaan** [comment]
@jodyheavener Possible fallout from recent #4530 PR.

**Comment by LZoog** [comment]
Oooh, the Results sidebar shouldn't actually load on the Design page. It should just enable the link.

**Comment by LZoog** [comment]
I think the title for this issue should be, "Results sidebar loads on Design page when Results are available" because I think that's the real bug here

**Comment by pdehaan** [comment]
@LZoog Are you saying that sidebar should only have "Design" + "Results" and the results subnav should only be visible when you're actively on the "Results" page?

**Comment by jodyheavener** [comment]
That or the subnav should know when you're _not_ on the Results page and update its link to be `/results#whatever` instead of just `#whatever`

**Comment by LZoog** [comment]
@pdehaan Right, if you're on the Design page, we do query to see if results are available, but if they are, the link should be enabled. If they're not, it's disabled with a message. The sidebar with all the fancy links should only show if you're on the Results page.

Also, I think we need to update Storybook, the Design page doesn't show the correct sidebar and we're missing a state or two in there for this scenario and if Results are unavailable.

**Comment by LZoog** [comment]
> That or the subnav should know when you're not on the Results page and update its link to be /results#whatever instead of just #whatever

Yeah, I figured we shouldn't show all the sublinks unless you were on the Results page, but I'm also fine with this (we could ask Ana which is preferred?)

**Comment by LZoog** [comment]
@AnaMedinac, if a user is on the Design page and Results are available, would you prefer that we show the full Results sidebar, or just enable the link to Results?

also cc @emtwo for awareness

**Comment by AnaMedinac** [comment]
I sort of like the Results side bar being enabled on the Design page. I assume that as we start building out some of the monitoring work, users might be switching back and forth often.
