### ISSUE TITLE
Test editCommonRedirects, remove duplicate redirect tests from PageEdit* components

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4586]
We have a bunch of code testing that certain pages redirect to other pages based on its status. Some examples:

* [https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/PageEditAudience/index.test.tsx#L85:L113](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/PageEditAudience/index.test.tsx#L85:L113)
* [https://github.com/mozilla/experimenter/blob/jh/4425/end-exp-ui/app/experimenter/nimbus-ui/src/components/PageEditBranches/index.test.tsx#L63:L91](https://github.com/mozilla/experimenter/blob/jh/4425/end-exp-ui/app/experimenter/nimbus-ui/src/components/PageEditBranches/index.test.tsx#L63:L91)

This is repeated throughout each PageEdit component. Instead of these duplicate tests we can just test [editCommonRedirects](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/lib/experiment.ts#L43-L51). Doing so would allow us to remove the duplicate tests.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-937)
┆Issue Number: EXP-937

**Comment by jodyheavener** [comment]
Fixed in #4608
