### ISSUE TITLE
Add pagination to GraphQL GET_EXPERIMENTS_QUERY

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4588]
Currently we only fetch a hardcoded 50 results from GraphQL. Might be time to add some sorting+pagination.
Potentially related Slack conversation: https://mozilla.slack.com/archives/C011MC5EB0V/p1612884360035700

https://github.com/mozilla/experimenter/blob/2a73bb1c62ba3f165b1922755c0dafac86452f6f/app/experimenter/nimbus-ui/src/gql/experiments.ts#L194-L197

Not sure if we bump the `limit` up to 100 or something in the meantime.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-939)
┆Issue Number: EXP-939

**Comment by pdehaan** [comment]
More pagination conversations happening in https://mozilla.slack.com/archives/CANCHH6R1/p1612975177299300 (back end vs front end filtering; general payload size of 3.1kB for 50 experiments, etc).

**Comment by jodyheavener** [comment]
You're beating me to filing my epic issues 😂

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Canceling because we're doing it all in the client now
