### ISSUE TITLE
Add experiment created timestamp to the experiment GraphQL resolver?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4593]
Per https://mozilla.slack.com/archives/CANCHH6R1/p1612975177299300 conversation.

Currently we only fetch 50 experiments; [until we add pagination](https://github.com/mozilla/experimenter/issues/4588).

But from what I can tell by looking through the [GraphiQL dashboard](https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v5/graphql#query=%7B%0A%20%20experiments(limit%3A%2050)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20owner%20%7B%0A%20%20%20%20%20%20username%0A%20%20%20%20%7D%0A%20%20%20%20slug%0A%20%20%20%20startDate%0A%20%20%20%20%23%20proposedDuration%0A%20%20%20%20%23%20proposedEnrollment%0A%20%20%20%20%23%20endDate%0A%20%20%20%20status%0A%20%20%20%20%23%20monitoringDashboardUrl%0A%20%20%20%20%23%20featureConfig%20%7B%0A%20%20%20%20%23%20%20%20slug%0A%20%20%20%20%23%20%20%20name%0A%20%20%20%20%23%20%7D%0A%20%20%7D%0A%7D%0A), the experiments aren't really sorted in any logical order (I'm using the experiment's `id` property -- which I assume is a primary key of sorts -- and it seems like my current experiment order is 32 -> 25 -> 31 -> 29 -> 28 -> 10 -> 205 -> 168…).

https://github.com/mozilla/experimenter/blob/2a73bb1c62ba3f165b1922755c0dafac86452f6f/app/experimenter/nimbus-ui/src/gql/experiments.ts#L194-L214

It might be nice to have the experiment created date as a field. Or maybe the problem is more that the data should be sorted server side before being proxied through GraphQL.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-941)
┆Issue Number: EXP-941

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Quick update: Ana informed me that sorting is going to be handled later, separate from paginating, so I'm going to bump this out of EXP-944. And for anyone looking down the road, we removed the 50-experiment limit on the home page.
