### ISSUE TITLE
Confusing behavior around experiment ending dates

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4594]
Currently on [stage](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus) we have 3 Live experiments:

<img width="1157" alt="Experiments___Experimenter" src="https://user-images.githubusercontent.com/557895/107549830-2164ab00-6b85-11eb-8b25-80c48710d77f.png">

Note that each experiment lists an ending date (Nov 23, 2020, Jan 4, and Jan 11 respectively).

But if I click on any of the experiments and go to the [details page](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/test-cfr-experiment), I don't see any of those end dates.

<img width="1155" alt="test-cfr-experiment___Experimenter" src="https://user-images.githubusercontent.com/557895/107550467-eb73f680-6b85-11eb-83b0-4582985b2157.png">

The [GraphiQL dashboard](https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v5/graphql#query=%7B%0A%20%20experimentBySlug(slug%3A%20%22test-cfr-experiment%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20owner%20%7B%0A%20%20%20%20%20%20username%0A%20%20%20%20%7D%0A%20%20%20%20slug%0A%20%20%20%20startDate%0A%20%20%20%20%23%20proposedDuration%0A%20%20%20%20%23%20proposedEnrollment%0A%20%20%20%20endDate%0A%20%20%20%20status%0A%20%20%20%20%23%20monitoringDashboardUrl%0A%20%20%20%20%23%20featureConfig%20%7B%0A%20%20%20%20%23%20%20%20slug%0A%20%20%20%20%23%20%20%20name%0A%20%20%20%20%23%20%7D%0A%20%20%7D%0A%7D%0A) for that experiment shows a `startDate` of Nov 13, but an `endDate` of `null`; so now I'm a bit confused as to how the homepage shows an "Ending" date of Nov 23 (apart from a `proposedDuration` and `proposedEnrollment` of 10 days).

```json
{
  "data": {
    "experimentBySlug": {
      "id": 29,
      "name": "test-cfr-experiment",
      "owner": {
        "username": "...@mozilla.com"
      },
      "slug": "test-cfr-experiment",
      "startDate": "2020-11-13T18:49:10.379319+00:00",
      "proposedDuration": 10,
      "proposedEnrollment": 10,
      "endDate": null,
      "status": "LIVE"
    }
  }
}
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-942)
┆Issue Number: EXP-942

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/pull/4672
