### ISSUE TITLE
Consolidate certain error message strings for consistency

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4597]
See https://github.com/mozilla/experimenter/pull/4591#discussion_r574092615

We're using a `SUBMIT_ERROR` const in some files, `SUBMIT_ERROR_MESSAGE` in another, and a string with the same message in others.

Let's consolidate our messaging/use the same var reference. See Peter's comment for potential other error strings we can make consistent.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-943)
┆Issue Number: EXP-943

**Comment by jodyheavener** [comment]
This is likely outside the scope of this issue, but I would personally love to eliminate the generic client messages and make the server messages and client exceptions more readable. Too often I've gotten a generic message and had to dig into Devtools or other areas to see what's up.
