### ISSUE TITLE
Display "Application" on Nimbus homepage?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4645]
Currently https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus doesn't tell me if an experiment is for Fenix or Desktop. I either have to click through each experiment, or guess by author, or use the [GraphiQL](https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v5/graphql#query=query%20getAllExperiments%20%7B%0A%20%20experiments%20%7B%0A%20%20%20%20name%0A%20%20%20%20owner%20%7B%0A%20%20%20%20%20%20username%0A%20%20%20%20%7D%0A%20%20%20%20slug%0A%20%20%20%20startDate%0A%20%20%20%20endDate%0A%20%20%20%20status%0A%20%20%20%20application%0A%20%20%7D%0A%7D%0A) dashboard to search for all experiments and then search for experiments where `"application": "FENIX"`.

But UI space is at a premium, and maybe there isn't a great place to display another column.

Not sure if a secret UI or filtering is an option, where we append `?application=FENIX` in the address bar is an option.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-969)
┆Issue Number: EXP-969

**Comment by jodyheavener** [comment]
As an aside: I think we should consider adding a greater max-width on the home page
