### ISSUE TITLE
Emails sent early for turning off experiments?

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#4647]
According to emcminn, she got emails on or around Feb 17 for two experiments that were supposed to end on Feb 24 and March 2. That seems early?

https://experimenter.services.mozilla.com/nimbus/multi-stage-aboutwelcome-set-default-as-first-screen/
https://experimenter.services.mozilla.com/nimbus/custom-messaging-in-aboutwelcome-for-chrome-users-to-import/

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-971)
┆Issue Number: EXP-971

**Comment by pdehaan** [comment]
Semi related https://github.com/mozilla/experimenter/issues/4693 (where I got an email to turn off my experiment around 10 days after the experiment was supposed to end; albeit I was on stage).
