### ISSUE TITLE
"Save and continue" disabled on audience page even though all fields are filled out

### ISSUE THREAD

**Issue by lmorchard** [mozilla/experimenter#4651]
Steps to reproduce:
* create a new experiment
* fill out each page, hitting "Save and continue" at each step
* finally, completely fill out Audience page
* "Save and Continue" will not be enabled, need to hit "Save" first

What I think is happening here is that we can only really know whether the Review page is accessible *after* saving the data. That lets us know whether we can continue.

What we might want to do is something like this:

* keep "Save and Continue" enabled at all times.
* when clicked, perform the save function
* wait to execute the navigation to next page until after the submit completes.
* only execute navigation when errors are clear and the next page is accessible. 

Transition to the next page is valid for all pages except Audience-to-Review. We should check if there are outstanding Review requirements and update the UI with warnings / errors if navigation is rejected.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-976)
┆Issue Number: EXP-976

**Comment by jodyheavener** [comment]
Your description of what's happen is correct, this was intentional, per #4626

> The Audience page needs to prevent you from continuing to the Request Review page until all valid fields are filled out, and so the Save and Continue button is disabled until the server allows you to continue.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Yeah, I'm just saying we may want to tweak it so that it goes ahead to save and check with the server, rather than just be disabled.

**Comment by jodyheavener** [comment]
Re-posting my note from the Slack thread:

> The problem with enabling this button is that even if you have all the fields correctly filled in on the Audience page the Overview or Branches page could have missing required fields, so clicking Next would not take you to the Request Review page, it would take you to one of those pages. My general opinion is that as long as we have the actual page disabled until you have all the correct fields this button should be disabled. 

So you could check with the server on click, but if you have invalid fields on other pages this could be a weird flow.
