### ISSUE TITLE
External Grafana URL in /request-review state doesn't have the fancy external icon

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4652]
https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-2021-02-18-lighthouse-audit/request-review

![pdehaan_2021-02-18_LiGhThOuSe-AuDiT_–_Review___Launch___Experimenter](https://user-images.githubusercontent.com/557895/108420351-8a34ce80-71e8-11eb-8d96-770223caad99.png)

This is mildly inconsistent with the external links for "See full JSON Representation", and "Risk mitigation checklist" links.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-977)
┆Issue Number: EXP-977

**Comment by pdehaan** [comment]
I guess another question is... Should the Monitoring link even appear at the "request review" state? There isn't anything to monitor since the experiment is under review and hasn't been approved/launched yet? Not sure if that link should be hidden until it's at least in the "Live" state.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Related: https://jira.mozilla.com/browse/EXP-874

> Should the Monitoring link even appear at the "request review" state?

Yeah I also don't think it's neccesary to show Timeline stuff either. This is just a byproduct of rendering the Summary component on this page. It might be worth adding a new prop to that component to indicate whether or not it should show  "slimmed-down" version for this page.
