### ISSUE TITLE
Add a slimmed-down version of Summary component (hide monitoring/timeline)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4657]
Should the Monitoring link appear at the "request review" state? There isn't anything to monitor since the experiment is under review and hasn't been approved/launched yet? Not sure if that link should be hidden until it's at least in the "Live" state.

_Originally posted by @pdehaan in https://github.com/mozilla/experimenter/issues/4652#issuecomment-781629567_

@jodyheavener replied in https://github.com/mozilla/experimenter/issues/4652#issuecomment-781650886 thread:

> Yeah I also don't think it's necessary to show Timeline stuff either. This is just a byproduct of rendering the Summary component on this page. _It might be worth adding a new prop to that component to indicate whether or not it should show  "slimmed-down" version for this page._

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-982)
┆Issue Number: EXP-982

**Comment by LZoog** [comment]
This relates to #4461
