### ISSUE TITLE
Timeline does not show end date

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4671]
Once an experiment has started we know its proposed duration and its real start date so we should know its proposed end date, I believe that should show here:

<img width="1141" alt="Screen Shot 2021-02-22 at 12 49 47 PM" src="https://user-images.githubusercontent.com/119884/108748552-b57f2c80-750c-11eb-9a8f-b0bfc733c674.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-989)
┆Issue Number: EXP-989

**Comment by pdehaan** [comment]
Possibly related: https://github.com/mozilla/experimenter/issues/4374

I thought I had an issue about the progress bar never really acting like a progress bar, but now I can't remember if I had an issue for it, or a comment in another issue, or if I was just shooting my stupid mouth in a fleeting Slack comment. I'll try digging that up if I can find it again.

**Comment by jodyheavener** [comment]
This issue _might_ be invalid since the experiment that triggered this had a "null" end date.

**Comment by jaredlockhart** [comment]
Actually what we really need is another property that does something like

```py
@property
def computed_end_date(self):
    return self.end_date or self.proposed_end_date
```

and that's what we should use everywhere in the UI that refers to an end date, so that while the experiment is live it uses teh proposed end date and then when it actually ends everything refers to the real end date.

So write a property like that, write tests for it, add it to V5, and then update all references in the UI to refer to that.
