### ISSUE TITLE
Don't return early in nimbus_check_kinto_push_queue

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4680]
I just noticed when we check whether we should push any experiments to kinto, if one collection has a pending review we return early instead of continuing on to the next collection.  We should continue, not return.

https://github.com/mozilla/experimenter/blob/main/app/experimenter/kinto/tasks.py#L105

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-996)
┆Issue Number: EXP-996

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Let's split nimbus_check_kinto_push_queue into two tasks, a parent task that loops over each application and dispatches a child task that takes in an application and performs all the relevant checks for that one application, and then it CAN return early while also not blocking the other application updates.  And then we don't even have to test/handle the case where returning early from one prevents updating the other.
