### ISSUE TITLE
Reduce integration test circle instance size

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4703]
We recently saw intermittent integration test failures #4700 which may be related to either temporary instability in Firefox Nightly builds, or in circle ci vm instance resource constraints.  As a possible mitigation we increased the circle ci instance size in https://github.com/mozilla/experimenter/pull/4702 but let's leave this ticket open to decrease back to `xlarge` in a week or two and see if the issue has passed.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1012)
┆Issue Number: EXP-1012

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Increasing the instance size didn't fix it, so I'm reverting this change now.  See https://jira.mozilla.com/browse/EXP-1011 for more discussion.
