### ISSUE TITLE
Confusing "Go to Review" button label when looking at an experiment in the Review state

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4706]
Re: https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/do-not-delete-about-welcome-reference-test

The wording might be a bit weird here where we're in the Review state, and the button says "Go to Review".

![do_not_delete_about_welcome_reference_test___Experimenter](https://user-images.githubusercontent.com/557895/109216769-cf697b00-7769-11eb-8b98-80934725559d.png)

---

For comparison sake, here's a few screenshots for the PREVIEW, LIVE, and COMPLETE experiment states.
Once an experiment is Live, the button changes to "Go to Design" with a different icon.

Even the "Go to Review" label during the Preview state might be a bit misleading, since it doesn't actually move the experiment from Preview => Review.

| STATE | IMAGE |
|:------|:------|
| PREVIEW | ![Testing_a_preview_for_previewing_sake___Experimenter](https://user-images.githubusercontent.com/557895/109217036-23745f80-776a-11eb-9de5-05cf1cf319e8.png)
| REVIEW | ![pdehaan_2020-12-08_004a___Experimenter](https://user-images.githubusercontent.com/557895/109217096-3a1ab680-776a-11eb-98cd-33821fab8497.png)
| LIVE | ![About_welcome_turn_off_experiment___Experimenter](https://user-images.githubusercontent.com/557895/109217147-4ef74a00-776a-11eb-9c7a-dbee50cd0da4.png)
| COMPLETE | ![pdehaan_Default_Firefoxen_Prompt_Retention_Experiment___Experimenter](https://user-images.githubusercontent.com/557895/109217217-6b938200-776a-11eb-9a7a-54ce61c32a7f.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1015)
┆Issue Number: EXP-1015

**Comment by LZoog** [comment]
We should be able to close this when #4682 is merged 😎

**Comment by jodyheavener** [comment]
Closing this as the core issue is resolved, but also filed https://jira.mozilla.com/browse/EXP-1017
