### ISSUE TITLE
Inconsistent "Back to Experiments" navigation links

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4707]
https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-default-firefoxen-prompt-retention-experiment

| `/{slug}` | `/{slug}/design` | 
|-----------|-----------------|
| ![pdehaan_Default_Firefoxen_Prompt_Retention_Experiment___Experimenter](https://user-images.githubusercontent.com/557895/109219692-c62ddd80-776c-11eb-87c4-2d0454aa419f.png) | ![pdehaan_Default_Firefoxen_Prompt_Retention_Experiment_–_Design___Experimenter](https://user-images.githubusercontent.com/557895/109219600-a696b500-776c-11eb-89df-82ce89abd1bf.png)

If you click the "Go to Design" button, the sidebar nav appears but the blue "&lsaquo; Back to Experiments" navigation turns into a gray "&lsaquo; Experiments" link.

---

![pdehaan_Default_Firefoxen_Prompt_Retention_Experiment___Experimenter](https://user-images.githubusercontent.com/557895/109218859-caa5c680-776b-11eb-943b-c4e3b38c1621.png)

![pdehaan_Default_Firefoxen_Prompt_Retention_Experiment_–_Design___Experimenter](https://user-images.githubusercontent.com/557895/109218971-f0cb6680-776b-11eb-9549-cd81605760de.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1016)
┆Issue Number: EXP-1016

**Comment by LZoog** [comment]
We should be able to close this when #4682 is merged since the blue link will no longer be present, though I wonder if the verbiage "Back to Experiments" is nicer than "Experiments".

**Comment by jodyheavener** [comment]
Closing for a more scoped issue https://github.com/mozilla/experimenter/issues/4708
