### ISSUE TITLE
"Experiments" or "Back to Experiments" in sidebar

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4708]
The link to go back to the homepage directory currently says "< Experiments" in the sidebar, and it was [suggested](https://github.com/mozilla/experimenter/issues/4707#issuecomment-786241084) that "< Back to Experiments" could be nicer.

Which is better? YOU be the judge. Call in now.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1017)
┆Issue Number: EXP-1017

**Comment by LZoog** [comment]
Confirmed by Ana we want "Back to Experiments".
