### ISSUE TITLE
Visualization results branch displays NaN%

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4713]
Looking at the visualization page for the random [multi-stage-aboutwelcome-set-default-as-first-screen-v2](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/multi-stage-aboutwelcome-set-default-as-first-screen-v2/results) experiment, and noticed a couple of the metrics are `NaN%` which doesn't feel very statistical.

![Multi-Stage_about_welcome_-_Set_Default_as_First_Screen_V2_–_Analysis___Experimenter](https://user-images.githubusercontent.com/557895/109231451-7c002880-777b-11eb-8dec-ef626fd7899e.png)

JSON goodness: https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v6/experiments/multi-stage-aboutwelcome-set-default-as-first-screen-v2/

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1019)
┆Issue Number: EXP-1019

**Comment by emtwo** [comment]
This seems to be resolved now. It must have been covered by a different bug fix.
