### ISSUE TITLE
Add GH action to notify maintainers of doc hub PRs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4721]
Doc maintainers, who may not maintain the Experimenter codebase, should be notified when a PR comes in specifically for doc updates. We should be able to do this with a GH action, perhaps with [issue-label-notifier](https://github.com/marketplace/actions/issue-label-notifier) or doing something similar to what this [SO question is asking](https://stackoverflow.com/questions/62325286/run-github-actions-when-pull-requests-have-a-specific-label). Create the label (`doc-hub`?) and add make sure it works by adding at least one email. We can add the actual users that should be notified after this epic is closed (that is, after all the initial set up/initial docs are done).

If possible, it might be worth looking into seeing if there's an action that will automatically add the label to PRs that contain MD-only file edits either in the root-level directory (or `app/doc-hub/`) or the branch, depending on what happens with EXP-1023, but that might be overkill and/or require a follow up ticket.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1026)
┆Issue Number: EXP-1026

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Cancelling this task, as EXP-1023 will be setting up a separate repository and those that would like to subscribe to documentation updates can do so there.

**Comment by pdehaan** [comment]
Ref: #4718 (which is EXP-1023)
