### ISSUE TITLE
Include table names on results page

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#4740]
@teonbrooks suggested that having the BigQuery results and statistics table names available from the results page would be a nice convenience for data scientists.

These will look like

```
`moz-fx-data-experiments`.mozanalysis.<experiment_slug>_<period>
`moz-fx-data-experiments`.mozanalysis.statistics_<experiment_slug>_<period>
```

where `period` is in {daily, weekly, overall}. We could also link to the [DTMO page](https://docs.telemetry.mozilla.org/datasets/jetstream.html) describing their schema.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1032)
┆Issue Number: EXP-1032

**Comment by teonbrooks** [comment]
great. and a copy button for it would be swell :)
