### ISSUE TITLE
Switch to release firefox for integration tests

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/experimenter#4741]
Currently, we use firefox nightly to run our integration tests against. We should switch that to firefox release.

Should fix #4700

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1033)
┆Issue Number: EXP-1033

**Comment by jaredlockhart** [comment]
@jrbenny35 does this need to be a separate issue or can it just be #4700?

**Comment by jrbenny35** [comment]
> 
> 
> @jrbenny35 does this need to be a separate issue or can it just be #4700?

Figured the fix should be a separate issue
