### ISSUE TITLE
Need better example Outcomes

### ISSUE THREAD

**Issue by jodyheavener** [mozilla/experimenter#4781]
Not sure if this is a request for jetstream-config, or maybe just how we parse the TOML files, but we need to make these example Outcomes better. These are distinct outcomes, one for Desktop and one for Fenix:

![Screen Shot 2021-03-09 at 12 24 14 PM](https://user-images.githubusercontent.com/6392049/110511638-691e1a00-80d2-11eb-8ac8-2d462c868767.png)

But you wouldn't know it! And because the slugs are the same, if you select one it prevents you from selecting the other.

cc @jaredlockhart

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1045)
┆Issue Number: EXP-1045

**Comment by jodyheavener** [comment]
I can dig deeper into this in a little bit, just wanted to surface it in case it was a quick fix.

**Comment by lmorchard** [comment]
Hmm, I was going to say that the outcome fixtures should be found here:

https://github.com/mozilla/experimenter/tree/main/app/experimenter/outcomes/tests/fixtures

But weird thing - the only one named "Example config" is this one called `should_be_ignored.toml.example` - which I *thought*, like, should be ignored?

https://github.com/mozilla/experimenter/search?q=%22example+config%22

I might scratch my head on this a bit today since I reviewed some of this stuff too

**Comment by lmorchard** [comment]
> These are distinct outcomes, one for Desktop and one for Fenix:

Also FWIW, after issue #4752, we should only see the outcomes filtered for the appropriate application selected for the experiment. Doesn't help that both of these are named "Example config", but eventually only one of these should be offered as a selection.

**Comment by lmorchard** [comment]
>We might want a local option to load up the test fixtures for dev usage? If only temporarily?

And to answer my own question, you could include this in your local `.env`?

```
JETSTREAM_CONFIG_OUTCOMES_PATH=/app/experimenter/outcomes/tests/fixtures/valid_outcomes
```

**Comment by jaredlockhart** [comment]
> > We might want a local option to load up the test fixtures for dev usage? If only temporarily?
> 
> And to answer my own question, you could include this in your local `.env`? [The path from where outcomes are loaded is configurable](https://github.com/mozilla/experimenter/blob/main/app/experimenter/outcomes/__init__.py#L27-L29).
> 
> ```
> JETSTREAM_CONFIG_OUTCOMES_PATH=/app/experimenter/outcomes/tests/fixtures/valid_outcomes
> ```

Oh yeah you could do that if you want extras to test with, you could also just copy the examples in the local checkout of the jetstream repo and fill them in with whatever and restart your docker 🐳 and then just delete them before you check in, whichever.  

I think if you set your env file to the fixtures folder and then forget you might miss changes to actual jetstream-config and being able to test those locally, so I'm not sure what the right workflow for local dev/debug is yet, we'll have to play around with it.

**Comment by jaredlockhart** [comment]
> > Not sure if this is a request for jetstream-config
> 
> Actually, I was wrong just now: The fixtures I mentioned in the last comment are just used in tests. The "Example config" entries _were_ coming from [jetstream-config](https://github.com/mozilla/jetstream-config/tree/main/outcomes).
> 
> I think this _could_ be a request for jetstream-config. But, eventually, real files will show up there.
> 
> We _might_ want a local option to load up the test fixtures for dev usage? If only temporarily?
> 
> Those ["Example config" files](https://github.com/mozilla/jetstream-config/tree/main/outcomes) were recently [renamed to use an `.example` file suffix](https://github.com/mozilla/jetstream-config/commit/04adf30aa36c361967f4c4530359dacfdc22d7e1). So, if you update your local git submodules, you'll end up with no selectable outcomes at all because `*.example` is filtered out when the files are loaded & parsed.

It should automatically update when you restart your containers I think, if it doesn't then something's going sideways.  And yeah there aren't any real outcomes in jetstream-config yet so the list should just be empty, but if you want something to test locally with you can either just put dummy files in the jetstream-config folder and then delete them before you commit or try changing the env var to point to the fixtures folder, I'm not sure which is a better pattern for local dev.

**Comment by jodyheavener** [comment]
Sweet, thanks all for your thoughts. Since this isn't a bug and not really a to-do I think we can close since it'll fix itself "eventually" and until then there are workarounds.
