### ISSUE TITLE
"Completed" view should sort by most recently ended

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#4782]
It's hard to find recent experiments in https://experimenter.services.mozilla.com/nimbus/ on the "Completed" tab. It would be nice if recently ended experiments were at the top of the list.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1046)
┆Issue Number: EXP-1046

**Comment by LZoog** [comment]
I'm going to close this as a dupe of #5281 since that one covers all tabs and has more discussion.
