### ISSUE TITLE
Autopopulate the Control branch name to: "Control"

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4802]
We should try to auto-populate the control branch name to "Control". It seems like most experiments have been naming the control branch "Control" and it might reduce friction, time, and effort while designing the experiment.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1064)
┆Issue Number: EXP-1064

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

This might be do-able in EXP-978

**Comment by LZoog** [comment]
Closing as a dupe of #4959
