### ISSUE TITLE
Can't access review page, but no missing fields warnings?

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4806]
This might be an edge case / obsolete with the upcoming changes to making review always accessible, but I thought I should file just in case:

**Actual:** Review view is greyed out after filling in all my fields:

!image-2021-03-12-08-27-55-582.png!

**Expected**:  I should either see what's missing or be able to access Review and Launch

See this staging experiment to reproduce:

[https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/asdasdasd_asdasdasdasd/edit/branches](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/asdasdasd_asdasdasdasd/edit/branches)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-1068)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15454/image-2021-03-12-08-27-53-098.png">image-2021-03-12-08-27-53-098.png</a> | <a href="https://jira.mozilla.com/secure/attachment/15453/image-2021-03-12-08-27-55-582.png">image-2021-03-12-08-27-55-582.png</a>
┆Issue Number: EXP-1068

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

FWIW this is due to "Expected number of clients" being set to 0.

**Comment by jaredlockhart** [comment]
Ah we should add a warning about that
