### ISSUE TITLE
`make up` fails on `jetstream_config` task if `unzip` not installed

### ISSUE THREAD

**Issue by lmorchard** [mozilla/experimenter#4828]
Getting started on a fresh checkout of experimenter under Ubuntu and ran into this:

```
➜  experimenter git:(4795-approve-reject-launch) make up
curl -LJ -o app/experimenter/outcomes/jetstream-config.zip https://github.com/mozilla/jetstream-config/archive/main.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   127  100   127    0     0    505      0 --:--:-- --:--:-- --:--:--   505
100 29175  100 29175    0     0  62206      0 --:--:-- --:--:-- --:--:--  144k
unzip -o -d app/experimenter/outcomes app/experimenter/outcomes/jetstream-config.zip
make: unzip: Command not found
Makefile:54: recipe for target 'jetstream_config' failed
make: *** [jetstream_config] Error 127
```

This is quickly fixed on the host with an `apt-get install unzip` - but this should probably a) be a part of the README or b) get handled somewhere in Docker?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1075)
┆Issue Number: EXP-1075

**Comment by jaredlockhart** [comment]
Good catch!  We should definitely update the README, I don't know how much we can automate that at the Makefile level without detecting the host OS, which is probably more work than it's worth.
