### ISSUE TITLE
Add a CODEOWNERS file to auto assign reviewers based on globs?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4846]
Re:reviewers, what about using a CODEOWNERS file to auto assign reviewers based on globs? 
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

For example, Tim+Anna are reviewers for any jetstream changes, experimenter core can be reviewed by whomever adds themselves to the codeowners file for whatever paths they volunteer to review/own. I can review PRs that add .svg files.

if we add e2e testing docs, B4hand and I can be notified on changes in those paths.

_Originally posted by @pdehaan in https://github.com/mozilla/experimenter-docs/issues/8#issuecomment-797820943_

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1083)
┆Issue Number: EXP-1083

**Comment by jaredlockhart** [comment]
Aw man I wish we could use that same logic to trigger CI tasks based on globs.

**Comment by pdehaan** [comment]
@jaredlockhart That's interesting, somebody else was asking about the same thing the other day.

I wonder if this works still: https://github.blog/changelog/2019-09-30-github-actions-event-filtering-updates/

Docs seem to say it's a thing, https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

**Comment by jodyheavener** [comment]
it's possible with gh actions but not with circleci

**Comment by jrbenny35** [comment]
We should add this. For QA automation it would help us keep track of changes to test files and allow us to see if something should have specific tests vs just a change.
