### ISSUE TITLE
Store published DTO on NimbusExperiment

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4851]
We currently expose the NimbusExperiment through the V6 API by serializing the current state of the experiment every time the V6 API is accessed.  However, the state in the database may not match the current published version of the experiment in Remote Settings as the experiment is modified while also being published (such as disabling enrollment).

Rather than serializing the database state when V6 is called, we should store the currently published DTO as a field on NimbusExperiment which is written to after any change is published to Remote Settings, and then use that to populate the V6 API.

This should allow us to delete the nimbus_check_experiments_are_paused task entirely, and simplify future workflows that involve making changes to published experiments.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1087)
┆Issue Number: EXP-1087

**Comment by jaredlockhart** [comment]
Actually upon further investigation I think what we'd have to do is add another field to V5 that contains the serialized DTO before it's published during the review step to completely separate the frontend review concern from the V6 publish state, and THEN we can do this.  But we don't really need to dig into this until we have a workflow that involves more live updates than just flipping the pause bool, so I think we can backlog this for now.
