### ISSUE TITLE
Adding new targeting shouldn't require a migration

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#4856]
I think it should be possible for external contributors to add new targeting PRs without having to run the entire setup locally / create a migration.

I have some opinions about how we could achieve this but I'll stop there :P

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1089)
┆Issue Number: EXP-1089

**Comment by lmorchard** [comment]
Hmm, yeah, this is how outcomes work now. Those can change based on an external source and be updated on container build without running a migration.

Could probably achieve this for targeting by getting away from [using `choices` in the model field](https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/models/nimbus.py#L94-L98) and use the list from constants more directly [in the v5 API feeding the frontend](https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/api/v5/queries.py#L53-L54).
