### ISSUE TITLE
Expose timeout data in V5 API

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4869]
To support the new timeout UI we need to look up the timeout in the changelogs and expose it in a convenient field in the V5 API.

We should

* Add a manager method to NimbusChangeLog to look up the most recent timeout changelog by finding the changelog which moves from publish_status Approved>Idle
* Add a field in the V5 NimbusExperiment type called `timeout` that is None or includes the entire changelog object so the frontend can display the date of the timeout

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1096)
┆Issue Number: EXP-1096

**Comment by lmorchard** [comment]
Just to double check [the flow diagram](https://github.com/mozilla/experimenter/tree/main/app/experimenter/kinto#publish-approvetimeout), I *think* the changelog transition we want to locate for timeout is draft/waiting to draft/review. 

![Capture](https://user-images.githubusercontent.com/21687/112226909-11140700-8bec-11eb-8035-84385052c813.PNG)

**Comment by lmorchard** [comment]
Though we also have "End (Approve/Timeout)" - looks like the transition there would be `live/waiting` to `live/review`

![Capture](https://user-images.githubusercontent.com/21687/112227664-3e14e980-8bed-11eb-9142-d814c27e4a8d.PNG)

**Comment by jaredlockhart** [comment]
@lmorchard Yeah I was thinking about that too, ending will come in a separate epic so I'd suggest we stick to just the launch case for now and we can add the extra filters/tests for the end case later.
