### ISSUE TITLE
[Nimbus] Profiles that invalidate the channel and version filters of an experiment are still marked as Active while being displayed in the "Completed Studies" section of the about:studies page

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#4898]
**[Prerequisites]:**
- Have an experiment that is set to target population on a specific release channel ("nightly", "beta", "release") and a specific version (e.g. 76 and higher).

**[Steps to reproduce]:**
1. Open a browser that can enroll in the experiment from prerequisites and enroll in the experiment.
2. Close the browser and open a different one using a different channel but the same profile.
3. Navigate to the "about:studies" page and observe the list of experiments.

**[Expected result]:**
- All experiments that had their targeting parameters invalidated by the channel switch are marked as completed and are found in the "Completed Studies" section.

**[Actual result]:**
- Experiments that had their targeting parameters invalidated by the channel switch are found in the "Completed Studies" section BUT they are marked as **active**.

**[Notes]:**
- The issue is also reproducible if the filter is invalidated by downgrading to an unsupported version using the same profile.
- The experiments are correctly marked as "completed" once the experiment is disabled in Remote Settings.
- Attached is a screenshot of the issue.

![image](https://user-images.githubusercontent.com/18304511/112309136-a6c29b80-8cab-11eb-97ad-e6fe286d3833.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1108)
┆Issue Number: EXP-1108

**Comment by lmorchard** [comment]
This seems like an issue more in Firefox than in Experimenter? Does Firefox re-check targeting once an experiment has been enabled within a profile? Also seems like an unexpected case to re-use a profile from one channel to another

**Comment by SoftVision-CiprianMuresan** [comment]
> This seems like an issue more in Firefox than in Experimenter?

If this were Normandy I would say yes, this is an issue on Firefox's side of things, but I'm not aware of a better place to file this scenario. Do we have a Bugzilla component for such issues?

> Does Firefox re-check targeting once an experiment has been enabled within a profile? Also seems like an unexpected case to re-use a profile from one channel to another

As far as I know, yes, Firefox does recheck targeting once an experiment is enabled to unenroll those profiles once they are no longer eligible. That being said, I realize these specific scenarios (channel switching and downgrading) are unexpected and quite discouraged, but there is enough information on how to circumvent the difficulties put in place to be able to still follow through with them.

**Comment by Softvision-PatriciuPop** [comment]
Cloned the ticket in Bugzilla for tracking. [Bug 1727074](https://bugzilla.mozilla.org/show_bug.cgi?id=1727074)
