### ISSUE TITLE
[Nimbus] A 2nd branch of an experiment is redisplayed in the creation form after it is removed

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#4899]
**[Steps to reproduce]:**
1. Navigate to the https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/ website.
2. Create a new experiment.
3. Fill all sections except the Branches one with valid data and save at each step.
4. Navigate to the Branches section and fill out one branch with valid data.
5. Remove the second branch and Save.
6. Refresh the page and observe the behavior.

**[Expected result]:**
- The experiment form remains unchanged and only shows a single branch.

**[Actual result]:**
- A 2nd empty branch is displayed.

**[Notes]:**
- The 2nd branch is also displayed on the `request-review` page in red.
- The 2nd branch does not appear in the Remote Settings 
- Attached is a screen recording of the issue.

![the 2nd branch of an experiment is redisplayed in the creation form after it is removed](https://user-images.githubusercontent.com/18304511/112313262-54d04480-8cb0-11eb-848f-2fb346f2b69d.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1107)
┆Issue Number: EXP-1107

**Comment by lmorchard** [comment]
I think this is working as intended: experiments need to have at least two branches - control and one treatment branch. [So, we create a default for control and the first treatment branch if either is missing](https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/api/v5/types.py#L152-L160).

**Comment by SoftVision-CiprianMuresan** [comment]
I understand, but in this case, we would need to have validation on the Branches page to expect 2 or more branches and not let users continue with a single branch. As it is now, the form heavily implies that you _need_ 2 branches, but lets you build an experiment with a single branch nonetheless.

**Comment by SoftVision-CiprianMuresan** [comment]
I have verified that the issue is no longer reproducible on the Experimenter stage platform. A second branch is no longer displayed in the "Branches" or "Review" pages when a single branch experiment is set up.
