### ISSUE TITLE
[Nimbus] "Expected number of clients" cannot be 0, but 0 is a valid number for that field

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#4901]
**[Steps to reproduce]:**
1. Navigate to the https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/ website.
2. Create a new experiment.
3. Fill all sections except the "Expected number of clients" field in the "Audience" section.
4. Write "0" in the "Expected number of clients" field and press "Save"
5. Observe the "Save and Continue" button and the "Review & Launch" section from the outline section.

**[Expected result]:**
- The "Save and Continue" button is actionable and no missing details pointed out in the outline section.

**[Actual result]:**
- The "Save and Continue" button is not actionable and the "Missing details in:" section is displayed, but no section is linked there.

**[Notes]:**
- Attached is a screen recording of the issue.

![expected number of clients cannot be 0](https://user-images.githubusercontent.com/18304511/112340491-42aed000-8cc9-11eb-82ec-a3b72f7faed4.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1668)

**Comment by Softvision-PatriciuPop** [comment]
I have retested this issue and the "Audience" section is marked as incomplete. However I am reopening this bug report because the affected field is not highlighted and no error is displayed when entering 0 as an expected number of clients.

**Comment by jaredlockhart** [comment]
@Softvision-PatriciuPop It does show:

<img width="1153" alt="Screen Shot 2021-08-23 at 1 04 49 PM" src="https://user-images.githubusercontent.com/119884/130487905-548c8968-e134-4808-b93c-a95c9728de95.png">
<img width="221" alt="Screen Shot 2021-08-23 at 1 04 44 PM" src="https://user-images.githubusercontent.com/119884/130487908-d2643c7c-030f-4fdf-b25b-c13c01f56ad0.png">
<img width="479" alt="Screen Shot 2021-08-23 at 1 04 38 PM" src="https://user-images.githubusercontent.com/119884/130487909-f1c1f1db-2505-406b-9800-7cab664b6afa.png">
