### ISSUE TITLE
Refactor NimbusExperimentFactory to incorporate publish_status

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4902]
Once we finish migrating everything over to using publish_status we'll want to add some logic to iterate the experiment through its status/publish_status stages to simplify the tests, and then we can remove explicitly creating those changelogs in the new tests.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1110)
┆Issue Number: EXP-1110

**Comment by jaredlockhart** [comment]
Okay I should've provided more detail, here is what I was thinking:

So when we only had status, the happy path lifecycle of an experiment (excluding like any kind of rejection flow) was like

- DRAFT (fill out all the fields that would be filled out by the form)
- REVIEW (generate bucketing)
- ACCEPTED
- LIVE 
- COMPLETE

so the point of the `create_with_status` method was to be able to say 'give me an experiment up to this point' (providing a target end status) and generate all the stages (status, branches, changelogs, the bucketing, etc) that would happen up to some point, as if someone had actually gone through the process by hand.

Now that looks more like

#### Launching
- DRAFT/IDLE/is_paused:False/is_end_requested:False
- DRAFT/REVIEW/is_paused:False/is_end_requested:False
- DRAFT/APPROVED/is_paused:False/is_end_requested:False
- DRAFT/WAITING/is_paused:False/is_end_requested:False
- LIVE/IDLE/is_paused:False/is_end_requested:False
#### Pausing 
- LIVE/WAITING/is_paused:False/is_end_requested:False
- LIVE/IDLE/is_paused:True/is_end_requested:False
#### Ending 
- LIVE/REVIEW/is_paused:True/is_end_requested:True
- LIVE/APPROVED/is_paused:True/is_end_requested:True
- LIVE/WAITING/is_paused:True/is_end_requested:True
- COMPLETE/IDLE/is_paused:True/is_end_requested:True

for the full flow with all the new review stages (we could implement the halfway version we have right now where we skip straight from IDLE to APPROVED but it would land and then we'd have to go in and add the REVIEW stages like a day later so we might as well just skip over that).

So like a completely naive way to do that would just be

```py
def create_with_status(target_status, target_publish_status, **kwargs):
    experiment = ...
    for status in Status.choices:
        for publish_status in PublishStatus.choices:
            experiment.status = status
            experiment.publish_status = publish_status
            experiment.save()
            nimbus_generate_changelog(experiment)

            if (status, publish_status) == (target_status, target_publish_status):
                return experiment
```

but already you can see there's a bunch of combinations of status/publish_status that would generate that aren't actually in our lifecycle, so I think probably a better way to do it would be to hard code the stages like

```py
class NimbusConstants:
    class Lifecycle(Enum):
        DRAFT_IDLE = {"status": Status.DRAFT, "publish_status": PublishStatus.IDLE, "is_paused": False, "is_end_requested": False}
        DRAFT_REVIEW = {"status": Status.DRAFT, "publish_status": PublishStatus.REVIEW, "is_paused": False, "is_end_requested": False}
        ...etc

def create_with_status(lifecycle_target, **kwargs):
    experiment = ...
    for lifecycle_state in Lifecycle:
        for field, value in lifecycle_state.items():
            setattr(experiment, field, value)
        experiment.save()
        nimbus_generate_changelog(experiment, ...)

        if lifecycle_state == lifecycle_target:
            return experiment
```

and then in all our tests, we can say, the way we do now

```py
    experiment = NimbusFactory.create_with_status(Lifecycle.COMPLETE_IDLE, ....)
```

and it'll loop over all the valid lifecycle states and give you an experiment in that target state.

So then we can replace all our tests with this so we can nuke all those places where we explicitly loop over the publish_status, and in the future it'll make it super easy to generate an experiment at some arbitrary point in its lifecycle.

**Comment by jaredlockhart** [comment]
Oh also one thing, dates.  In legacy I'd pick a random day in the past, and then for each lifecycle state, do it 1 day later:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/tests/factories/legacy.py#L144-L164

This should help for cases where we want things to have happened in the past.  We could do some logic like this and incorporate things like the number of enrollment days so the pausing happens that many days later...

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Was thinking about picking this up, but it looks like its status is in progress while unassigned - is someone working on this?

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Hmm, don't think anyone looked at this in a week or so since I asked and forgot about it. So, I think I'll pick it up 😀
