### ISSUE TITLE
Implement End UI components in front-end

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4940]
In EXP-1143 we prepared the components for the End UI. From here we should be able to add them to the console.

Add this UI to the experiment Summary page, after an experiment has requested to end and the user can review the experiment. The entrypoint for this is likely inside the [EndExperiment](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/Summary/EndExperiment/index.tsx#L77:L77) component. Refer to the [Figma designs](https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/Nimbus-Console-UI?node-id=219024%3A3402), but take care to update the copy to not use possessive phrasing when the UI is intended for a broad audience (You can end _your_ experiment, and you can reject _the_ experiment change, but _the_ change has timed out in RS).

Throughout this flow ensure that the canReview property is being used to determine who can see what UI (unless our existing components already handle it). Currently canReview is anyone but the experiment owner, allowing the following:

* Experiment owner can see the initial live state of the experiment, where they can initiate an end request
* Experiment owner can see the rejected state/reason of an experiment
* Reviewer can see any of approve/reject UI for an experiment’s end request, the owner cannot
* Everyone can see the banner for when an end request has timed out in Remote Settings

Because the UI for this was already built in EXP-1055 the mutation for rejecting an experiment should already be in place, and completion of this issue should mean the full flow is ready for use.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1144)
┆Issue Number: EXP-1144

**Comment by jodyheavener** [comment]
Ah looks like this is partly blocked by #5030, and #4939 added the re-usable component to the right place. I think this issue is now just adding the right mutation.
