### ISSUE TITLE
Timeline shows wrong durations

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4945]
In the Nimbus UI, the timeline shows the projected durations and not the actually occurring durations.  Ie I just launched and ended this on the same day but still shows 28/7 days:

<img width="1156" alt="Screen Shot 2021-03-29 at 2 45 35 PM" src="https://user-images.githubusercontent.com/119884/112884504-93457500-909d-11eb-9914-a7b28d0b7b3c.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1146)
┆Issue Number: EXP-1146

**Comment by jodyheavener** [comment]
Huh, yeah makes sense. We could use the `computedEndDate`-`startDate` for the total duration, but enrollment might be a little wonky to calculate. Maybe the lesser of `computedEndDate`-`startDate` _or_ proposed duration 🤔

**Comment by jaredlockhart** [comment]
No we can figure out the real enrollment period by looking at the changelogs.  We should just add some computed properties for those to the model that use the real values from teh changelogs if they exist or fallback to teh proposed ones, expose those in V5 and change the timelie UI to always use the computed values and then they'll be the proposed ones until teh real values start filling in and then update automagically.
