### ISSUE TITLE
Nimbus pages should have better CSS class names

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/experimenter#4947]
Most of the pages don't have class names that indicate what page it is. We should add these as it would help with UI testing.

```data-testid``` works but with selenium it is a bit cumbersome to check for. A class/ID would be faster.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1148)
┆Issue Number: EXP-1148

**Comment by LZoog** [comment]
@jrbenny35 Hmm, what's it look like to select something in Selenium with a `data-testid` vs `class`? We could potentially add a class name when we add `data-testid`s, but if we don't need to style the component or you don't need to select a group of common items, it feels like we should use an `id` over a class name.

**Comment by jodyheavener** [comment]
From me in slack:

> Yeah I guess since we’ve been heavily using Bootstrap components and classes we haven’t needed to roll our own. Cool with me if you want to add some (or if you want us to try and incorporate them into future work), I just want to avoid custom CSS as a result :ok_hand:

**Comment by jrbenny35** [comment]
> 
> 
> @jrbenny35 Hmm, what's it look like to select something in Selenium with a `data-testid` vs `class`? We could potentially add a class name when we add `data-testid`s, but if we don't need to style the component or you don't need to select a group of common items, it feels like we should use an `id` over a class name.
> 
> Edit: I'm all for making things easier, just curious about the benefits gained. 😄

I agree, an ID would be better
