### ISSUE TITLE
Don't import NimbusConstants and NimbusExperiment in the same file

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4952]
NimbusExperiment has NimbusConstants mixed into it so we don't need to import both in the same file, you can just import one.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1152)
┆Issue Number: EXP-1152

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

I did this in a recent PR.
