### ISSUE TITLE
Branches should be called "control" and "treatment" by default

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#4959]
Based on a feature request from Grisha:
> It’ll be nice if the control/treatment were standard options in a dropdown menu, to prevent me from having to input these manually & making a typo

I don't think dropdown is right since we need to support other values in desktop (and will in mobile soon), but having `control` and `treatment` be the default values seems like an obvious win

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1156)
┆Issue Number: EXP-1156

**Comment by LZoog** [comment]
Duplicate of: #4802

I'll close 4802 though since this task also asks for `treatment`

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

I think also it would make sense in the Summary view just to say "Branches are not saved yet" or similar
