### ISSUE TITLE
Add 'Accepted by Normandy' button

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#497]
When an experiment is in the 'ready to launch' state, we need to add a button for 'accepted by normandy'.

**Comment by shell1** [comment]
I'm going to close this one for now.  This state might be more legacy from the old flow.  Now we look at "ready to ship" on Mondays - and ship everything that isn't blocked.

**Comment by jaredkerim** [comment]
For clarity, this will be handled by #498
