### ISSUE TITLE
Branch configuration screen is non-intuitive for Fenix

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4991]
For Fenix experiments - when going through the branch configuration there are certain parts of the UI that are confusing.

1. There is no visual mapping of the "feature flag" to the featureID slug that is implemented in the Fenix client.  1st timers were not sure what needed to be added there.

2. Mismatch in naming - referred to as _feature flag_ in UI but referred to in onboarding docs as _Feature Configuration_ Fenix docs and api as featureID

3. :exclamation:in the UI doesn't clear when the experiment is correctly setup - so it _feels_ like you've done something wrong.

4. List of feature flags is not filtered to the application (which was selected) - so if there are similar names between applications, the wrong feature flags may be selected.

!image-2021-04-06-10-26-03-064.png|width=979,height=598!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1173)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15933/image-2021-04-06-10-26-03-064.png">image-2021-04-06-10-26-03-064.png</a>
┆Issue Number: EXP-1173

**Comment by jaredlockhart** [comment]
1. Great point, we should show more information about the feature when you're selecting it 👍 
2. Also a good point, we should be consistent with that naming 👍 
3. I think this is refering to the 'Required for Launch Errors' here https://jira.mozilla.com/browse/EXP-907
4. Yep this is filed here https://github.com/mozilla/experimenter/issues/4610
