### ISSUE TITLE
account:experimenter creating new approve request to update last modified date

### ISSUE THREAD

**Issue by punamdahiya** [mozilla/experimenter#4994]
In production RS, after approving pause enrollment request from account:experimenter, a new approve request is sent to RS asking to approve change to last_modified_date
<img width="1034" alt="Screen Shot 2021-04-08 at 10 59 06 AM" src="https://user-images.githubusercontent.com/597734/114074870-ba4c3580-9859-11eb-84f6-851cbbe17fe2.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1178)
┆Issue Number: EXP-1178

**Comment by punamdahiya** [comment]
Enrollment pause request was created a week ago by account:experimenter and approved today, after which a new approve request with last modified date was sent  by account:experimenter, attaching complete history from RS
<img width="1044" alt="Screen Shot 2021-04-08 at 11 05 06 AM" src="https://user-images.githubusercontent.com/597734/114075570-87567180-985a-11eb-914f-0076d071381d.png">

**Comment by jaredlockhart** [comment]
Interesting!  Thank you for catching @punamdahiya !

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Okay we've made recent changes to the way we handle RS changes that should address this.  I'm going to close this and if we see it come up again we can refile.

Ref https://github.com/mozilla/experimenter/pull/5074
