### ISSUE TITLE
Rejecting End request does not reset isEndRequested

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5020]
Steps to repro:

* Launch an experiment
* End the experiment in the console so that the request shows up in RS
* Optionally confirm that isEndRequested is true on that experiment
* Reject the change

Expected result:

* Experiment stays Live/Idle but isEndRequested is now false, thus displaying the UI to re-request the end

Actual result:

* Experiment is Live/Idle but isEndRequested is still true, preventing the user from re-requesting the end

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-1191)
┆Issue Number: EXP-1191

**Comment by jaredlockhart** [comment]
Fixed in #4942
