### ISSUE TITLE
Format and check integration tests with flake8/black

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#5038]
We need to make sure flake8 and black check and format the integration tests folder.  I thought I had done this previously but maybe something broke at some point.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1199)
┆Issue Number: EXP-1199

**Comment by jodyheavener** [comment]
FWIW I was just playing with this and found that the check correctly failed when using `docker-compose.yml`, but not `docker-compose-test.yml`
