### ISSUE TITLE
Add integration test docs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5048]
We should have integration test docs with notes on how to run these locally/how to run just one and any other relevant info.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1207)
┆Issue Number: EXP-1207

**Comment by pdehaan** [comment]
Needs:
- how to run locally
- how to run a single test (or directory of tests)
- how to generate new baselines locally (or by grabbing generated assets from CI)
- how to view assets/videos for failed CI builds

Wants:
- guidance on writing new tests for regressions? We've had a few recent issues w/ Application Errors and other breakages. Not sure if we want to document when tests should be written in certain cases or lessons learned.
- how to test Android/iOS? (unless these are just Desktop specific docs currently and we want other docs/flows for mobile testing)
- any potential issues w/ mac-vs-pc-vs-linux baselines?
- debugging if a test passes locally but fails on CI (or vice versa)?

**Comment by jrbenny35** [comment]
> Not sure if we want to document when tests should be written in certain cases or lessons learned.

I like this but we can't watch every issue. The team should file or add a label so we can look back

**Comment by pdehaan** [comment]
> I like this but we can't watch every issue. The team should file an issue or add a label so we can look back

💯 &nbsp; I think an issue in Jira/GitHub with a tag of "regression" makes a lot of sense. Easy to search for and ideally a test can be written along with the PR that fixes the regression. I think we had 1-2 instances this week where we had unexpected errors due to recent changes.
