### ISSUE TITLE
Add survey fields

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#507]
We should add new optional fields under the analysis section

Link "help" for this section to one location: https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-SurveyChecklist

Survey Required? - boolean

**If yes and add-on experiment:** 
Survey URL(s) - open text field
Launch timing - open text field

**If yes and pref-flip experiment**
Survey URL(s) - open text field
Duration until add-on expiration - open text field

If presenting 2 different options for pref-flip versus add-on... talk to @shell1 or @jaredkerim  about next best options.  Also I'd be interested in your opinion on what it would look like to put the specific help guidance from the page in some of the open text boxes (like "Launch Timing" or "Duration until add-on expiration")

**Comment by shell1** [comment]
Survey should link to the help here https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-SurveyChecklist

Let Shell know when this bug lands - to update the information on where to put Survey URLs (until this lands - guiding folks to put in Analysis details.)

**Comment by shell1** [comment]
we need separate handling of this for pref flip and add-on studies.  add-on studies require a week longer running (with enrollment paused) to allow the add-on to expire and trigger the survey.

**Comment by shell1** [comment]
assigned to myself until I've made this card 100% actionable.  Will unassign once I'm satisfied that someone can work on it.

**Comment by jaredkerim** [comment]
I think it makes most sense to just have two fields 

Survey URLs
Survey Launch Instructions

And then just include specific help text for each of pref-flip and add-on experiments, rather than going through the logic of creating two different fields that are essentially filling the same role.  @shell1 ?

**Comment by shell1** [comment]
@jaredkerim so long as in box instructions for each are taken from the related place in mana for each - I'm OK with. It is pretty specific for each one what we need, so probably better to put in the box.  Thanks for sharing what is possible/hard.  even if the inbox help can only show the same blurb that covers each scenario separately that could work.. "for Pref experiment surveys...blah" and for add-on experiment surveys...blah" - that still works.  https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-SurveyChecklist
