### ISSUE TITLE
Modify Branch UI to make Feature Config required

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#5103]
Because we now want all experiments to include a feature config, we should change the branch UI to make it clearer that users must select a feature config.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1231)
┆Issue Number: EXP-1231

**Comment by LZoog** [comment]
Oooh, this relates to #5171 / could even be considered a dupe.

@AnaMedinac tagging you in case you can help give some direction on what should be displayed here.

**Comment by LZoog** [comment]
I'm going to throw this into the Required for Launch errors epic, I don't think we necessarily need input from Ana here but we should show this field as required.
