### ISSUE TITLE
Algoila prepends experimenter-docs/ to URLs which breaks search on experimenter.info

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5112]
Original Slack message:

> the docs search seems a lil wonky; if i search “dto” it finds https://experimenter.info/experimenter-docs/android-feature-api/#experiment-api-dto but that 404s; the page is https://experimenter.info/android-feature-api

> oh, this must be github-url vs cool-url

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1239)
┆Issue Number: EXP-1239

**Comment by jodyheavener** [comment]
@tdsmith this should be fixed now via https://github.com/algolia/docsearch-configs/pull/4020

(Also TIL we are encouraged to submit our own PRs there if we need to make more changes)
