### ISSUE TITLE
Audiences should be filtered by application

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#5116]
Audiences should:

* Apply to one or more application 
* Only show up in the UI for matching applications

Note that all audiences currently in that file are **Desktop only**

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1242)
┆Issue Number: EXP-1242

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Note that we ran into an error in a production configuration (it was caught in review) because of this, I'd like to prioritize higher

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Audiences are currently defined as constants here:
https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/constants/nimbus.py#L18  

They have some other metadata associated with them, but not application

**Comment by lmorchard** [comment]
> They have some other metadata associated with them, but not application

How do we determine which targeting is associated with which application? That'd be the first blocker to getting this done.

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Added a note, all existing audiences are currently Desktop only
