### ISSUE TITLE
Add docs about testing to this repo

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/experimenter#5161]
There are no docs on what/why/how we test either experimenter or nimbus within this repo.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1263)
┆Issue Number: EXP-1263

**Comment by LZoog** [comment]
We have a "Running tests and checks" section in the README, but we have #5048 filed specifically for integration tests. I was going to close one of these as a dupe, and we probably still can, but @jrbenny35 seems like this ticket is about reworking our test docs and maybe not specifically about integration tests?

**Comment by jrbenny35** [comment]
Yeah, this is just about all types of testing. There aren't many docs on the tests, in any context.
