### ISSUE TITLE
General application error when saving branches with no Feature configuration

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#5180]
https://stage.experimenter.nonprod.dataops.mozgcp.net/__version__

```json
{"commit": "94b55b50de073676211d5549f241bd42322562b2",
 "source": "https://github.com/mozilla/experimenter.git",
 "build": "https://circleci.com/gh/mozilla/experimenter/26663"}
```

### Steps to reproduce

1. Create a new experiment
	- Enter a Public name
	- Enter a Hypothesis
	- Choose an Application (I chose Desktop, but doubt it's relevant)
1. Click "Next"
2. Click "Save and Continue" (without filling anything out on "Overview" page)
3. Click "Save and Continue" (without filling anything out on "Branches" page)

### Actual results

> #### General application error
> Something went wrong. Please try again later.

```
[instrument.ts:129] TypeError: Cannot read property 'name' of undefined
    at xu (index.tsx:129)
    at Xa (react-dom.production.min.js:153)
    at Po (react-dom.production.min.js:175)
    at mu (react-dom.production.min.js:263)
    at sc (react-dom.production.min.js:246)
    at uc (react-dom.production.min.js:246)
    at Zu (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at qi (react-dom.production.min.js:122)
    at Gi (react-dom.production.min.js:123)
    at Wi (react-dom.production.min.js:122)
    at Qu (react-dom.production.min.js:230)
    at vo (react-dom.production.min.js:163)
    at useBaseQuery.ts:38
```

Example URL https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-2021-05-06-test-aaaaaa/edit/metrics

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1280)
┆Issue Number: EXP-1280

**Comment by pdehaan** [comment]
Even if I try and juggle the URL string, I can't seem to get this experiment back into a "good" state. Not sure if this is related to something in Metrics that is trying to calculate something on an undefined branch...
I'll try creating a few more experiments with dummy data and see if I can trace down where the `<undefined>.name` error is throwing from.

**Comment by pdehaan** [comment]
Wow, tricky... I think this might be potentially related to saving Branch configs.
If I create a new experiment, jump to the /edit/branches route, enter some descriptions, then click "Save", I get the same "General Application Error". I don't even have to visit the /edit/metrics route.

**Comment by pdehaan** [comment]
OOooo! I _don't_ get the error when I specify a Feature configuration (about:welcome) with one branch enabled (`{}`) and the other branch value is disabled.
After specifying a feature configuration, I can Save and Continue and not get the Application error.

So my $0.03 CAD is that saving the branch configuration without a Feature configuration is no bueno. 😢 
Thanks for coming to my TED Talk.

**Comment by jaredlockhart** [comment]
Thanks for filing @pdehaan ! Closing as duplicate of https://github.com/mozilla/experimenter/issues/5186

**Comment by jaredlockhart** [comment]
Actually I shouldn't close this, @pdehaan please verify fixed on stage and then close 🙏

**Comment by pdehaan** [comment]
<kbd>/giphy "Huzzah!"</kbd>

I can now create experiments on stage without it giving me the application error when saving the Branches page.

Closing.
