### ISSUE TITLE
Experiment detail page broken on stage

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#5186]
https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-20210506-ddd-application-error/edit/overview

"'NoneType' object has no attribute 'slug'"

in v6 serializer

in sentry:

https://sentry.prod.mozaws.net/operations/experimenter-stage/issues/11194593/?query=is%3Aunresolved

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1282)
┆Issue Number: EXP-1282

**Comment by pdehaan** [comment]
See also #5180 / EXP-1280
