### ISSUE TITLE
Infinite redirect loop on Review & Launch page

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#5189]
On [this experiment](https://experimenter.services.mozilla.com/nimbus/default-browser-adoption-experiment) on the 'Review & Launch' page, there is an infinite redirect loop bouncing back and forth between the review page and an error page.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1284)
┆Issue Number: EXP-1284

**Comment by pdehaan** [comment]
[graphiQL](https://experimenter.services.mozilla.com/api/v5/graphql#query=%7B%0A%20%20experimentBySlug(slug%3A%22default-browser-adoption-experiment%22)%20%7B%0A%09%09%23%20id%0A%20%20%20%20name%0A%20%20%20%20slug%0A%20%20%20%20application%0A%20%20%20%20status%0A%20%20%20%20publishStatus%0A%20%20%20%20%23%20publicDescription%0A%20%20%20%20%23riskMitigationLink%0A%20%20%20%20riskBrand%0A%20%20%20%20riskPartnerRelated%0A%20%20%20%20riskRevenue%0A%20%20%20%20%23isPaused%0A%20%20%20%20%23%20hypothesis%0A%20%20%20%20%23featureConfig%20%7B%0A%20%20%20%20%23%20%20id%0A%20%20%20%20%23%7D%0A%20%20%20%20readyForReview%20%7B%0A%20%20%20%20%20%20message%0A%20%20%20%20%20%20ready%0A%20%20%20%20%7D%0A%20%20%20%20%23referenceBranch%20%7B%0A%20%20%20%20%23%20%20featureValue%0A%20%20%20%20%23%7D%0A%20%20%20%20%23reviewRequest%20%7B%0A%20%20%20%20%23%20%20oldStatus%0A%20%20%20%20%23%20%20oldPublishStatus%0A%20%20%20%20%23%20%20message%0A%20%20%20%20%23%20%20experimentData%0A%20%20%20%20%23%7D%0A%20%20%20%20%23recipeJson%0A%20%20%7D%0A%7D%0A) says:

```js
{
  "data": {
    "experimentBySlug": {
      "name": "Default Browser Adoption Experiment",
      "slug": "default-browser-adoption-experiment",
      "application": "FENIX",
      "status": "DRAFT",
      "publishStatus": "REVIEW",
      "riskBrand": null,
      "riskPartnerRelated": null,
      "riskRevenue": null,
      "readyForReview": {
        "message": {
          "risk_partner_related": [
            "This field may not be null."
          ],
          "risk_revenue": [
            "This field may not be null."
          ],
          "risk_brand": [
            "This field may not be null."
          ]
        },
        "ready": false
      }
    }
  }
}
```

**Comment by LZoog** [comment]
Unassigning myself as Jared is working on #5192 and the migration will fix this👍

**Comment by LZoog** [comment]
Just checked, the patch for #5192 covered this.
