### ISSUE TITLE
Add a data migration to set non null values for risk mitigation questions for existing experiments

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#5192]
We recently added new risk mitigation question fields to the NimbusExperiment model, which are now required to launch.  For new experiments, this is fine.  For launched experiments, this is fine.  But for exeriments that are ready to review but not yet launched, they're caught in a state where they're both not editable and not ready to review.  For those experiments we should set the risk questions to False becuase the risk mitigation information will be captured in the risk mitigation document that was filled out when the experiment was created.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1286)
┆Issue Number: EXP-1286

**Comment by LZoog** [comment]
The fix for this is going to fix #5189
