### ISSUE TITLE
Our directory view shows "No Feature" for all experiments under the Feature column

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5214]
In the prod directory view in Nimbus all our experiments are showing "No Feature" under the feature column. 

Marking as a bug since it's not intentional behaviour. 

!image-2021-05-10-16-33-25-042.png|width=672,height=455!

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-1291)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16212/image-2021-05-10-16-33-25-042.png">image-2021-05-10-16-33-25-042.png</a>
┆Issue Number: EXP-1291

**Comment by lmorchard** [comment]
Merged, and I think this fixed the issue.

Before prod deploy:

![Capture](https://user-images.githubusercontent.com/21687/117881355-00802480-b25e-11eb-9510-461132360b15.PNG)

After prod deploy:

![Capture2](https://user-images.githubusercontent.com/21687/117881390-0d047d00-b25e-11eb-9bee-fe48d1ac3e12.PNG)
