### ISSUE TITLE
Add anchor tags to important headers on summary page

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#5228]
Now that we have lots of interesting info on the summary page, we should add anchor tags to all the important headers so people can link straight to them.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1303)
┆Issue Number: EXP-1303

**Comment by pdehaan** [comment]
You mean just add anchor tags w/ ids to make sharing easier? Or were you thinking more of a mini table of contents to quickly jump between sections on the page?

For example, on https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/message-homepage-remediation-v2-search-value-props-exper-release-83 (random experiment), were you thinking of anchors for:

- H2. Timeline
- H3. Monitoring (not sure why this is an H3 and others are H2, unless we're recycling this component)
- H2. Summary
- H2. Audience
- H2. Branches
	- TH. control
	- TH. Treatment A
	- TH. Treatment B
	- TH. Treatment C

Or just quick anchors for the H2-H3 elements and not the individual branches?

**Comment by LZoog** [comment]
We could also potentially use `react-scrollspy` since we're already using it on the Results page.

**Comment by LZoog** [comment]
We don't want to use `react-scrollspy` here: just add anchor tags to Timeline, Monitoring, Summary, Audience, and Branches. Also double check that they're consistent / semantically correct heading levels.
