### ISSUE TITLE
Add collapse/expand option to summary page JSON blobs

### ISSUE THREAD

**Issue by LZoog** [mozilla/experimenter#5231]
Now that we have JSON formatting in place, some experiments have a pretty lengthy summary/review page: https://experimenter.services.mozilla.com/nimbus/multi-stage-onboarding-set-default-v42-experiment

We can potentially add a toggle that adds a max-height to these sections with "expand"/"contract" options, or something else similar to help clamp the full value when it's really lengthy.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1304)
┆Issue Number: EXP-1304

**Comment by pdehaan** [comment]
Oh interesting... It looks like GitHub adds a "copy to clipboard" icon when I expand the details section, but I think that's a neat GitHub-specific thing since I don't see that when I try the same snippet on jsbin.

**Comment by LZoog** [comment]
@pdehaan Ohh that's really neat/that's what you meant on Slack, I didn't know that was a thing now! I'm not sure if we want some kind of preview or not, or if it's OK to hide all of it until they click "click to toggle", but that's something to experiment with. 😁

**Comment by pdehaan** [comment]
I also learnt that you can do `<details open>` and it should open the collapsible details section by default. Then there were lots of CSS bits about `:not(open)` for conditional styling where I started to get lost.
