### ISSUE TITLE
Set start and end dates for grafana link

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#5234]
The Grafana link should have start and end dates encoded in the URL. The start date should be the actual start date and the end date should be inferred from the duration of the experiment if it doesn't exist.

The format of the URL params is `from=1601251200000&to=1620864000000`, where the `from` and `to` values are ms epoch times

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1308)
┆Issue Number: EXP-1308

**Comment by jaredlockhart** [comment]
Thank you for filing but also you don’t have to infer end date for a live experiment, omitting it will default to end=now. Only have to set end date after it’s ended to snap it to the lifespan of the experiment.
