### ISSUE TITLE
Add `PreviewURL` component to Storybook

### ISSUE THREAD

**Issue by LZoog** [mozilla/experimenter#5238]
We're missing it in there and it'd be nice to see/poke at it on its own.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1310)
┆Issue Number: EXP-1310

**Comment by Mardak** [comment]
There was also a request to pull out the inline `cursor: copy` style to reuse for other components
https://github.com/mozilla/experimenter/pull/5232#discussion_r631244010
https://github.com/mozilla/experimenter/blob/908a3416d4c92fc3fb40d475b7a04b902dc54e56/app/experimenter/nimbus-ui/src/components/PreviewURL/index.tsx#L30
