### ISSUE TITLE
Make risk mitigation answers more obvious in summary table

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#5243]
https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-disapproving-experiment-is-disapproving-0001a/request-review

![pdehaan-disapproving_experiment_is_disapproving_0001a_–_Review___Launch___Experimenter](https://user-images.githubusercontent.com/557895/118055659-58418d00-b33d-11eb-9c6d-aade34921732.png)

I answered "Yes" to one of these risk mitigation questions, but it isn't immediately obvious which one of the three is a risk.
We might want to consider styling the answers with some CSS to maybe do:

no -- green
yes -- red

Something possibly like this devtools hackjob nightmare sauce:

![pdehaan-disapproving_experiment_is_disapproving_0001a___Experimenter](https://user-images.githubusercontent.com/557895/118056124-33014e80-b33e-11eb-8251-1b4a26e12797.png)

I suspect this might make the answers stand out a bit better for the reviewers who will be able to see any riskier answers a bit easier.

We already do something roughly similar when the values are not set (I believe with our custom `<NotSet/>` component):

![pdehaan-disapproving_experiment_is_disapproving_0001b___Experimenter](https://user-images.githubusercontent.com/557895/118055802-a22a7300-b33d-11eb-8f9b-a2c81319f2b2.png)

https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-disapproving-experiment-is-disapproving-0001b

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1312)
┆Issue Number: EXP-1312

**Comment by LZoog** [comment]
Closing this after confirming with Ana that she prefers how it looks as-is now.
