### ISSUE TITLE
Risk mitigation questions are only items in summary table w/ trailing colons

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#5244]
Related: #5243

A minor nit and inconsistency, but my eyes will not be able to unsee.

![pdehaan-disapproving_experiment_is_disapproving_0001a___Experimenter](https://user-images.githubusercontent.com/557895/118056598-17e30e80-b33f-11eb-9e09-777bc2c717b7.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1313)
┆Issue Number: EXP-1313

**Comment by pdehaan** [comment]
Outside the scope of my nit above, but not sure if it'd tighten up the UI a bit by having a single row saying "Risk mitigation questions" (plural, no trailing colon) and then have the three questions/answers in a list within the cell:

![pdehaan-disapproving_experiment_is_disapproving_0001a___Experimenter](https://user-images.githubusercontent.com/557895/118056808-714b3d80-b33f-11eb-9b30-ae764e805d81.png)

**NOTE:** Ignore the colors, that was just a visual artifact from the other bug report's faux screenshot.

Not sure if `<ul>` or `<ol>` is more preferable. I tried both but had no strong feelings either way.

**Comment by LZoog** [comment]
Tagging @AnaMedinac here. I agree the colons should be removed, I'm not sure how I missed that, lol. I know Ana did explicitly request that they be on separate rows, so I'll let her make the call here. 🙂

**Comment by LZoog** [comment]
Confirmed that we want to remove them.
