### ISSUE TITLE
End experiment UI shows up on a different unrelated experiment

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#5253]
When I approved a request to end an experiment https://experimenter.services.mozilla.com/nimbus/1-click-pin-during-onboarding, I navigated to a different experiment (
https://experimenter.services.mozilla.com/nimbus/1-click-pin-experiment) which incorrectly showed the "waiting for approval" UI:

![image](https://user-images.githubusercontent.com/1455535/118186864-395dfc00-b40c-11eb-994f-d63c0228508d.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1320)
┆Issue Number: EXP-1320

**Comment by lmorchard** [comment]
Hmm, from the admin, it looks like the "1-click pin experiment" is currently in Live/Waiting status - which would explain the approval UI. (i.e. the UI is correct insofar as Live/Waiting is when it's meant to appear)

![Capture](https://user-images.githubusercontent.com/21687/118201235-dec4a000-b40b-11eb-9116-514202f2a9bf.PNG)

But, as far as I can tell, there's no associated changelog entry to explain how it got to that status.

**Comment by lmorchard** [comment]
So, except for `isEnrollmentPaused` not being True, I'd think that this unrelated experiment is waiting for approval because it coincidentally also has a change in need of approval in Remote Settings. (I can't access RS myself to check)

**Comment by Mardak** [comment]
The experiment enrollment is now paused and it is still showing the Remote Settings button as well as "enrolling":
<img width="562" alt="image" src="https://user-images.githubusercontent.com/438537/118304621-c308da80-b49b-11eb-96cf-ee3bbaace00b.png">

https://experimenter.services.mozilla.com/nimbus/1-click-pin-experiment

https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/nimbus-desktop-experiments/records/1-click-pin-experiment has `isEnrollmentPaused | true`
