### ISSUE TITLE
Pause enrollment requests should not block launches and end requests

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#5255]
Because the pause enrollment request goes directly to remote settings and sits there, the team ran into a scenario where:
- They didn't want to pause enrollment for the experiment (https://experimenter.services.mozilla.com/nimbus/1-click-pin-experiment), so it just sat there
- All experiment launches/end requests were blocked 

They also noticed that the request seemed to go out a bit early, they launched at 4pm PST thursday, and the automated pause enrollment happened at 5pm on wednesday

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1321)
┆Issue Number: EXP-1321

**Comment by Mardak** [comment]
5pm pacific does match up with utc midnight. @punamdahiya approved the pause at 4:17 then at 4:18 came in the delayed end experiment that @k88hudson green button approved a few hours ago from nimbus-ui
```
delete | record | 1-click-pin-during-onboarding | account:experimenter
```
And again at 4:32 a duplicate delete?
```
delete | record | 1-click-pin-during-onboarding | account:experimenter
```

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

I filed an epic https://jira.mozilla.com/browse/EXP-1325 to replace this since it's a little more involved than a single bug
