### ISSUE TITLE
Additional Links on Overview page are not saved unless you set a document type

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#5270]
### Steps to reproduce
1. Create a new experiment, or modify https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-2021-05-17-addtl-links/edit/overview?show-errors
1. Add a new "Additional Link" URL (but don't specify a document type from the dropdown menu).
1. Click "Save and Continue".
2. Click back on the Overview page.

### Actual results
After saving, the "additional link" value is lost.
Clicking "Save" is misleading, since the field is still populated. You only notice the data loss once you save the page, go elsewhere, and then return and see that your link was quietly discarded. Furthermore, it looks like a case of client-vs-server error handling is in play since hitting the "Save" button then the client validation turns everything green, implying the fields are valid (even though they would ultimately fail server side validations).

![ASDasdas_asd_asd_–_Overview___Experimenter](https://user-images.githubusercontent.com/557895/118710654-6e36ce00-b7d3-11eb-8007-364432b60aed.png)

### Expected results
🤷 
I don't know if there should be some sort of error on a partially saved field (since the field requires both the Document type dropdown and text input field to be set in order to be valid+saved).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1327)
┆Issue Number: EXP-1327

**Comment by jodyheavener** [comment]
For whoever picks this up, this is technically intentional (though I agree it could be confusing) and if we do decide to not do this you'll want to remove [this bit here](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/FormOverview/documentationLink.ts#L90:L106).
