### ISSUE TITLE
Filter Version drop down by application

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#5271]
https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-2021-05-17-more-things-to-be-tested/edit/audience?show-errors
Open the dropdown menu for "Min Version".

### Actual results
Looks like we currently specify Firefox versions 11->100, but sorted in _ascending_ order.

![pdehaan-2021-05-17-more_things_to_be_tested_–_Audience___Experimenter](https://user-images.githubusercontent.com/557895/118713018-557be780-b7d6-11eb-8233-a567609358a5.png)

### Expected results
We should probably reverse the sort order (100->11), since it's far more likely that users will want something in the 88-100 range than in the 11-77 range (where current ESR version is 78.10.1, per https://whattrainisitnow.com/).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1329)
┆Issue Number: EXP-1329

**Comment by jaredlockhart** [comment]
I know it's confusing and annoying, it's not that we support desktop 11, those are for iOS whose versions are down in that lower range.  What we should be doing is filtering it by application.

**Comment by pdehaan** [comment]
Makes sense, but I also assert that sorting in descending order (even the filtered version numbers) is probably desirable since we're more likely are looking for one of the newer versions of Firefox (especially as time marches on and the list presumably grows larger and larger).
