### ISSUE TITLE
Rejection message lost after re-requesting review

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#5275]
OK, this is a bit tricky to reproduce since it requires two people to launch/approve/reject experiments.

@jaredlockhart lovingly made me a bespoke https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/just-for-peter/request-review experiment which I promptly rejected with a classic Ren and Stimpy "Mr Horse" quote:

![Just_For_Peter_🎁_–_Review___Launch___Experimenter](https://user-images.githubusercontent.com/557895/118727202-45203880-b7e7-11eb-8080-dab8df101be2.png)

Next, I bothered @jrbenny35 to re-request launch (to test that anybody can try launching anybody's experiment and it didn't have to be the original experiment creator making the request).
When @jrbenny35 requested the launch, I hit approve and it prompted me to go do more stuff in Remote Settings, but somewhere along the way, my original priceless feedback from the first launch request was lost. Not sure if that's a bug, or if we assume that the original feedback was no longer relevant since the launch requester presumably addressed whatever feedback caused the initial rejection. But I could conceivably see how that original feedback might still be a relevant piece of information which I can now no longer see.

![Just_For_Peter_🎁_–_Review___Launch___Experimenter](https://user-images.githubusercontent.com/557895/118727500-b2cc6480-b7e7-11eb-96da-1234da899b01.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1332)
┆Issue Number: EXP-1332

**Comment by jaredlockhart** [comment]
Yeah this is behaving as designed, it only shows the rejection feedback until the next change is applied, which requesting a new review counts as.  We could change this if we want, but I think the better solution here is exposing the full history of changes properly in a history page, which is logged here: https://jira.mozilla.com/browse/EXP-727
