### ISSUE TITLE
Handle stuck WAITING experiments

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#5280]
@pdehaan and I have just seen on stage that when there is a pause pending in remote settings while another experiment is ready to launch, the collection will get rolled back and both experiments will get stuck in Waiting without being resolved.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1335)
┆Issue Number: EXP-1335

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Ah, figured out why experiments were getting stuck in WAITING after pausing: https://jira.mozilla.com/browse/EXP-1375

We still need to address this case where experiments can possibly be stranded in WAITING and we don't address it, regardless of the above fix, so I'll leave this open to handle that case.

**Comment by jaredlockhart** [comment]
This can also happen if someone rejects and then rolls back the collection, then we lose the record of the rejection and the experiment is stuck in WAITING.

Now that we track the WAITING time on the server, we can use that to say that if something is in WAITING for longer than the review time AND the collection has been rolled back to signed for whatever reason, we can treat it as a time out.
