### ISSUE TITLE
Sort experiments on /nimbus/ page by recency?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#5281]
Re: https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus

Jared and I recently approved some experiments on staging, but the order of the results seems to almost be random (his is second from the top, mine is fifth, despite mine being approved more recently). Not sure if we should be sorting by `id` (ascending or descending) for each of the following sections:

- Active > Live
- Active > In Review
- Active > In Preview
- Completed
- Drafts

Probably makes marginally more sense to sort with the most recent experiments at the top of the respective tab lists. Or possibly sort by most recently updated, if that information is available.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1336)
┆Issue Number: EXP-1336

**Comment by pdehaan** [comment]
Possibly related: #4593 and #4782

**Comment by jaredlockhart** [comment]
Yeah I just noticed this too, makes it impossible to find anything, the ordering seems pretty random atm. Hopefully we can just order the QS on the backend and the frontend should just update.

**Comment by LZoog** [comment]
I just threw this into the experiment pagination epic. 👍
