### ISSUE TITLE
When a review is needed, we should tell people they need to ask someone in the UI

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5282]
When someone requests a review to launch an experiment, this message is confusing:

_All set! This experiment will launch as soon as it is approved._

We update that to this text instead:

_Please ask someone on your team with review privileges or a qualified [reviewer](__[https://mana.mozilla.org/wiki/display/FJT/Nimbus+Reviewers)](https://mana.mozilla.org/wiki/display/FJT/Nimbus+Reviewers)_ _to review and launch your experiment. You should send them this URL: {__current URL}_

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1337)
┆Issue Number: EXP-1337

**Comment by pdehaan** [comment]
Should this be specific for Desktop/Fenix/iOS?

For example, if you're launching a Fenix experiment, should we have a list of appropriate people to ping (ie: travis, james, dmose)? Or just a generic "Message somebody on your team" style message which is the same for each of the applications/platforms?
Unless we have specific mailing lists for Desktop/Fenix/iOS where we/they notify the email list that an experiment needs to be approved. At least that way people can sign up to the platforms they want to be approvers for.

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

[~pdehaan@mozilla.com] adding a suggested reviewer list for each feature might be something we want to do in the future, for now I think it's ok to link to the general list / suggest "someone on your team"
