### ISSUE TITLE
Add checkbox in the Branches page to set isEarlyStartup for features

### ISSUE THREAD

**Issue by piatra** [mozilla/experimenter#5300]
In [bug 1710919](https://bugzilla.mozilla.org/show_bug.cgi?id=1710919) we landed the ability to remotely specify if a feature value should be cached for early startup availability. We need UI to support this in the UI and in the recipe.
The recipe looks like this:

```js
...
{
  feature: {
    featureId: "cfr",
    enabled: true,
    isEarlyStartup: true,
    values: {},
  }
...
}
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1345)
┆Issue Number: EXP-1345

**Comment by k88hudson** [comment]
Also needs a non-breaking DTO schema change

**Comment by jaredlockhart** [comment]
If this is strongly tied to a feature config then can we put this in the Feature Config model instead of in the Branch?
