### ISSUE TITLE
Custom metrics are described as default metrics

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#5319]
At e.g. https://experimenter.services.mozilla.com/nimbus/default-browser-adoption-experiment/results#mozilla_default_browser, custom metrics from a Jetstream config are described as default secondary metrics. In particular, the tooltip suggests that they're in the default set of metrics, which could be confusing,

Do we need to include some information about the provenance of these metrics in the metadata Jetstream publishes?

<img width="386" alt="Screen Shot 2021-05-28 at 13 22 09" src="https://user-images.githubusercontent.com/173889/120038336-f1b4a400-bfb7-11eb-9f41-3876cb77ef88.png">

<img width="855" alt="Screen Shot 2021-05-28 at 13 24 15" src="https://user-images.githubusercontent.com/173889/120038383-0a24be80-bfb8-11eb-8725-05aa2da0299e.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1360)
┆Issue Number: EXP-1360

**Comment by emtwo** [comment]
> Do we need to include some information about the provenance of these metrics in the metadata Jetstream publishes?

Yes, I think that would be helpful. To experimenter, there is no way to differentiate between the ones that are custom vs. default. Unless we hard-coded the default ones. Probably nice if Jetstream can specify it
