### ISSUE TITLE
Fix spelling mistake when creating new experiment

### ISSUE THREAD

**Issue by chuckthemole** [mozilla/experimenter#5324]
I was looking to contribute to this repository and when I was familiarizing myself with the code base I came across a grammatical error. Overview contains `an delivery`. It should be changed to `a delivery`. This is a screen shot of the error.
![Screen Shot 2021-05-29 at 12 14 28 PM](https://user-images.githubusercontent.com/48399734/120082519-59322880-c078-11eb-9320-fc31308ae7bd.png)

The location of the error in the repository is 
`experimenter/app/experimenter/legacy-ui/templates/experiments/edit_nav_inline.html`
![Screen Shot 2021-05-29 at 12 14 45 PM](https://user-images.githubusercontent.com/48399734/120082651-eecdb800-c078-11eb-9cf6-16072485aac2.png)

I'm willing to make a pull request if you'd like. I know it's a small issue but I wanted to dip my toes in the repository 😄

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1362)
┆Issue Number: EXP-1362

**Comment by jaredlockhart** [comment]
Hi @chuckthemole ! Welcome :D 

Thanks for catching this!  Yes please do file a PR if you have time, you can [find the instructions here](https://github.com/mozilla/experimenter/blob/main/contributing.md#pull-request-process).  Ping here if you get stuck 🐧

**Comment by chuckthemole** [comment]
Thanks for the reply @jaredlockhart ! I've created a PR. I believe I followed the instructions correctly. I'm unable to change milestones. But if you're able to review it should be good to go. Thanks!
