### ISSUE TITLE
Clarification between enrollment period and duration period

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5357]
I've heard some feedback that it's confusing to understand if enrollment period is included in the duration period calculations. 

In the UI, it's calculated including it, but often we want additional X days after enrollment, so it's causing confusion if we should continue the experiment longer or end it on "calculated" time.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-1381)
┆Issue Number: EXP-1381

**Comment by LZoog** [comment]
We want a tooltip after "Experiment duration" on the Audience page as well as a tooltip on the Summary page after "Total duration", copy TBD.
