### ISSUE TITLE
Switch to using a single Feature Configuration selector on branch pages?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/experimenter#5366]
Since Feature Config is required now (#5103) and it's the same Feature Config across all branches, would it make more sense if there was a single selector for the whole page - i.e. rather than per-branch selectors that all need to be kept in sync?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1386)
┆Issue Number: EXP-1386

**Comment by lmorchard** [comment]
FWIW, if it's important to ensure the Feature Configuration name is included in each branch as context for the feature on/off switch, it would be easier to just have a label there than a fully interactive select

**Comment by LZoog** [comment]
Ohh nice, yeah, @AnaMedinac mentioned to me last week that she's thought about users selecting this somewhere else. I'll use that fancy `needs-product` label here.
