### ISSUE TITLE
UserWarning: class incompatibility, duplicated operationId in OpenAPI schema

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5413]
This occurs in tests and in CI.

!image-2021-06-09-18-29-06-124.png!

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-1407)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16456/image-2021-06-09-18-29-06-124.png">image-2021-06-09-18-29-06-124.png</a>
┆Issue Number: EXP-1407

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

[~lzugai@mozilla.com] this is warning about the V1/V2 legacy APIs when generating the docs here:

https://htmlpreview.github.io/?https://github.com/mozilla/experimenter/blob/main/app/experimenter/docs/swagger-ui.html ( https://htmlpreview.github.io/?https://github.com/mozilla/experimenter/blob/main/app/experimenter/docs/swagger-ui.html )

Is this blocking or breaking anything?

**Comment by LZoog** [comment]
@jaredlockhart Not blocking or breaking anything, it's low priority. 👍

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Looks like the solution is to override the AutoSchema objects (which right now are completely auto generated) and override the `get_operation_id_base` method where appropriate, but I think that has to be done on a per view basis, which we're not doing.

https://github.com/encode/django-rest-framework/issues/6844#issuecomment-593987675
