### ISSUE TITLE
Support relevant metrics in Jetstream for CFR experiments

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5473]
The Cirrus analysis milestone 1 - work is tracked in this [project board](https://github.com/mozilla/jetstream/projects/3).

These parts have dependencies on things landing in same time frame as M1. There is value to landing these ASAP, as current x-man/CFR experiments can start leveraging and giving feedback:

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/EXP-6)

**Comment by jaredlockhart** [comment]
I believe we can support this using outcomes/custom experiment jetstream configs.  Any work that must be done in jetstream should be filed upstream in the jetstream repo.
