### ISSUE TITLE
Experimenter Monitoring parity with Grafana

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5475]
Parity with experimenter A/A experiments with Grafana monitoring. Ensuring that the connections work and the slug naming works to populate.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-48)

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

This is superceded by the Visualization Add Monitoring Support epic.

**Comment by shell1** [comment]
implemented!
