### ISSUE TITLE
Audience for first start-up users should target Windows only?

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5479]
Per today's team meeting and @mythmon's suggestion (since detecting first run can be not entirely reliable on other OSes).

![Mozilla](https://user-images.githubusercontent.com/557895/89059558-42b32780-d316-11ea-9794-3f33602ccf5a.png)UNITO-UNDERSCORE!Experimenter!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-219)

**Comment by jaredlockhart** [comment]
Any changes to targeting parameters can be filed as PRs against the targeting configs.
