### ISSUE TITLE
[FE] Add metric count section for remaining segments

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5481]
blocked on segment support https://github.com/mozilla/jetstream/issues/58

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-246)

**Comment by emtwo** [comment]
This involves adding a `Show other segments` dropdown similar to this under the metric count tables:
![Screen Shot 2021-08-18 at 1 50 31 PM](https://user-images.githubusercontent.com/784781/129947416-a2b06bca-c197-4bca-89c0-ba200116d23b.png)

The [metric count table ](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/PageResults/TableMetricCount/index.tsx) would look the same but be shown separately for each segment in this dropdown.

**Comment by jaredlockhart** [comment]
Closing this until we have more support for data visualization and we can rethink the segmentation support more wholistically.
