### ISSUE TITLE
Experiment data scientists should be included when creating an experiment

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5483]
It should be possible to assign a data science owner to an experiment at creation/edit time and this would be displayed in the visualization page.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-240)

**Comment by data-sync-user** [comment]
➤ Marina Samuel commented:

This includes adding it as an input when creating the experiment, saving it to the database, and making sure it's available to the visualizations page.

**Comment by shell1** [comment]
if we link to the data science ticket - that will be enough - as we change off DS sometimes so should go there.

**Comment by shell1** [comment]
https://github.com/mozilla/experimenter/issues/6235
