### ISSUE TITLE
Labels on Review & Launch don't match intake form

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5513]
https://stage.experimenter.nonprod.dataops.mozgcp.net/*version*

```javascript
{ "commit": "7906f4618b0f5f0526c44fe9f7ba1d0f68c8bb08",
  "source": "https://github.com/mozilla/experimenter.git",
  "build": "https://circleci.com/gh/mozilla/experimenter/19125" }
```

Minor nit, but makes it a bit trickier to fix any potential issues if the field labels don't match.

## [/edit/audience](https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/pdehaan-2020-12-07-005/edit/audience)
![pdehaan](https://user-images.githubusercontent.com/557895/101418165-113d0080-38a2-11eb-8700-f3ec4e5aa35d.png)UNITO-UNDERSCORE!2020-12-07!UNITO-UNDERSCORE!005_–_Audience!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!Experimenter!

- - -
## [/request-review](https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/pdehaan-2020-12-07-005/request-review)
![pdehaan](https://user-images.githubusercontent.com/557895/101418145-084c2f00-38a2-11eb-9ba0-b4e85698311f.png)UNITO-UNDERSCORE!2020-12-07!UNITO-UNDERSCORE!005_–_Review!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!Launch!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!Experimenter!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-680)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

This is a UX question, AnaMedinac k88hudson should we adjust the wording on the table to what Peter has suggested?

**Comment by data-sync-user** [comment]
➤ Ana Medinac commented:

Ah yes! They should definitely match. Let's update:

  * Population % to Percent of clients and
  * Custom audience to Advanced Targeting. 
Let's leave Minimum version as is. I'll update the Figma specs btw.

**Comment by jaredlockhart** [comment]
This UI has all changed since this was filed.
