### ISSUE TITLE
Review & Launch page is the only page with right aligned navigation

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5522]
https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/pdehaan-2020-12-08-003a/request-review

![pdehaan](https://user-images.githubusercontent.com/557895/101548874-86bbd600-3961-11eb-93a6-8771c7fdd718.png)UNITO-UNDERSCORE!2020-12-08!UNITO-UNDERSCORE!003a_–_Review!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!Launch!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!Experimenter!

versus:

![pdehaan](https://user-images.githubusercontent.com/557895/101548932-9e935a00-3961-11eb-94d4-dfbc41265240.png)UNITO-UNDERSCORE!2020-12-08!UNITO-UNDERSCORE!003a_–_Overview!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!Experimenter!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-709)

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Screenshots above also show how the "Public description" and "Hypothesis" fields have line breaks in the <textarea> fields, but condense to single lined blobs in the Review page, although there should be other tracking issues for that.

**Comment by LZoog** [comment]
Closing this since the "Launch" button no longer exists. It's true the flows (launch experiment, end experiment, soon end enrollment) start on the left (at the top of the Summary page), but I don't think we need to left-align the Save/Next buttons to match. Please feel free to reopen if you disagree @pdehaan :)
