### ISSUE TITLE
New Tab Integration

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5523]
┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/EXP-691)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Meeting with Vicky tomorrow to discuss overall status of NewTab in terms of engineering and experimentation goals. Based on that, we will have more information. Search meeting with Julie scheduled next week to identify if Search is a potential customer.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

These efforts are currently being tracked in Bugzilla here: https://as-bugzy.herokuapp.com/feature/1691400

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

We are now feature complete as of Feb 19 Nightly and ready for A/A testing. Documentation for feature is here:

https://mana.mozilla.org/wiki/display/FJT/New+Tab+-+Nimbus+Feature+Documentation ( https://mana.mozilla.org/wiki/display/FJT/New+Tab+-+Nimbus+Feature+Documentation )

I am following up with QA to verify test cases.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Engineering is complete, A/A experiment has been launched. Need to onboard Teon and a NewTab engineer to Nimbus as well.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Onboarded Teon and Mike onto the Console. Many questions asked surrounding current integration and opportunities in experimentation using Nimbus. Potential opportunities in collaboration between NewTab and Nimbus for experimentation beyond this initial integration.

**Comment by data-sync-user** [comment]
➤ Ana Medinac commented:

The code is integrated, the New Tab team is onboarded and we have run an A/A experiment with the team. However, we are putting this on hold until the team is ready to start experimenting on the New New Tab UI/functionality.  We will call this closed once we have helped the New Tab team run an A/B experiment.

**Comment by jaredlockhart** [comment]
Let's close this and file a new one when more focus on the New Tab arrives.
