### ISSUE TITLE
Fenix-specific probes in Desktop experiments?

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5539]
1. Create a new Firefox **Desktop** experiment.
1. Click the "Metrics" link in the left nav.
1. Set the Primary Probe set to "Fenix Bookmarks Probes".
> It's a bit weird that a Desktop app can add mobile probe sets.

- - -
![pdehaan](https://user-images.githubusercontent.com/557895/102140624-5d44f380-3e14-11eb-827e-478e0ce88a49.png)UNITO-UNDERSCORE!2020-12-14!UNITO-UNDERSCORE!003_–_Overview!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!Experimenter!

![pdehaan](https://user-images.githubusercontent.com/557895/102140798-aa28ca00-3e14-11eb-8c31-52fc638b2c62.png)UNITO-UNDERSCORE!2020-12-14!UNITO-UNDERSCORE!003_–_Metrics!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!Experimenter!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-756)

**Comment by jaredlockhart** [comment]
Outcomes are now filtered by application 👍
