### ISSUE TITLE
A few nimbus-ui files are missing copyright headers

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5543]
Not a big issue, but I think we've noted this in a couple PRs when new files get added sans copyright. But it can be fun to play w/ `git grep` and use some regexes. 🤷 

```sh
git rev-parse --short HEAD # "81d5614e"

git grep -L "This Source Code Form is subject" app/experimenter/nimbus-ui/ | grep -E "\.(jsx?|tsx?)$"
```

### Current results
```
app/experimenter/nimbus-ui/.eslintrc.js
app/experimenter/nimbus-ui/apollo.config.js
app/experimenter/nimbus-ui/src/components/AppErrorBoundary/index.stories.tsx
app/experimenter/nimbus-ui/src/components/TableVisualizationRow/index.tsx
app/experimenter/nimbus-ui/src/hooks/index.ts
app/experimenter/nimbus-ui/src/types/createExperiment.ts
app/experimenter/nimbus-ui/src/types/getAllExperiments.ts
app/experimenter/nimbus-ui/src/types/getConfig.ts
app/experimenter/nimbus-ui/src/types/getExperiment.ts
app/experimenter/nimbus-ui/src/types/globalTypes.ts
app/experimenter/nimbus-ui/src/types/updateExperimentAudience.ts
app/experimenter/nimbus-ui/src/types/updateExperimentBranches.ts
app/experimenter/nimbus-ui/src/types/updateExperimentOverview.ts
app/experimenter/nimbus-ui/src/types/updateExperimentProbeSets.ts
app/experimenter/nimbus-ui/src/types/updateExperimentStatus.ts
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-843)

**Comment by jaredlockhart** [comment]
Why do we put copyright in individual files when we have the license at the top level?

**Comment by jaredlockhart** [comment]
And why only in frontend files?

**Comment by pdehaan** [comment]
Was #4436.
We could also argue if we need them at all since they are mostly .ts/.tsx files which get transpiled and removed in the final main.js anyways. Plus its an internal only tool and not a distributed library. 
I know a few projects use copyright headers, and we've even had linters for them in the past, but I think it's been a definite minority of the projects I've worked on.

**Comment by jaredlockhart** [comment]
Okay as per https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=130927170 we should be including the MPL2 header in every source file, so let's go through and do that.
