### ISSUE TITLE
As a QA person, I want to be able to easily update the QA status, so that I can reduce the number of channels I have to update

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5549]
**Why:** 
 As a QA person, I want to have the ability to leave QA sign-offs as comments.

QA sign-offs should be in Nimbus so that they are visible and easily accessible by the whole team: QA, Engineering, and experiment owners. Currently QA leaves their sign-offs in both Experimenter and Jira, however, it's often lost in Jira tickets due to there being many comments in the thread. If we have a place for QA to sign-off within the Nimbus flow, they would be able to reduce the redundancy of having to document the Sign-Off status in multiple locations (email, Jira, and other tracking bugs [Bugzilla]). Overall, it could help experiment owners and QA have one source of truth and smooth out the process required.

If the comments persist across different Nimbus states ( for example: QA --> Draft state), it's easier for QA and experiment owners to track the changes required, and in the future for QA reference the previous QA sign-off state / feedback.

Having comments available, helps collaborate more tightly with QA and de-risk launches. 

**Specs**

**[To be completed]**

**Acceptance criteria**

* Users are able to leave feedback/comments in Nimbus
* Comments persist regardless of the state of the Nimbus experiment
* [...more to be added]

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/EXP-845)

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Is the intention:
(a) to move all QA conversation to Experimenter and stop using Jira for comments;
(b) to leave most of the conversation/back-and forth in Jira but only use comments in Experimenter to describe changes in status?

If (a), there are a lot of features such as cross-linking to bugs filed, notifications for mentioning people, rich text support folks would lose from Jira – is that something we've thought through?
If (b), how do you intend to make sure people know when to use which channel for what? Why are comments the best way handle communicating status v.s. some kind of structured field/input? (For example, is it because we need comments for other things? If so, what?)

**Comment by data-sync-user** [comment]
➤ Krupa Raj commented:

The current intention is closer to (b) to leave most of the conversation/back-and forth in Jira but only use comments in Experimenter to describe changes in status - we already follow this model with experimenter where the experiment-related chatter happens in the PI Jira ticket and the sign-offs/status updates happen in the comment section.

The advantage Jira has is that teams get notified via email whenever the Jira ticket gets updated. If we ever want to move all discussions to Nimbus, that will be a must-have.

There was a discussion within the team about this workflow which can be tracked @ https://docs.google.com/spreadsheets/d/1QvQns64FywD8OzTxvcso2LNQ6UUPaLQAXVDXzJM0W6s/edit#gid=0 ( https://docs.google.com/spreadsheets/d/1QvQns64FywD8OzTxvcso2LNQ6UUPaLQAXVDXzJM0W6s/edit#gid=0 )

**Comment by jaredlockhart** [comment]
Yes leaving qa feedback directly in experimenter is a good idea and something I'd like to see but we'll have to plan and scope it as an epic in the future so I'm closing this for now.
