### ISSUE TITLE
[Nimbus] Add ability to target specific platforms

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5553]
Audience section is missing “Platform”; we ship experiments which only run on Windows.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-824)

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Possible dupe of https://github.com/mozilla/experimenter/issues/3164

**Comment by jaredlockhart** [comment]
Platforms can currently be specified using advanced targeting, if a need for a platform specific field we can revisit it.
