### ISSUE TITLE
Leftover test class from pre-mutation merge

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5586]
I just noticed we still have this test class:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/tests/api/v5/test_serializers.py#L42

Whose tests should be merged in here: 

https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/tests/api/v5/test_serializers.py#L729

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-968)

**Comment by jaredlockhart** [comment]
This is done.
