### ISSUE TITLE
Consolidate certain error message strings for consistency

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5590]
See https://github.com/mozilla/experimenter/pull/4591#discussion_r574092615

We're using a `SUBMIT_ERROR` const in some files, `SUBMIT_ERROR_MESSAGE` in another, and a string with the same message in others.

Let's consolidate our messaging/use the same var reference. See Peter's comment for potential other error strings we can make consistent.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-943)

**Comment by anthonytran7757** [comment]
Hey @jodyheavener, I'd like to pick this one up!
