### ISSUE TITLE
Allow the Nimbus home page to paginate through experiments

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5594]
This epic will give us the ability to list experiments by status and paginate through them.

As of filing our homepage directory returns all experiments in the database, with the idea that because there will almost certainly never be enough experiments to bog down the page that the client can handle everything. So we now need to divide them up by status and display a certain amount per “page”.

This epic previously also included sorting (beyond status tabs), but we have decided to leave that to a future epic.

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/EXP-944)

**Comment by jaredlockhart** [comment]
Now that we have things sorted by status and filterable, I'll close this and we can refile if we need to make any future changes.
