### ISSUE TITLE
Add a link to the preview collection on the launch page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5596]
To help people find their DTO when an experiment is in Preview we should add a link either to the whole preview collection and possibly instructions on how to configure a local test browser to point to it for testing.

We'll probably want to add the public remote settings url as an env var to each of stage and prod and add it to the configuration GQL query.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-990)

**Comment by jaredlockhart** [comment]
This is done.
