### ISSUE TITLE
Add documentation for Jetstream -> Visualization details

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5601]
It should include information such as:

* Where Jetstream data is pulled from
* What is the format of Jetstream data
* How the experimenter API layer parses the jetstream data
* What the output of the API looks like
* How the data is used on the frontend

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-960)

**Comment by jaredlockhart** [comment]
Any future requirements for documentation for system integration can be PRed into https://github.com/mozilla/experimenter-docs
