### ISSUE TITLE
Visualization - Add Context

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5616]
This epic includes adding context to the results page including branch screenshots, custom summary text, and a responsible data scientist

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/EXP-1053)

**Comment by data-sync-user** [comment]
➤ Marina Samuel commented:

Work has started for grouping search & usage metrics to reduce visual clutter.

**Comment by data-sync-user** [comment]
➤ Rob Hudson commented:

I've begun to dig into the code and figure out where to make this change, and along the way picking up some knowledge about Typescript.

**Comment by data-sync-user** [comment]
➤ Rob Hudson commented:

A PR was submitted and is currently going through a review cycle. The expectation is this review updates will land and this can be merged in the next week or so.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Marina Samuel Rob Hudson still in progress on this epic? Any expected timeline on when we should expect to hand this off to QA?

**Comment by jaredlockhart** [comment]
The work tracked in this epic is complete and new epics can been filed for screenshots and other knowledge sharing, closing this.
