### ISSUE TITLE
Should feature ids be unique per-application v.s. globally unique?

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5627]
One challenge I think we're going to run into is that manifests for features will always live in different locations (i.e. in each application) and it will be hard to enforce uniqueness across all of them at that level.

Would it be reasonable to make feature ids unique per-application instead?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1092)

**Comment by jaredlockhart** [comment]
This will be addressed when we switch to ingesting feature configs from external repos.
