### ISSUE TITLE
[Nimbus] "Expected number of clients" cannot be 0, but 0 is a valid number for that field

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5639]
**[Steps to reproduce]:**

1. Navigate to the https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/ website.
1. Create a new experiment.
1. Fill all sections except the "Expected number of clients" field in the "Audience" section.
1. Write "0" in the "Expected number of clients" field and press "Save"
1. Observe the "Save and Continue" button and the "Review & Launch" section from the outline section.

**[Expected result]:**

* The "Save and Continue" button is actionable and no missing details pointed out in the outline section.

**[Actual result]:**

* The "Save and Continue" button is not actionable and the "Missing details in:" section is displayed, but no section is linked there.

**[Notes]:**

* Attached is a screen recording of the issue.

![expected number of clients cannot be 0](https://user-images.githubusercontent.com/18304511/112340491-42aed000-8cc9-11eb-82ec-a3b72f7faed4.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1109)

**Comment by jaredlockhart** [comment]
This is fixed now.
