### ISSUE TITLE
Feature is enabled but not shown in UI

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5641]
Just saw this in stage, no feature config is selected but it's complaining that it is enabled:

![](https://user-images.githubusercontent.com/119884/113599804-225a0c00-960d-11eb-917e-0da998978644.png)

![](https://user-images.githubusercontent.com/119884/113599911-4a496f80-960d-11eb-823a-5b1b343ec044.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1171)

**Comment by jaredlockhart** [comment]
this is fixed now.
