### ISSUE TITLE
Move some getStatus checks to new state-specific experiment properties

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5643]
In EXP-1153 we'll add some handy boolean properties to the experiment query, such as isEditable. Once these are in place let's start using them in the frontend and re-evaluate the current frontend usage of the getStatus helper. It may no longer be needed or it could be refactored to possibly split up status and publishStatus states.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1158)

**Comment by jaredlockhart** [comment]
If this becomes critical we can reopen/refile.
