### ISSUE TITLE
Roles - Managing permissions for launch/review of experiments

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5649]
Manage permissions for which users can launch and review experiments, facilitating moving the current RS-based review workflow into the console

**Background**

To prevent errors during experiment QA and launch, it is important to have multiple parties review and validate an experiment.  To facilitate this rigorously in Experimenter, we can add specific roles for experiment creators, reviewers, and QA.  By restricting the set of permissions to a given role, we can enforce that the correct parties are involved at each stage of an experiments lifecycle.

**Proposal:** [https://docs.google.com/document/d/1r8oI_Hxe5JQcOejqZcSziX1Aso20AFGBToTFu3BE5j8/edit#heading=h.jc8k67jwqhb8](https://docs.google.com/document/d/1r8oI_Hxe5JQcOejqZcSziX1Aso20AFGBToTFu3BE5j8/edit#heading=h.jc8k67jwqhb8)

**Goal:** Reduce experiment launch errors by enforcing multiple parties are involved in the launch/review process

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/EXP-1135)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Design has been deprioritized to begin designing rollouts. There may be roles/permissions work that can move forward without design.

**Comment by jaredlockhart** [comment]
Keeping this open to fill in soon.
