### ISSUE TITLE
Controlling & Visualizing Interactions - Automates the manual effort of determining conflicting experiments on populations.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5652]
Automates the manual effort of determining conflicting experiments on populations.

**Why?**

* Important for Search and New Tab
* Important for First Run
* Evidence of failures caused in Normandy, identified as a long held risk

**KR**

Velocity, and Reliability (not a KR, but important long term)

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/EXP-1136)

**Comment by jaredlockhart** [comment]
Closing as a duplicate of https://github.com/mozilla/experimenter/issues/6171
