### ISSUE TITLE
[Reporting] Add ending reason options to Normandy

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5656]
Ending reasons will need to be added somewhere into normandy
Initial thoughts maybe placing it into the model EnabledStates
Will need to check with mythmon

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1164)

**Comment by tiftran** [comment]
Closing for now, as it currently isn't relevant for now and there existing field for it
