### ISSUE TITLE
Add more state-specific booleans to Experiment query

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5657]
The Nimbus UI is doing a lot of checking on the various status and publish status values to infer specific states on an experiment (is it launched? is it editable?). Let's move some is that to properties on the Experiment query (e.g. isEditable, isLaunched, more if you can think of them). Let the backend figure this out for us.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1153)

**Comment by jaredlockhart** [comment]
The spirit of this is correct but we can address it on a case by case basis as we continue to work on the mutation.
