### ISSUE TITLE
Automated Population Sizing Tool - Allows experiment owners to determine their population size without DS

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5662]
**Business Outcome**

Allows experiment owners to determine their population size without DS.

**Why?**

* Save a lot of DS time, lots of requests
* Supports Search and New Tab

**Background**

While I was launching the A/A experiment for New Tab, we got stuck on the population sizing portion. It felt like I could directly message Tim (or whichever DS scientist I already have a working relationship with) to ask them to do population sizing. I think for some of these experiments that are Nightly and lower risk, it feels like we can reduce the number of steps required or messages sent to get an estimate for what the population should be.

**Goal:** Have a tool as a product manager that I can rely on to do quick / easy population sizing.

**Metric**: Reduce number of dependencies on DS

**Outcomes**

By X date we will have Y that will do Z. // Everything we do has a target time frame in which we’re aiming to influence a metric. By defining the timeframe, we have a timeline in which to make scope tradeoffs, and a bounding box for options on implementation. How do you deal with the fact that it might not be accomplishable in that time frame? If the goal exceeds the time frame that is needed, we either renegotiate the timeframe or cancel the charter.

**Moonshot**

By X+N date we will have Y+N that will do Z+N. // Sometimes when architecting a solution it’s important to know what types of features and experiences are coming just beyond. The moonshot is an opportunity to outline a far future state which allows us to either technically consider, or intentionally ignore considerations for a later date.

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/EXP-1140)

**Comment by data-sync-user** [comment]
➤ Shell Escalante commented:

Does anyone know if this has moved forward at all?  or if there was a direction around it?

**Comment by jaredlockhart** [comment]
Automated population sizing has long been a dream of experimentation at Mozilla.  As yet there is no movement on this topic so I will close this.
