### ISSUE TITLE
Complete experiment should not show incomplete warning

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5665]
The pill in this experiment says it's complete but the warning says it isn't:

https://experimenter.services.mozilla.com/nimbus/multi-stage-onboarding-ask-and-show-to-pin/results

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1142)

**Comment by jaredlockhart** [comment]
That's expected behaviour while jestream is still processing results.
