### ISSUE TITLE
[Reporting]Add UI to Experiment Legacy to flag relaunch experiments

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5666]
We should introduce a field to the overview form with a question along the lines of “is this experiment a relaunch of a previous experiment”
May want to consider whether we want to indicate which experiment
Will need to confirm with Shell for the structure/questions

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1162)

**Comment by tiftran** [comment]
Closing for now, as it currently isn't relevant for now
