### ISSUE TITLE
Intermittent toolkit/components/nimbus/test/browser/browser_remotesettingsexperimentloader_remote_defaults.js | Called by RS sync - 0 == 1 - JS frame :: browser/browser_remotesettingsexperimentloader_remote_defaults.js :: test_remote_fetch_and_ready

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5669]
**Filed by:** csabou [at] mozilla.com
**Parsed log:** https://treeherder.mozilla.org/logviewer?job_id=335603971&repo=autoland
**Full log:** https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/RmPeeGXkRtKCgK1-sI5iqQ/runs/0/artifacts/public/logs/live_backing.log
**Reftest URL:** https://hg.mozilla.org/mozilla-central/raw-file/tip/layout/tools/reftest/reftest-analyzer.xhtml#logurl=https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/RmPeeGXkRtKCgK1-sI5iqQ/runs/0/artifacts/public/logs/live_backing.log&only_show_unexpected=1

---
```
[task 2021-04-06T19:17:49.175Z] 19:17:49     INFO - TEST-PASS | toolkit/components/nimbus/test/browser/browser_remotesettingsexperimentloader_remote_defaults.js | Set by remote defaults - 3 == 3 - 
[task 2021-04-06T19:17:49.175Z] 19:17:49     INFO - Buffered messages finished
[task 2021-04-06T19:17:49.176Z] 19:17:49     INFO - TEST-UNEXPECTED-FAIL | toolkit/components/nimbus/test/browser/browser_remotesettingsexperimentloader_remote_defaults.js | Called by RS sync - 0 == 1 - JS frame :: chrome://mochitests/content/browser/toolkit/components/nimbus/test/browser/browser_remotesettingsexperimentloader_remote_defaults.js :: test_remote_fetch_and_ready :: line 102
[task 2021-04-06T19:17:49.176Z] 19:17:49     INFO - Stack trace:
[task 2021-04-06T19:17:49.176Z] 19:17:49     INFO - chrome://mochitests/content/browser/toolkit/components/nimbus/test/browser/browser_remotesettingsexperimentloader_remote_defaults.js:test_remote_fetch_and_ready:102
[task 2021-04-06T19:17:49.176Z] 19:17:49     INFO - GECKO(1543) | console.debug: RSLoader:
[task 2021-04-06T19:17:49.177Z] 19:17:49     INFO - GECKO(1543) |   Setting remote defaults for feature: aboutwelcome: {"variables":{"remoteValue":42},"enabled":true,"targeting":"true"}
[task 2021-04-06T19:17:49.177Z] 19:17:49     INFO - Not taking screenshot here: see the one that was previously logged
[task 2021-04-06T19:17:49.178Z] 19:17:49     INFO - TEST-UNEXPECTED-FAIL | toolkit/components/nimbus/test/browser/browser_remotesettingsexperimentloader_remote_defaults.js | Uncaught exception - at chrome://mochitests/content/browser/toolkit/components/nimbus/test/browser/browser_remotesettingsexperimentloader_remote_defaults.js:104 - TypeError: can't access property "args", stub.firstCall is null
[task 2021-04-06T19:17:49.178Z] 19:17:49     INFO - Stack trace:
[task 2021-04-06T19:17:49.178Z] 19:17:49     INFO - test_remote_fetch_and_ready@chrome://mochitests/content/browser/toolkit/components/nimbus/test/browser/browser_remotesettingsexperimentloader_remote_defaults.js:104:1
[task 2021-04-06T19:17:49.178Z] 19:17:49     INFO - Leaving test bound test_remote_fetch_and_ready
[task 2021-04-06T19:17:49.178Z] 19:17:49     INFO - GECKO(1543) | console.debug: RSLoader:
[task 2021-04-06T19:17:49.179Z] 19:17:49     INFO - GECKO(1543) |   Setting remote defaults for feature: newtab: {"variables":{"remoteValue":3},"enabled":true,"targeting":"true"}
[task 2021-04-06T19:17:49.179Z] 19:17:49     INFO - GECKO(1543) | MEMORY STAT | vsize 2809MB | residentFast 311MB | heapAllocated 130MB
[task 2021-04-06T19:17:49.180Z] 19:17:49     INFO - TEST-OK | toolkit/components/nimbus/test/browser/browser_remotesettingsexperimentloader_remote_defaults.js | took 28ms```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1175)

**Comment by data-sync-user** [comment]
➤ bugzilla-integration commented:

(releasemgmtaccount-bot@mozilla.tld) commented: 
{quote}Set release status flags based on info from the regressing bug 1700760{quote}

**Comment by data-sync-user** [comment]
➤ bugzilla-integration commented:

(releasemgmtaccount-bot@mozilla.tld) commented: 
{quote}Set release status flags based on info from the regressing bug 1700760{quote}

**Comment by data-sync-user** [comment]
➤ bugzilla-integration commented:

(orangefactor@bots.tld) commented: 
{quote}14 failures in 3854 pushes (0.004 failures/push) were associated with this bug in the last 7 days.

Repository breakdown:

  * autoland: 14

Platform and build breakdown:

  * linux1804-64: 2
  * debug: 1
  * opt: 1
  * macosx1014-64-qr: 4
  * opt: 2
  * debug: 2
  * linux1804-64-qr: 2
  * opt: 1
  * debug: 1
  * windows7-32: 2
  * opt: 1
  * debug: 1
  * windows10-64-qr: 2
  * debug: 1
  * opt: 1
  * windows10-64: 2
  * debug: 1
  * opt: 1

For more details, see:
https://treeherder.mozilla.org/intermittent-failures/bugdetails?bug=1703355&startday=2021-04-05&endday=2021-04-11&tree=all{quote}

**Comment by data-sync-user** [comment]
➤ bugzilla-integration commented:

(ERROR on Update): 
{quote} event attempted:	{"action": "modify", "time": "2021-04-12T16:00:33", "user": {"id": 476157, "login": "andrei.br92@gmail.com", "real_name": "Andrei Oprea [:andreio]"}, "changes": [{"field": "assigned_to", "removed": "nobody@mozilla.org", "added": "andrei.br92@gmail.com"}, {"field": "cc", "removed": "", "added": "andrei.br92@gmail.com"}], "target": "bug", "routing_key": "bug.modify:assigned_to,cc"}{quote}

**Comment by data-sync-user** [comment]
➤ bugzilla-integration commented:

(orangefactor@bots.tld) commented: 
{quote}6 failures in 4255 pushes (0.001 failures/push) were associated with this bug in the last 7 days.

Repository breakdown:

  * autoland: 4
  * mozilla-central: 2

Platform and build breakdown:

  * linux1804-64-asan: 2
  * opt: 2
  * linux1804-64: 4
  * debug: 4

For more details, see:
https://treeherder.mozilla.org/intermittent-failures/bugdetails?bug=1703355&startday=2021-04-12&endday=2021-04-18&tree=all{quote}

**Comment by data-sync-user** [comment]
➤ bugzilla-integration commented:

(orangefactor@bots.tld) commented: 
{quote}5 failures in 3224 pushes (0.002 failures/push) were associated with this bug in the last 7 days.

Repository breakdown:

  * autoland: 3
  * mozilla-central: 2

Platform and build breakdown:

  * linux1804-64-asan: 1
  * opt: 1
  * linux1804-64: 4
  * debug: 3
  * opt: 1

For more details, see:
https://treeherder.mozilla.org/intermittent-failures/bugdetails?bug=1703355&startday=2021-04-19&endday=2021-04-25&tree=all{quote}

**Comment by data-sync-user** [comment]
➤ bugzilla-integration commented:

(orangefactor@bots.tld) commented: 
{quote}10 failures in 3706 pushes (0.003 failures/push) were associated with this bug in the last 7 days.

Repository breakdown:

  * mozilla-central: 3
  * mozilla-beta: 2
  * autoland: 4
  * try: 1

Platform and build breakdown:

  * linux1804-64: 8
  * debug: 7
  * opt: 1
  * linux1804-64-asan: 2
  * opt: 2

For more details, see:
https://treeherder.mozilla.org/intermittent-failures/bugdetails?bug=1703355&startday=2021-04-26&endday=2021-05-02&tree=all{quote}

**Comment by data-sync-user** [comment]
➤ bugzilla-integration commented:

(orangefactor@bots.tld) commented: 
{quote}10 failures in 3706 pushes (0.003 failures/push) were associated with this bug in the last 7 days.

Repository breakdown:

  * mozilla-central: 3
  * mozilla-beta: 2
  * autoland: 4
  * try: 1

Platform and build breakdown:

  * linux1804-64: 8
  * debug: 7
  * opt: 1
  * linux1804-64-asan: 2
  * opt: 2

For more details, see:
https://treeherder.mozilla.org/intermittent-failures/bugdetails?bug=1703355&startday=2021-04-26&endday=2021-05-02&tree=all{quote}

**Comment by data-sync-user** [comment]
➤ bugzilla-integration commented:

(orangefactor@bots.tld) commented: 
{quote}10 failures in 3706 pushes (0.003 failures/push) were associated with this bug in the last 7 days.

Repository breakdown:

  * mozilla-central: 3
  * mozilla-beta: 2
  * autoland: 4
  * try: 1

Platform and build breakdown:

  * linux1804-64: 8
  * debug: 7
  * opt: 1
  * linux1804-64-asan: 2
  * opt: 2

For more details, see:
https://treeherder.mozilla.org/intermittent-failures/bugdetails?bug=1703355&startday=2021-04-26&endday=2021-05-02&tree=all{quote}

**Comment by data-sync-user** [comment]
➤ bugzilla-integration commented:

(phab-bot@bmo.tld) commented: 
{quote}{quote}

**Comment by data-sync-user** [comment]
➤ bugzilla-integration commented:

(orangefactor@bots.tld) commented: 
{quote}6 failures in 3279 pushes (0.002 failures/push) were associated with this bug in the last 7 days.

Repository breakdown:

  * autoland: 4
  * mozilla-central: 2

Platform and build breakdown:

  * linux1804-64-asan: 2
  * opt: 2
  * linux1804-64-shippable: 1
  * opt: 1
  * linux1804-64: 3
  * debug: 3

For more details, see:
https://treeherder.mozilla.org/intermittent-failures/bugdetails?bug=1703355&startday=2021-05-03&endday=2021-05-09&tree=all{quote}

**Comment by data-sync-user** [comment]
➤ bugzilla-integration commented:

(andrei.br92@gmail.com) commented: 
{quote}Pretty confident bug 1709360 fixed this intermittent.{quote}

**Comment by data-sync-user** [comment]
➤ bugzilla-integration commented:

(andrei.br92@gmail.com) modified the status: 
{quote} resolution:	DUPLICATE
 status:	RESOLVED{quote}

**Comment by jaredlockhart** [comment]
Bugzilla reports this as resolved.
