### ISSUE TITLE
Nimbus UI shows ending message when pausing

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5678]
When an experiment is pausing in remote settings, the nimbus ui shows the end requested message:

![](https://user-images.githubusercontent.com/119884/115253863-cc03c780-a0fa-11eb-9882-61ef2f577fcf.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1209)

**Comment by jaredlockhart** [comment]
I believe this is fixed now.
