### ISSUE TITLE
Rename notions of Kinto to Remote Settings

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5685]
The Experimenter code base mentions Kinto instead of Remote Settings.

Kinto is an implementation detail, the service on which Experimenter relies is Remote Settings.

This is can be confusing for those unfamiliar with Kinto, whereas Remote Settings is an official service at Mozilla.

Plus, there is a chance that the Remote Settings service would be provided by a different implementation, under a different name.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1228)

**Comment by leplatrem** [comment]
:man_shrugging:
