### ISSUE TITLE
Add external links to list page

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#570]
We should add the bar of external links (ie bugzilla ticket, monitoring dashboard) to the list page so it's easier to check on experiments from the landing page.

**Comment by shell1** [comment]
we are closing out a bunch of these original "we could possible do x" UX enhancements.  Mid-year after 2 quarters of development - we will look at the UX and see all up what changes will be truly helpful to the users.  Don't want a bunch of ideas in the backlog that might get worked on individually - and conflict with more recent changes.
