### ISSUE TITLE
Add clearer guidance and instructions about new review flow to Nimbus UI

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5700]
We recently launched the new review/approval UI that requires two parties to be able to launch/end an experiment.  Because this differs from the old launch/end flow (which was operable by a single user), users do not understand the new flow and are getting stuck.  Multiple users have reported requesting a launch/end and then sitting and waiting for the experiment to show in Remote Settings without understanding that they need to tag a second person to review/approve in Experimenter before that happens.

Perhaps we can expand the guidance text in the UI to more clearly guide users about what they have to do next?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1255)

**Comment by LZoog** [comment]
Closing this - users should know what to do next now that the summary and review/launch pages have been merged. They'll be presented with "action text" which differs per flow.
