### ISSUE TITLE
Add docs about testing to this repo

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5704]
There are no docs on what/why/how we test either experimenter or nimbus within this repo.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1263)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

We have a "Running tests and checks" section in the README, but we have #5048 filed specifically for integration tests. I was going to close one of these as a dupe, and we probably still can, but jrbenny35 seems like this ticket is about reworking our test docs and maybe not specifically about integration tests?

**Comment by data-sync-user** [comment]
➤ Benjamin Forehand Jr commented:

Yeah, this is just about all types of testing. There aren't many docs on the tests, in any context.

**Comment by jaredlockhart** [comment]
Feel free to PR in any relevant docs that appear to be missing, closing this as not directly actionable.
