### ISSUE TITLE
/nimbus experiment list is getting slow to load (stage)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5724]
https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/

![Experiments](https://user-images.githubusercontent.com/557895/118063228-80d18300-b34d-11eb-8e3b-944cc0bc8784.png)UNITO-UNDERSCORE!!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!Experimenter!UNITO-UNDERSCORE!and!UNITO-UNDERSCORE!New!UNITO-UNDERSCORE!Issue_·_mozilla!UNITO-UNDERSCORE!experimenter!

Looks like stage is currently fetching around 350 experiments, and the /graphql response is taking around 4.33 seconds (5.14 seconds total pageload time).

[Production](https://experimenter.services.mozilla.com/nimbus/) is better, at only 1.03 seconds for around 50 experiments for the /graphql page, and 1.67s total time.

![Experiments](https://user-images.githubusercontent.com/557895/118063455-f9d0da80-b34d-11eb-9ef8-1431e1423902.png)UNITO-UNDERSCORE!!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!Experimenter!UNITO-UNDERSCORE!and!UNITO-UNDERSCORE!New!UNITO-UNDERSCORE!Issue_·_mozilla!UNITO-UNDERSCORE!experimenter!

Obviously, none of this is end of the world, and it probably impacts a few of us, but 5 second page load times can get tedious.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1314)

**Comment by jaredlockhart** [comment]
We cleared the stage db out and then recently landed performance improvments to that API so this should be sufficiently resolved now.
