### ISSUE TITLE
Add collapse/expand option to summary page JSON blobs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5729]
Now that we have JSON formatting in place, some experiments have a pretty lengthy summary/review page: https://experimenter.services.mozilla.com/nimbus/multi-stage-onboarding-set-default-v42-experiment

We can potentially add a toggle that adds a max-height to these sections with "expand"/"contract" options, or something else similar to help clamp the full value when it's really lengthy.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1304)

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

If we just want a full toggle (without min/max height), we could use ye olde <details>+<summary> tags:

<details>
<summary>Click to toggle</summary>
<pre><code>
<details>
<summary>Click to toggle</summary>
<pre><code>Things and stuff</code></pre>
</details>
</code></pre>
</details>

It could work for the new FormattedJson component, although probably overkill for the one-liner Jexl field (unless we word wrap onto multiple lines using CSS).

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Oh interesting... It looks like GitHub adds a "copy to clipboard" icon when I expand the details section, but I think that's a neat GitHub-specific thing since I don't see that when I try the same snippet on jsbin.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

pdehaan Ohh that's really neat/that's what you meant on Slack, I didn't know that was a thing now! I'm not sure if we want some kind of preview or not, or if it's OK to hide all of it until they click "click to toggle", but that's something to experiment with. 😁

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

I also learnt that you can do <details open> and it should open the collapsible details section by default. Then there were lots of CSS bits about :not(open) for conditional styling where I started to get lost.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Took a peek at this and took a shot at trying a different JSON view component:

https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/af2066f014a9ec82aaabe71333cfd6bf91c67587/nimbus-ui/index.html?path=/story/pages-summary--missing-required-fields ( https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/af2066f014a9ec82aaabe71333cfd6bf91c67587/nimbus-ui/index.html?path=/story/pages-summary--missing-required-fields|smart-link ) 

Maybe too much expanding & collapsing?

**Comment by jaredlockhart** [comment]
We've split the summary page into high level and detailed sections and JSON is on the detailed page so I think the spirit of this is accomplished.
