### ISSUE TITLE
Add sign-offs to experiment list page

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#573]
We received feedback that it would be helpful to indicate the state of all the sign-offs on the list page, so let's find a nice way to represent them there.

**Comment by shell1** [comment]
I'm changing this one to won't fix for now.  After we've made the copious changes to the UI that are pending - we can do a full UX review for how it conveys needed info.  But going to get rid of any optional feature request type of changes at this point - since it's evolving.
