### ISSUE TITLE
Add checkbox in the Branches page to set isEarlyStartup for features

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5732]
In [bug 1710919](https://bugzilla.mozilla.org/show_bug.cgi?id=1710919) we landed the ability to remotely specify if a feature value should be cached for early startup availability. We need UI to support this in the UI and in the recipe.
The recipe looks like this:

```javascript
...
{
  feature: {
    featureId: "cfr",
    enabled: true,
    isEarlyStartup: true,
    values: {},
  }
...
}
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1345)

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Also needs a non-breaking DTO schema change

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

If this is strongly tied to a feature config then can we put this in the Feature Config model instead of in the Branch?

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Yep that sounds good!

**Comment by jaredlockhart** [comment]
This hasnt' come up recently so if it becomes critical we can revisit it when we port features over to being consumed as manifests from repos.
