### ISSUE TITLE
Sort experiments on /nimbus/ page by recency?

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5741]
Re: https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus

Jared and I recently approved some experiments on staging, but the order of the results seems to almost be random (his is second from the top, mine is fifth, despite mine being approved more recently). Not sure if we should be sorting by `id` (ascending or descending) for each of the following sections:

* Active > Live
* Active > In Review
* Active > In Preview
* Completed
* Drafts

Probably makes marginally more sense to sort with the most recent experiments at the top of the respective tab lists. Or possibly sort by most recently updated, if that information is available.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1336)

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Possibly related: #4593 and #4782

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

Yeah I just noticed this too, makes it impossible to find anything, the ordering seems pretty random atm. Hopefully we can just order the QS on the backend and the frontend should just update.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

I just threw this into the experiment pagination epic. 👍

EDIT: Well never mind, I'll take it out, I just checked out #4593 and from @jodyheavener:

> Quick update: Ana informed me that sorting is going to be handled later, separate from paginating, so I'm going to bump this out of EXP-944. And for anyone looking down the road, we removed the 50-experiment limit on the home page.

**Comment by jaredlockhart** [comment]
Experiments can be sorted by any table column now.
