### ISSUE TITLE
Branch tables with uninterrupted strings in the feature configuration forces the /nimbus/ page to display a horizontal scrollbar

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5750]
**[Steps to reproduce]:**

1. Navigate to [this experiment ticket](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/cmuresan-nimbus-smoke-05272021).
1. Scroll down to the bottom of the page.
1. Observe the "treatment" branch.

**[Expected result]:**

* The "treatment" table has a horizontal scrollbar inside the cell the value is in.

**[Actual result]:**

* The whole page has a horizontal scrollbar and the table's boundaries are extended to display the full uninterrupted string.

**[Notes]:**

* The issue is also reproducible on the /request-review page.
* Attached is a screen recording of the issue.
* [PI-1051]

![branches tables with uninterrupted strings in their feature configuration do not have a horizontal scrollbar in their respective cell](https://user-images.githubusercontent.com/18304511/119836915-caec6400-bf0a-11eb-97f5-9cb8c061b685.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1355)

**Comment by anthonytran7757** [comment]
hey @jaredlockhart I'd like to give this one a go.
