### ISSUE TITLE
`_` is not a valid slug

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5752]
@SoftVision-CiprianMuresan brilliantly figured out that if the experiment slug is just `_` then remote settings will reject it, and the experiment gets stuck.  We need to validate that the experiment slug will be accepted by remote settings, the regex for it is here:

https://github.com/Kinto/kinto/blob/master/kinto/core/storage/generators.py#L12

{{    regexp = r"^[a-zA-Z0-9][a-zA-Z0-9_-]*$"}}

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1357)

**Comment by jaredlockhart** [comment]
Yep we should do this 👍

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Ciprian Muresan Can you please see if you can still recreate this?

**Comment by data-sync-user** [comment]
➤ Ciprian Muresan commented:

Jared Kerim I tried to create a new experiment using only symbols available on an US layout keyboard ~`!@#$%^&*()_-+|}{][":';?></., and some Japanese symbols for good measure but I couldn’t.

We seem to be ok now.

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Awesome thanks Ciprian Muresan !
