### ISSUE TITLE
Enable pytest-html HTML report for integration-tests

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5770]
We should enable the HTML report and capture it on CI to help debug failures.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1409)

**Comment by jaredlockhart** [comment]
We should do this soon since we're adding more integration tests and debugging them will become increasingly important.

**Comment by jaredlockhart** [comment]
This hasn't blocked us from debugging integration tests thus far so we can refile if we need it later.
