### ISSUE TITLE
Long uninterrupted strings and partially hidden and force the about:privatebrowsing page to display a horizontal scrollbar

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5771]
_[Affected versions]:_

* Firefox Nightly 90.0a1, Build ID 20210530214555
* Firefox Beta 89.0 Build ID 20210527174632

_[Affected platforms]:_

* Windows 10 x64
* macOS 10.15.7
* Linux Mint 20 x64

_[Prerequisites]:_

* Have a Nimbus recipe targeting the "about:privatebrowsing" feature with a long uninterrupted string for the "promoTitle" parameter.
* Have a browser profile enrolled in the experiment.

_[Steps to reproduce]:_

1. Open the browser with the profile from prerequisites and open a new Private Browsing window.
1. Observe the page's promo section.

_[Expected result]:_

* The promo section's title is broken up and displayed fully on the page.

_[Actual result]:_

* The promo section's title is cut off and a horizontal scrollbar is displayed.

_[Notes]:_

* [PI-1051]
* Attached a screenshot of the issue:
![long](https://user-images.githubusercontent.com/40393891/120198131-79094e00-c22a-11eb-919c-fe0648eb07c4.png)UNITO-UNDERSCORE!string!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1363)

**Comment by jaredlockhart** [comment]
Validating client features in this way is outside of the scope of this project.
