### ISSUE TITLE
Enhancement: The "privatebrowsing" feature configuration shouldn't allow duplicate parameters in the Value textbox

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5775]
_[Steps to reproduce]:_

1. Open a Draft experiment's "Branches" page.
1. Select the "privatebrowsing" feature configuration and enable it.
1. Enter the following snippet: {"infoEnabled": true, "infoTitle": "Hello world", "infoTitle": "Hello world2"}.
1. Click the "Save" button and observe the page.

_[Expected result]:_

* The branch should not be saved and an error should be displayed.

_[Actual result]:_

* No errors are displayed and the branch configuration is saved.

_[Notes]:_

* When enrolling in an experiment with duplicate parameters, the second one is applied.
* [PI-1051]
* Attached a screen recording of the issue:
![duplicate](https://user-images.githubusercontent.com/40393891/120202369-3138f580-c22f-11eb-9e4f-d28799b5254e.gif)UNITO-UNDERSCORE!param!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1364)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Two things: 

> The branch should not be saved and an error should be displayed.

If we accept & fix #5339, we will show no errors on branch save - just at review time. 

> When enrolling in an experiment with duplicate parameters, the second one is applied.

This is technically normal JSON behavior and I haven't found an option in the jsonschema validator ( https://python-jsonschema.readthedocs.io/en/stable/validate/ ) for enforcing a rule that duplicate properties are disallowed. I might have missed something in the docs? Otherwise, this might be tricky to change.

**Comment by jaredlockhart** [comment]
Yeah this is an interesting point.  We rely on the feature json schema to validate so if that accepts it I'm inclined to think that's sufficient.  We also require multiple stages of human review for each experiment so it should be up to the experiment owners and reviewers to catch this kind of thing.  I haven't heard any complaints about this so far, if it comes up we can revisit it but in the meantime I will close this.
