### ISSUE TITLE
Outcomes in visualization should have placeholder text

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5776]
!image-2021-06-08-14-16-09-801.png!

Placeholder text can be N/A if no outcomes.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1399)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/14664/image-2021-06-08-14-16-09-801.png">image-2021-06-08-14-16-09-801.png</a>

**Comment by jaredlockhart** [comment]
We can revisit this when we look at the visualizations page in more detail.
