### ISSUE TITLE
The “Expecting ‘,’ delimiter” error message is displayed when a parameter's value string contains quotation marks

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5779]
[Prerequisites]:

* Have Firefox Nightly 90.0a1 installed and opened.
* Have a new [Nimbus](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/) experiment created and opened.

[Steps to reproduce]:

1. Open the experiment's Branch section and click the "+Feature Configuration" button.
1. Open the Feature configuration dropdown menu and select the "privatebrowsing" feature.
1. Click the “ON” toggle and add the “{ "infoLinkText": "This “is” a link" }” configuration inside the “Value” textbox.
1. Click on the “Save” button from the bottom part of the page.
1. Observe the behavior.

[Expected result]:

* The changes are saved and no error message is displayed.

[Actual result]:

* The “Expecting ‘,’ delimiter” error message is displayed.

[Notes]:

* Attached a screenshot of the issue.
* [PI-1051]

![Nimbus](https://user-images.githubusercontent.com/50919288/120204915-03a17b80-c232-11eb-846f-e0567ce2b74e.png)UNITO-UNDERSCORE!ErrorMessage!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1365)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Looks like the error is due to invalid JSON. We probably want to move that requirement to the review serializer and allow in-progress work to be saved even if invalid.

**Comment by jaredlockhart** [comment]
Yeah the validator is working correctly here, it's an interesting point @lmorchard about allowing saving and moving the JSON validation to the review stage rather than at save time.  Let's wait to receive user feedback about this before we address it.  Closing for now.
