### ISSUE TITLE
Switch dependabot to minor only

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5797]
So our current dependabot process isn't really doing a good job of keeping us up to date, keeping security warnings clear, and is taking too much of peoples time.  So we should try to switch dependabot to daily, for major/minor updates only (no patch) and setup a gh action to auto merge them if CI passes.  Hopefully that keeps us more up to date, keeps the security warnings down, and takes less of peoples time.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1425)

**Comment by jaredlockhart** [comment]
Okay so I don't think we can do most of this.

- If we switch it to daily, then we'll invalidate our local docker caches constantly which will blow up local dev times and CI times, so we should probably keep it at weekly.
- Biweekly would be nice but the only options are daily, weekly, monthly
- We can set it to minor only, ignoring patch (noisy frequent updates) and major (most likely to be breaking)

I wanted to set legacy-ui to security only but there doesnt' seem to be a way to do that.

I'll setup an automerge action as a followup in https://github.com/mozilla/experimenter/issues/5894
