### ISSUE TITLE
Add failure messages to integration test assertions

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5800]
It would be nice if all of our assertions in our integration tests came with some helpful messages like

```py
assert some_element_found_in_page, message="Expected element to be in page but it was not found"
```

so that it's easier to distinguish expected test failures from crashes.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1426)

**Comment by jaredlockhart** [comment]
We can do this kind of thing as we land changes to the tests rather than tracking it separately.
