### ISSUE TITLE
[Experimenter Stage] Nimbus experiments sent to Remote Settings Writer are still pending for approval after 10 minutes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5808]
**[Affected versions]:**

* Firefox Nightly 90.0a1 (Build ID: 20210617221244);

**[Affected Platforms]:**

* Windows 10 x64;
* macOS 10.15.7;
* Linux Mint 20 x64;

**[Prerequisites]:**

* Have the latest Firefox Nightly installed.
* Have a Nimbus experiment sent to Review in the RSW.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from prerequisites.
2. Open and login into the RSW.
3. Click the "nimbus-desktop-experiments" collection from the "main-workspace" bucket.
4. Search for the Nimbus experiment mentioned in prerequisites.
5. Wait for 10 minutes.
6. Refresh the RSW page and observe the behavior.

**[Expected result]:**

* The Nimbus experiment has timed out.

**[Actual result]:**

* Nothing happens, the experiment is still pending approval.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1435)

**Comment by jaredlockhart** [comment]
This should no longer be the case.  If it occurs again we can refile.

**Comment by data-sync-user** [comment]
➤ Carmen Fat commented:

Confirming that this issue doesn't happen anymore. The experiment times out after 15 minutes in Remotes Settings Writer and an error notification is displayed on the experiment's Nimbus page.  !notification timeout.jpg|thumbnail!
