### ISSUE TITLE
Wrong duration displayed

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5812]
Just noticed we're still showing the wrong duration in one place, that 28 should be 0:

![](https://user-images.githubusercontent.com/119884/122109786-c15c6a80-cdeb-11eb-9e7a-c5e4e7d5bc97.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1423)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Is this a dupe of #4945? PR #5402 should aim to address this

**Comment by LZoog** [comment]
Closing this, should be addressed now.
