### ISSUE TITLE
Test Jira Please Ignore

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5814]
I'm a little jira short and stout here is my description here is my assignee 🫖

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1437)

**Comment by jaredlockhart** [comment]
Github Comment

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

Jira Comment

**Comment by jaredlockhart** [comment]
Closing on Github side
