### ISSUE TITLE
Auto format slugs correctly

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#582]
When an experiment is created, we need to create a slug of the form

[type]-[name]-[population]-[bug id]

This means we need to have two slugs, one the experimenter slug, and the other the normandy slug, because we won't have the bugzilla id until after the experiment is created in experimenter.

The normandy slug is what will get communicated to normandy and then used for monitoring.

**Comment by jaredkerim** [comment]
Note: we don't need to store this as a model field, I think we can just use a property to generate it dynamically.  Also we'll probably want to pay attention to very long experiment names to cap it at like 6 words or something.

**Comment by mythmon** [comment]
Will generating these on the fly and not storing them handle things like Activity Stream slugs must include the substring "activity-stream"?

**Comment by jaredkerim** [comment]
@mythmon So that would be the case where the name of the experiment would be something like 'Activity Stream 60 Beta Wide Layout (user pref fix)' which we would then convert into a normandy style slug of the form:

pref-flip-activity-stream-60-beta-wide-layout-user-pref-fix-beta-60-bug-12345

The activity stream naming thing (ie for telemetry to be marked and filtered correctly) would probably be the responsibility of the person logging the experiments into Experimenter to know and manage, because that's a special case for them.

What's the maximum length of a Normandy slug?

**Comment by mythmon** [comment]
> What's the maximum length of a Normandy slug?

Normandy effectively doesn't have a limit on slug name, but Telemetry might have a limit for things like event telemetry that would be good to respect. The longest slug we have on the server right now is 81 characters.

**Comment by mlopatka** [comment]
How does this apply for add-on studies deployed via experimenter?

**Comment by jaredkerim** [comment]
@mlopatka That's what 'type' at the start refers to, so an addon study would look like

`addon-taar-new-thingy-bug-12345`

**Comment by mlopatka** [comment]
Thanks @jaredkerim, so for an addon study, we need to know the bug number before it is generated?

**Comment by mythmon** [comment]
@jaredkerim To clear up some potential confusion, add-on studies currently hard code the slug within the add-on, and it can't be controlled through Normandy. That poses a sort of chicken and egg problem for development.

@mlopatka Yes, we'll need to make sure to get the appropriate bugs filed before the final version of the add-on, so we can make sure it ships with the right slug. Experimenter should make that easier than in the past though.

**Comment by jaredkerim** [comment]
@mythmon Oh you're right.  Hrmm.  Maybe in that case we need to expose that field as part of the experiment form, like next to addon XPI URL, and have the developers prepopulate it before it is about to get sent to Normandy?

**Comment by mythmon** [comment]
I think that's a good stop gap solution.
