### ISSUE TITLE
[FE] Show labels for exposure analysis basis

### ISSUE THREAD

**Issue by scholtzan** [mozilla/experimenter#5827]
https://github.com/mozilla/jetstream/pull/703 adds support for using exposures and enrollments as analysis basis for metrics. Currently, Experimenter assumes that all metrics and results are computed based on an enrollments analysis basis. Some changes will need to be made in the visualization to support and indicate what analysis basis results are based on.

There is an [ADR](https://github.com/mozilla/jetstream/blob/main/docs/adr-0002-publishing_statistics_with_analysis_basis.md) which describes the changes of the metadata that Experimenter will need to consider.

Blocks https://github.com/mozilla/jetstream/issues/796

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1441)

**Comment by emtwo** [comment]
Once the backend changes (https://github.com/mozilla/experimenter/issues/6262) are done to pass down the metadata labels for the analysis type, the frontend needs to show some kind of label to users of what the analysis type is.
For each metric table, this could be a label that goes next to the metric type label perhaps around here: 

![Screen Shot 2021-08-19 at 2 38 23 PM](https://user-images.githubusercontent.com/784781/130126675-c6a700d6-3079-4087-8f35-ad613eb95282.png)


In the highlights and summary tables, perhaps this could be added as part of the tooltip text for each metric.

**Comment by jaredlockhart** [comment]
Closing this until we have more support for data visualization and we can rethink the exposure support more wholistically.
