### ISSUE TITLE
Link "Not set"s on summary page to appropriate page 

### ISSUE THREAD

**Issue by LZoog** [mozilla/experimenter#5832]
@pdehaan pointed out it would be nice to do this rather than have the user scroll all the way back up and click on it through the sidebar and I totally agree.

Though, I'm curious if @AnaMedinac thinks they should stay red with say, an underline, to signify it's a link.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1443)

**Comment by LZoog** [comment]
Per Ana, let's keep the links red and use Bootstrap's default link style - no underline when active, but underline on hover.

**Comment by jaredlockhart** [comment]
We currently link to pages that are missing data, so we can put off any further enhancements to that functionality until we receive user feedback.
