### ISSUE TITLE
Revisit nimbus integration test selectors

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5849]
This was brought up in retro. 

The original conversation in Slack about using CSS selectors was here, hopefully this is still viewable: https://mozilla.slack.com/archives/CANCHH6R1/p1617123439123600

I noticed in our integration tests, sometimes we query by ID, CSS-selector-turned-ID (as in, a unique class is specifically made for an element without custom CSS styles and only used for integration tests), or a generic selector like `.font-weight-bold` that has potential to change and create flaky tests.

We talked about using ID-only or some way to use data-id, but it's best practice to query by `role` or what the user is seeing in the UI rather than ID anyway so... whatdo? At the very least, let's record the decision here and consider making these selectors consistent.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1452)

**Comment by LZoog** [comment]
@jrbenny35 @jaredlockhart

**Comment by pdehaan** [comment]
A bit of poking in DevTools and this seemed to work for finding the "Drafts" tab on the /nimbus/ homepage (without resorting to `id=` or `class=`):

```js
$$("nav[role=tablist] a[role=tab][data-rb-event-key=drafts]")
```

Uses roles and `data-*` attributes instead of `id`s or `class` values. :shrug:

Similarly, if I'm on the Drafts tab, I can access the big-ol' table using:

```js
// But I did cheat by using `div.tab-content`.
$$("div.tab-content div[role=tabpanel][aria-hidden=false] table")
```

**Comment by jrbenny35** [comment]
>> but it's best practice to query by role or what the user is seeing in the UI rather than ID

Could you elaborate on this?

**Comment by jaredlockhart** [comment]
We can make this kind of enhancement as tests are added rather than tracking it separately.
