### ISSUE TITLE
(UI) Move common prop sets (based on flows/experiment status) to central location

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5851]
We have a lot of sets of properties for various experiment flows and/or states for use in Storybook, testing, and in our mutations. It feels like these could go in some sort of shared location, or a shared flow/prop mock file and another for reference in the UI.

We have some great "[state]BaseProps" in [ChangeApprovalOperations mocks](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/ChangeApprovalOperations/mocks.tsx). I think we can pull these out to a higher level to use across stories where applicable, there's likely other stories (and potentially tests) like [in AppLayoutWithSidebar](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/AppLayoutWithSidebar/index.stories.tsx#L56-L75) and [LinkNavSummary tests](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/LinkNavSummary/index.test.tsx#L59) that could pull from a shared place, and we have other "base props" [set up in Summary mocks](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/Summary/mocks.tsx#L64) as well as [in PageSummary](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/PageSummary/mocks.tsx#L70).

Additionally, we have a lot of flow actions for mutations that correspond to similar sets of "flow props". See this [in PageSummary](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/PageSummary/index.tsx#L55-L101) as well as one [in Summary](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/Summary/index.tsx#L41-L43).

There may be other similar instances - just mostly feels like this could use some consolidation and something that can make these properties/objects correspond with a kind of flow or action would feel a bit cleaner.

Related, fixing up how we're checking for statuses: EXP-1158 / #5643

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1454)

**Comment by jaredlockhart** [comment]
@lmorchard if you feel like doing this soon then great, if not then just close this as a wontfix 👍
