### ISSUE TITLE
Add link to experimenter.info and #ask-experimenter Slack channel in sidebars

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#5888]
The link to experimenter.info site is available on the homepage, but we should make it more prominent and maybe a static footer so users know where to ask if they get stuck during the experiment creation process.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1462)

**Comment by LZoog** [comment]
Per Ana, let's add this to the bottom of the sidebar and not create a footer for this.

It won't be present on the directory view but that's OK.

**Comment by anthonytran7757** [comment]
Hi @LZoog I'd like to pick this one up!
