### ISSUE TITLE
Add FAQ for Frequently asked Qs and put them on experimenter.info

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#5889]
&hellip; and possibly lots of cross references from the experimenter site to specific sections/answers on experimenter.info.

Notes from @AnaMedinac:
There's confusion around Feature configuration, and feature config on/off
On the Metrics page, how do I implement the primary and how do I know what’s included with "default browser"?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1463)

**Comment by jaredlockhart** [comment]
Feedback about missing docs can be captured separately, this ticket doesn't contain clearly actionable work so closing for now.
