### ISSUE TITLE
Move/clone "+ Add branch" button on /edit/branches down towards the bottom of the screen

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#5890]
https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/ppop-ios-test2/edit/branches

Noticed during Ana's excellent walkthough that she added a second or third branch, then needed to scroll back to the top of the page to click "Add branch" then back to bottom to add details, then back to top to click "Add branch" then back to bottom, etc.

I don't expect a lot of experiments have oodles of branches, but it might make sense to copy the button so it's in the lower left side of the "Save"/"Save and Continue" buttons so people can add more branches without excessive scrolling.

![Banners_and_Alerts_and__ppop__iOS_test2_–_Branches___Experimenter](https://user-images.githubusercontent.com/557895/124659117-74533d80-de59-11eb-8cf8-c95a510ec9a8.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1464)

**Comment by jaredlockhart** [comment]
Let's just move this button entirely to the position you suggested here @pdehaan, I think that's always the place the user will want to interact with it.

**Comment by bhushan-borole** [comment]
Hey @jaredlockhart 
I am willing to take up this issue.
