### ISSUE TITLE
Add more spacing around review form on detail page

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#592]
We need to add more space around the review checkboxes so you don't accidentally click the 'Save' button when you're trying to check off the bottom review.

**Comment by ooHAoo** [comment]
I'm interested in contributing to this, however, I'm having some issues setting up
(at the 'make createuser')

**Comment by jaredkerim** [comment]
@ooHAoo Thanks for your interest in contributing!  File a separate ticket with the issue you're having with `make createuser` so we can figure out what the problem is and feel free to reach out to me on [irc.mozilla.org](https://wiki.mozilla.org/IRC) my username is `jkerim` :)

**Comment by jaredkerim** [comment]
I've redone that UI since this was filed, if I need to change it again I'll file a new ticket.
