### ISSUE TITLE
The Nimbus UI can take between 3 and 25 seconds to be refreshed when requesting to end an experiment

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#5921]
**[Prerequisites]:**
- Have an Desktop experiment in the `Live` state. (eg [here](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/cmuresan-testing-end-experiment-ui-response-time))

**[Steps to reproduce]:**
1. Navigate to the Nimbus experiment page from prerequisites.
2. Click the "End Experiment" and "Yes, end the experiment" buttons.
3. Observe the page.

**[Expected result]:**
- The page is instantly refreshed and the "All set, the experiment will end as soon as it is approved" message is displayed.

**[Actual result]:**
- The page can take between 3 and 25 seconds to refresh, the buttons to become unavailable, and the message to be displayed.

**[Notes]:**
- Users could potentially request the end of an experiment multiple times before the UI is refreshed and the buttons are unavailable.
- Attached is a screen recording of the issue.

![it can take between 3 and 25s for the UI to change when requesting an experiment to end](https://user-images.githubusercontent.com/18304511/125089765-4ed36780-e0d7-11eb-99d9-215f7dee2a52.gif)

![can make multiple end requests before the UI changes](https://user-images.githubusercontent.com/18304511/125089732-47ac5980-e0d7-11eb-9cd2-5f4677e25d90.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1474)

**Comment by jaredlockhart** [comment]
Interesting, thanks for catching.  We should probably disable buttons and add a spinner.  Separately we should figure out why that's taking so long since it should just be a fast call, but we should also set the UI up to handle possible network latency.

**Comment by LZoog** [comment]
Ohh, I have seen this happen inconsistently locally before but didn't see it occur on staging. Definitely something we should fix.

**Comment by SoftVision-CiprianMuresan** [comment]
I have verified that the issue is no longer reproducible on the Stage server. From an end-user perspective the transition is almost instant and the button is no longer actionable after the first click.
