### ISSUE TITLE
Add tests for checking results page loading of weekly vs overall data

### ISSUE THREAD

**Issue by emtwo** [mozilla/experimenter#5926]
This is a follow up to https://github.com/mozilla/experimenter/pull/5925

We need tests to ensure that primary and secondary outcomes only show up on the results page when overall results are available

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1477)

**Comment by jaredlockhart** [comment]
@emtwo if this is still critical then we can leave it open but if it's not necessary then please close it 👍

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Looks like not urgent.
