### ISSUE TITLE
Enable automerge PRs in experimenter-docs, update contributing page docs

### ISSUE THREAD

**Issue by LZoog** [mozilla/experimenter#5928]
Did a quick check to see how to enable this:
https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request

Tried enabling it, but: 
> Note: the option to enable auto-merge is shown only on pull requests that cannot be merged immediately. 

I don't see it as an option with current open PRs (all dependabot).

We should enable this feature in experimenter-docs and then update the [request workflow section](https://experimenter.info/contributing#pull-request-workflow) of the contributing page to mention it as an option.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1479)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Auto merge has been enabled. This ticket is to update the contributing page to mention this.

**Comment by jaredlockhart** [comment]
Sounds good 👍

**Comment by jaredlockhart** [comment]
Enabled auto merge for experimenter docs.
