### ISSUE TITLE
ZeroDivisionError experimenter.jetstream.tasks.fetch_experiment_data

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5936]
We're getting a "float division by zero" error in prod Sentry:

https://sentry.prod.mozaws.net/operations/experimenter-prod/issues/11763102/?query=is%3Aunresolved

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1483)

**Comment by jaredlockhart** [comment]
This has been open for a while with seemingly no impact on users.  Since it has received no attention I will close this and mark the sentry report to be ignored.  If something becomes critically apparent to users we can refile.
