### ISSUE TITLE
Issue while trying to setup with  'make createuser'

### ISSUE THREAD

**Issue by ooHAoo** [mozilla/experimenter#594]
Hi,
I was trying to setup for this project and got stuck at  the 'make createuser' command.
It gave me 1 error and I'm not sure if that's something to do with the way I had everything else setup or if it's something obvious that I'm not seeing. Please kindly direct me :)
Here is the screenshot:

![screen shot 2018-11-17 at 11 22 09 pm](https://user-images.githubusercontent.com/26858034/48668610-c0da8680-eabf-11e8-8562-db80e60efb85.png)

a little more details:
![screen shot 2018-11-17 at 11 22 46 pm](https://user-images.githubusercontent.com/26858034/48668612-ce900c00-eabf-11e8-8e90-211ba3bbf722.png)

**Comment by jaredkerim** [comment]
Ah see in the red text how it says there are 'unapplied migrations'.  You have to run `make migrate` first, then try it again.  Let me know if that works!

**Comment by ooHAoo** [comment]
> Ah see in the red text how it says there are 'unapplied migrations'. You have to run `make migrate` first, then try it again. Let me know if that works!

Could have sworn I did that many times until I posted this issue. Magically works now.
Thank you so much!
