### ISSUE TITLE
Upgrade dev Kinto

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5943]
When going through the request review flow, the button for "Open Remote Settings" takes you to a path ending in /simple-review, and this in stage/prod but not locally, where the correct path is /records.

Kate mentioned this is because the dev Kinto version is older and needed to be upgraded. I took a quick look but don't really know how to upgrade this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1485)

**Comment by jaredlockhart** [comment]
Kinto is provided as a [docker image](https://github.com/mozilla/experimenter/blob/main/docker-compose.yml#L96) but we don't explicitly state the version and docker won't automatically go find a newer version and pull it in.  So the simple way to do it now is to `docker pull mozilla/kinto-dist` and that'll pull in the most recent image.

Some options for how to address this are
1) Update docs to mention doing a pull if kinto updates and we want to pull in the changes
2) Possibly add this to the makefile as a manually invoked command like `update_kinto`
3) Possibly add this to the makefile as something that happens automatically when you restart but I wonder if it'd be smart enough to know nothing's changed and skip that step if it's up to date.  Maybe?
