### ISSUE TITLE
Refine End Experiment / End Enrollment action button UX

### ISSUE THREAD

**Issue by lmorchard** [mozilla/experimenter#5970]
Following on from PR #5852, some things that could use refinement in the summary page action buttons here:

* ["End Enrollment for Experiment" is very long for a button and maybe redundant?](https://github.com/mozilla/experimenter/pull/5852#discussion_r670461587) I erred on the side of verbosity to distinguish from "End Experiment", but maybe we could improve this?

* The "End Enrollment for Experiment" and "End Experiment" buttons [are not inline, but they'd probably look better if they were](https://github.com/mozilla/experimenter/pull/5852#discussion_r670462698).

* Also, [the confirmation panes for both of those buttons can be summoned at the same time](https://github.com/mozilla/experimenter/pull/5852#discussion_r670469134), one after the other. It might be better if clicking one of the two buttons replaced both with a single confirmation pane.

All the above could be addressed in a new component that unifies the separate buttons into a single button strip with a single shared confirmation pane that adapts to whichever was clicked.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1501)

**Comment by jaredlockhart** [comment]
Yeah it's a good idea, I'd like to revisit the UX of the summary page in general.  I'll close this and when we're ready to focus more attention on that page we can come up with a new cohesive plan.
