### ISSUE TITLE
Use React Context for fetched Experiment, rather than function-as-child-component?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/experimenter#5971]
We commonly use this pattern for supplying an experiment from the shared app layout to a page:
```javascript
    <AppLayoutWithExperiment
      title="Overview"
      testId="PageEditOverview"
      redirect={editCommonRedirects}
    >
      {({ experiment, refetch }) => {
        currentExperiment.current = experiment;
        refetchReview.current = refetch;

        return (/*...*/);
      }}
    </AppLayoutWithExperiment>
```
What if instead we used React Context supplied by `AppLayoutWithExperiment`?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1502)

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Busted this out into its own epic, https://mozilla-hub.atlassian.net/browse/EXP-1597 ( https://mozilla-hub.atlassian.net/browse/EXP-1597|smart-link ) so I think we can close
