### ISSUE TITLE
Intermittent test failure: TestExperimentListView::test_list_view_total_experiments_count

### ISSUE THREAD

**Issue by lmorchard** [mozilla/experimenter#6004]
In PR #5996 from dependabot, there was [a python test CI failure](https://app.circleci.com/pipelines/github/mozilla/experimenter/10403/workflows/52942f1f-5031-4fdf-8509-276563f21bdc/jobs/30723):

```
=========================== short test summary info ============================
FAILED experimenter/experiments/tests/test_views.py::TestExperimentListView::test_list_view_total_experiments_count
=========== 1 failed, 882 passed, 324 warnings in 186.59s (0:03:06) ============
```

On rerun, [all tests passed](https://app.circleci.com/pipelines/github/mozilla/experimenter/10403/workflows/949f9c98-856e-4601-a629-b5eb9b28964f/jobs/30758).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1517)

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

This failure looks like the result of accidentally choosing a random value two times when unique values were needed. If it happens infrequently I’d say we could ignore it for now.

**Comment by jaredlockhart** [comment]
Oh yeah, we've been seeing these forever, I have no idea how to solve it.  Faker is supposed to randomly generate names/slugs but every so often it creates two identical ones and violates the db uniqueness constraint.  I don't know if it's legitimately a problem in faker or just cosmic rays, but for now if we see those, just re run the circle task.  Maybe some day we'll find a better solution.
