### ISSUE TITLE
Some lifecycle states are problematic in loaded dummy experiments

### ISSUE THREAD

**Issue by lmorchard** [mozilla/experimenter#6023]
Some lifecycle states should only be reached when there is a corresponding record in Kinto. Iterating through all possible lifecycle states in load_dummy_experiments results in some experiments in states that violate this expectation.

For example, ENDING_APPROVE without a corresponding record in Kinto results in a repeating celery task that keeps trying to delete the experiment but [failing with an exception each time](https://github.com/mozilla/experimenter/blob/main/app/experimenter/kinto/tasks.py#L262-L265).

Solution is probably to figure out which lifecycle states produce this situation and just filter those out of the list used to generate dummy experiments.

Off the top of my head, this is at least ENDING_APPROVE and PAUSING_APPROVE. Might also include any WAITING cases.

Could also look at making the Celery task handle this data inconsistency more robustly, though it's probably an edge case.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1527)

**Comment by jaredlockhart** [comment]
Yeah I've thought about this too.  Probably the simplest thing to do is just only create Draft, Preview, Review, Complete experiments.  Since the live ones won't actually be live since they won't be in RS.  Then if you need something live you can launch one of the drafts.
