### ISSUE TITLE
Full targeting expression on summary page obscured by scrollbars

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6027]
Users are having difficulty interacting with the full targeting expression on the summary page because it is obscured by the scrollbar.  Let's change this to fixed width.

![image](https://user-images.githubusercontent.com/119884/126680567-f63480a3-3799-43f9-bbc8-cd1c9b1e2ea4.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1529)

**Comment by jodyheavener** [comment]
System Preferences > General > Show scroll bars > Always

Profit 💰
