### ISSUE TITLE
Results table of contents doesn't scroll overflow

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6031]
If the results table of contents exceeds the page height, there's no way to scroll it to see the items below the fold.  I know we had it locked so it was always visible while the right hand content is scrolled, but then you can't see the items on the left.  We could make the table of contents independently scrollable, but that seems needlessly complicated.  Maybe we should just make them a single scroll pane?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1531)

**Comment by jaredlockhart** [comment]
<img width="260" alt="Screen Shot 2021-07-22 at 3 30 50 PM" src="https://user-images.githubusercontent.com/119884/126699141-9c8f6aa7-5ec7-4166-8b79-3b1f5f547a16.png">

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

+1 for making it a single scroll pane
