### ISSUE TITLE
Visualization overlapping text

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6032]
On https://experimenter.services.mozilla.com/nimbus/default-browser-adoption-experiment/results you can see some of the results numbers are overlapping:

<img width="321" alt="Screen Shot 2021-07-22 at 3 36 23 PM" src="https://user-images.githubusercontent.com/119884/126699255-74e97b95-41a6-41b6-8abc-bef4afaeeb6d.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1532)

**Comment by LZoog** [comment]
This was closed in #6088
