### ISSUE TITLE
Nimbus Feature Config "Slug" should be more clearly associated to "featureId"

### ISSUE THREAD

**Issue by Mardak** [mozilla/experimenter#6053]
Adding a new feature config name results in an automatic slug, so when I put in "shellService" name to match Firefox FeatureManifest entry https://searchfox.org/mozilla-central/rev/523ac2e17550f1f1da16aacdc6ac647af8b35508/toolkit/components/nimbus/FeatureManifest.js#125

… it ended up generating a slug of "shellservice" which Firefox treats differently.

Maybe it could be clearer that `slug` is what ends up in the json, so it should match exactly with what clients expect.

![name slug](https://user-images.githubusercontent.com/438537/126823417-6b441c4a-3f53-4833-b7ec-7747c6c40aa4.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1543)

**Comment by jaredlockhart** [comment]
Soon features will not be stored in the database/admin at all but consumed directly from the relevant repos so this workflow will go away altogether.
