### ISSUE TITLE
Visualization tooltips are empty

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6054]
Just noticed this [here](https://experimenter.services.mozilla.com/nimbus/default-browser-adoption-experiment-release/results)

<img width="595" alt="Screen Shot 2021-07-23 at 2 10 09 PM" src="https://user-images.githubusercontent.com/119884/126823755-c39f9a0c-13f7-4980-b558-a838a4a0d5c0.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1544)

**Comment by Mardak** [comment]
Just need to select some text… 😉 

<img width="499" alt="image" src="https://user-images.githubusercontent.com/438537/126823958-a0ab1b2c-6211-4a28-87be-32ff15e982d9.png">

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Yeah so looks like this is parsing Markdown into a code block. So we can style the code block to a lighter text color. But I’m more curious about why we’re writing this description as a markdown code block? We can style it white but it’s still going to display as monospace typeface. Jared Kerim do you have insight into this?
