### ISSUE TITLE
Remove .value from enums in logic/tests

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6068]
In some places we have appended `.value` to enum lookups, such as

```py
NimbusExperiment.Application.DESKTOP.value
```

however the `.value` is redundant since the enum member will evaluate to the value automatically, so we can just remove any `.value`.

I think the bulk of them are here:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/tests/test_changelog_utils/test_changelog_utils_nimbus.py
https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/tests/factories/nimbus.py
https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/tests/api/v5/test_serializers.py

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1549)

**Comment by kushagra189** [comment]
Hey, @jaredlockhart I am not able to assign the ticket to my name. Do I need any permissions for the same? Also, seems like the Jira Board also has restricted access. Will take this up!!
