### ISSUE TITLE
Convert list of targeted country names into a list?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6074]
Minor nit, but since some country names contain commas (at least "Bonaire, Sint Eustatius and Saba", "Palestine, State of", and "Saint Helena, Ascension and Tristan da Cunha"), not sure if it'd make it more legible to display the country names in a bulleted list of sorts. 

### PROS
- easier to read in a bulleted list

### CONS
- lists take up more vertical space
- the countries in question will likely never be used

https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-2021-07-27-audiences-gonna-audience/edit/audience

<img width="1141" alt="pdehaan-2021-07-27-audiences-gonna_AuDiEnCe_______–_Audience___Experimenter" src="https://user-images.githubusercontent.com/557895/127240331-f4dba56d-dd5c-446b-96fb-b7b0c600bdb1.png">

https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-2021-07-27-audiences-gonna-audience

<img width="1130" alt="pdehaan-2021-07-27-audiences-gonna_AuDiEnCe_______–_Summary__Request_Launch___Experimenter" src="https://user-images.githubusercontent.com/557895/127240373-f6f93116-c3b0-44a0-b0db-86ab0d695a9f.png">

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/EXP-1552)

**Comment by bhushan-borole** [comment]
Hey @pdehaan 
I would like to work on this issue.

**Comment by jaredlockhart** [comment]
Yeah it would definitely be more readable as a list and an easy change.
