### ISSUE TITLE
Change Locales to Targeted Locales on /audience page?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6075]
Ref: #6074  
Just noticed that the /audience page says "Locales" and "Countries", whereas the summary page says "Targeted Locales" and "Targeted Countries". Not sure if we want to change one to the other for consistency sake.

![Convert_list_of_targeted_country_names_into_a_list__·_Issue__6074_·_mozilla_experimenter](https://user-images.githubusercontent.com/557895/127242176-347766fb-e6a0-4935-aa73-c01649cde4e7.png)

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/EXP-1553)

**Comment by jaredlockhart** [comment]
Good catch @pdehaan , let's remove the word `Targeted` from the summary page since it's not used on any of the other fields on either the form or summary pages.

**Comment by anthonytran7757** [comment]
Hey @jaredlockhart I'd like to take this
