### ISSUE TITLE
Move common Locales and Countries to the top of the list?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6076]
I'm not sure what the most common Locales and Countries are for real-world studies, but wondering if it makes sense to sort the countries by name, and then see if we can either duplicate common entries at the top so they're "above the fold" or just see if we can hardcode some values at the top of the react dropdown.
I imagine that "USA" is a pretty common target, but takes lots of scrolling.

![locales_and_languages_in_Fenix_–_Audience___Experimenter](https://user-images.githubusercontent.com/557895/127247744-aa7ecde9-8e04-4856-a1bb-00dfed7b7aae.png)

For example, to find "United States of America", you'd need to either scroll until you found "United States of America", or start typing at least "uni" then press the up arrow on the keyboard to select the item at the bottom of the list, and then click the item or press enter.

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/EXP-1554)

**Comment by jaredlockhart** [comment]
The field is searchable.  If we receive feedback about this from users we can address it then, closing this.
