### ISSUE TITLE
Add "Learn more about Nimbus analysis" Mana link to Results page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6079]
Related: EXP-1400

Add this to the Results page above the "Monitoring" heading: https://mana.mozilla.org/wiki/pages/viewpage.action?spaceKey=FJT&title=Nimbus+Onboarding#NimbusOnboarding-Part3:MonitoringandAnalyzingyourExperiment

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/EXP-1556)

**Comment by bhushan-borole** [comment]
Hey @jaredlockhart 
Can you tell me more about this issue, and how can I go about it?

**Comment by eliserichards** [comment]
Is this still valid? I don't think we have the "Monitoring" heading anymore.
