### ISSUE TITLE
Pressing Enter in a multiselect with no options highlighted causes the form to submit and refresh

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6086]
This has tripped me up a few times already today, so figure its possibly worthy of discussion.

https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/locales-in-fenix/edit/audience

### STR
1. Click in the Countries control.
2. Type "Canade" (something with a slight typo.
3. Click Enter because you thought you typed "Canada".

### Actual results
When the "No options" popup is visible and you click "Enter", the form submits with "Save and Continue" and refreshes to the [Summary page](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/locales-in-fenix).

<img width="474" alt="locales_in_Fenix_–_Audience___Experimenter" src="https://user-images.githubusercontent.com/557895/127551457-81c2454a-9036-411c-a62d-458541773465.png">

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/EXP-1559)

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

This is a good point but I’m not sure it’s worth the effort to start overriding the focus/submit behaviour of inputs on some fields rather than others so I’ll close this as a wontfix and if it starts tripping users up more we can refile.
