### ISSUE TITLE
Potentially confusing behavior around targeting US

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6087]
From Slack: https://mozilla.slack.com/archives/CANCHH6R1/p1627420174087700

TLDR: I don't think it's a bug, but there might be some confusing behavior around targeting "United States of America" and users potentially thinking it includes other territories like "Puerto Rico", "Guam". I can't remember if this was something we encountered on early VPN days when we released it to US-only, but learnt it wasn't available to people in US territories like Puerto Rico, Guam, etc.

> Looking at the Updating Targeting epic, and had an existential question about “What is America”. (I’ll add this as a comment/bug in the epic somewhere too, but was wondering where best to discuss). Like, I can select “United States of America” from the dropdown. But then USA is also weird with their “Virgin Islands (U.S.)” and “United States Minor Outlying Islands”, and “Guam”, and “Puerto Rico”, which I guess are all … territories but not official states. So, I guess the question is “If we’re targeting US for an experiment, would a person have to select all the territories, or would we just run the study in the contiguous 48 states, plus Hawaii/Alaska”

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/EXP-1560)

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

We’ve used the same targeting locale/region list on legacy(normandy) experiments for a while now and I can’t recall this being a significant issue for experiment targeting so I’m inclined to leave this alone unless some set of experiments becomes really complicated as a result.
