### ISSUE TITLE
Update "access visualization data locally" section of our docs

### ISSUE THREAD

**Issue by LZoog** [mozilla/experimenter#6089]
https://github.com/mozilla/experimenter/tree/main/app/experimenter/nimbus-ui#access-visualization-data-locally

I tried following our instructions recently and had trouble with it. The `testing-nimbus` bit should be updated to say that the experiment name/slug should exist in production and that the data being pulled will be from that experiment. Probably also need to tweak what it says about branches too.

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/EXP-1562)

**Comment by jaredlockhart** [comment]
I'd like to see some changes to the way we test the results data locally, but without further support from data tools our focus here is limited.  Closing this for now.
