### ISSUE TITLE
Cannot save experiment with empty Advanced Targeting selection

### ISSUE THREAD

**Issue by jodyheavener** [mozilla/experimenter#6093]
Not sure when this started happening but it looks like by default an experiment has no selection for the "Advanced Targeting" field on the Audience page. You cannot save the form with this field empty; you need to explicitly select the "No Targeting" option.

Furthermore, it looks like when you do selected the "No Targeting" option, save the form, and then reload the page the field returns to an empty state, preventing further saves.

This field should default to the "No Targeting" option, and use that option when there is no default value. It should not be possible to save this field with a truly empty value.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1563)

**Comment by jaredlockhart** [comment]
Good catch 👍

**Comment by pdehaan** [comment]
> Furthermore, it looks like when you do selected the "No Targeting" option, save the form, and then reload the page the field returns to an empty state, preventing further saves.

I think this is not getting pre-selected for _any_ targeting option. 
If I select "Homepage set to google.com", click "Save" then refresh the page, the Advanced Targeting dropdown is empty. I can go to the summary page and see my "Full targeting expression" and the JEXL is correctly checking for `hoemPageSettings.urls[.host == 'google.com']` but going back to the /audience page doens't reselect that option in the drop down.

**Comment by pdehaan** [comment]
Ah, and if you click "Save" with nothing selected for Advanced Targeting, you get yellow error message, but all the validation for the fields is green, so you don't know which of the valid fields is invalid.

> "Sorry, an error occurred while submitting. Please try again."

<img width="846" alt="deprecating-targeting-us-users_en__–_Audience___Experimenter" src="https://user-images.githubusercontent.com/557895/127699777-76d7a589-431a-4c07-b571-896b9d652c4f.png">

Devtools does give this though:
```
POST https://stage.experimenter.nonprod.dataops.mozgcp.net/api/v5/graphql 400. instrument.ts:158
```

**Comment by pdehaan** [comment]
Wait. looking at my screenshot above, is it a bug that the multi-select "Locales" and "Countries" are valid, but don't show the green rect or the checkmark like the other fields?
