### ISSUE TITLE
The status is not changed from "Accepted by Normandy" to "Live" after the experiment is launched and enabled

### ISSUE THREAD

**Issue by SoftVision-SimonaRosu** [mozilla/experimenter#6100]
[Prerequisites]:
- Have the Firefox browser installed.
- Have the [Normandy Devtools V2.3.1](https://github.com/mozilla-extensions/normandy-devtools/releases) addon installed.
- Have VPN access to the staging environment.
- Have a couple of browser profiles that can be targeted by Normandy Stage recipes. - [Normandy prerequisites](https://docs.google.com/document/d/13yxuvfpIGojY1FSsUJYHKUUQldKkSW0UzrUirdC0kQ0/edit#bookmark=id.k2nk5lj7jzh1)

[Steps to reproduce]:
1. Open the browser and navigate to "https://stage.experimenter.nonprod.dataops.mozgcp.net/".
2. Create a new "Pref-Flip Experiment" Delivery and leave the “Observation” section empty.
3. Click the "Begin Sign-Offs" button.
4. Check all the required Sign-offs from the "Required Checklist" section and click the "Save Sign-Offs" button.
5. Click the "Confirm Ready to Ship" button.
6. Click the blue "Send to Normandy" button.
7. Add the "qaOnly" flag in the "Additional Filter Expression" field and delete the content of the "import Instructions" field.
8. Approve the recipe and navigate to the experimenter ticket.
9. Publish the Normandy recipe and enroll a couple of profiles in the experiment.
10. Wait ~15 min, navigate to the study's Experimenter page and observe the status.

[Expected result]:
 - The status changes from "Accepted by Normandy" to "Live". 

[Actual result]:
 - The status remains as “Accepted by Normandy” even after more time has passed.

[Notes]:
- Also, the status is not changed from “Accepted by Normandy” to “Enrollment Complete” and “Complete” states when the experiment is paused, respectively disabled. 
- I didn’t manage to reproduce this issue after creating an experiment with the “Observation” section completed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1567)

**Comment by tiftran** [comment]
Hi @SoftVision-SimonaRosu,

Based on the instructions you left above, Experimenter is working as intended.

`Add the "qaOnly" flag in the "Additional Filter Expression" field and delete the content of the "import Instructions" field`.


As long as the qaOnly flag is left in the Normandy recipe, Experimenter will not update its status.

Please kindly open this issue if I misunderstood or there is something else :)
