### ISSUE TITLE
Every advanced targeting filter is displayed as deprecated in the Summary page

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6106]
**[Prerequisites]:**
- Have a desktop experiment with all the sections filled-in correctly until you reach the Audience page.

**[Steps to reproduce]:**
1. Have the Nimbus experiment page from prerequisites open on Audience.
2. Fill every field other than Advanced Targeting.
3. Select one of the Advanced Targeting options (e.g. Mac OS users only).
4. Click Save and Continue.
5. Observe the Advanced Targeting section from the Summary page.

**[Expected result]:**
- The new options from Advanced Targeting are not tagged as Deprecated.

**[Actual result]:**
- Every Advanced Targeting option, even if it doesn’t have a locale/country included, is tagged as Deprecated.

**[Notes]:**
- The Full targeting expression seems to be correctly set.
- Experiments with deprecated tags in Advanced Targeting can be launched from Draft state.
- Attached is a recording of the issue.

![deprecated](https://user-images.githubusercontent.com/53752296/127996044-eb34afa8-8777-4a94-8a60-42db14e418a3.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1570)

**Comment by jaredlockhart** [comment]
Thanks for catching @heres-maria !  This should be fixed here: https://github.com/mozilla/experimenter/issues/6093

Looks right to me on stage, but I'll wait for you to validate and then you should be able to close this 👍

**Comment by heres-maria** [comment]
I have verified that Advanced Targeting in Summary no longer displays deprecated the new filters in Firefox 90.0.2 (Build ID: 20210721174149).
