### ISSUE TITLE
Be able to add final "Recommendation" to the experiment results

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6111]
Feature request to be able to add a "recommendation" based on the experiment results directly in Nimbus. 

The user should be able to select their "recommendation" on the summary or results page at the end of an experiment, and the options should be:

* Rerun
* Proceed 
* Change course
* Stop

These are based on the Mana template that product managers use when doing experiment share outs (https://mana.mozilla.org/wiki/display/FPS/Template%3A+%5BArea%5D+Experiment+Name) 

This should be something that a user can also filter by and search for experiments in the directory view

┆Issue is synchronized with this [Jira EXP Request](https://mozilla-hub.atlassian.net/browse/EXP-1574)

**Comment by jaredlockhart** [comment]
This is done!
