### ISSUE TITLE
PageHome "loading" story errors + stories/tests using RouterSlugProvider?

### ISSUE THREAD

**Issue by LZoog** [mozilla/experimenter#6113]
Our Storybook stories for PageHome use `RouterSlugProvider` and shows the location as `demo-slug/edit` which is not correct. Passing in `path="/"` renders a blank page. We're also using this instead of `MockedCache` in tests, which isn't a big deal by any means but doesn't feel correct.

Also, as of #6107, the QueryError story needs different mocks provided than what we've got in `storyTemplate`. It seems like there's some room for cleanup here.

Additionally, the "Loading" story for this page renders the same as an error.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1575)

**Comment by jodyheavener** [comment]
Related convo https://github.com/mozilla/experimenter/pull/6084#discussion_r681975766

**Comment by jaredlockhart** [comment]
Closing this in favour of deprecating storybook entirely.
