### ISSUE TITLE
Some Experiments are stuck in preview after the recent Audience targeting deprecation 

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#6125]
**[Prerequisites]:**

* Have an Desktop experiment in the `Preview` state. (eg. [https://experimenter.services.mozilla.com/nimbus/firefox-suggest-history-vs-online)](https://experimenter.services.mozilla.com/nimbus/firefox-suggest-history-vs-online))

**[Steps to reproduce]:**

1. Change the Nimbus code so that the Audience section needs to be changed for experiments to be valid for launch.
1. Navigate to the experiment from prerequisites and observe it's status.

**[Expected result]:**

* The experiment is in preview and can either be launched or moved back to draft.

**[Actual result]:**

* The experiment is stuck in preview because the audience section is no longer valid.

**[Notes]:**

* Found in Prod.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1585)

**Comment by jaredlockhart** [comment]
Oh yep good catch @SoftVision-CiprianMuresan.  We need to change the frontend logic to note gate the launch/end buttons on the ReadyToShip serializer if it's not in Draft.

**Comment by SoftVision-CiprianMuresan** [comment]
Marking this as Verified as Nan confirmed on Slack that he can place the experiment back into the `Draft` state to make the necessary changes.
