### ISSUE TITLE
PIP install error during integration test runs in CI

### ISSUE THREAD

**Issue by lmorchard** [mozilla/experimenter#6132]
As seen in PR #6130 and PR #6109, there's [an error during pip install for the integration test containers](https://app.circleci.com/pipelines/github/mozilla/experimenter/10639/workflows/f906910f-5ec1-4e96-ad1d-34bba336f801/jobs/31638).

```
INFO: pip is looking at multiple versions of pytest-base-url to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r ../requirements.txt (line 4) and tenacity==7.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested tenacity==7.0.0
    pytest-selenium 2.0.1 depends on tenacity<7 and >=6

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
WARNING: You are using pip version 21.1.3; however, version 21.2.2 is available.
You should consider upgrading via the '/code/app/tests/integration/.tox/integration-test-nimbus/bin/python3 -m pip install --upgrade pip' command.
ERROR: InvocationError for command /code/app/tests/integration/.tox/integration-test-nimbus/bin/pip install -r ../requirements.txt (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   integration-test-nimbus: commands failed
ERROR: 1
make: *** [Makefile:163: integration_test_nimbus] Error 1

Exited with code exit status 2

CircleCI received exit code 2
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1588)

**Comment by lmorchard** [comment]
Trying to reproduce locally. Had to resort to a fully fresh install with respect to docker:
```
make kill
docker system purge -a
make refresh
make up_prod_detached
make integration_test_legacy
```

**Comment by lmorchard** [comment]
[Last update to `requirements.txt` was 10 days ago.](https://github.com/mozilla/experimenter/commit/f48b83e62752fbc7babc041b29368b0078bf9a6b) And I thought the exact dependencies were locked down with versions & hashes. 

Also really weird: [pytest-selenium 2.0.1 was upgraded to 2.0.1 over 10 months ago](https://github.com/mozilla/experimenter/commit/8e563a97d99cd4f4ef7c4ce8cd974d04f30c87d1) while [tenacity was upgraded to 7.0.0 over 5 months ago](https://github.com/mozilla/experimenter/commit/96f2508bc92dcdea0c92c6d9a978f274c5a9e42b). Not sure why this conflict would emerge now?

**Comment by lmorchard** [comment]
Got pip install to succeed [by reverting some upgrades to idna and tenacity](https://github.com/mozilla/experimenter/compare/6132-pip-install-error). Doesn't make much sense, since those upgrades happened awhile ago.

**Comment by lennartschoch** [comment]
Seems like my PR #6099 is also failing because of this.
My suspicion is that this has to do with the Docker image used by the integration tests.
The installation started failing around the time @jrbenny35 created [this commit](https://github.com/jrbenny35/selenium-firefox/commit/2a81a950ecd9eadda92907f8841f311aa66801b9) that upgrades Python inside the image.

**Comment by jrbenny35** [comment]
I updated the selenium-firefox image last night to run python 3.8. I wonder if this would be causing the errors.
