### ISSUE TITLE
The links from the Additional Links section are incorrectly underlined when hovered

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#6133]
**[Prerequisites]:**
- Have an Desktop experiment in the `Draft` state.
- Have `Additional Links` added to the experiment.

**[Steps to reproduce]:**
1. Navigate to the Nimbus experiment page from prerequisites and scroll down to the `Overview` section.
2. Hover one of the Additional Links and observe the underline.

**[Expected result]:**
- The underline is displayed under the string.

**[Actual result]:**
- The underline is displayed between the words.

**[Notes]:**
- The issue is not reproducible with `Learn More` links from the Sign-offs section.
- Attached is a screenshot of the issue.

- incorrect underline:
![image](https://user-images.githubusercontent.com/18304511/128521704-59a4a7b8-fea9-4f38-ab08-b1b70a5ab055.png)

- correct underline:
![image](https://user-images.githubusercontent.com/18304511/128521829-4bc7a2b5-a7dd-44d1-9d83-43ffedc28691.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1589)

**Comment by jodyheavener** [comment]
Simply removing `align-middle` from [this line](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/Summary/TableOverview/index.tsx#L71:L71) fixes the issue (it ever so slightly throws off the vertical alignment of the icon, but 🤷)

**Comment by jaredlockhart** [comment]
Wontfix.  If this is really troublesome somebody will refile.
