### ISSUE TITLE
[Enhancement] Modify how additional links are added to be easier to differentiate between them

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6136]
**[Prerequisites]:**
- Have a Nimbus experiment draft already created.

**[Steps to reproduce]:**
1. Have the Nimbus experiment page from prerequisites open on Overview.
2. Add more than one Engineering Ticket type link in Additional Links (e.g. Jira and Bugzilla).
3. Save the experiment.
4. Go to Summary and observe how the links are displayed.

**[Proposed result]:**
- Add a separate type of additional link for QA Jira tickets so that they are easier to identify at first glance on the Summary page as different from the Engineering ticket.
OR
- Modify the Additional Links section so that the names of the different types of links are editable once chosen, since they’re the text displayed by that link on Summary. 
That way, users would get a template to start from, while being able to customize what their links are called, so they don’t have multiple links with the same name displayed. 
e.g. you choose three “Engineering Ticket (Bugzilla/Jira/Github)” links. The “Engineering Ticket (Bugzilla/Jira/Github)” strings are now editable, so you can rename one “QA Jira Ticket”, one “ Engineering Ticket (Bugzilla)”, and one “Engineering Ticket (GitHub)” if you want to do that.

**[Current result]:**
-  If a user wants to add multiple tickets of one type, the Summary page displays them with the same name, and you have to hover them to see what type they are exactly. Since QA and Engineering would be categorized in the same type, the case where the links have the same name seems like it would be common.

**[Notes]:**
- Attached is a recording of the current behavior.
![additional links](https://user-images.githubusercontent.com/53752296/128523756-a419121f-b6e5-4a67-9283-9c90d5a681ef.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1592)

**Comment by jaredlockhart** [comment]
Oh yes great point @heres-maria there's no way to distinguish the links, we should totally fix that 👍

**Comment by jaredlockhart** [comment]
@shell1 is filing an epic to review the additional links UX and workflow so we can review that there EXP-2162
