### ISSUE TITLE
There are 2 “Japanese” locale options in the Nimbus “Locales” field

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6140]
**[Prerequisites]:**
- Have a Nimbus desktop experiment draft already created.

**[Steps to reproduce]:**
1. Open the draft from prerequisites on “Audience”.
2. Click the “Locales” field.
3. Write “japanese”.

**[Expected result]:**
- There is only one “Japanese” option displayed.

**[Actual result]:**
- There are two “Japanese” options displayed.

**[Notes]:**
- On the Summary page they are listed as ['ja', 'ja-JP-mac'].
- Attached is a recording of the issue.

![japanese](https://user-images.githubusercontent.com/53752296/128703266-7ab5856d-4b52-4b0e-bed6-be040b7bcab0.gif)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1595)

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Oh yeah sounds good to me.

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Probably a good first bug for a contributor 👍

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Should it block the epic?

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

I’ll take it out of the epic

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

Oh yeah, it shouldn’t block the epic, thnx 👍

**Comment by anthonytran7757** [comment]
hey, @jaredlockhart I'd like to pick this one up!

**Comment by heres-maria** [comment]
@jaredlockhart As the issue is still reproducible both on Stage and Prod, I am going to reopen it,

**Comment by jaredlockhart** [comment]
Yeah we'd need a data migration to remove it from the stage/prod dbs, but that's risky becuase it could cascade delete other entities.  I'm not sure this is significant enough to warrant the risk.  I will close this and if it becomes a problem in the future we can refile and address it then.
