### ISSUE TITLE
Desktop Feature Manifests

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6156]
**Objective:** Features should appear in the Console automatically after landing in Firefox so that it is easy for teams to add new features without assistance from a Console admin. This work will also enable us to add UI that replaces the JSON editor for feature variables in a future sprint.

**Scope:** The first iteration will only apply to Desktop Firefox, and only pull from the latest version of the manifest (i.e. in Nightly).

**Non-functional requirements**

* The architecture should be designed in such a way that adding support for **per~~channel/per~~version** manifest reading is an extension, not a complete rewrite, of the functionality.

**Creating new experiments**

* When an owner makes a new experiment for a given application for a feature currently defined in the Nightly manifest, they should be able to select a feature defined in that application’s manifest file.
* When an owner makes a new experiment targeting a _past version_ for a feature that no longer exists in nightly), they should not see the feature but they can click “Custom” to add a custom feature
* When an owner makes a new experiment that doesn’t exist in a manifest (e.g. as they are developing a new feature that hasn’t landed), they can click “Custom” to add a custom feature.
  * I should be able to create multiple custom experiments that have the same id.

**Validating variables**

* When an owner adds a variable that exists in its manifest entry and is valid, it should not throw any errors.
* When an owner adds a variable X that doesn’t match its specified type, it should show a warning in the UI that “variable X is the wrong type….”
* When an owner adds a variable X that doesn’t exist in the manifest , it should show a warning in the UI that “variable X is not defined for this feature”
* When an owner DOESN’T include a variable,  “variable X is defined for feature and doesn’t have a value”

**Adding new features**

* When an engineer lands a new feature in the manifest of an application, the feature should be available to  the owner via UI within 24 hours.
  * We should have documentation for people to know how to ask to bump the deploy if they need it sooner
  * We should have documentation about how to create custom feature for now
* An engineer should be able to add variables of type string, boolean, integer, json
* An engineer should be able to add “choices” to a variable for strings

**Modifying existing features**

* When a feature id is renamed, the feature will be treated like a new feature.
* When new variables are added
* When the type of a variable changes
* When variables are removed 
* When adding a release experiment for a feature that doesn’t match the variable set in Nightly, the owner will have to leave out the extra fields that don’t exist or use the custom option if the type has changed. 
  * There should be “warning” documentation that explains this and warns people to do QA to check this.

**Removing features**

* If a user tries to create an experiment for a feature that was removed in Nightly, they should not see the feature and will have to use the “Custom” option.

**Viewing past experiments**

* When viewing a past experiment on the summary page with a feature X  that is no longer defined in the manifest
  * The “Feature config” row should show “Deprecated: X”
  * The feature id and variable definitions should appear as normal in the DTO and in the branch definition
* When filtering by feature on the Directory view, a user should be able to see _all_ features, including deprecated and existing feature ids.
* When selecting an id of a custom-defined feature id “xyz” in the feature filter, I should see all experiments that defined a custom feature id “xyz”

**Client requirements**

* It should not be possible to use the Nimbus SDK API for a feature without registering it in a manifest.
* All features that are currently in use or are intended to be used in the experimenter DB should be migrated to application manifests before landing these changes.

**Enabling stories**

* Experimenter should read from the Desktop Manifest ([https://hg.mozilla.org/mozilla-central/raw-file/default/toolkit/components/nimbus/FeatureManifest.js](https://hg.mozilla.org/mozilla-central/raw-file/default/toolkit/components/nimbus/FeatureManifest.js)), with an expected format of [https://searchfox.org/mozilla-central/source/toolkit/components/nimbus/schemas/ExperimentFeatureManifest.schema.json](https://searchfox.org/mozilla-central/source/toolkit/components/nimbus/schemas/ExperimentFeatureManifest.schema.json|smart-link) 
* Experimenter should read from iOS and Fenix Manifests, which should be compliant with the above schema.

**Describing telemetry in Feature Manifests**

* There should be a required field for a description of the implementation/meaning of the exposure event for each feature. For example:
  * “Exposure is sent every time the new tab page loads”
  * “Exposure is sent once per browsing session at startup if the feature is active”

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/EXP-1608)

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Note: CFR has a specific schema that would be nice to have… could we support JSON schemas for JSON variables?

Also we would need create feature definitions for messaging system stuff for CFR etc. Victor Andrei Oprea

**Comment by Mardak** [comment]
Not quite sure where the changes were made to automatically load desktop FeatureManifest.js but currently "json" type is converted to "string" which led to filing https://bugzilla.mozilla.org/show_bug.cgi?id=1737375 to update aboutwelcome feature.

**Comment by Mardak** [comment]
Ah found #6451. Maybe this should be marked fixed? Although I see it only supports these 4 source types and 3 output types:
https://github.com/mozilla/experimenter/blob/1be1a85fe541de93c029b95611ac416b0e8234f0/app/experimenter/features/__init__.py#L20-L24

I needed to set "array" as the type to get things working for aboutwelcome `screens`

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Jared will make a new epic, in which several of the bugs/issues tracked here will be moved. Expect this epic to close.
