### ISSUE TITLE
Some locales are not available as options in the Nimbus “Locales” field

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6165]
**[Prerequisites]:**
- Have a Nimbus desktop experiment draft already created.

**[Steps to reproduce]:**
1. Open the draft from prerequisites on “Audience”.
2. Click the “Locales” field.
3. Write “Scots”.

**[Expected result]:**
- There is a “Scots” (code “sco”) option.

**[Actual result]:**
- There is no “Scots” (code “sco”) option.

**[Notes]:**
- This issue is also reproducible for “Silesian” (code “szl”). 
- The locales appear in https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/locales/l10n-changesets.json.
- Attached is a recording of the issue.

![scots silesian 1](https://user-images.githubusercontent.com/53752296/128892961-fb98058c-9006-48cc-a98b-209e6772d9f3.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1609)

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

It looks like there are 8 locales not present in our \codebase ( https://github.com/mozilla/experimenter/blob/main/app/experimenter/base/fixtures/locales.json ), when comparing to l10n-changesets.json:

["bo", "ckb", "hye", "meh", "scn", "sco", "szl", "tg" ]

Jared Kerim any reason I can’t just add them to the fixture?

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Yep you can add them to the fixture but that won’t add them in stage/prod so we’ll have either get ops to manually run a command to load them in or write it as a data migration.  Maybe data migration?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

https://bugzilla.mozilla.org/show_bug.cgi?id=1726154 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1726154|smart-link )  filed to load the new locales fixture

**Comment by heres-maria** [comment]
I have verified that the following locales have been added to the locale list: Scots (code: sco), "Silesian (szl), Tibetan (bo), Central Kurdish (ckb), Armenian Eastern Classic Orthography (hye), Mixteco Yucuhiti (meh), Sicilian (scn), Tajik (tg).
I have also verified that I can enroll on stage in an experiment that used these locales using Firefox Nightly 93.0a1 meh (Build ID: 20210819095342).

**Comment by jodyheavener** [comment]
@heres-maria I don't think these locales are available in prod yet, still working on it

**Comment by heres-maria** [comment]
@jodyheavener yes, I just noticed this too. I'm sorry, I will remove the verified fixed tag and will retest this in prod when the bugzilla bug is closed.

**Comment by jodyheavener** [comment]
@heres-maria This should be verifiable in prod now :)

![Screen Shot 2021-08-19 at 5 13 04 PM](https://user-images.githubusercontent.com/6392049/130137452-07bf0a03-7077-4cc9-938c-12711dafa725.png)

**Comment by heres-maria** [comment]
Thank you. I have verified that the Scots (code: sco), "Silesian (szl), Tibetan (bo), Central Kurdish (ckb), Armenian Eastern Classic Orthography (hye), Mixteco Yucuhiti (meh), Sicilian (scn), Tajik (tg) are now also available in the Locales field in production. 
As a result, I will mark this issue verified fixed.
