### ISSUE TITLE
Filter options with longer names will wrongly vertically resize a Nimbus filter field

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6175]
**[Prerequisites]:**
- Have the Nimbus main page open.

**[Steps to reproduce]:**
1. Click the “Feature” filter field.
2. Select the “No Feature Firefox Desktop” option.
3. Observe the field.

**[Expected result]:**
- The field is not resized for a single option.

**[Actual result]:**
- The field is vertically resized for single options with longer names.

**[Notes]:**
- The issue is reproducible for all filter fields.
- Attached is a screenshot of the issue.

![Screenshot from 2021-08-11 09-15-24](https://user-images.githubusercontent.com/53752296/129035433-42f34767-b8d6-46fa-b310-ba476e117941.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1612)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Not sure we can really control that too much, it’s the built-in behavior of the multi-select component to make room for additional options. Seems weird in this case with one option, but might be tough to change.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Hmm, looking at this further, I see that the blank space there is actually the text entry field for the multi-select. If you click on it, a cursor appears for typing a partial option. I think this is actually working as intended.
