### ISSUE TITLE
[Enhancement] Consider making it more obvious that the "Public name" has an 80 character limit

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#6184]
**[Steps to reproduce]:**
1. Navigate to the Nimbus homepage and click the blue "Create New" button.
2. Write a 81 character long string in the "Public Name" field.
3. Fill all other fields with valid data and click next.

**[Expected result]:**
- The field gains a red border and an error message is displayed in forming the user that the "Public Name" field needs to be under 81 characters.

**[Actual result]:**
- The field continues to have a green border, a green checkmark in it, and a generic "Sorry, an error occurred while submitting. Please try again." error is displayed.

**[Notes]:**
- Attached is a screenshot of the issue:

![image](https://user-images.githubusercontent.com/18304511/129164969-1a51cfd6-e2f9-40c9-96c8-5fefed403106.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1617)

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

Oh yes good call we should definitely cap this field 👍

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

And display a more informative error message.  We can probably also cap the input so users can’t even enter more than 80 characters.

**Comment by heres-maria** [comment]
I have verified that the Public name of an experiment displays the "Cannot be greater than 80 characters" front end error when input is over 80 characters and that saving the experiments in that state does not save that name. 
Verified using Firefox 91.0.1 (Build ID: 20210816143654).
