### ISSUE TITLE
[Enhancement] Consider adding a warning when approving an experiment if other changes were requested in the same timeframe

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#6186]
This is more of a user story but I've hit this "problem" when testing the Nimbus flows at the same time as others we're making changes.
If multiple launches are approved at the same time, the "Open RS" button redirects to https://settings-writer.stage.mozaws.net/v1/admin/#/buckets/main-workspace/collections/nimbus-desktop-experiments/simple-review which only shows the latest change pending in RS. Due to inattentiveness on my part I've managed to approve changes that were not the changes I requested.

I'm wondering if there's any way that Nimbus could throw up a warning when multiple experiments have changes pending in RS.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1619)

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

Yeah this is definitely a pretty critical issue that I’ve struggled with.  I think our two primary mitigations here are

  1. So far we don’t have a high enough frequency that collisions like this are likely
  2. It’s a pretty important role of the reviewer to look carefully at the record they’re reviewing

For testing I can understand you’re flying through so many of them that it’s easy to miss.  I’m hestitant to make any major changes to the UI around this workflow until we hit more production issues that we can unpack with users.  For testing, if you hit the wrong record you can just reject it and the next one in line will show up after a few minutes.  See how far you can get with the workflow as it is now, and if it really becomes a tremendous hassle then we can think about it some more, but I’d rather wait until it’s absolutely necessary.
