### ISSUE TITLE
After sorting/filtering you can't navigate back to an experiment after using the "< Back to Experiments" button

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#6207]
**[Steps to reproduce]:**
1. Navigate to the Nimbus homepage and sort the page a few times.
2. Create a new experiment.
3. Fill the fields with valid data and save the experiment.
4. Click the "< Back to Experiments" button.
5. Click the Browser's "Back" button and observe the behavior.

**[Expected result]:**
- The previously created experiment page is displayed.

**[Actual result]:**
- The homepage is refreshed.

**[Additional Notes]:**
- The issue is also reproducible when navigating to the homepage from an already existing experiment.
- You can get back to the experiment page through the Back button's context menu.
- Attached is a screen recording of the issue:

![cant go back to an experiment after using sorting or filtering](https://user-images.githubusercontent.com/18304511/129369381-efeb3362-47ab-432f-b7c0-3a6fae4057bf.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1631)

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible. Following the STR will return the user to the experiment page. 
Tested on Firefox Release 91.0.1 (Build ID: 20210816143654).
