### ISSUE TITLE
More responsive design on nimbus homepage?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6227]
<img width="950" alt="Experiments___Experimenter" src="https://user-images.githubusercontent.com/557895/129638960-91a4da38-33be-4ca7-a35d-f0f01faf978b.png">

**Figure 1:** [Nimbus homepage](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus?tab=drafts&owners=pdehaan%40mozilla.com&application=DESKTOP%2CFENIX%2CIOS%2CFOCUS_ANDROID%2CKLAR_ANDROID&featureConfig=no-feature-firefox-desktop%2Cno-feature-fenix%2Cno-feature-ios%2Cupgradedialog%2Curlbar%2Cfenix-default-browser%2CnimbusValidation%2Cfenix-android-keystore%2Cinfobar%2Ccfr%2Caboutwelcome%2Conboarding-default-browser%2Cprivatebrowsing%2Cnewtab%2Cno-feature-focus-android%2Cno-feature-klar-android&firefoxMinVersion=FIREFOX_11) half screen on my 15" rMBP.

It doesn't look like the 4 columns/fields ever reflow, just get narrower to the point of you can only see a few characters.
Not sure if we want to try adding 1-2 more breakpoints so that we get 2 rows of 2 columns for the drop down menus (Feature+Application, Owner+Version).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1637)

**Comment by jaredlockhart** [comment]
We'll wait to see if this becomes really critical.
