### ISSUE TITLE
Sort features by name?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6228]
It doesn't look like features are sorted by value (or any sorting; but maybe it's just natural sorting). Not sure if we want to do an "order by" somewhere to make it alphabetical or something else.

Homepage filtering:
![Experiments](https://user-images.githubusercontent.com/557895/129640989-d4bcec95-ce1b-40f7-aa79-cd0d6fb0b4b3.png)UNITO-UNDERSCORE!!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!Experimenter!

- - -
[/edit/branches](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/first/edit/branches):
![FIRST_–_Branches](https://user-images.githubusercontent.com/557895/129641326-56e84e9e-1b51-4436-827d-091b522872df.png)UNITO-UNDERSCORE!!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!Experimenter!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1638)

**Comment by jaredlockhart** [comment]
We should totally do this.

**Comment by purna135** [comment]
I'd like to get started on this, but I'm a beginner. Could you please point me in the right direction?

**Comment by mikewilli** [comment]
This looks like it was fixed on the backend. In testing I verified that the dropdowns shown above are sorted, and the response from GraphQL is already sorted coming to the client


**Main page dropdown**:
<img src="https://user-images.githubusercontent.com/102263964/163867882-26685767-44cc-4757-8d7b-f5549ba1af93.png" width="240" height="360">

**/edit/branches**:
<img src="https://user-images.githubusercontent.com/102263964/163867886-ed4b4ec2-3596-4162-a0e9-cd695f9af595.png" width="240" height="460">
.
