### ISSUE TITLE
Display submitError for archiving somewhere if it occurs?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/experimenter#6234]
While looking into issue #6229, I noticed that while [we return a `submitError`](https://github.com/mozilla/experimenter/blob/a2fe7fc84bd455bdb27b1c29a41259bdff3be405/app/experimenter/nimbus-ui/src/hooks/useArchive.tsx#L65) from the mutation hook if/when archiving fails, we [don't actually use it or display it anywhere](https://github.com/mozilla/experimenter/blob/a2fe7fc84bd455bdb27b1c29a41259bdff3be405/app/experimenter/nimbus-ui/src/components/SidebarActions/index.tsx#L18-L25). So, if there's an error during archiving / unarchiving, it'll be a silent failure. We might want to throw an error message into a bubble portal somewhere maybe?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1642)

**Comment by jaredlockhart** [comment]
This is a good idea but we'll close this until it blocks someones workflow.
