### ISSUE TITLE
Create the DS ticket required in the additional links section on Nimbus

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6235]
We've gotten some feedback from customers that they would like to have the DS ticket required so that they can always have access to it through Nimbus. This might also be helpful for other teams, such as QA, and people who might be looking at the experiment.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1643)

**Comment by jaredlockhart** [comment]
Closing in favour of revisiting the UX of the additional links. @shell1 will file a story to rethink additional links.

**Comment by shell1** [comment]
https://mozilla-hub.atlassian.net/browse/EXP-2162 is the story for this
