### ISSUE TITLE
Be able to have a high level summary of the experiment in Nimbus

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6238]
Customer feedback was that overall it was hard to get a good understanding of what the experiment is if you're not involved in the experiment from the summary page. The summary page includes a lot of information relevant for QA and engineering, but it's hard to find information relevant to the experiment at a high level, for example, all the Jira tickets, hypotheses, context, etc... it's buried under in all the other information which might make it easy to miss. 

The use case was if you were new to the team, leadership, or from another team and browsing through experiments that were run, it'd be difficult to understand the experiment, and if it was a follow up experiment or a completely new idea. 

The request here would be to have a high level view of the more important information at the top, and potentially know if this is a follow up experiment.

┆Issue is synchronized with this [Jira EXP Request](https://mozilla-hub.atlassian.net/browse/EXP-1645)

**Comment by jaredlockhart** [comment]
This is done.
