### ISSUE TITLE
Add multi-retry when you encounter a GraphQL polling error on homepage

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6239]
Related to #6039; "An error occurred while looking up experiments: JSON.parse"

@Mardak mentioned in [Slack](https://mozilla.slack.com/archives/C011MC5EB0V/p1629230456024100?thread_ts=1626799999.145500&cid=C011MC5EB0V) that he saw the error again (although slightly different UI now, due to the previous fix w/ expanded details).

> looks like the error message got expanded to show more details. i first got a yellow “this might be because mid-deploy. trying again 5 seconds” which then refreshed to show a red message for a server error responding with html (resulting in JSON.parse failure). then it very quickly went away to show the expected content

Per @LZoog (in aforementioned Slack thread above):

> Right now, it just retries once since that seemed like it’d fix what was described. In a follow up issue we could update that to keep retrying with backoff.
> Dang, and I really hoped that would be enough to fix this. Just feels… kinda strangely flakey.
> Yeah so that was another thing I was thinking about… the error shown in red should get logged, but we’re not doing that for the errors shown in yellow because it didn’t seem like we should

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1646)

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Related https://mozilla-hub.atlassian.net/browse/EXP-1537 ( https://mozilla-hub.atlassian.net/browse/EXP-1537|smart-link )

**Comment by jaredlockhart** [comment]
This is a good idea but I don't think it's something we shoudl focus our attention on right now so I'm going to close this.
