### ISSUE TITLE
Add message for why an experiment has been archived?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6241]
Via comment in [The Epic](https://mozilla-hub.atlassian.net/browse/EXP-1182?focusedCommentId=450039):
> Are there plans to add a “why”? Sure it’s archived but why is it archived.

I think this would be super nice in case you're archiving a bad experiment, or somebody else's experiment on production, etc. I suppose it could be optional, but probably doesn't hurt to always slap a few keys as to why you're archiving something to the experiment graveyard.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1647)

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Per discussion with Jared Lockhart we’re gonna pass on this for now. Here’s the PR in case we want to revisit it down the road: https://github.com/mozilla/experimenter/pull/6260 ( https://github.com/mozilla/experimenter/pull/6260|smart-link )
