### ISSUE TITLE
Archiving an experiment while in Draft mode doesn’t redirect you to the Summary page

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/experimenter#6247]
**[Prerequisites]:**
- Have a Nimbus experiment saved in Draft mode.
- Have the drafted experiment page open.

**[Steps to reproduce]:**
1. Select one of the “Edit” sections from the sidebar (Overview, Branches, Metrics, Audience).
2. Click the “Archive Experiment” option from the sidebar.
3. Observe the behavior.

**[Expected result]:**
- You are redirected to the "Summary" page.

**[Actual result]:**
- You remain on the “Edit” section selected at step 1.

**[Notes]:**
- This issue is reproducible with Firefox Release 91, Chrome (Version 92.0.4515.159), and Chromium (Version 92.0.4515.131) browsers, across platforms (Windows 10 x64, Ubuntu 20.04, and macOS 11.5.1).
- Attached is a recording of the issue.

![summary page](https://user-images.githubusercontent.com/26000308/129918420-98532f12-49ec-4116-945d-c997bc527045.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1651)

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible. Clicking the Archive button while on Overview, Branches, Metrics or Audience will now redirect the user to Summary. Tested using Firefox 91.0.2 (Build ID: 20210823123856).
