### ISSUE TITLE
Remove all scrollspy stuff

### ISSUE THREAD

**Issue by LZoog** [mozilla/experimenter#6249]
In #6031 a bug was reported where if the sidebar nav was too long, users couldn't see the bottom of the list.

We solved this by making the sidebar unfixed. However, now the sidebar seems significantly less useful as 1) you can only click on sections when you're scrolled to the very top part of the page and 2) you can't see where you are when you're scrolling down the page.

We can either add an independent scrollbar for the sidebar and leave it at that, or add the 2nd scrollbar and try adjusting font-size/margins to accommodate more cases with a lot of results in the sidebar, or add the 2nd scrollbar and have it scroll up/down when the user is at that part of the page. Or, if we leave this as-is, we should just remove all the scrollspy pieces/package.

Personally I'm thinking we try the 1st or 2nd solution, the 3rd is ideal but seems like a much higher level of effort (maybe we can look at it in a separate maintenance task?).

Willing to hear pushback of course, but the nav just seems way less helpful if we leave the sidebar as-is. There will also be new "actions" to consider that will live under this section, however.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1652)

**Comment by jaredlockhart** [comment]
Where does this feedback come from @LZoog ?

**Comment by emtwo** [comment]
> Where does this feedback come from @LZoog ?

Myself and Lauren discussed this and it can't be useful if you can't see it

**Comment by emtwo** [comment]
I think a quick fix like adding a scrollbar to the sidebar would be nice but after some discussion with Jared, there are some higher priorities like segmentation and exposure analysis so we may sadly have to put this on hold

**Comment by jaredlockhart** [comment]
Yep, I take your point.  I'd rather wait until we get feedback from users that they're having trouble with it before we do anything, so I'm going to close this and if we get feedback from users that it's an issue we can either reopen it or refile it.

**Comment by LZoog** [comment]
@jaredlockhart but we need to remove scrollspy code and package, if we want to leave it as-is. We've got an extra dep now and code around it.

**Comment by jaredlockhart** [comment]
Ah ya @LZoog points out that there's still orphaned code in here we should remove, let's refocus this just for removing scrollspy and related react fragments.

**Comment by jodyheavener** [comment]
I agree that if this is being closed as wontfix that scrollspy needs to come out - it's doing nothing

**Comment by jaredlockhart** [comment]
@LZoog can you please add a bit of detail about which lines need to come out?

**Comment by LZoog** [comment]
We can remove the package and the import in `AppLayoutWithExperiment`. There's a couple comments on there that can be taken out after they're read/accounted for ([here](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/AppLayoutSidebarLaunched/index.tsx#L166) and [here](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/AppLayoutSidebarLaunched/index.tsx#L125)), and the actual scrollspy container [here](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/AppLayoutSidebarLaunched/index.tsx#L161). IIRC we can clean up those `<li className="ml-3 mb-2">` inside that scrollspy and change them to become `<LinkNav`. There might be some other clean up bits there but I'd say this is a 2 pointer.
