### ISSUE TITLE
[Integration-Tests] Use django admin to create experiments for tests that just need an experiment

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/experimenter#6250]
Not all of the integration tests need to go through the create experiment flow. We should create some experiments to be specifically used by the integration tests. We can do this using django admin, or hijack the "dummy experiment" generator.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1653)

**Comment by jaredlockhart** [comment]
Yeah doing it with the dummy experiment generator would be the way.  If we need a specific set of experiments created we can creat ea second parallel one called like `generate_integration_test_experiments` that sets them up in teh states the tests expect.

**Comment by jaredlockhart** [comment]
This is a nice optimization but we should leave it until we really can't manage with the existing test workflow.
