### ISSUE TITLE
[Sentry] Problem installing fixture '/app/./experimenter/base/fixtures/locales.json'

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6258]
Looks like this was found in Prod via Sentry:

> IntegrityError: Problem installing fixture '/app/./experimenter/base/fixtures/locales.json': Could not load base....
> Culprit
> django.db.backends.utils in _execute

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1657)

**Comment by pdehaan** [comment]
Hhmm, we [recently tweaked](https://github.com/mozilla/experimenter/pull/6217) some locales, but I thought the locales.json has been around for a while, so not sure why it's panicking today.

**Comment by pdehaan** [comment]
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1726154 (via this lengthy [Slack thread](https://mozilla.slack.com/archives/CANCHH6R1/p1629320114216100?thread_ts=1629316033.202900&cid=CANCHH6R1))

**Comment by jodyheavener** [comment]
Another lengthy [Slack thread](https://mozilla.slack.com/archives/CANCHH6R1/p1629320397217000)

Basically, we're going to manually insert the locales in prod

**Comment by jaredlockhart** [comment]
Fixed in prod now 👍
