### ISSUE TITLE
The UI of the main Nimbus page slightly shifts horizontally when adding some filters

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6259]
**[Prerequisites]:**
- Have the Nimbus main page open.

**[Steps to reproduce]:**
1. Click the Feature filter field.
2. Select one of the options (e.g. No Feature Firefox Desktop)
3. Observe the page.

**[Expected result]:**
- The page does not shift horizontally.

**[Actual result]:**
- The page slightly shifts horizontally (to the right).

**[Notes]:**
- Possible regression from #6206
- This is reproducible for the other filter fields as well.
- Attached is a recording of the issue.

![horizontal shift](https://user-images.githubusercontent.com/53752296/130072363-963756b0-164f-4612-bbcc-e9ec0020af5e.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1658)

**Comment by jaredlockhart** [comment]
Yep that's just the scrollbar showing up and leaving, classic problem and not worth worrying about 👍
