### ISSUE TITLE
Some visualization tooltips are rendered as pre+code blocks w/ horizontal scrolling

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6261]
➤ Jody Heavener commented:

Yeah so looks like this is parsing Markdown into a code block. So we can style the code block to a lighter text color. But I’m more curious about why we’re writing this description as a markdown code block? We can style it white but it’s still going to display as monospace typeface. Jared Kerim do you have insight into this?

_Originally posted by @data-sync-user in https://github.com/mozilla/experimenter/issues/6054#issuecomment-895181635_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1659)

**Comment by pdehaan** [comment]
![Default_Browser_Adoption_Experiment_-_Release_–_Analysis___Experimenter](https://user-images.githubusercontent.com/557895/130118687-45aebbb6-8129-4035-a120-4cf4cc351cd3.png)

**Comment by LZoog** [comment]
This is coming directly from the Jetstream metadata, we just plop the metric `description` output in the tooltips. It should be updated over there if this was by accident. cc @scholtzan

**Comment by jaredlockhart** [comment]
I'll close this until this is brought up again.
