### ISSUE TITLE
[BE] Send exposure analysis by default if it's available 

### ISSUE THREAD

**Issue by emtwo** [mozilla/experimenter#6262]
It is now possible in Jetstream to have 2 different types of analysis for a single metric - `exposures` or `enrollments`.

For now, we will display only one of these but on the frontend there will be a label to show which type it is. If a metric has both types, the `exposures` type is prioritized to be shown.

In the [`statistics`](https://github.com/mozilla/experimenter/blob/main/app/experimenter/jetstream/client.py#L30) folder of the jetstream GCS bucket, a given [`JetstreamDataPoint` ](https://github.com/mozilla/experimenter/blob/main/app/experimenter/jetstream/models.py#L68) now additionally has an `analysis_basis` field. This will have the value of either `exposures` or `enrollments`. 

The [`metadata`](https://github.com/mozilla/experimenter/blob/main/app/experimenter/jetstream/client.py#L36) folder will also have an additional field per metric called `analysis_basis`. However, this will be an array that can contain either 1 or both of `exposures` and/or `enrollments`.

We need to send to the frontend the data for only one of the two types of `analysis_basis` and ignore the other, for now. We also need to send to the frontend the type it is so the label can be displayed.

One way this can be done is by:
1. After [fetching the metadata](https://github.com/mozilla/experimenter/blob/main/app/experimenter/jetstream/client.py#L34) file, iterate through the metrics and replace each `analysis_basis` list into a string to only contain either `exposures` or `enrollments` (instead of both).
2. When [iterating over all the jetstream data](https://github.com/mozilla/experimenter/blob/main/app/experimenter/jetstream/models.py#L174) to convert it to the API format, check the metadata to see whether the type for that metric is the same as the type in the `JetstreamDataPoint`. If they are different, ignore that `JetstreamDataPoint`.

Now only the data with the chosen `analysis_basis` will be sent to the frontend and the metadata info sent to the frontend will also contain which `analysis_basis` it is so it can be shown as a tag.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1660)

**Comment by jaredlockhart** [comment]
This is a helpful reference for the current state of the experimenter analysis API and what will need to change but in terms of future planning of work for segmentation and exposure we'll have to rethink it more cohesively when we have more data support so I'm going to close this since it's not exactly actionable as a current deliverable, but it's tagged for visualization so we'll be able to refer to it when we need to revisit this topic.
