### ISSUE TITLE
Results sidebar nav "breaks" if sections are closed

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6269]
Not sure if this is a bug, per se. 
Noticed on https://experimenter.services.mozilla.com/nimbus/multi-stage-onboarding-ask-and-show-to-pin/results, but if you close all the option sections (see screenshot below) then the sidebar nav items stop working since the target URL/anchor is now hidden (removed?).

![Multi-Stage_Onboarding_Ask_And_Show_To_Pin_–_Analysis___Experimenter](https://user-images.githubusercontent.com/557895/130280564-35a82381-8444-4e24-af6b-bb4c79e22b03.png)

Very much an edge case, and probably falls under "so don't do that" territory. Not sure if the answer to some of the visualization performance issues is to split them into 3-4 different pages to try and reduce the DOM elements.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1664)

**Comment by jaredlockhart** [comment]
We'll refile this if users start to hit it.
