### ISSUE TITLE
Team Categories filter

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6276]
As a user I want to be able to categorize my experiment so that I can find it easier later. 

* Add categories through multiselect filtering
* Let users add their own

Similar to this dropdown on Normandy: 

!image-20220526-223624.png|width=357,height=580!

Questions: 

* Are we pulling a base list of these categories from somewhere? Or are we just leaving it blank as users add their own?

We will be adding filter support in this ticket

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1672)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24347">image-20220526-223624.png</a>

**Comment by jaredlockhart** [comment]
We can reuse `Projects` to solve this all we gotta do is attach it to the API and show it in the UI.

**Comment by jaredlockhart** [comment]
Let's support the ability for users to enter their own labels right through the multiselect.

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

Let’s do the following.

Here we can do this the same way we did in legacy, so users can select ‘projects’ (or team if you wanna call it that) in a multiselect drop down somewhere in the forms, probably the overview page?  And then we can add a multiselect filter on the list page.  And projects can still be administered through the admin.  And then later if people really want the ability to create new projects themselves can build that later.

So let’s split this into a couple tickets:

  * Back end ticket
  * Overview Form ticket
  * Summary display ticket
  * List Page Filter ticket
