### ISSUE TITLE
Archived Draft experiments say "Request Launch" in summary area

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6285]
Archived Draft experiments say “Summary - Request Launch”. that “request launch” but is confusing. Doesn’t look like this is the case when i archive a Completed experiment on stage.

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1679)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/16088/FIRST_–_Summary__Request_Launch___Experimenter.png">FIRST_–_Summary__Request_Launch___Experimenter.png</a>

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

Oh yes totally I noticed that too 👍

**Comment by jaredlockhart** [comment]
We'll just leave this until it blocks someones workflow.
