### ISSUE TITLE
I want to be able to add a new JEXL targeting expressions and find/fix mistakes with less effort

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6291]
UJET folks (Andrei, Dan) had to land some new targeting expressions:

* No syntactic validation for JEXL expressions, so they landed something that wasn't valid
* Long lead time to go fix it, request review again

They would like to be able to add JEXL to the DB and have some validation to check if it's correct.

This also came up as a request from the Firefox Suggest team.

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1685)

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

For reference: https://github.com/mozilla/experimenter/pull/6271 ( https://github.com/mozilla/experimenter/pull/6271|smart-link ) 

Also, we definitely should not be requiring people to generate migrations for these PRs

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

Also the name here is misleading, you can add JEXL targeting.  I think what this is talking about is JEXL targeting validation?

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Updated for clarity, pain here is related to a) having to run the repo locally b) having to request review from a smaller group of reviewers c) errors not being caught by CI

**Comment by jaredlockhart** [comment]
So we're validating the JEXL expressions in CI now with both a JEXL interpreter in Python as well as through inside Firefox Desktop's JEXL evaluator to check both syntactic and semantic correctness.  Replicating this validation through the admin or through the Nimbus-UI would be very onerous and so we should only really approach it if it becomes critical.  Recent experiments have added custom audiences through the PR workflow without too much trouble so I'll close this and we can refile if it becomes a severe blocker.
