### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6294]
We have a Google Analytics deployed for experimenter but it's not part of the Moco account.  We should create a new Moco one using https://bugzilla.mozilla.org/enter_bug.cgi?product=Websites&component=Web%20Analytics and then update the IDs as env vars in stage/prod and then deprecate the old one.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1687)

**Comment by jaredlockhart** [comment]
Oh yep we're gonna have to do that.

**Comment by jaredlockhart** [comment]
We should just remove the google analytics altogether now that we have better monitoring from Sentry and we don't really use the audience capabilities of GA.
