### ISSUE TITLE
Redirect to summary page after archiving experiment

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6296]
# Steps to reproduce
1. [https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-2021-06-21-lang/edit/metrics](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-2021-06-21-lang/edit/metrics)
1. Click the "Archive Experiment" button to archive the experiment.
1. Click the "Save" button on the archived experiment.

# Actual results
After archiving and saving the experiment, you see error messages on the metrics page:

* "primary_outcomes can't be updated while an experiment is archived"
* "secondary_outcomes can't be updated while an experiment is archived"
[https://mozilla-hub.atlassian.net/browse/EXP-1682](https://mozilla-hub.atlassian.net/browse/EXP-1682)

If you're on one of the editing pages when you archive the experiment, I wonder if it'd be better to redirect to the summary page automatically when archiving an experiment.

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1689)

**Comment by jaredlockhart** [comment]
This is done.
