### ISSUE TITLE
The "descending" sorting filter cannot be removed once applied to a category if the "tab=" parameter is missing from the address bar

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/experimenter#6314]
*[Steps to reproduce]:*
1. Open the Nimbus main page without clicking on any of the tabs (e.g. Live, Review, Preview, Completed, Draft, Archived)
2. Click on one of the categories to sort by it twice.
3. Click on the same category a third time.

*[Expected result]:*
- The "descending" sorting filter is removed.

*[Actual result]:*
- The "descending" sorting filter is removed and then reapplied instantly.

*[Notes]:*
- The issue is not reproducible if one of the tabs is opened first and the "tab=" parameter is added. (e.g. tab=live)
- Attached a screen recording of the issue:

![descending_not_removed](https://user-images.githubusercontent.com/40393891/130963631-7c524fe0-68a8-4da9-ac08-b68fb6ba538c.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1697)

**Comment by lmorchard** [comment]
Ohh, I see what's happening here: Resetting the sort order in this scenario should result in an empty query string. However, when the query string is empty, we "restore" a value stored in the app context (i.e. the last sort order)

We retain the last query string to restore state on returning from clicking on an experiment. It only gets restored if the query string is empty. But, I don't think we clear the stored query string when the query string is **intentionally set** to empty. That's probably the bugfix here.

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible. The "descending" filter can be applied and removed from all sections without any issues, tested using Firefox Nightly 94.0a1 (Build ID: 20210924094613).
