### ISSUE TITLE
Add tool tip to clone UI to explain slug cannot be updated afterwards

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6319]
Per Figma spec

!Nimbus_Console_UI_–_Figma.png|thumbnail!

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1701)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/16158/Nimbus_Console_UI_–_Figma.png">Nimbus_Console_UI_–_Figma.png</a>

**Comment by jaredlockhart** [comment]
I don't think it needs to be a tooltip it can just be a helptext below the slug field.
