### ISSUE TITLE
Add link to cloned experiment's parent in sidebar

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6320]
Per Figma spec

!Nimbus_Console_UI_–_Figma.png|thumbnail!

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1702)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/16159/Nimbus_Console_UI_–_Figma.png">Nimbus_Console_UI_–_Figma.png</a>

**Comment by jaredlockhart** [comment]
Closing as duplicate of https://github.com/mozilla/experimenter/issues/5796
