### ISSUE TITLE
Sort versions from high to low on Version dropdown on Nimbus homepage

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6332]
https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/?tab=archived&firefoxMinVersion=FIREFOX_16

Not sure if it's better to have consistent and predictable numbering from Firefox 11-100, or gaps in numbering but fewer instances of "No experiments found."

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1706)

**Comment by jaredlockhart** [comment]
Yeah we can probably remove everything below....90?

**Comment by pdehaan** [comment]
... Unless old experiments use the old version numbers? Unless the previously selected version number is archived in the data for completed/archived experiments.

**Comment by eliserichards** [comment]
I'd recommend keeping the old values but re-sorting it so the newest version numbers are at the top

**Comment by yashikakhurana** [comment]
closing this as done in https://github.com/mozilla/experimenter/pull/8127
