### ISSUE TITLE
Enrollment duration for complete experiment uses proposed duration

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6338]
Just noticed a complete experiment is showing the wrong enrollment duration, it's using proposed instead of computed:

<img width="1161" alt="Screen Shot 2021-09-01 at 3 59 14 PM" src="https://user-images.githubusercontent.com/119884/131736030-157b35eb-566f-4f84-b824-c09b61869c2a.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1709)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Thinking this is because the experiment was ended before enrollment was ended - and our model logic yields proposed duration unless enrollment was ended. But, that logic should probably consider experiment end also.
