### ISSUE TITLE
As a data scientist, I want to look up which probes are relevant to the experiment

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6342]
Some suggestions from Su

* Being able to look up exact feature variable values in Nimbus is really helpful 
* He'd like to be able to see which probes are relevant to the feature, as well as implementation details of the exposure event.

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1711)

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

One thing we could do is have folks add probes to the feature manifest, as well as a “exposureDescription” required field that would describe what the meaning of the exposure event is.

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Su-Young Hong We decided to go ahead with requiring a description of the meaning/implementation of the exposure event for each feature, which we will eventually display in the Experimenter UI (implementation tracked in EXP-1722)

**Comment by jaredlockhart** [comment]
We will address this here https://mozilla-hub.atlassian.net/browse/EXP-2151
