### ISSUE TITLE
Have a "copy preview" button on each branch for experiments in Preview mode

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6346]
For experiments in a preview state, it would be nice to have a button next to each branch name that would let you copy the right preview link

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1714)

**Comment by jaredlockhart** [comment]
I think there's probably a bunch of things we can do to improve the testing/QA workflow but I'd rather do it as a larger body of work when we can dedicate more time and thought to it.  There's a dropdown now to get the branch test URL so the workflow isn't critically blocked, and it's not clear where the strongest pain points for testing are now and where we should focus our attention.
