### ISSUE TITLE
Should the clone experiment modal display the Application (as well as name/slug)?

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6350]
When cloning an experiment, you can change the public name, and there is a read-only copy of the slug (based on the current name).
But you can't see or change or change the Application type.

Even a read-only version of the to-be-cloned Application with the same caveats might be nice:
> Experiments can only target one Application at a time.
> Application can not be changed after an experiment is created.

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1717)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/16245/a_–_Overview___Experimenter.png">a_–_Overview___Experimenter.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/16246/a_–_Overview___Experimenter.png">a_–_Overview___Experimenter.png</a>

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

This also means that you can’t clone a Fenix experiment and create a Focus/Klar experiment. Or clone a Fenix experiment and reuse all the same parameters/branches for an iOS experiment. That’s a slightly different concern probably best put in a new issue for discussion, but I think it would be a common use case.

**Comment by jaredlockhart** [comment]
Yeah a very good point about retargeting mobile applications, that might become an important workflow.  We may very well have to do this but let's wait to see if we get any requests for it from users before we prioritize it.  Good catch 👍

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Even if we choose not to let people retarget, I think we should consider displaying the application+notice in the clone dialog.

Sorry, I should have filed the comment as a separate ticket so we could track/discuss separately.

**Comment by jaredlockhart** [comment]
Actually we can't clone across applications becuase the features are different so there's no way to manage that, and adding a special case to check for it and remove them would be complicated, I'll wait until cross mobile cloning becomes more importanta and revisit this.
