### ISSUE TITLE
Allow positive windows in Segments [Jetstream]

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6351]
When defining a custom Segment, Jetstream currently only allows non-positive values for `window_start` and `window_end` (see https://mozilla.github.io/mozanalysis/api/segments.html#mozanalysis.segments.SegmentDataSource) 

We should allow positive values for `window_start` and `window_end`. Here are some use cases:

* Clients assigned to a "treatment branch" must still manually opt-in to actually receive the treatment. In order to segment to the clients that opted in, we would need positive values for window_start and window_end because the manual opt-in happens after enrolling in the Nimbus experiment.
* We want to segment to clients / users who performed a certain action during the experiment, and this action has no causal impact on the experiment's metrics. For example, for the Firefox Suggest experiments, we would like to segment just to users who used the urlbar during the course of the experiment. This has no causal impact on metrics (and does not bias the segment assignment) because using the urlbar happens **before** a Firefox Suggest is shown.

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1718)

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Anna Scholtz Is this something you’re able to pick up?

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Also thank you for the feedback Rebecca BurWei ! 🎉

**Comment by data-sync-user** [comment]
➤ Anna Scholtz commented:

I can look into it

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Thanks Anna Scholtz !

**Comment by data-sync-user** [comment]
➤ Rebecca BurWei commented:

The first use case applies to the Firefox Suggest Online experiment going out on Sept 30, so it would be useful to have this feature available by Oct 11.

**Comment by scholtzan** [comment]
That should be doable. I think I'll have time to work on this in about 2 weeks from now

**Comment by data-sync-user** [comment]
➤ Rebecca BurWei commented:

Thanks Anna Scholtz !

**Comment by data-sync-user** [comment]
➤ Anna Scholtz commented:

Fixed in https://github.com/mozilla/mozanalysis/pull/142 ( https://github.com/mozilla/mozanalysis/pull/142|smart-link )
