### ISSUE TITLE
Experiments no longer reach the nimbus-preview or nimbus-desktop-experiments collections in RS

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#6357]
**[Prerequisites]:**
- Have a Desktop experiment in the `Draft` state.
- Have LDAP access.

**[Steps to reproduce]:**
1. Navigate to the Nimbus experiment page from prerequisites.
2. Launch the experiment to Preview.
3. Navigate to https://settings-writer.stage.mozaws.net/v1/admin/#/buckets/main/collections/nimbus-preview/records and observe the most recent entry.

**[Expected result]:**
- The experiment from prerequisites is displayed in the list.

**[Actual result]:**
- The experiment is not found in the list.

**[Notes]:**
- The issue might also be happening in PROD.
- The issue is also reproducible with Normandy, which leads me to believe that this is a RS related issue.
- The issue is also reproducible when approving a launch of an experiment. But in this case, the experiment remains stuck in the waiting for approval state and it doesn't get automatically rejected after 15 mins.
- Sentry also sent the following KintoExeptions:
  - https://sentry.prod.mozaws.net/operations/experimenter-stage/issues/12842315/?referrer=alert_email
  -  https://sentry.prod.mozaws.net/operations/experimenter-stage/issues/12855348/?referrer=alert_email
  - https://sentry.prod.mozaws.net/operations/experimenter-stage/issues/12855384/?referrer=alert_email
- Attached is a screen recording of the issue:
![recipes can't be pushed to the RS collection](https://user-images.githubusercontent.com/18304511/131974298-b0695c89-e3a0-4941-9560-9f38022eaf9a.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1719)

**Comment by data-sync-user** [comment]
➤ Ciprian Muresan commented:

Looks like there’s a signing issue on the Stage server, it’s currently tracked here - https://bugzilla.mozilla.org/show_bug.cgi?id=1728857 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1728857|smart-link ). Luckily it seems the cert has not yet expired on Prod.

**Comment by SoftVision-CiprianMuresan** [comment]
I have verified that the issue is no longer reproducible now that [Bug 1728857](https://bugzilla.mozilla.org/show_bug.cgi?id=1728857) was resolved. I've successfully sent and removed experiments to/from the nimbus-preview and nimbus-desktop-experiments collections.
