### ISSUE TITLE
How can we help DS discover/understand the implementation details of relevant probes for each Nimbus feature?

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6358]
It would be nice to have documentation / a better way to figure out which Telemetry is relevant to each Nimbus feature, but we should do some investigation into how this relates to Glean annotations.

┆Issue is synchronized with this [Jira Spike](https://mozilla-hub.atlassian.net/browse/EXP-1723)

**Comment by jaredlockhart** [comment]
This is a good question but we'll have to review the analysis architecture in a broader sense when we get some new data folks and this can be part of that discussion but I don't think is an actionable ticket atm.
