### ISSUE TITLE
QA for Desktop multifeature implementation

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6359]
**Given the following API format** (note: this is not implemented in Experimenter yet):

```json
{
  featureIds: ["foo", "bar"],
  branches: [{
    slug: "control",
    ratio: 1
    features: [
      {featureId: "foo", value: {enabled: true}},
      {featureId: "bar", value: {hello: "world""}}
    }
  }]
}
```

* Desktop clients should enroll in experiments that target one or more features.
* No two experiments should be enrolled at the same time that have intersecting featureId arrays
* Experiments with the existing single-feature format should still enroll correctly
* Experiments with the existing single-feature format that were already enrolled in 92 before Firefox upgrades to 93 should:
  * be returned from the Feature API correctly
  * send the correct telemetry events
  * show up about:studies correctly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1724)

**Comment by data-sync-user** [comment]
➤ Maria Heres commented:

Peter deHaan Victor Andrei Oprea Jared Kerim We have some tests prepared for multifeature in our Nimbus Test Suite ( https://testrail.stage.mozaws.net/index.php?/suites/view/16163&group_by=cases:section_id&group_order=asc&group_id=227737 ) - The “WIP  Multifeature” folder. We were thinking on adding the desktop tests from our Functionality folder to our weekly test run this week. The idea would be to create some recipes with common features in RS Stage and check whether we can enroll in them at the same time or not.

**Comment by data-sync-user** [comment]
➤ Maria Heres commented:

We ended up not including the multifeature functionality tests this week.

**Comment by data-sync-user** [comment]
➤ Maria Heres commented:

We included the desktop client side tests in our full run in week 11.08 - 11.11. We found no issues related to the feature. The testing report can be found here ( https://docs.google.com/document/d/1FCQlOeTf3xFPofr_iVDy5W0xXI1M4p6OgbftyBo-VbI/edit?usp=sharing ).

**Comment by data-sync-user** [comment]
➤ Maria Heres commented:

We tested the change introduced by https://mozilla-hub.atlassian.net/browse/EXP-1841 ( https://mozilla-hub.atlassian.net/browse/EXP-1841|smart-link ) using experiments created in various states before the change was introduced. You can find the scenarios tested here ( https://docs.google.com/spreadsheets/d/1YHGBp3yFiUZaP78vOorkJ9DB5BOzw2m8jGcE_-5fKkA/edit#gid=0 ). We have found no issues related to this change.

**Comment by data-sync-user** [comment]
➤ Maria Heres commented:

We will perform an additional round of testing for the multifeature schema change in +#185+ ( https://github.com/mozilla/nimbus-shared/pull/185/ ) based on the +provided testing recipes+ ( https://github.com/mozilla/nimbus-shared/pull/185/files ), as requested.  We will perform both desktop and mobile testing.  

Jared Lockhart Kate Hudson James Hugman could you please take a look at the testing recipes we have been provided to make sure we are using correct test data? There are some comments on the recipes that also need to be addressed before we continue testing. 

Our plan is to verify the scenarios found +here in Gdoc form+ ( https://docs.google.com/spreadsheets/d/1Hip_O276Ajt97ocfFN3PhDCDD-kEQ_UUh5JQzhkVORo/edit?usp=sharing ) for the example recipes. 

We plan to test them on Firefox Release 95 on Windows 10, macOS 11.6 and Linux (Mint 20.1 or Ubuntu 20.04) for desktop.

We plan to test them on Firefox for Android Beta 96 on Android 9 or 10 and Fennec built from the latest changes of the v39.0 branch of Firefox for iOS on the latest available iOS version of the Xcode Simulator.

**Comment by data-sync-user** [comment]
➤ Maria Heres commented:

We have finished testing the multifeature client side scenarios. You can find the reports here  ( https://github.com/mozilla/nimbus-shared/issues/182#issuecomment-984734607 )and here ( https://github.com/mozilla/nimbus-shared/issues/182#issuecomment-992646578 ).

**Comment by jaredlockhart** [comment]
Soon!
