### ISSUE TITLE
QA for Branch Screenshots

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6379]
- Create a new experiment.
	- While in draft mode, I can upload 1 (or more) screenshots per *branch*.
	- Each screenshot can be deleted.
	- Screenshots are visible on the Summary page once the experiment has all the required fields populated.
- Create an experiment and add a few screenshots to a branch.
	- Clone the experiment and confirm that the cloned experiment includes the same images.
	- Delete a screenshot from the cloned experiment and confirm that the same screenshot isn't deleted from the parent experiment (make sure the images are copied, not a reference to images).
- Create an experiment and add a few screenshots to a branch.
	- Copy the path to the branch screenshot and open the image in a new tab.
	- Delete the screenshot from the branch.
	- Refresh the new tab created earlier with a link to the image. Verify if the image still resolves correctly. (if so, images are likely being orphaned in GCP).
- Create an experiment w/ multiple branches (and 1+ screenshots per branch)
	- On the summary page, scroll down to the Branches section and click "Promote to Rollout". Confirm that the new rollout copies over the branch images for that single branch rollout.
- Create an experiment and add multiple screenshots to a branch.
	- Delete each screenshot from the branch and confirm nothing "funny looking" happens.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1735)

**Comment by pdehaan** [comment]
Possibly other stuff around
- uploading multiple images at same time?
- can we upload via drag and drop?
- size limitations on images?
- verify that it works for JPEG, PNG, [animated] GIF. (Not sure if TIFF and BMP are supported -- they're horribly inefficient, but probably not a technical reason it _wouldn't_ work.)
- Upload some images w/ various dimensions (portrait, landscape, large screenshots from mobile/desktop) and verify that things look "correct" and not unbalanced. I'm not sure if the images will have thumbnails or just be inlined.

**Comment by data-sync-user** [comment]
➤ Maria Heres commented:

Jared Lockhart Les Orchard Peter deHaan Last week we ran the test cases we prepared for this feature. You can find them here in spreadsheet form  ( https://docs.google.com/spreadsheets/d/1ht0yGUlBirmMKMOfH_1-06TqxHFNR2dQz7W0jXCUkxo/edit?usp=sharing )or in our TestRail test suite ( https://testrail.stage.mozaws.net/index.php?/suites/view/16163 ) in the “Firefox Desktop” > “Experiment Page” > “Branches” > “Screenshot specific” folder. Could you please review them to make sure we included all the important scenarios?
