### ISSUE TITLE
An experimenter email is displayed as the author of a Remote Settings rejection performed with an ldap account

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6385]
**[Prerequisites]:**
- Have a live Nimbus experiment with enrollment still active open.
- Have someone else have the experiment page open.

**[Steps to reproduce]:**
1. Have someone click the "End Enrollment for Experiment" button and confirm the choice.
3. Click the “Approve and End Experiment” button.
4. Click “Open Remote Settings” and sign in using ldap.
5. Reject the change with a comment.
6. Go back to the experiment page and observe the email of the commenter.

**[Expected result]:**
- The email of the person signed into the admin page is displayed as having rejected the change.

**[Actual result]:**
- The “experimenter@experimenter.services.mozilla.com” email is displayed as having rejected the change.

**[Notes]:**
- Attached is a screenshot of the issue.
![image](https://user-images.githubusercontent.com/53752296/132546005-d506a3fa-0b64-4726-978e-172b7fba1bf1.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1739)

**Comment by jaredlockhart** [comment]
Yes that is true.  Pulling history/metadata out of remote-settings is tricky, there's a couple things wrong with the way the rejections are handled, but they don't critically block the workflow atm so until we can work more closely with the remote settings team to get some API changes we'll just have to make do with this for now.
