### ISSUE TITLE
[Enhancement] Consider having one Show/Hide Weekly Data button affect both the Relative and Absolute tabs

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6391]
**[Prerequisites]:**
- Have a completed Nimbus experiment with Results open (e.g. https://experimenter.services.mozilla.com/nimbus/message-homepage-remediation-v2-search-value-props-exper-release-83/results).

**[Steps to reproduce]:**
1. Click the “Show Weekly Data” button from the “Relative uplift comparison” tab.
2. Click the “Absolute comparison” button.
3. Observe the behavior of the table and button.

**[Proposed result]:**
- The “Show Weekly Data” button seems like it would be more useful outside the two tabs, with the tabs and their tables being shown/hidden both based on clicking on the one button.

**[Current result]:**
- There are two buttons for each tab. They show/hide the individual tables, each one for its own tab. It feels like there are too many clicks required for each.

**[Notes]:**
- Attached is a recording of the current behavior.
![visualization weekly data](https://user-images.githubusercontent.com/53752296/132652580-c8ffb8a0-ff7d-4243-86c7-46e63b18a54c.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1741)

**Comment by jaredlockhart** [comment]
Definitely nice to have but closing for now until we have more support for data visualization.
