### ISSUE TITLE
[Enhancement] Consider having the link to a clone’s parent automatically open in a new tab

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6395]
**[Prerequisites]:**
- Have a clone of another experiment open.

**[Steps to reproduce]:**
1. Click the name of the parent experiment from “Cloned from <parent_name_link>”.
2. Observe the behavior.

**[Proposed result]:**
- On left-click on the parent’s name, the page could open in a new tab. The other links on experiment pages seem to all open in new tabs. I think it would also be more convenient for users to have it open in a new tab instead of having to confirm they want to leave the page when asked by the prompt that is displayed if you have unsaved changes.

**[Current result]:**
- The link opens in the same tab. 

**[Notes]:**
- Attached is a recording of the current behavior.

![open in new tab](https://user-images.githubusercontent.com/53752296/132704669-e7f9cb5a-18c9-454f-a2e4-5f49f3ecb7f4.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1745)

**Comment by SoftVision-CiprianMuresan** [comment]
I have verified that clicking a cloned experiment's parent link will open a new tab with the parent experiment.
