### ISSUE TITLE
Adding dot release to Nimbus comparator for the Suggest experiment

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#6400]
When @mythmon knows the exact version string of the dot release - ping @jaredlockhart to add the exact version string to the version list as a code change.  

This will mean when the Jexl string firefox version comparator does the comparison - it can validate and do only the dot release.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1749)

**Comment by mythmon** [comment]
@jaredlockhart This will be Firefox version 92.0.1.

**Comment by shell1** [comment]
@jaredlockhart QA is hopefully starting final beta testing on 93 Monday morning.  Once it passes - the dot release for 92 will go out.

Should we consider testing options?  Like testing on Beta version?  Beta 7 is the version that will have the fixes - if adding that version to Nimbus makes sense - just for testing targeting by a specific "version"

**Comment by jaredlockhart** [comment]
@shell1 That's a good question but I'm going on PTO until the 27th so I'll have to refer you to my esteemed colleague @k88hudson to answer that
