### ISSUE TITLE
Ending enrollment with request and review seems unnecessarily complicated

### ISSUE THREAD

**Issue by Mardak** [mozilla/experimenter#6402]
#5742 / #5852 added manual enrollment ending review flow, and I believe one of the primary issues is that it used to be automatic ending, which had at least a couple problems:
- enrollment might actually want to be extended from what originally was scheduled
- automatic remote settings change still requires manual remote settings review/approval, which blocks other remote settings changes

Currently a reviewer needs to find someone else to initiate the request button so that the reviewer can approve. Maybe a special case of review access can bypass or at least self-review (allowing for rejecting accidental end)? Unclear if this change should also apply for ending an experiment, but the current flow is definitely appropriate for launching.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1750)

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Thanks for filing Ed Lee !  In the future please use the ‘Feedback’ link https://bit.ly/38dgkqR ( https://bit.ly/38dgkqR )  rather than filing it in github so that it sets all the Jira fields correctly 🙏

**Comment by jaredlockhart** [comment]
In the future the 'updating a live experiment' workflow will change to include more possible updates and we can revisit how the 'end enrollment' workflow fits into that.  In the mean time I will close this.
