### ISSUE TITLE
Live Monitoring is displayed for Completed Nimbus experiments which have full Results

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6404]
**[Notes]:** 
- Expected behavior is based on the old Experimenter. [This page](https://experimenter.services.mozilla.com/experiments/delegated-credentials-nightly-breakage-study/) has Results and does not display Monitoring, while [this one](https://experimenter.services.mozilla.com/experiments/activity-stream-pktnewtabh22019-69-story-card-test/) does not have Results and displays Monitoring.

**[Prerequisites]:**
- Have a completed experiment which has results displayed open (e.g. https://experimenter.services.mozilla.com/nimbus/homepage-remediation-exposure-nightly-test)

**[Steps to reproduce]:**
1. Open Summary and observe “Monitoring”.
2. Open Results and observe the “Live Monitoring Dashboard” link.

**[Expected result]:**
- Complete experiments which have full Results displayed do **not** link to Live Monitoring.

**[Actual result]:**
- Complete experiments which have full Results displayed link to Live Monitoring on both the Summary and Results sections.

**[Additional Notes]:**
- Attached is a screen recording of the issue and screenshots of the Experimenter behavior.
![monitoring with Results](https://user-images.githubusercontent.com/53752296/132833087-d3a5cf8e-2a6d-4541-9674-e2a3acb6cc4e.gif)
![no results yes monitoring](https://user-images.githubusercontent.com/53752296/132833146-11e08186-bb79-4b69-ba44-31a5a01a4fc8.png)
![yes results no monitoring](https://user-images.githubusercontent.com/53752296/132833158-4877c6bb-14d2-4968-b191-e78621034583.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1751)

**Comment by jaredlockhart** [comment]
Legacy is no longer maintained.

**Comment by heres-maria** [comment]
@jaredlockhart This report refers to the Nimbus console. The Legacy Experimenter pages are used as the basis for the expected behavior. For Nimbus, would this be a valid issue? Should this issue be reopened?
