### ISSUE TITLE
Clicking on one of the subsections of Results in the navigation sidebar while on Summary opens just Results

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6405]
**[Prerequisites]:**
- Have an experiment with Results available open on Summary.

**[Steps to reproduce]:**
1. Click on “Results Summary” from the navigation sidebar.
2. Observe the behavior.

**[Expected result]:**
- The Results page opens focused on the “Results Summary” section.

**[Actual result]:**
- The Results page opens without being focused on any section. 
- The user has to click again on “Results Summary” to navigate to that section.

**[Notes]:**
- The issue is applicable for all subsections of Results in the navigation sidebar.
- Attached is a screen recording of the issue.
![click twice on Results](https://user-images.githubusercontent.com/53752296/132845900-623e92e9-74a8-4e4a-9e79-b34e565dfcf7.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1752)

**Comment by jaredlockhart** [comment]
Yeah we've had ongoing hiccups with the 'scroll to anchor' logic on these pages but it's not urgently workflow breaking so I'm going to close this.
