### ISSUE TITLE
Some Result Outcomes are displayed as empty sections for Nimbus experiments with incomplete Results

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6406]
**[Prerequisites]:**
- Have a Live experiment with partial results open (e.g. https://experimenter.services.mozilla.com/nimbus/firefox-suggest-history-vs-offline/results#results_summary).

**[Steps to reproduce]:**
1. Click on “Results” from the navigation sidebar.
2. Attempt to click on “Primary Outcomes”.
3. Scroll down to the bottom of the page.

**[Expected result]:**
- Results sections with no data(?) are not displayed in either Results or the navigation sidebar.

**[Actual result]:**
- Results sections with no data(?) are displayed in Results and the navigation sidebar, where they are unclickable.

**[Notes]:**
- Attached is a screen recording of the issue.

![empty results](https://user-images.githubusercontent.com/53752296/132863572-699fd047-527d-45d5-8e85-d922ed236c9f.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1753)

**Comment by jaredlockhart** [comment]
I'm going to close this until we have more support from data tooling and we can revisit the analysis pages more cohesively.
