### ISSUE TITLE
Determine access control policy for search experiments 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6443]
Given that Search is revenue impacting and involves contractual obligations / compliance, we should assess the feature itself and whether Nimbus’s access control policy is sufficient for our needs here.

* **The integration itself:** How much scope should Nimbus have to control search configurations within experiments/rollouts ?
  * Primary risks here are more on the contract/compliance side.
* **Permissions:** Is our existing [Nimbus Access Control Policy](https://docs.google.com/document/d/1r8oI_Hxe5JQcOejqZcSziX1Aso20AFGBToTFu3BE5j8/edit) sufficient/appropriate for Search experiments?
  * Currently, we allow any LDAP user (i.e. onboarded experiment owners) to create/request launch, and any **L3** reviewer ([https://mana.mozilla.org/wiki/display/FJT/Nimbus+Reviewers](https://mana.mozilla.org/wiki/display/FJT/Nimbus+Reviewers)) to approve. We don’t make a distinction between specific feature owners.

See slack conversation: 

[https://mozilla.slack.com/archives/CFLFWM98V/p1631804257038400](https://mozilla.slack.com/archives/CFLFWM98V/p1631804257038400|smart-card)

┆Issue is synchronized with this [Jira Spike](https://mozilla-hub.atlassian.net/browse/EXP-1779)

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

1. There is a proposal for a full suite of access control capabilities that has not yet been scoped/planned for implementation and would be costly and time consuming to implement in its entirety https://docs.google.com/document/d/1r8oI_Hxe5JQcOejqZcSziX1Aso20AFGBToTFu3BE5j8/edit?usp=sharing ( https://docs.google.com/document/d/1r8oI_Hxe5JQcOejqZcSziX1Aso20AFGBToTFu3BE5j8/edit?usp=sharing|smart-link ) 
  2. There are very simple and easy things we could do to implement a very basic form of access control within Experimenter using the Django Permissions framework if we wanted to do something quickly to restrict access just to a given feature (ie Search) that would require minimal scoping/planning/implementation

**Comment by jaredlockhart** [comment]
Closing this as completed investigation until we have new requirements or planning.
