### ISSUE TITLE
A Completed experiment has a warning on its Results page that it is incomplete

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6448]
**[Prerequisites]:**
- Have this experiment open: https://experimenter.services.mozilla.com/nimbus/firefox-vpn-test-1629

**[Steps to reproduce]:**
1. Click the “Results” option from the navigation sidebar.
2. Observe the message displayed in "Results Summary”.

**[Expected result]:**
- Completed experiments do not have experiment is not complete warnings.

**[Actual result]:**
- The experiment has a “WARNING: Experiment is not complete. Do not end the experiment early based on these results without consulting a Data Scientist.” warning displayed.

**[Notes]:**
- The experiment also displays  issue #6406.
- Attached is a screenshot of the issue.
![image](https://user-images.githubusercontent.com/53752296/133819093-c1328ec2-5e2f-4d4a-b410-26b6c667bd2e.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1783)

**Comment by jaredlockhart** [comment]
Yes that is true this will happen if it fails to load the jetstream data, which is covered by https://github.com/mozilla/experimenter/issues/7067 so closing this as a duplicate.
