### ISSUE TITLE
The links from Overview and the Locales and Countries filters from Audience are deleted when the Branches section is saved

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6468]
**[Prerequisites]:**
- Have a draft of a Nimbus experiment open on Overview.

**[Steps to reproduce]:**
1. Save a few links in the “Additional Links” section.
2. Go to the “Audience” section.
3. Save options in the “Locales” and “Countries” fields.
4. Go to the “Branches” section.
5. Click “Save”.
6. Go to “Summary” and observe the “Additional links”,  “Locales” and “Countries” sections.

**[Expected result]:**
- Saved links, country and locale filters remain saved.

**[Actual result]:**
- Saved links, country and locale filters are deleted when the “Branches” section is saved.

**[Notes]:**
- The data is deleted from the “Audience” and “Overview” sections as well, not just Summary.
- The data does not seem to be deleted when other sections are saved.
- Whether the "Save" or "Save and Continue" buttons are used does not affect the result.
- Attached is a screen recording of the issue.

![deleted data](https://user-images.githubusercontent.com/53752296/134321367-0223d566-6ebe-4c15-b939-1d6b2e7a172a.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1788)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I can reproduce locally. Not sure what the cause is, but I will dig into this today.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Did a git bisect and it looks like the issue was introduced in PR 6444 with changes to branch updated to begin supporting screenshots.

https://github.com/mozilla/experimenter/commit/dfad7ffdfe479706b9979adfab3f874afebba8d6 ( https://github.com/mozilla/experimenter/commit/dfad7ffdfe479706b9979adfab3f874afebba8d6|smart-link ) 

Still not sure how this update is causing the issue, continuing to dig.

**Comment by lmorchard** [comment]
I think I worked out the culprit with a fix in PR #6470: We have the foreign key `reference_branch` on experiments set to [`on_delete=models.CASCADE`](https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.CASCADE) - which means that deleting the reference branch deletes the parent experiment. Then, we re-create the experiment with *almost* all the same properties - except without the associations to links, locales, and countries.

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible. Saving the Branches section no longer deletes the Additional Links, Locales or Countries filters. Tested using Firefox Nightly 94.0a1 (Build ID: 20210921190609).
