### ISSUE TITLE
Some Absolute Count values are displayed as 0.00 while their Relative Improvement shows very large changes

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6474]
**[Prerequisites]:**
- Have an experiment like this open on Results: https://experimenter.services.mozilla.com/nimbus/android-keystore-reliability-experiment-v2/results

**[Steps to reproduce]:**
1. Observe a metric like “Abnormal get_result”.

**[Expected result]:**
- The “Absolute Count” values correlate with the “Relative Improvement” changes.

**[Actual result]:**
- The “Absolute Count” values are 0.00 while “Relative Improvement” shows changes, some significant.

**[Notes]:**
- Clicking “Show Graphs” for the metric used as an example shows values smaller than 0.01. 
- The baseline also seems to be different from 0 on the graphs.
- The issue is reproducible for multiple probes.
- Attached is a screenshot of the issue.
![image](https://user-images.githubusercontent.com/53752296/134640407-059066a8-70ee-4970-a2fb-c886c00a7eb0.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1791)

**Comment by jaredlockhart** [comment]
Yep that is true and an unfortunate side effect of the Math™️.  There might be something we can do to make it less awkward looking from a design perspective but until we have more support I'll just close this.
