### ISSUE TITLE
Updating and re-publishing to preview fails 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6488]
Use case was that the configuration for a feature id was wrong in the DB.

After updating the feature id, we re-saved the experiment, removed it from the preview collection and put it back in. We had some trouble with that, publishing maybe got into a weird state? 

Also, we had trouble getting the updated version in Firefox - possibly due to remote settings not updating?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1797)

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Yeah, definitely seems to be related to remote settings not being updated

**Comment by leplatrem** [comment]
The URL change for stage should not affect this part.
We only refined the public URLs (CDN vs Origin).

Is the STAGE server still in a weird state?

**Comment by heres-maria** [comment]
I retested updating a Nimbus experiment and republishing it to Stage Preview. The experiment did update after a while, I think I might have not waited enough last time.

**Comment by lmorchard** [comment]
Is this still an issue? If so, could use some more details / steps to reproduce:

> After updating the feature id, we re-saved the experiment, removed it from the preview collection and put it back in. We had some trouble with that, publishing maybe got into a weird state?

* Which experiment was this?
  * Would help to see the Nimbus changelog entries and Remote Settings activity
* How was the feature ID updated? 
  * And with respect to Nimbus, this is the feature config *slug* right?
* How was the experiment re-saved?
  * If an experiment is in the preview collection, it *should* be read-only with respect to the Experimenter front-end.
  * Was it removed from preview *before* re-saving? Or was something else done, e.g. editing from the Django admin?
* How was the experiment removed from the collection and put back in?
  * That is, was it done directly on remote settings? Or via the Experimenter front end UI?
* When you say "We had some trouble with that" - what exactly was the trouble?

Trying to think through what possible weird states could happen in this flow, so details would help.

**Comment by jaredlockhart** [comment]
Closing this as not reproducible and we can refile if we see it again.
