### ISSUE TITLE
Clear media folder out during make refresh

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6492]
I just noticed that my local `/media` folder has thousands of folders/images from test runs.  We should switch the unit tests to only use the in memory storage provider so nothing persists between test runs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1798)

**Comment by jaredlockhart** [comment]
I think `make refresh` is also dumping files in there from the factories.  Not sure what we should do about that.  Ideally we're not litering that folder with junk data.  Possibly adding a directive to the Makefile that clears that folder out during `make refresh` would be the right thing?  So tests are in memory only, local dev uses the real filesystem, and `make refresh` clears it out?

**Comment by lmorchard** [comment]
The *tests* should be using in-memory storage already - that's what [`settings_test.py`](https://github.com/mozilla/experimenter/blob/main/app/experimenter/settings_test.py) should be doing. If you delete `/media` and do a `pytest` run, is it still filling up with images?

I think the main thing is `make refresh` and the factories.

**Comment by jaredlockhart** [comment]
Oh good point, let me check.

**Comment by jaredlockhart** [comment]
Yep you're right, it's `make refresh` not the tests so we just need to add a directive to clear that folder out when we run `make refresh`
