### ISSUE TITLE
Move FeatureManifest schema from MC to nimbus-shared

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6573]
Let's move the FeatureManifest schema from MC to nimbus-shared and then we can use it to validate feature manifest files in all repos across desktop/mobile.

https://searchfox.org/mozilla-central/source/toolkit/components/nimbus/schemas/ExperimentFeatureManifest.schema.json

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1832)

**Comment by jaredlockhart** [comment]
We should do this 👍
