### ISSUE TITLE
Saving branches, metrics pages do not highlight fields in green

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6584]
The overview and audience pages highlight all the fields in the green border and checkmark after saving to show that they were validated and saved, but the branches and metrics pages do not.  We should fix that so all pages show the valid fields as green when saving, it's just a nice UI signal that your stuff was saved properly.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1839)

**Comment by jaredlockhart** [comment]
@dbelokon Oh I'm sorry I missed this!  No you don't need Jira to work on it, feel free to pick anything labeled 'Good First Bug' up and get started on it and follow the PR process to submit a PR 🙏 https://github.com/mozilla/experimenter/blob/main/contributing.md#pull-request-process

**Comment by eliserichards** [comment]
I broke this out into two separate issues. Closing this.
