### ISSUE TITLE
A GraphQL Apollo Error error is displayed when accessing multiple experiment pages

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6617]
**[Steps to reproduce]:**
1. Go to this page https://experimenter.services.mozilla.com/nimbus/default-browser-winning-branch-extended-holdback-study-beta
2. Observe the page displayed.

**[Expected result]:**
- The page is correctly loaded and displayed.

**[Actual result]:**
- The page displays a GraphQL Apollo Error 
Message: Expecting value: line 1 column 1 (char 0) 
graphQL error: Expecting value: line 1 column 1 (char 0)

**[Notes]:**
- The issue is reproducible for multiple experiments of different statuses.
- Other experiments where the issue is reproducible (not exhaustive):
 https://experimenter.services.mozilla.com/nimbus/emotive-pin-firefox-modal
https://experimenter.services.mozilla.com/nimbus/mr2-upgrade-spotlight-holdback
https://experimenter.services.mozilla.com/nimbus/captive-portal-vpn-info-experiment
https://experimenter.services.mozilla.com/nimbus/default-browser-winning-branch-extended-holdback-study-release
https://experimenter.services.mozilla.com/nimbus/user-messaging-set-default-trackers-blocked-notification
https://experimenter.services.mozilla.com/nimbus/user-messaging-trackers-blocked-notification
https://experimenter.services.mozilla.com/nimbus/1-click-pin-experiment
https://experimenter.services.mozilla.com/nimbus/onboarding-modal-experiment
https://experimenter.services.mozilla.com/nimbus/default-browser-adoption-experiment-release
https://experimenter.services.mozilla.com/nimbus/1-click-pin-during-onboarding
https://experimenter.services.mozilla.com/nimbus/multistage-onboarding-remove-urlbar-focus
- Attached is a screenshot of the issue.
![image](https://user-images.githubusercontent.com/53752296/139846854-c9150280-3106-4c60-b2a0-662ca73205d3.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1848)

**Comment by pdehaan** [comment]
[I replied in [Slack](https://mozilla.slack.com/archives/CANCHH6R1/p1635867191112600?thread_ts=1635856502.111700&cid=CANCHH6R1) but probably a bit more useful here... although this response might look like hot garbage in Jira due to Jira<=>GitHub formatting differences]

This is interesting. Looking at the DevTools for one of the graphql requests, I see this:

```json
{
  "errors": [
    {
      "message": "Expecting value: line 1 column 1 (char 0)",
      "locations": [{ "line": 76, "column": 5 }],
      "path": ["experimentBySlug", "readyForReview"]
    }
  ],
```

Where the `readyForReview` is `null` in the data for this experiment:
```json
  "data": {
    "experimentBySlug": {
      "id": 75,
      "readyForReview": null,
      "name": "default-browser-winning-branch-extended-holdback-study-beta",
      "slug": "default-browser-winning-branch-extended-holdback-study-beta",
      "status": "LIVE",
      "statusNext": "LIVE",
      "publishStatus": "REVIEW",
```

**Comment by pdehaan** [comment]
So if we assume that `null` is the likely culprit, we can scrape the [/api/v5/graphql endpoint](https://experimenter.services.mozilla.com/api/v5/graphql#query=%7B%0A%20%20experiments%20%7B%0A%20%20%20%20application%0A%20%20%20%20name%0A%20%20%20%20slug%0A%20%20%20%20status%0A%20%20%20%20readyForReview%20%7B%0A%20%20%20%20%20%20message%0A%20%20%20%20%20%20ready%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) for all experiments and then filter out any `null` ones locally:

```mjs
// index.mjs
import fs from "node:fs/promises";

// Where "result.json" is a local copy of https://experimenter.services.mozilla.com/api/v5/graphql#query=%7B%0A%20%20experiments%20%7B%0A%20%20%20%20application%0A%20%20%20%20name%0A%20%20%20%20slug%0A%20%20%20%20status%0A%20%20%20%20readyForReview%20%7B%0A%20%20%20%20%20%20message%0A%20%20%20%20%20%20ready%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A
const result = await fs.readFile("./result.json").then(JSON.parse);

console.log(result.errors.length, "errors");

result.data.experiments.forEach(experiment => {
  if (experiment.readyForReview === null) {
    console.log(`application=${experiment.application}; status=${experiment.status}; slug=${experiment.slug};`);
  }
});
```

And see that we have 19 potential failing-to-render experiments on prod.

```sh
> node index.mjs

19 errors
application=DESKTOP; status=LIVE; slug=emotive-pin-firefox-modal;
application=DESKTOP; status=COMPLETE; slug=user-messaging-set-default-trackers-blocked-notification;
application=DESKTOP; status=LIVE; slug=mr2-upgrade-spotlight-holdback;
application=DESKTOP; status=LIVE; slug=captive-portal-vpn-info-experiment;
application=DESKTOP; status=COMPLETE; slug=user-messaging-trackers-blocked-notification;
application=FENIX; status=LIVE; slug=default-browser-winning-branch-extended-holdback-study-release;
application=FENIX; status=LIVE; slug=default-browser-winning-branch-extended-holdback-study-beta;
application=FENIX; status=COMPLETE; slug=default-browser-adoption-experiment-release;
application=DESKTOP; status=COMPLETE; slug=onboarding-modal-experiment;
application=DESKTOP; status=COMPLETE; slug=1-click-pin-experiment;
application=IOS; status=PREVIEW; slug=testing-preview-collection-selection;
application=FENIX; status=COMPLETE; slug=default-browser-adoption-experiment-beta;
application=FENIX; status=COMPLETE; slug=default-browser-adoption-experiment;
application=DESKTOP; status=COMPLETE; slug=multistage-onboarding-remove-urlbar-focus;
application=DESKTOP; status=COMPLETE; slug=1-click-pin-during-onboarding;
application=DESKTOP; status=COMPLETE; slug=multi-stage-onboarding-ask-and-show-to-pin;
application=DESKTOP; status=COMPLETE; slug=custom-messaging-in-aboutwelcome-for-chrome-users-to-import;
application=DESKTOP; status=COMPLETE; slug=multi-stage-aboutwelcome-set-default-as-first-screen-v2;
application=DESKTOP; status=COMPLETE; slug=multi-stage-aboutwelcome-set-default-as-first-screen;
```

**Comment by lmorchard** [comment]
Hmm, a first hunch I have is possibly we started enforcing feature value schema validation against branches where the feature was not enabled? Not sure how that would result in `readyForReview` as null though

https://github.com/mozilla/experimenter/commit/623b04c4c97abcf1cd62676dc9858dd6c9685edd#diff-da5192d8fdd27a14107b117c1f4fbfbbc6cbee34c61bc19dd273fc612781f7ebL749-R745

**Comment by jaredlockhart** [comment]
It's unfortunate that graphql is masking the actual error.

**Comment by jaredlockhart** [comment]
Ah yep branches that were disabled have `feature_value` = `''` which isn't valid json and now that there is no such thing as disabled all branches must have valid json values so we just gotta data migrate those to `{}`

**Comment by lmorchard** [comment]
FWIW, I haven't been able to reproduce the graphql error locally with a feature-disabled branch. But yeah, I still would guess that the null is from a json parsing exception swallowed up by the API layers

**Comment by jaredlockhart** [comment]
I just replicated one of the prod failing experiments locally by copying all the fields manually in the admin and can reproduce locally.  What we should do is add a 'dump to json' 'load from json' to the admin to make it easier to replicate prod experiments locally.

**Comment by lmorchard** [comment]
Might want to wrap that `json.loads()` in `_validate_feature_value_against_schema` with a try/catch to more helpfully report invalid JSON at that stage. That *should* be caught earlier in normal submission, but this just kind of slipped through in backend migrations. Could help to bolster that validator though

**Comment by jaredlockhart** [comment]
Yeah I tried that but actually you can do it a step earlier right in the branch ready serializer.

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible. Navigating to the experiment pages no longer displays the error. Tested on Firefox Release 93.0 (Build ID: 20210927210923).
