### ISSUE TITLE
Expose isRollout bool on experiment DTO

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6627]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1858)

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/nimbus-shared/pull/179/files

**Comment by jaredlockhart** [comment]
Oh I think this got accidentally closed by a different PR we still need to do this.
