### ISSUE TITLE
Creating a new experiment gives me a duplicate branch name

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6633]
https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/treatment-a-rollout-screenshots-test-copy/edit/branches

Note that I currently have a control branch (Treatment A) and a treatment branch (Treatment B).
Scroll down to the bottom of the page and click the `+ Add branch` button. Note that the new branch is named "Treatment B" which conflicts with my existing "Treatment B" branch name and if you click Save it will warn you saying "Branch names must be unique".
Except I didn't see that the first two times and ended up finding and uploading images, clicking Save, missing that error message because my scaled high DPI mobile screenshots were big (716×1273px) so the Save action didn't work and when I refreshed the page all my screenshots were gone.

Not sure why I'm getting auto generated conflicting branch names. But it's an interesting case of clones of clones of rollouts of experiments so maybe something got crossed at some point.

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1863)

**Comment by jaredlockhart** [comment]
Yep I can totally see why this is happening but the important thing is that we don't save invalid information so even if it generates a duplicate branch name as long as that isn't saved we'll be okay, the user can still fix it from the error feedback.
