### ISSUE TITLE
Vague error when saving takeaways w/o recommendation

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6660]
### STR
1. Have a "complete" experiment; ie: https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdwhaan-amp
2. On the Summary page, click "Edit"
3. Enter a summary (but no recommendation)
4. Click "Save"

### Actual results
> _"Sorry, an error occurred while submitting. Please try again."_

But there isn't a description of what the actual error is, or indication that recommendation and/or summary are required fields.

Looking at the failing /graphql error in the DevTools console, it tells me the following:

```json
{
  "errors":[
    {
      "message":"Variable \"$input\" got invalid value {\"changelogMessage\": \"Updated Takeaways\", \"conclusionRecommendation\": \"\", \"id\": 111, \"takeawaysSummary\": \"It was the best of things\\n\\nIt was the worst of things\\n\\nDo the things again\"}.\nIn field \"conclusionRecommendation\": Expected type \"NimbusExperimentConclusionRecommendation\", found \"\".",
      "locations":[
        {
          "line":1,
          "column":27
        }
      ]
    }
  ]
}
```

![pdwhaan-________amp__–_Summary___Experimenter](https://user-images.githubusercontent.com/557895/141026510-eafbf105-71db-48f5-a9e3-afe74e6cfb3b.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1878)

**Comment by lmorchard** [comment]
Yup, I can reproduce, taking a look! 👀
