### ISSUE TITLE
The Recipe JSON displayed for Live Nimbus experiments does not get updated if it is modified directly in Remote Settings

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6662]
**[Prerequisites]:**

* Be connected to the corporate VPN.
* Have the [Nimbus main page](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus) open.

**[Steps to reproduce]:**

1. Create a new Nimbus experiment.
1. Launch the experiment.
1. Open the Remote Settings Writer on the appropriate collection (e.g. [main-workspace/nimbus-desktop-experiments](https://settings-writer.stage.mozaws.net/v1/admin/#/buckets/main-workspace/collections/nimbus-desktop-experiments/records)).
1. Update the experiment record from RS.
1. Request a review for the changes and have someone approve them.
1. Observe the Recipe JSON of the experiment’s Nimbus page.

**[Proposed result]:**

* The Recipe JSON is updated to reflect the changes from Remote Settings.

**[Current result]:**

* The Recipe JSON displays the recipe at the time of its launch. 

**[Notes]:**

* Attached is a recording of the behavior.
![width=200,height=183](https://user-images.githubusercontent.com/53752296/141279195-facfd67f-4696-4256-aa9b-c66ba9ee7dc6.gif)

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1880)

**Comment by lmorchard** [comment]
I think this is working as designed & expected. We don't support modifying the record directly in Remote Settings.

The flow is only one-way from Experimenter to Remote Settings, with the exception of tracking changes in approval status. The recipe JSON on Experimenter is derived from the data managed within the experimenter UI. That gets pushed to Remote Settings and will overwrite any manual changes made there.

If we want / need the data flow to be bi-directional, it would be a significant project.

**Comment by heres-maria** [comment]
There is an older issue - #6115 - which made me think this might be an issue. Please let me know if this should be changed to a user request.

**Comment by lmorchard** [comment]
The phrasing seems like it could mean Remote Settings affects what the Summary page says, but it's actually the opposite. That was a bug where something displayed on Experimenter didn't reflect what had been pushed to Remote Settings - it's not that a change in Remote Settings flowed back into Experimenter

**Comment by heres-maria** [comment]
I have changed this to a user request. It would be helpful when testing requires us to modify anything directly in Remote Settings. That being said, I understand this might not be feasible.

**Comment by jaredlockhart** [comment]
@heres-maria Yeah I understand why it would be helpful for testing but it breaks a lot of the assumptions in the current workflow and it's not easy to change so I'm going to wontfix this for now.
