### ISSUE TITLE
The MR2 mobile experiments display a General application error for their Results pages

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6664]
**[Steps to reproduce]:**
1. Open the [All Users Home Screen Android](https://experimenter.services.mozilla.com/nimbus/all-users-home-screen-android) page.
2. Click the “Results” link from the navigation panel.
3. Observe the page.

**[Expected result]:**
- The Results page is displayed correctly.

**[Actual result]:**
- The Results page returns an error:
“General application error
t[e].branch_data[r][n] is undefined|

**[Notes]:**
- These are the experiments which display this error:
https://experimenter.services.mozilla.com/nimbus/all-users-home-screen-android
https://experimenter.services.mozilla.com/nimbus/mr2-home-screen-impact-assessment-experiment
https://experimenter.services.mozilla.com/nimbus/upgraded-user-home-screen-impact-assessment-experiment
- Attached is a recording of the issue.
![results page error](https://user-images.githubusercontent.com/53752296/141456442-68254ed4-4224-4611-a88d-bcd7115f69f1.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1881)

**Comment by pdehaan** [comment]
I'm seeing the following error on https://experimenter.services.mozilla.com/nimbus/all-users-home-screen-android/results

> _Cannot read properties of undefined (reading `'relative_uplift'`)_

**Comment by jaredlockhart** [comment]
@heres-maria suggests it may result from a mismatch in the branches data from the experiment and from the results data.

**Comment by heres-maria** [comment]
@jaredlockhart The issue is still reproducible. On my usual Firefox Release profile I see the error mentioned in the original STR and using a new profile in Google Chrome I get the ["Cannot read properties of undefined (reading 'relative_uplift')" error ](https://github.com/mozilla/experimenter/issues/6664#issuecomment-967369089) @pdehaan mentioned. 
As a result, I will reopen this issue.
Tested using Firefox Release 94.0.1 (Build ID: 20211103134640) and Google Chrome 95.0.4638.69.

**Comment by heres-maria** [comment]
These are the errors displayed in the Console for Chrome:
![image](https://user-images.githubusercontent.com/53752296/142005755-7c2dba84-8891-49e0-bfef-42ec3f96fa2a.png)
![cors](https://user-images.githubusercontent.com/53752296/142006426-a53c0401-f91c-4b01-a083-c7a61595843e.png)

**Comment by jaredlockhart** [comment]
@heres-maria Fix should be deployed now.

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible. The Results pages are correctly opened for the three experiments. Tested using Firefox Release 94.0.1 (Build ID: 20211103134640). As a result I will close the issue and mark it verified fixed.
