### ISSUE TITLE
[Enhancement] Consider introducing more user-friendly error messages if possible

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6665]
**[Prerequisites]:**
- Have a draft with a custom Nimbus feature chosen.

**[Steps to reproduce]:**
1. Go to the admin page and modify the feature config used in the draft to have an incorrect JSON form (e.g. delete a comma)
2. Go to the draft from prerequisites.
3. Observe the page.

**[Proposed result]:**
- The error message displayed cautions the user that the feature configuration is not correct.
OR
- The draft is still displayed, but the Branches section is displayed as having an incorrect field.

**[Current result]:**
- The page returns a generic error.

**[Notes]:**
- Similarly for errors caused by the Results responses not having the expected configuration, if there is a way to have a more user-friendly error that explains what exactly went wrong based on the error code, that would help more easily identify what went wrong for the user seeing the error and not look so alarming.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1882)

**Comment by jaredlockhart** [comment]
@heres-maria I'm not exactly sure which specific errors you're describing here, can you include screenshots or quotes?

**Comment by heres-maria** [comment]
@jaredlockhart Here is a recording of the scenario from the STR.

![wrongly modify feature config](https://user-images.githubusercontent.com/53752296/152754031-69f81048-ae93-43b5-ac6e-c09f9901d9f7.gif)
