### ISSUE TITLE
Add support for targeting Developer Edition channel

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6678]
An example use case for targeting Dev Edition instead of Beta users:

For my ["Firefox 100" webcompat experiment](https://mana.mozilla.org/wiki/display/FIREFOX/Firefox+100+User-Agent+Experiment), I'd like to target Dev Edition users but not Beta users because the primary goal of this experiment is get user-submitted bug reports, not gather telemetry, and I believe that Dev Edition users are more likely to file bug reports (because they know they're running pre-release software, unless the majority of Beta users).

Beta users are not representative of our Release channel users: more than 50% don't even know they're running Beta software, about 60% are running Windows 7 compared to less than 20% of Release channel users run Windows 7, and about 60% are in located in India and Indonesia.

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1885)

**Comment by jaredlockhart** [comment]
Giving this a bump.
