### ISSUE TITLE
Branch slugs are not modified from the initially saved version if the branch name is changed

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6679]
**[Prerequisites]:**
- Have a new Nimbus draft open on the "Branches" section.

**[Steps to reproduce]:**
1. Add a branch name for the default branches or leave them on their default names.
2. Click “Save”.
3. Modify the branch names.
4. Click “Save”.
5. Go to the “Details” section and observe the branch slugs.

**[Expected result]:**
- The slugs correspond to the branch names.

**[Actual result]:**
- The slugs remain set to correspond to the first branch name saved. 

**[Notes]:**
- If experiments can be set up so that the behavior is determined by branch name and the user makes a mistake when first saving one, modifies it and does not notice the slug not changing, it could potentially lead to other issues.
- Attached is a recording of the issue.
![branch slug](https://user-images.githubusercontent.com/53752296/142404113-c30c4a9b-5f02-4332-a4ee-cae92f5a1f68.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1887)

**Comment by jaredlockhart** [comment]
Yep this is by design.  Unless we have a strong reason to change it we'll just leave it this way for now.
