### ISSUE TITLE
A “Detailed Analysis” link is wrongly displayed for experiments with “null” results

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6681]
**[Prerequisites]:**
- Have a live/completed experiment with no results (the admin page displays “null” for the "Results data" field)

**[Steps to reproduce]:**
1. Open the Nimbus page from prerequisites.
2. Observe the “Links” section.
3. Click the “Detailed Analysis” link and observe the page it opens.

**[Expected result]:**
- No “Detailed Analysis” link is displayed for experiments with no results.

**[Actual result]:**
- Step 2: A “Detailed Analysis” link is displayed for experiments with no results (“null”)  
- Step 3: The “Detailed Analysis” link opens an error page.

**[Notes]:**
- If Results returns any other value, the link is not displayed.
- Attached is a recording of the issue
![null results](https://user-images.githubusercontent.com/53752296/142597988-1e365b17-93f8-442a-87a5-1532eb2cfde5.gif)
.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1889)

**Comment by jaredlockhart** [comment]
Good catch 👍
