### ISSUE TITLE
A “Detailed Analysis” link is briefly displayed for experiments with empty results

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6682]
**[Prerequisites]:**
- Have a live/completed experiment for which the Results section displays “Experiment analysis not ready yet” (e.g. https://experimenter.services.mozilla.com/nimbus/more-from-mozilla).

**[Steps to reproduce]:**
1. Open the Nimbus page from prerequisites.
2. Observe the “Links” section.

**[Expected result]:**
- No “Detailed Analysis” link is displayed for experiments where analysis is not yet ready.

**[Actual result]:**
- A “Detailed Analysis” link is briefly displayed in the “Links” section before disappearing. 

**[Notes]:**
- Attached is a recording of the issue
![detailed analysis flashing](https://user-images.githubusercontent.com/53752296/142600770-71df1841-7abf-4f49-b19d-1bd00e3a8158.gif)
.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1890)

**Comment by jaredlockhart** [comment]
Yeah I'm not too worried about that as long as it prevents users from doing the wrong thing.
