### ISSUE TITLE
[Enhancement] Consider updating the Results even later than three days

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6684]
**[Prerequisites]:**
- Have a Complete experiment finished more than three days ago where the Control branch was incorrectly set. Have Results displayed for the experiment already.

**[Steps to reproduce]:**
1. Modify the control branch using Jetstream.
2. Open the Results section of the Nimbus page for the experiment. 
3. Observe the contents of the page.

**[Proposed result]:**
- The page correctly displays the modified branch as baseline even after three days. The experiment where this was observed needed an update on Nov 9 for an experiment which ended on Oct 23.

**[Current result]:**
- The results are not updated after three days.

**[Notes]:**
- This behavior was observed for this production experiment: https://experimenter.services.mozilla.com/nimbus/user-messaging-set-default-trackers-blocked-notification/results.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1892)

**Comment by jaredlockhart** [comment]
We have a way to manually trigger updating the results from the admin if a user requests it so I think I can close this as fixed.
