### ISSUE TITLE
The first paragraph from the experimenter.info Introduction is missing some text at the end

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6685]
**[Steps to reproduce]:**
1. Open the https://experimenter.info/ page.
2. Observe the end of the first paragraph.

**[Expected result]:**
- The paragraph ends properly.

**[Actual result]:**
- The paragraph is missing some text at the end.

**[Notes]:**
- Attached is a screenshot of the issue.
![Screenshot 2021-11-19 at 21-44-34 Getting Started Experimenter Docs](https://user-images.githubusercontent.com/53752296/142650795-3bda10bc-10bd-4053-8159-c69b048853aa.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1893)

**Comment by pdehaan** [comment]
Looks like this page/section was added in https://github.com/mozilla/experimenter-docs/commit/8f1f734913ae60ff84b025e97ba89565945c2b90#diff-22c9fb0ec1df70b351f4e5e5a543ebc423084c924e0bbc5f3b42214be8e78893.
Although I don't see a matching deletion in that commit to imply that the content was copied from elsewhere, so I think it was new content.

**Comment by jaredlockhart** [comment]
We have a professional technical writer reviewing these docs now so I think this will get fixed during that pass.
