### ISSUE TITLE
Add ready-for-review validation to ensure is_rollout is supported on application version selected for experiment

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6697]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1895)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Getting into this task, I wonder if this should be a warning rather than an error? That is, a single-branch experiment is currently supported as-is, which is what we’ve been using as an MVP for rollouts. The next immediate practical upshot from rollout support (i.e. isRollout exposed in the DTO per https://mozilla-hub.atlassian.net/browse/EXP-1858 ( https://mozilla-hub.atlassian.net/browse/EXP-1858|smart-link )) is separate feature namespace bucket isolation for experiment vs rollout, IIRC?

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

🚩 Flag added

blocked on nimbus-shared/issues/183

**Comment by eliserichards** [comment]
PR: https://github.com/mozilla/experimenter/pull/6765
