### ISSUE TITLE
Rollouts with the isRollout set and Experiments using the same feature can not both be active

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6709]
**[Affected Versions]:**
- Firefox Nightly 96.0a1 (Build ID 20211126093927) 
- Firefox Beta 95.0b12 (Build ID 20211125185815) 

**[Affected Platforms]:**
- Windows 10
- macOS 11.6
- Linux Mint 20.1

**[Prerequisites]:**
- Have an experiment and a rollout with the isRollout flag set using these recipes: [experiment](https://gist.github.com/heres-maria/4075c16bc36674bec8d30b3d34e9df70) (ver with flag) / [experiment](https://gist.github.com/heres-maria/5ecdc6acf4185fac846998090f86a527) (ver without flag) and [rollout](https://gist.github.com/heres-maria/a90f472e2058ba4f77bbded3c63c48b4).

**[Steps to reproduce]:**
1. Open Firefox.
2. Change the environment to Stage using Remote Settings Devtools.
3. Clear data and perform a Poll.
4. Restart the browser.
5. Observe the enroll and enroll failed events in “about:telemetry#events”.

**[Expected result]:**
- You are enrolled in both the experiment and rollout.

**[Actual result]:**
- If you are enrolled in an experiment using a certain feature, you can not enroll in an rollout using the same feature.

**[Notes]:**
- The issue is also reproducible for the case in which you are enrolled in a rollout and attempt to enroll in an experiment.
- Attached is a recording of the issue.
![rollout vs experiments](https://user-images.githubusercontent.com/53752296/143592017-f2c5b630-6a87-4e47-8a78-27076219918e.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1903)

**Comment by piatra** [comment]
The new rollouts (with `isRollout`) has not yet landed in desktop: https://bugzilla.mozilla.org/show_bug.cgi?id=1738286

**Comment by heres-maria** [comment]
Based on the previous comment, I will close this issue.
