### ISSUE TITLE
Add checkbox to exclude enterprise users from experiments and rollouts

### ISSUE THREAD

**Issue by piatra** [mozilla/experimenter#6710]
Excluding enterprise users is coming up very often in Audience targeting. I think it should be the default. Something like this in the audience tab:
- [x] Exclude enterprise users

Checked by default and if needed it can be unchecked.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1905)

**Comment by piatra** [comment]
It can wait, I was thinking I could also give it a try if I have some time.

**Comment by jaredlockhart** [comment]
Bumping this.
