### ISSUE TITLE
Bug 1738937 -  Switch Desktop FeatureManifest to yaml format and auto-generate the JS file

### ISSUE THREAD

**Issue by piatra** [mozilla/experimenter#6724]
Bug 1738937 removes the `FeatureManifest.js` from `toolkit/components/nimbus` and replaces it with a yaml file.
The `FeatureManifest.js` will continue to exist as a build artifact (generated from the yaml file) and will be indexed by searchfox at this address:

```
// not currently available, takes a day for searchfox to refresh it's cache
https://searchfox.org/mozilla-central/source/__GENERATED__/__macosx64__/toolkit/components/nimbus/FeatureManifest.js
```

So we can continue to use the JS file (from the new location) or switch to the YAML file the contents will be identical. Otherwise if the file was pulled from hg.mozilla.org then there will be no `.js` file there.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1909)

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

Thanks for the heads up Victor Andrei Oprea.  This should let us gut out our janky js loading here:

https://github.com/mozilla/experimenter/blob/main/Makefile#L69-L72 ( https://github.com/mozilla/experimenter/blob/main/Makefile#L69-L72|smart-link ) 

and replace it with just curling the yaml file and using pyyaml to load it.

**Comment by jaredlockhart** [comment]
The YAML file is here: https://searchfox.org/mozilla-central/source/toolkit/components/nimbus/FeatureManifest.yaml

**Comment by lmorchard** [comment]
So, that's the YAML as indexed in searchfox... do we actually want this from mercurial? i.e.: 

https://hg.mozilla.org/mozilla-central/raw-file/tip/toolkit/components/nimbus/FeatureManifest.yaml

**Comment by lmorchard** [comment]
Looks like this is the URL for the JS:

https://hg.mozilla.org/mozilla-central/raw-file/b12bc4e6534808fb9a5352b7545f573f6dec90d3/toolkit/components/nimbus/FeatureManifest.js

Do we want to pin this to a commit? Or is `tip` good from here?
