### ISSUE TITLE
Bug 1740718 - Adding a new field `schema` to a Feature in FeatureManifest

### ISSUE THREAD

**Issue by piatra** [mozilla/experimenter#6725]
In Bug 1740718 we added a new field `schema` ([example](https://searchfox.org/mozilla-central/rev/e9cd2997be1071b9bb76fc14df0f01a2bd721c30/toolkit/components/nimbus/FeatureManifest.js#425)) that points to a location in the mozilla-central tree where a JSON Schema is found that can be used to validate the `variables` field.
This field is optional and useful for features where the values are large JSON objects that are too cumbersome (and insufficient) to be described with our current FeatureManifest syntax.
The `variables` field for entries that specify a `schema` will be empty.

[RFC doc with additional context](https://docs.google.com/document/d/1svvj-PcqARb0RHa1w2LdISwvwzT73FNFFPirvHSGhyE/edit)

https://mozilla-hub.atlassian.net/browse/EXP-1910

**Comment by jaredlockhart** [comment]
Awesome thank you @piatra we should adopt this pattern on mobile too.  We'll need to ingest and use this schema in the console.

**Comment by jaredlockhart** [comment]
https://mozilla-hub.atlassian.net/browse/EXP-1910

**Comment by jaredlockhart** [comment]
This is done now.
