### ISSUE TITLE
Use `feature_values` in nimbus-ui

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6743]
Once we've added the `feature_values` field in the V5 API in https://github.com/mozilla/experimenter/issues/6742 we can migrate nimbus-ui to use it for the branch page.  This change will only migrate the API call and not the UI itself so users will still only be able to input a single feature value.  We can update the UI to allow inputing multiple feature values as a followup.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1917)

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

Folding this into https://mozilla-hub.atlassian.net/browse/EXP-1914 ( https://mozilla-hub.atlassian.net/browse/EXP-1914|smart-link )
