### ISSUE TITLE
Allow selecting multiple features and inputting multiple values for them in nimbus-ui

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6745]
After the V5 API has been migrated to use the new `feature_configs` and `feature_values` fields we can update the UI to allow users to input multiple features and their values in each branch.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1919)

**Comment by jaredlockhart** [comment]
Soon!

**Comment by brennie** [comment]
This landed two weeks ago
