### ISSUE TITLE
[Enhancement] Consider opening the #ask-experimenter Slack channel in the browser application also 

### ISSUE THREAD

**Issue by SoftVision-SimonaRosu** [mozilla/experimenter#6766]
**[Prerequisites]:**
- Have Firefox browser installed and opened.
- Be logged in to the Slack browser app (do not have the standalone Slack app installed).
- Have a Nimbus recipe created.

**[Steps to reproduce]:**
1. Click the "#ask-experimenter" link from the “Overview” page of the recipe.
2. Observe what happens.

**[Proposed result]:**
- The #ask-experimenter Slack channel is opened in the Slack browser application.

**[Current result]:**
- The #ask-experimenter” Slack channel is not opened and the “The address wasn’t understood” error message is displayed.

**[Notes]:**
- The #ask-experimenter” Slack channel should also be opened in the Slack browser application since there are users who use this application only in the browser.
- Attached is a screen recording of the current behavior.

![channel_SlackBrowser](https://user-images.githubusercontent.com/50919288/145397753-72c7d42f-8ad6-4004-ba98-be3844eacbaa.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1931)

**Comment by lmorchard** [comment]
Hmm, currently the link we have here is [an app-specific deep-link](https://api.slack.com/reference/deep-linking#client): slack://channel?team=T027LFU12&id=CF94YGE03

What we probably want is something more like this [HTTP redirect deep link](https://api.slack.com/reference/deep-linking#app_channel): https://slack.com/app_redirect?channel=CF94YGE03

**Comment by SoftVision-SimonaRosu** [comment]
I've verified the fix, the “ask-experimenter” Slack channel is opened in the browser application or the Desktop application, depending on what the user uses. Tested on Firefox Nightly 97.0a1, Build ID 20211209155024.
