### ISSUE TITLE
Screenshots are not removed from the database if their branch is deleted

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6770]
**[Prerequisites]:**
- Have a Nimbus experiment draft.

**[Steps to reproduce]:**
1. Open the Nimbus draft on the “Branches" page.
2. Add a screenshot with a description to a branch.
3. Click “Save” and navigate to “Details”.
4. Open the screenshot using right click and “Open image in new tab”.
5. Go back to “Branches”.
6. Delete the branch associated with the screenshot and click “Save”.
7. Go back to the screenshot opened previously and refresh the page.

**[Expected result]:**
- The screenshot can no longer be accessed using the link.

**[Actual result]:**
- The screenshot can still be accessed using the link.

**[Notes]:**
- The issue is not reproducible when deleting the screenshots themselves.
- Attached is a recording of the issue.
![screenshot for deleted branch](https://user-images.githubusercontent.com/53752296/145581444-4c133844-2747-4f58-8c6b-dfd1a932fbfc.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1935)

**Comment by jaredlockhart** [comment]
We should verify if this is still happening.

**Comment by timalsinab** [comment]
Hello, I am a outreach applicant. Can I work on it?

**Comment by yashikakhurana** [comment]
@timalsinab I replicated the issue, it is no longer valid, I am closing this issue, please feel free to find other issue, let me know if you have any questions
