### ISSUE TITLE
The "Learn more" (Project Nimbus) link from Request Launch leads to a “Page Not Found” Confluence page

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6771]
**[Prerequisites]:**
- Have a Nimbus experiment draft Ready for Launch.

**[Steps to reproduce]:**
1. Open the draft from prerequisites on “Summary”.
2. Click the “Learn more” link from the “Request Launch” section.

**[Expected result]:**
- The link leads to a valid Confluence page.

**[Actual result]:**
- The link leads to a Confluence page that displays:
“Page Not Found”
“The page you were trying to reach could not be found: it may have been renamed or moved to another space, or the name you requested may be incomplete”

**[Notes]:**
- One of the suggested links displayed in the “In This Space” section is the renamed page https://mana.mozilla.org/wiki/display/FJT/Nimbus
- Attached is a recording of the issue.
 
![project Nimbus](https://user-images.githubusercontent.com/53752296/145604951-e1209f4a-48d9-4514-85ed-bf3fd35e72fb.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1936)

**Comment by jaredlockhart** [comment]
We should verify this.

**Comment by aminomancer** [comment]
I was about to report this, just happened to me today

> Do you want to test this experiment before launching to production? [Learn more](https://mana.mozilla.org/wiki/display/FJT/Project+Nimbus)[Opens in new window](https://mana.mozilla.org/wiki/display/FJT/Project+Nimbus)

**Comment by eliserichards** [comment]
Just verified that this is still broken. The link should be this: https://mozilla-hub.atlassian.net/wiki/spaces/FJT/pages/11470446/Nimbus

**Comment by yashikakhurana** [comment]
this is same issue reported here - https://github.com/mozilla/experimenter/issues/8347

**Comment by emmaz12** [comment]
@yashikakhurana Hi! I am an outreachy applicant! I would love to take on this issue

**Comment by yashikakhurana** [comment]
@emmaz12 same comment as previous, would recommend finishing first assigned issue, then tag me again I will assign it to you :)

**Comment by ahn-nath** [comment]
Hello, @yashikakhurana.

I am an Outreachy participant and noticed this task is still open. Could you assign it to me, please? Thanks.

**Comment by ahn-nath** [comment]
> @ahn-nath if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

Please feel free to reassign. Thanks.

**Comment by emmaz12** [comment]
@yashikakhurana If this issue is open, happy to take it on :)

**Comment by emmaz12** [comment]
@yashikakhurana Attempting to reproduce this issue. However, when directed to the link described above, I am brought to a site asking to log into confluence. When creating an account to log in, I receive this error: 

<img width="464" alt="Screen Shot 2023-03-10 at 11 44 39 AM" src="https://user-images.githubusercontent.com/117552772/224413391-1fb91a23-3aa6-40fc-92de-75f21a0a0c5b.png">


Planning to assume the bug exists and change to the correct link above (https://mana.mozilla.org/wiki/display/FJT/Nimbus). However, will not be able to test if this is configured correctly on my end. 

Any suggestions?

**Comment by yashikakhurana** [comment]
@emmaz12 don't worry, when you will create PR I can test that for you :)
