### ISSUE TITLE
Need Audience section to set max version of an experiment

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6775]
Current Nimbus experimenter console only allows min version to set , and doesn't have capability to set Max version which block running experiment targeting specific version only

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1938)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/18552/Screen+Shot+2021-12-13+at+9.49.36+AM.png">Screen Shot 2021-12-13 at 9.49.36 AM.png</a>

**Comment by data-sync-user** [comment]
➤ Punam Dahiya commented:

UI for More From Mozilla changes in Fx 96 and we don’t want users upgrading to 96 to stay in the experiment

**Comment by punamdahiya** [comment]
With fix of this issue custom targeting added in #6776 can be removed

**Comment by data-sync-user** [comment]
➤ Punam Dahiya commented:

Tried using max version from experimenter console. It seems there is client validation set that doesn’t allow to user to select same release as both min and max version which is needed to run experiment on a selected release. See attached screenshot Thanks
