### ISSUE TITLE
Nimbus experiments can be saved with a max version smaller than the minimum version

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/experimenter#6813]
*[Prerequisites]:*
- Have a Nimbus experiment created in a Draft state.
- Have the "Audience" page open.

*[Steps to reproduce]:*
1. Click the "Min Version" dropdown and select a value.
2. Click the "Max Version" dropdown and select a value lower than the minimum one.
3. Click the "Save and Continue" button and observe the behavior.

*[Expected result]:*
- The "Audience" page is not saved and an error is displayed.

*[Actual result]:*
- The "Audience" page is saved and the "Summary" page is displayed.

*[Notes]:*
- Clicking the "Audience" button from the "Missing details in: Audience" section highlights the fields and displays an error.
- Navigating to the "Audience" page from the side menu does not trigger the error.
- Attached a screen recording of the issue:

![min_max](https://user-images.githubusercontent.com/40393891/147263847-1eec466f-8024-456e-bbed-8834a4388abc.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1953)

**Comment by lmorchard** [comment]
I think this is working as intended.

> [Actual result]:
>    The "Audience" page is saved and the "Summary" page is displayed.
> [Notes]:
>    Clicking the "Audience" button from the "Missing details in: Audience" section highlights the fields and displays an error.

The design idea here is that the user should be able to save partial and even erroneous input while the experiment draft is in progress. Full validation is deferred until the point of requesting a review for launch.

>    Navigating to the "Audience" page from the side menu does not trigger the error.

This is also working as intended, though there is a user request to reconsider this. https://github.com/mozilla/experimenter/issues/6666
