### ISSUE TITLE
[Enhancement]The experiment's Summary Page should direct users to file a QA request instead of a PI request

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/experimenter#6833]
*[Prerequisites]:*
- Have a Nimbus experiment created in a Draft state.
- Habe the experiment's "Summary" page open.

*[Steps to reproduce]:*
1. Observe the string from the "QA Sign-off" section.

*[Expected result]:*
- The "Recommended: Please file a QA request." string is displayed.

*[Actual result]:*
- The "Recommended: Please file a PI request." string is displayed.

*[Notes]:*
- With the name change of PI requests to QA requests we should update the string to reflect the change.
![image](https://user-images.githubusercontent.com/40393891/148398058-dbb205f5-2881-4fe7-9f9e-f6651d52cb42.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1961)

**Comment by SoftVision-CiprianMuresan** [comment]
I have verified that the string has been updated to "Recommended: Please file a QA request." on the Stage and Prod servers.
