### ISSUE TITLE
Store set_experiments_locally documents as strings

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6930]
The call into set_experiments_locally takes a string, and deserializes it into an Experiment, then re-serializes it back into a string before storing it in rkv.

This is wasteful because it does a whole serde cycle.

More importantly, it is messy from an updates point of view:

1. user downloads an experiment recipe document. It is loaded and saved as the current version of the schema.
2. app is updated, and now the SDK has a different version of the schema
3. app is run, so a migration happens from the old version to the new version.

If experimenter starts using the new version of the schema before the app upgrades, the old version downloads the new schema recipes, **migrates it down a version** and stores it. Once the app is upgraded and relaunched, the downgraded version of the new recipe is then migrates it **up a version**. We should avoid this first downward migration.

This issue postpones the migration of schema until the time it is first needed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2074)

**Comment by purna135** [comment]
I'd like to get started on this, but I'm a beginner. Could you please point me in the right direction?
