### ISSUE TITLE
End of epic demo

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6996]
For the New What's News letter for experimenter.info

This should be a video demo, to whet our customers' appetite for the upcoming work.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2137)

**Comment by tarikeshaq** [comment]
heh, I think the sync is broken? I changed it from "new" to "todo" it `data-sync-user` just closed it 🤷
