### ISSUE TITLE
The Archive tooltip is not displayed when an experiment is put in the Preview or Review state until the page is refreshed

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6999]
**[Prerequisites]:**

* Have an fully completed experiment in the `Draft` state.

**[Steps to reproduce]:**

1. Navigate to the experiment from prerequisites.
1. Click the `Launch to Preview` button.
1. Hover the circled ? symbol next to the `Archive` option and observe the behavior.

**[Expected result]:**

* The `Experiments can only be archived when in Draft or Complete.` tooltip is displayed.

**[Actual result]:**

* No tooltip is displayed

**[Notes]:**

* The issue is also reproducible when the experiment is put in the `Review` state.
* The issue is not reproducible when the experiment is put in the `Live` state.
* The issue is no longer reproducible after the page is refreshed.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-2142)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19624">no tooltip right after moving to preview.gif</a>

**Comment by eliserichards** [comment]
https://github.com/mozilla/experimenter/blob/0651bb753566d87ec80f48767c5b24ac416257ac/app/experimenter/nimbus-ui/src/lib/constants.ts#L22

**Comment by tobidosumu** [comment]
Hello @eliserichards. I am also an Outreachy applicant. I would like to fix this bug.

**Comment by yashikakhurana** [comment]
@tobidosumu assigned to you 🎉 , let me know if you have any questions

**Comment by tobidosumu** [comment]
Hooray! Finally 😁. Thanks @yashikakhurana 🙏

**Comment by yashikakhurana** [comment]
@tobidosumu if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

**Comment by tobidosumu** [comment]
Hello @yashikakhurana. I am working on the issue. Please, kindly give me some time. Thank you.

**Comment by cherish2003** [comment]
@yashikakhurana i want to work on this issue can you assign me

**Comment by cherish2003** [comment]
@yashikakhurana Kindly review the PR to close this issue

**Comment by cherish2003** [comment]
@yashikakhurana mam is there any changes to make in this issue

**Comment by yashikakhurana** [comment]
@cherish2003 no no everything is done, thank you, our QA just verified the issue and its all good :)
