### ISSUE TITLE
The "Value" feature configuration field can be set up so curly braces are not present

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#7000]
**[Prerequisites]:**
- Have a Nimbus draft.

**[Steps to reproduce]:**
1. Navigate to “Branches”.
2. Select a feature and toggle enable to on.
3. In the "Value" field write “2”.
4. Click “Save and Continue”.

**[Expected result]:**
- The Branches section appears in the sidebar as having an incorrect field.

**[Actual result]:**
- The Branches section does not appear in the sidebar as having an incorrect field.

**[Notes]:**
- The experiment can be launched.
- The field also accepts true and “string”.
- Attached is a recording:

![int book string](https://user-images.githubusercontent.com/53752296/150554671-62ef1438-295c-4222-a3b6-537da3f800c1.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2143)

**Comment by eliserichards** [comment]
Is this still a valid issue?

**Comment by sudarsan2k5** [comment]
I would like to work on this.

**Comment by heres-maria** [comment]
@eliserichards @sudarsan2k5 I can no longer reproduce this issue. Trying the STR now leads to a "2 is not of type 'object'" error.

**Comment by eliserichards** [comment]
Thanks @heres-maria! I am going to close this issue, sorry @sudarsan2k5
