### ISSUE TITLE
Some green checkmarks from the “Overview” and “Audience” sections overlap the drop-down arrows

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7013]
**[Prerequisites]:**

* Have an experiment in draft view.

**[Steps to reproduce]:**

1. Have the “Overview” section displayed.
1. Go to the “Additional Links” subsection. 
1. Click on the first drop-down button and choose one of the options displayed.
1. Click outside of the drop-down button.
1. Observe the behavior.

**[Expected result]:**

* The checkmark is displayed next to the drop-down arrow.

**[Actual result]:**

* The checkmark overlaps the drop-down arrow.

**[Notes]:**

* This issue is also reproducible in the “Create a new Experiment” section for the “Application” field and in the “Audience” section for the “Channel”, “Min Version”, “Max Version” and “Advanced Targeting” fields.

* In some cases the green checkmark overlaps the text.

* Attached are some print screens of the issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-2155)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19934">image 1.JPG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19936">image 2.JPG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19935">Image 3.JPG</a>

**Comment by sudarsan2k5** [comment]
I would like to work on this.

**Comment by eliserichards** [comment]
@sudarsan2k5 I have already assigned you to https://github.com/mozilla/experimenter/issues/7575. Once that is finished (or if you would rather work on this instead) then you can pick this one up 😄

**Comment by eliserichards** [comment]
<img width="1992" alt="image" src="https://user-images.githubusercontent.com/43795363/223573263-2d214491-e1ab-481c-9acc-62dcdbbd3413.png">

This is still valid

**Comment by Yass32** [comment]
Hello @eliserichards Im a new outreachy applicant, id like to be assigned this task

**Comment by Yass32** [comment]
@yashikakhurana thank you

**Comment by Yass32** [comment]
Hi @yashikakhurana sorry but I'm having trouble finding the CSS file of that page, can you please help me out?

**Comment by Sprof22** [comment]
Hello, can this task be assigned to me. I have an idea of how to go about it. I need your greenlight @yashikakhurana

**Comment by Sprof22** [comment]
@yashikakhurana thanks. setting up the environment. Expect results shortly

**Comment by Sprof22** [comment]
I am having difficulty setting up this project. 
If it's not working by the close of day, I will unassign myself. Thanks for your patience

**Comment by Avi-88** [comment]
Hello @yashikakhurana ma'am, the changes I made in one of my recent PR's ([this one](https://github.com/mozilla/experimenter/pull/8539)) also address this issue, but I haven't included the advanced targeting input selector in that one . I can include it in that PR itself or I could work on the rest of the changes in different PR for this particular issue which will close this, please let me know what you think about this, thanks

**Comment by yashikakhurana** [comment]
@Avi-88 sure thank you, since they are very closely related, I would suggest making changes in the same and link issue in the same PR, thanks
