### ISSUE TITLE
[Intermittent] Different Firefox Focus for Android startups seem to either enroll users in cached(?) or current experiments in turns 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7063]
**[Affected Versions]:**

* Firefox Focus for Android 98.0 (Build #360350715 GV: 98.0a1-20220203093047)

**[Affected Platforms]:**

* Android 10 - Samsung Galaxy S8

**[Prerequisites]:**

* Have a Nimbus experiment for Focus for Android launched on Stage Preview to 100% of the population.
* Have a Focus for Android build with the following modifications:

The following lines added to “local.properties”:

```
nimbus.remote-settings.url = https://settings.stage.mozaws.net/v1
debuggable = true
```

A new “.nimbus” file containing the following line:

`https://settings.stage.mozaws.net/v1`

* Have a build set up so that you get Preview experiments (at the moment it is the default due to EXP-2193)

**[Steps to reproduce]:**

1. Remove from Preview the experiment from prerequisites.
1. Launch to Preview another experiment.
1. Install the Focus for Android app on a device.
1. Open the app.
1. Close the app.
1. Go to Settings > Privacy & Security > Studies.
1. Repeat steps 4-6 a few times.
1. Observe whether you are enrolled in the study from prerequisites.

**[Expected result]:**

* You are enrolled in one study. After the collection has been updated, you are unenrolled from the first study and enrolled in the second study.

**[Actual result]:**

* You are enrolled in one study after one restart, then another study after another restart and so on. In some cases you are not enrolled in any study after a restart.

**[Notes]:**

* Attached is a recording of the issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-2194)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/20188">restart.gif</a>

**Comment by jaredlockhart** [comment]
Double check in the collection

https://settings.stage.mozaws.net/v1/buckets/main/collections/nimbus-preview/records

To make sure that the unpublished one is unpublished and the published one is published

**Comment by data-sync-user** [comment]
➤ Maria Heres commented:

I will come back with more information on whether the unpublished recipe is displayed in https://settings.stage.mozaws.net/v1/buckets/main/collections/nimbus-preview/records ( https://settings.stage.mozaws.net/v1/buckets/main/collections/nimbus-preview/records ) and if I am able to reproduce it for other platforms ASAP on Monday.
