### ISSUE TITLE
Jetstream parse error 'list index out of range'

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7067]
https://sentry.prod.mozaws.net/operations/experimenter-prod/issues/17811821/?query=is%3Aunresolved

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2197)

**Comment by shell1** [comment]
early investigation from Jared and Anna discussions is that the format of data that jetstream emits and that console consumes don’t agree.  It causes an issue on importing… seeing more often.  

Need DE resources to partner with Jared to get the visual infrastructure in experimenter to work.  do we want to visualize in looker?  what is the future path.  Anna is thinking through alternatives now.  @shell1 raise with Rob as critical for experimentation.

**Comment by scholtzan** [comment]
@jaredlockhart is there a traceback that this error produces? I don't have access to sentry, so I can't check for it myself, but I do have an idea of why this error might be happening.

**Comment by jaredlockhart** [comment]
I'm assuming this is closable now.
