### ISSUE TITLE
Add New-User targeting to Experimenter options for Focus

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#7093]
Refiling here for @travis79

* was filed in an area it wouldn't be seen (as Initiative). [https://mozilla-hub.atlassian.net/browse/EXP-2222](https://mozilla-hub.atlassian.net/browse/EXP-2222) - refiled here [https://github.com/mozilla/experimenter/issues/7093](https://github.com/mozilla/experimenter/issues/7093|smart-link) 

Focus Android and iOS currently don’t have the option to select new users under the advanced targeting options.  They will require this functionality for an upcoming experiment, specifically on Focus Android (removing tabs experiment).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2228)

**Comment by travis79** [comment]
Thanks @shell1!  I didn't realize I filed this in the wrong place :)

**Comment by data-sync-user** [comment]
➤ Shell Escalante commented:

https://github.com/mozilla/experimenter/issues/7093 ( https://github.com/mozilla/experimenter/issues/7093|smart-link )

**Comment by data-sync-user** [comment]
➤ Tarik Eshaq commented:

PR is up in https://github.com/mozilla/experimenter/pull/7099 ( https://github.com/mozilla/experimenter/pull/7099|smart-link )

**Comment by channingcarter** [comment]
I see that this issue has been closed. When will this be available in experimenter? @tarikeshaq

**Comment by tarikeshaq** [comment]
@channingcarter I verified that this is available in stage already 😄 Should be available in prod as well (I'm not 100% sure about the deployment cycles, but it should be there)
