### ISSUE TITLE
It is not made clear to experiment owners that some mobile version targeting will not be reflected in the experiment recipe

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7139]
**[Prerequisites]:**

* Have a mobile Focus draft open.

**[Steps to reproduce]:**

1. Open the draft from prerequisites on the “Audience” page.
1. Set the “Min Version” field to “No Version”.
1. Set the “Max Version” field to a value (e.g. Firefox 99).
1. Click “Save and Continue”.
1. Click “Preview Recipe JSON” to observe the “targeting” part of the recipe.

**[Expected result]:**

* Users are notified in some way that only setting a Max Version will not be functional.

**[Actual result]:**

* Users can set only a Max Version, without a Min Version, despite that targeting will not be updated to respect that choice.

**[Notes]:**

* The same issue appears when users try to set a Minimum version <98. They are not informed by the UI that it is not possible. It is especially problematic if they also want to set an acceptable Maximum version (Min 97 & Max 99), as the Maximum version will not be accepted either.

* Attached is a recording of the issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-2304)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22060">max version only.gif</a>

**Comment by jaredlockhart** [comment]
Excellent catch @heres-maria !
