### ISSUE TITLE
Expose targeting config in API

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7159]
Each targeting config has a description field but we don't show it anywhere on the audience form or on the detail/summary page.  We should show it in the drop down if we can finagle it into the react-select item component, and we should add it on the detail page.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2328)

**Comment by eliserichards** [comment]
GQL refreshes on the page every 30s. We are making a "get experiments" call **and** a "get config" call. The "get config" uses the `config.ts` query.

Todo:
* add `description` field to `config.ts` file
* run `make generate_types`. Then we will be able to access the description field from the [`Nimbus.py`](https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/constants/nimbus.py) objects
* add to the Audience section of the Details view (probably in [TableAudience](https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/constants/nimbus.py))
   * overwrite element in react-select item to show:
      1. primary text = title (existing)
      2. secondary text = description

------
Additional work will be broken out into other tickets:
* add advanced targeting config to audience section in Details for feature configs
* description to details -> branches -> first dropdown, and details overview "feature config"

**Comment by eliserichards** [comment]
Expose feature config description in overview: https://github.com/mozilla/experimenter/issues/7213
