### ISSUE TITLE
Migrate to new sentry

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7203]
We need to migrate Experimenter over to the new sentry deployment.

Instructions:

We will need you to migrate your application to use the new SaaS Sentry. We have just finished a small beta period and the migration is now open to the whole company. The SaaS Sentry is SSO enabled. The login URL is https://sentry.io/organizations/mozilla/issues/ . 

Further set up instructions can be found on this mana page here: https://mana.mozilla.org/wiki/display/SRE/SaaS+Sentry

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2381)

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

Also filed https://mozilla-hub.atlassian.net/browse/DSRE-776 ( https://mozilla-hub.atlassian.net/browse/DSRE-776|smart-link )  to update the env vars to point to the new DSNs
