### ISSUE TITLE
Refactoring targeting_config_slug to use targeting_config

### ISSUE THREAD

**Issue by yashika-khurana** [mozilla/experimenter#7251]
We added `targeting_config` in the api end point-` experimentBySlug` and `targeting_configs` in `getConfig `Api end point,
which includes field label, value, description and application values, so now we can get rid of `targeting_config_slug `field in the api, need to modify usage of this field on frontend, removing field from backend and fixing test cases (both frontend and backend)

PR where this new field added: [https://github.com/mozilla/experimenter/pull/7228](https://github.com/mozilla/experimenter/pull/7228)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2402)

**Comment by jaredlockhart** [comment]
Let's close this and refile if it becomes an issue later.
