### ISSUE TITLE
Allow multi select for Channels

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7291]
With [https://mozilla-hub.atlassian.net/browse/EXP-2412](https://mozilla-hub.atlassian.net/browse/EXP-2412|smart-link) and [https://mozilla-hub.atlassian.net/browse/EXP-2447](https://mozilla-hub.atlassian.net/browse/EXP-2447|smart-link) as part of TCP rollout, experiments need to be cloned to have a single channel selected before review and launch. For each nimbus phase of the TCP rollout, the experiment might need up to 4 copies for 1) release 2) esr 3) beta 4) aurora.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2448)

**Comment by jaredlockhart** [comment]
Let's close this and revisit it if it comes again later.
