### ISSUE TITLE
Sort weekly results by week number

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#7295]
Weekly results table (Results > Results Summary > “show weekly data”) sort by the integer representation of the week number. Looks like it’s sorting the strings (“Week 1” -> “Week 10"  but should go “Week 1” -> “Week 2")

![image](https://user-images.githubusercontent.com/43795363/169390761-cea62cc8-011a-4858-9dd5-2fea9c5ad9da.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2451)

**Comment by jaredlockhart** [comment]
Is this still a real issue @mikewilli ?

**Comment by mikewilli** [comment]
Yes, this is still a bug for experiments with more than 9 weeks of results. Examples: https://experimenter.services.mozilla.com/nimbus/106-major-release-firefox-new-user/results and https://experimenter.services.mozilla.com/nimbus/106-major-release-firefox-existing-user-experience/results (I'm sure there are others)

**Comment by suhana832** [comment]
@yashikakhurana can I work on this ?

**Comment by yashikakhurana** [comment]
@suhana832 if you are outreachy applicant, this task is not marked for outreachy contribution, thanks

**Comment by nox1134** [comment]
Hi @yashikakhurana! I'd like to work on this issue. Can you guide me on where to begin and what I should change?

**Comment by mikewilli** [comment]
I'd take a look at the `TableWeekly` component in experimenter/experimenter/nimbus-ui/src/components/PageResults/TableWeekly/index.tsx. It looks like there's a function in there that's getting a list of the week indices (`getWeekIndexList`) but the sorting is probably string-based instead of number-based.

The easiest way to test is probably to write (or update) a unit test on the function to confirm the current behavior, and to confirm that it's fixed after any changes you make.

**Comment by nox1134** [comment]
I have successfully installed Node, Docker, Yarn, and NVM. However, when I run 'make check,' following error occurs:
`make check
docker buildx build --target test -f experimenter/Dockerfile -t experimenter:test experimenter/
[+] Building 7.2s (16/58)                                           docker:desktop-linux
 => [internal] load build definition from Dockerfile                                0.0s
 => => transferring dockerfile: 8.16kB                                              0.0s
 => [internal] load .dockerignore                                                   0.0s
 => => transferring context: 353B                                                   0.0s
 => [internal] load metadata for docker.io/library/alpine:3.12.0                    6.7s
 => [internal] load metadata for docker.io/library/python:3.11.1                    6.7s
 => [auth] library/python:pull token for registry-1.docker.io                       0.0s
 => [auth] library/alpine:pull token for registry-1.docker.io                       0.0s
 => CACHED [file-loader 1/3] FROM docker.io/library/alpine:3.12.0@sha256:185518070  0.0s
 => [internal] load build context                                                   0.3s
 => => transferring context: 289.10kB                                               0.3s
 => [system-builder  1/12] FROM docker.io/library/python:3.11.1@sha256:4d25a30d294  0.0s
 => CACHED [system-builder  2/12] RUN curl -sS https://dl.yarnpkg.com/debian/pubke  0.0s
 => CACHED [system-builder  3/12] RUN echo "deb https://dl.yarnpkg.com/debian/ sta  0.0s
 => CACHED [system-builder  4/12] RUN apt-get update                                0.0s
 => CACHED [system-builder  5/12] RUN apt-get --no-install-recommends install -y a  0.0s
 => CACHED [system-builder  6/12] RUN curl -o- https://raw.githubusercontent.com/c  0.0s
 => ERROR [system-builder  7/12] RUN . "/root/.nvm/nvm.sh" && nvm install 16.19.0   0.4s
 => CANCELED [file-loader 2/3] COPY . /experimenter/                                0.1s
------
 > [system-builder  7/12] RUN . "/root/.nvm/nvm.sh" && nvm install 16.19.0:
0.353 /bin/sh: 1: .: cannot open /root/.nvm/nvm.sh: No such file
------
Dockerfile:28
--------------------
  26 |     ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
  27 |     RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.3/install.sh | bash
  28 | >>> RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
  29 |     RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
  30 |     RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
--------------------
ERROR: failed to solve: process "/bin/sh -c . \"$NVM_DIR/nvm.sh\" && nvm install ${NODE_VERSION}" did not complete successfully: exit code: 2
make: *** [build_test] Error 1`

**Comment by eliserichards** [comment]
@nox1134 What does it say when you run `node -v`? Mine is saying `v16.19.0`, and it looks like that's what's erroring: 

```
 => ERROR [system-builder  7/12] RUN . "/root/.nvm/nvm.sh" && nvm install 16.19.0   0.4s
```

If yours says another version, you might need to do `nvm use 16.19.0`

**Comment by eliserichards** [comment]
@nox1134 If that still doesn't work, we might be able to help some more on [Matrix](https://wiki.mozilla.org/Matrix) (it's a little easier to chat there) 😄  We hang out in the [Nimbus channel](https://matrix.to/#/#nimbus:mozilla.org)
