### ISSUE TITLE
Wording changes in the Experimenter to match the flow changes

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#732]
Experimenter was originally written for a flow where there was an intake team doing reviews and high-touch shepherding.

Now projects are starting with the Data Science team.  That means the data should be coming in with more accurate hypotheses and branching designs.  Advising and mentoring is possibly needed after Data Science discussion, on the intricacies of what can be tested and how using Normandy pref-flips and add-ons.

Also, the responsibility of making sure all needed sign-offs and clearance has been obtained - has moved from the experiment intake team, entirely to the experiment requester.

when the red words have been removed FROM THE ENTIRE WORDING UPDATE SECTION - it is done with final reviews and ready to be implemented.  https://docs.google.com/document/d/1LknFtapAZ2OQtXzufRlgwwHjDrkCrQHucXgBTzDlZ5g/edit#heading=h.1b9n697bom2b

@jaredkerim

**Comment by jaredkerim** [comment]
I think this is closed by other tickets that have been completed.
