### ISSUE TITLE
Handle auth refresh in integration tests

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7321]
Remote Settings has a behaviour where refreshing a page when you're logged in will kick you back into the login screen, and it seems to be intermittent or unpredictable so it's causing intermittency in the integration tests.  Let's update the tests to handle this case and instead of just refreshing a page, do the entire login and navigate flow every time we need to refresh the page.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2463)

**Comment by jrbenny35** [comment]
What if we just delay the refresh instead of doing it ever 1 second. Something like every 10 seconds. I was doing this and it seemed to help

**Comment by jaredlockhart** [comment]
Okay so this is proving to be intractable, so let's switch tactics entirely and bypass the Remote Settings UI altogether in favour of calling its API directly, filed here: https://github.com/mozilla/experimenter/issues/7326
