### ISSUE TITLE
Consider using Python 3's f-Strings to clean up nimbus targeting configurations

### ISSUE THREAD

**Issue by lmegviar** [mozilla/experimenter#7322]
While adding new advanced targeting, we found defining variables for formatted strings to be error prone. Let's consider taking Ed's suggestion below to use Python 3's f-Strings for nimbus targeting configurations. If we go that route, we may also want to consider making some of the variable names clearer so that the targeting strings are still easy to read and comprehend at a glance.
________________________________

I haven't used it myself, but looks like there's some existing usage, e.g., https://github.com/mozilla/experimenter/blob/c283826781dde5f81bc51c6e564973fde459fd31/app/experimenter/experiments/constants/nimbus.py#L356-L357

_Originally posted by @Mardak in https://github.com/mozilla/experimenter/pull/7311#discussion_r882148168_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2466)

**Comment by jaredlockhart** [comment]
Yes I love this idea 👍

**Comment by Mardak** [comment]
Just to follow up, I have now used it, and it was great! 😜 
https://github.com/mozilla/experimenter/blob/ccb993a97803d6290e3e26d39792a1b061dfdab0/app/experimenter/experiments/constants/nimbus.py#L622-L623
