### ISSUE TITLE
Link to email templates - pre-populated if possible for QA and Relman engagement

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#733]
We want people creating new studies to engage correctly and efficiently with other teams.  To do that we should provide them with guidance on when and how.  For QA and Release Management - there are at least 2 points where sending an email is the normal way to engage.

1. QA - requesting QA via a PI-request email
2. Relman - letting them know of intent to ship

Both of these emails it is important to:
1. Ask Early enough that QA and Relman have time to do what is needed on their end.
2. Not ask too early - for projects that fail to launch, we don't want to create the work/noise unnecessarily.
3. Provide accurate information in a format easy to consume.

P1: we have a link in the checklist that takes them to a template form for each type of request.  
P2: that template is populated with the correct information from Experimenter.

I'm not sure what is possible.  I'd love for the P2, but can break that into a separate bug - if we're talking "what can be done ASAP".

Here are the templates - WHEN THE RED IS GONE FROM THIS WHOLE SECTION - THE COPY IS READY TO IMPLEMENT.  https://docs.google.com/document/d/1LknFtapAZ2OQtXzufRlgwwHjDrkCrQHucXgBTzDlZ5g/edit#heading=h.ecyy351wvp01

@jaredkerim

**Comment by jaredkerim** [comment]
Links were added in #745
