### ISSUE TITLE
The label and the Feature configuration toggle overlap for some window sizes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7367]
**[Prerequisites]:**

* Have a Draft experiment open.

**[Steps to reproduce]:**

1. Open the “Branches” section of the experiment from prerequisites.
1. Resize the browser window to a smaller size (~50%).
1. Observe the “Feature is” toggle.

**[Expected result]:**

* The “Feature is” label and the toggle do not overlap.

**[Actual result]:**

* The “Feature is” label and the actual toggle slightly overlap for some window sizes.

**[Notes]:**

* Attached is a screenshot of the issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-2494)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24657">Screenshot 2022-06-03 at 16-39-53 unfini Copy - Treatment A Rollout – Branches Experimenter.png</a>

**Comment by yashikakhurana** [comment]
closing this issue as fixed in this https://github.com/mozilla/experimenter/pull/7590 and in improved ui

**Comment by data-sync-user** [comment]
➤ Maria Heres commented:

I have verified that the issue is no longer reproducible. The toggle is no longer displayed. Tested on Stage using Firefox Nightly 112.0a1 (Build ID: 20230308094825) -  Windows 10.
