### ISSUE TITLE
Breaking the Population Section into Normandy friendly sections

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#739]
Right now the Population section is one big text entry field.  Ideally we still have a free text area - but put the common study aspects separately.  Adding drop down menus with properly formatted options. 

Talking to UX soon about what we are trying to accomplish https://docs.google.com/document/d/1kciKwYv1hbN3wFZQsT4x9nWmDlKpQU5JpKawV5Yf0qk/edit#heading=h.pwe6psoeskcc

**Comment by mostlygeek** [comment]
We could expose a UI that creates Normandy FilterObjects directly in Experimenter.  Anything outside of FilterObject capabilities we can keep as plain text description.   This would help reduce interpretation / ambiguity in translating plain text to JEXL.

**Comment by jaredkerim** [comment]
Closing this in favour of yet to be filed tickets to reorganize all the form fields.
