### ISSUE TITLE
Some results metrics missing titles

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7413]
Now that https://github.com/mozilla/experimenter/pull/7392 has landed all the missing analyses are coming back 🎉 

But it looks like some of them are missing titles, example from https://experimenter.services.mozilla.com/nimbus/firefox-suggest-history-vs-offline/results

![image](https://user-images.githubusercontent.com/119884/173928975-67a21247-3c42-45a9-94d8-c69d545e7ab4.png)

The tooltips still show the correct descriptions so there's probably something simple we're missing.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2518)

**Comment by data-sync-user** [comment]
➤ Mike Williams commented:

The metadata in the API response for the metrics with missing names is returning empty string for friendly_name field, which presumably explains why the UI is showing a blank.

"autofill_count":{
  "description":"Number of autofills selected from the urlbar",
  "friendly_name":"",
  "analysis_bases":["enrollments"],
  "bigger_is_better":true
}Next step: figure out why friendly_name is empty.

**Comment by data-sync-user** [comment]
➤ Mike Williams commented:

Confirmed that the friendly_name is empty in GCP bucket ( https://console.cloud.google.com/storage/browser/_details/mozanalysis/metadata/metadata_firefox_suggest_history_vs_offline.json;tab=live_object ).

**Comment by data-sync-user** [comment]
➤ Mike Williams commented:

OK, I think this is just missing from the metadata and needs to be filled in. A number of outcomes are missing the friendly_name field here ( https://github.com/mozilla/jetstream-config/blob/main/outcomes/firefox_desktop/firefox_suggest.toml#L12 ), which I think is where they should be defined. 

Anna Scholtz Jared Lockhart Can one of you please confirm?

**Comment by data-sync-user** [comment]
➤ Anna Scholtz commented:

friendly_name is optional in the config files. But would it be helpful if jetstream auto-fills the friendly_name field based on the metric slug (for example bookmark_count would become Bookmark Count) when exporting the metadata?

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

Aha!  Missing friendly names.  Yep that’d do it.  Okay so we can totally derive friendly names from metric names, should that happen in Jetstream or Experimenter?  I think either’s fine?  Which do you prefer Anna Scholtz Mike Williams ?

**Comment by data-sync-user** [comment]
➤ Anna Scholtz commented:

This can be handled in Jetstream. Mike is having a go at it.

**Comment by data-sync-user** [comment]
➤ Mike Williams commented:

I re-ran jetstream against the experiment mentioned in this ticket and all looks good.
