### ISSUE TITLE
QA for Sticky Targeting

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7422]
Once we have the sticky targeting implemented we should qa that it behaves correctly in both desktop and the SDK.

## Acceptance Criteria
* Users can mark an experiment as sticky from the Audience page
* Non-Sticky experiments do not include a sticky expression in the JEXL
* Sticky experiments include a sticky expression in the JEXL that applies to some targeting criteria and not others
* Clients enrolled in a sticky experiment do not unenroll if the enrollment targeting criteria no longer become true
* Clients enrolled in a sticky experiment do unenroll if the continuous targeting criteria no longer become true

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2528)

**Comment by jaredlockhart** [comment]
Sticky targeting is done and live now, closing this.
