### ISSUE TITLE
Update integration tests to include all targeting fields

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7444]
When we run the integration tests against advanced targeting JEXL expressions, we should also set all the built in fields so that they are included in the test, that way we’re validating both the built in JEXL as well as the custom expressions added by users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2539)

**Comment by data-sync-user** [comment]
➤ Benjamin Forehand Jr. commented:

Is this specifically for the rust integration tests?

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

Benjamin Forehand Jr. for both desktop and mobile so that we stress test both the built in JEXL targeting expressions as well as the user supplied custom ones.

**Comment by jaredlockhart** [comment]
This is done now.
