### ISSUE TITLE
Link in jetstream override warning is out of date + need one warning word changed

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7445]
The warning on the results page about a jetstream override points to `#cirrus` which is now defunct.  It should point to `#ask-experimenter`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2543)

**Comment by shell1** [comment]
Also when making that change... please change the warning from 

"The results shown on this page are from an analysis ran with at least one experiment override that affects only the analysis, meaning experiment data on the Summary page will not reflect this."

To replace the word "data" with "details and description"...

"The results shown on this page are from an analysis ran with at least one experiment override that affects only the analysis.  The original experiment details and description on the Summary page will not reflect this change."

**Comment by jbrannigan89** [comment]
Hi, i just created a pull request for this.  pls let me know if I've made any errors I'm fairly new to contributing to projects.  Thanks.
