### ISSUE TITLE
Add more SDK app contexts with multiple values for each variable

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7447]
The operator short circuiting in different JEXL runtimes can cause the right hand side of an `||` operation to not be evaluated at all, which means if they appear in our targeting JEXL expressions and the supplied app contexts don't include values that will cause the left hand operand to evaluate to `false` we'll never test the right hand side.  We should modify our supplied test app contexts [here](https://github.com/mozilla/experimenter/blob/main/app/tests/integration/nimbus/app_contexts.json) to include more possible values, at the very least for the values in

```js
              "custom_targeting_attributes": 
              {
                "is_already_enrolled": true,
                "days_since_update": 1,
                "days_since_install": 1
              }
```

I think we can get away with each of `false|true` for boolean fields and `0|1` for integer fields.  Let's try that and we can evaluate further later if we find something more.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2548)

**Comment by data-sync-user** [comment]
➤ Benjamin Forehand Jr. commented:

This should be done after https://mozilla-hub.atlassian.net/browse/EXP-2553 ( https://mozilla-hub.atlassian.net/browse/EXP-2553|smart-link )

**Comment by jaredlockhart** [comment]
Actually through testing I determined this won't actually force the evaluator to evaluate both sides of an `||` clause, closing this in favour of https://github.com/mozilla/experimenter/issues/7464
