### ISSUE TITLE
QA Request Email

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#746]
Notes for Jared:  Some teams may have their own process with QA and have already created QA request.  They can just check the box.  If they do not - they should click "send email".  

The requested template and experimenter fields that should pre-populate is in the doc - but I put it below too: https://docs.google.com/document/d/1LknFtapAZ2OQtXzufRlgwwHjDrkCrQHucXgBTzDlZ5g/edit#heading=h.ecyy351wvp01

_help should link here:  https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-QArequested.
email should say...._

To: pi-request@mozilla.com 
cc: {Creator and anyone else we know about from experiment}
From:  {either Experimenter Bot (if possible) or use experiments-review@mozilla.com}
Summary: SHIELD Study QA request: {SHIELD_study_name} on Firefox {version} {channel}

Hi QA,

Please reach out to the person(s) on cc: here for any questions, details, or discussion.  The details in this email are from Experimenter.

**Project name**: {SHIELD_study_name}
        **Experimenter Bug**: {Experimenter bug number}
        **Experimenter project**:{link to specific experimenter project}
        **Study owner**:  {experiment requester}
        **Description**:  {Short Description} 
**Timeline & Channel**: {version} {channel}
        **Intended study dates**: {proposed start date} - {proposed end date} 
**Percent of Population**: {percent of population}
**Platforms**: {platforms}
**Locales**: {Locales and Geographic areas}
**Testing instructions**:  {testing instructions}
**Test builds** (when applicable): {test builds}
        **Meta Bug**: {Feature Meta Bug}
**Related links**: {links to related work}        
**Risk and Complexity**:  {risk - only if it there is info in the box because one of the radial buttons was "yes"}

Thank you!!

**Comment by jaredkerim** [comment]
This is blocked on https://github.com/mozilla/experimenter/issues/742

**Comment by shell1** [comment]
I made a mistake at the end of this email template - and grouped Risk and Technical Complexity together.  The last item that is populated should be....

**Risk**: {Risk Box - only if it exists}
**Technical Complexity**: {Technical Complexity Box - only if it exists}

**Comment by shell1** [comment]
starting for Firefox 68 - QA will now only be accepting new QA requests in Jira instead of the PI request emails. So we will NOT be automating the creation - but just updating the guidance. 

this is the link to the Jira portal.  S https://moz-pi-test.atlassian.net/servicedesk/customer/portal/9
