### ISSUE TITLE
QA for rollout live editability

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7463]
# What do we want to test?
1. **Rollouts** are the only thing editable while **Live**

   * This will make publish_status=Dirty

2. A live rollout can be edited from: Summary page → Audience (left sidebar) → change population percent (“Percent of clients”) → Save

   * It can only be edited while **LIVE** (not Complete, review, archived, etc)

3. The **population percent** (“Percent of clients”) is the only field that is editable for live rollouts

4. When a live rollout has been edited (change population percent (“Percent of clients”) → Save), it is clear that there are unpublished changes from:

   * the red status pill next to “Timeline” that says “Unpublished changes” 
   * the “Request update” button should appear in the “Actions” section (with “End enrollment” and “End experiment” buttons)

5. The user can make as many edits as they want (and save) before they request an update.

6. When an update is requested (“Request update” button in the “Actions” sections), the user can go through the familiar review flow (approve/reject in Experimenter, then approve/reject in Remote Settings). All of the following scenarios are possible:

   * Request update → Approve in Exp → Approve in RS
   * Request update → Approve in Exp → Reject in RS
   * Request update → Reject in Exp

7. Make a live rollout with a specific application, channel, feature value, and advanced targeting. Make another rollout with the same application, channel, feature value, and advanced targeting, and see that the warning pops up: [https://mozilla-hub.atlassian.net/browse/EXP-3198](https://mozilla-hub.atlassian.net/browse/EXP-3198|smart-link) 

- - -
The following scenarios are possible, with each value edited, saved, requested update, approved, and launched to the user:

1. Rollout with population percent = 

   * 0%
   * 50%
   * 75%
   * 100%

2. Rollout with population percent = 

   * 0%
   * 100%
   * 0%
   * 100%

3. Rollout with population percent = 

   * 0%
   * 50%
   * 100%
   * 50%

4. Rollout with population percent = 

   * 100%
   * 50%
   * 0%

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2565)

**Comment by jaredlockhart** [comment]
Coming soon!

**Comment by data-sync-user** [comment]
➤ Elise Richards commented:

I added this description on the Acceptance Criteria on the Epic. Closing this in favor of of that 🙂
