### ISSUE TITLE
Disable the "enabled" switch in Web UI when targeting Fx 104+

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7466]
Firefox 104 is removing support for Feature.enabled, so recipes targeting it should not use the Feature.enabled flag.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2576)

**Comment by jaredlockhart** [comment]
Let's add a check to the review serializer that 'enabled' can't be false for desktop 104+
