### ISSUE TITLE
Add Jetstream analysis date/time to Results page

### ISSUE THREAD

**Issue by mikewilli** [mozilla/experimenter#7474]
Idea is to give additional context about the information shown on Results page and the decisions that were made off of this info.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2580)

**Comment by scholtzan** [comment]
To determine the timestamp, there are two different options that come to mind:
1) we can use the timestamp of the metadata file
2) jetstream can add the timestamp to the metadata

Option 2 is probably more robust, but would require some jetstream changes.
