### ISSUE TITLE
Replace status change messages with status labels

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#748]
We have this set of descriptions to describe status changes but we can just as easily use the status label in the change log and then remove those labels altogether, I think that simplifies things.

**Comment by peterbe** [comment]
@jaredkerim If you say "Fixes #12345" as the first line of the git commit *body* (aka. the PR description) then, GitHub will automatically link to the PR from the issue. 

Granted, from [individual commits](https://github.com/mozilla/experimenter/commit/3a5b2d4450cccfe584d5ccea3914f3b323342b82) one can find the PR URL if you go to the commit. But I don't know how that works with rebasing.

**Comment by jaredkerim** [comment]
I'm reopening this, I changed my mind, I don't think this is an effective solution.  This means that every message for creating/editing a draft will just look like 'Set Status: Draft' which isn't actually helpful.  We should probably revert this and just add the more status messages to account for changes that don't currently have a message.
