### ISSUE TITLE
Change text of the help for sticky enrollment

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#7488]
![width=200,height=183](https://user-images.githubusercontent.com/8192232/177565729-21a17e48-b337-45b5-b87a-75405c793e57.png)

If asked if I want "Clients remain enrolled until the end of the experiment" -my answer would be "of course I do"

change to...

* Only click if you have discussed the need for clients to remain enrolled in the experiment EVEN IF they become disqualified based on initial enrollment criteria."

Let's also make this secondary text below the checkbox text instead of in parentheses 

(opening new issue for this:) We should add a link “learn more” to an FAQ for enrollment or targeting

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2587)

**Comment by jaredlockhart** [comment]
@shell1 One thing we realized is sticky targeting must be required for any first run targeting, so that messaging doesn't exactly work.  What do you think?

**Comment by shell1** [comment]
hmm... let's assign this one to me to look at after i get back from vacation.  I think we should understand more the behavior of sticky and not - and talk with DS about what the behaviour should be.  sticky could possibly become the default - and there be an option to make unsticky a very unlikely to need option (so could hide the UX some).

**Comment by shell1** [comment]
this was resolved.  thank you!
