### ISSUE TITLE
GraphQL error for spotlight experiments + private browsing mode experiment

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#7492]
Seeing a GraphQL error when trying to view results for several 'spotlight feature' experiments https://experimenter.services.mozilla.com/nimbus/?tab=completed&applications=DESKTOP&allFeatureConfigs=DESKTOP%3Aspotlight and this non-spotlight one https://experimenter.services.mozilla.com/nimbus/firefox-focus-pbm-fx100/results

![image](https://user-images.githubusercontent.com/8192232/177805555-857c0f48-594b-43bd-80f7-ab724c950e82.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2592)

**Comment by mikewilli** [comment]
See issue #7489 and related PR #7490 -- that issue looks the same and the PR should fix these experiments as well.
