### ISSUE TITLE
Move loading external configuration files into an automated PR step

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7496]
Presently, we load external configuration files for

1) Feature manifests from external client repos
2) Jetstream configs from jetstream-config repo

at container build time.  However, errors in these files can result in any of the following

1) PRs breaking in CI before merging regardless of whether the PR code is healthy
2) Deploys breaking after merging regardless of whether the main code is healthy
3) Production servers breaking at runtime regardless of whether the main code is healthy

This means any stage of our workflow can break because of an external error that is not fixable by any process in Experimenter or its contributors.

To prevent this from happening in the future, we should move these external configuration fetching steps into a different workflow like so:

0) Local healthy copies of all external configuration files live in the Experimenter repo
1) A change to a configuration file lands in an external repo
2) The change is automatically detected and a PR is automatically created against the copies stored in the Experimenter repo
3) This PR step will catch any errors introduced in changes to those configuration files that would break some stage of the Experimenter test/deploy/live cycle
4) This PR can be automerged if it passes CI

This way we can separate code changes and configuration changes so that a breakage in one does not prevent deploying the other.

As part of this change, we should move the step that parses the desktop feature manifest files for externally linked resource schemas and fetches them out of the startup task that loads feature configurations at runtime, and into the container build stage so that we reduce the risk that breaking changes are introduced at runtime.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2596)

**Comment by jaredlockhart** [comment]
Filed this to add github creds to circle: https://mozilla-hub.atlassian.net/browse/DSRE-897

**Comment by data-sync-user** [comment]
➤ Benjamin Forehand Jr. commented:

I want to take this one

**Comment by jaredlockhart** [comment]
Okay so in more detail about step 3:

1) First remove [these .gitignore rules](https://github.com/mozilla/experimenter/blob/main/.gitignore#L101-L105) so that the jetstream config and manifest files are tracked by git
2) Add a new scheduled circle ci task that runs every hour that does the following
3) Runs `make jetstream_config feature_manifests` to fetch the latest versions of the config files
4) Run `git diff` to see if any changes are detected and if there are
5) Create a new git branch
6) Commit the changes with some helpful message
7) Use the [GitHub CLI](https://github.com/cli/cli) to create a PR using the auth token available in the CircleCI environment as `GH_TOKEN`

Then, some change will land in a remote repo, shortly later a PR will just show up with the changes, and we can rely on the integration tests to detect that everything starts normally and healthily.

**Comment by jaredlockhart** [comment]
Oh it occurred to me we should actually do this in two steps.  Add them to the repo first in https://github.com/mozilla/experimenter/issues/7518 and then add the CI task separately in this.
