### ISSUE TITLE
Update atomicwrites dependency to 1.4.1

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#7497]
The dependency `atomicwrites` has published a new version and removed all old versions. We are currently using 1.4.0, so we need to update to the latest versions so we aren't breaking CI.

https://github.com/untitaker/python-atomicwrites/issues/61

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2597)

**Comment by jaredlockhart** [comment]
The old versions were restored: https://github.com/untitaker/python-atomicwrites/issues/61#issuecomment-1179538430
