### ISSUE TITLE
The error messages are not dismissed after adding the missing details if the section is accessed from "Missing details" 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7569]
**[Prerequisites]:**

* Have a Nimbus draft opened **with no feature selected**
* The "Branches" section is not completed and it is displayed in the "Missing details" section.

**[Steps to reproduce]:**

1. From the "Missing details" section click the "Branches" link.
1. Select a feature from the dropdown.
1. Focus on another field and observe the behavior.

**[Expected result]:**

* The "You must select a feature configuration from the drop-down." message disappears and the field has a green border.

**[Actual result]:**

* The "You must select a feature configuration from the drop-down." message is still displayed and the field still has a red border.

**[Notes]:**

* This issue is reproducible for all the mandatory fields that are not completed yet if they are accessed from the "Missing details" section.
* However, from what I noticed only the "feature configuration" dropdown border is not changed into the green color. The rest of the mandatory fields gain a green border after are completed, but the error message is still displayed.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-2654)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/27078">error messages do not disappear.mp4</a>

**Comment by yashikakhurana** [comment]
@eliserichards I am not able to replicate this, do you? if not lets close this \o/
