### ISSUE TITLE
Experimenter API failing during jetstream rerun

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7573]
A `jetstream rerun --argo` command (when run in Argo on k8s) launches a pod for every day of analysis that needs to be conducted. These pods then proceed to each make a GET request to the Experimenter API ([https://experimenter.services.mozilla.com/api/v6/experiments/](https://experimenter.services.mozilla.com/api/v6/experiments/)). Recently, the API has started to return 502 errors in this situation. This does not _appear_ to be affecting the daily Jetstream jobs for in-flight experiments, it _appears_ to be localized to jetstream-config CI jobs and manually launched `jetstream rerun --argo` jobs.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-2665)

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/pull/7574 not sure why this didn't close?
