### ISSUE TITLE
Launch to Preview Now button showing in odd place

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7575]
<img width="659" alt="Screen Shot 2022-08-08 at 3 11 34 PM" src="https://user-images.githubusercontent.com/119884/183495644-cb4bfac2-15cd-4789-b376-f5af1d8c2498.png">

I don't remember this button being there but blame says it's 2 years old, I don't know why it's showing now, or in that spot, but I don't think we need that button at all so let's take it out?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2669)

**Comment by heres-maria** [comment]
@jaredlockhart Could we talk about this during a QA sync meeting before this change is implemented?

**Comment by jaredlockhart** [comment]
@heres-maria points out that having more buttons that encourage people to launch to preview encourages people to QA their experiments before launching, and if we take that button out, we may lose some of that encouragement, so as we're thinking about what to do with this very weirdly placed button, we should keep in mind ways to encourage people to preview/QA their experiments before launching.

**Comment by eliserichards** [comment]
For now, let's move the "Launch to Preview Now" button to a new line underneath the red text, and make the color match the "Request Launch" button color.

**Comment by sudarsan2k5** [comment]
Hi @eliserichards I would like to work on this. could you please assign this issue to me.

**Comment by eliserichards** [comment]
@sudarsan2k5 I will assign this to you! Tag me if you have any questions 👍

**Comment by yashikakhurana** [comment]
since the new ui have a good placing 
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/25848231/223285240-aead7e30-638f-4b54-add2-bd499cf783d5.png">
@jaredlockhart can we close this issue now?

**Comment by jaredlockhart** [comment]
This is done now.
