### ISSUE TITLE
Move camelCase fields from graphql to serializers

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7599]
The GraphQL framework we are using (Graphene) will automatically convert snake_case fields to camelCase fields, so the fields in the serializer are all in snake_case but are referenced in the frontend by camelCase.  To prepare for removing the GraphQL layer, let’s move the camelcasing back a layer to the serializer layer.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2686)

**Comment by jaredlockhart** [comment]
Reopening after this was reverted in https://github.com/mozilla/experimenter/issues/7747

Let's address the following in reapplying this change:

https://github.com/mozilla/experimenter/issues/7746
https://github.com/mozilla/experimenter/issues/7744
https://github.com/mozilla/experimenter/issues/7743
https://github.com/mozilla/experimenter/issues/7739
