### ISSUE TITLE
Warn for removed features

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7605]
A feature may be removed from a feature manifest in which case we should warn users targeting it that it has been removed and may no longer be supported.  If Experimenter had a strong sense of the release schedule it could know past which version it is no longer available, but in lieu of that we should at least warn users that the feature has been removed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2692)

**Comment by yashikakhurana** [comment]
@jaredlockhart can we close this issue, as we are not showing removed features to the users?
