### ISSUE TITLE
Update Results not available warning message to point to currently used location

### ISSUE THREAD

**Issue by mikewilli** [mozilla/experimenter#7611]
#cirrus is no longer used, we should point to #ask-experimenter instead

![image](https://user-images.githubusercontent.com/102263964/185491546-b64f779c-c730-405a-a39c-a76153ba9c90.png)

See #7445 for related update

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2702)

**Comment by eliserichards** [comment]
already done: https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/AppLayoutSidebarLaunched/index.tsx#L216
