### ISSUE TITLE
Add a reference to #ask-experimenter slack

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#764]
We have a new channel on slack called #ask-experimenter for general experiment process questions, we should put a little message somewhere on the site that mentions it so people know to go there.

**Comment by shell1** [comment]
In Header where ever it's easy to add.  Idea is next to "Leave Feedback".  Even if just directions on channel name (believe hard to connect to Slack directly - but give them the channel name).

**Comment by pdehaan** [comment]
Slack does have a Web UI, but not sure if https://mozilla.slack.com/messages/CF94YGE03/details/ is very helpful, or if everybody uses the Slack desktop client and doesn't want to log into web-ui to join the channel.

**Comment by peterbe** [comment]
Note-to-self; These instructions work: https://api.slack.com/docs/deep-linking

GitHub won't turn this into a link but I'm using: slack://channel?id=CF94YGE03 and it seems to work on macOS.
