### ISSUE TITLE
an experiment "stuck" in staging - from getting to "save sign-offs"

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#767]
Just troubleshooting an odd scenario to see if it's a real issue.  Don't actually need this particular staging experiment test. 

Jessilyn Davis and me managed to get an experiment "stuck" in staging - so that even with all required checkboxes checked - it won't "save sign-offs" so we can't get to "ready to ship".

I had created initially - and played with state - and then had Jessilyn use it to demo and it was stuck.

I didn't move to draft or try other stuff to get back into a good state.  Reporting before messing with.

https://experimenter.stage.mozaws.net/experiments/junk-testing/

**Comment by jaredkerim** [comment]
Yeah you can't move to 'ready to ship' unless you complete all the sections, the risks and testing aren't filled out.  I used to have a message right under the button that indicated there was still sections to be completed, I don't know why I took that out I should put it back so it's clearer that the form isn't finished being filled out.

**Comment by shell1** [comment]
doh.  thank you.  I can just let folks know that.  likely only common to hit while we are doing testing stuff.
