### ISSUE TITLE
QA link in legacy returns 'Access Denied'

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7678]
The QA ticket link in legacy is returning access denied in jira so we probably need to update that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2751)

**Comment by jrbenny35** [comment]
Which link exactly? I see 2 
![image](https://user-images.githubusercontent.com/5751892/188744880-bad3636d-03f4-4baf-a16e-73b7937a57ff.png)

**Comment by jaredlockhart** [comment]
Legacy is nearly EOL, let's close this.
