### ISSUE TITLE
Does Staging connect to live Bugzilla?  if yes, would we be good changing that or marking those bugs somehow

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#768]
Just checking as Emma Humphries mentioned there is a bugzilla staging.  Do we want experimenter staging connecting to a bugzilla staging instead of creating live Bugzilla tickets?  

Or leave as is and just mark ones from Staging so we can clear those out easily.

I'm fine going through and closing all the junk ones every few days - but maybe we should put something in the title of any created from Staging like "STAGING TEST" so we know which ones shouldn't get into RelMan tracking :)

**Comment by jaredkerim** [comment]
Staging Experimenter does connect to Staging Bugzilla, so we don't have to worry about cleaning anything!

Example: 

https://experimenter.stage.mozaws.net/experiments/i-know-what-i-want/

https://bugzilla.allizom.org/show_bug.cgi?id=1488910
