### ISSUE TITLE
Add a creation_date field to NimbusExperiment

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7680]
Let's add a creation_date datetimefield to NimbusExperiment with auto_now_add=True and then we can default order the model by the pair of `('_start_date', 'creation_date')` for the landing page so we don't have to do any joins on the changelog model.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2752)

**Comment by yashikakhurana** [comment]
if the only purpose was for the landing page, we have added `_updated_date_time`, do we still want this? @jaredlockhart

**Comment by jaredlockhart** [comment]
Yeah you're right we don't need this anymore.
