### ISSUE TITLE
Preview Recipe JSON should expand JSON on Summary page

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#7697]
Clicking on "Preview Recipe JSON" from the Summary page sidebar scrolls you down to the JSON. When this happens, we should assume that the user wants to see the full JSON and automatically expand ("Show more") the JSON preview

https://user-images.githubusercontent.com/43795363/188969372-4eb50b61-e47c-41bb-a164-d42e6c5eb262.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2766)

**Comment by yashikakhurana** [comment]
blocked by-https://github.com/mozilla/experimenter/issues/6801

**Comment by Avi-88** [comment]
Hello @yashikakhurana ma'am , I would like to work on this, if possible please assign it to me , thanks

**Comment by Avi-88** [comment]
Hi @KramStyles , I'm still working on this, I'm done with the changes just need to fix some broken tests. Feel free to look for other open issues in the mean time good luck :)
