### ISSUE TITLE
Add link to GitHub repo in footer?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#770]
It may make for marginally easier bug reporting if there was a GitHub link in the footer area (where we currently say "(c) Mozilla Corporation 2018").

**Comment by leplatrem** [comment]
Should there be a `contribute.json` too?

https://www.contributejson.org

**Comment by pdehaan** [comment]
FWIW, I did find the "Leave Feedback" (https://github.com/mozilla/experimenter/issues/new) link in the header. /shrug 



> Should there be a `contribute.json` too?

I'd say probably not, since this is an internal-only system behind an LDAP login.

**Comment by jaredlockhart** [comment]
Hasn't come up as necessary so far, so closing.
