### ISSUE TITLE
Filter "Owners" dropdown by people w/ at least 1 active (or archived) experiments?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#771]
I was a bit surprised to see my name in the "Owners" dropdown (since I've never created an experiment in stage/production).
Currently it looks like production has about 252 `<option>` tags for Owner in the filter dropdown, but it may be easier if we only showed the names/emails of people who have at least 1 current/archived experiment, since searching by owner will always return 0 results otherwise.

**Comment by jaredkerim** [comment]
Good idea.

**Comment by shell1** [comment]
we are closing out a bunch of these original "we could possible do x" UX enhancements.  Mid-year after 2 quarters of development - we will look at the UX and see all-up what changes will be truly helpful to the users.  Don't want a bunch of ideas in the backlog that might get worked on individually - and conflict with more recent changes.  We don't want anything to delay the major feature development that is in progress.  We'll work out a high impact, many UX improvements plan based on feedback from the evolved state of Experimenter.
