### ISSUE TITLE
Add Mobile First Run Targeting

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7713]
Let's add a new targeting config for mobile first run that uses the boolean property that Fenix and Firefox iOS expose that is true on the first session, and then set both sticky and first run options on the targeting config to true.

Blocked on https://github.com/mozilla/experimenter/issues/7712

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2775)

**Comment by yashika-khurana** [comment]
@eliserichards whenever you get a chance, could you help me with this :)
