### ISSUE TITLE
Create integration tests for rollouts workflow

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#7721]
Presently, we don't have any integration tests for rollouts. Let's make some!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2779)

**Comment by data-sync-user** [comment]
➤ Benjamin Forehand Jr. commented:

Which workflow is this exactly?

**Comment by data-sync-user** [comment]
➤ Benjamin Forehand Jr. commented:

Done by Elise Richards in https://mozilla-hub.atlassian.net/browse/EXP-3157 ( https://mozilla-hub.atlassian.net/browse/EXP-3157|smart-link )
