### ISSUE TITLE
500 on prod: "all_english"

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7738]
Just saw this on prod, probably a deleted targeting config reference.

https://experimenter.services.mozilla.com/nimbus/first-aboutnewtab-nightly-aa/results

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2787)

**Comment by data-sync-user** [comment]
➤ Benjamin Forehand Jr. commented:

I cant even find this experiment in the database

**Comment by jaredlockhart** [comment]
Fixed through the admin.
