### ISSUE TITLE
Use "placeholder" text for Objective & Analysis textarea fields?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#774]
Currently it looks like the `<textarea>` fields are just using placeholder text, which means I can submit the forms without entering the values.

It also means that the "Objectives" section on the experiment page have the following text:

> You must complete the objectives form before you can launch your experiment.
> You must complete the analysis form before you can launch your experiment.

Not sure if it'd be easier to change from this:

```html
<textarea name="objectives" cols="40" rows="20" class="form-control" required=""
  id="id_objectives">What is the objective of this study?  Explain in detail.</textarea>
```

To this:

```html
<textarea name="objectives" cols="40" rows="20" class="form-control" required=""
  id="id_objectives" placeholder="What is the objective of this study?  Explain in detail."></textarea>
```

This way the field doesn't have any actual content by default and the `required=""` attribute will enforce the client side check and display the "Please fill out this field" tooltip and add the red border on the form field.

**Comment by jaredkerim** [comment]
Yeah I designed it this way on purpose to be able to fold multiple questions into a single text box, because the questions were fluctuating so much I didn't want to have to change everything every time.  It's clunky and not super webby and this is a good optimization, I think i'll leave this open in the backlog for a future time when we can treat text input fields more intentionally on a per question basis.

**Comment by shell1** [comment]
we are closing out a bunch of these original "we could possible do x" UX enhancements. Mid-year after 2 quarters of development - we will look at the UX and see all-up what changes/clean-up will be truly helpful to the users. Don't want a bunch of ideas in the backlog that might get worked on individually - and conflict with more recent changes. We don't want anything to delay the major feature development that is in progress. We'll work out a high impact, many UX improvements plan based on feedback from the evolved state of Experimenter.

this one in particular - we have to go back through all the text boxes and look at default text and handling.  just don't one change being made after we get to our next state - when it should be "update all areas to be consistent".
