### ISSUE TITLE
Risks field isn't always visible while editing

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#775]
### Steps to reproduce

Go to https://experimenter.stage.mozaws.net/experiments/prettyfancyesperiment/edit-objectives/

Note that this fake study has a "Yes" for "Does this need to be shipped outside the normal release process?"

Click the "Save Draft and Continue" button. Note that the only visible fields are the 5 yes/no questions, and the "Test Plan" textarea.

Set the "Does this need to be shipped outside the normal release process?" radio button to "No", then back to "Yes". Note that the "Risks" section now re-appears.

### Expected results:

Since the study has a "Yes" answer, it should have the "Risks" textarea immediately without having to toggle the radio buttons.

**Comment by jaredkerim** [comment]
I fixed this in #829
