### ISSUE TITLE
Add new custom targeting for an upcoming experiment

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#7756]
create new targeting to avoid these two normandy experiments:

https://experimenter.services.mozilla.com/experiments/search-experiment-measuring-the-impacts-of-alternative-default-search-providers/
https://experimenter.services.mozilla.com/experiments/search-experiment-measuring-the-impacts-of-alternative-default-search-providers-part-2/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2803)

**Comment by shell1** [comment]
Chris bellini is going to confirm before we start this.

**Comment by cbellini** [comment]
We'll be ending potentially-conflicting experiments before launching related new ones, so this particular targeting may no longer be needed.

**Comment by shell1** [comment]
closing as we don't need with the experiment closing.  can re-open if new custom targeting is identified.
