### ISSUE TITLE
Only show pagination if there is more than one page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#776]
https://experimenter.stage.mozaws.net/?ordering=-latest_change&type=&status=&firefox_channel=&firefox_version=&project=&owner=31&archived=on

I only have one experiment, but it shows me the `[ Previous | 1 | Next ]` pagination, which feels a bit, excessive.

**Comment by jaredkerim** [comment]
Is it excessive? Or is it excessive to add additional special cases and filtering logic for the case where there is only one page to remove the buttons when it doesn't really bother anything or anyone?  It's a draw, we'll let @shell1 decide.

**Comment by shell1** [comment]
This is a low priority UX preference, so closing.  This is likely always below the level we'd fix for an internal tool.   But we are still at the "critical functionality" level bugs - or if I enter this I can crash the whole tool issues :).
