### ISSUE TITLE
Allow user to group Results page by segmentation 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7760]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2805)

**Comment by eliserichards** [comment]
Needs more info

**Comment by mikewilli** [comment]
Right now, Jetstream performs analysis for segments (sub-groupings of enrolled users as defined in the jetstream-config for an experiment), but the results are only available in partybal ([example](https://protosaur.dev/partybal/firefox_ios_inactive_tabs.html#has_10_plus_tabs) - segment is `has_10_plus_tabs`).

We want to include this functionality in the Results page for experiments, allowing the user to select not just the `All` segment (which is the current view), but any other defined segments. The exact UI for this is TBD, but currently my thought is to have a dropdown or similar selector and to only show a single segment at a time (vs partybal which shows everything on a single pre-generated static page).
