### ISSUE TITLE
Branch slugs can not be changed for clones/rollouts

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7776]
**[Steps to reproduce]:**

1. Create a new experiment draft.
1. Fill-in the Branches section with valid data.
1. Save the changes.
1. Clone the experiment.
1. Open the clone’s Branches section.
1. Rename at least one branch.
1. Save the changes.
1. Open the Details page.
1. Observe the branch slugs in the recipe JSON and Branches section.

**[Expected result]:**

* Branch slugs change when renaming the cloned branches.

**[Actual result]:**

* Branch slugs of cloned experiments / rollouts remain set to the originals of the cloned experiment.

**[Notes]:**

* The issue is also reproducible when using the “Promote to Rollout” button.
* For non-cloned experiments, the branch slug can only be changed once.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-2817)

**Comment by data-sync-user** [comment]
➤ Yashika Khurana commented:

thank you Maria Heres

**Comment by eliserichards** [comment]
I think this is expected behavior. When we rename a branch, we are changing the `name` field. The `slug` field is not changeable:

```
referenceBranch {
  name: <new name here>
  slug: old-slug
  ...
}
```

**Comment by data-sync-user** [comment]
➤ Yashika Khurana commented:

Correct, but as per the conversation with Jared Lockhart, we are considering adding the ability to rename it as this is requested many times by the users 🤔

**Comment by data-sync-user** [comment]
➤ Elise Richards commented:

Ahh ok I see. I’ll close this (since it’s a bug) and we can file an enhancement ticket for it 👍
