### ISSUE TITLE
The number from the "Population size" section is not entirely visible in edit mode if it contains more than 3 decimals

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#780]
**[Affected versions]:**
- Firefox Release 64.0 and above
- Chrome 71.0.3578.98
- Microsoft Edge 42.17134.1.0
- Safari 12.02

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile created.
- Have an experiment created on the "https://experimenter.stage.mozaws.net/" website.
- You are logged in your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites and click the "Edit" button from "Population" section.
3. Insert a number with 4 decimals in the "Population Size" section.
4. Observe the number inserted in the input field.

**[Expected result]:**
- All numbers are visible in the input field.

**[Actual result]:**
- The first number is not visible.

**[Notes]:**
- This issue is also reproducible if you re-edit the "Population" section after it's saved, the last 2 decimals are not visible.
- Attached is a screen recording of the issue:
![decimals](https://user-images.githubusercontent.com/40061643/51118879-114d3680-181a-11e9-9646-b93cf84ec35c.gif)

**Comment by shell1** [comment]
we are closing out a bunch of these original "we could possible do x" UX enhancements. Mid-year after 2 quarters of development - we will look at the UX and see all up what changes will be truly helpful to the system users (so what UX isn't working for them and really blocking them). Don't want a bunch of ideas in the backlog that might get worked on individually - and conflict with more recent changes.
