### ISSUE TITLE
Add link for creating a new github issue in this repo under "help" section

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#7803]
link using github icon from help section on the lefthand sidebar on the summary that goes to https://github.com/mozilla/experimenter/issues/new

When people need to request advanced targeting - they need to know to file a ticket in this repo.  Under the feedback link - should have a link for "File targeting criteria request"

common scenarios: 
- need a specific release (nightly build, beta version, or dot release) targeted that isn't offered off the version list by default.
- need advanced targeting that isn't available.

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/43795363/223559819-17c06de5-aa8d-43d6-9982-9bbdbcc12fc1.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2830)

**Comment by prernadabi23** [comment]
Hello, @shell1 I am an outreach applicant. Please assign this issue to me.

**Comment by prernadabi23** [comment]
I am not able to view the experimenter page. It is giving me an error "Sorry, you do not have permission to access https://experimenter.services.mozilla.com. Please contact eus@mozilla.com if you should have access."

**Comment by yashikakhurana** [comment]
yes, you want be able to access this, the only way is to set up locally and run from there 🙏
