### ISSUE TITLE
Add learn more link for sticky targeting on Audience page

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#7808]
Followup to #7488 

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/43795363/194160519-aebf9a30-9549-4130-acb8-10f14e5052de.png">

We should add a “learn more” link to an FAQ for enrollment or targeting.

Link: https://experimenter.info/workflow/custom-audiences

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2831)

**Comment by cybraia** [comment]
Hi, I would like to work on. I am Outreachy applicant. Could you give me more information and assign it to me? Thanks!

**Comment by yashikakhurana** [comment]
this task is to add a link along with the text Sticky enrollment, add new text learn more there, and add a link @cybraia

**Comment by yashikakhurana** [comment]
@cybraia if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

**Comment by cybraia** [comment]
I am working on it. There are some issues with installation. I did not qork with yarn, and npm doesn't seem to work. Give me a day.

**Comment by cybraia** [comment]
I am working on windows, are there any different instructions that needs to be followed. I am having a lot of errors; I have been trying to fix. It would be great if I could get some help.

**Comment by yashikakhurana** [comment]
what's the error, you can use the Nimbus Outreachy channel, a lot of windows users were able to run the project successfully

**Comment by cybraia** [comment]
Yes, I have followed all the instructions, it happens to still not work. I have asked a few to help me out. Waiting for their responses. The error occurs when I try "yarn start", the start script is not recognized.

**Comment by KramStyles** [comment]
@cybraia are you still having problems installing on windows? Do you still need help?

**Comment by cybraia** [comment]
Yes, I have been active on the element chat. Still no resolution.

**Comment by yashikakhurana** [comment]
@cybraia have you tried allocating more memory, cleaning your docker and run `make refresh up`

**Comment by cherish2003** [comment]
@yashikakhurana  if @cybraia  is not working on this issue would you assign me

**Comment by yashikakhurana** [comment]
@cybraia are you working on this or do you want me to allocate this issue to @cherish2003? please let me know, thanks

**Comment by cybraia** [comment]
I'm sorry, I've been trying to fix the errors. It's not running. I will keep trying. But you can assign others if you need the fix
