### ISSUE TITLE
[Firefox] Decimals are wrongly added on the number from the "Population size" section when is edited using the arrows if it was previously saved with decimals

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#781]
**[Affected versions]:**
- Firefox Release 64.0 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile created.
- Have an experiment created on the "https://experimenter.stage.mozaws.net/" website.
- You are logged in your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites and click the "Edit" button from "Population" section.
3. Insert a number with decimals in the "Population Size" section and click "Save draft" from the bottom of the page.
4. Click again on the "Edit" button from "Population" section and delete the number from the input field.
5. Click the up arrow from the input field and observe the behavior.

**[Expected result]:**
- The number "1" is inserted in the input field.

**[Actual result]:**
- The decimals from the last saved "Population Size" number are inserted in the input field.

**[Notes]:**
- The issue is also reproducible if you delete the displayed number and enter a new number without decimals. After using the arrows the number doesn't increase/decrease but the previously saved decimals are added.
- Attached is a screen recording of the issue: 
![adddecimals](https://user-images.githubusercontent.com/40061643/51121702-b4a14a00-1820-11e9-9ac8-be5fb053a510.gif)

**Comment by jaredkerim** [comment]
This is a browser behaviour we can't alter.
