### ISSUE TITLE
Sort versions from high to low on Min/Max Version dropdown on Audience page

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#7810]
Related to #6332 

<img width="782" alt="image" src="https://user-images.githubusercontent.com/43795363/194163120-553f35bb-30f7-44bd-a6ce-f11e55c75260.png">

Change the sorting of Min Version and Max Version dropdown so that the most recent (highest) version number is at the top, keeping "No version" as the first item in the list.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2833)

**Comment by shams-rf** [comment]
Hi, please assign me to work on this issue @eliserichards

**Comment by JacobHearst** [comment]
Going to pick this up for Hacktoberfest!

**Comment by eliserichards** [comment]
Awesome @JacobHearst! I will assign this issue to you. Tag me if you have any issues!
