### ISSUE TITLE
Update docs for nimbus-ui readme

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#7812]
Update the `yarn` development instructions [here](https://github.com/mozilla/experimenter/tree/main/app/experimenter/nimbus-ui#development). These seem to be out of date

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2834)

**Comment by eliserichards** [comment]
`make check` runs this command to run the `.test.ts` and `.test.tsx` tests:

```
yarn workspace @experimenter/nimbus-ui test:cov
```

**Comment by yashikakhurana** [comment]
not valid, closing this
