### ISSUE TITLE
[Enhancement] An option to edit added comments should be available

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#782]
**[Affected versions]:**
- Firefox Release 64.0 and above
- Chrome 71.0.3578.98
- Microsoft Edge 42.17134.1.0
- Safari 12.02

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile created.
- Have an experiment created on the "https://experimenter.stage.mozaws.net/" website.
- You are logged in your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites and click the "Add Comment" button from the "Overview" section.
3. Add some text in the input field and click "Save Comment".
4. Observe the added comment.

**[Expected result]:**
- An option to edit the comment should be available.

**[Actual result]:**
- No option to edit the comment is displayed.

**[Notes]:**
- Attached is a screen recording of the issue: 
![editcomment](https://user-images.githubusercontent.com/40061643/51124327-bbcb5680-1826-11e9-9762-b0306adbd9ed.gif)

**Comment by shell1** [comment]
for now - we are won't fixing this.  So far - it also forces a permanent comment.  In most cases that is desired so we have a record of discussions and progress around these experiments.  We may revisit if we hit many complaints - but at this point we are happy as is.  

It definitely isn't always ideal - but many cases it is.  After more use we'll see if we want to change it.
