### ISSUE TITLE
Don't let rollouts be archived

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#7824]
We can add the following lines to `validate_is_archived`:

```
        if self.instance.is_rollout:
            raise serializers.ValidationError(
                f"A rollout can not be archived"
            )
```

and also disable the Archive button on the side panel if it's a rollout: 
<img width="278" alt="image" src="https://user-images.githubusercontent.com/43795363/194939055-dd3b4785-49e3-451e-a38f-25793b12424b.png">

also fix https://github.com/mozilla/experimenter/blob/84e27e361a6d8d07171f2e1cf99b81f1ba308265/app/experimenter/experiments/models.py#L611

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2840)

**Comment by anand-pb** [comment]
hi @yashikakhurana, I would like to solve this issue, it would be of help if you could assign me with this

**Comment by anand-pb** [comment]
I forgot to mention, I am an outreachy applicant currently

**Comment by yashikakhurana** [comment]
sure thank you @anand-pb , assigning this ticket to you, let me know if you have any questions :)

**Comment by yashikakhurana** [comment]
@anand-pb  I am so sorry, I have to remove this issue for Outreachy tasks, please feel free to look at other issues, and let me know if you need any help.

**Comment by anand-pb** [comment]
ok, I will find an other issue that I can help with
