### ISSUE TITLE
[Security] The option to "Sign out" from your LDAP account is not available on the "Experimenter" website

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#783]
**[Affected versions]:**
- Firefox Release 64.0 and above
- Chrome 71.0.3578.98
- Microsoft Edge 42.17134.1.0
- Safari 12.02

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile created.
- You are logged in with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Observe the up-right section where your "Mozilla email" is displayed. 

**[Expected result]:**
- The option to "Sign out" from your LDAP account is displayed.

**[Actual result]:**
- There is no option to "Sign out" from your LDAP account.

**[Notes]:**
- Attached is a screen recording of the issue: 
![loggout](https://user-images.githubusercontent.com/40061643/51126749-96d9e200-182c-11e9-992c-9fefdca845ba.gif)

**Comment by shell1** [comment]
the sign-in times out eventually.  you can also sign out of auth0 to sign out of all things - if you were on a shared computer.  there are work arounds

**Comment by jaredkerim** [comment]
I'm marking this as blocked because we will soon be migrating from AWS to GCP and changing from the Auth0/OpenIDC to the Google native authenticator and that will probably give us some better way to accomplish this.

**Comment by jaredlockhart** [comment]
Hasn't come up after a year so closing.
