### ISSUE TITLE
Default sort list page by recently updated

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7838]
We previously sent the list of experiments to the frontend sorted by most recently updated, but the SQL call was extremely costly and so we removed it for performance reasons.  However, now the frontend is receiving experiments in ascending creation order, so the oldest experiments are appearing first which isn't really a great user experience.  Let's find a way to send them back to the frontend in most recently updated order without needing to do a costly SQL join.  We can probably denormalize an updated date right onto the NimbusExperiment model and sort on that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2843)

**Comment by yashikakhurana** [comment]
closing this issue on favour of https://github.com/mozilla/experimenter/pull/8159
