### ISSUE TITLE
Hide the first run checkbox for desktop

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7843]
Becuase the first run checkbox only applies for mobile experiments we should hide it altogether for desktop experiments to prevent confusion.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2847)

**Comment by yashikakhurana** [comment]
to provide more context, if the application is Desktop, then we want to hide the first run experiment checkbox from the audience section

**Comment by adevicky** [comment]
I'm an outreachy applicant and I would like to work on this project @yashikakhurana

**Comment by yashikakhurana** [comment]
@adevicky sure, thank you, assigning to you , let me know if you have any questions

**Comment by yashikakhurana** [comment]
@adevicky if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

**Comment by adevicky** [comment]
@yashikakhurana I am working on it, though locating the CSS file of the checkbox is giving me problems, I don't know if you can help. Thanks.

**Comment by yashikakhurana** [comment]
not sure why are you looking for CSS 
![image](https://user-images.githubusercontent.com/25848231/224121414-4596b2e9-401c-42bc-8d1e-a0f67987894f.png)
we need to hide this first run experiment checkbox if the application is desktop

**Comment by kelani34** [comment]
Hello @yashikakhurana I'm an outreachy applicant. Can I get this assigned to me?

**Comment by yashikakhurana** [comment]
completed here - https://github.com/mozilla/experimenter/pull/8674
