### ISSUE TITLE
results page on existing completed experiment shows failure screen

### ISSUE THREAD

**Issue by vtay29** [mozilla/experimenter#7847]
The [same issue](https://github.com/mozilla/experimenter/issues/7839) is occurring :

"General application error
Something went wrong. Please try again later.
can't convert undefined to object"

These are the following experiment results affected:
https://experimenter.services.mozilla.com/nimbus/doodle-pin-to-taskbar-core-eco2207-en/results
https://experimenter.services.mozilla.com/nimbus/doodle-pin-to-taskbar-regular-eco2207-en/results
https://experimenter.services.mozilla.com/nimbus/doodle-pin-to-taskbar-casual-eco2207-en/results
https://experimenter.services.mozilla.com/nimbus/doodle-pin-to-taskbar-infrequent-eco2207-en/results
https://experimenter.services.mozilla.com/nimbus/doodle-set-default-infrequent-eco2207-en/results
https://experimenter.services.mozilla.com/nimbus/doodle-set-default-regular-eco2207-en/results
https://experimenter.services.mozilla.com/nimbus/doodle-set-default-core-eco2207-en/results
https://experimenter.services.mozilla.com/nimbus/doodle-set-default-casual-eco2207-en/results
https://experimenter.services.mozilla.com/nimbus/about-welcome-dyk-pip-and-switch-tabs/results

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2850)

**Comment by mikewilli** [comment]
Thanks for reporting -- we've identified the issue and are working on a fix now.

**Comment by mikewilli** [comment]
@vtay29 Fix is in and pushed through -- I see all those results pages properly now, but please let us know if you continue to see any issues.

**Comment by vtay29** [comment]
thank you!
