### ISSUE TITLE
Error 400 Bad request is displayed when trying to edit the enrollment date from the admin panel

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7848]
**[Prerequisites]:**

* Have a Nimbus experiment launched and approved on the Stage server.

* The experiment has enrollment still active.

* Have an LDAP account with rights to the 

[+Stage admin page+](https://stage.experimenter.nonprod.dataops.mozgcp.net/admin/).

**[Steps to reproduce]:**

1. Navigate to “[+https://stage.experimenter.nonprod.dataops.mozgcp.net/admin/experiments/nimbusexperiment/+](https://stage.experimenter.nonprod.dataops.mozgcp.net/admin/experiments/nimbusexperiment/) “ page.
1. Open the page of the experiment from prerequisites.
1. Set the "Proposed enrollment:" to 0 and save the changes.

**[Expected result]:**

* The "Proposed enrollment" field can be changed in order for QA to trigger the end enrollment email.

**[Actual result]:**

* A “Bad Request (400)” error is received.

**[Notes]:**

* Attached a screen recording of the issue.
!Screen Recording 2022-10-14 at 11.28.07.mov|width=3506,height=1736!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-2851)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/29709">Screen Recording 2022-10-14 at 11.28.07.mov</a>

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/issues/8171
