### ISSUE TITLE
Long name makes page to break

### ISSUE THREAD

**Issue by poubina** [mozilla/experimenter#785]
[Affected versions]:

Firefox Release 64+
Chrome 71+

[Affected Platforms]:

All Windows
All Mac
All Linux

[Prerequisites]:

Have a new Firefox profile created.
You are logged in your LDAP account to "https://experimenter.stage.mozaws.net/" website .

[Steps to reproduce]:

Create a new experiment.
Fill in field "Name" with 255 characters and all remaining fields with correct data. 
Save draft.
Observe the behavior.

[Expected result]:

Page displays experiment info without breaking.

[Actual result]:

Page breaks.

[Notes]:

find screenshots attached:
![descriptionoverflow](https://user-images.githubusercontent.com/44272078/51130128-063eda00-180b-11e9-8d12-04e9f6ad48e3.png)

![descriptionoverflow2](https://user-images.githubusercontent.com/44272078/51130136-0d65e800-180b-11e9-8035-580042e6fd81.png)

**Comment by shell1** [comment]
thank you for catching.  this is an acceptable behavior for now.  will revist after using the system for a few quarters to see if we run into any issues with this.
