### ISSUE TITLE
Hide results pages for rollouts

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7852]
Rollouts will not receive jetstream analysis and so we should hide the results links in the sidebar on the experiment summary page altogether for rollouts.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/43795363/220993941-0dfcf32c-382d-4462-a5a8-106143f603a4.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2858)

**Comment by mikewilli** [comment]
Could we also set the `show_analysis` flag to `false` for these experiments so that if the results page is accessed, we display the standard warning message? Or would that be the wrong message to display for rollouts?

**Comment by jaredlockhart** [comment]
There's that default state it enters where the link is greyed out and it says 'results are not ready yet' but we should modify the language to 'results are not available for rollouts'

**Comment by timalsinab** [comment]
Hello, I am an outreachy applicant. Can I work on this?

**Comment by yashikakhurana** [comment]
@timalsinab yes sure I can assign it to you, let me know if you have any questions

**Comment by mikewilli** [comment]
@timalsinab I am currently doing some work that may affect this (and might fix it), so I would suggest waiting to begin this bug. This is my fault for missing this ticket when gathering up related issues for my current work, my apologies. Glad you're excited to get started though! You can look for another bug with the labels `good-first-bug` or `Outreachy` in the meantime.

cc @yashikakhurana

**Comment by yashikakhurana** [comment]
@timalsinab unfortunately you will need to find another issue, let me know if I could help you with anything. @mikewilli thank you for providing insights :)
