### ISSUE TITLE
Population size error message is wrong

### ISSUE THREAD

**Issue by poubina** [mozilla/experimenter#787]
[Affected versions]:

Firefox Release 64+
Chrome 71+

[Affected Platforms]:

All Windows
All Mac
All Linux

[Prerequisites]:

Have a new Firefox profile created.
You are logged in your LDAP account to "https://experimenter.stage.mozaws.net/" website .
A experiment saved with basic information (1. Overview).

[Steps to reproduce]:

Edit the experiment of the prerequisites (2. Population).
Fill in field "Population Size" with 0 (zero).
Fill in all remaining fields with correct information
Save draft.
Observe the behavior.

[Expected result]:

Population size should be > 0.

[Actual result]:

Wrong error message is displayed "The population size must be between 0 and 100 percent."

[Notes]:

find screenshots attached:

![populationzero](https://user-images.githubusercontent.com/44272078/51131170-af86cf80-180d-11e9-8a6e-1097965d7820.png)

**Comment by jaredkerim** [comment]
Thanks for catching this, but we're just gonna leave it as is.
