### ISSUE TITLE
Experimenter includes a toggle to exclude users that have any of the features target prefs set in the User branch

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#7906]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2861)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/EXP-2861

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/pull/7884
