### ISSUE TITLE
Add a data migration to clean up `us_only`

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7921]
We removed some targeting configs including one tha thad the slug `us_only` but did not update references in the db so now some older experiments are broken.  We should null that value out.  The actual targeting expression used by the experiment will be cached separately in the recipe data field so it shouldn't matter for historical reference.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2921)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/EXP-2921

**Comment by data-sync-user** [comment]
➤ Yashika Khurana commented:

fixed in this PR https://github.com/mozilla/experimenter/pull/8044 ( https://github.com/mozilla/experimenter/pull/8044|smart-link )
