### ISSUE TITLE
Add sentry to integration tests

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7922]
Sentry now offers very advanced performance monitoring which is helpful for tracking and debugging, so let's add that to our integration test suite as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2922)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/32949">image-20230111-184857.png</a>

**Comment by data-sync-user** [comment]
➤ Benjamin Forehand Jr. commented:

!image-20230111-184857.png|width=2570,height=3669!

Progress!
