### ISSUE TITLE
Show population percent in summary with one decimal point

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#7952]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/43795363/202039032-598b30b6-0a17-4efc-80c2-8145d1594d5f.png">

The population percentage here should match the Audience page and only show one decimal point, not 4.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2929)

**Comment by cherish2003** [comment]
Hello @yashikakhurana. I am an Outreachy applicant and I would love to participate in this experimenter project by working on this issue.

**Comment by emmaz12** [comment]
@yashikakhurana I would love to work on this issue! I am also an Outreachy applicant

**Comment by yashikakhurana** [comment]
@cherish2003 since I already assigned you the ticket please feel free to tag me in any other issue once you finish your assigned ticket, i am going to @emmaz12 this ticket for now, @emmaz12 let me know if you have any questions.

**Comment by yashikakhurana** [comment]
@emmaz12 i just noticed that I also assigned the other ticket to you, please feel free to work towards that, once you create a PR and its reviewed, please tag me again for the assignment if its still available

**Comment by yashikakhurana** [comment]
@emmaz12 create separate PR for each issue

**Comment by emmaz12** [comment]
@yashikakhurana PR for this issue as been created! 
Thanks
