### ISSUE TITLE
Errors incorrect on audience page for expected num of clients

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#7953]
The "Expected number of clients" field on the [Audience page](https://github.com/mozilla/experimenter/blob/1590e3a23ea1691ae52ad1747de0cf5b1806d87c/app/experimenter/nimbus-ui/src/components/PageEditAudience/FormAudience/index.tsx#L374) is not showing errors if the string begins with a number:

<img width="428" alt="image" src="https://user-images.githubusercontent.com/43795363/202042701-5919f77b-63c4-4fb4-8458-887cfe09abc4.png">

<img width="333" alt="image" src="https://user-images.githubusercontent.com/43795363/202042633-3a3d9bfc-8e29-4a5a-bc18-1935482b6d9b.png">

<img width="469" alt="image" src="https://user-images.githubusercontent.com/43795363/202042716-966fb7da-8b5e-4038-927d-1d88a91ab65f.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2930)

**Comment by yashikakhurana** [comment]
@cherish2003 I assigned you the other issue, if you want this one too I can assign this too, please let me know

**Comment by Faith-Nchifor** [comment]
Hello @yashikakhurana. I am an Outreachy intern. I will be glad to do this task

**Comment by prernadabi23** [comment]
Hello @yashikakhurana , I am an outreach applicant, Please assign this issue to me.

**Comment by yashikakhurana** [comment]
@Faith-Nchifor assigned to you, @prernadabi23 you have to find other tasks, its based on first come first, let me know if need any help, thanks

**Comment by Faith-Nchifor** [comment]
Hello @yashikakhurana,
Permit me to ask this question.
How can I  install the project on my machine? I can't find a .yarn file or package.json in the project folder. It's windows os

**Comment by Faith-Nchifor** [comment]
Okay @yashikakhurana. Thanks

**Comment by yashikakhurana** [comment]
@Faith-Nchifor if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

**Comment by emmaz12** [comment]
@yashikakhurana I am interested in this issue if it is still open! Thanks!
