### ISSUE TITLE
Add tests for status_next transitions 

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#7990]
Let's explicitly test `status_next` like we're doing in https://github.com/mozilla/experimenter/pull/7987

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2953)

**Comment by eliserichards** [comment]
https://github.com/mozilla/experimenter/blob/117a12b0ced2dc07d75dbcedfd06f8d07ef57509/app/experimenter/experiments/tests/api/v5/test_serializers/test_nimbus_experiment_serializer.py#L582

**Comment by yashikakhurana** [comment]
@eliserichards can we close this?
