### ISSUE TITLE
Population slider won't allow '.' or numbers to be entered directly

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#7994]
The slider won't let us enter '.' so we can enter non-whole number or even enter numbers directly - so is taking away capabilities.  I found a way to hack in .5% by doing to 5% and adding a '.' before.  

I get NaN when I do anything outside of dragging the bar and then can't type until delete NaN.

I can't add 5.5% - as it won't let me type a . after a number.  It won't let me type in 7% - but i can type in 5 and then type of that number with a 7.  

also it will let you target over 100% - so 1000% you can save.

![image](https://user-images.githubusercontent.com/8192232/205149290-5798c6b9-1039-429e-ac16-8802b658eda2.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2956)

**Comment by data-sync-user** [comment]
➤ Elise Richards commented:

Backspacing all the way makes the field show NaN instead of empty
