### ISSUE TITLE
Population slider text input allows values over 100 to save

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#7997]
Breaking this out from #7994 - I wasn't able to reproduce this:

> also it will let you target over 100% - so 1000% you can save.

![image](https://user-images.githubusercontent.com/8192232/205149290-5798c6b9-1039-429e-ac16-8802b658eda2.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2958)

**Comment by jrbenny35** [comment]
I tried this on stage and I can't get it to save.

![image](https://user-images.githubusercontent.com/5751892/205173369-ef10ba74-503e-44fe-95fe-d605237ece8f.png)

**Comment by eliserichards** [comment]
Not reproducible, closing this.
