### ISSUE TITLE
lets add logo \o/

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#8013]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2969)

**Comment by yashika-khurana** [comment]
@BhuvanAde The logo is ready to use (prepared) this issue is just referring to plug that :), let me know if you need UI/UX design task I can help you with that :)

**Comment by BhuvanAde** [comment]
@yashika-khurana I just checked out the logo, and it's great. Yes, please let me know if there are any UI/UX design tasks that I can help with.

**Comment by yashika-khurana** [comment]
@BhuvanAde give me a day or two, I am going to mark some of the task ui/ux ready to take bugs and share with you :)

**Comment by yashika-khurana** [comment]
oh @BhuvanAde do you want to take this https://github.com/mozilla/experimenter/issues/8016 ?

**Comment by yashika-khurana** [comment]
or @BhuvanAde this one https://github.com/mozilla/experimenter/issues/8020, let me know which one you want :)
