### ISSUE TITLE
Scroll main content independent of sidebar when viewing an experiment

### ISSUE THREAD

**Issue by mikewilli** [mozilla/experimenter#8016]
This is a small UX improvement, but it would be nice to scroll the main content of the page without scrolling the left-hand sidebar. This would be particularly helpful on the Results page where some sidebar links help to quickly navigate to different metrics.

Of note, the sidebar should also be able to scroll independently, in case the content overflows the window.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2970)

**Comment by BhuvanAde** [comment]
Can I take up this issue?

**Comment by yashika-khurana** [comment]
@BhuvanAde sure let me assign it to you :)

**Comment by BhuvanAde** [comment]
Hey @yashika-khurana, I'm having trouble running the project locally. Could you please tell me how I can do this?

**Comment by yashika-khurana** [comment]
@BhuvanAde what issue you are currently having? to run project locally you can do `make refresh up` or `make up`

**Comment by BhuvanAde** [comment]
`experimenter-worker-1 | [2022-12-16 08:03:23,906: INFO/ForkPoolWorker-3] experimenter.kinto.tasks.nimbus_synchronize_preview_experiments_in_kinto[9bebc9d6-b239-4515-9f97-9f65729712e3]: Synchronizing preview experiments failed: PATCH /v1/buckets/main-workspace/collections/nimbus-preview - 403 403 - {'code': 403, 'errno': 121, 'error': 'Forbidden', 'message': 'Not in nimbus-preview-reviewers group'}`

@yashika-khurana

**Comment by yashika-khurana** [comment]
@BhuvanAde can you do `make refresh up` and have you followed instructions from here (readme file) https://github.com/mozilla/experimenter ?

**Comment by BhuvanAde** [comment]
@yashika-khurana Sorry, I was on a trip and didn't have much time to contribute 🥲
Will soon fix this.

**Comment by cherish2003** [comment]
Hello mam @yashikakhurana. I am an Outreachy applicant and I would love to participate in this experimenter project by working on this issue.

**Comment by yashikakhurana** [comment]
@cherish2003 sure thank you, I am assigning this ticket to you, let me know if you have any questions :)

**Comment by yashikakhurana** [comment]
@cherish2003 I am so sorry, I have to remove this issue for Outreachy tasks, please feel free to look at other issues, and let me know if you need any help.
