### ISSUE TITLE
Bugzilla Experimenter bug creation when “Ready for Sign-offs” button clicked

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#802]
This bug is a blank holder for QA comments and release management.  Bugzilla allows studies to fit into existing queries and release processes.  Bug not truly used (to deploy Normandy) until after “ready to ship” is clicked.

_Jared - Let me know if parts of these bug editing requests are technically complex.  We can include those in manual instructions for what bug editing is need._
 
**BUG TITLE** = [STUDY]:{type} {Name} 
**SEE ALSO** = {Data Science Bug} _Issue - need only the numbers in bugzilla (not URLs)_
**BLOCKS** = If {Feature Meta Bug} exists, put in BLOCKS _Issue - need only the numbers (not URLs)_
**Set TrackingRelease{release}**=? set this initial assessment- flags for QA and Relman what is targeting a release.  This will be written again when “ready to Ship” is clicked.  Shell will document in the checklist for bugzilla, that they need to manually edit the TrackingRelease field to remove “?” if the study release/channel changed.  Currently we can only set this for the one version we get back from experimenter.  But we should be getting min version and max version soon ... and be able to add all those. That will be a new ticket.
**URL** = {experimenter link} 
**Comment** = “Experimenter is the source of truth for details and delivery.  {experimenter specific study link}.   Changes to Bugzilla are not reflected in Experimenter and will not change delivery configuration.”  
**Whiteboard** = “Ready for Sign-offs”

**Comment by jaredkerim** [comment]
@tiftran For the 'comment' just put it in the description field so we only need to make one API call and include a link back to experimenter
