### ISSUE TITLE
Logo favicon 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#8020]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2972)

**Comment by yashika-khurana** [comment]
we have added new logo, lets try this logo as favicon too!

**Comment by BhuvanAde** [comment]
Can I go with this for now because I think we need it early?

**Comment by yashika-khurana** [comment]
sure let me assign it to you

**Comment by yashika-khurana** [comment]
I assigned myself too, just in case you need any help!

**Comment by BhuvanAde** [comment]
app/experimenter/nimbus-ui/public/favicon.ico must be replaced right?

**Comment by yashika-khurana** [comment]
yup that's correct

**Comment by BhuvanAde** [comment]
between I'm unable to see manifesto.json out there

**Comment by yashika-khurana** [comment]
sorry I am not sure what you mean 🤔

**Comment by BhuvanAde** [comment]
Sorry, I just got confused.

**Comment by BhuvanAde** [comment]
I replaced the favicon.ico file. Aside from that, is there anything else in the code that should be changed?

**Comment by yashika-khurana** [comment]
yeah you can run the project locally, run command `make check` to see if all the test cases are passing, and submit PR, and please add me as a reviewer :)

**Comment by BhuvanAde** [comment]
Ok I'll do that, Thanks!

**Comment by BhuvanAde** [comment]
Could someone kindly help me with running the project locally? I've tried, but I'm unable to run it. Between I have run the 
````make check```` command and all the cases are passing successfully.

**Comment by BhuvanAde** [comment]
@yashika-khurana Please check the Pull Request I sent.

**Comment by yashika-khurana** [comment]
@BhuvanAde yeah sure I can review that, thank you for doing that 👏

**Comment by BhuvanAde** [comment]
Please let me know if there are any changes to be made.
