### ISSUE TITLE
Disable results link for experiments without analysis results 

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#8025]
I see a lot of experiments not having results because the enrollments ran through the entire experiment so there's no analysis period.  We can deduce that entirely locally since we have the dates, so let's just compute that and then use that to disable the results link entirely rather than making it look like there should be results but it's broken for some reason.

Example:

https://experimenter.services.mozilla.com/nimbus/tcp-rollout-phase-iii-tcp-on-by-default-for-95-existing-release-profiles/results

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2976)

**Comment by mikewilli** [comment]
Related: #7852
