### ISSUE TITLE
Bugzilla update when Experimenter goes to “Live” state

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#804]
~~**Whiteboard**= overwrite with “Live”~~

~~Set **Status-firefox{version} to FIXED** (see below image).  I checked with relman, this would move it along through their channel.~~

**New Comment** 
Start date: {start date}, 
Experiment end date: {calculated experiment end date}. 

<img width="506" alt="Screen Shot 2019-04-26 at 8 45 52 AM" src="https://user-images.githubusercontent.com/8192232/56820016-c4590300-67ff-11e9-92d6-583be9886ce4.png">

EDIT: Based on discussions with @shell1 scope of bugzilla behaviour has been reduced

**Comment by jaredkerim** [comment]
Blocked on #158
