### ISSUE TITLE
Takeaways "Edit" button vertical padding

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#8078]
1. Have a "Complete" experiment
2. On the Summary page, click on the "Archive" button on the lefthand side

When you archive the experiment, you can see the "Edit" button on the Takeaways section goes away. When it does, the vertical padding of the Takeaways section changes. This should be a consistent size whether or not the Edit button is present.

https://user-images.githubusercontent.com/43795363/208506481-b19ee2f7-b1e1-45ec-b056-76abcb0aa5aa.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3012)

**Comment by emmaz12** [comment]
@yashikakhurana I am an Outreachy applicant! I would love to work on this issue :)

**Comment by yashikakhurana** [comment]
@emmaz12 sure, thank you, assigning this ticket to you, let me know if you need any help :)

**Comment by emmaz12** [comment]
@yashikakhurana I believe I have completed this bug. Please let me know about any changes I can make! 

https://user-images.githubusercontent.com/117552772/223656496-d7bd1ca1-3c63-4470-9b17-c77a98270b68.mov

**Comment by yashikakhurana** [comment]
@emmaz12 kindly submit a PR 🙏

**Comment by emmaz12** [comment]
@yashikakhurana Just submitted a PR, waiting for review now! Thanks :)
