### ISSUE TITLE
Remove invalid enrollment dates on clone

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#8091]
If the enrollment dates are in the past, the clone operation should remove the invalid dates or not let the user save.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3016)

**Comment by mikewilli** [comment]
Could we use the cloned enrollment period to set a new prospective end date? Or would it be better to force the experiment runner to make an explicit choice?

**Comment by jaredlockhart** [comment]
Closing as a dupe of https://github.com/mozilla/experimenter/issues/8130
