### ISSUE TITLE
Match dropdown arrows on Audience page

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#8093]
The dropdown arrows on Channel, Min version, and Max version are tiny and don't have end padding. Let's match these to the bigger dropdown arrows on Country and Locale:

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/43795363/208762782-5a95793a-6315-409e-bf01-0e78079d789b.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3017)

**Comment by mikewilli** [comment]
This looks related to #8067, which may fix this inconsistency as a side effect. It could also be that these are already react-select dropdowns and the difference is because the larger dropdowns are multi-selects.

**Comment by betty-alagwu** [comment]
Hello, can i take up this issue, i will love to work on it

**Comment by 0x0god** [comment]
Hello, I'm an outreachy intern, can i work on this?

**Comment by betty-alagwu** [comment]
Working on it.

**Comment by yashikakhurana** [comment]
@betty-alagwu if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

**Comment by Avi-88** [comment]
Hello @yashikakhurana ma'am, I would like to work on this could you please assign it to me, thanks

**Comment by Avi-88** [comment]
Hi @eliserichards ma'am , I looked into the approach for this issue. One is to use the `<Select/>` component from react-select that is being used for country and locale which will match the styling perfectly, But it will require adding new states for the inputs that will be changed. Other one was to use the `custom` prop that react-boostrap provides the form component which will add the padding by default,  but I couldn't find a good way to replace the suffix arrow icon that it provides by default with one that matches the other inputs. I can try and research more to find a way to do it. For reference I'll attach screenshots of both the results achieved so far.Please let me know which approach sounds more promising so I can proceed with that, thanks

With `custom` prop - 

![image](https://user-images.githubusercontent.com/79744258/225558987-1905533a-e938-46ae-8e0c-01e63b919e9a.png)

With `<Select/>` ccomponent and extra states - 

![image](https://user-images.githubusercontent.com/79744258/225562091-ee80ddf9-84c1-4f40-b3a3-26a4557a438c.png)

**Comment by yashikakhurana** [comment]
@Avi-88 visually with `<Select/>`, it looks better, but if this is a optimized approach or the best approach, I will let you research and decide :)

**Comment by Avi-88** [comment]
Understood ma'am, I'll research a bit more before finalizing the approach and make a PR
