### ISSUE TITLE
Filter errors displayed in Result to the current analysis basis

### ISSUE THREAD

**Issue by mikewilli** [mozilla/experimenter#8097]
Once Jetstream starts logging analysis basis as part of errors, Experimenter should handle this and display only the errors for the currently selected analysis basis (defaulting to `enrollments`).

Related to https://github.com/mozilla/jetstream/issues/1488

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3019)

**Comment by shell1** [comment]
Hi Mike, I'm seeing errors most experiments now that I'm trying to read for results.  I can't tell if something just is seriously broken - or if there's just more errors being made visible.  But it feels like something is broken.

This experiment also has a bunch of errors for other default metrics https://experimenter.services.mozilla.com/nimbus/first-run-easy-as-one-click-ver-1/results
