### ISSUE TITLE
There is no limitation to the number of branches that can be added and saved

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#813]
**[Affected versions]:**
- Firefox Release 64.0.2 and above
- Chrome 71.0.3578.98
- Microsoft Edge 42.17134.1.0
- Safari 12.02

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile created.
- Have an experiment created on the "https://experimenter.stage.mozaws.net/" website with 20 branches.
- You are logged in your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites. 
3. Scroll to the bottom of the page and click the "+ Add Branch" button button from "Branches" section. 
4. Observe the behavior.

**[Expected result]:**
- Nothing happens, the "+ Add Branch" button is grayed out.

**[Actual result]:**
- Another branch is added under the existing branches.

**[Notes]:**
- I have managed to create and save 60 branches. I didn't go further since it takes a lot of time to create and complete all of them.
- After all the added branches input fields are completed and you click the "Save Draft" button the created branches are saved.
- Attached is a screen recording of the issue: 
![branchnr](https://user-images.githubusercontent.com/40061643/51264242-be60b400-19be-11e9-9d99-69309bb0534e.gif)

**Comment by jaredkerim** [comment]
That's funny I thought I capped it at 20.  That's definitely a bug.

**Comment by jaredkerim** [comment]
Thanks for catching this, we're closing this per @shell1
