### ISSUE TITLE
[Enhancement] Input fields should have a minimum height so that they always display at least one line of text

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/experimenter#816]
[Affected versions]:
- Firefox Release Version 64.0.2, Build ID 20190108160530
- Firefox Nightly Version 66.0a1, Build ID 20190116093310

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- You are logged in with a valid LDAP account.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://experimenter.stage.mozaws.net/.
2. Click the "Create Experiment" button and enter a string of text in the "Short Description" input field.
3. Click the bottom-right corner of the "Short Description" input field and drag it upwards.
4. Observe the behavior.

[Expected result]:
- The input field displays one line of text.

[Actual result]:
- The input field can be resized until the text is no longer visible. 

[Additional Notes]:
- This behavior is also reproducible using the following input fields:
  - "Short Description"
  - "Related Work URLs"
  - "Population Filtering"
  - "Branch Description"
  - "Objectives"
  - "Analysis Plan"
  - "Technical Risks Description"
  - "Risks"
  - "Test Instructions" 
  - "Test Builds"
  - "QA Status"
- I have attached a screen recording of the issue:
![box resize](https://user-images.githubusercontent.com/40393891/51390128-0aceff80-1b37-11e9-9e60-3a37a7611e0a.gif)

**Comment by shell1** [comment]
valid - but closing for now.  we are doing a full UX review mid-year after a lot of new stuff has landed to determine the most impactful changes.
