### ISSUE TITLE
[Linux] The focus indicator is visible when clicking the page's elements

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/experimenter#818]
[Affected versions]:
- Firefox Release 64.0.2 and above

[Affected Platforms]:
- All Linux

[Prerequisites]:
- Have a new Firefox profile created.
- Have an experiment created on the "https://experimenter.stage.mozaws.net/" website.
- You are logged in your LDAP account.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/" website.
2. Click on the experiment card from prerequisites.
3. Observe the behavior.

[Expected result]:
- The navigation takes place without any visible changes.

[Actual result]:
- The focus indicator (dotted line) is visible around the experiment's card until the navigation takes place.

[Notes]:
- The focus indicator can be seen on all the website's page elements (if clicked).
- Please see the screen recording of the issue: https://goo.gl/yhx8dt

**Comment by jaredkerim** [comment]
Thanks for catching this but it's a minor issue and doesn't affect usage so I'm going to close this for now.
