### ISSUE TITLE
[Mobile] The "Experimenter" website is not optimized for mobile devices

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#819]
**[Affected versions]:**
- Firefox 64.0.2
- Chrome 71.0.3578.99
- Safari 12

**[Affected Platforms]:** 	 	
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)
- Android 6.0 (Huawei P8 Lite)
- iOS 12.1.2 (Iphone 6S)

**[Prerequisites]:**
- Have the latest Firefox for mobile version installed on your device.
- You are logged in your LDAP account.

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to "https://experimenter.stage.mozaws.net/".
2. Navigate through the website and observe the website's content.

**[Expected result]:**
- The website's content is correctly displayed.

**[Actual result]:**
- The website's content is not displayed correctly.

**[Notes]:**
- This issue is also reproducible if the device's display mode is in "landscape".
- Attached are screen recording of the issue: 
![expmobile](https://user-images.githubusercontent.com/40061643/51482052-12dca880-1d9e-11e9-9627-7280977969f5.gif)

**Comment by jaredkerim** [comment]
Mobile support will be a distant stretch goal many quarters from now, so I'm going to close this for now.
