### ISSUE TITLE
Ignore EndedException in Analysis Results Errors

### ISSUE THREAD

**Issue by mikewilli** [mozilla/experimenter#8190]
Per @danielkberry we should be safe to ignore errors of this type when displaying on the Results page. In the example below, the errors are caused by an overridden end date in the custom config file. We should verify that there are no other scenarios that cause this error that we'd want to alert users about, and if not then we should filter them out either in the Jetstream client code or on the UI page.

Example of error here: https://experimenter.services.mozilla.com/nimbus/106-major-release-firefox-existing-user-experience/results

(screenshot in case the link changes)
![image](https://user-images.githubusercontent.com/102263964/214397013-3834c836-ed80-45c0-8d21-e5c8a3772997.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3088)

**Comment by danielkberry** [comment]
As best I can tell, this is only thrown [here](https://github.com/mozilla/jetstream/blob/69b694e34f97fc024e2a556707568cd38b1a7186/jetstream/analysis.py#L368) if an experiment has an end date defined in the config and the run is after that date. In that case, I think it's sufficient to show the warning message below (`Analysis has manual overrides in Jetstream`) and we don't need the error

**Comment by mikewilli** [comment]
Planning to do this on the Jetstream side so I'm closing this ticket. Please see the [linked issue](https://github.com/mozilla/jetstream/issues/1593) for tracking.
