### ISSUE TITLE
Experiment count maxes out at 10

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#820]
Experimenter tells me there are 10 experiments when there are more than 10 experiments:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/173889/51500879-925d7e00-1d84-11e9-80b3-6ee21d9a875f.png">

"Number of experiments I'm showing you on this page" isn't a very interesting count.

**Comment by jaredkerim** [comment]
Good point, it originally showed the total number and then I added the pagination, I should change it back to showing the total number.

**Comment by jaredkerim** [comment]
I actually already opened a ticket for this a long time ago: https://github.com/mozilla/experimenter/issues/567
