### ISSUE TITLE
Completed rollouts have an “Audience” link in the sidebar

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#8204]
**[Prerequisites]:**

* Have a completed rollout (e.g. this [+stage rollout+](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/edit/summary)).

**[Steps to reproduce]:**

1. Open the rollout from prerequisites and observe the sidebar.
1. Click the “Audience” link from the sidebar.

**[Expected result]:**

* Completed rollouts do not have an “Audience” link in the sidebar.

**[Actual result]:**

* Completed rollouts have an “Audience” link in the sidebar.

**[Notes]:**

* Fields on the Audience page that gets accessed can be edited, but the changes can not be saved.
* Attached is a screen recording of the issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-3100)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/33396">audience.gif</a>

**Comment by eliserichards** [comment]
If a rollout has `status=COMPLETE`, the Audience page should be hidden: https://github.com/mozilla/experimenter/blob/3a0e8439865deae8bd26c7b1344276b945c99ed5/app/experimenter/nimbus-ui/src/components/AppLayoutSidebarLaunched/index.tsx#L195

**Comment by tobidosumu** [comment]
Hello @eliserichards. I am also an Outreachy applicant. I would love to fix this please?

**Comment by yashikakhurana** [comment]
@eliserichards can you verify the expected behavior? if that's the issue, let me know I can assign it to @tobidosumu

**Comment by yashikakhurana** [comment]
@tobidosumu if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

**Comment by KramStyles** [comment]
@yashikakhurana can this task be assigned to me  please?

**Comment by Sprof22** [comment]
@yashikakhurana I am an Outreachy applicant, I am yet to be assigned any task, I have an idea of what you need me to do. Can I be assigned to this task. As my reward, I would like to be assigned to more task

**Comment by Avi-88** [comment]
Hello @yashikakhurana ma'am, I'd like to work on this issue, could you please assign it to me , thanks

**Comment by Avi-88** [comment]
Hello @yashikakhurana  ma'am, I don't see any rollouts in the project right now. To recreate this issue should I create one ? if yes what do I need to put in all the fields ? It'd be a huge help if I had something to refer to, thanks

**Comment by yashikakhurana** [comment]
@Avi-88 yes, in the branches page you can select yes it is a rollout checkbox

**Comment by data-sync-user** [comment]
➤ Maria Heres commented:

I have verified that the “Audience” field is no longer displayed.
