### ISSUE TITLE
Show more experiments on list page

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#821]
10 experiments isn't very many -- I think it'd be great if the default were closer to 50, and/or if there was a "view all" escape hatch.

I'm mostly interested in being able to use control-F to search through filtered results; text search would reduce the need for longer pages a little.

**Comment by peterbe** [comment]
Seems to be that the need is a widget to personally control how many experiments should be listed. The [default is 10](https://github.com/mozilla/experimenter/blob/63a6c723901eb5f12a776f13936f8783f81051e8/app/experimenter/settings.py#L224) but ideally we should let the user choose. How about a drop-down widget near the pagination controls (lower right-hand corner) where you can select between 10, 25, 50, and 100 ...experiments per page.

**Comment by peterbe** [comment]
However, if the objective is to be able to search I think a larger pagination batch size is a sooner-or-later losing pattern. What if the one you search for is the 51st experiment and it won't appear when you control-F for "mysearch". 

I'd rather we focus our attention on https://github.com/mozilla/experimenter/issues/400 first.
