### ISSUE TITLE
The section links from the “Edit” side menu are partially actionable for archived drafts

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#8237]
**[Prerequisites]:**

* Have a Rollout draft created.

**[Steps to reproduce]:**

1. Open the draft from prerequisites.
1. Click the “Archive” button.
1. Observe the side menu.
1. Click one of the sections from “Edit” (e.g. “Overview”).
1. Make an edit to a field
1. Save or "Save and Continue"

**[Expected result]:**

* The links from the “Edit” section are not actionable anymore.

**[Actual result]:**

* The links from the “Edit” section are actionable.

**[Notes]:**

* For rollouts, the pages open and can be edited, but not saved. Archiving a rollout while on one of the sections will also not redirect the user to the Summary page.
* For experiments, the links can be clicked, but will not open the pages.
* Attached is a recording of the issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-3119)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/33588">archived rollout vs experiment.gif</a>

**Comment by eliserichards** [comment]
Still reproducible. The problem shows up when you try to click save: 
<img width="1803" alt="image" src="https://user-images.githubusercontent.com/43795363/226732673-c9b17783-0df7-41d4-88b8-ac22d20e4cce.png">
