### ISSUE TITLE
Use updated_date_time instead of changed_on

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#8246]
We can use the new `-_updated_date_time` instead of `-changed_on`. Change all of the models and tests to match.

example: https://github.com/mozilla/experimenter/blob/29986536ccb52fa9390e2d041f360dda277b13e2/app/experimenter/experiments/models.py#L68

_Originally posted by @yashikakhurana in https://github.com/mozilla/experimenter/pull/8235#discussion_r1096123714_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3128)

**Comment by jaredlockhart** [comment]
Oh, two different models.  `-changed_on` is on the NimbusChangeLog model, whereas `-_updated_date_time` is on NimbusExperiment.  Do you mean change this to `-_updated_date_time`?  Which we should definitely do.

https://github.com/mozilla/experimenter/blob/29986536ccb52fa9390e2d041f360dda277b13e2/app/experimenter/experiments/models.py#L60-L61

**Comment by 0x0god** [comment]
I'm an Outreachy intern, I just updated this issue on https://github.com/mozilla/experimenter/pull/8415

**Comment by yashikakhurana** [comment]
for more context, this issue is not renaming the field of `NimbusChangelog` model, we have this method- https://github.com/mozilla/experimenter/blob/15025e794d5287c1efbdd77e28d69adade366c02/app/experimenter/experiments/models.py#L54 which uses changelog `changes_on`, since we have added `_updated_date_time`, we should use that field in the method.

**Comment by kennedy-muthaura** [comment]
hello @yashikakhurana , if the task is still available assign it to me please

**Comment by yashikakhurana** [comment]
@kennedy-muthaura  if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

**Comment by kennedy-muthaura** [comment]
> @kennedy-muthaura if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

I submitted a new PR
