### ISSUE TITLE
Filling in a search query on Nimbus landing page before experiments load does not apply filter

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#8254]
If you start typing a search query, or possibly any other filter, before the experiments have finished loading, after they load they will not be filtered, so then you have to clear your filters and reapply them.  Maybe there's some way to apply the filters on the first load?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3131)

**Comment by judengaba** [comment]
Hello @yashikakhurana, I am an outreachy applicant and very interested in this task. Could you please assign this to me?

**Comment by yashikakhurana** [comment]
sure @judengaba thank you, let me know if you need help

**Comment by Karimat22** [comment]
Hello @yashikakhurana, I am an outreachy applicant and very interested in this task. Could you please assign this to me?

**Comment by yashikakhurana** [comment]
@Karimat22 this task is already assigned, do you mind looking for other tasks, thank you

**Comment by Karimat22** [comment]
@yashikakhurana yes, ma. I wouldn't mind. 

And ma could you please put me through the whole contribution period, I'm find it difficult to understand the whole process on the website. 

Thank you ma.

**Comment by Karimat22** [comment]
Hello @Benjamin Forehand Jr, I am an outreachy new intern applicant and very interested in this task. Could you please assign this to me?

**Comment by yashikakhurana** [comment]
@Karimat22 this task is already, would suggest finding non-assigned tasks

**Comment by yashikakhurana** [comment]
@judengaba if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

**Comment by judengaba** [comment]
@yashikakhurana sorry I haven't been able to make a PR yet. I'm having some
issues with the codebase. But I hope by tomorrow I'll be able to push my
work.

**Comment by yashikakhurana** [comment]
@judengaba  if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

**Comment by cherish2003** [comment]
@yashikakhurana Can you assign me this issue i would like to work on this

**Comment by cherish2003** [comment]
@yashikakhurana @jaredlockhart kindly review the PR #8551 to close this issue .Thank you 😃

**Comment by cherish2003** [comment]
@yashikakhurana mam now i think the filling issue is rectified but the filter issue still exists the filters on the nimbus landing page are not removing after the page reload and this is produced when new experiment is created so now i will start working towards it make a PR soon.

**Comment by cherish2003** [comment]
@yashikakhurana kindly review the PR #8606 to close this issue

**Comment by cherish2003** [comment]
@yashikakhurana @jaredlockhart  can you elaborate steps to reproduce this issue i am sort of getting confused to produce this issue

**Comment by cherish2003** [comment]
@yashikakhurana @jaredlockhart  can you kindly explain the steps to reproduce this issue

**Comment by yashikakhurana** [comment]
@cherish2003 you will see it takes time to load the experiments when you visit the main page which list all the experiments, and in meanwhile if you apply filters before the completion of loading of experiments, and the loaded gets completed, filters have no effect, you have to manually remove it and then apply filters again actually to see the difference, you can add more experiments using factory method, try to load 1500-2000 experiments, then you will see the difference,  do `make refresh up` 
```
make bash
./manage.py shell
from experimenter.experiments.tests.factories import NimbusExperimentFactory
for i in range(2000):
    NimbusExperimentFactory.create_with_lifecycle(NimbusExperimentFactory.Lifecycles.ENDING_APPROVE_APPROVE)
```

**Comment by cherish2003** [comment]
> @cherish2003 you will see it takes time to load the experiments when you visit the main page which list all the experiments, and in meanwhile if you apply filters before the completion of loading of experiments, and the loaded gets completed, filters have no effect, you have to manually remove it and then apply filters again actually to see the difference, you can add more experiments using factory method, try to load 1500-2000 experiments, then you will see the difference, do `make refresh up`
> 
> ```
> make bash
> ./manage.py shell
> from experimenter.experiments.tests.factories import NimbusExperimentFactory
> for i in range(2000):
>     NimbusExperimentFactory.create_with_lifecycle(NimbusExperimentFactory.Lifecycles.ENDING_APPROVE_APPROVE)
> ```

Okay got it mam @yashikakhurana Thank you for your response
