### ISSUE TITLE
Help linking to Mana from the individual Risks isn't working

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#836]
From the Risk page, all of those questions "help" links should go to the top of the Risk Help.   Not going to link to each individual one - but just to the section.

https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-Risks&Testing

**Comment by jaredkerim** [comment]
@shell1 It does link to the Risk section but the first time you go to mana it does it automatic login redirect which throws out the actual url you were going to go, so it only works the second time you click on the help.  Without getting the security team to change the way the auth redirects work I don't think there's a way to fix this =/

**Comment by shell1** [comment]
that is weird.  I couldn't get the links to open mana yesterday at all - even with a few clicks.  working today.  must be human error.  totally fine with the auth0 issue of just going to the main mana page for studies - instead of the specific one.
