### ISSUE TITLE
Rename buttons when the experiment is a rollout

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#8368]
When an experiment is a rollout (is_rollout=True), we can change the strings to say "rollout" instead of "experiment".

Examples where this could change: 
- "End experiment" button -> "End rollout"
- ...

_Originally posted by @yashikakhurana in https://github.com/mozilla/experimenter/pull/8366#discussion_r1122337067_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3206)

**Comment by betty-alagwu** [comment]
Hello, i'm an outreachy participant and i will like to work on this.

**Comment by yashikakhurana** [comment]
sure, thank you for your interest, I am assigning you this ticket :)

**Comment by yashikakhurana** [comment]
@betty-alagwu if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

**Comment by betty-alagwu** [comment]
Hello, @yashikakhurana 

I’ve been stuck on this while trying to understand the code base. 

Please kindly reassign to someone else while I get up to speed. 

Thank you for your prompt.

**Comment by yashikakhurana** [comment]
sure, @betty-alagwu thank you for letting me know, please feel free to grab other ticket :)

**Comment by kennedy-muthaura** [comment]
Hello, i'm an outreachy participant and i would like to work on this.. please assign me this

**Comment by kennedy-muthaura** [comment]
@yashikakhurana  I am currently assigned another task issue #8246. you can assign this to someone else since many people from outreachy are looking forward to being assigned a task. if it's not assigned by the time am done with the current task I will ask you to reassign me again. thank you

**Comment by KramStyles** [comment]
@yashikakhurana can I please get assigned to this ?
