### ISSUE TITLE
Integration test for editing live rollout

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#8378]
Once all of the review forms are ready to go, we can enable the population percent fields on the audience page for live rollouts. Let’s make an integration test for “create - launch - update - launch”.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3212)

**Comment by data-sync-user** [comment]
➤ Benjamin Forehand Jr. commented:

I can see a few test cases here. Do you mind defining the cases here?

**Comment by eliserichards** [comment]
When an update is requested (“Request update” button in the “Actions” sections), the user can go through the familiar review flow (approve/reject in Experimenter, then approve/reject in Remote Settings). 

We want our tests to cover the following scenarios:

   * Live rollout → Edit population % → Request update → Approve in Exp → Approve in RS
   * Live rollout → Edit population % → Request update → Approve in Exp → Reject in RS
   * Live rollout → Edit population % → Request update → Reject in Exp

**Comment by eliserichards** [comment]
The summary page for the experiment should show Live status, no "Unpublished changes" status or "Request update", and should reflect the updated population percentage

**Comment by data-sync-user** [comment]
➤ Elise Richards commented:

🚩 Flag added

Having some weird errors on CI that I can't reproduce locally. Once Ben is back we can pair on this
