### ISSUE TITLE
create new Django app- changelogs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#8393]
In the existing Django project, create a new app with the name 

```python
changelog
```

we already have an existing app called experiments.

Refer here to learn about how to create a Django app [Django app create tutorial](https://docs.djangoproject.com/en/4.1/intro/tutorial01/)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3223)

**Comment by data-sync-user** [comment]
➤ Yashika Khurana commented:

* Create the app using the startapp command
  * Organize the files and folders inside the app directory

**Comment by siddhi-244** [comment]
Can I work on this? I am a outreachy participant and really interested in this project

**Comment by siddhi-244** [comment]
Thank you ! Will start working on it !

**Comment by siddhi-244** [comment]
Also there is no steps on installing docker on windows !

**Comment by yashikakhurana** [comment]
you can refer to the official doc here- https://docs.docker.com/desktop/install/windows-install/

**Comment by siddhi-244** [comment]
> you can refer to the official doc here- https://docs.docker.com/desktop/install/windows-install/

Thank you !

**Comment by yashikakhurana** [comment]
@siddhi-244 I am so sorry, I have to remove this issue for Outreachy tasks, please feel free to look at other issues, and let me know if you need any help.
