### ISSUE TITLE
Live rollout without any changes shows 'Unpublished Changes'

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#8396]
I just noticed a live rollout here:

https://experimenter.services.mozilla.com/nimbus/mozilla-rally-convert-core-add-on-users-to-attention-stream-2nd-rollout/summary

is showing 'Unpublished Changes' even though there can't be any unpublished changes since we haven't landed that functionality yet:

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/119884/223172917-17061c78-5c38-4ad3-91c9-4e91cb11a00b.png">

Currently in status LIVE/LIVE/WAITING

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3225)

**Comment by data-sync-user** [comment]
➤ Elise Richards commented:

This will be invalid once https://mozilla-hub.atlassian.net/browse/EXP-3123 ( https://mozilla-hub.atlassian.net/browse/EXP-3123|smart-link ) is merged

**Comment by data-sync-user** [comment]
➤ Elise Richards commented:

Closing since this is no longer valid.
