### ISSUE TITLE
Live rollout shows 'Updated Audience' with no audience change

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#8397]
This is an interesting one.  This live rollout here:

https://experimenter.services.mozilla.com/nimbus/experiment-for-additional-metrics-for-product-insights-rollout-100/summary

Shows 'Unpublished Changes'.  The admin shows that it is dirty and has an 'Updated Audience' changelog triggered by a user.

The diff for that changelog shows the only change as:

<img width="947" alt="image" src="https://user-images.githubusercontent.com/119884/223175804-c423f1dd-4c4c-4146-b201-1a0089a4b2b8.png">

This is set whenever the start_date is requested but not cached.  It's not clear how that would trigger 

1) generating a changelog
2) flipping the status to DIRTY

Even though the Audience page is now viewable for live experiments, the 'Save' buttons are disabled so a user shouldn't be able to trigger those.  

Let's figure out how a live rollout got into this state.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3226)

**Comment by eliserichards** [comment]
ahh interesting. This scenario _does_ pass all of the checks for updating to dirty: 

```
            experiment.is_rollout
            and not experiment.is_paused
            and experiment.status == NimbusExperiment.Status.LIVE
            and experiment.status_next is None
            and experiment.publish_status == NimbusExperiment.PublishStatus.IDLE
            and validated_data.get("publish_status")
            != NimbusConstants.PublishStatus.REVIEW
```

The easiest way to figure out if this is a live update to population percent would be to check that field. Not sure if there's another way to differentiate this...

**Comment by jaredlockhart** [comment]
No movement on this for a year so I'm going to close and if it comes up again we can refile.
