### ISSUE TITLE
Create templates for the Changelogs app

### ISSUE THREAD

**Issue by yashikakhurana** [mozilla/experimenter#8414]
Define the templates needed for the app's views
Create a base template that other templates can inherit from
Ensure the templates are properly rendered with the necessary context

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3233)

**Comment by CharityKithaka** [comment]
Hey,@yashikakhurana could I work on this issue?

**Comment by Kisavi** [comment]
Hello @yashikakhurana. I am an Outreachy applicant and I would love to participate in this experimenter project by working on this issue.

**Comment by tobidosumu** [comment]
Hello @yashikakhurana. I am also an Outreachy applicant. I am excited about this project and would love to contribute to it.

**Comment by yashikakhurana** [comment]
@tobidosumu do you mind choosing another issue, as @Kisavi asked first, it is totally based on the first come first basis,

**Comment by yashikakhurana** [comment]
@Kisavi do note that this issue is blocked until this get released- https://github.com/mozilla/experimenter/issues/8393

**Comment by tobidosumu** [comment]
Ok. I will look for another issue I can make meaningful contributions to. Thanks for the feedback.

**Comment by KramStyles** [comment]
> Hello @yashikakhurana. Thank you for your response. I am not sure though I understand what this means. `do note that this issue is blocked until this get released- #8393` Could you kindly explain? Thank you

Hello @Kisavi it means an issue or tasks is blocking your task. You can't proceed without that issue solved. For instance, you are supposed to create templates for the `changelogs app` but the`changelogs app` hasn't been created. 

Creating the changelog app is another issue: [https://github.com/mozilla/experimenter/issues/8393](8393). Do you understand? If you don't do let me know. My task is also blocked alongside yours 😄

**Comment by Kisavi** [comment]
Hello @KramStyles. Thank you for the clarification. I guess I will use that time to fully setup the repo to have it fully running and functional on my machine. Have you been able to set up yours on your machine?

**Comment by yashikakhurana** [comment]
@KramStyles thank you for helping @Kisavi , @KramStyles absolutely correct, let me know if you have any other questions :)

**Comment by yashikakhurana** [comment]
@Kisavi  I am so sorry, I have to remove this issue for Outreachy tasks, please feel free to look at other issues, and let me know if you need any help.

**Comment by Kisavi** [comment]
@yashikakhurana Okay. Thank you for the feedback. Let me look up at another issue that I can pick to work on
