### ISSUE TITLE
Unpublished Changes doesn't show in mid review flow

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#8416]
When a rollout goes from REVIEW > APPROVED the 'Unpublished Changes' pill disappears:

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/119884/223259684-f82dc1ef-1066-425a-aa19-d2a3f2d6e5d7.png">

and then reappears when it goes from APPROVED > WAITING

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/119884/223259847-e4e42657-23c8-4e7a-93f8-4e7cb835451f.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3234)

**Comment by jrbenny35** [comment]
Would be nice to have this checked within the integration tests in #8378
