### ISSUE TITLE
Data loss when "Save draft and continue" intercepted by OAuth

### ISSUE THREAD

**Issue by felixlawrence** [mozilla/experimenter#842]
I took an hour or two to fill out step 3 of a new experiment. When I clicked "Save Draft and Continue", the usual OAuth prompt flashed on the screen momentarily (it didn't ask me to enter passwords or go through 2FA) and then I was redirected back to step 3, but missing all the text I had entered.

I've noticed that the post-auth redirects for Experimenter often fail, meaning that I have to manually re-navigate to the target page (e.g. enter the URL manually again); this could be related?

Thankfully in this instance I was able to retrieve my work by navigating backwards, but it was a scary event nevertheless.

**Comment by jaredkerim** [comment]
Yes this is a known issue: #247, and it is definitely a major problem but I don't know what the ideal solution looks like.  Maybe after we switch to GCP and use the google auntheticator it'll be smarter about this.
