### ISSUE TITLE
Hello @yashikakhurana, I am a new outreachy intern applicant and very interested in this task. Could you please assign this to me?

### ISSUE THREAD

**Issue by Karimat22** [mozilla/experimenter#8425]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3238)

**Comment by yashikakhurana** [comment]
@Karimat22 you have to search from the list of issues, take a look at the outreachy project descriptions, you will find more info on how to find an issue to work on, thanks

**Comment by Karimat22** [comment]
@yashikakhurana Thank you for your information I will do as you instructed.
