### ISSUE TITLE
Search bar cross overlapping

### ISSUE THREAD

**Issue by yashikakhurana** [mozilla/experimenter#8428]
If we write a long string in search bar, it overlaps the search cancel button
![image](https://user-images.githubusercontent.com/25848231/223574133-75da1751-8be7-4113-80b9-8df8c66c7118.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3241)

**Comment by ChiedozieOH** [comment]
Hello, It's Chiedozie, I can handle this.

**Comment by yashikakhurana** [comment]
@ChiedozieOH are you outreachy?

**Comment by yashikakhurana** [comment]
sure I assigned it to you

**Comment by ChiedozieOH** [comment]
> 

Yes, I am

**Comment by ChiedozieOH** [comment]
> 

Thank you, I'll get right on it

**Comment by yashikakhurana** [comment]
@ChiedozieOH if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

**Comment by ChiedozieOH** [comment]
> Hey @ChiedozieOH can we collaborate on this?

Definitely

**Comment by ChiedozieOH** [comment]
I'm working

**Comment by ChiedozieOH** [comment]
@Yass32 you have WhatsApp?

So we can correspond effectively?

**Comment by Yass32** [comment]
Sure @ChiedozieOH  send me your WhatsApp number

**Comment by yashikakhurana** [comment]
@ChiedozieOH  if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

**Comment by cherish2003** [comment]
@yashikakhurana [#8536 ](https://github.com/mozilla/experimenter/pull/8536) kindly review this PR to close this issue

**Comment by Mehak-4545** [comment]
Hello @yashikakhurana , I am Mehak, an Outreachy applicant. If the overlapping searchbar issue is still open and unassigned, I would like to work on it. Can it be assigned to me?

**Comment by yashikakhurana** [comment]
@Mehak-4545 someone already submitted a PR, would suggest finding other issue :)
