### ISSUE TITLE
Add learn more link for rollouts checkbox

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#8429]
On the audience page, let's add a "Learn more" link next to the rollouts checkbox ("This is a rollout (single branch)"). The learn more link should take you here: https://experimenter.info/deep-dives/experimenter/rollouts

<img width="1980" alt="image" src="https://user-images.githubusercontent.com/43795363/223574277-c25c5894-a2f5-4a02-8562-5b384854b94e.png">

Example: https://github.com/mozilla/experimenter/blob/cf4809ae017f4b04ce6f8cc41d51f00be37df5d7/app/experimenter/nimbus-ui/src/components/PageEditAudience/FormAudience/index.tsx#L359 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3242)

**Comment by KramStyles** [comment]
Please @eliserichards can this be assigned to me?!

**Comment by Yass32** [comment]
Hey @KramStyles can we collaborate on this?

**Comment by yashikakhurana** [comment]
closing https://github.com/mozilla/experimenter/pull/8457

**Comment by KramStyles** [comment]
> Hey @KramStyles can we collaborate on this?

@Yass32 Oh. That would be great but this PR has been closed.
