### ISSUE TITLE
Miss

### ISSUE THREAD

**Issue by Karimat22** [mozilla/experimenter#8431]
I’m open to learn. I’m a newbie in Tech.

kindly help a sisterhood 

thanks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3244)

**Comment by yashikakhurana** [comment]
Hi @Karimat22 you can find more info here-  https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/firefox/#history-tracker
