### ISSUE TITLE
Alphabetize Meta fields in v5 serializer

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#8440]
Reorder the Meta fields in the [v5 serializer](https://github.com/mozilla/experimenter/blob/a462dc03c04d0135d0b21228d532756992397a94/app/experimenter/experiments/api/v5/serializers.py#L840) so that they are in alphabetical order.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3258)

**Comment by Med16-11** [comment]
Hello @eliserichards @yashikakhurana I am an Outreachy applicant from India and would like to work on this task.

**Comment by Yass32** [comment]
Hello @eliserichards Im a new outreachy applicant, id like to be assigned this task

**Comment by jakada01** [comment]
Hello @yashikakhurana , @eliserichards. My name is Yusuf, and i am an outreachy applicant participating in the 2023 outreachy program. I would like to start my contribution by working on this issue. Please assign me to work on this issue. I am also available for future issues that may arise. Thank you.

**Comment by yashikakhurana** [comment]
assigning issue based on first request, kindly please search for other issues
