### ISSUE TITLE
[Enhancement] A warning that informs that the entered data will be lost should be displayed when changing the "Edit sections" without manually saving after editing

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#845]
**[Affected versions]:**
- Firefox Release 65.0 and above
- Chrome 71.0.3578.98

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile created.
- Have an experiment created on the "https://experimenter.stage.mozaws.net/" website.
- You are logged in your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites and click the "Edit" button from "Overview" section .
3. Change the name of the experiment from the "Name" section.
4. Click the "2. Population" section from the top of the page.
5. Observe the behavior.

**[Expected result]:**
- A warning that the entered data will be lost is displayed.

**[Actual result]:**
- You are redirected to the "2. Population" section and the changes made are deleted.

**[Notes]:**
- The changes made are deleted if you jump through any of the the "Edit sections", even if you click on the same section you are editing.
- The data from the first edited section is deleted even after you save changes on the other "Edit sections".
- Attached is a screen recording of the issue: 
![savechanges](https://user-images.githubusercontent.com/40061643/52069157-d4f23800-2586-11e9-82ee-0cda385eb5c8.gif)

**Comment by shell1** [comment]
this is true - but hasn't come up as much as we'd thought.  people do it once and then not again.  we are building other guardrails in for higher risk issues.
