### ISSUE TITLE
Pref branch and type are not reflected on detail page

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#846]
We collect and store information about the pref branch and type but it's not reflected on the detail page so with the current work flow will not be communicated to normandy, which defeats the purpose of collecting it in the first place.

**Comment by peterbe** [comment]
@leplatrem Why are your commits, mentioned above, tied to this issue?

**Comment by leplatrem** [comment]
> @leplatrem Why are your commits, mentioned above, tied to this issue? 

Thanks for pinging me, it was #821, I wonder why I got mixed up
