### ISSUE TITLE
There is a inconsistency in the "Proposed Enrollment Duration" section between the description an the error message displayed regarding the enrollment duration

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#847]
**[Affected versions]:**
- Firefox Release 65.0 and above
- Chrome 71.0.3578.98

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile created.
- Have an experiment created on the "https://experimenter.stage.mozaws.net/" website.
- You are logged in your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites and click the "Edit" button from "Timeline" section.
3. Insert a higher number in the "Proposed Enrollment Duration" input field then the one displayed in the "Proposed Experiment Duration" input field.
4. Click the "Save Draft" button.
5. Click the "Help" button from the "Proposed Enrollment Duration".
6. Observe the duration of enrollment described in the error message and the one in the description displayed under the error message. 

**[Expected result]:**
- The descriptions provided and the error message imply the same enrollment duration.

**[Actual result]:**
- The error message implies that the duration must be "less than or equal"  to the experiment duration and the description implies that the duration must be "shorter" than the experiment duration.

**[Notes]:**
- Attached is a screen shot of the issue: 
![enrollment](https://user-images.githubusercontent.com/40061643/52124558-420ed780-2632-11e9-8bd1-2e14d6ab18f1.PNG)

**Comment by shell1** [comment]
moved back to genuine bug (since it's guidance for new concept) - @shell1 to get the rest of how this works....

Replace the "must be less than or equal to" to "must be shorter than". 

Add to the end of that help. 
"If there is no enrollment duration period specified, enrollment continues throughout the Experiment Duration until _______.

Shell find out if it is until the study end or until it hits the target population size or both - how does this really work :)

**Comment by jaredkerim** [comment]
@shell1 I think we need to figure this out a little bit more.

If we allow the user to enter `enrollment duration` that's the exact same as the 'experiment duration', then that is the same as not specifying the enrollment duration at all, ie users will continue to enroll for the entire experiment.  

We might want to prevent that just to make it clearer that you should only use the `enrollment duration` if you specifically want a period shorter than the actual length of the experiment for enrollment.  Then we'd have to change the logic and messaging to reflect that.

**Comment by shell1** [comment]
Change that line in Red to read.  "Enrollment duration is optional, but if set, must be lower than the experiment duration.   If it enrollment duration not specified - users are enrolled for the entire experiment"

**Comment by uhlissuh** [comment]
I can't tell exactly what's going on here in the comments/history of this ticket... but I am submitted a PR for changing the text to read as above in @shell1 's comment.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible after the v2.31.0 stage deployment on [Experimenter stage](https://stage.experimenter.nonprod.dataops.mozgcp.net/) website.
Tested on Windows 10 x64, Mac 10.14 and Arch Linux 4.16.6 x64.
