### ISSUE TITLE
[Windows] There are UI issues displayed on different sections when using high contrast themes 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/experimenter#848]
**[Affected versions]:**
- Firefox Release 65.0 and above

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a new Firefox profile created.
- Have an experiment created on the "https://experimenter.stage.mozaws.net/" website.
- You are logged in your LDAP account.
- High Contrast 2 Theme is enabled from Windows' Settings.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites and click the "Edit" button from "Overview" section.
3. Observe the arrow buttons from the Proposed Experiment Duration (or Enrollment) from the right side of the field.
4. Hover the Proposed Experiment Duration field and observe the tooltip.

**[Expected result]:**
- Step 3 - The "Up" and "Down" arrows are visible.
- Step 4 - "Please enter a number" tooltip text is displayed.

**[Actual result]:**
- Step 3 - A rectangle button is displayed instead of arrows.
- Step 4 - The tooltip's text is not visible.

**[Notes]:**
- The arrow buttons issue is also reproducible when using the other High Contrast themes.
- Please see the screencast attached.

![tst](https://user-images.githubusercontent.com/26000308/52125435-23f6a680-2635-11e9-91c0-51cf900946c0.gif)

**Comment by shell1** [comment]
we are still working out the right content - so without a driving current need for high-contrast internally... we will delay this until a later date.  closing for now and will revisit at a stable point.
