### ISSUE TITLE
Store search results

### ISSUE THREAD

**Issue by yashikakhurana** [mozilla/experimenter#8499]
We added a search param in the url- &search="searchterm", when we do write anything in search box on landing page, the &search get assigned like this, 
![image](https://user-images.githubusercontent.com/25848231/225158223-8c4744f3-2d4c-4826-ada8-40abe29bcd15.png)
but whenever we click on any experiment, lets say this 
![image](https://user-images.githubusercontent.com/25848231/225158431-28158b1f-bb72-4882-8304-b5e0a7f406b8.png)
and then click on back to experiments, 
![image](https://user-images.githubusercontent.com/25848231/225158524-36c000fb-6d1c-4a5f-9656-3ac57e0900cf.png)
the filtered results are no longer present and search query get empty

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3277)

**Comment by KramStyles** [comment]
@yashikakhurana can I please get this task assigned to me?!
