### ISSUE TITLE
Replace constants

### ISSUE THREAD

**Issue by yashikakhurana** [mozilla/experimenter#8500]
`NimbusExperiment` model inherits `NimbusConstants` 
``` python class NimbusExperiment(NimbusConstants, TargetingConstants, FilterMixin, models.Model):```

 https://github.com/mozilla/experimenter/blob/86c4d1d7e8c9ab20d1a5d07568cb542655238266/experimenter/experimenter/experiments/models.py#L109

so essentially you can on Nimbus experiment model like this `self.Application.DESKTOP` like here- https://github.com/mozilla/experimenter/blob/86c4d1d7e8c9ab20d1a5d07568cb542655238266/experimenter/experimenter/experiments/models.py#L287
so that means instead of writing `NimbusConstants.Application.Desktop`, you can write `NimbusExperiment.Application.Desktop` there are many place where we can replace constants with NimbusExperiment.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3278)

**Comment by cherish2003** [comment]
@yashikakhurana can you assign me this issue i am outreach applicant

**Comment by satyamksharma** [comment]
Hi there @yashikakhurana I would like to contribute to the project being an outreachy applicant so please assign me.

**Comment by yashikakhurana** [comment]
@cherish2003 and @satyamksharma I have assigned you other tasks, I would suggest work on that and tag me again for the assignment once you are done with that :)

**Comment by Shofiya2003** [comment]
Hello
I am an outreachy applicant and interested in working on this issue @yashikakhurana .

**Comment by kennedy-muthaura** [comment]
@yashikakhurana  please assign me this

**Comment by Shofiya2003** [comment]
Apologies for the delay. I am occupied with some other tasks so could not complete the issue. You can reassign the issue. @yashikakhurana
