### ISSUE TITLE
Add a text copy button next to the experiment slug on the summary page

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#8530]
Let's add one of those handy dandy 'copy to clipboard' type buttons next to the experiment slug on the summary page.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3299)

**Comment by Avi-88** [comment]
Hello @yashika-khurana ma'am, I'd like to work on this issue could you please assign it to me, thanks

**Comment by cherish2003** [comment]
@jaredlockhart @yashikakhurana  i am outreachy applicant i would like to work on this issue

**Comment by Avi-88** [comment]
Hi @jaredlockhart sir and @yashika-khurana ma'am, I've added the button but I've not been able to write a good test for it. I tried creating a mock function for the `navigator.clipboard.writeText` function but it's not getting called, could you please guide me on what I could be doing wrong, thank you

**Comment by yashikakhurana** [comment]
@Avi-88 you can refer to this conversation- https://stackoverflow.com/questions/61807378/jest-test-for-a-copy-to-clipboard-method-using-react-with-typescript

**Comment by Avi-88** [comment]
I did refer to this specific answer before but couldn't figure it out. I'll try once again , thank you ma'am
