### ISSUE TITLE
Log experiment slug in jetstream fetch task

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#8531]
It would be helpful to include the experiment slug in the jetstream fetch task logging so that we can inspect task logs in the Google Cloud Console for a given experiment.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3300)

**Comment by mikewilli** [comment]
Looks like we're already logging the `experiment.name`, so while `slug` would probably be more useful, at least we can use `name` in the meantime.
