### ISSUE TITLE
Allow null values while drafting

### ISSUE THREAD

**Issue by felixlawrence** [mozilla/experimenter#854]
When I'm filling out an experimenter form for the first time, I don't have all the required information. E.g. I might not know the rollout schedule, or I might not have done the power analysis. To get the ball rolling I would like to start entering things in the form before all information is ready. Right now, I need to add values for the rollout schedule and % of population: I would much rather leave these fields blank rather than putting dummy values in, because no-one will interpret `NULL` as a real value.

**Comment by felixlawrence** [comment]
Yeah there's a minor wrinkle in the process here from a DS perspective.

A DS must do these things in the following order:
1. Gather/understand/reach consensus on the "Objectives"
2. Propose/reach consensus on the "Analysis" (what probes to look at)
3. Spend time (hours?) doing a power analysis specific to what was decided in (1) and (2)
And only after (3) can the DS give a meaningful figure for the "%" of population. By asking for this number upfront, we're encouraging a random number to be proposed, without a process that explicitly requires that this random number be replaced by a validly chosen one.

**Comment by felixlawrence** [comment]
I guess the question is "how early in the process can we start using this tool?"

If Experimenter could be a home for an experiment "from cradle to grave" - i.e. from the moment the DS and product team start collaborating to define the experiment, until the analysis is done and it's all wrapped up - then that would be a huge win for other teams. Otherwise people will be copying back and forth between experimenter and gdocs.

Does anyone pay attention to draft (pre "ready to ship") experiments? If not, could validation be done at the time of clicking "ready to ship" so that we can use NULL values up to that point?

**Comment by shell1** [comment]
OK - this was getting messy.  closing this and breaking into multiple tickets #900 and #901 (and a few others - will add.
