### ISSUE TITLE
Add firefox version flag to integration test docs

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#8549]
Let's update our docs to specify that we need the following firefox version flag when running integration tests: 

```FIREFOX_VERSION=nimbus-firefox-release```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3311)

**Comment by Prithvi-Chanchal** [comment]
@yashika-khurana I like to work on this one, could you please assign this to me and tell me in which file should I add it?
