### ISSUE TITLE
After entering a number over "1001" with decimals in the "Proposed Experiment Duration" input field, the message and tooltip displayed wrongly suggest that the nearest integer numbers are valid

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#855]
**[Affected versions]:**
- Firefox Release 65.0 and above
- Chrome 71.0.3578.98

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile created.
- Have an experiment created on the "https://experimenter.stage.mozaws.net/" website.
- You are logged in your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites and click the "Edit" button from "Timeline" section.
3. Enter a number over "1001" with decimals in the "Proposed Experiment Duration" input field (eg.1001.5).
4. Click the "Save Draft" button.
5. Observe the message displayed under the "Proposed Experiment Duration" input field.

**[Expected result]:**
- The "Please select a integer valid value under or equal to 1000." message is displayed.

**[Actual result]:**
- The "Please select a valid value. The two nearest valid values  are 1001 and 1002." message is displayed even though the number entered must be under or equal to "1000".

**[Notes]:**
- This issue is also reproducible when completing the steps above and you hover over the "Proposed Experiment Duration" input field, the tooltip displays the same message. 
- This issue is reproducible even if you enter the "1000" number with decimals, the message suggests that you can also enter the number "1001" as valid.
- Attached is a screen recording of the issue:
![over1000](https://user-images.githubusercontent.com/40061643/52212079-56520f00-2894-11e9-86cd-02bc2cccd682.gif)

**Comment by jaredkerim** [comment]
Closing as wontfix per @shell1
