### ISSUE TITLE
Add FAQ link to rollout bucket warning

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#8566]
We [added a new section](https://github.com/mozilla/experimenter-docs/pull/403) on experimenter.info to explain the [bucketing warning](https://github.com/mozilla/experimenter/pull/8362) that shows up for duplicate rollouts.

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/43795363/227015945-3fe10893-287c-4ce7-afd9-bfcb69770209.png">

Let's add a "learn more" link to the [warning](https://github.com/mozilla/experimenter/blob/4197b94a167aa7fa9bf63c58388db4d2238207a6/experimenter/experimenter/nimbus-ui/src/components/PageSummary/index.tsx#L221) that links to the new FAQ: https://experimenter.info/faq/Rollouts-and-experiments#question-2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3322)

**Comment by emmaz12** [comment]
@yashikakhurana I would be interested in taking this on! Thanks :)

**Comment by kennedy-muthaura** [comment]
@yashikakhurana  am willing to work on this, please assign me

**Comment by kennedy-muthaura** [comment]
I submitted a pr for this, Please  review it for me
