### ISSUE TITLE
The message displayed after Canceling an Update Request wrongly references enrollment

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#8596]
**[Prerequisites]:**

* Have a Live rollout open.

**[Steps to reproduce]:**

1. Open the rollout on the “Audience” section.
1. Change the value of “Percent of clients”.
1. Click “Save and Continue”.
1. Click “Request Update”.
1. Click “Cancel Review”.
1. Observe the message displayed.

**[Expected result]:**

* The message displayed mentions that a request for update was canceled.

**[Actual result]:**

* The message displayed reads: “The request to ﹍end enrollment﹍ for this experiment was **Rejected** due to:”

**[Notes]:**

* The message also uses the word “experiment”.
* Attached is a recording of the issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-3330)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/35420">end enrollment for update.mov</a>

**Comment by cherish2003** [comment]
@yashikakhurana i want to work on this issue can you assign me
