### ISSUE TITLE
Checklist Question 5: changing "study" to "experiment" and adding checklist item if "Is this experiment confidential to Mozilla?" is "yes"

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#860]
Update the wording of "is the study confidential to Mozilla" to "Is the experiment confidential to Mozilla?" and add a dynamic checklist item if "yes".

"Yes" radial button selection for this question - should make "VP Sign-off " move to "required". Required means they need to check it before they can click "ready for shipping".

Help for this question should take them to the risks section. https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-Risk

The help next to the actual checklist item should go to the main Dependent section. Linking to the section instead of the specific action, avoids future name changes breaking the header link. https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-DependentSign-offs

Need to add in dummy migrations with any new input needed (fields, radials, etc.).  Add default “no” for Live or Complete experiments.  This avoids “incomplete section” errors -  which block that section from displaying in the read-only mode.

**Comment by tiftran** [comment]
fix included with #858
