### ISSUE TITLE
Update Readme Cloning process

### ISSUE THREAD

**Issue by Philipotieno** [mozilla/experimenter#8604]
It may be of importance to update the `readme.me` with the following after the user has cloned the fork; 

- Add an upstream remote(main repository).
- Ways to update the fork/working-branch with the latest changes on the main repository.

This will enable contributors to keep the forked repository in sync with the main repository.

Over time, the original repository may receive updates or improvements that one may want to incorporate into their forked repository before one starts to contribute. Also, one might face errors, especially if there are many changes to be merged that touch the files the contributor was working on.

The update can be included after this point on the [General setup](https://github.com/mozilla/experimenter#general-setup)

![Screenshot 2023-03-29 at 20 05 35](https://user-images.githubusercontent.com/29012135/228615574-adb0f484-a230-47fe-8e33-126ac6e63cc6.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3335)

**Comment by Haywayaheadshot** [comment]
@yashika-khurana Can I work on this please?

**Comment by yashikakhurana** [comment]
@Philipotieno do you want to work on this or want me to assign @Haywayaheadshot this task? Kindly let me know since you file the issue I am wondering if you have already worked on this

**Comment by Haywayaheadshot** [comment]
@yashikakhurana I had no idea @Philipotieno is also an Outreachy applicant. Since he noticed it, I think it's only right he gets the chance to work on it.

**Comment by Philipotieno** [comment]
@yashikakhurana I'll work on it since I do not have any other task to work on.

**Comment by yashikakhurana** [comment]
closing in favor of- https://github.com/mozilla/experimenter/pull/8618
