### ISSUE TITLE
Intermittent test failure: Test Focus Android and Remote Settings (Release Firefox) CI check

### ISSUE THREAD

**Issue by mikewilli** [mozilla/experimenter#8605]
Sometimes fails, and a re-run from failed on CircleCI fixes it. I noticed it on PR #8600 (see here for failed/successful runs: https://app.circleci.com/pipelines/github/mozilla/experimenter?branch=pull%2F8600), but others have noticed as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3336)

**Comment by jrbenny35** [comment]
I'll keep an eye on this
