### ISSUE TITLE
Checklist question 6: updating the "...large number of release users" risk question to clearer wording and adding dynamic checklist item

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#861]
Update the existing "Does this study affect a large number of Release users?" to say "Does this experiment affect 1% or more of Release users?".  

If "Yes" radial button selection for this question - should make "VP Sign-off " move to "required". Required means they need to check it before they can click "ready for shipping".

Help for this question should take them to the risks section. https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-Risk

The help next to the actual checklist item should go to the main Dependent section. Linking to the section instead of the specific action, avoids future name changes breaking the header link. https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-DependentSign-offs

Need to add in dummy migrations with any new input needed (fields, radials, etc.).  Add default “no” for Live or Complete experiments.  This avoids “incomplete section” errors -  which block that section from displaying in the read-only mode.

**Comment by tiftran** [comment]
fix included with #858
