### ISSUE TITLE
Update sequence diagrams to use Mermaid

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#8623]
We want to switch our sequence diagrams over to using Mermaid [https://mermaid.js.org/syntax/sequenceDiagram.html](https://mermaid.js.org/syntax/sequenceDiagram.html|smart-link) . After we do this, we can do [https://mozilla-hub.atlassian.net/browse/EXP-3319](https://mozilla-hub.atlassian.net/browse/EXP-3319|smart-link) 

[https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/|smart-link)

[https://github.com/mermaid-js/mermaid/issues/1844](https://github.com/mermaid-js/mermaid/issues/1844|smart-link)  

[https://github.com/JakeSteam/Mermaid/blob/main/sequence.md](https://github.com/JakeSteam/Mermaid/blob/main/sequence.md|smart-link) 

[https://jojozhuang.github.io/tutorial/mermaid-cheat-sheet/](https://jojozhuang.github.io/tutorial/mermaid-cheat-sheet/|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3339)

**Comment by eliserichards** [comment]
- [ ] Draft create
- [ ] Preview
- [ ] Publish (approve/approve)
- [ ] Publish (reject/---)
- [ ] Publish (approve/reject)
- [ ] Publish (approve/reject + manual rollback)
- [ ] Publish (approve/timeout)
