### ISSUE TITLE
Have to double click to get into the results section now

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#8628]
Najla reported and Shell able to replicate - looking at [windows vs tab modal](https://experimenter.services.mozilla.com/nimbus/window-modal-vs-tab-modal/summary) and [colorways](https://experimenter.services.mozilla.com/nimbus/colorways-expiring-fx108/summary) experiment results.

I have to double-click to get off the summary page and into anywhere in results.  Single click seems to take me there (flicker or scrolls and then scrolls back) then takes me right back to summary.  

The was a single click action before and all other links on left are still single click that I tested (opening any of the links or returning to Summary).

Once in the results section - you can single click around the different metric areas.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3347)

**Comment by mikewilli** [comment]
Seems likely to have been caused by #8620 -- if I can't spot an obvious fix we can just roll that back for the time being.
