### ISSUE TITLE
Add date of expected Results page availability

### ISSUE THREAD

**Issue by mikewilli** [mozilla/experimenter#8651]
The Results page link is unavailable for a period of time until the weekly/overall results get calculated (a week after enrollment ends). We should be able to calculate the date that the link will become available and indicate this to users.

Before enrollment ends, we can either a) calculate based off of the proposed enrollment and include a caveat, or b) just indicate that results will be available a week after enrollment ends, whenever that is.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3368)

**Comment by Daniel-olaO** [comment]
Hi, I'm new to OS, can I address this issue

**Comment by mikewilli** [comment]
Hi @Daniel-olaO, thanks for your interest! I would recommend getting started with a bug that has the `good-first-bug` label ([link](https://github.com/mozilla/experimenter/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-bug)).
