### ISSUE TITLE
Checklist question 11: Does this feature need security review, consulting, or security testing?

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#866]
"Yes" radial button selection for this question - should make "Security Review" move to "required". Required means they need to check it before they can click "ready for shipping".

Help for this question should take them to the risks section. https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-Risk

The help next to the actual checklist item should go to the main Dependent section. Linking to the section instead of the specific action, avoids future name changes breaking the header link. https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-DependentSign-offs

Need to add in dummy migrations with any new input needed (fields, radials, etc.).  Add default “no” for Live or Complete experiments.  This avoids “incomplete section” errors -  which block that section from displaying in the read-only mode.

**Comment by tiftran** [comment]
@shell1 just wanted to double check with you if you wanted "feature" in this question to be "experiment" or is it fine the way it is?

**Comment by shell1** [comment]
"does this require..."
