### ISSUE TITLE
Add new targeting for users that have a default pref for `network.trr.mode`

### ISSUE THREAD

**Issue by valenting** [mozilla/experimenter#8689]
In the [ohttp](https://experimenter.services.mozilla.com/nimbus/dns-ohttp-dooh/summary) experiment we want to target only the users that haven't changed their TRR settings.
I thought about adding `"trrMode": 0` to both branches, but the `trrMode` is in a separate feature configuration.
As such, we'd need a separate targeting for users that _do not_ have a user set value for the  `network.trr.mode` pref.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3387)

**Comment by valenting** [comment]
See #8696

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/pull/8696
