### ISSUE TITLE
Update Risk box help - once dynamic checklist capability is enabled.

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#870]
The Risk help provided inside the box was updated recently - to point people to manually read the mana guidance and determine what they need to do.  The wording below should be updated AFTER dynamic checklist goes it - as it lets them know how their answers impact the "required items".

New copy below:

The Required checklist items for this study will be adjusted based on your “Yes” answers.  

If you answered "Yes" to any of the question above - this box is the area to capture the details.  Please include why you think the risk is worth it or needed for this experiment.  Please also include any known mitigating factors for each risk.

This information is used to collaborate with supporting teams (ex: for sign-offs). Good details avoid assumptions or delays while people locate the information necessary to make an informed decision.

**Comment by tiftran** [comment]
@shell1  @jaredkerim just want to clarify this issue.

Currently inside the risk text box it it has the message stated in this ticket. Is the ask of this ticket to remove the help text? and If, so is there anything replacing it? or am I interpreting this completely wrong?

![Screen Shot 2019-04-24 at 2 15 09 PM](https://user-images.githubusercontent.com/25379936/56695719-8d1f1080-669e-11e9-8cd6-a7bfd298887c.png)

**Comment by jaredkerim** [comment]
Yeah it looks like this is already done.  @shell1 if this is already done, can you close this?
