### ISSUE TITLE
[docs] Links between pages not working after refreshing page

### ISSUE THREAD

**Issue by moztcampbell** [mozilla/experimenter#8727]
When I visit https://experimenter.info/desktop-feature-api/ (from other documentation repos) then links in the first paragraph to related doc pages do not work. This is because the trailing `/` causes browser to try loading related docs as though they were inside a directory.

If I use the sidebar to navigate, then the `/` gets disappeared and links work. If I refresh the page that I am on, the browser puts the `/` back (due to a server redirect) and links no longer work properly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3414)

**Comment by eliserichards** [comment]
Thank you so much for letting us know!!

**Comment by eliserichards** [comment]
This should be working now @moztcampbell 👍
