### ISSUE TITLE
Branches Description: newlines are hidden when not editing

### ISSUE THREAD

**Issue by arthuredelstein** [mozilla/experimenter#875]
Hi -- I added some text to a description in one of my experiment branches. This text contains newlines (a bulleted list) and when the I finish editing, the newlines are not displayed, so it is hard to read. Please see https://experimenter.services.mozilla.com/experiments/strict-list-cookie-restrictions/#branches

**Comment by arthuredelstein** [comment]
Editing:
![image](https://user-images.githubusercontent.com/355566/52246634-4be74380-289b-11e9-94ba-de588b61533f.png)

Displayed:
![image](https://user-images.githubusercontent.com/355566/52246597-3540ec80-289b-11e9-9e28-09b368e8aca6.png)

**Comment by jaredkerim** [comment]
@arthuredelstein Thanks for finding this!

We need to add the [https://docs.djangoproject.com/en/2.1/ref/templates/builtins/#linebreaks](linebreaks template filter) to the [https://github.com/mozilla/experimenter/blob/master/app/experimenter/templates/experiments/section_branches.html#L20](description in the template)
