### ISSUE TITLE
Are these old "Live" studies really live, or ready to marked Completed?

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#876]
Pinging Matt Grimes and Jared K(owners of these studies) to see if these studies are truly still live.  I suspect the Pioneer one may be - but the other 2 I suspect the other 2 are not still running.

https://experimenter.services.mozilla.com/experiments/pioneer-enrollment-study/ - may still be live and the way we know if people are in Pioneer.

https://experimenter.services.mozilla.com/experiments/56-satisfaction-1406537/

https://experimenter.services.mozilla.com/experiments/pref-flip-activity-stream-60-release-pocket-spocs-holdback-1456585/

**Comment by jaredkerim** [comment]
Closing this per @shell1
