### ISSUE TITLE
The "Branch Size" value can be wrongly set to "0" if the total sum of the remaining branches is "100"

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/experimenter#877]
**[Affected versions]:**
- Firefox Release 65.0 and above
- Chrome 72.0.3626.81

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile created.
- Have an experiment created on the "https://experimenter-app.dev.mozaws.net/" website with a minimum of two branches.
- You are logged with your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter-app.dev.mozaws.net/".
2. Open the experiment from prerequisites and click the "Edit" button from the "Branches" section.
3. Go to the "Control Branch" section and change the value from the "Branch Size" field to "0".
4. Go to the "Branch 1" section and change the value from the "Branch Size" field to "100".
5. Click the "Save Draft" button from the bottom part of the page and observe the behavior.

**[Expected result]:**
- An error message is displayed, considering the fact that the branch value could not be zero.

**[Actual result]:**
- The "Population" section is saved.

**[Notes]:**
- This issue is also reproducible if we have more than two branches if the size of all branches is equal with 100.
- Also, the Normandy receipt could not be created using two branches with "100" and "0" ratios: 
![image](https://user-images.githubusercontent.com/31243259/52284122-810f9680-296c-11e9-9f6a-06fd7f036fb5.png)

- Attached is a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/52283621-799bbd80-296b-11e9-9dc0-c8b99632a2cd.gif)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible on the "https://experimenter.stage.mozaws.net/" website after the (v2.27.0) deployment.
Tested on Windows 10x64, MacOS 10.14 and Ubuntu 16.04 x64.
