### ISSUE TITLE
[Enhancement] Experiment name should be displayed as tab name to easily differentiate multiple opened experiments

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/experimenter#878]
**[Affected versions]:**
- Firefox Release 65.0 and above
- Chrome 72.0.3626.81

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- There is at least one an experiment created on the "https://experimenter.stage.mozaws.net/" website.
- You are logged in your LDAP account.

**[Steps to reproduce]:**
1. Open the browser and navigate to "https://experimenter.stage.mozaws.net/".
2. Open one of the experiments in the same tab (left click) or in a new tab (middle click).
3. Observe the tab title in the tab strip.

**[Expected result]:**
- A part of the experiment name is displayed as tab name.

**[Actual result]:**
- No matter what experiment is opened, "Mozilla Experimenter" is only displayed as tab name

**[Notes]:**
- This enhancement will help to easily differentiate opened experiments by looking at the tab name. 
- Attached is a screenshot of the issue:

![image](https://user-images.githubusercontent.com/17258026/52285979-0779a780-2970-11e9-9116-cbca31720f3d.png)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and the Experiment's name is displayed as tab name. Verified on Experimenter stage "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website after the v2.28.0 stage deployment.
Tested on Windows 10x64, Mac 10.14 and Arch Linux 4.16.6 x64.
