### ISSUE TITLE
There is no validation on the "Risks" field even if the "Yes" radio button is checked 

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/experimenter#883]
**[Affected versions]:**
- Firefox Release 65.0 and above
- Chrome 72.0.3626.81

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an experiment created on the "https://experimenter-app.dev.mozaws.net/" website.
- You are logged with your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter-app.dev.mozaws.net/".
2. Open the experiment from prerequisites and click the "Edit" button from the "Risks" section.
3. Delete the placeholder text from the "Risk" input field.
4. Click the "Save Draft and Finish" button and observe the behavior.

**[Expected result]:**
- An error message is displayed.

**[Actual result]:**
- The experiment is successfully saved.

**[Notes]:**
- This issue is not reproducible with the "Technical Risks Description" field.
- It seems that this issue is a regression caused by bug #829.
- Attached is a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/52355853-cf3f9b00-2a3b-11e9-9e23-c50ee825848d.gif)

**Comment by tiftran** [comment]
Closing as behaviour for required fields is planned to change
