### ISSUE TITLE
API data for `ios-notification-opt-in-prompt` experiment is incorrect

### ISSUE THREAD

**Issue by danielkberry** [mozilla/experimenter#8858]
The API is reporting `"isEnrollmentPaused":false` for this experiment, while enrollment is indeed paused. The pause was made on May 3rd and is correctly reflected in Experimenter's DB (I checked the admin panel which shows that `is_paused` flips to true when enrollment was paused).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3506)

**Comment by jaredlockhart** [comment]
Yep this is a bug, right here:

https://github.com/mozilla/experimenter/blob/5a3720681145ee74e2b087ad87e46c3967d80f87/experimenter/experimenter/nimbus-ui/src/components/Summary/index.tsx#L64-L71

What happened was

1) Enrollment is ended, is_paused is True in the db
2) Someone requests end experiment
3) Someone cancels end experiment request
4) is_paused is set back to False from the lines above

We should only set isEnrollmentPaused to `false` from the frontend when canceling a pause review, not an end review.

**Comment by jaredlockhart** [comment]
Bonus points:  We could write a data migration to detect cases where we erroneously set `is_paused` to `True` while ending an experiment after it was previously set to `True` and set it back to `True`.
