### ISSUE TITLE
Canceling a change request left the visual experimenter state in "enrollment paused" but the admin was NOT paused

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#8879]
We had ended [enrollment on the redesign experiment ](https://experimenter.services.mozilla.com/nimbus/release-android-onboarding-redesign/summary) on May 24 - and it was reflected as enrollment-paused = true.  But now remote settings keeps trying to force it back to enrollment-paused = false.  https://github.com/mozilla-mobile/firefox-android/pull/2226/files is the PR.  
<img width="416" alt="image" src="https://github.com/mozilla/experimenter/assets/8192232/53fa2be1-069e-455a-9541-40c50a7133a0">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3522)

we are seeing it as NOT paused in experimenter.  

realized that Shell went to "end" and realized it was an accident and "canceled" and at that point Enrollment paused got unset in experimenter admin and then forced the firsturn experiment.config to set to false. =\

**Comment by shell1** [comment]
@jhugman

**Comment by shell1** [comment]
we had an issue creating a new experiment config file - a state was improperly changed in an autogenerated pull request picking up something from over a day ago.   We had ended enrollent on the redsign experiment - and it was reflected as enrollment-paused = true.  So it is sending out of sync information every half hour.

**Comment by mostlygeek** [comment]
Do you have any logs from the server side?  

What I'd be looking for is: 

- what endpoint URL is experimenter writing to? 
- what HTTP status code is getting returned? 
- when you pull the collection data directly from the remote-settings origin server, is it what you expect?  
  - `curl https://prod.remote-settings.prod.webservices.mozgcp.net/v1/buckets/main/collections/nimbus-desktop-experiments/records | jq . | less`
  - this bypasses the CDN so there is no caching

**Comment by mikewilli** [comment]
This looks very similar to [another issue](https://github.com/mozilla/experimenter/issues/8858) that @eliserichards is working on. @shell1 does the explanation of the bug over there explain the behavior you're seeing or does it seem like a different issue?

**Comment by shell1** [comment]
see comment above
