### ISSUE TITLE
The branch names cannot be reused on other experiments

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/experimenter#890]
**[Affected versions]:**
- Firefox Release 65.0 and above
- Chrome 72.0.3626.81

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an experiment created on the "https://experimenter.stage.mozaws.net" website.
- You are logged with your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net".
2. Click the "Create Experiment" button and fill all the fields from the "Overview" page.
3. Click the "Save Draft and Continue" button and name the branches in the same way as in the experiment from prerequisites.
4. Complete the rest of the fields from the "Population" page and click the "Save Draft and Continue" button.
5. Observe the behavior.

**[Expected result]:**
- The page is successfully saved.

**[Actual result]:**
- The "All branches must have a unique name" error is displayed.

**[Notes]:**
- This issue is not reproducible on Normandy, where different experiments can have the same branch name.
- Also, I have observed that on the Experimenter prod website the same branch name is present in multiple experiments.
- Attached is a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/52416448-45063e00-2af2-11e9-8e26-24ea9477cde2.gif)

**Comment by jaredkerim** [comment]
I accidentally opened a duplicate ticket for this: https://github.com/mozilla/experimenter/issues/908

I have deployed it to stage as v2.22.5 can you please verify that it's fixed there and I will push that to prod.

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible on the https://experimenter.stage.mozaws.net/ website (v2.22.5) of Experimenter.
Considering this I will close this issue and mark it as verified fixed.
