### ISSUE TITLE
Add input field for QA testplan URL

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#891]
It may be nice to add an optional input field to the URL of a QA test plan so that QA folk can quickly test the experiment.

I was recently asked to look at a study and I had to find the study owner's email, email them, and ask them for the link.

**Comment by shell1** [comment]
Jared just added a new optional input field for "test instructions".   That wasn't there initially - so the first studies coming through - but is there now for all the next studies coming.

The guidance is "If additional QA is required, provide a plan (or links to them) for testing each branch of this study".

An optional field for Test Builds was added too.  "If applicable, link to any test builds / staging information".
