### ISSUE TITLE
Disable release date field if not mobile

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#8933]
We should only let users pick a release date if it could be first run – so this should only be allowed for mobile.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3553)

**Comment by eliserichards** [comment]
Confirmed with shell that we should do the following:
* Don't _hide_ the release date field if not first run, just disable it
* Hide it with the first run checkbox if not mobile
* Rename the field to "First Run Release Date"
* Move the field down with the first run checkbox
