### ISSUE TITLE
Is there a way to extend the stop date on the WebRender study to Jan 31 2020?

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#894]
For this study: https://experimenter.services.mozilla.com/experiments/prefflip-webrender-v1-3-1492568/ is there any way to change the end date to Jan 31 2020?  They want to "let this ride".

not sure what the "admin" editing rights could be - but this is either blocked by https://github.com/mozilla/experimenter/issues/874 or could potentially be the type of thing that should just be done through admin console.  which would just be blocked on giving Shell rights to do that.

**Comment by jaredkerim** [comment]
We should find a more effective solution to this, maybe users can edit the duration while the experiment is live?

**Comment by shell1** [comment]
fixed
