### ISSUE TITLE
FAQ link for rollout bucket warning is 404

### ISSUE THREAD

**Issue by Mardak** [mozilla/experimenter#8943]
https://github.com/mozilla/experimenter/blob/daa44fb1d909c6d6cf00bc49ff8eec71167d1bac/experimenter/experimenter/nimbus-ui/src/lib/constants.ts#L67-L68
was added for #8566 with #8571

But https://experimenter.info/faq/Rollouts-and-experiments#question-2 is 404 maybe because #8239 was fixed?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3560)

**Comment by eliserichards** [comment]
Good catch @Mardak !! The URL should be https://experimenter.info/rollouts-and-experiments#question-2
