### ISSUE TITLE
Release date field should only appear for mobile first run experiments

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#8946]
The release date field only has meaning when used with a mobile first run experiment whose release date will be different than its launch date.  We should hide this field altogether for cases where it shouldn't be used.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3562)

**Comment by eliserichards** [comment]
There's already a ticket for this -- #8933
