### ISSUE TITLE
Use 'dashboard_url' if it's set for live dashboard link

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#897]
Right now we only attempt to link directly to test tube with the slug, but if the experimenter slug doesn't match the normandy slug it'll link to a non existent dashboard.  Until we can ensure the slugs are in sync, we can use the 'dashboard_url' model field to just set a link for existing live studies.

**Comment by peterbe** [comment]
I wouldn't mind working on this but I think it's a grander and moving target. The URL to test tubes is assumed based on the `slug`. We can either, in run-time Django or in a celery worker, do a `HEAD http://testtubes.com/{slug}`. 
Whatever we do, I suspect we need to redo it when we switch to Grafana. Because of this I'd be eager to not jump into coding just yet. 

Do you have an existing formed plan about doing these kinds of checks? 

Personally, I think one should avoid state and celery as much as possible if there a simpler solution. So I'd favor a solution like this:

```python
def view_experiment(request, slug):
    ...
    
    if condition_for_there_to_possible_exist_a_telemetry_dashboard:
        cache_key = f'testtube-{slug}'
        test_tube_url = cache.get(cache_key)
        if test_tube_url is None:
            try: 
                test_tube_url = f'https://testtubes.herokuapp.com/{slug}'
                requests.head(test_tube_url, timeout=3).raise_for_status()
            except HTTPError:
                test_tube_url = ''
            cache.set(cache_key, test_tube_url, 60 * 60)
        context['test_tube_url'] = test_tube_url
    
    ...
    render('experiment.html', context)
```

**Comment by peterbe** [comment]
It brings to mind something else...

On the top of the page we have a bunch of bugzilla links. It would be awesome if they were a bit more descriptive to saving having to click on them just to see their status and their summary. 

On [crash-stats](https://crash-stats.mozilla.com/search/?product=Firefox&date=%3E%3D2019-02-19T18%3A07%3A00.000Z&date=%3C2019-02-26T18%3A07%3A00.000Z&_facets=signature&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature) for each displayed bugzilla ID there's a on-mouse-over tooltip that displays the bug title and its status. 

Do we have any such plans? If so, I think it might affect how we pre-emptively check bugzilla AND testtubes.

**Comment by shell1** [comment]
until we get the unified slugs, in the model method that gets the testtube URL we can use this field "external dashboard URL" in model from Admin to get to the right place.

**Comment by jaredkerim** [comment]
Actually I'm going to scrap this idea altogether.  If we do https://github.com/mozilla/experimenter/issues/582 and store it on the model, then we can manually backfill normandy slugs for past studies, and then auto generate the correct test tube or grafana dashboard using that, instead of doing that for the full URL using this ticket.
