### ISSUE TITLE
Allow null values in Overview Wizard when creating the Draft

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#901]
History: The goal is to be able to start and save the draft before you know all the answers - capturing information you have as you go.  Today the validation on each section requires putting in dummy information (if you don't yet know the answers to the most critical fields) - in order to pass section by section validation on Required information.   

Ticket work: Please make it so in the "Overview Wizard" there is a way to leave the required "date" field and the "Proposed Experiment Duration (days)" field blank or "null" and still "save" the data that is there.    

Not sure if this should be part of this bug or bug #900:   Please make any Null required fields Red in the Wizard mode.  

in Bug #900 we want to throw a validation error if required fields are left empty when they click "ready for sign-offs".  It would be nice if they could go into edit mode and easily see the "red" fields.  User experience works if null fields are only "red" when they fail validation at "ready to ship" - or if they are "red from the first save that they were blank".    Putting here as not sure if that is easiest done as part of this issue or the final validation.

**Comment by shell1** [comment]
this actually happens at the "ready to ship" stage - which is fine.

**Comment by jaredkerim** [comment]
So for this we'll need to

1) Make the following fields optional
- proposed_start_date
- proposed_duration

2) Add a new method 'completed_timeline' that checks that those values are not None

3) Change `section_complete=True` to `section_complete=experiment.completed_timeline` here https://github.com/mozilla/experimenter/blob/master/app/experimenter/templates/experiments/detail_base.html#L57
