### ISSUE TITLE
Hide enrollment duration for rollouts

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#9027]
Because we disabled the ability to pause rollouts, the enrollment duration field has no meaning and so we should hide this field altogether for rollouts.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3635)

**Comment by tj-26** [comment]
Hi Im interested to work on this task. It would be great to be assigned to this! Thanks

**Comment by eliserichards** [comment]
I just touched base with @shell1, and I think that we would like to have the field greyed out (unclickable) instead of totally hidden
