### ISSUE TITLE
Create a dummy test app for Cirrus integration testing

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#9040]
Let's add a tiny dummy node/typescript webapp in the root of the repo that we can use as a test bed for Cirrus in integration tests.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3641)

**Comment by data-sync-user** [comment]
➤ Sundus Mazhar commented:

Yashika Khurana can this task be closed?
