### ISSUE TITLE
Kinto does not accept float values

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#9082]
Here on stage we see that kinto will reject a record that includes a float value:

https://mozilla.sentry.io/issues/4264507499/?project=6377194&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

We do not currently validate that feature values do not contain any float values, and so Experimenter will allow a float value but then publishing to kinto will fail and break.  We should validate that feature values never contain floats.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3661)

**Comment by brennie** [comment]
Fixed in #9091
