### ISSUE TITLE
Add Field for the Normandy Recipe ID Number

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#910]
Adding a field to enter the Normandy Recipe number makes connecting from the Experiment to the Normandy JSON much simpler.

Having this number makes it simpler for admins to move between Experimenter and Normandy.

This would be editing after it is in "Ready to Ship" state - so may be blocked on #874

**Comment by mythmon** [comment]
Experiments don't always have a one-to-one relationship with Normandy recipes. Some experiments may not need any recipes at all, and some might have several. We may want to accommodate that in Experimenter.
