### ISSUE TITLE
Model changes for feature versioning

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#9109]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3647)

**Comment by brennie** [comment]
This was fixed in https://github.com/mozilla/experimenter/pull/9110

**Comment by data-sync-user** [comment]
➤ Barret Rennie commented:

Closed in https://github.com/mozilla/experimenter/pull/9110 ( https://github.com/mozilla/experimenter/pull/9110|smart-link )
