### ISSUE TITLE
Multifeature experiments that contain a large number of features cannot be launched

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#9122]
**[Prerequisites]:**

* Have a Nimbus multifeature experiment created with ~20 features.

**[Steps to reproduce]:**

1. Open the "Summary" page of the experiment.
1. Click the "Launch to Preview" button and observe the page.

**[Expected result]:**

* The "All set! Your experiment is in Preview mode and you can test it now." message is displayed.

**[Actual result]:**

* The "Sorry, an error occurred while submitting. Please try again." message is displayed.

**[Notes]:**

* This is most likely related to the "namespace" parameter character limit, as fewer feature configurations with longer names are needed to hit the limit (around 15).
* The character limit of the “namespace“ seems to be around 250 characters.
* This issue is also reproducible when attempting to launch without preview, the error appears after the launch is approved, but the configuration is not sent to RS.
* Attached a screenshot of the issue:

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-3683)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/39715">error_occured.png</a>

**Comment by jaredlockhart** [comment]
Interesting, let's set a limit on the max number of multi features, maybe 10 for now and we can adjust it later if we need to.

**Comment by data-sync-user** [comment]
➤ Patriciu Pop commented:

I’ve verified that the number of features has been limited to 20 and the experiment can be launched. Due to the limitation of the namespace this issue could still be encountered if the chosen features have long slug strings.

**Comment by data-sync-user** [comment]
➤ Barret Rennie commented:

We increased the size of the namespace field in the db so it shouldn't be an issue with 20 features
