### ISSUE TITLE
Validate an experiment can not be both required and excluded

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#9123]
We should validate in the review serializer that the same experiment can't be both required and excluded.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3684)

**Comment by brennie** [comment]
This is already completed in #9044

see test here: https://github.com/mozilla/experimenter/blob/a013d35fd5907834a0066c6e44400ddcd46b2745/experimenter/experimenter/experiments/tests/api/v5/test_serializers/test_nimbus_ready_for_review_serializer.py#L2382
