### ISSUE TITLE
Cirrus pytest command should be run in verbose mode

### ISSUE THREAD

**Issue by b4handjr** [mozilla/experimenter#9148]
Right now the cirrus pytest tests just show the test file name and a bunch of dots. We should run the suite in verbose mode so we can easier identify failing tests.

![image](https://github.com/mozilla/experimenter/assets/5751892/4dea0bb9-2465-4f8e-a6dd-ece8bcb7ebaa)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3705)

**Comment by sudhirVoid** [comment]
I tried to access Jira but unable to access that too.  How can I do that.  If I need to know some more info for this issue to solve. I am new here so.

**Comment by jrbenny35** [comment]
> I tried to access Jira but unable to access that too. How can I do that. If I need to know some more info for this issue to solve. I am new here so.

Hello @sudhirVoid , welcome. The JIRA task is just a copy of what I wrote here. If you have any questions you can post them here, on this issue. Thanks!

**Comment by brennie** [comment]
Re-opened. #10084 did not fix this. See-also #10174.
