### ISSUE TITLE
Send emails to console in dev mode

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#915]
Instead of configuring an SMTP server, when sending emails, during local dev, we should make it possible to set the [`console.EmailBackend`](https://docs.djangoproject.com/en/2.1/topics/email/#console-backend) backend.

**Comment by peterbe** [comment]
There should be a GitHub issue label for Developer Experience (DX).

**Comment by jaredkerim** [comment]
@peterbe it does do that:

https://github.com/mozilla/experimenter/blob/master/docker-compose.yml#L61-L69

https://github.com/mozilla/experimenter/blob/master/.env.sample#L18

<img width="623" alt="screenshot 2019-02-12 17 57 36" src="https://user-images.githubusercontent.com/119884/52673783-b299dc00-2eef-11e9-996c-66fe3fea8cfb.png">

**Comment by peterbe** [comment]
That's different. That's actually sending it on SMTP. Instead there are better ways in Django. Using [`console.EmailBackend`](https://docs.djangoproject.com/en/2.1/topics/email/#console-backend) means you don't actually send the emails. And it has other benefits around unit testing.

**Comment by jaredkerim** [comment]
Closing as a duplicate of https://github.com/mozilla/experimenter/issues/948

**Comment by peterbe** [comment]
Wow! Issue/bug duplicates happen. But this time from the same (stupid) user! :)
