### ISSUE TITLE
N+1 Query

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#9202]
Sentry Issue: [EXPERIMENTER-PROD-HM](https://mozilla.sentry.io/issues/4360065394/?referrer=jira_integration)
| **Offending Spans** | db - SELECT "experiments_nimbusfeatureconfig"."...

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-3731)

**Comment by brennie** [comment]
This is due to NimbusVersionedSchema queries not being prefetched correctly in the graphql API.
