### ISSUE TITLE
N+1 Query

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#9203]
Sentry Issue: [EXPERIMENTER-PROD-HK](https://mozilla.sentry.io/issues/4359963523/?referrer=jira_integration)
| **Offending Spans** | db - SELECT "experiments_nimbusversionedschema"...

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-3732)

**Comment by brennie** [comment]
I think this is a dupe of #9202 but I'm not sure. They are both due to NimbusVersionedSchema queries not being prefetched in the API,

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/issues/9202
