### ISSUE TITLE
Localize date/time stamps to local users TZ

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#922]
Right now we store timestamps in the servers timezone and display them as such in the UI.  We should store them in GMT and then localize the timestamps to the clients timezone when we render a page.

**Comment by shell1** [comment]
while valid - this isn't stopping anything from working with the flow that we have today.  For our internal use of the tool - we are OK with this.  A few folks noticed, but it never stopped it from working.  will consider if/when this becomes a blocking problem.
