### ISSUE TITLE
Gain Amount - Add new fields in Takeaways section

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#9231]
Expose the following fields in Takeaways section -  “Gain Amount”.  

"Gain Amount" should be an open text field - so we can see how these wins get measured.  But I suspect it will be a sentence like “.5% gain in retention” or “.5% gain in days of use”..

!image-20230203-203812.png|width=1130,height=281!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3738)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/40653">image-20230203-203812.png</a>

**Comment by eliserichards** [comment]
> can we change "promising metric gain" to "statistically significant DaU gain"... wanted it to be specific for ONLY the gains we are sharing around DaU this year.
> we would not want the database field to include DaU in the name ... just the visual wording.
