### ISSUE TITLE
generated experiment config file not matching experimenter - enrolling when should not be

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#9248]
https://mozilla.slack.com/archives/CANCHH6R1/p1691614027132909 - It seems like the experiment.config being generated for first run experiments is not always matching the changes in experimenter on Android.

This experiment is enrolling when it should not be.  https://experimenter.services.mozilla.com/nimbus/lifestyles-images-onboarding-experiment-v3/summary
live monitoring: https://mozilla.cloud.looker.com/dashboards/216?Experiment=lifestyles-images-onboarding-experiment-v3&Time+Range+%5BUTC%5D=28+day
experiment launched in 114 on June 6 - enrollment ended with 115 on July 4 (when the firstrun change shipped with 115) - experiment ended with 116 on Aug 1 (when the firstrun change shipped to users with 116).  We would expect some changes the week before each of those dates (due to the pre-release to 5%).

there is another first run android experiment that doesn't seem to have ended enrollment when it was set to when Android 116 went out Aug 1.   admin tool and experimenter say that enrollment is paused though.
https://experimenter.services.mozilla.com/nimbus/android-re-engagement-notifications-timing-v2/summary
https://mozilla.cloud.looker.com/dashboards/216?Experiment=android-re-engagement-notifications-timing-v2&Time+Range+%5BUTC%5D=28+day

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3751)

**Comment by eliserichards** [comment]
Just to confirm I'm reading this correctly, there should be NO enrollments after July 4?

**Comment by shell1** [comment]
yes, for the Lifestyles experiment there should have been no enrollments after July 4th and the experiment should have ended and started unenrolling on Aug 1.

for the re-engagement notifications, there should have been no new enrollments after Aug 1.  

the changes were requested days sooner for these - because of the first run nature - but July 4th and Aug 1 are the closest release dates after the changes where we should have started seeing big changes.

**Comment by eliserichards** [comment]
I'm splitting the second one out into it's own issue ^

**Comment by eliserichards** [comment]
Looking at the APKs for v115, 115.0.1, 115.2.1, and 116, all of them have `isEnrollmentPaused: true`, as we expected. 

The targeting also seems correct: 
```
((is_already_enrolled) || ((isFirstRun == 'true') && (app_version|versionCompare('114.!') >= 0) && (language in ['en'])))
```

**Comment by shell1** [comment]
so - after amazing teamwork and swarming... it looks like the 250K users a day are coming in from 114.2.  So we have started a data incident and are likely dealing with bots somewhere doing bad things and flooding irrelevant data at us.
