### ISSUE TITLE
Migrate schemas make commands to docker

### ISSUE THREAD

**Issue by mikewilli** [mozilla/experimenter#9271]
Related to this ticket: https://github.com/mozilla/experimenter/pull/9157#discussion_r1291691246, but in general this follows the pattern used elsewhere in the repo and is safer practice.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3762)

**Comment by brennie** [comment]
Fixed in #9616
