### ISSUE TITLE
Code style fixes

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#930]
We have new contributors to the project (yay!) however I neglected to fully document the PR process so some commits missed running the `make check` suite which includes the auto formatter.  Here are the auto format changes so they don't accidentally sneak into other PRs.

**Comment by peterbe** [comment]
I would strongly recommend `therapist`. It's used in most repos in the team. It has many benefits:

1. Same config use for local devs and we'd use in CI. 
2. Devs can install it locally as a git pre-commit hook to prevent making PRs when the linting in CI will fail anyway. 
3. Can define linting rules for .js and .py files.

**Comment by peterbe** [comment]
Also, I would strongly recommend switching to 88 character line lengths. [normandy](https://github.com/mozilla/normandy/blob/master/pyproject.toml) uses 99. 

[88 is the default for `black`](https://github.com/ambv/black)

**Comment by peterbe** [comment]
By the way, [here's normandy's `.therapist.yml`](https://github.com/mozilla/normandy/blob/master/.therapist.yml)

**Comment by peterbe** [comment]
Moved my thoughts about therapist here: https://github.com/mozilla/experimenter/issues/945
