### ISSUE TITLE
Add automated dependency management

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/experimenter#932]
For python projects we use [dependabot](https://dependabot.com/).  For docker containers we use [renovatebot](https://renovatebot.com/). 

[Normandy's renovate.json](https://github.com/mozilla/normandy/blob/master/renovate.json)  may be a good starting point. 

Previous work and discussions:  #128, #488, #601, #921.

**Comment by peterbe** [comment]
To add Dependabot I followed the instructions on https://mana.mozilla.org/wiki/display/SVCOPS/Application+Dependency+Management and clicked to register it for mozilla/experimenter. 

But I noticed the strong recommendation that "Make sure you have branch protection enabled on master and other deployment branches, so the bot cannot write to deploy branches." which we don't have enabled on experimenter. 

@jaredkerim Can you review: https://github.com/mozilla/experimenter/settings/branch_protection_rules/new and set this up. We use `bors` on Normandy but here's how it's protected:

![screen shot 2019-02-28 at 15 49 36-fullpage](https://user-images.githubusercontent.com/26739/53597589-8ed1c980-3b70-11e9-90af-47ab4903c21a.png)

**Comment by peterbe** [comment]
I think we should...

* Require approvals
* Only signed commits
* Disable force-pushes (gets set by default)
* Require CI to pass

**Comment by peterbe** [comment]
I'm struggling to configure Dependabot because we don't have a `/requirements.txt` so I filed this: https://github.com/dependabot/feedback/issues/387

**Comment by peterbe** [comment]
[Enabled!](https://app.dependabot.com/accounts/mozilla/repos/71493337)

**Comment by jaredkerim** [comment]
@peterbe Thank you! I added the branch protection to master.  @mostlygeek Can you review and close this?

**Comment by jaredkerim** [comment]
@peterbe I think we still need to do something to get dependabot to support signed commits?  I tried enabling signed commit requirements and all the dependabot PRs were not signed.

**Comment by mostlygeek** [comment]
Looks like dependabot is running. If you guys are ok with it feel free to close this issue.

**Comment by jaredkerim** [comment]
@mostlygeek Looks like we still have to figure out how to handle the signed commits, let's keep it open until we come to a decision about how to handle that.

**Comment by jaredkerim** [comment]
I filed https://github.com/mozilla/experimenter/issues/1005 as followup.
