### ISSUE TITLE
Use pre-built version nimbus-cli to do FML transformations

### ISSUE THREAD

**Issue by jhugman** [mozilla/experimenter#9329]
Currently, getting from the FML manifest from app repository / converting it to the experimenter format is a little convoluted.

For new style app's:

- experimenter's Makefile curls the FML file from the app's repo.
- experimenter checks out `application-services`, installs Rust, and builds `nimbus-fml`.
- experimenter runs `nimbus-fml` to generate the final form that experimenter understands.

This is slow for experimenter to do at build.

For Firefox/Focus on mobile, a slightly older workflow:

- the app's buiid script converts FML to a `.experimenter.yaml` file
- the app developer checks this into the repo.
- experimenter's Makefile curls the .experimenter.yaml file from the repo.

This is mysterious for the app developer who has to check in this generated file.

This issue is to:
- experimenter's Makefile to install the nimbus-cli from a pre-built binary.
- use the nimbus-cli's FML command line to download and transform the FML straight from the app's repo.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3786)

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/pull/9331
