### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#9372]
Sentry Issue: [EXPERIMENTER-PROD-J1](https://mozilla.sentry.io/issues/4458994992/?referrer=jira_integration)

```
TypeError: 'NoneType' object is not iterable
(33 additional frame(s) were not displayed)
...
  File "experimenter/experiments/models.py", line 941, in get_changelogs_by_date
    change = get_formatted_change_object(
  File "experimenter/experiments/changelog_utils.py", line 127, in get_formatted_change_object
    values = list(data.filter(pk__in=old_value).values_list("name", flat=True))
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-3809)

**Comment by Avi-88** [comment]
Hi @yashika-khurana , I'd like to work on this issue could you please assign this to me, thanks

**Comment by yashikakhurana** [comment]
Assigned it to you, let me know if you need any help :)

**Comment by yashikakhurana** [comment]
I just fixed the issue
