### ISSUE TITLE
Feature warning not shown on branch page

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#9373]
When an experiment is created but no features have been selected, there is a warning that the user must select a feature:

<img width="482" alt="image" src="https://github.com/mozilla/experimenter/assets/119884/df0eb7a0-9e89-43d2-9bb8-2bbc24761bd9">

But we do not show it on the branch page when `show-errors` is enabled:

![image](https://github.com/mozilla/experimenter/assets/119884/f9b1d1c0-3cf3-4bef-91da-8b25ce4eff8a)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3810)

**Comment by data-sync-user** [comment]
➤ Barret Rennie commented:

Up for review.

**Comment by data-sync-user** [comment]
➤ Barret Rennie commented:

Patch is in the merge queue
