### ISSUE TITLE
Targeting for Android 8

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#9399]
I need targeting for a first-run mobile onboarding experiment for users on Android 8.0 and above.
There is already one there for Android 13 so it should be similar.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3773)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Here is the experiment brief https://docs.google.com/document/d/1wuyDtm4miBMOHJlL7RsO0symOmogs9AwiIij_Drccws/edit ( https://docs.google.com/document/d/1wuyDtm4miBMOHJlL7RsO0symOmogs9AwiIij_Drccws/edit|smart-link )

**Comment by eliserichards** [comment]
Fixed in #9400
