### ISSUE TITLE
Vendor FML files and use them to generate experimenter yaml files

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#9409]
We can use nimbus-cli to fetch the single-file FML files based on the apps listed in apps.yaml, and then generate experimenter.yaml files. This will also help with the FML-in-experimenter work.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3836)

**Comment by brennie** [comment]
Fixed in #9471
