### ISSUE TITLE
The "Experiment Bugzilla Ticket" button and notifications are displayed only after the page is refreshed 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#942]
**[Affected versions]:**
- Firefox Release 65.0.1 and above
- Chrome 72.0.3626.109

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an experiment "Ready for Sign-Off" on the "https://experimenter.stage.mozaws.net/" website.
- You are logged in your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites and click the "Ready for Sign-Off" button.
3. Observe the "Tickets" section under the experiment's title. 

**[Expected result]:**
- The "Experiment Bugzilla Ticket" is displayed in front of the "Data Science Bugzilla Ticket".
- The "An email was sent to.." and "A Bugzilla Ticket was created.." notifications are displayed above the tickets section.

**[Actual result]:**
- Only the existing tickets are displayed.

**[Notes]:**
- This issue is also reproducible for the "The Bugzilla Ticket was updated.." notifications when going forward with the experiment's states.
- This issue is not reproducible for the notifications displayed after the "Save Sign-Offs" button is clicked. The notifications are displayed right after the button is clicked.
- Also, the notifications are displayed correctly after you navigate on other sections of the page.
- Attached is a screen recording of the issue:
![nomessage](https://user-images.githubusercontent.com/40061643/52873783-82a14180-3158-11e9-86b0-b82c88a0d0a4.gif)

**Comment by Softvision-RemusDranca** [comment]
I have retested this issue in different scenarios and it seems that this issue is reproducible on all OSes, and it's also affecting more than the previously mentioned notifications. I will update this issue accordantly.

**Comment by shell1** [comment]
Thanks Remus!  This is an acceptable timing delay.  The experimenter bugzilla ticket is only used for managing turning the Normandy recipes on and off and for release management and QA tracking for what is coming in different releases.

The requester doesn't need to do anything with the experimenter bugzilla ticket at the point when they click "ready for sign-offs" - so this delay (while the ticket is created) is fine.  

There is a group of work down the road to improve the bugzilla integration (when to update - more bugzilla field editing).  Immediately available ticket when hitting that button still won't be a requirement.
