### ISSUE TITLE
Results page notice of default to exposure events

### ISSUE THREAD

**Issue by mikewilli** [mozilla/experimenter#9427]
Swap to exposures by default and put message about enrollments being deprecated

cc @danielkberry

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3843)

**Comment by danielkberry** [comment]
idk if "deprecated" is the right word. We just want exposures by default. We'll also want enrollments too. From a technical perspective, enrollments measure the Average Treatment Effect (ATE) and exposures measure the Local Average Treatment Effect (LATE). They're both useful, just measure different things. As we scale the program, we'll expect more experiments that move only exposures and not enrollments (stat sig LATE, but not ATE).

**Comment by mikewilli** [comment]
Good point. Perhaps better wording might be that "experiments without exposure event support" and "enrollments analysis as the default basis" are what are being deprecated, though both will continue to be computed. In any case, we can definitely figure out the appropriate wording when this is being implemented.
