### ISSUE TITLE
Use therapist for local dev and for CI

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#945]
Spawned from [this monologue](https://github.com/mozilla/experimenter/issues/930#issuecomment-463786208).

The goal is simple:

1. All linting (that *can* be automated) should be checked in CI. 
2. The same linting should be easy to run locally.
3. Everyone should use the same linting scripting.
4. Ideally, devs shouldn't create a PR if the lint is going to fail in CI.

**Comment by jaredkerim** [comment]
Right now all linting is specified in the makefile which is used locally and on CI in identical ways and so we can reproduce the same checks locally and remotely.  If our needs grow beyond that we can revisit this.
