### ISSUE TITLE
AnyForm.save is not an atomic transaction

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#946]
For example, [this `ExperimentStatusForm.save` method](https://github.com/mozilla/experimenter/blob/585c5779033332d1847aa1d88f478d0947a9d76a/app/experimenter/experiments/forms.py#L731-L758) isn't run as 1 transaction. 

I noticed because I was messing around inside one of them put in a `raise Exception('debug?!')` to see what was going on and it proceeded to make the save anyway. I'd expect all operations within should be 1 atomic transaction. If not, not only bugs but operational exceptions could cause data corruption.

**Comment by jaredkerim** [comment]
Closing this for now, we haven't seen any errors arise as a result of this, if a specific error occurs we will file a new ticket.
