### ISSUE TITLE
Change debouncing rules for feature linting

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#9479]
Consider varying [+debouncing for linting+](https://codemirror.net/docs/ref/#lint.linter%5Econfig.delay) (CodeMirror currently defaults to 750ms for their delay)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3872)

**Comment by jaredlockhart** [comment]
Let's leave this alone until we notice a reason to change it.
