### ISSUE TITLE
A system check should check that emails are set

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#950]
If you don't set things like `EMAIL_REVIEW`, `EMAIL_SHIP`, and `EMAIL_SENDER` you might be very baffled that emails aren't sent. And for production I dare to assume that these are mandatory for a functioning system. 

Instead stumbling on this in runtime or anything like that, we should use the Django system checks to check that these are set up.

**Comment by glasserc** [comment]
I think a really easy way to fix this would be to add sample emails to `.env.sample`.

**Comment by jaredkerim** [comment]
Closing this for https://github.com/mozilla/experimenter/issues/1340
