### ISSUE TITLE
Create advanced targeting for review checker (fakespot experiment)

### ISSUE THREAD

**Issue by meaou** [mozilla/experimenter#9500]
Hi, 
Can we please ask to create advanced targeting for the upcoming 119 review checker experiment: 

Targeting:
- EXCLUDE users that have the fakespot add-on installed - https://addons.mozilla.org/en-US/firefox/addon/fakespot-fake-reviews-amazon/
- EXCLUDE users that have browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features pref is false

Experiment link
https://experimenter.services.mozilla.com/nimbus/review-checker-first-beta-119/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3887)

**Comment by Mardak** [comment]
The pref value should be `true` indicating we _can_ show the review checker sidebar/recommendation.

**Comment by jaredlockhart** [comment]
Example of targeting add-ons:

https://github.com/mozilla/experimenter/blob/main/experimenter/experimenter/targeting/constants.py#L1029

**Comment by shell1** [comment]
we should include people with it true or exclude people with it set to false.  same thing.

**Comment by Mardak** [comment]
This has been merged, but it seems like it hasn't shown up in experimenter advanced targeting dropdown on prod or stage. Is there another step needed to deploy?
