### ISSUE TITLE
"find in page" returns incorrect results on Experimenter landing page due to drop down lists content being searchable

### ISSUE THREAD

**Issue by rkothari19** [mozilla/experimenter#951]
On the experimenter landing page https://experimenter.services.mozilla.com/?page=1, if I search for "pocket", it return 15 matches even though you cannot "see" them nor are they "highlighted" or get to them by clicking on the up/down arrows of the "find in page" toolbar. 

DHolbert helped me understand that the 15 matches were coming from the drop down lists "all projects", "all owners". I don't think the "find in page" should be searching through the drop down list contents.

**Comment by rkothari19** [comment]
This might be a Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1490974#c10

**Comment by dholbert** [comment]
It is indeed. It's unlikely that Experimenter can do anything to hack around this, I'll bet.  (Or if there is a hackaround, I'll bet it'd be terrible dark magic that might break accessibility or something.)

Probably best to close this issue, and just track this in the Firefox bug.

**Comment by peterbe** [comment]
I agree with @dholbert that this is a Firefox bug. If anything we should focus our attention on: https://github.com/mozilla/experimenter/issues/400
