### ISSUE TITLE
Bad redirect after logging in

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#953]
Steps to reproduce:

1) Fresh profile/cookies or something so that opening https://experimenter.services.mozilla.com/ redirects to https://auth.mozilla.auth0.com/login
2) Log in successfully

Expected result:
Be redirected back to https://experimenter.services.mozilla.com/

Actual result:
Be redirected to https://sso.mozilla.com/dashboard

**Comment by peterbe** [comment]
Note, if you already have a valid cookie with auth.mozilla.auth0.com and you don't need to stop there to type in your email + password, this won't happen.

**Comment by jaredkerim** [comment]
@peterbe That's weird, that sounds like an OpenIDC bug.  @jbuck Can you take a look at this and see if you can reproduce it?

**Comment by peterbe** [comment]
It's fitting that I think Delivery Console is suffering from the same "bug". It uses Auth0 entirely in client-side and correctly, passes a ["returnUrl"](https://github.com/mozilla/delivery-console/blob/0ace0300e4585965801e5b7b0368328f0673bdfa/src/components/auth/AuthButton.js#L66) when it triggers a redirect to auth0. It works if you already have a active cookie with auth0.com but if you have to the whole email + password (plus 2FA), when it redirects back to the app, it redirects to `/` instead of whatever the "returnUrl" was.

**Comment by peterbe** [comment]
So, it *could* be a configuration problem or an actual bug in Auth0.

**Comment by jaredkerim** [comment]
This configuration is managed by auth0 and ops, I don't see any evidence of this happening on any of our deployments now so I'm closing this, if it comes up again we can file a ticket against the ops team.
