### ISSUE TITLE
Update glean maxEvents value on the cirrus side

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#9534]
When setting up glean sdk on cirrus side, we set the maxEvents to 500, that means it waits on the client side to gather all 500 events and once it gets 500 then it sends the batch of events, we want to change the value to 1, so that we can see the immediate results. Lets set maxEvents value to 1

[https://mozilla.github.io/glean/book/reference/general/initializing.html#configuration](https://mozilla.github.io/glean/book/reference/general/initializing.html#configuration|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3907)

**Comment by yashikakhurana** [comment]
as discussed, we will change the value to `10` as `1` can be too rigorous, and also to set this value usig `.env` variable to try best value that works for the given application
