### ISSUE TITLE
Custom targeting for iPhone

### ISSUE THREAD

**Issue by dnarcese** [mozilla/experimenter#9564]
For the Fakespot 120 experiment, we need to be able to target only iPhone users (ie no iPad users). We can use the `deviceModel` field.

We will need 2 advanced targeting criteria with this iPhone users only:

1. iphone only + new users only
1. iphone only + existing (or not new) users only.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3944)

**Comment by data-sync-user** [comment]
➤ Shell Escalante commented:

Chris Peterson Daniela Arcese   the iOS experiment needs 2 advanced targeting criteria - right?  One for the experiment for new users and one for the existing users experiment.  

so advanced targeting would be:
-no iPad + new users only

-no iPad + not new users only

I didn’t want to edit the description before checking.

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

That’s correct. I had assumed “no iPad” and “new/existing user” checks could be coded separately and enabled independently, but it sounds like Nimbus will need to be configured for each of these combinations?

**Comment by data-sync-user** [comment]
➤ Shell Escalante commented:

Yes - Nimbus doesn’t have the ability to add together advanced targeting criteria.  that is a requested improvement -but for now the criteria need to be in one target.

**Comment by data-sync-user** [comment]
➤ James Hugman commented:

If we’re calling new users ‘people who have installed the app within the previous 7 days’, we can say something like:

  1. “new users only” is  days_since_install < 7
  2. “existing (or not new) users only” is days_since_install >= 7

**Comment by data-sync-user** [comment]
➤ Shell Escalante commented:

let isPhone = UIDevice.current.userInterfaceIdiom == .phone from Roux Buciu

**Comment by data-sync-user** [comment]
➤ Shell Escalante commented:

this will be resolved in https://mozilla-hub.atlassian.net/browse/EXP-3944 ( https://mozilla-hub.atlassian.net/browse/EXP-3944|smart-link )

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

The Nimbus PR was merged on 2023-10-27: https://github.com/mozilla/experimenter/pull/9642 ( https://github.com/mozilla/experimenter/pull/9642|smart-link )
