### ISSUE TITLE
Count header is wrong

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#962]
At the top of the page, on https://experimenter.services.mozilla.com/, it says "10 Experiments" which isn't right. The [10](https://github.com/mozilla/experimenter/blob/63a6c723901eb5f12a776f13936f8783f81051e8/app/experimenter/settings.py#L224) most probably comes from the pagination and the count of experiments in one *page*.

![screen shot 2019-02-20 at 09 28 29-fullpage](https://user-images.githubusercontent.com/26739/53098688-322c3a00-34f2-11e9-9e8a-727d4fd2b405.png)

**Comment by shell1** [comment]
dupe #567
