### ISSUE TITLE
Android for fakespot - early and later day user targeting

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#9640]
or the real fakespot stat sig review checker experiment (not the beta channel smoketest experiment) we want to add criteria for early days or not. This is so we can have 2 experiments and size for early users (fewer) and later (more).

Later days users: PROFILE28DAYS = "(currentDate|date - profileAgeCreated|date) / 86400000 >= 28"
Early Days user: PROFILELESSTHAN28DAYS = "(currentDate|date - profileAgeCreated|date) / 86400000 < 28"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3969)

**Comment by shell1** [comment]
PR up https://github.com/mozilla/experimenter/pull/9642

**Comment by cpeterso** [comment]
PR https://github.com/mozilla/experimenter/pull/9642 has been merged, so I think we can close this issue.
