### ISSUE TITLE
Create v5 endpoint for fetching FML errors

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#9644]
Make an endpoint that takes the feature configuration and returns the `Diagnostic`s. This may be using the experiment slug and feature id to look up app and versions, or it can be totally stateless and pass back the feature_id, app name and versions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3971)

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/issues/9478
