### ISSUE TITLE
Upgrade fontawesome

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#965]
We currently use Font Awesome Free 5.3.1 but 5.7.2 is the latest version.

One benefit of this upgrade is that we'd get [the new and latest Slack icon](https://github.com/mozilla/experimenter/pull/952).

It still hurts my soul to have 18.3MB worth of static files into the git repo. Espectially those tonnes of svgs that we know we don't use.

**Comment by pdehaan** [comment]
This is pretty interesting... I found where we host Font Awesome in our repo: https://github.com/mozilla/experimenter/tree/master/app/experimenter/static/lib/fontawesome

I also found https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome which mentions a few ways to customize **Font Awesome**:

> There are some wonderful online services which allows you to customize Font Awesome, like:
>
> - **Fort Awesome:** http://fortawesome.com (Seems to have "Font Awesome 5.2" and old Slack icon, and paid service?)
> - **Fontello:** http://fontello.com (seems to have "Font Awesome 4.7" and old Slack icon)
> - **IcoMoon:** http://icomoon.io/app/#/select (unknown Font Awesome version, old Slack icon)
> - **Fontastic:** http://fontastic.me (seems to have "Font Awesome 4.4" and old Slack icon)

But if we don't care about the exact Slack icon we use, it may be interesting to consider a custom icon bundle and save ourselves a lot of files in the repo (at the expense of needing to regenerate the icon bundle in the future if we wish to add new icons).

**Comment by pdehaan** [comment]
And a little bit of greppin' (and manual editing) tells me that this may be a semi-accurate list if current Font Awesome icon usage:

```sh
$ git grep -h "fas " *.html | sort | uniq
```

And it looks like we only have about 19 icons that we're currently using:

```
<span class="fas fa-archive"></span>
<span class="fas fa-ban"></span>
<span class="fas fa-chart-bar"></span>
<span class="fas fa-check-circle"></span>
<span class="fas fa-check-square"></span>
<span class="fas fa-check"></span>
<span class="fas fa-comment-alt"></span>
<span class="fas fa-edit"></span>
<span class="fas fa-exclamation"></span>
<span class="fas fa-exclamation"></span>
<span class="fas fa-info-circle"></span>
<span class="fas fa-link"></span>
<span class="fas fa-plus-circle"></span>
<span class="fas fa-plus"></span>
<span class="fas fa-save"></span>
<span class="fas fa-shipping-fast "></span>
<span class="fas fa-times"></span>
<span class="fas fa-undo"></span>
<span class="fas fa-user"></span>
```

**Comment by peterbe** [comment]
For what it's, I don't mind the total payload of the site being excessively heavy. Most users are on desktop browsers and are repeat visitors so browser caching works in their favor.

Ideally, I think the static stuff like jquery and font-awesome should NOT be checked into git but instead a build artifact. I.e. list the packages we need in a `package.json`, run `yarn` to make them available in `./node_modules/**` and Django then copies the stuff it needs and runs `./manage.py collectstatic` and those files that get copied (and minified etc.) are added to the docker image which CircleCI then ships to DockerHub (or whatever the equivalent tech is going to be). 

There are, though, a bunch of files inside https://github.com/mozilla/experimenter/tree/master/app/experimenter/static/lib/fontawesome that are never ever used. For one, we either use `fontawesome.js` or we use `fontawesome.min.js` but not the other.

**Comment by pdehaan** [comment]
Huge +1 to using some package manager (like npm) to manage the 3rd party libs, if possible. One more build step and tool needed, but would make the repo much leaner.
