### ISSUE TITLE
Remove Hydrobuild

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#9679]
We were lucky enough to be invited to a private beta for [Docker Hydrobuild](https://docs.docker.com/build/hydrobuild/) which we have used for the last few weeks in CI and locally.  After initial setup hiccups, we now have enough data in CI to see that it didn't improve our CI times enough to warrant continued use.  Let's remove it from our CI infrastructure for now.  We can re evaluate it in the future if we decide it's worth looking at again.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3995)

**Comment by brennie** [comment]
Closed in #9680
