### ISSUE TITLE
Capture Application Services version hash in Dockerfile

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#9687]
As part of the Dockerfiles for Experimenter and Cirrus, we [fetch Application Services](https://github.com/mozilla/experimenter/blob/main/experimenter/Dockerfile#L86).  However we presently fetch the latest `main` branch which may introduce breaking changes to Cirrus and Experimenter.  To prevent break changes appearing, let's hard code a commit hash as part of the reference here, and then we can increment that reference as part of PRs that will consume and adapt to changes in Application Services.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4003)

**Comment by brennie** [comment]
Fixed in #9690
