### ISSUE TITLE
Missed code auto formatting

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#972]
More changes have landed without the Python auto formatter being run, maybe we should set it up so that the Circle build fails if code is pushed without the formatter being run?  For now I'll just push this small change with the format fixes and we can revisit the topic if this continues to be an issue.

**Comment by mythmon** [comment]
In my opinion, any code formatting that isn't enforced by CI isn't a part of the project. I think you should definitely have CI block on code format and other linting issues if you want it to stay consistent. #945 is a good way to do that.

**Comment by jaredkerim** [comment]
@mythmon I agree, I will follow this up with #974
