### ISSUE TITLE
Locate templates with their apps

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#973]
At the moment, the templates are all in one folder. E.g. `experimenter/templates/experiments/`
Instead, templates should live within their app. Like we do with tests. I.e. we have `experimenter/experiments/tests/` and `experimenter/base/tests/` instead of `tests/experiments/` and `tests/base/` respectively.

**Comment by jaredkerim** [comment]
Not a bad idea but not critical, I'm gonna close this.
