### ISSUE TITLE
Can't pull reports

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#9757]
Shell is trying to get Sept and Oct numbers - but it keeps failing to run report.  eventually give me a 503

!image-20231108-190926.png|width=775,height=234!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4012)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/52765">image-20231108-190926.png</a>

**Comment by eliserichards** [comment]
The last successful pull of the reports was Sept 12

**Comment by data-sync-user** [comment]
➤ Elise Richards commented:

PR: https://github.com/mozilla/experimenter/pull/9761 ( https://github.com/mozilla/experimenter/pull/9761|smart-link )

**Comment by data-sync-user** [comment]
➤ Elise Richards commented:

The changelog prefetching wasn’t necessary, and it was taking a long time which caused nginx to kill it and throw a 502. Removing the prefetching and only looking at the changelogs when needed (for uncomputed start dates) fixes the issue.
