### ISSUE TITLE
Indicate that results are not available for rollouts

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#9766]
Presently we disable the results button for rollouts but the help text says `Experiment analysis not ready yet.`  We should change that text to something like `Analysis results are not available for rollouts.` for rollouts so it's clear that no results will ever appear.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4037)

**Comment by tj-26** [comment]
Please assign this one to me. Thanks

**Comment by nox1134** [comment]
Hi everyone! If no one is working on this issue, I'd like to take up this issue and work on it.
Could you please assign the issue to me?
