### ISSUE TITLE
Dont fetch the world every time

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#9781]
Right now, `manifest-tool fetch`will always attempt to fetch everything, even things that have not been updated since its last fetch, because it doesnt know what has or has not been fetched. We should keep an index mapping ref names to refs and versions so we can compare new fetches against that cache and prevent extra fetches.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4041)

**Comment by brennie** [comment]
Fixed in #9785
