### ISSUE TITLE
Impossible to specify repeating-decimal branch fractions

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#981]
I would like a study to have three equal-sized branches. This is impossible to specify; Experimenter complains that the sum isn't 100%.

Using the `weightedVariations` model that the Shield Study Add-on Utils use could be one option: https://github.com/mozilla/shield-studies-addon-utils/blob/master/examples/small-study/src/studySetup.js#L70-L84

**Comment by jaredkerim** [comment]
@tdsmith Right now the best you can do is 34/33/33.  We'll have to revisit this in the future to find a more 'correct' solution.

**Comment by mythmon** [comment]
Note that the Normandy machinery that powers this uses ratio weights, which can deal with any rational branch rates (note that 1/3 is actually rational, since it is a ratio). We can manually manipulate things to have the desired branches, even if Experimenter doesn't allow that to be represented.

**Comment by tdsmith** [comment]
Good catch; I don't anticipate needing 1/π of my users in a branch.

**Comment by jaredlockhart** [comment]
This will be covered by https://github.com/mozilla/experimenter/issues/1932
