### ISSUE TITLE
No protection for "bad" responses from Bugzilla

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#982]
See these lines: https://github.com/mozilla/experimenter/blob/57f776d6df2d2e23797ca0018e15f92354f0189f/app/experimenter/experiments/bugzilla.py#L48-L49

If the response from bugzilla is 400 or 403 (misconfigured API key) that will go unnoticed. I.e. no exception and no Sentry log. 

We should at least use `response.raise_for_status()`.

**Comment by peterbe** [comment]
By the way, we shouldn't do

```python
response = requests.post(url, data)
return json.loads(response.content)
```

Instead, we should do:

```python
response = requests.post(url, data)
return response.json()
```

[The one in `requests`](https://github.com/kennethreitz/requests/blob/a345b776fb2cf67d1a1810349e71fd60a83f53eb/requests/models.py#L873-L897) respects the charset and does validation on the response JSON byte string.

**Comment by jaredkerim** [comment]
This is fixed now.
